### ISSUE TITLE
Better state restoration

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#100]
We should be able to restore views/settings better

**Comment by frederoni** [comment]
I took a stab at this but my conclusion is that we _shouldn't_ implement support for state restoration.

Consider this use case:
1. User starts navigating,
2. User sends the app to the background,
3. State is saved in `encodeRestorableState` (this is the only trigger where we can use the coder),
4. Progress and steps are saved,
5. User continues driving/walking around changing the route progress and perhaps even triggers a reroute, 
6. User goes back into the app and triggers a state restoration which brings them back to step 4.

It's very unlikely that this is what the user wants.
