### ISSUE TITLE
Warn developers if they are using an outdated version

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1003]
Similar to the Mapbox Maps SDK, we should warn developers who are not on the latest version.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
It’d be nice to pair #1007 with a reference in the readme to [this option](https://github.com/Carthage/Carthage#optionally-add-build-phase-to-warn-about-outdated-dependencies) for Carthage users. That’ll add a build warning, which is still gentle but won’t get lost in the noise of the console.
