### ISSUE TITLE
Load resources from Bundle

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#1017]
**Mapbox Navigation SDK version: 0.12.1**

Hello, I've been trying to link and use the Mapbox Navigation for iOS statically but have come roadblock. I've managed to statically link all of the frameworks and include them in my app, however, the app crashes when starting a route due to missing resources. Currently, 10 frameworks are required to use this project.

Is it possible to load the resources from a bundle the same way as it's done on the [Mapbox-iOS-SDK](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/NSBundle%2BMGLAdditions.m)?

This would apply to:
MapboxNavigation (Uses resources and Localizable strings)
MapboxMobileEvents (Uses Localizable strings)
MapboxCoreNavigation (Uses Localizable strings)

The other libraries don't have bundled resources in them, so it is not an issue.

**Comment by 1ec5** [comment]
To clarify, you’re asking for this code to [look for a resource bundle](https://github.com/mapbox/mapbox-gl-native/blob/b3d3ab0e31d251cf39dfa78dfbc0661b8819a8ab/platform/darwin/src/NSBundle%2BMGLAdditions.m#L10-L20) if the SDK isn’t an embedded dynamic framework, correct?

https://github.com/mapbox/mapbox-navigation-ios/blob/321af7a1f095a8b23e8b1550a865035f8ba07fb3/MapboxNavigation/Bundle.swift#L5-L7

This should be feasible, but it’ll look a little different than the map SDK’s implementation. When you install the SDK as a static framework using CocoaPods, CocoaPods creates a resource bundle for the [resources](https://guides.cocoapods.org/syntax/podspec.html#resources) declared in the library’s podspec. I haven’t looked into what this bundle looks like, but the path to the bundle would be defined by CocoaPods in any case.

**Comment by Sealos** [comment]
Correct.

We would like to be able to build this project using Carthage statically, and that either requires for the resources to be inlined, or to be able to be loaded from a bundle which should be copied to the main bundle (Current Mapbox iOS SDK solution).

**Comment by frederoni** [comment]
I think you'd have to merge libraries to get below Apple’s recommended threshold of 400ms to match the app start-up animation and less than 6 dylibs. We will eventually replace AWSCore and AWSPolly with another speech library and SDWebImage would be fairly easy to replace but that alone won't get us below 6 external frameworks.

I ran some numbers:
<details>

```markdown
### Cold Start Dynamic      
Total pre-main time: 959.69 milliseconds (100.0%)
    dylib loading time: 521.13 milliseconds (54.3%)
    rebase/binding time: 140.15 milliseconds (14.6%)
    ObjC setup time:  84.44 milliseconds (8.7%)
    initializer time: 213.90 milliseconds (22.2%)
    slowest intializers :
    libSystem.B.dylib :   6.23 milliseconds (0.6%)
    Mapbox : 251.73 milliseconds (26.2%)

### Warm Start Dynamic 
Total pre-main time: 113.72 milliseconds (100.0%)
         dylib loading time:  41.26 milliseconds (36.2%)
        rebase/binding time:   5.15 milliseconds (4.5%)
            ObjC setup time:   8.24 milliseconds (7.2%)
           initializer time:  58.97 milliseconds (51.8%)
           slowest intializers :
             libSystem.B.dylib :   3.08 milliseconds (2.7%)
   libBacktraceRecording.dylib :   3.21 milliseconds (2.8%)
    libMainThreadChecker.dylib :   8.27 milliseconds (7.2%)
                        Mapbox :  81.59 milliseconds (71.7%)

### Cold Start Static
Total pre-main time: 745.04 milliseconds (100.0%)
         dylib loading time: 559.96 milliseconds (75.1%)
        rebase/binding time:  41.66 milliseconds (5.5%)
            ObjC setup time:  33.86 milliseconds (4.5%)
           initializer time: 109.41 milliseconds (14.6%)
           slowest intializers :
             libSystem.B.dylib :   8.95 milliseconds (1.2%)
                        Mapbox : 134.69 milliseconds (18.0%)

### Warm Start Static
Total pre-main time: 122.33 milliseconds (100.0%)
         dylib loading time:  42.17 milliseconds (34.4%)
        rebase/binding time:  11.35 milliseconds (9.2%)
            ObjC setup time:  10.63 milliseconds (8.6%)
           initializer time:  58.07 milliseconds (47.4%)
           slowest intializers :
             libSystem.B.dylib :   3.56 milliseconds (2.9%)
   libBacktraceRecording.dylib :   3.60 milliseconds (2.9%)
    libMainThreadChecker.dylib :   9.60 milliseconds (7.8%)
                        Mapbox :  74.65 milliseconds (61.0%)
```

</details>

The static version here is just using the static version of the iOS Maps SDK but it indicates that support for static libraries alone is not sufficient. Warm start is within the threshold for both static and dynamic but cold start is quite far away.

I'd like to avoid the overhead of maintaining static releases for all dependencies but we could certainly make it easier to build static frameworks or static libraries.

**Comment by 1ec5** [comment]
> We will eventually replace AWSCore and AWSPolly with another speech library

This work is progressing in #617, by the way.

**Comment by frederoni** [comment]
SDWebImage was removed in #1046

**Comment by 1ec5** [comment]
Relatedly, CocoaPods recently added support for [static Swift libraries](http://blog.cocoapods.org/CocoaPods-1.5.0/). However, since this SDK depends on at least one Objective-C library (the map SDK), that library’s podspec will [apparently](http://blog.cocoapods.org/CocoaPods-1.5.0/) need to be modified to opt the generated target into getting a module map: mapbox/mapbox-gl-native#11794.

**Comment by 1ec5** [comment]
@mapbox/maps-ios is planning to stop publishing the map SDK as a static library, which will make it infeasible to offer the navigation SDK as a static library: mapbox/mapbox-gl-native#12841.

/cc @mapbox/navigation-ios

**Comment by zugaldia** [comment]
> @mapbox/maps-ios is planning to stop publishing the map SDK as a static library, which will make it infeasible to offer the navigation SDK as a static library: mapbox/mapbox-gl-native#12841.

@1ec5 is there documentation work needed for nav to manually build the static framework like you recommended for maps on https://github.com/mapbox/mapbox-gl-native/issues/12841#issuecomment-419265864?

**Comment by 1ec5** [comment]
We don’t (can’t) publish binaries of the navigation SDK, so it’s up to developers to build it from source using CocoaPods or Carthage. If the map SDK is no longer offered as a static library binary, then it becomes the responsibility of individual developers to build the navigation SDK and all its dependencies, including the map SDK, as static libraries from source. While there is documentation on building the map SDK from source as a static library, I’m pretty sure that library could only be used by a fork of the navigation SDK.
