### ISSUE TITLE
Reroute missing new route metrics

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#1025]
We don't seem to be updating/sending the following properties of the reroute event after a reroute any more:
* `newDistanceRemaining`
* `newDurationRemaining`
* `newGeometry`

https://github.com/mapbox/mapbox-navigation-ios/blob/1fa117b95fc11237708f766dd1fe7c9cdb41ea4b/MapboxCoreNavigation/MMEEventsManager.swift#L404-L412

cc @bsudekum @mapbox/navigation-ios

**Comment by bsudekum** [comment]
Hrm, I'm able to hit a breakpoint in this function each time a reroute occurs.
