### ISSUE TITLE
Allow overriding speak() function for voice synthesis

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#1026]
This would offer developers who want to announce custom events in their app a way to easily achieve a voice consistent with navigation.

cc @mapbox/navigation-ios @mapbox/navigation-android

**Comment by 1ec5** [comment]
`PollyVoiceController.speak(_:)` is currently `public`, but it should be `open` so that a custom subclass of PollyVoiceController can override this method and pass a modified SpokenInstruction to our superclass implementation.

**Comment by bsudekum** [comment]
This has been fixed.
