### ISSUE TITLE
Hide delimiters in banner when surrounded by loaded shield images

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1027]
In the turn banner, when an image component loads, hide any adjacent delimiter component to prevent unsightly slashes next to images:

![image](https://user-images.githubusercontent.com/1231218/35028582-a9434114-fb0b-11e7-8e19-90287c9f4e82.png)

Blocked by mapbox/MapboxDirections.swift#224.

/cc @bsudekum @ericrwolfe

**Comment by 1ec5** [comment]
Looks like we need some padding or a space between each component too.

**Comment by akitchen** [comment]
MVP is done; there is some tail work remaining in the PR description which I would like to ticket out and address separately. Marked as ready for review.

**Comment by akitchen** [comment]
I removed the review flag and am reopening this to look at why the network queue seems to get backed up on very long routes.

**Comment by bsudekum** [comment]
This has been implemented, thanks @akitchen!

**Comment by 1ec5** [comment]
Specifically, this was implemented in #1046
