### ISSUE TITLE
Compiler errors after pod update to MapboxNavigation 0.12.2

### ISSUE THREAD

**Issue by magnas35** [mapbox/mapbox-navigation-ios#1039]
I added a new unrelated pod today and ran pod update which also incrementally updated MapboxNavigation from 0.12.1 to 0.12.2. Cleaned and tried to build but I'm getting a couple of compiler errors in MapboxCoreNavigation.

This is my pod file:
`pod 'Mapbox-iOS-SDK', '~> 3.7'`
`pod 'MapboxNavigation', '~> 0.12.0'`
`pod 'ObjectMapper', '~> 3.1'`

Both errors relate to the ManeuverType.
The first error is 
> Initializer for conditional binding must have Optional type, not 'ManeuverType'

on the line
`if let leftType = left.maneuverType, let rightType = right.maneuverType {`

in file RouteStep.swift.
The second (related no doubt) error is
> Cannot use optional chaining on non-optional value of type 'ManeuverType'

on the line
`"upcomingType": upComingStep?.maneuverType?.description ?? NSNull(),`

in the extension to RouteLegProgress in file MMEEventsManager.swift.

Swift 4
Xcode 9.2

**Comment by frederoni** [comment]
Looks like MapboxNavigation is not in sync with MapboxDirections. Would you mind sharing your Podfile.lock? `maneuverType` is no longer optional as of https://github.com/mapbox/MapboxDirections.swift/pull/227.

`pod repo update && pod update`  should fix the compilation error.

**Comment by magnas35** [comment]
Podfile.lock as requested:

`PODS:
  - AWSCore (2.6.11)
  - AWSPolly (2.6.11):
    - AWSCore (= 2.6.11)
  - Mapbox-iOS-SDK (3.7.3)
  - MapboxCoreNavigation (0.12.2):
    - MapboxDirections.swift (~> 0.15)
    - MapboxMobileEvents (~> 0.2)
    - Turf (~> 0.0.4)
  - MapboxDirections.swift (0.16.0):
    - Polyline (~> 4.2)
  - MapboxMobileEvents (0.2.10)
  - MapboxNavigation (0.12.2):
    - AWSPolly (~> 2.6)
    - Mapbox-iOS-SDK (~> 3.6)
    - MapboxCoreNavigation (= 0.12.2)
    - SDWebImage (~> 4.1)
    - Solar (~> 2.1)
    - Turf (~> 0.0.4)
  - ObjectMapper (3.1.0)
  - Polyline (4.2.0)
  - SDWebImage (4.2.3):
    - SDWebImage/Core (= 4.2.3)
  - SDWebImage/Core (4.2.3)
  - Solar (2.1.0)
  - Turf (0.0.4)

DEPENDENCIES:
  - Mapbox-iOS-SDK (~> 3.7)
  - MapboxNavigation (~> 0.12.0)
  - ObjectMapper (~> 3.1)

SPEC CHECKSUMS:
  AWSCore: a461695bf302a32a366768bf36056be3a2c87d8d
  AWSPolly: fa1600710f3eb20624caeb1d0566d77a44ae4902
  Mapbox-iOS-SDK: 5304bd9605babe6da9050ea4cb23c1671420b737
  MapboxCoreNavigation: e22830451f66b82c28eced23449aaf2101dda0c3
  MapboxDirections.swift: 168cc83745b188d792c5482bfb0653c233d1455c
  MapboxMobileEvents: 9e48b59d0eed04508595dcb04a77b7632e1c3054
  MapboxNavigation: f6a8ed114b071b65de6948a330ee384d2836a87b
  ObjectMapper: 20505058f54e5c3ca69e1d6de9897d152a5369a6
  Polyline: 3d69f75bb136357e27291d439d0436c6ebda57a4
  SDWebImage: 791bb72962b3492327ddcac4b1880bd1b5458431
  Solar: 2dc6e7cc39186cb0c8228fa08df76fb50c7d8f24
  Turf: 6c169618fa671e3f8a7b764b5b3332053ad6110e

PODFILE CHECKSUM: 553165b1265fef1b4366b410c19cc9be0d437b6b

COCOAPODS: 1.3.1`

**Comment by magnas35** [comment]
Same errors after `pod repo update && pod update` I'm afraid. You mentioned a possible syncing problem between MapboxDirections and MapboxNavigation. Originally my app only used Directions but then I added the turn-by-turn navigation and removed the`pod 'MapboxDirections.swift', '~> 0.15'` when I added `pod 'MapboxNavigation', '~> 0.12.0'` to the pod file. Could that be the issue? It was compiling fine with MapboxNavigation 0.12.1.

**Comment by frederoni** [comment]
MapboxDirections.swift 0.16.0 contains a breaking change which MapboxCoreNavigation 0.12.2 haven't adopted yet. You can use a transient version of MapboxDirections in the meantime by adding:
```rb
pod 'MapboxDirections.swift', '~> 0.15.0'
```
to your Podfile.

Should we specify semver revision when using the tadpole operator to avoid these breaking changes from getting released or what's the protocol? /cc @1ec5 @bsudekum 
Perhaps a CocoaPods pre-flight test would have caught this earlier.

**Comment by magnas35** [comment]
Thanks, the transient version has me up and running again.

**Comment by paul019** [comment]
I've realized, that I forgot to run `pod repo update`. After doing that and running `pod install`, CocoaPod gets stuck at the installation process after printing this line: `Installing MapboxNavigationNative 3.3.1 (was 3.2.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)`. I found similar issues on Github, but no workaround worked for me so far.

Do you know, how I can solve this problem?

(My Xcode version: `Version 10.1 (10B61)`)
