### ISSUE TITLE
Fail CI build if strings files are in UTF-16

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1049]
This project prefers UTF-8 encoding for strings files, since Git is unable to diff UTF-16-encoded files natively. Since there’s already a handy script for converting the strings files to UTF-8, let’s add a step to one of the Bitrise apps that verifies all the files are in the right encoding.

/cc @frederoni

**Comment by frederoni** [comment]
Fixed by adding a step to Bitrise.
Tested in #1053
