### ISSUE TITLE
Use superior letters for abbreviations in French

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1051]
In French, abbreviations are commonly written with [superior letters](https://en.wikipedia.org/wiki/Superior_letter#Use_in_French) for readability. Currently, the turn banner only displays plain text (other than route shield images), so in French, we display everything on the baseline, which can get confusing.

[![A4 - A104](https://user-images.githubusercontent.com/1231218/35187663-2de1ef42-fddc-11e7-8a27-f9f2b7734b3e.png)](https://commons.wikimedia.org/wiki/File:A4_-_A104_-_panoramio.jpg)
_<sup>s</sup>⁄ = sur, C<sup>tre</sup> = Centre, Comm<sup>cial</sup> = Commercial, R<sup>al</sup> = Régional_

While it’s possible to represent some of these superior letters in plain text with [Unicode superscript characters](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts), fonts don’t necessarily have the full set of those characters. It would be better to apply a superscript attribute to the attributed string. Ideally it would be the Directions API that tells this SDK to superscript a run of text (see #1050); that way, we can avoid language-specific special cases on the client side.

As a workaround, I suppose the translation could specify Unicode superscript characters; this SDK could replace them with ASCII characters and apply a superscript attribute to them.

Some of the [existing abbreviations](https://github.com/mapbox/mapbox-navigation-ios/blob/12be1a29ba29b3696470104dd33b9dfd1f5abfd3/MapboxNavigation/Resources/es.lproj/Abbreviations.plist#L33-L34) in the Spanish localization suggest that this functionality might be useful for that language as well.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/1047#issuecomment-359126811
/cc @mapbox/navigation @mapbox/guidance

**Comment by bsudekum** [comment]
@1ec5 how much of this could be done on the server?

**Comment by 1ec5** [comment]
Half of it, which is why I opened this issue here. This SDK would still be responsible for applying the superscript attribute to the attributed string wherever the Directions API says to.

**Comment by 1ec5** [comment]
@danpaz @mandeepsandhu, any idea what would be the most appropriate way for the Directions API to tell the navigation SDK to use superior letters in these abbreviations? Or do you think it would be appropriate for the navigation SDK to special-case French and hard-code these particular abbreviations as having superior letters?

**Comment by mandeepsandhu** [comment]
> @danpaz @mandeepsandhu, any idea what would be the most appropriate way for the Directions API to tell the navigation SDK to use superior letters in these abbreviations? Or do you think it would be appropriate for the navigation SDK to special-case French and hard-code these particular abbreviations as having superior letters?

We could add _additional_ attributes to the abbreviation component (something like `use_superior: true`?). Do we have enough info to figure out when superior letters are to be used?
