### ISSUE TITLE
Get on the Mapbox Maps iOS SDK v4

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1057]
v4 is coming, there will be a decent amount of work to tend to WRT to run time styling. 

Can test this out via pods (or prob carthage too) via: https://raw.githubusercontent.com/mapbox/mapbox-gl-native/1ec5-e8n-8074/platform/ios/Mapbox-iOS-SDK.podspec

**Comment by bsudekum** [comment]
This breaking change will allow us to make https://github.com/mapbox/mapbox-navigation-ios/issues/987 work better

**Comment by 1ec5** [comment]
> Can test this out via pods (or prob carthage too) via: https://raw.githubusercontent.com/mapbox/mapbox-gl-native/1ec5-e8n-8074/platform/ios/Mapbox-iOS-SDK.podspec

Note that expressions have landed as a beta.
