### ISSUE TITLE
EndOfRouteViewController

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1059]
Hi, I am using 0.13
first:
when dismiss EndOfRouteViewController, func navigationViewControllerDidCancelNavigation is not called. Can u guys call the func navigationViewControllerDidCancelNavigation or provide a notification so that I can override the function. like what I just did.
![snip20180122_15](https://user-images.githubusercontent.com/10751092/35243902-0b48053a-ff84-11e7-95fe-adb36b76e698.png)
second:
![image1](https://user-images.githubusercontent.com/10751092/35243926-1babdc76-ff84-11e7-828d-c20f3becde62.png)

**Comment by bsudekum** [comment]
This will be fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/1056
