### ISSUE TITLE
updateOTA Error

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1060]
Hi, guys I am using navigation-ios 0.13.
I can still see this error sometimes, Thanks.
![snip20180122_16](https://user-images.githubusercontent.com/10751092/35244347-759b8cd0-ff85-11e7-96df-ec9353a001ce.png)

**Comment by bsudekum** [comment]
@zijiazhai we have not seen this crash since https://github.com/mapbox/mapbox-navigation-ios/pull/977/ was introduced in v0.12.2. 

Can you reproduce the crash consistently in v0.13.0? Is there anything notable you are doing when the crash occurs?

**Comment by zijiazhai** [comment]
No, I only saw this error once today in 0.13.3. I will let you guys know if I can get some useful information to reproduce it.

**Comment by zijiazhai** [comment]
This issue still exists in V0.13.1. Seems like when the app crash, the func updateETA was called twice. on the second time, routeController is nil.  Plz take a look @bsudekum , I am not sure how to reproduce yet.
![121519168293_ pic](https://user-images.githubusercontent.com/10751092/36454557-15bfb1b2-1662-11e8-9119-cc37744dae62.jpg)
![111519168281_ pic](https://user-images.githubusercontent.com/10751092/36454559-1848a0b0-1662-11e8-959a-db8b3c5869cb.jpg)
