### ISSUE TITLE
Bluetooth Memory leak 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1061]
code: https://github.com/mapbox/mapbox-navigation-ios/blob/bf83b55c3286da3b4258aa5cdd78a2df9eb6e541/MapboxCoreNavigation/MMEEventsManager.swift#L285-L293

![image](https://user-images.githubusercontent.com/1058624/35249375-960a41a4-ff86-11e7-8928-bc84ff5a5a4b.png)

/cc @frederoni

**Comment by frederoni** [comment]
This is only an issue when running in the simulator which isn't a reliable source for testing for leaks and cycles.
