### ISSUE TITLE
Carthage build includes nested frameworks

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#1065]
**Mapbox Navigation SDK version:** 0.13.0

After updating to the latest mapbox navigation version, the delivery failed because nested frameworks are included again in the build. They were removed in https://github.com/mapbox/mapbox-navigation-ios/pull/930, and readded again in https://github.com/mapbox/mapbox-navigation-ios/commit/5830291b4b2b7b27c5d367367361b6bc91c8de7e.

A workaround is still possible after running carthage:
> rm -rf "Carthage/Build/iOS/MapboxNavigation.framework/Frameworks"

**Comment by frederoni** [comment]
Sorry for the inconvenience. Fixed in #1066
