### ISSUE TITLE
Various constraints fail to mirror in right-to-left languages

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1070]
Now that #1043 has added Hebrew support to the UI, we need to ensure that the UI layout mirrors properly in right-to-left languages. I spotted a few issues on a quick simulated trip through Tel Aviv:

✅ <img src="https://user-images.githubusercontent.com/1231218/35385291-ae0d54b0-017c-11e8-9c2d-5f90cdbb24af.png" width="300" alt="example" align="top"> <img src="https://user-images.githubusercontent.com/1231218/35385333-cca952ac-017c-11e8-9b3d-15a46c4011a9.png" width="300" alt="start" align="top">

❌ <img src="https://user-images.githubusercontent.com/1231218/35384971-c5f23d44-017b-11e8-8af4-97617c4b7c13.png" width="300" alt="navigation" align="top"> <img src="https://user-images.githubusercontent.com/1231218/35385214-75eea3ea-017c-11e8-90cf-767c4956d139.png" width="300" alt="overview" align="top">

❌ <img src="https://user-images.githubusercontent.com/1231218/35385135-3cbf9c78-017c-11e8-84d0-40cba53ea756.png" width="300" alt="feedback" align="top">

✅ <img src="https://user-images.githubusercontent.com/1231218/35384623-c8bd689c-017a-11e8-8eac-a065745798b3.png" width="300" alt="end of route" align="top">

The storyboard and any programmatic Auto Layout code needs to be audited for the use of left and right constraints, which should be replaced by leading and trailing constraints in most cases.

/cc @mapbox/navigation-ios @danesfeder

**Comment by JThramer** [comment]
Perhaps this would be a good thing to check for in the linter. It's usually just accidental usage of something like `leftAnchor` over `leadingAnchor`.

**Comment by 1ec5** [comment]
The lanes in the lane view are also in the wrong order. This is really confusing. In the example below, the user is prone to thinking they should take one of the left lanes to turn left, whereas they should take one of the right lanes to turn right:

<img src="https://user-images.githubusercontent.com/1231218/36819248-7e57e4ba-1c9d-11e8-8eca-865e1aa85079.png" width="300" alt="lanes">

**Comment by danpat** [comment]
@1ec5 are you *sure* this isn't just a https://en.wikipedia.org/wiki/Hook_turn location?

**Comment by 1ec5** [comment]
Haha, [nope](https://www.openstreetmap.org/way/19069246), but I’ve seen weirder road configurations in this part of Ohio…

**Comment by 1ec5** [comment]
Filed #1174 for the lane issue.
