### ISSUE TITLE
Allow developers to present FeedbackViewController over custom navigation

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#1071]
As part of splitting our UI into standalone components (#645), developers who implement a custom UI should be able to present our default feedback UI. 

Currently, FeedbackViewController is private and the logic to present the Feedback UI and create + update feedback events is contained within RouteMapViewController. 

We should considering abstracting this away so someone can present the default feedback UI as an overlay as easy as presenting a [UIActivityViewController](https://developer.apple.com/documentation/uikit/uiactivityviewcontroller). 

A developer should need to make any direct calls to the route controller's `recordFeedback()`, `updateFeedback()`, or `cancelFeedback()` functions.

cc @mapbox/navigation-ios

**Comment by ericrwolfe** [comment]
@danesfeder is this something that's possible in the Android SDK?

**Comment by danesfeder** [comment]
@ericrwolfe yeah you can show `FeedbackBottomsheet` over any `Activity` by calling:

```
    FeedbackBottomSheet.newInstance(this,
      NavigationConstants.FEEDBACK_BOTTOM_SHEET_DURATION).show(
      (getContext()).getSupportFragmentManager(), FeedbackBottomSheet.TAG);
```

**Comment by JThramer** [comment]
Strongly agree @ericrwolfe, although I do think that it is also desirable to try and decouple our telemetry engine from our route controller. It would be nice if the `RouteController` interacted with a singleton as a "black-box", like this: 

`Telemetry.shared.report(reroute: newRouteProgress, old: oldRouteProgress)`

Past that point, the `RouteController` cares not about _how_ the report is delivered, with message queueing and the like. That's the telemetry engine's job. It should be fire-and-forget.

That way, the `FeedbackViewController` could also talk directly to the telemetry singleton without leaving the developer the task of manual message passing.

`Telemetry.shared.report(userFeedback: .confusingInstruction, description: nil)`

It seems to me that there is quite a lot of back and forth between the `RouteController` and the telemetry logic, but really the only three things that the feedback engine actually cares about in the route controller is the `routeProgress`, the current location and whether it's simulated, and the `sessionState`, which I think the Telemetry engine should own.

Also, it's worth noting that the feedback [payload assembly logic](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/MMEEventsManager.swift#L116) is ripe for `Codable` refactoring.

**Comment by brsbl** [comment]
tracking next actions [here](https://github.com/mapbox/mapbox-navigation-ios/issues/1165)

**Comment by JThramer** [comment]
Posterity: The two main ideas from [this comment](https://github.com/mapbox/mapbox-navigation-ios/issues/1071#issuecomment-360568842) now live on in [their own](https://github.com/mapbox/mapbox-navigation-ios/issues/1200) separate [issues](https://github.com/mapbox/mapbox-navigation-ios/issues/1201).
