### ISSUE TITLE
top/bottom banner view are blank

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1072]
sorry, guys , I am using v0.13.0, but what cause this happen?
![wechatimg3](https://user-images.githubusercontent.com/10751092/35415199-5ccbca3c-01ea-11e8-928e-e59d307b16cc.jpeg)

**Comment by zijiazhai** [comment]
default UI, after I switch simulate locations to without simulate locations.

**Comment by bsudekum** [comment]
It appears this occurs when the location manager does not fire at the beginning of a route.

**Comment by Sealos** [comment]
I'm also experiencing this issue as of 0.13.0.

**Comment by bsudekum** [comment]
@zijiazhai @Sealos I'm having a hard time reproducing this bug. Can you give me a few steps to reproduce? Are you simulating location?

**Comment by zijiazhai** [comment]
if u start navigation with simulation location first, then dismiss navigationController, then switch to start navigation without simulation location, that should reproduce the issue.

**Comment by zijiazhai** [comment]
@bsudekum
