### ISSUE TITLE
Shield Numbers as secondaryInstruction

### ISSUE THREAD

**Issue by dblythy** [mapbox/mapbox-navigation-ios#1077]
I'm wondering if there's a way that I can prefer road names over shield/route numbers. 
Where I live, there are a few routes through every town and most people don't use route numbers. A short trip ends up looking like:

![simulator screen shot - iphone 6s - 2018-01-27 at 17 09 26](https://user-images.githubusercontent.com/4974769/35469215-e6484470-0384-11e8-8c8d-beaa52dc9fca.png)

**Comment by 1ec5** [comment]
This is a bug in the Directions API: for surface roads, you should be seeing the road name followed by the route number. We’ve got a fix in the works, and it’ll be deployed in a matter of days. Thanks for your patience!

/cc @captainbarbosa

**Comment by 1ec5** [comment]
This is a bug in the Directions API: for surface roads, you should be seeing the road name followed by the route number. We’re working on a fix on the server side. Thanks for your patience!

/cc @captainbarbosa @allierowan

**Comment by bsudekum** [comment]
This change has now been deployed. The motorway name and highway shield will most of the time be visible.
