### ISSUE TITLE
StepIndex Incrementation leads to assert(false) --> crash

### ISSUE THREAD

**Issue by hervouinc** [mapbox/mapbox-navigation-ios#1081]
**Mapbox Navigation SDK version: 0.13.0**

file: `RouteController`
`func updateRouteStepProgress(for location:)`
--> `func advanceStepIndex(to:)`
--> `routeProgress.currentLegProgress.stepIndex += 1`

file: `RouteProgress`
```
@objc public var stepIndex: Int {
        didSet {
            assert(stepIndex >= 0 && stepIndex < leg.steps.endIndex)
            currentStepProgress = RouteStepProgress(step: currentStep)
        }
 }
```

`assert` shoud be replaced by a `guard` or `StepIndex` should not be incremented.

**Comment by bsudekum** [comment]
I think you raise a fair point. We should gently tell the developer they cannot increment further instead of asserting and crashing.

/cc @mapbox/navigation-ios

**Comment by hervouinc** [comment]
Hi @bsudekum , saw you have closed the "Do not assert" PR. 
Can you referenced the PR that fix this issue when available ? Thanks

**Comment by bsudekum** [comment]
@hervouinc I'm trying to reproduce the situation via your comment 

> * the user goes over the last waypoint of the route
> * we choose to not reroute when asked by the routeController to its delegate, at least for a while (based on several local properties) since we know the user can stop after the waypoint
> * the user's location is still handled by the routeController and leads to updateRouteStepProgress and then advanceStepIndex.

Can you clarify step 2 with a code snippet perhaps? 

I'm trying to reproduce it in the sim with something like: 
![image](https://user-images.githubusercontent.com/1058624/35820755-73b1aa18-0a5b-11e8-9f23-123156382c9c.png)

**Comment by hervouinc** [comment]
@bsudekum here is the step 2:

**Comment by bsudekum** [comment]
@hervouinc thanks, was successfully able to reproduce locally.
