### ISSUE TITLE
Compilation Error After Installing MapboxNavigation -> 13.1

### ISSUE THREAD

**Issue by AlaaAmrAmin** [mapbox/mapbox-navigation-ios#1096]
Am using xCode 9.2 and Swift 3.2, I tried to update MapboxNavigation using pods to version 13.1, but am getting this compilation error "_The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor._".
I know version 13.1 is for Swift 4, but from what I've understood, xCode 9.2 can run both swift 3.2 & 4 together.

I have also tried to install MapboxNavigation version 10.1, still same error, which is really weird, as version 10.1 is for swift 3.2.

Help!

**Comment by bsudekum** [comment]
Hi @AlaaAmrAmin are you using cocoapods or carthage? Also, can you explain a little bit more of your situation? Why are you unable to use Swift 4?

**Comment by AlaaAmrAmin** [comment]
@bsudekum am using cocoapod. I have built the project using Swift 3.2 and xCode 8, then I upgraded to xCode 9.2, but haven't upgraded to Swift 4, this was a couple of months ago, before adding Mapbox. Then I integrated the _'Mapbox-iOS-SDK'_  and _'MapboxNavigation', '~> 0.8.0'_ and everything was working fine, but I need to upgrade the _MapboxNavigation_, as the turn by turn navigation is not working as expected, and I need to show the alternative routes on the map using "showRoutes" function, with the ability to select one them, and this is not available in version 8.

And here's the contents of my pod file, in case you need to take a look at it:

    pod 'AFNetworking', '~> 3.0'
    pod 'SwiftyJSON'
    pod 'MBProgressHUD'
    pod 'IQKeyboardManagerSwift', '5.0.0'
    pod 'LGSideMenuController'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    
    pod 'GoogleMaps'
    pod 'PXAlertView', '~> 0.1.0'
    pod 'SDWebImage'
    pod 'DLRadioButton', '~> 1.4'
    pod 'SwiftyImage'
    pod 'CameraManager', '~> 3.2'
    
    pod 'Mapbox-iOS-SDK', '~> 3.7'
#    pod 'MapboxNavigation', '~> 0.8.0'
    pod 'MapboxNavigation', '~> 0.13.1'

    pod 'AXRatingView'

**Comment by bsudekum** [comment]
@AlaaAmrAmin I'm really unsure about this error, but I'd recommend upgrading to Swift 4 if at all possible. That said, can you double check your project is setup similarly to that outlined in https://stackoverflow.com/a/46339401/1522419?
