### ISSUE TITLE
navigationMapView(_ didSelect:) function doesn't get if map has a style URL

### ISSUE THREAD

**Issue by AlaaAmrAmin** [mapbox/mapbox-navigation-ios#1099]
I initialized a navigationMapView instance with a styleURL, and I show multiple routes on the map. The problem, is didSelect function never gets called, but if I remove the style, the function is invoked on select.

**Comment by bsudekum** [comment]
@AlaaAmrAmin I'm unable to reproduce this. Can you provide a simple example that shows the issue?
