### ISSUE TITLE
Adopt named arrival instructions from Directions API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1123]
Spoken instructions for an `arrive` step should include the name of the waypoint. In typical SDK usage, the developer supplies a `Waypoint.name` that’s either the name of a point of interest or an address. The user would find it very useful to hear the address when arriving at the destination. Arriving at a named waypoint is a basic use case, so the SDK should handle it without requiring any developer intervention.

Currently, the arrival instructions come from the Directions API, like any other instruction. In the absence of Directions API support for this feature, the SDK would need to ignore the `arrive` step’s `SpokenInstruction` objects in favor of its own homegrown instruction strings. For localization, we have two options:

* Translate the arrival instructions as part of this SDK’s Transifex project. The strings will be somewhat redundant with OSRM Text Instructions. We won’t be able to take advantage of the grammar support in OSRM Text Instructions, which would be very unfortunate for Russian, because declination is required for the waypoint name.
* Add named waypoint strings to OSRM Text Instructions and depend on [OSRM Text Instructions for Swift](https://github.com/Project-OSRM/osrm-text-instructions.swift/) once again. Russian declination would need to be fixed in Project-OSRM/osrm-text-instructions.swift#49.

/cc @mapbox/navigation-ios @mapbox/guidance

**Comment by 1ec5** [comment]
Note that it would be insufficient to append the waypoint name to the server-generated instruction, for the following reasons:

* This SDK sends an SSML string to the Voice API. We lack access to an XML parser, so we can’t reliably modify the SSML string in any way, not even to append to the sentence.
* If OSRM knows which side of the street the destination is on, the instruction [includes the phrase “on the left/right”](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/test/fixtures/v5/arrive_waypoint/left.json); the waypoint name would have to come before that phrase.
* Appending the waypoint name to the instruction would be ungrammatical in some of the languages we support (and some major languages we don’t yet support, like Japanese).

**Comment by bsudekum** [comment]
@1ec5 would this require some server involvement? IE the response would change to

```
"voiceInstruction": "You have arrived at {replace text here}."
```

**Comment by 1ec5** [comment]
> would this require some server involvement?

That would make a lot of sense. However, if the Directions API won’t add any support for this option, then we’re kind of on our own. We’d need to build some of our own voice instructions on the client side, essentially.

**Comment by akitchen** [comment]
Server will name the waypoint in the banner, but MapboxDirections.swift will eventually need to change.

**Comment by vincethecoder** [comment]
Update:
Per conversation with @1ec5, here is an update for this ticket requirement:
> The `DirectionsOptions.params` getter needs to add another URLQueryItem to the array based on mapping all the waypoints to their names.

Source: https://mapbox.slack.com/archives/C220EHL3W/p1525805537000136

**Comment by vincethecoder** [comment]
@1ec5 if we "_remove this special case for arrival banners_"[[1](https://github.com/mapbox/mapbox-navigation-ios/issues/1123#issuecomment-383674366)], does that mean, this line: [StepsViewController.swift#L221](https://github.com/mapbox/mapbox-navigation-ios/blob/d7f8c4d075ca578983cbe02d819d74eb7ac284c4/MapboxNavigation/StepsViewController.swift#L221) should only be assigned an instruction's secondaryInstruction like this:  `cell.instructionsView.secondaryLabel.instruction = instructions.secondaryInstruction` ?


###### [1] Reference to comment - "_Remove this special case for arrival banners_" https://github.com/mapbox/mapbox-navigation-ios/issues/1123#issuecomment-383674366

**Comment by vincethecoder** [comment]
* [x] Remove this special case for arrival banners: 
[func instructionForArrivalInstruction(text: String?) -> VisualInstruction](https://github.com/mapbox/mapbox-navigation-ios/blob/d7f8c4d075ca578983cbe02d819d74eb7ac284c4/MapboxNavigation/StepsViewController.swift#L203-L207) 
PR reference: https://github.com/mapbox/mapbox-navigation-ios/pull/1406
