### ISSUE TITLE
Make step table more discoverable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1138]
#785 moved the entry point for the step table, so that instead of dragging the bottom bar upwards, the user taps the banner at the top. We observed in a small study that users have a difficult time finding the step table. Participants expected to swipe upwards from the bottom bar, as in Google Maps and Apple Maps; failing that, they expected to swipe downwards from the banner. There are several things we can do to improve the discoverability of this feature (pick two):

* [ ] Add a visual cue that the banner reveals additional steps, either a handle at the bottom of the banner or a 🍔 icon on the side.
* [x] Reveal the step table upon swiping downwards from the banner.
* [ ] Reveal the step table upon swiping upwards from the bottom bar.

/cc @mapbox/navigation-ios @mapbox/navigation-android

**Comment by 1ec5** [comment]
If we implement either swipe gesture, we can remove the banner’s tap gesture and repurpose it for repeating the current instruction: #979.

**Comment by bsudekum** [comment]
I think before moving forward here, we should design some mockups. I'm weary of adding more visual buttons to the UI that may clutter it and make it confusing for the user.

**Comment by JThramer** [comment]
Just recording this for posterity, but I'm a big fan of swiping, either down from the top banner or up from the bottom banner.

**Comment by 1ec5** [comment]
> I'm weary of adding more visual buttons to the UI that may clutter it and make it confusing for the user.

Agreed. Google and Apple take the approach of placing a handle on the bottom bar, subtly hinting that you can swipe on the bar to reveal more content. We could add a pan gesture recognizer and small handle to the banner without fundamentally changing the interaction model or cluttering up the UI.

**Comment by 1ec5** [comment]
In chat, it seems like this might be a path forward:

* [ ] Add a subtle handle to the bottom of the banner, as a visual cue that the banner reveals additional steps, similar to what Apple and Google do.
* [ ] Reveal the step table upon swiping downwards from the banner, leaving in place the current tap gesture.

Future steps that don’t need to take place right away:

* [ ] Repeat the current instruction when tapping the banner (to fix #979).
* [ ] Reveal the step table upon swiping upwards from the bottom bar, replacing the functionality that’s currently in the top bar.

**Comment by brsbl** [comment]
This work was merged: https://github.com/mapbox/mapbox-navigation-ios/pull/1150

**Comment by 1ec5** [comment]
Per https://github.com/mapbox/mapbox-navigation-ios/pull/1150#pullrequestreview-103662514, a handle wasn’t added to the banner, so the step table isn’t much more discoverable than it was when this issue was opened.

**Comment by bsudekum** [comment]
Steps indicator was added in https://github.com/mapbox/mapbox-navigation-ios/pull/1253
