### ISSUE TITLE
Improve layout in landscape orientation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1139]
NavigationViewController is laid out inefficiently when the device is in landscape orientation. Each banner takes up the entire width of the screen, revealing plenty of whitespace, while taking up valuable vertical screen real estate. With enough banners visible (lanes, “then”, simulation), the user puck overlaps the banners, and the floating action buttons at right overlap the bottom bar, obscuring the exit button.

<table>
<tr></tr>
<tr><td>

![landscape](https://user-images.githubusercontent.com/1231218/36442932-27fb8bd4-162c-11e8-8a77-eccd179d7764.png)

</td></tr>
</table>

Many navigation applications, including Apple Maps, switch to a two-column layout in landscape orientation, with the left column containing the banners and the bottom bar. With this layout, the banner gets less horizontal space but more vertical space, which can be used for line wrapping or for displaying additional information like incidents.

Previously: #726.

/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
I'm actually unsure how the lanes view and the then banner are both showing up in this pr, as we only show the then banner if the lanes view is hidden

https://github.com/mapbox/mapbox-navigation-ios/blob/c45d93837c6a07dc5f3ea5a829f3cd50ca7f7e46/MapboxNavigation/RouteMapViewController.swift#L276-L279

**Comment by 1ec5** [comment]
For the original report above, I was simulating [approximately this route](https://www.mapbox.com/get-directions/#15.55/39.2876/-84.4642?coordinates=-84.4567878134779,39.287417340931626;-84.46744300898638,39.28699625839792), and the stacked views did reproduce reliably. There’s a bit of a gap between these two checks:

https://github.com/mapbox/mapbox-navigation-ios/blob/c45d93837c6a07dc5f3ea5a829f3cd50ca7f7e46/MapboxNavigation/NextBannerView.swift#L78-L82
https://github.com/mapbox/mapbox-navigation-ios/blob/c45d93837c6a07dc5f3ea5a829f3cd50ca7f7e46/MapboxNavigation/LanesView.swift#L78

So one view showed up first, then the other, as I approached the intersection.

**Comment by 1ec5** [comment]
Note that the screenshot in https://github.com/mapbox/mapbox-navigation-ios/issues/1139#issue-298711096 was taken on an iPhone 8, while the screenshot in https://github.com/mapbox/mapbox-navigation-ios/issues/1139#issuecomment-390740140 was taken on an iPhone X. (You can tell because of the extra padding on the right to make room for the notch.)

**Comment by brsbl** [comment]
cc @Cjballard would love your input here more generally, but also I think it's important to think about landscape mode as we are sprinting on redesigning the UI.

**Comment by Cjballard** [comment]
Was thinking about this as well while doing some test drives in landscape mode. I liked the Apple & Waze two-column approach a little better because it consolidated info neatly and reserved more map space. 

![apple-landscape](https://user-images.githubusercontent.com/7535952/40668032-88993160-6331-11e8-844c-b0b6d93657d6.png)


But more generally interested in how we can rectify information dead zones where we rarely present any information and instruction in landscape mode, and split-screen is just one solution.

![dedzone](https://user-images.githubusercontent.com/7535952/40668105-acf4793e-6331-11e8-8d8e-e772da9f34ba.png)

**Comment by 1ec5** [comment]
By the way, we implemented a two-column layout as a matter of course in CarPlay. (We didn’t have a choice, and it looks good!)

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native#14664 adjusts the map’s vanishing point to account for edge padding, which unblocks the sort of landscape layout seen in CarPlay. (#2134 updates the CarPlay support code to take advantage of this improvement to the map SDK.)

**Comment by MaximAlien** [comment]
Moving to `v2.2` for now. There is a low chance that we'll be able to tackle this in `v2.1`.
