### ISSUE TITLE
Destination pin should match style

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#114]
We’re currently using the map SDK’s default annotation icon for the destination pin. The red has good contrast with the default navigation style, but maybe we could be using a different color and different shape that more closely matches the style.

Down the line, we might also want to make it easier for the developer to customize the annotation to match the annotation they’re using to represent the destination on a preview map or some other map. But matching the style would be a good start.

/cc @aparlato @pveugen @bsudekum

**Comment by aparlato** [comment]
@1ec5 does this relate to https://github.com/mapbox/cartography/issues/109 (it seemed the workflow described in this ticket was ruled out)? 
Or, if not, what kind of workflow do you see here for this? Is it helpful for carto to provide a destination pin as an SVG that goes with our navigation styles? Does this pin apply to other maps developers are using with the sdk?

**Comment by 1ec5** [comment]
> Is it helpful for carto to provide a destination pin as an SVG that goes with our navigation styles?

An SVG would be fine. We’d convert it into a PDF or PNGs, but an SVG would be more maintainable, so we’d check in both.

> Does this pin apply to other maps developers are using with the sdk?

Do you mean something like the main map or preview map on a navigation-focused application? I’d imagine the developer would want to be fully in control of those maps, including specifying a style other than the navigation style.

For now, we should make sure the destination pin looks good on the navigation style, even if it differs from the pin used on other maps in the application. Eventually, we could expose an option for the developer to take the pin from another map and reuse it in the navigation map.

**Comment by aparlato** [comment]
> Do you mean something like the main map or preview map on a navigation-focused application? I’d imagine the developer would want to be fully in control of those maps, including specifying a style other than the navigation style.

I mean in terms of specifying a style other than the navigation style, as in would this pin be applied to a navigation style but also potentially, say, Streets if the developer wanted to use that?

> For now, we should make sure the destination pin looks good on the navigation style

Ok cool, this makes sense :+1:

**Comment by aparlato** [comment]
cc @mayagao it looked like you already had a pin designed/were designing a pin for the SDK for this style?
