### ISSUE TITLE
Improve progressDidChange + location

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1142]
Two issues here:

* `RouteController.location` is poorly named. This location is the snapped location. We should make this more clear.
* The location returned from progressDidChange is the raw unsnapped location. When implementing a custom UI, a developer would have to know to reach into the `routeController` to get the snapped location to update the user puck view. 

Proposals:

1. Rename `RouteController.location` to `snappedLocation`
1. Return both the raw location and snapped location on progress updates.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> `RouteController.location` is poorly named. This location is the snapped location. We should make this more clear.

It was called `snappedLocation` originally, before we removed the `location` property that represented the raw location. If we trust our snapping functionality, wouldn’t the snapped location be the only location the developer cares about? In that case, the location in the `progressDidChange` notification should represent the snapped location too.

**Comment by bsudekum** [comment]
Yeah this sounds good to me.
