### ISSUE TITLE
Offline Navigation Example

### ISSUE THREAD

**Issue by maley63** [mapbox/mapbox-navigation-ios#1147]
Hi there,

Is there any documentation to show how to set up Offline Navigation within MapBox.  
I have read online that it is possible however, I am constantly getting that the Internet connection appears to be offline.  There appears to be nothing explaining this on the internet.
My code is very basic, taking into account two points of my map that has been downloaded for offline use.

**Comment by bsudekum** [comment]
@maley63 currently, offline navigation is not available. This is something that is on our roadmap however.

**Comment by anthony1810** [comment]
@bsudekum Hi There! I am a paid client of Mapbox. Just need an update on @maley63 question. Can Mapbox calculate route for turn by turn navigation in offline mode. If possible, please point me to some resources we want to implemented for iOS and Android platform.
