### ISSUE TITLE
Make annotate function public/overridable

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#115]
This should be configurable: https://github.com/mapbox/MapboxNavigation.swift/blob/master/MapboxNavigationUI/MGLMapView.swift#L15

**Comment by 1ec5** [comment]
What do we expect the use cases to be? What aspects of this method would developers need to customize?

**Comment by bsudekum** [comment]
It's the only way we can get congestion along the route line working.

**Comment by 1ec5** [comment]
This method is only used on NavigationMapView, our subclass of MGLMapView.

1. Move `annotate(_:)` to NavigationMapView and remove this extension.
1. Split out a `func shape(describing: Route) -> MGLShape` method, make it public, and call it from within `annotate(_:)`.
1. If you want to implement custom color-coded congestion along the route line in your own application, you can further subclass NavigationMapView to override `shape(describing:)`. Down the line, we could replace that method with a `mapView(_:shapeDescribing:)` method on a NavigationMapViewDelegate protocol.

**Comment by bsudekum** [comment]
Done in https://github.com/mapbox/mapbox-navigation-ios/pull/116!
