### ISSUE TITLE
testDownloadingImageAgainAfterFirstDownloadCompletes fails time to time

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1151]
The test `testDownloadingImageAgainAfterFirstDownloadCompletes` seems to fail 1 out of 10 tests runs with the error:

```
MapboxNavigationTests.ImageDownloaderTests
  testDownloadingImageAgainAfterFirstDownloadCompletes, Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "Second Image Download".
  <unknown>:0
```

Perhaps the timeout here needs to be increased?

/cc @akitchen

**Comment by akitchen** [comment]
We had a similar issue in the maps SDK test suite recently. Yes, I agree we
should increase the timeout.

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/1157
