### ISSUE TITLE
App crash when removing NavigationViewController as ChildViewController

### ISSUE THREAD

**Issue by riserpete** [mapbox/mapbox-navigation-ios#1153]
**Mapbox Navigation SDK version: iOS 0.13**

App crashes because of unwrapping optional var `routeController` on `RouteMapViewController` after removing the container `NavigationViewController` from the view controller hierarchy.

I add the NavigationViewController as a ChildViewController (embedded) and later on remove it manually when the user cancels navigation. The reference to the NavigationViewController seems to correctly become nil, no other object holding a reference to it. But then the app crashes because the contained `RouteMapViewController` still seems to be in memory and the optional member variable `routeController` on it is nil. (Line 763 in `RouteMapViewController - `bottomBannerView?.updateETA(routeProgress: routeController.routeProgress)`)

I debugged with the XCode Memory Graph Debugger and saw that there is still a reference to the `RouteMapViewController` AFTER it was already removed from the hierarchy:

<img width="924" alt="screen shot 2018-02-25 at 18 33 55" src="https://user-images.githubusercontent.com/26596353/36644560-4dc0321e-1a5c-11e8-9ae9-c81fda0ae57e.png">

Update:
..it does not seem to happen in version 0.14..I am still testing..

**Comment by bsudekum** [comment]
Thanks for the report @riserpete, looking into this.

**Comment by bsudekum** [comment]
This should be fixed with https://github.com/mapbox/mapbox-navigation-ios/commit/d8bcd0e5992a7eea3e2c8c038b06176bef91820f.

@riserpete can you update and check if the issue still persists?

**Comment by riserpete** [comment]
thank you @bsudekum, works fine! as mentioned in the description above, the issue seemed to have disappeared in 0.14 already...
