### ISSUE TITLE
Remove `MBProgressBar`

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1161]
It has been unused for many releases now.

/cc @mapbox/navigation-ios

**Comment by JThramer** [comment]
@bsudekum `MBProgressBar` is still used in the `FeedbackViewController` [here](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/Resources/Base.lproj/Navigation.storyboard#L451) -- should we still remove?

**Comment by JThramer** [comment]
Posterity: Talked with @bsudekum on slack, agreed to invalidate ticket.
