### ISSUE TITLE
Refactor FeedbackViewController out of storyboard.

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1165]
Now that the Navigation Scene is out of the storyboard (#1063), we really should bring the `FeedbackViewController` layout out of the storyboard as well.

/cc @mapbox/navigation-ios

**Comment by brsbl** [comment]
@JThramer would this ticket be a way to implement [this](https://github.com/mapbox/mapbox-navigation-ios/issues/1071)?

**Comment by frederoni** [comment]
@brsbl that's correct

**Comment by JThramer** [comment]
@brsbl they're related, but not quite the same thing.

#1071 calls for custom UI Implementers to be able to present our `FeedbackViewController`, and this ticket will make it easier for them to do that, as it makes our FVC both easily accessible in two ways: 

1. `FeedbackViewController(frame: CGRect)` instead of instantiating the FVC from a storyboard -- which is not really a disclosed pattern
2. This also allows the `FeedbackViewController` to be extended.

However, In my [comment](https://github.com/mapbox/mapbox-navigation-ios/issues/1071#issuecomment-360568842) in that ticket, I pointed out that the `RouteController` and the Telemetry Engine (`MMEEventsManager`) are [very tightly coupled.](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift?utf8=✓#L982) While fixing [that issue](https://github.com/mapbox/mapbox-navigation-ios/issues/1071#issuecomment-360568842) will _also_ make our Telemetry/Feedback system easier to digest by developers, IMHO [that](https://github.com/mapbox/mapbox-navigation-ios/issues/1071#issuecomment-360568842) is a distinct issue and really deserves it's own story.

/cc @mapbox/navigation-ios
