### ISSUE TITLE
Navigation view should push onto view

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1168]
@JThramer is this the default animation when pushing the view? Can make it not grow from the bottom center?

![new3](https://user-images.githubusercontent.com/1058624/36762971-df566994-1bda-11e8-8284-0003fe527d5f.gif)

**Comment by bsudekum** [comment]
Also, it looks like the padding on the way name label is a little off on smaller screens.

**Comment by JThramer** [comment]
@bsudekum 🤔 it should be. I'll have a look.
