### ISSUE TITLE
Intersection index is always 0

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1170]
`RouteStepProgress.intersectionIndex` is never set to anything beyond 0. Thus `upcomingIntersection` always returns the first intersection along the step, and `userDistanceToUpcomingIntersection` always measures the distance from the beginning of the current step to the current location.

Perhaps the code that actually sets `intersectionIndex` got removed by accident at some point?

/ref #560
/cc @bsudekum @vincethecoder

**Comment by 1ec5** [comment]
Also, `RouteStepProgress.upcomingIntersection` returns the just-passed intersection, not the upcoming one:

https://github.com/mapbox/mapbox-navigation-ios/blob/2890d2f649b5d4f62285747d601c94cf565a6aad/MapboxCoreNavigation/RouteProgress.swift#L398

**Comment by vincethecoder** [comment]
This issue with `RouteStepProgress.intersectionIndex` will be fixed in my PR: https://github.com/mapbox/mapbox-navigation-ios/pull/1127/files#diff-851f438872328e98cbe395ac0733c16bR398

**Comment by 1ec5** [comment]
Fixed in #1127.
