### ISSUE TITLE
Roundabout banner icons should accurately represent roundabout geometry

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1171]
Example:

![image](https://user-images.githubusercontent.com/1058624/36807810-a81e83a0-1c78-11e8-9fcd-ded1d525ca44.png)

We'll first need to expose the property in MapboxDirections.swift.

/cc @lyzidiamond

**Comment by akitchen** [comment]
Instead of using a generic roundabout icon, we should represent the exit locations as described in the API response
