### ISSUE TITLE
Lanes in wrong order in Hebrew

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1174]
When the system language is set to Hebrew, the lanes in the lane view are in the wrong order, potentially creating a confusing end user experience. In the example below, the user is prone to thinking they should take one of the left lanes to turn left, whereas they should take one of the right lanes to turn right:

<img src="https://user-images.githubusercontent.com/1231218/36819248-7e57e4ba-1c9d-11e8-8eca-865e1aa85079.png" width="300" alt="lanes">

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/1070#issuecomment-369422431
/cc @frederoni

**Comment by bsudekum** [comment]
Should the lanes array be flipped at the OSRM level?

/cc @danpat

**Comment by 1ec5** [comment]
@bsudekum, no, this is purely a UI layout issue. I’ve got a fix in hand.
