### ISSUE TITLE
Some feedback icons are Americentric

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1181]
The “Missing Exit” and “Confusing Instruction” feedback category icons assume the user writes in a left-to-right language or is familiar with United States signage.

[<img src="https://user-images.githubusercontent.com/1231218/36885403-92f29948-1d9b-11e8-8de3-02308e68d392.png" width="90" alt="feedback-exit" align="left">](https://github.com/mapbox/mapbox-navigation-ios/blob/2890d2f649b5d4f62285747d601c94cf565a6aad/MapboxNavigation/Resources/Assets.xcassets/feedback-exit.imageset/exit-3x.png)

The “Missing Exit” icon resembles MUTCD-style exit gore signage. The MUTCD is primarily used in the U.S. and Canada, and the word “Exit” is specific to English. This is problematic because a typical driver in Europe who doesn’t know English will have no idea what this sign represents, certainly not when they have to decide on a category within just a few seconds.

A more globally recognizable symbol would be [<img src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Sinnbild_Autobahnausfahrt.svg" width="32" alt="the Vienna Convention motorway exit symbol" align="top">](https://commons.wikimedia.org/wiki/File:Sinnbild_Autobahnausfahrt.svg), which is used extensively in Vienna Convention countries (including European countries) because it avoids favoring one language over another.

<br clear="all">

[<img src="https://user-images.githubusercontent.com/1231218/36885388-78333b44-1d9b-11e8-84ee-ac854ce25fb9.png" width="90" alt="feedback-confusing-directions" align="left">](https://github.com/mapbox/mapbox-navigation-ios/blob/2890d2f649b5d4f62285747d601c94cf565a6aad/MapboxNavigation/Resources/Assets.xcassets/feedback-confusing-directions.imageset/confusing-directions-3x.png)

The “Confusing Instruction” icon uses the “?” question mark. This is OK for now: of the languages we currently support, only Chinese uses a different question mark (the fullwidth question mark “？”), which looks similar. Hebrew uses the same question mark as English, but Hebrew is written right-to-left, so technically the overall icon should be mirrored horizontally. Once we support other right-to-left languages like Arabic, we’ll need to mirror the question marks themselves, because they use the reversed question mark ؟.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
[<img src="https://user-images.githubusercontent.com/1231218/36911410-4aa5c144-1df8-11e8-87ce-469e71f77ca6.png" width="90" alt="feedback-no-turn-allowed" align="left">](https://github.com/mapbox/mapbox-navigation-ios/blob/2890d2f649b5d4f62285747d601c94cf565a6aad/MapboxNavigation/Resources/Assets.xcassets/feedback-no-turn-allowed.imageset/no-turn-allowed-3x.png)

This sign also resembles an MUTCD icon, but it’s pretty recognizable regardless. I think this icon was intended to resemble a No Left Turn sign, left being the most common direction of a turn restriction in countries that drive on the right. In countries that drive on the left, the equivalent would be a No Right Turn sign. The asset catalog is only capable of mirroring the icon based on the language’s writing direction, not the side of the road a country drives on. Fortunately, I don’t think this will cause a lot of confusion; it’s just a minor example of Americentrism in our icons.

**Comment by 1ec5** [comment]
@bsudekum, we should track down the original vector artwork and commit it to [navigation-ui-resources](https://github.com/mapbox/navigation-ui-resources/). I can refile this issue upstream once that happens.

**Comment by bsudekum** [comment]
@angel do you think you could PR the raw vector files used to create these icons to https://github.com/mapbox/navigation-ui-resources/?

**Comment by bsudekum** [comment]
Added source in https://github.com/mapbox/navigation-ui-resources/pull/10

**Comment by 1ec5** [comment]
mapbox/navigation-ui-resources#10 omits the “Missing Exit” icon. Do we still need it?

**Comment by 1ec5** [comment]
Fixed in #2421.
