### ISSUE TITLE
Managing integration tests in slow (CI) environments

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1187]
From #1175 

> 2 seconds timeout doesn't seem to be sufficient for Bitrise on a slow day like this
testDownloadingImageAgainAfterFirstDownloadCompletes, Asynchronous wait failed: Exceeded timeout of 2 seconds, with unfulfilled expectations: "Second Image Download".

A few thoughts:

We should minimize the number of tests with async expectations. In my experience working on the ImageRepository & related classes, the synchronous tests (using a test download operation) were just as useful, and in some cases more useful, than the NSURLProtocol-based tests which require async waiting due to multiple layers of async (URL loading queue, callback queue, etc.).  We will always need a couple such tests to ensure appropriate implementation of the URL loading delegate callbacks, but we should be opinionated toward synchronous test abstractions whenever and wherever feasible.

I propose we reduce the number of async expectations as far as we can, and perhaps let them wait indefinitely (or with a very very long timeout) on CI. Thoughts?

/cc @mapbox/navigation-ios

**Comment by frederoni** [comment]
> I propose we reduce the number of async expectations as far as we can, and perhaps let them wait indefinitely (or with a very very long timeout) on CI. Thoughts?

I agree. Perhaps synchronize them using a semaphore and maybe a performance test for the processing part if necessary/critical.

**Comment by bsudekum** [comment]
Noting, this failure has not appeared in some time now.

**Comment by akitchen** [comment]
I think Father Time took that as a taunt, b/c my latest push failed.

I might give the semaphore idea another look...
