### ISSUE TITLE
User puck is a little low when starting 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1198]
It fixes it self after a few moments though.

![image](https://user-images.githubusercontent.com/1058624/37006088-7eda247e-208b-11e8-938a-f4dbc4afa693.png)

/cc @JThramer @frederoni

**Comment by bsudekum** [comment]
![simulator screen shot - iphone x - 2018-03-05 at 16 05 19](https://user-images.githubusercontent.com/1058624/37006809-078d244e-208f-11e8-9c17-c3adba0485d7.png)

**Comment by JThramer** [comment]
I _may_ have an idea as to what's happening here. After the `NavigationMapView` appears in a navigation context (`NavigationViewController`), the `contentInset` mutates from `.bottom = 0` to `.bottom = 80.0`. When I override the `contentInset` reference in the `userAnchorPoint` getter and hard-code the inset with a `.bottom = 80.0`, the problem does not reproduce.

**Comment by bsudekum** [comment]
@JThramer You may have some luck by stepping through the commits in https://github.com/mapbox/mapbox-navigation-ios/pull/1186 & https://github.com/mapbox/mapbox-navigation-ios/pull/1184 as i think this bug came out of there.

**Comment by JThramer** [comment]
@bsudekum awesome, will 👀. Thanks for the tip!

**Comment by JThramer** [comment]
So after some investigation, it looks like [MGLMapView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L1002) might be involved in this. If `automaticallyAdjustsScrollViewInsets == true`, it will update the `contentInset` based off of it's `parentViewController`s' `topLayoutGuide` and `bottomLayoutGuide`. I bet that manually setting the `bottomLayoutGuide` as if the `WayNameView` was visible (whether it is or not) will fix this issue.
