### ISSUE TITLE
Decouple Telemetry/Feedback from the RouteController.

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1200]
_Context: This ticket originated as an [issue comment](https://github.com/mapbox/mapbox-navigation-ios/issues/1071#issuecomment-360568842) on #1071. This issue was opened to track movement on that idea after its' parent issue was closed._

Currently, our [telemetry/feedback engine](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/MMEEventsManager.swift) is [very tightly coupled](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift?utf8=✓#L982) to the [RouteController](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift).

Ideally, the `RouteController` would interact with the feedback/telemetry engine via A terse, opaque, "fire-and-forget" interface. Something that looks like this: 
```swift
Telemetry.shared.report(reroute: newRouteProgress, old: routeProgress)
```
or 
```swift
Telemetry.shared.report(userFeedback: .confusingInstruction, on: routeProgress, description: nil)
```
Past that point, the `RouteController` cares not about _how_ the report is delivered, with message queueing and the like. That's the telemetry engine's job. It should be fire-and-forget.

That way, the `FeedbackViewController` could also talk directly to the telemetry singleton without leaving the developer the task of manual message passing.

Currently, there is quite a lot of back and forth between the `RouteController` and the telemetry logic, but really the only three things that the feedback engine actually cares about in the route controller is the `routeProgress`, the current location and whether it's simulated, and the `sessionState`, which I think the Telemetry engine should own.

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
I like where this is headed -- 'fire and forget'. I would also like us to do more to encapsulate the steps required to build up an event contextually.

The `RouteController` extension you linked to probably deserves to become its own class. There is a lot of navigation-specific event information which needs to live somewhere other than the core mobile telemetry implementation; it just so happens to be partially consolidated in that extension but is also spread around the `RouteController` class itself. As the navigation use cases have matured so should our code...

I'd like to see the `events` property (and ensuing mutation of same) removed entirely from the `RouteController` into another class as a part of tackling this. I understand the OP is pseudo-code, but let's not assume interaction with a singleton. Instead, an abstraction (i.e. a protocol with more than one possible implementation) which declares the expected API interaction in a mostly if not entirely tell-based interface. This should help us improve our testability/test coverage as well as paving the path for more code reuse.

**Comment by akitchen** [comment]
I added myself to the ticket -- I would like a pair of us to work on this together to work through the object relationship design and desired architecture, so HMU!

**Comment by vincethecoder** [comment]
@JThramerm, @akitchen I'm also interested in the relationship design and desired architecture pairing.

**Comment by vincethecoder** [comment]
@JThramer 
>That way, the FeedbackViewController could also talk directly to the telemetry singleton without leaving the developer the task of manual message passing.

Instead of a singleton, we should consider using a valued-type (aka struct). In our `RouteController` we send feedback about the current road segment/maneuver, hence the `telemetry` as a valued-type would be the most ideal candidate.

**Comment by akitchen** [comment]
#1500 is replacing this, with the hope of better clarifying the work needed here.
