### ISSUE TITLE
Mapbox navigation for Swift 3.2

### ISSUE THREAD

**Issue by OlegGordiichuk** [mapbox/mapbox-navigation-ios#1205]
I need to install pod v0.10.1 to be able to work with Swift 3.2 version. 

But after install of the lib I receive swift compiler error from OSRMTextInstructions.

After investigation of the issue I can conclude that  Mapbox navigation v0.10.1 use wrong version of the sub dependency like  OSRMTextInstructions. How can I solve this ?

**Comment by bsudekum** [comment]
@OlegGordiichuk What version of osrm-text-instructions.swift does it install? The last version that supports swift 3.2 is v0.5.0.

You may have to specify this version in your podfile.

**Comment by bsudekum** [comment]
Please reopen if setting `osrm-text-instructions.swift ` to v0.5.0 does not work.
