### ISSUE TITLE
CompletionHandler documentation not expanded on click

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-navigation-ios#1209]
**Mapbox Navigation SDK version:** N/A

A developer using [`calculate(_:completionHandler:)
`](https://www.mapbox.com/mapbox-navigation-ios/directions/0.17.0/Classes/Directions.html#/c:@M@MapboxDirections@objc(cs)MBDirections(im)calculateDirectionsWithOptions:completionHandler:) will need to know the signature of the completion handler, but the documentation doesn't appear to provide that information.

The documentation [links](https://www.mapbox.com/mapbox-navigation-ios/directions/0.17.0/Classes/Directions.html#/s:16MapboxDirections0B0C17CompletionHandlera) the type name `CompletionHandler` in the method signature, but the link doesn't appear to go anywhere.

**Comment by jfirebaugh** [comment]
Ah, the documentation is in fact there -- this is actually a UI bug: clicking the [`CompletionHandler`](https://www.mapbox.com/mapbox-navigation-ios/directions/0.17.0/Classes/Directions.html#/s:16MapboxDirections0B0C17CompletionHandlera) link in the declaration:

```
@discardableResult open func calculate(_ options: RouteOptions, completionHandler: @escaping CompletionHandler) -> URLSessionDataTask
```

doesn't expand the relevant section above.

**Comment by JThramer** [comment]
👍

**Comment by jfirebaugh** [comment]
Can we keep this open to track the UI bug?

**Comment by JThramer** [comment]
Oh, my bad... yeah, the UI bug should be tracked. But wouldn't this ticket be better placed in [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift)?

**Comment by jfirebaugh** [comment]
Sure, happy to refile it there if that's better. I was just assuming that this was the best repo, since it's the `mb-pages` branch here that's published to https://www.mapbox.com/mapbox-navigation-ios/.

**Comment by JThramer** [comment]
😆 Ah, I see! My apologies, I was not aware of that.

**Comment by 1ec5** [comment]
The actual MapboxDirections.swift docset is generated from [this folder](https://github.com/mapbox/MapboxDirections.swift/tree/master/docs/) in MapboxDirections.swift. Either way, it’s a bug in the theme that’s used by both projects and the iOS and macOS SDKs. [This script](https://github.com/mapbox/MapboxDirections.swift/blob/master/docs/theme/assets/js/jazzy.js) appears in each repository and is based on [this script](https://github.com/realm/jazzy/blob/master/lib/jazzy/themes/fullwidth/assets/js/jazzy.js) upstream in jazzy. So this might be a bug upstream, depending on whether or not [our templates](https://github.com/mapbox/MapboxDirections.swift/tree/master/docs/theme/templates/) are at fault.
