### ISSUE TITLE
Stick to chosen alternative route after rerouting proactively

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1211]
As of #995, we stick to the chosen route (whether the primary route or an alternative route) when rerouting due to the user going off-route. However, RouteController can still ignore this choice when proactively rerouting based on the `reroutesOpportunistically` option.

/ref #818
/cc @bsudekum @brsbl

**Comment by bsudekum** [comment]
`checkForFasterRoute`  calls [`getDirections`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L741) which does actually seek to use the most similar route:

https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L848

@1ec5 it looks like we are trying to stick to the same route, or am I missing something here?

**Comment by 1ec5** [comment]
Did you mean to link to this method?

https://github.com/mapbox/mapbox-navigation-ios/blob/f839ae1bd9a58a48d133e8b3168177bbe2799286/MapboxCoreNavigation/RouteController.swift#L848

I’m not sure what it has to do with proactive rerouting.

**Comment by 1ec5** [comment]
Ah, you’re right, not sure how I missed that:

https://github.com/mapbox/mapbox-navigation-ios/blob/f839ae1bd9a58a48d133e8b3168177bbe2799286/MapboxCoreNavigation/RouteController.swift#L668
https://github.com/mapbox/mapbox-navigation-ios/blob/f839ae1bd9a58a48d133e8b3168177bbe2799286/MapboxCoreNavigation/RouteController.swift#L775
