### ISSUE TITLE
Add "routeControllerShouldReroute" delegate method

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#122]
In addition to supporting automatic rerouting by default, we should consider offering developers finer control of rerouting behavior with an optional `routeControllerShouldReroute` delegate method that returns a bool.

The default implementation would return true, which indicates that automatic rerouting is enabled.

```swift
func routeViewControllerShouldReroute(viewController: RouteViewController) -> Bool {
    // Possible scenarios:
    // Check if we've rerouted too frequently
    // Check if internet connection is spotty or cellular not allowed
    // Log that a user went off course and needed a reroute
    
    // Handle rerouting manually, perhaps with different routing options
    Directions.shared.calculate(options) { (waypoints, routes, error) in
        // Check if this reroute makes sense?
        
        // Possible hook to make your own re-routing announcement
        
        // manually update the navigation route
        viewController.route = routes.first!
    }
    
    return false // disables automatic rerouting
}
```

**Comment by wwajerowicz** [comment]
That's something that would be quite useful for me. I'm happy to have a go at implementing it and submit a PR.

I'd suggest adding a following method to the delegate:
``` 
@objc optional func navigationViewControllerShouldReroute(_ : NavigationViewController, fromLocation location: CLLocation)
```
and modifying `shouldReroute` method to something like this:
```
func shouldReroute(notification: NSNotification) {
        let location = notification.userInfo![RouteControllerNotificationShouldRerouteKey] as! CLLocation
        if navigationDelegate?.routeViewControllerShouldReroute?(self, fromLocation: location) != nil {
           return;
        }
             
  //continue as normal

}
    
```
That way, if someone implements that method in the delegate, they will be responsible for handling rerouting.

Let me know if that makes sense and I'll have a go at implementing it.

**Comment by frederoni** [comment]
@wwajerowicz A PR would be great.
Should we also pass the current `route` object to the receiver along with the last known location?

**Comment by wwajerowicz** [comment]
@frederoni I think `route` object would be useful, but it's possible to get it directly from `NavigationViewController`, so I'm not sure if it's necessary to pass it directly to the function.
