### ISSUE TITLE
Can user switch between mph and kph?

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1225]
Can user switch between mph and kph?
Thanks

**Comment by bsudekum** [comment]
@zijiazhai which part of the SDK are you referring to? Currently, there is no sense of mph/kph.

**Comment by zijiazhai** [comment]
One Netherlands user reported that his country's default unit is km, but the app shows mile in Netherlands.

**Comment by bsudekum** [comment]
@zijiazhai oh, the distance remaining. This is based on the `Locale` of the user's device. For example, if the user's device is set to `en-GB` and traveling in the Netherlands, they will still see miles. The distance is not localized to where the device actually is.

**Comment by zijiazhai** [comment]
@bsudekum 
Thanks a lot, that is what i thought. But the user says he already set the iPhone's region as Netherlands. 
I will talk to the user, and make sure he gets the right setting.

**Comment by bsudekum** [comment]
Re-open this if you'd like to discuss further.

**Comment by 1ec5** [comment]
By the way, you can also implement an option for the user to switch between miles and kilometers. When requesting a route, set the measurement units like this:

```swift
routeOptions.distanceMeasurementSystem = .metric
```
