### ISSUE TITLE
Distance label should accommodate more text without truncation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1237]
#1235 attempted to fix #1234 by reducing the minimum font size for autoscaling. Unfortunately, that isn’t enough to avoid truncation – or even left truncation – in some languages that have long abbreviations for customary units. Of particular concern are Swedish and Ukrainian. (Ukrainian doesn’t have a localization yet, but it is supported by the Directions API.)

Language | Metric | Customary
----|:--:|:--:
Hebrew | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639317-c7d4aa54-2c08-11e8-94c3-887ec24054ea.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639356-fcec37ca-2c08-11e8-830d-210726ed80de.png"> | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639430-472978ca-2c09-11e8-9126-eb15002238e0.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639511-983ed7fa-2c09-11e8-8f7f-ce234b89737d.png">
Russian | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639756-893ddf52-2c0a-11e8-911b-e25981fe9e37.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639768-96ccf702-2c0a-11e8-9a98-4168f0d297ca.png"> | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639783-a930894a-2c0a-11e8-866b-be7c063351ce.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639828-d9b5eb5a-2c0a-11e8-892b-aa3a44cd561d.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639797-bbb49020-2c0a-11e8-86c4-1a37e0f753c1.png">
Swedish | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639922-2bd251bc-2c0b-11e8-9d2b-ac4edd2ec7fc.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639931-3aa29cba-2c0b-11e8-99ac-8fb77ad458a1.png"> | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640008-871199ac-2c0b-11e8-8d82-1e88922152ba.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640021-933f24ce-2c0b-11e8-8478-13086b2d8505.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640030-a0832c2a-2c0b-11e8-868a-ee17b7bcfc29.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640060-ca8e20a6-2c0b-11e8-864a-4583991908ce.png">
Ukrainian | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640178-56641144-2c0c-11e8-8fc2-7dc0e0e893a3.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640190-669ba98c-2c0c-11e8-85c8-631d7a96122d.png"> | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640223-7a699e92-2c0c-11e8-82ae-d0ede7afb663.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640234-88a119ae-2c0c-11e8-898b-cda476f11b62.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640252-9d930c6e-2c0c-11e8-8441-a0d68807163f.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37640302-c7c96122-2c0c-11e8-863d-63c6fc0db67b.png">
Vietnamese | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639554-cfb5b208-2c09-11e8-9965-8e8fc84bfad3.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639651-3090e4a8-2c0a-11e8-8e15-ae452a6461f3.png"> | <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639675-4a785a4a-2c0a-11e8-89d4-e8920a4e4b6f.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639864-f92396ae-2c0a-11e8-9ceb-7f6e47a214f1.png"> <img width="375" alt="failed_testlongdistance 2x" src="https://user-images.githubusercontent.com/1231218/37639695-5b41c014-2c0a-11e8-9ab9-cb67c5c6c4c0.png">

I mentioned a possible fix in https://github.com/mapbox/mapbox-navigation-ios/issues/1234#issue-306117655:

> Some supported languages have even longer abbreviations for “meter” or “kilometer” than “公尺”. One possible solution would be to dynamically increase the horizontal space allotted to the maneuver icon and distance label based on the distance label’s intrinsic width. (The more fundamental issue is that we’re cramming such an important, dynamic label into such a tight spot, as if it doesn’t really matter.)

/cc @frederoni @JThramer

**Comment by vincethecoder** [comment]
@1ec5 in this scenario, we need to adjust the content `compression resistance`. Setting a higher priority on the distance label will make prevent the view from shrinking than the intrinsic content size.

/cc @frederoni @JThramer @mapbox/navigation-ios

**Comment by vincethecoder** [comment]
@1ec5 Should we also involve the UX designer, Chris Ballard with Navigation Data?
