### ISSUE TITLE
RouteViewController should use an initializer rather than a static function on NavigationUI

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#124]
Is there any reason why we prefer to instantiate a RouteViewController this way

```swift
let viewController = NavigationUI.routeViewController(for: route)
```

vs this way?

```swift
let viewController = RouteViewController(for: route)
```

/cc @frederoni

**Comment by 1ec5** [comment]
Previous discussion in https://github.com/mapbox/mapbox-navigation-ios/pull/43#discussion_r101695620.

**Comment by 1ec5** [comment]
The current [`NavigationUI.routeViewController(for:directions:)`](https://github.com/mapbox/mapbox-navigation-ios/blob/78c1d6be5cca50b9d768ce436d894f6e35dfc174/MapboxNavigation/NavigationUI.swift#L67-L79) implementation is simple enough that I think we could fold it into RouteViewController as a factory method. The signature would look identical to how it looks now. The main benefit would be one less class to think about when setting up the view controller.

If an initializer is strictly necessary, then we could implement a factory method in Objective-C that gets bridged to Swift as an initializer. Something like this:

```objc
+ (instancetype)routeViewControllerForRoute:(MBRoute *)route directions:(nullable MBDirections *)directions {
    MGLPointAnnotation *destination = [[MGLPointAnnotation alloc] init];
    destination.coordinate = route.coordinates.lastObject;
    
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Navigation" bundle:[NSBundle navigationUI]];
    MBRouteViewController *routeViewController = (MBRouteViewController *)[storyboard instantiateInitialViewController];
    NSAssert([routeViewController isKindOfClass:[MBRouteViewController class]]);
    
    controller.route = route;
    controller.destination = destination;
    controller.directions = directions;
    
    return controller;
}
```

**Comment by frederoni** [comment]
AFAIK, Objective-C header files can't import the generated ModuleName-Swift.h-files, hence no way to add public categories on Swift classes within the same target. Though, importing `<MapboxNavigation/MapboxNavigation-Swift.h>` in the header seems to be working as long as it's not added to the umbrella header.

On the other hand, we're expecting a new design so there's a chance we can get rid of the Pulley altogether.

**Comment by 1ec5** [comment]
Moving the existing factory method into RouteViewController would address the oddity @ericrwolfe pointed out while avoiding the question of implementing the interface using a storyboard versus code, which is hopefully a separate issue.
