### ISSUE TITLE
Add convenience initializer for letting the UI request directions

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#125]
We should add a way to to make the Navigation UI as simple to use as possible, needing only an optional origin (your current location if nil) and a destination. 

Something like this?
```swift
RouteViewController(origin: Waypoint? = nil, destination: Waypoint, routingMode: MBDirectionsProfileIdentifier? = .automotive)
```

This would make getting started as easy as:

```swift
let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 38.8977, longitude: -77.0365), name: "White House")
let viewController = RouteViewController(destination: destination) 
present(viewController, animated: true, completion: nil)
```

The navigation UI would calculate the needed route internally (and likely need to show some sort of loading indicator).

We'd still support passing in a `Route` object should the developer want full control over routing, or if they wanted to display a route on their own overview screen.

**Comment by 1ec5** [comment]
We could add an initializer with the following signature to NavigationViewController:

```swift
required public init(routeOptions: RouteOptions, directions: Directions = Directions.shared)
```

NavigationViewController would assume responsibility for issuing the request. The developer could still call the initializer that accepts a Route if they’ve already issued the request and want to avoid a delay showing the route in the navigation view controller. NavigationViewController could also set any options it depends on, such as `routeShapeResolution` and `includeSteps`, without the developer having to worry about those details.

**Comment by 1ec5** [comment]
Related: #528.
