### ISSUE TITLE
Cartfile issue

### ISSUE THREAD

**Issue by pdp2015** [mapbox/mapbox-navigation-ios#1255]
xcode is saying when clicking clean: No such module "MadbpxDirections'

**Comment by bsudekum** [comment]
@pdp2015 Can you paste the output in your terminal from when you run `carthage update --platform ios`?

**Comment by pdp2015** [comment]
**i get this:** 

MacBook-2:Map andrewferriby$ carthage update --platform iOS
Parse error: unexpected trailing characters in line: binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 3.7
MacBook-2:Map andrewferriby$

**Then if i use:**

pod repo update && pod install

I get this:

MacBook-2:Map andrewferriby$ pod repo update && pod install
Updating spec repo `master`
  $ /usr/bin/git -C /Users/andrewferriby/.cocoapods/repos/master fetch origin
  --progress
  remote: Counting objects: 9, done.        
  remote: Compressing objects: 100% (9/9), done.        
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     e18a210641e..3043e628b06  master     -> origin/master
  $ /usr/bin/git -C /Users/andrewferriby/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/andrewferriby/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at 3043e628b06 [Add] EasyCalls 1.2.0

CocoaPods 1.5.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0.beta.1

Analyzing dependencies
Downloading dependencies
Using Mapbox-iOS-SDK (3.7.6)
Using MapboxCoreNavigation (0.15.0)
Using MapboxDirections.swift (0.17.0)
Using MapboxMobileEvents (0.3.1)
Using MapboxNavigation (0.15.0)
Using MapboxSpeech (0.0.1)
Using Polyline (4.2.0)
Using Solar (2.1.0)
Using Turf (0.0.4)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 9 total pods installed.

[!] Automatically assigning platform `ios` with version `9.0` on target `Example-Objective-C` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `ios` with version `9.0` on target `Example-Swift` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `ios` with version `9.0` on target `MapboxCoreNavigation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `ios` with version `9.0` on target `MapboxNavigation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `Example-Swift [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Example-Swift/Pods-Example-Swift.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Example-Swift [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Example-Swift/Pods-Example-Swift.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
MacBook-2:Map andrewferriby$

**Comment by bsudekum** [comment]
@pdp2015 okay, and does the project build?

**Comment by pdp2015** [comment]
Nope it fails coz it cant find the missing modules that cant be found.

Do you have a copy of your pod file?

**Comment by bsudekum** [comment]
No, that should not be necessary.

**Comment by iStig** [comment]
i  fix this issue.  maybe you should upgrade carthage. https://stackoverflow.com/questions/43550724/carthage-parse-error

**Comment by bsudekum** [comment]
Please re-open if you still have issues.
