### ISSUE TITLE
End of route view controller placement

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1259]
![image](https://user-images.githubusercontent.com/1058624/37921659-4b4eb9d0-30df-11e8-8c9c-094008167b3b.png)

@JThramer having a hard time reproducing, but I think this can happen if the route is finished in the background. Seen it ~3 times recently.

**Comment by bsudekum** [comment]
Had this occur again 
![image](https://user-images.githubusercontent.com/1058624/39441508-0a557924-4c63-11e8-9dbe-89ef89614f53.png)

**Comment by bsudekum** [comment]
Had this happen again, really unsure how to reproduce:

![image](https://user-images.githubusercontent.com/1058624/40011592-2128bb16-575d-11e8-9c22-446c0eaa27a4.png)

![image](https://user-images.githubusercontent.com/1058624/40011599-2649aac4-575d-11e8-9bc9-ede5f774ef76.png)

**Comment by JThramer** [comment]
oof, what the heck?

**Comment by bsudekum** [comment]
This looks like the culprit:

https://github.com/mapbox/mapbox-navigation-ios/blob/0c0e54e4bd93d4c30f5e2f0118139b7571852a19/MapboxNavigation/RouteMapViewController.swift#L940

You can reproduce this issue by starting a route, open a new app, open the keyboard, go back into navigation, end the route.
