### ISSUE TITLE
Rename alert levels

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#126]
We should make our alert level enum values more meaningful.

Right now we have (from the readme):
* `none`
* `depart` - Emitted while departing origin
* `low` - Emitted directly after completing the maneuver
* `medium` - Emitted when the user has 70 seconds remaining on the ~route~ maneuver
* `high` - Emitted when the user has 15 seconds remaining on the ~route~ maneuver
* `arrive` - Emitted when the user arrives at destination

Particularly we should rename `low`, `medium`, and `high` to be more descriptive, perhaps:
* `low` -> `completedManeuver`
* `medium` -> `approachingManeuver`
* `high` -> `startingManeuver`

/cc @bsudekum @1ec5

**Comment by 1ec5** [comment]
@willwhite has some opinions on this. 😛

**Comment by 1ec5** [comment]
In the past, I’ve used the terms “post-maneuver prompt”, “advance prompt”, and “impending prompt” for low, medium, and high alerts, respectively. (Incidentally, Apple Maps has a fourth prompt, which occurs 10 miles ahead of the maneuver.)

I think the low/medium/high terminology could work well if we describe it as “urgency” instead of “alert level”. Unfortunately, `depart` and `arrive` throw a bit of a wrench into that naming system.

**Comment by ericrwolfe** [comment]
From the perspective of an external developer who'd need to handle these notifications, this ordered alert level naming feels arbitrary and confusing.

As you've noted with Apple Maps announcing a fourth prompt (`medium-low`?), developers using our navigation components to build custom navigation apps might have different requirements around the number and priority of notifications and announcements to end users.

In terms of clarity and documentation, I think we should try to be explicit with naming, and leave room for flexibility with future customers and use cases.

**Comment by TCOA** [comment]
Could you please add something to the documentation on how to access these alert levels?  I've found the items in the NotificationCenter, though nothing on how to access these Alerts (which I am very interested in - in particular, the 'arrived' one - as I need to trigger some other events from them).

Also, a quick note (as it affects documenting in this area) - RouteControllerAlertLevelDidChange states "Notification contains 3 keys:", though only 2 are listed.
