### ISSUE TITLE
Developers can provide their own way name to populate the label below the puck

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1269]
This will allow developers to easily add/display a current street label, such as:

![img_402cabd8e03c-1](https://user-images.githubusercontent.com/378648/38116355-89e35e6c-3364-11e8-9d27-5e4963785b33.jpeg)

/cc @1ec5

**Comment by bsudekum** [comment]
The gist of what is happening here:

We need to know the make up of a vector tile source before we can dig into to grab names off of roads. We first check to see if mapbox streets is already in the style, if not we add it:

https://github.com/mapbox/mapbox-navigation-ios/blob/3a3d7e9dc89887795904dd8350d0453286b3aab8/MapboxNavigation/RouteMapViewController.swift#L698-L709

@1ec5 @akitchen just to verify, the issue we're seeing is that if someone is not using a Mapbox style that does not contain mapbox streets, the current way name label is not shown?

Perhaps we could make this a little bit looser by always checking for a layer `name` in the style sheet. We know that mapbox streets will have this, and if a developer is using their own style we can ask them to conform to this.

**Comment by 1ec5** [comment]
Maybe we can completely outsource the job of populating this label to the developer: add a delegate method that returns the road name at a given location. The default implementation would continue to query the Mapbox Streets source, as long as that source is being used in the current style. But if this delegate method is implemented, then the application would be responsible for supplying a road name on each location update. The road name doesn’t necessarily have to come from feature querying, so this could be an interesting customization hook.

**Comment by bsudekum** [comment]
I'd be okay with a delegate here.

**Comment by ksummerill** [comment]
@akitchen thanks for filing this! Is there a timeline for this work that I can share with Hitta?

**Comment by akitchen** [comment]
I like the idea of using a delegate for this -- it seems like a looser coupling and yes, it does allow more optionality for putting other text in there too... which could be desirable in certain use cases.

**Comment by akitchen** [comment]
@vincethecoder Please don't forget to include at least a feature-level or integration test demonstrating this functionality. It seems like this feature should start with a few tests for things like [this](https://github.com/mapbox/mapbox-navigation-ios/pull/1309/files/5cadc64faa3b01d8ad0eb176d456e018e32e23a4#diff-292af689ce88d5b5aa06966456abc0e9), [this](https://github.com/mapbox/mapbox-navigation-ios/pull/1309#discussion_r182548329), [this](https://github.com/mapbox/mapbox-navigation-ios/pull/1309#discussion_r182540863), etc. Basically any place the code is making a decision should include some form of test, and we also want at least one test which ensures things are properly wired up.
