### ISSUE TITLE
Add support for custom fonts in NavigationUI

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#127]
UIFont has an init function
```swift
init?(name fontName: String, size fontSize: CGFloat)
```
so we could accept the font name as a string and use our default font sizes internally.

As for the font string, we could either accept a single "font family" string and try to match up specific font styles under the hood (bold/heavy/italic/oblique/thin/etc), or have multiple font name properties for specific font styles in the UI (`fontName`, `boldFontName`, `italicFontName`).

/cc @frederoni

**Comment by frederoni** [comment]
Let's just take `UIFont` for better accessibility support. By default, we use `primaryFont: UIFont` and perhaps secondaryFont. Also expose all labels and buttons so developers can set the font on them individually.
