### ISSUE TITLE
Customising NavigationMapView For iOS

### ISSUE THREAD

**Issue by rahulactivecaler** [mapbox/mapbox-navigation-ios#1279]
Can we use NavigationMapView class directly in our project? I am unable to use it directly. I am assigning the class on storyboard but the app crashes. Please suggest me I am wanting to design a screen that has a view at the bottom of the navigation screen. You can go to this link and find out what is my exact requirement.
What I need = > https://www.dropbox.com/s/p4oomt9fnza8q2a/navigation.png?dl=0

What is actually given in example = > https://www.dropbox.com/s/p4oomt9fnza8q2a/navigation.png?dl=0

![navigation](https://user-images.githubusercontent.com/38035066/38247386-c5b8806e-3762-11e8-832c-e7f07a9da752.png)

**Mapbox Navigation SDK version:**
0.16

**Comment by frederoni** [comment]
What you need and what is given seems to be pointing to the same image. 🤔 

> I am assigning the class on storyboard but the app crashes

Can you provide a crash log?

**Comment by rahulactivecaler** [comment]
My application is not crashing, but I need you help in customising NavigationMapView screen. I want to customise the screen like below screen. Please share me the step to do so.

The attached screen is taken from android device.
![navigation](https://user-images.githubusercontent.com/38035066/38288777-52d50db8-37f0-11e8-9ea1-5ec9384929c2.png)

**Comment by rahulactivecaler** [comment]
Can we only have maximum 3 coordinate in NavigationRouteOptions. While creating object of NavigationRouteOptions class with 4 to 5 coordinate it show some error in logs. **"The operation couldn’t be completed. Too many coordinates; maximum number of coordinates is 3."**

Or in you premium paid version you have this service?

**Comment by frederoni** [comment]
The traffic routing profile (`MBDirectionsProfileIdentifierAutomobileAvoidingTraffic`) currently only supports 3 waypoints/coordinates but the other supports up to 25. Check out [api-documentation/#directions](https://www.mapbox.com/api-documentation/#directions) for more info.

**Comment by rahulactivecaler** [comment]
How can we update the destination in NavigationViewController object. Let say there are Points A, B, C and D, and first we need to reach from point A to B then after reaching B I need to update the map with new destination as C and then after reaching to C need to update destination as D and soon.

Currently I am using MBDirectionsProfileIdentifierAutomobileAvoidingTraffic.

**Comment by rahulactivecaler** [comment]
Embedded navigation in no more available in the git Repository you shared. Request you to please share the example for new version MapBox SDK.
