### ISSUE TITLE
Investigate & profile performance of StepsViewController

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1291]
A recent anecdotal report of sluggish scrolling of this table reminds us: let's profile scrolling this table view on a long route & identify performance hotspots &/or a reasonable baseline. Timebox this, with the goal of 

 - [ ] Establishing an XCTestCase which could help us set a performance baseline for scrolling this view, in order to identify future deltas
 - [ ] Addressing any relatively simple issues / low-hanging fruit, and/or
 - [ ] Cutting additional ticket(s) describing identified performance issues which might involve a more complicated solution

**Comment by akitchen** [comment]
It was suggested to use SFO -> LA as an example for this.

**Comment by vincethecoder** [comment]
@akitchen in efforts to establish an XCTestCase to set the performance baseline for scrolling the steps table view, we could begin with `StepsViewController.updateCell(_:at:)` which has a complex processing when the [instruction view secondary label's instruction gets set](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/StepsViewController.swift#L221). 

---
**More context**: Setting that instruction property, invokes `InstructionPresenter.attributedText()` which in turn processes this relatively complex logic [fittedAttributedComponents().forEach { string.append($0) }](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/InstructionPresenter.swift#L33) for each steps table view cell.

**Comment by vincethecoder** [comment]
**UPDATE** 
This proposed performance baseline testing approach also covers recently merged development efforts in PR #1272 

/cc @JThramer @akitchen
