### ISSUE TITLE
MapboxNavigation depends on private compactMap(_:) method

### ISSUE THREAD

**Issue by srikanthsrnvs** [mapbox/mapbox-navigation-ios#1295]
I keep running into this error when building;

'compactMap' is inaccessible due to 'internal' protection level

I am using mapbox navigation 0.16.1 via cocoapods on latest xcode and swift.

**Comment by frederoni** [comment]
Hm, the CocoaPods pre-flight test did catch this bug but CI completed successfully https://www.bitrise.io/build/0cfd54518dc966e9

**Comment by srikanthsrnvs** [comment]
Still not fixed for me.. Project team also says that their builds stopped working after a pod update.

**Comment by 1ec5** [comment]
Yes, sorry, to be clear, https://github.com/mapbox/mapbox-navigation-ios/issues/1295#issuecomment-380916749 was a diagnosis of the problem; the fix is coming in #1296. If you need a fix immediately, you can point your Podfile to that branch instead of the latest release.

**Comment by 1ec5** [comment]
The fix is in v0.16.2 – thanks for reporting the issue @srikanthsrnvs!

**Comment by srikanthsrnvs** [comment]
no worries!
