### ISSUE TITLE
Add Objective-C class prefix to public classes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#130]
The following classes are exposed publicly but pollute the class namespaces in Objective-C because they don’t have the `MB` class prefix via the `@objc` attribute:

* [ ] DashedLineView (should be `@objc(MBDashedLineView)` or private)
* [ ] DistanceFormatter (should be `@objc(MBDistanceFormatter)`)
* [ ] NavigationMapView (should be `@objc(MBNavigationMapView)`)
* [ ] RouteStepFormatter (should be `@objc(MBRouteStepFormatter)`)
* [ ] RouteVoiceController (should be `@objc(MBRouteVoiceController)`)
* [ ] StyleButton (should be `@objc(MBStyleButton)` or private)
* [ ] StyleKitArrows (should be `@objc(MBStyleKitArrows)` or private)
* [ ] StyleLabel (should be `@objc(MBStyleLabel)` or private)
* [ ] TurnArrowView (should be `@objc(MBTurnArrowView)` or private)

Same with the following protocols:

* [ ] RouteViewControllerDelegate (should be `@objc(MBRouteViewControllerDelegate)`)

And:

* [ ] All the constants and functions in Constants.swift
* [ ] `TextStyle` (should be `@objc(MBTextStyle)` or private)

/cc @bsudekum @frederoni

**Comment by frederoni** [comment]
If the app that is using the library is using components individually in a storyboard, (like Example-Swift) they have to specify the obj-c prefixed class name, even though the app and the library are written in Swift. I assume this minor drawback is acceptable but what's blocking right now is that  Navigation.storyboard can't find either the prefixed obj-c class or the swift class when using `@objc`.

I think we should move away from using storyboards inside libraries, that would probably make it easier to fix issues like https://github.com/mapbox/mapbox-navigation-ios/issues/124 and https://github.com/mapbox/mapbox-navigation-ios/issues/125

**Comment by 1ec5** [comment]
> Navigation.storyboard can't find either the prefixed obj-c class or the swift class when using `@objc`.

Unlike Swift classes, Objective-C classes aren't namespaced by module. If you clear out the module field in the Custom Class inspector property, it should be able to find the class by its Objective-C name.
