### ISSUE TITLE
NavigationViewController shows only 3 legs for 4 waypoints

### ISSUE THREAD

**Issue by srikanthsrnvs** [mapbox/mapbox-navigation-ios#1303]
I have 4 waypoints, a, b , c, d. I also have my initial location as x.

I have a list of waypoints [a, b , c, d] but x is not included in this list since it isnt a waypoint, just my initial location.

I want my navigationViewController to show my directions from x -> a -> b -> c -> d and use the following code;

let waypointList = [a, b , c, d]
let options = NavigationRouteOptions(waypoints: waypointList, profileIdentifier: .automobile)
                    let task = Directions.shared.calculate(options, completionHandler: { (waypoints, routes, error) in
                        if error == nil{
                            print("route", (routes?.first)!.routeOptions)
                            let navigation = NavigationViewController(for: (routes?.first)!)
                            self.present(navigation, animated: true, completion: nil)
                        }
                    })

However, my navigationViewController is showing me directions from x -> b -> c -> d

Why does it work this way and skip my first waypoint origin? is this a bug? maybe a bug in my own code?

**Comment by 1ec5** [comment]
The list of waypoints needs to include the initial waypoint. The initial waypoint is used as the beginning of the route, not the first destination. MapboxDirections.swift doesn’t automatically insert the user’s current location, because some applications may require a route that doesn’t start from that location.
