### ISSUE TITLE
ERROR_CGDataProvider_BufferIsNotReadable crash

### ISSUE THREAD

**Issue by riserpete** [mapbox/mapbox-navigation-ios#1305]
**Mapbox Navigation SDK version: iOS 3.7.4**

Ever since updating to version 3.7+ (in this case 3.7.4), I am experiencing crashes in my app with a somewhat not really expressive Stack Trace. Searching for `ERROR_CGDataProvider_BufferIsNotReadable` brought up a lot of hints to a memory leak. It was also indicated that crashes usually only occur on (iPhone) Plus devices and the iPhone X, which is also true for my case. Seems to be some kind of Image drawing/memory issue....?

[crash.txt](https://github.com/mapbox/mapbox-navigation-ios/files/1915893/crash.txt)

**Comment by frederoni** [comment]
It looks like this crash involves the Maps SDK, not the Navigation SDK. Would you mind opening an issue in https://github.com/mapbox/mapbox-gl-native and closing this one?

**Comment by riserpete** [comment]
arrr sorry! :)

**Comment by friedbunny** [comment]
→ https://github.com/mapbox/mapbox-gl-native/issues/11690
