### ISSUE TITLE
Multiple waypoint bug

### ISSUE THREAD

**Issue by srikanthsrnvs** [mapbox/mapbox-navigation-ios#1306]
Im using the latest version of mapbox with xcode. I have a list of waypoints and instatiate a navigationViewController with those waypoints. Two issues arise from this;

1) When a waypoint has been visited, it dissapears from the map, and the next waypoint to be visited shows a little circe with a 1, even though this is the second waypoint. Similarly, after visiting the second waypoint, it dissapears and the next waypoint shows on the map as a 1, when it is actually the third waypoint.

2) The voice instructions tell me that im about to visit my first destination even though it might be the 2nd, third or fourth. It only works for the first, and last.

3) Is the tiny circle with the waypoint number an annotation? if so, how can I change its appearence based on my waypoint.name? is there a way to access waypoint through viewForAnnotation?

**Comment by bsudekum** [comment]
Hi @srikanthsrnvs, I'm looking into this issue now.

**Comment by srikanthsrnvs** [comment]
I think I’ve found the reason. Everything works fine when on route, but if you press the button to show all the route waypoints, and then switch back to resume, it screws things up.

**Comment by srikanthsrnvs** [comment]
So the issue is this;


When on multiwaypoint route,

If I press the button to show the entire route after visiting the first waypoint, and then press resume, when it arrives at the next waypoint, it thinks I have arrived at my first waypoint, when it is actually the second. Similarly, for third, fourth etc.

Sometimes the destination annotation also disappears.
