### ISSUE TITLE
NavigationMapView randomly doesn't show all routes

### ISSUE THREAD

**Issue by riserpete** [mapbox/mapbox-navigation-ios#1308]
**Mapbox Navigation SDK version: 0.16.2**

I am calling `navigationMapView.showRoutes(routes)` but after every second request or so, it only shows one of two alternatives (sometimes 2 of 3 alternatives). The "hidden" route on the map is still tappable and can be selected, it just doesn't show up in the grey-unselected-state.

I attached a video of my use case and I also tried it with the official example project. Some kind of issue occurs in this example as well, not sure if it's the same.

[vids.zip](https://github.com/mapbox/mapbox-navigation-ios/files/1923496/vids.zip)

**Comment by bsudekum** [comment]
This should be fixed in v0.17.0.
