### ISSUE TITLE
turnbyturn navigation issue

### ISSUE THREAD

**Issue by DawidMagnus** [mapbox/mapbox-navigation-ios#1317]
Hi, 

I am now using mapbox turn by turn navigation.

By the way, map doesn't show highlighted blue road sometimes.

What's the reason? Please help me.

**Comment by frederoni** [comment]
Would you mind sharing a bit more information, perhaps a code snippet?
Are you building a custom navigation experience or are you using the NavigationViewController? Custom style, custom tiles?

**Comment by DawidMagnus** [comment]
Here is my code.
@property (strong, nonatomic) MBNavigationViewController *navigationViewController;

- (void)initNavigationViewController {
    MBSimulatedLocationManager *locationManager = [[MBSimulatedLocationManager alloc] initWithRoute:_route];
    _navigationViewController = [[MBNavigationViewController alloc] initWithRoute:_route
                                                                       directions:[MBDirections sharedDirections]
                                                                            style:nil
                                                                  locationManager:locationManager];

    _navigationViewController.voiceController.volume = 1.0;
    _navigationViewController.view.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height);
    
    _navigationViewController.mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    
    // Set the map’s center coordinates and zoom level.
    if (priorCamera == nil){
        [_navigationViewController.mapView setCenterCoordinate:currentCoordinate
                                                     zoomLevel:12
                                                      animated:NO];
    }else{
        [_navigationViewController.mapView setCamera:priorCamera animated:NO];
    }
    _navigationViewController.mapView.delegate = self;
    _navigationViewController.delegate = self;
    
    [self.view insertSubview:_navigationViewController.view atIndex:0];
}

**Comment by Nirajpaul2** [comment]
Hi , we are try to install pod for the navigation but i am failed. i posted bug in the stackoverflow here is the link https://stackoverflow.com/questions/50063034/mapbox-pod-installation-failure. Please help me to implement mapbox navigation.  We are follow the tutorial https://www.mapbox.com/mapbox-navigation-ios/navigation/0.16.2/

**Comment by bsudekum** [comment]
@Nirajpaul2 do you have `use_frameworks!` at the top of your podfile? Can you also open a new ticket? The issue you posted does not seem related to the issue here.

**Comment by Nirajpaul2** [comment]
Thanks to replay me, I have solved the issues installed mapbox by carthage.
