### ISSUE TITLE
Getting ETA

### ISSUE THREAD

**Issue by rahulactivecaler** [mapbox/mapbox-navigation-ios#1322]
I am currently using Embedded navigation in my application. I want my map to send ETA to my server while moving. We are getting ETA in BottomBannerView, so how can we access of the objet of that label ? Or is there any method available that tells us about the ETA. We need to update the ETA to our server every second.

**Comment by frederoni** [comment]
The `RouteController` will post notifications with the progress and current location on each location update. You can observe these notifications and grab the ETA from there.

```swift
override public func viewDidLoad() {
    super.viewDidLoad()
    NotificationCenter.default.addObserver(self, selector: #selector(progressDidChange(notification:)), name: .routeControllerProgressDidChange, object: nil)
}


@objc func progressDidChange(notification: NSNotification) {
    let routeProgress = notification.userInfo![RouteControllerNotificationUserInfoKey.routeProgressKey] as! RouteProgress
    let location = notification.userInfo![RouteControllerNotificationUserInfoKey.locationKey] as! CLLocation
    let eta = routeProgress.durationRemaining
}
```

**Comment by JanTG1** [comment]
@frederoni "RouteControllerNotificationUserInfoKey" seems to have been renamed, could you please update your answer?
