### ISSUE TITLE
Test failures in ImageDownloaderTests — Semaphore timed out

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1327]
[This Bitrise build](https://www.bitrise.io/build/3b057052f7f1513a) for #1076 experienced a slew of test failures related to semaphores in the image downloader tests:

<details>
<summary>Test failures</summary>

MapboxNavigationTests.ImageDownloaderTests
  testDownloadingAnImage, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/ImageDownloaderTests.swift:49
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
  ```
  testDownloadingImageAgainAfterFirstDownloadCompletes, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/ImageDownloaderTests.swift:95
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testDownloadingSameImageWhileInProgressAddsCallbacksWithoutAddingAnotherRequest, failed - Timeout occurred on runUntil(condition:pollingInterval:until:)
  /Users/vagrant/git/MapboxNavigationTests/ImageDownloaderTests.swift:118
  ```
        guard (timeout >= DispatchTime.now()) else {
            XCTFail("Timeout occurred on \(#function)")
            return
  ```
MapboxNavigationTests.ImageRepositoryTests
  test_imageWithURL_downloadsImageWhenNotCached, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/ImageRepositoryTests.swift:27
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
  test_imageWithURL_prefersCachedImageWhenAvailable, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/ImageRepositoryTests.swift:27
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
MapboxNavigationTests.InstructionsBannerViewIntegrationTests
  testDelimiterDisappearsOnlyWhenAllShieldsHaveLoaded, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift:51
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
  testDelimiterIsHiddenWhenAllShieldsAreAlreadyLoaded, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift:51
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
  testDelimiterIsHiddenWhenAllShieldsAreAlreadyLoaded, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift:51
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
  testDelimiterIsShownWhenShieldsNotLoaded, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift:51
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
  testExitBannerIntegration, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewIntegrationTests.swift:51
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
    }
  ```
MapboxNavigationTests.InstructionsBannerViewSnapshotTests
  testAbbreviateInstructions, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testAbbreviateInstructionsIncludingDelimiter, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testAbbreviateWestFremontAvenue, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testAdjacentShields, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testExitShields, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testInstructionsAndNextInstructions, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testLongDistance, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testMultilinePrimary, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testPrimaryShieldAndSecondary, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testSinglelinePrimary, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testSinglelinePrimaryAndSecondary, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testSweEngLongDistance, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
  testUkrainianLongDistance, XCTAssertTrue failed - Semaphore timed out
  /Users/vagrant/git/MapboxNavigationTests/InstructionsBannerViewSnapshotTests.swift:32
  ```
        let semaphoreResult = semaphore.wait(timeout: XCTestCase.NavigationTests.timeout)
        XCTAssert(semaphoreResult == .success, "Semaphore timed out")
        
  ```
	 Executed 48 tests, with 23 failures (0 unexpected) in 12.279 (12.406) seconds

</details>

/ref #1311
/cc @akitchen @JThramer

**Comment by akitchen** [comment]
Something doesn't seem to add up here. How could we have so many timeouts logged within a test run of ~12 seconds?

We should try `.distantFuture` as the deadline on CI and see what really happens -- is this an unanticipated call order or is Circle somehow strongly deprioritizing work that happens off the main thread? Are the deadline `DispatchTime`s somehow being calculated too early?

**Comment by akitchen** [comment]
As I said to @JThramer just now, we declare a `static let`, which is calculated once and memoized. But time keeps on ticking, as the song goes, so this value needs to either be `.distantFuture` or calculated, ahem, just in time.

**Comment by JThramer** [comment]
![Did I do that?](https://i.imgur.com/dy0bSTi.gif)
