### ISSUE TITLE
Unable to update MapboxDirections.swift to 0.20.0

### ISSUE THREAD

**Issue by Jauzee** [mapbox/mapbox-navigation-ios#1332]
**Mapbox Navigation SDK version:** 0.16.2

Just checked on a new test project. CocoaPods resolves `MapboxDirections.swift` on **0.19.1** even if `MapboxCoreNavigation` depends on **0.20.0**

**Comment by frederoni** [comment]
Did you run `pod repo update`? 0.20.0 is pushed to CocoaPods public repo. 🤔

**Comment by Jauzee** [comment]
@frederoni yes, just updated once again. I see that it's there, but can't figure out why it doesn't update. Tried to manually specify each dependency, but then I faced other bugs.

**Comment by frederoni** [comment]
Actually, mapbox-navigation-ios v0.16.2 should depend on MapboxDirections.swift v0.19.1 which it does.
mapbox-navigation-ios v0.17.0 will depend on v0.20.0 of the MapboxDirections SDK.

**Comment by Jauzee** [comment]
@frederoni I was confused by the updated podspec. Thanks!
