### ISSUE TITLE
latitude must be between -90 and 90

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1333]
latitude must be between -90 and 90

I saw this crash a few times, it happens in both 0.15 and 0.16.2

**Comment by zijiazhai** [comment]
![snip20180425_6](https://user-images.githubusercontent.com/10751092/39272376-58cd25b8-48a1-11e8-9fcc-052968ee4b46.png)
![snip20180425_7](https://user-images.githubusercontent.com/10751092/39272435-7ffe45ea-48a1-11e8-9084-6b879f86f033.png)
I try to get the userlatitude in func mapViewDidFinishRenderingMap after users launch the app. Is that the problem userLatitude == -180?

**Comment by 1ec5** [comment]
`kCLLocationCoordinate2DInvalid` is located at −180° latitude and −180° longitude. The user location’s coordinate may be invalid because the device is unable to obtain a GPS location, or it’s too soon for the map view to begin receiving the location, or the user has denied Location Services permissions.

**Comment by bsudekum** [comment]
@zijiazhai what's the use case for a latitude greater than 90? IMO, this is expected as it's an invalid location.

**Comment by 1ec5** [comment]
It’s possible that the map finished rendering before the device got its first user location update. Until the first user location update arrives, you’ll have to check `CLLocationCoordinate2DIsValid()` and fall back to another value. If no fallback value makes sense in this situation, consider delaying this code until the first location update comes in.

Note that none of this is necessary if you use NavigationViewController: it has its own independent implementation of the user location view, and you don’t need to set the visible coordinates manually.

**Comment by zijiazhai** [comment]
@1ec5 Thanks for the detail information, I agree with that delaying the code until the first location update comes in.
I setVisibleCoordinateBounds when requesting route which is before presenting navigationViewController.
The bug is fixed, THANKS

**Comment by gulzatique** [comment]
hi all, @1ec5 could you show an example of code which would help to avoid this kind of errors? 

I tried to check CLLocationCoordinate2DIsValid() in mapViewDidFinishLoadingMap(_ mapView: MGLMapView) and even added a delay(2 sec). Few delays did not give any results, still CLLocationCoordinate2DIsValid() was invalid

**Comment by rameshvaduka9** [comment]
The following is helped to me

https://docs.mapbox.com/help/glossary/lat-lon/#:~:text=Different%20Mapbox%20services,latitude%2Clongitude.
