### ISSUE TITLE
userCourseView.y value

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1334]
Hi, 
I am wondering how to change the userCourseView.y, so when users present my bottomViewController, they can still see the userCourseView like the image below.
Thanks
![wechatimg31](https://user-images.githubusercontent.com/10751092/39209947-e83a79ba-47cc-11e8-93b5-385f2eba0bc1.jpeg)

**Comment by frederoni** [comment]
There's a `navigationViewController(_:mapViewUserAnchorPoint:)]` delegate method defined in `NavigationViewControllerDelegate`

See [NavigationViewControllerDelegate.navigationViewController(_:mapViewUserAnchorPoint:)](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.16.2/Protocols/NavigationViewControllerDelegate.html#/c:@M@MapboxNavigation@objc(pl)MBNavigationViewControllerDelegate(im)navigationViewController:mapViewUserAnchorPoint:)  for more information.
