### ISSUE TITLE
Modify access control for NavigationViewController

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-navigation-ios#1344]
Currently the `NavigationViewController` is [marked as public](https://github.com/mapbox/mapbox-navigation-ios/blob/ce9ae2f057c79c1aa85f9449dec189880979ac47/MapboxNavigation/NavigationViewController.swift#L196), which means that subclasses are not allowed outside of the scope of the module. Would it be possible to change the [access control](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html) such that this class can be `open`, so that subclassing would be possible?

cc @frederoni

**Comment by 1ec5** [comment]
Sounds good to me. Any other `public` classes we should make `open`, while we’re at it? SimulatedLocationManager and ReplayLocationManager, perhaps?
