### ISSUE TITLE
Upgrade to v4 navigation map styles

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1347]
The v2 Navigation Preview/Guidance Day/Night styles should be replaced by the v3 Navigation Preview/Guidance Day/Night styles once they’re ready.

/cc @mapbox/navigation-ios @aparlato

**Comment by 1ec5** [comment]
As part of adopting the new navigation map styles, I think MapboxNavigation should extend MGLStyle with `navigationPreviewDayStyleURL`, `navigationPreviewNightStyleURL`, `navigationGuidanceDayStyleURL`, and `navigationGuidanceNightStyleURL` class properties along the lines of the ones built into MGLStyle. That’ll make the new styles more accessible to developers who design their own Style subclasses.

/cc @frederoni @friedbunny @fabian-guerra

**Comment by 1ec5** [comment]
#1366 takes care of upgrading to the new styles. @frederoni, would it also make sense for that PR to extend MGLStyle with the class properties proposed in https://github.com/mapbox/mapbox-navigation-ios/issues/1347#issuecomment-385122271?

**Comment by 1ec5** [comment]
Despite its title, #1366 didn’t end up upgrading to the v3 styles. This ticket remains open to track that upgrade.

**Comment by 1ec5** [comment]
Also, #1366 added `navigationGuidanceDayStyle` and `navigationGuidanceNightStyle` properties to MGLStyle but omitted `navigationPreviewDayStyle` and `navigationPreviewNightStyle`, which were never added to the map SDK.

**Comment by akitchen** [comment]
Next steps: update style URLs and evaluate color compatibility of drop-in UI vs. palette of new map styles.

**Comment by 1ec5** [comment]
Repurposing this issue for the v4 navigation styles, which are a minor update to the v3 styles that include layers indicating incidents such as road closures and detours. These are the same styles that #1613 is meant to be compatible with.
