### ISSUE TITLE
MapboxDirections library is missing.

### ISSUE THREAD

**Issue by Nirajpaul2** [mapbox/mapbox-navigation-ios#1352]
When i run the Xcode the compiler throw me **import MapboxDirections** is missing.

**Comment by frederoni** [comment]
It sounds like you forgot the first step in "[Building the SDK](https://github.com/mapbox/mapbox-navigation-ios/blob/master/CONTRIBUTING.md#building-the-sdk)" where Carthage downloads and compiles all the dependencies. Please reopen this ticket if you run into the same issue.
