### ISSUE TITLE
Maneuver arrow is black

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1356]
**Mapbox Navigation SDK version: [master](https://github.com/mapbox/mapbox-navigation-ios/commit/afff53402344b68f7dc30b45826bb826e1549029)**
![img_3570](https://user-images.githubusercontent.com/1058624/39439157-82db1f14-4c5b-11e8-982a-1a8573e5b7f6.PNG)

/cc @1ec5

**Comment by 1ec5** [comment]
The color is set here:

https://github.com/mapbox/mapbox-navigation-ios/blob/4c882386d0d8bea852803ebc732a634a288e5f29/MapboxNavigation/NavigationMapView.swift#L646-L647
https://github.com/mapbox/mapbox-navigation-ios/blob/4c882386d0d8bea852803ebc732a634a288e5f29/MapboxNavigation/NavigationMapView.swift#L669-L670
