### ISSUE TITLE
distanceMeasurementSystem should respect overriden locale

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1369]
https://github.com/mapbox/mapbox-navigation-ios/blob/7b7ce41e4b2b0724d839a8372c936c64631da179/MapboxCoreNavigation/NavigationRouteOptions.swift#L84-L85

We use the device's system even when the locale is overriden here.

/cc @1ec5

**Comment by bsudekum** [comment]
Perhaps `distanceMeasurementSystem ` should never be overridable?

**Comment by 1ec5** [comment]
The measurement system should be overrideable, in order to support a very common user preference: #589.

**Comment by 1ec5** [comment]
Setting the locale automatically synchronizes the measurement system to that locale: https://github.com/mapbox/MapboxDirections.swift/blob/c9ea062fdd1db772b28f2e4502c1d368619f3c32/MapboxDirections/MBDirectionsOptions.swift#L380

The issue here is that the NavigationRouteOptions initializer unconditionally overrides that default, so that line can be removed safely.

**Comment by bsudekum** [comment]
Strange, something like below actually passes
```swift
import XCTest
import MapboxDirections
@testable import MapboxCoreNavigation

class NavigationRouteOptionsTests: XCTestCase {
    
    func testLocale() {
        
        let coordinate = CLLocationCoordinate2D(latitude: 0, longitude: 0)
        let options = NavigationRouteOptions(coordinates: [coordinate, coordinate])
        
        options.locale = Locale(identifier: "en-US")
        XCTAssertEqual(options.distanceMeasurementSystem, MeasurementSystem.imperial)
        
        options.locale = Locale(identifier: "de")
        XCTAssertEqual(options.distanceMeasurementSystem, MeasurementSystem.metric)
    }
}
```

Maybe the code is actually fine @1ec5 ?

**Comment by 1ec5** [comment]
If the system locale is `en-FR`, distances should be measured in the metric system by default. At a glance, it seems that NavigationRouteOptions and NavigationMatchOptions would default to whatever would be appropriate to the language (`en`), but not necessarily the full locale (`en-FR`). MapboxDirections.swift does a better job of synchronizing these two properties, so Core Navigation should let that library do its job.
