### ISSUE TITLE
Detect last waypoint

### ISSUE THREAD

**Issue by Satwa** [mapbox/mapbox-navigation-ios#1370]
Hello, I'm using the latest version of the SDK and I was currently searching how to detect when we reach the latest waypoint/destination. 

Note that the function navigationViewController didArriveAt is never called.

**Comment by srikanthsrnvs** [comment]
make sure you set the navigationViewController.delegate to self

**Comment by Satwa** [comment]
```swift
let navigationController = NavigationViewController(for: route)
navigationController.delegate = self
navigationController.showsEndOfRouteFeedback = false
navigationController.showsReportFeedback = navigationController.voiceController?.instructionVoiceSpeedRate = 0.8
```

I actually did it, I think? 
Tell me if I should share more code. What happens here is that when I click on a button, it calls a function that init *NavigationRouteOptions* and the code above is inside *Directions.shared.calculate*

**Comment by dacvrijma** [comment]
For me it worked using the RouteControllerDelegate instead. You set it with:
`navigationController.routeController.delegate = self`
It also has a didArrive function that seems to be triggered just fine

**Comment by bsudekum** [comment]
@Satwa @blipdelivery can you follow the example found here? https://github.com/mapbox/navigation-ios-examples/blob/master/Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift

It shows how you can use `NavigationViewController(_:didArriveAt:)` to detect arrivals and show a custom UI. Note, it's important to remember, it's up to you to [set the leg index](https://github.com/mapbox/navigation-ios-examples/blob/123d2c8f39f8364eda8f8a1628d1291347cc09a3/Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift#L45) once the user has arrived and would like to proceed onto the next leg.

**Comment by Satwa** [comment]
It still doesn't work. The only thing different from the example is that I'm not showing the NavigationViewController from the viewDidLoad but when a user performs a click

**Comment by Satwa** [comment]
@bsudekum You were right, I put the code in the viewDidLoad and it works now, thanks for your help mate!
Hope it helps others: follow the tutorial, put the Directions.shared.calculate(options) in the viewDidLoad and not in another function and it'll work
