### ISSUE TITLE
NavigationViewControllerDelegate methods should identify the view controller

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1376]
Several NavigationViewControllerDelegate methods have suboptimal names in both Swift and Objective-C. We should always follow the convention in both languages of passing the delegator into the method as its first argument. That convention allows a single delegate to serve multiple delegators. I don’t think we need to pass in the NavigationMapView: there can only be one, and it’s already accessible via `navigationViewController.mapView`.

Current Swift | New Swift | New Objective-C
----|----|----
`navigationMapView(_:routeStyleLayerWithIdentifier:source:)` | `navigationViewController(_:routeStyleLayerWithIdentifier:source:)` | `-navigationViewController:routeStyleLayerWithIdentifier:source:`
`navigationMapView(_:routeCasingStyleLayerWithIdentifier:source:)` | `navigationViewController(_:routeCasingStyleLayerWithIdentifier:source:)` | `-navigationViewController:routeCasingStyleLayerWithIdentifier:source:`
`navigationMapView(_:shapeDescribing:)` | `navigationViewController(_:shapeFor:)` | `-navigationViewController:shapeForRoute:`
`navigationMapView(_:simplifiedShapeDescribing:)` | `navigationViewController(_:simplifiedShapeFor:)` | `-navigationViewController:simplifiedShapeForRoute:`
`navigationMapView(_:waypointStyleLayerWithIdentifier:source:)` | `navigationViewController(_:waypointStyleLayerWithIdentifier:source:)` | `-navigationViewController:waypointStyleLayerWithIdentifier:source:`
`navigationMapView(_:waypointSymbolStyleLayerWithIdentifier:source:)` | `navigationViewController(_:waypointSymbolStyleLayerWithIdentifier:source:)` | `-navigationViewController:waypointSymbolStyleLayerWithIdentifier:source:`
`navigationMapView(_:shapeFor:)` | `navigationViewController(_:shapeFor:)` | `-navigationViewController:shapeForRoute:`
`navigationMapView(_:didTap:)` | `navigationViewController(_:didSelect:)` | `-navigationViewController:didSelectRoute:`
`navigationMapView(_:imageFor:)` | `navigationViewController(_:imageFor:)` | `-navigationViewController:imageForAnnotation:`
`navigationMapView(_:viewFor:)` | `navigationViewController(_:viewFor:)` | `-navigationViewController:viewForAnnotation:`

If this all seems terribly verbose, note that https://github.com/mapbox/mapbox-navigation-ios/issues/685#issuecomment-334294064 proposes to get RouteMapViewController out of the business of being NavigationMapView’s delegate, so that the developer can safely register their own class as NavigationMapView’s delegate and implement all its delegate methods directly.

/ref #1375
/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
Let's add this to the v0.17.0 milestone so we can group more breaking changes together.
