### ISSUE TITLE
exit view missing

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1379]
Should 5B be rendered as an exit?

![img_3589](https://user-images.githubusercontent.com/1058624/39599559-f983c84c-4ed0-11e8-9045-1d9076bbf438.PNG)
[Request](https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.41024459645669%2C37.779921665577135%3B-122.314559%2C37.482712.json?geometries=polyline&annotations=congestion&steps=true&overview=full&access_token=YOUR_TOKEN&banner_instructions=true) (search for 5b)

![image](https://user-images.githubusercontent.com/1058624/39599546-ef412b54-4ed0-11e8-9b92-97b328993886.png)

/cc @JThramer @1ec5

**Comment by JThramer** [comment]
🤔 Yes. Something's not right. Will investigate.
