### ISSUE TITLE
Successive route coordinates with identical longitude and latitude are unable to advance user puck.

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1383]
steps to reproduce:

1. ~~enable tunnel simulation~~ (encountered regardless of tunnel simulation mode)
1. set location to san francisco in xcode
1. set destination after stockton tunnel
1. simulate route

The puck stops at the entrance of the tunnel.

![simulator screen shot - iphone x - 2018-05-04 at 09 08 06](https://user-images.githubusercontent.com/1058624/39638302-adaf5288-4f7a-11e8-9eb7-da0481fa7cc2.png)

/cc @vincethecoder

**Comment by vincethecoder** [comment]
@bsudekum Upon investigation, this is a very weird edge-case,  here is my console log from debugging the coordinates:

```
(lldb) po closestCoordinateOnRoute.index
4

(lldb) po coordinates[4]
▿ CLLocationCoordinate2D
  - latitude : 37.790279999999996
  - longitude : -122.40714999999999

(lldb) po coordinates[5]
▿ CLLocationCoordinate2D
  - latitude : 37.790279999999996
  - longitude : -122.40714999999999

(lldb) po coordinates[6]
▿ CLLocationCoordinate2D
  - latitude : 37.789969999999997
  - longitude : -122.40708999999998
```

**Comment by bsudekum** [comment]
@vincethecoder we should still solve the issue here. I think the coordinates you're printing off here are close together because there is severe congestion along the route in which case, location updates will be slower and closer together.

**Comment by vincethecoder** [comment]
@bsudekum yes, I'm currently working on it. I wanted to make a note of the finding for future reference.

**Comment by vincethecoder** [comment]
Also, @bsudekum they are not close together -- they are have the same latitude and longitude.
i.e. ` coordinates[4] == coordinates[5] `
