### ISSUE TITLE
Incorrect voice instruction read from cache

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1391]
I [noticed this route](https://www.mapbox.com/get-directions/#14.99/37.7921/-122.4025?coordinates=-122.400157,37.787735;-122.406105,37.797461) gave me a bogus instruction (I will update this with the actual text, perhaps there is a hint in the instruction that it read) when turning right onto 3rd street. I verified this indeed is an on-device caching issue by making the exact request to the server which produced the correct instruction. Noting where and how we're creating cache keys:

https://github.com/mapbox/mapbox-navigation-ios/blob/d7f8c4d075ca578983cbe02d819d74eb7ac284c4/MapboxNavigation/DataCache.swift#L63-L65

https://github.com/mapbox/mapbox-navigation-ios/blob/d7f8c4d075ca578983cbe02d819d74eb7ac284c4/MapboxNavigation/Cache.swift#L112-L130

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
The problem is likely that cacheKeyForKey is too naive; the last path component can easily collide.

**Comment by bsudekum** [comment]
I was able to track down a hash key for the instruction that was read aloud: `8305224406764629362`. Looking for the hash key for the correct instruction now.

**Comment by bsudekum** [comment]
### Correct instruction:

> <speak><amazon:effect name="drc"><prosody rate="1.08">Continue on <say-as interpret-as="address">3rd</say-as> Street for 1 mile</prosody></amazon:effect></speak>

### Incorrect instruction

> <speak><amazon:effect name="drc"><prosody rate="1.08">Continue on <say-as interpret-as="address">I-680</say-as> Street for 6 miles</prosody></amazon:effect></speak>

**Comment by bsudekum** [comment]
Okay, I went through all audio files in the cache on my device, the correct voice instruction was not there.

**Comment by bsudekum** [comment]
Digging a bit deeper, I looked around for a route that had the incorrect instruction. Turns out, a route that includes this instruction, also has an error when this instruction should be spoken, [route](https://www.mapbox.com/get-directions/#11.59/37.9085/-122.3106?coordinates=-122.299111,37.850395;-122.322136,37.96646).

This instruction is telling me to continue for 3 miles instead of 6!

![simulator screen shot - iphone x - 2018-05-08 at 10 44 15](https://user-images.githubusercontent.com/1058624/39773388-cecd6ec0-52ac-11e8-84f7-ac233914288e.png)

**Comment by bsudekum** [comment]
```
(lldb) p key
(String) $R0 = "<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Continue on <say-as interpret-as=\"address\">I-80</say-as> East for 3 miles</prosody></amazon:effect></speak>"
(lldb) p String.init(key.hashValue)
(String) $R1 = "8305224406764629362"
```

```
(lldb) p key
(String) $R2 = "<speak><amazon:effect name=\"drc\"><prosody rate=\"1.08\">Continue on <say-as interpret-as=\"address\">I-80</say-as> East for 6 miles</prosody></amazon:effect></speak>"
(lldb) p String.init(key.hashValue)
(String) $R3 = "8305224406764629362"
```

Oh, cool.

**Comment by bsudekum** [comment]
![image](https://user-images.githubusercontent.com/1058624/39774910-25f9e666-52b1-11e8-8c19-495bdb50e33d.png)

Demonstrating some collisions

**Comment by JThramer** [comment]
@bsudekum 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/887225/39775133-32f83a26-52ba-11e8-8c95-b3051257523a.png">

yeah, it may be better to key off of a hash of the critical properties directly rather than hashing the speech representation of the instruction.

**Comment by 1ec5** [comment]
[`NSString.hash`](https://developer.apple.com/documentation/foundation/nsstring/1417245-hash) is guaranteed to be deterministic but not guaranteed to be unique across all strings, as shown above.

The conventional solution to this problem would be to generate a UUID for each new audio file, then map SSML text strings to UUIDs. The mapping can be maintained in memory as a dictionary and also saved out periodically as a plist.
