### ISSUE TITLE
Broken Feedback UI in landscape mode

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1426]
Feedback UI:

![simulator_screen_shot_-_iphone_x_-_2018-05-11_at_13 13 34](https://user-images.githubusercontent.com/1058624/39945186-69e8d566-551e-11e8-992d-0498d9dfda9f.png)

Should become:
![simulator screen shot - iphone x - 2018-05-11 at 13 13 34](https://user-images.githubusercontent.com/1058624/39945168-53ca3d06-551e-11e8-81f8-89cadaf3589e.png)

If rotating the end of route UI, it becomes:
![simulator screen shot - iphone x - 2018-05-11 at 13 21 11](https://user-images.githubusercontent.com/1058624/39945241-8fc948e2-551e-11e8-8d96-05fcd8f5e3b8.png)

**Comment by brsbl** [comment]
To clarify @bsudekum the feedback UI components should not actually be repeated, but there should be 6 distinct feedback UI components in landscape mode (as we see in portrait mode), right?

**Comment by vincethecoder** [comment]
@brsbl that's correct. I believe the screenshot above was just an illustration.
/cc @bsudekum
