### ISSUE TITLE
Improvements to user-facing arrival behavior

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1444]
There are a few cases we need to handle here:

* User arrives at a waypoint
* User arrives at destination waypoint

In both cases, we should probably stop:
* Snapping (maybe). The issue I see with snapping is that if you go beyond the destination, it remains snapped to the last coord
* rerouting, depending on whether this is the last waypoint or not

**Comment by akitchen** [comment]
Capturing what we've talking about recently:

By default, we want navigation to end when reaching a destination, however this might not be universally true. An optional NavigationDelegate method could allow customization beyond this default for use cases where navigation shouldn't end.
