### ISSUE TITLE
Setting to enable/disable step skips in RouteProgress

### ISSUE THREAD

**Issue by dacvrijma** [mapbox/mapbox-navigation-ios#1457]
**Mapbox Navigation SDK version: 0.17**

In the userIsOnRoute(_:) function in RouteController.swift there is a check to see if any future steps are closer to the users location than the current step. If so, it then progresses to that step. It would be great if there was a global variable to set if you want to enable or disable this. 

I have had situations where a route would make a turn and (nearly) intersect itself. If the GPS was off just a bit, it would jump to the intersecting step and incorrectly update the instructions, ETA etc. I have also noticed that Mapbox Navigation for Android does not have this behavior. It would be great if we could turn it on and off. That way we could guarantee the same behavior on iOS and Android.

**Comment by bsudekum** [comment]
Interesting idea @dacvrijma. However in the case you described where we find a more suitable step, if this were disabled the user would still be rerouted from this location. This final check only happens as we're about to reroute. Would this actually be better or worse?

**Comment by dacvrijma** [comment]
@bsudekum Ah okay I hadn't noticed it was only triggered while rerouting. In that case it makes sense. However I think it would still be useful to be able to set it. All you would need is one extra true or false boolean. And then you could at least guarantee exactly the same behavior on iOS and Android. We've had people testing our app together cross platform and occasionally one would be sent a different direction that the other (possibly that only one triggered the reroute)

**Comment by bsudekum** [comment]
I think the feature is a good one but it does have it's issues. I might be inclined to keep it but figure out the places where false positives are occurring instead of adding a flag. 

I'm mostly only seeing it at the beginning of routes when you're not necessarily on route yet. @dacvrijma are there specific situations where you see it occur more often?
