### ISSUE TITLE
Mapbox navigation will getting nearest road or bypass toll by default?

### ISSUE THREAD

**Issue by tester87** [mapbox/mapbox-navigation-ios#1458]
Hi all,

I am new in Mapbox and I would like to know mapbox navigation will cater road direction by nearest way or bypass toll payment road?

Thanks in advance.

**Comment by bsudekum** [comment]
If you'd like to avoid tolls, you can do something like this when creating your route options:

```swift
let options = NavigationRouteOptions(waypoints: waypoints)
options.roadClassesToAvoid = .toll
```

**Comment by NaviniOS** [comment]
Any in-build option to add this option on MAPView/UI  ?
