### ISSUE TITLE
[!] Unable to find a specification for 'MapboxNavigation.swift'.

### ISSUE THREAD

**Issue by mgurreta** [mapbox/mapbox-navigation-ios#146]
I added to my Podfile
`pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v0.2.0'`

and upon `pod install` I get:

> Analyzing dependencies
> Pre-downloading: 'MapboxNavigation.swift' from 'https://github.com/mapbox/mapbox-navigation-ios.git', tag 'v0.2.0'
> [!] Unable to find a specification for 'MapboxNavigation.swift'.

**Comment by bsudekum** [comment]
@mgurreta we changed the names around, check out this diff: https://github.com/mapbox/mapbox-navigation-ios/commit/0f8fe6254e3e6fa68352e1f1c8a4f25a35683470

**Comment by mgurreta** [comment]
thanks @bsudekum
