### ISSUE TITLE
(Random encounter) Route is not drawn on presenting MBNavigationViewController

### ISSUE THREAD

**Issue by DKetaki** [mapbox/mapbox-navigation-ios#1466]
Hello,
Recently I have integrated mapbox SDK for turn-by-turn navigation.
The Turn-by-turn navigation works like a charm.
But sometimes the blue route is not visible.
please refer the screenshot attached.
Also I am using objective-c as current language will post the snippet below.

```
MBNavigationViewController  *nav = [[MBNavigationViewController alloc] initWithRoute:routeFinded directions:[MBDirections sharedDirections] style: @[daystyle] locationManager: location];
[self presentViewController:nav animated:YES completion:^{

// some code
        }];
```
![6](https://user-images.githubusercontent.com/39909659/40917635-9283d668-6821-11e8-93bc-910eae29dc3a.jpg)

Thanks in advance

**Comment by bsudekum** [comment]
@DKetaki this should be fixed in v0.18.0. Can you verify and then close this out?

**Comment by DKetaki** [comment]
is this available on pods ?

**Comment by DKetaki** [comment]
When I tried to update my pod with version 0.18.0 it gave me error.Also when I installed pod without any version,0.16.2 version was updated.
Please update me
