### ISSUE TITLE
Exit view is shrunken after selecting step in list

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1467]
After selecting a step from the steps list, the exit number view appears to be smaller than usual:
![image](https://user-images.githubusercontent.com/1058624/40923286-47aced44-67c9-11e8-9e89-e91cc66e9525.png)

/cc @JThramer

**Comment by JThramer** [comment]
Oof. 

Yeah, that's not right. I'll have a look.

**Comment by bsudekum** [comment]
I wonder if this is related to https://github.com/mapbox/mapbox-navigation-ios/issues/1472

**Comment by bsudekum** [comment]
While working through https://github.com/mapbox/mapbox-navigation-ios/issues/1472, I also noticed after applying `DayStyle.apply()`, the exit view does not inherit the default styles. Could be related:

![simulator screen shot - iphone x - 2018-06-12 at 10 11 32](https://user-images.githubusercontent.com/1058624/41306647-9feb7918-6e2b-11e8-9067-be0ef32e2fdc.png)

**Comment by bsudekum** [comment]
You can see this in the demo app by selecting `custom view`.
