### ISSUE TITLE
automaticallyUpdatesDesiredAccuracy is nonfunctional

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1479]
`NavigationLocationManager.automaticallyUpdatesDesiredAccuracy` is marked as deprecated, but it’s already unused. It should be removed. In fact, it should’ve been marked unavailable in the first place if there was no way to automatically update `desiredAccuracy` as a stopgap.

https://github.com/mapbox/mapbox-navigation-ios/blob/10195cf07e66823a58499d0185019eeb417e7517/MapboxCoreNavigation/NavigationLocationManager.swift#L20-L25

/cc @bsudekum

**Comment by bsudekum** [comment]
fixed via https://github.com/mapbox/mapbox-navigation-ios/pull/1481
