### ISSUE TITLE
intermittent test failures

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1482]
Specifically, this test fails often on bitrise:

https://github.com/mapbox/mapbox-navigation-ios/blob/c6d33b37dd9c3f700dc7b50bbdc88d1cf715cee0/MapboxNavigationTests/NavigationViewControllerTests.swift#L89-L104

**Comment by akitchen** [comment]
I've also noticed this, possibly only after a certain time in the day, strangely.

Could you please link to an example build for posterity?

**Comment by bsudekum** [comment]
Adding one to the list here:

```
Failing tests:
	ImageRepositoryTests.test_imageWithURL_downloadsImageWhenNotCached()
** TEST FAILED **
```

Occurred in https://github.com/mapbox/mapbox-navigation-ios/pull/1533/

[73ea65838b2ab5c9.log](https://github.com/mapbox/mapbox-navigation-ios/files/2159917/73ea65838b2ab5c9.log)

**Comment by frederoni** [comment]
Tests that access audio hardware in the simulator tends to fail intermittently as well.

```bash
2018-07-04 06:51:32.002678-0700 Example-Swift[3184:19539] [AudioHAL_Client] AudioHardware.cpp:780:AudioObjectSetPropertyData:  AudioObjectSetPropertyData: no object with given ID 0
2018-07-04 06:51:32.003010-0700 Example-Swift[3184:19539] 80: Failed to set processVolumeScalar on device. Error: 560947818
```

https://app.bitrise.io/build/02588bc3451e603f

**Comment by akitchen** [comment]
I would like to avoid playing audio in tests, relying on a mock or spy instead (#1453)

It's my hope that #1543 will help with some of what we're dealing with here since it removes a lot of unintended side-effects and implicit behaviors.

**Comment by bsudekum** [comment]
https://github.com/mapbox/mapbox-navigation-ios/pull/1543 has seemed to help out a lot here, no issues recently.

**Comment by bsudekum** [comment]
Spoke too soon: https://app.bitrise.io/build/630f460d3de026cc

**Comment by akitchen** [comment]
> Spoke too soon: https://app.bitrise.io/build/630f460d3de026cc

I don't believe that to be related, as these changes affect MapboxNavigationTests, not MapboxCoreNavigationTests. But I will have a look...

**Comment by akitchen** [comment]
It seems pretty clear that https://app.bitrise.io/build/630f460d3de026cc is unrelated to anything having to do with #1543 as we don't use a bundle loader (AKA a UIApplication) for the MapboxCoreNavigtationTests. Stepping through the code in `testShouldReroute()` (the test that failed in the above) it's not immediately clear where there could be a deadlock or unreasonable delay, although I did notice that we're using a real EventsManager in the tests. However, the EventsManager doesn't do much besides initialize more objects before returning.

I think perhaps waiting for a time interval on CircleCI is a bad idea in general (paging Captain Obvious!)... Time is a dependency which we need to do a better job of managing.

**Comment by bsudekum** [comment]
Right, all I'm saying is that we can't close this out because there was another intermittent test failure.
