### ISSUE TITLE
error TURF signal SIGABRT

### ISSUE THREAD

**Issue by dsmila** [mapbox/mapbox-navigation-ios#1488]
Hello,

I have a problem with the turf , when I am trying to Run an app on the device the lldb return me this error
```
 dyld: Library not loaded: @rpath/Turf.framework/Turf
  Referenced from: /Users/utils/Library/Developer/
  Reason: no suitable image found. 

```

how can i solve this error ?

thank you in advance

here is my podFile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codetest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
        pod 'SwiftyJSON'
    pod 'MapboxNavigation'
    pod 'MapboxGeocoder.swift'
  # Pods for codetest

end
```

ps: my xcode version is 9.3

**Comment by bsudekum** [comment]
Can you try:

* Cleaning your build (cmd + shift + k)
* `pod installing` again.
* Closing and opening xcode

I've seen this a few times in the past but cannot put my finger on what the exact issue. Usually just requires telling xcode to try again/harder.

**Comment by bsudekum** [comment]
Please reopen if you have any further issues.
