### ISSUE TITLE
Module 'MapboxCoreNavigation' not found

### ISSUE THREAD

**Issue by tester87** [mapbox/mapbox-navigation-ios#1491]
Hi all,

I have this issue after installed following pods. Any idea?

use_frameworks!
target 'XXX' do
pod 'Mapbox-iOS-SDK'
pod 'MapboxNavigation'
pod 'MapboxGeocoder.swift'
end

Installing shown as below and result is successful.

Installing Mapbox-iOS-SDK (4.0.2)
Installing MapboxCoreNavigation (0.18.0)
Installing MapboxDirections.swift (0.21.0)
Installing MapboxGeocoder.swift (0.8.1)
Installing MapboxMobileEvents (0.4.1)
Installing MapboxNavigation (0.18.0)
Installing MapboxSpeech (0.0.1)

**Comment by bsudekum** [comment]
Can you try:

* Cleaning your build (cmd + shift + k)
* `pod installing` again.
* Closing and opening xcode

**Comment by tester87** [comment]
Tried but still the same.
