### ISSUE TITLE
Voice Instruction comes in meters(in ios)

### ISSUE THREAD

**Issue by DKetaki** [mapbox/mapbox-navigation-ios#1493]
Hello,
I have set my local region to Unites states.
The text I am getting is in miles but voice instructions are still coming in meters/kilometres.
I have found various thread on this topic each topic suggest that the metrics unit set depend upon the device local.
Can you please suggest the appropriate .
Thanks in advance

**Comment by DKetaki** [comment]
` options.distanceMeasurementSystem = MBMeasurementSystemImperial;`
Worked  for me.

**Comment by bsudekum** [comment]
@DKetaki glad you figured it out. Just curious, do you have any secondary languages set in your regions settings for your device?

**Comment by DKetaki** [comment]
@bsudekum No I have not set any secondary language as of now.
