### ISSUE TITLE
Pod installation issues

### ISSUE THREAD

**Issue by dhsu210** [mapbox/mapbox-navigation-ios#1498]
**Mapbox Navigation SDK version:**
0.18.0

Attempting to install the MapboxNavigation pod and wondering if these issues have been occurring for others. I'm in the latest Xcode 9.4.1 (have also tested in Xcode 10.0 beta to no avail).

<img width="349" alt="screen shot 2018-06-13 at 7 46 07 pm" src="https://user-images.githubusercontent.com/10564231/41388888-e9b14a38-6f42-11e8-8eb3-c9c49c753dec.png">

**Comment by frederoni** [comment]
Are you using CocoaPods or Carthage? Would you mind including Cartfile.resolved or Podfile.lock (or at least the relevant parts of the corresponding resolution file?

**Comment by dhsu210** [comment]
Cocoapods, I've attached the screenshot of the relevant parts:

![screen shot 2018-06-14 at 10 04 11 am](https://user-images.githubusercontent.com/10564231/41426992-517cacf8-6fba-11e8-99ba-3687a0c6a2ad.png)
