### ISSUE TITLE
How to show address in Secondary label when reached destination?

### ISSUE THREAD

**Issue by DKetaki** [mapbox/mapbox-navigation-ios#1508]
Hello,
When navigation reached its destination it shows coordinate value in secondLabel.I want to show address in that place.
please find the attached image for reference.
Kindly revert back.

![simulator screen shot - iphone x - 2018-06-19 at 14 30 38](https://user-images.githubusercontent.com/39909659/41588079-658ffc1e-73ce-11e8-8ec3-15435141b72b.png)

**Comment by bsudekum** [comment]
@DKetaki if you pass in named waypoints when making your request, it should appear. Checkout how it's done in the example app:

https://github.com/mapbox/mapbox-navigation-ios/blob/1da7d0fb3ea2f33ade97b9c2d8d4a1efd5390ad9/Examples/Swift/ViewController.swift#L160-L161
