### ISSUE TITLE
Incorrect pronunciation of German U-turn

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-ios#1518]
**Mapbox Navigation SDK version:**
0.18

### Steps to trigger behavior

Currently, OSRM has the following translation for the U-turn for German:
"uturn": "180°-Wendung"

This is read out as "180 Grad Zeichenwende" (180 degrees symbol turn)

**Comment by bsudekum** [comment]
@kozyr How should this read instead? Instructions are generated via [osrm-text-instructions](https://github.com/Project-OSRM/osrm-text-instructions/blob/1a1ec46152be22bacb2872816739abe6a30804d0/languages/translations/de.json#L37) so we'll need to create a PR there. [Here is a link](https://github.com/Project-OSRM/osrm-text-instructions/blob/1a1ec46152be22bacb2872816739abe6a30804d0/languages/translations/de.json#L37) to one one place where we have this translation currently.

**Comment by 1ec5** [comment]
Is there a difference in German between how this word should be displayed (e.g., as “180°-Wendung”) versus how it should be read aloud (“180-Wendung”)? If so, it may be necessary to elide the degree symbol within the Directions API rather than OSRMTI.
