### ISSUE TITLE
Turf error "Type 'Polygon' does not conform to protocol 'Equatable'"

### ISSUE THREAD

**Issue by abe732** [mapbox/mapbox-navigation-ios#1520]
**Mapbox Navigation SDK version:** 0.18

I'm trying to use the native module in a React Native application, updated my podfile to include:
```
use_frameworks!
pod 'MapboxNavigation', '~> 0.18'
```
The project build fails with a "does not conform to protocol 'Equatable'" error. This occurs in 6 places, in the Turf/Geometry.swift file, and 1 place in the Turf/FeatureIdentifier.swift file. Basically, at every structure that is defined with an Equatable.

Any suggestions for resolving would be greatly appreciated!

**Comment by frederoni** [comment]
I'm not familiar with the RN setup. What version of Swift are you using? What version of Xcode? The equatable conformance for these structs are provided via the overloaded equality operator in CoreLocation.swift.

https://github.com/mapbox/turf-swift/blob/3f8c9c7b36d6842b17df034612756aa5470729e0/Sources/Turf/CoreLocation.swift#L75-L77

**Comment by abe732** [comment]
@frederoni using Xcode 9.2 and Swift 3.2

**Comment by frederoni** [comment]
The last release compatible with Swift 3.2 was v0.10.1.
You can use Swift 3.2 libraries in a Swift 4.0 project but not the other way around.

**Comment by abe732** [comment]
Ok gotcha, thanks for the help on this!
