### ISSUE TITLE
NavigationMapView delegates aren't exposed for objective-c

### ISSUE THREAD

**Issue by matthewkertis** [mapbox/mapbox-navigation-ios#1526]
Mapbox Navigation SDK version: 0.18

In NavigationMapView the `navigationMapDelegate` and `courseTrackingDelegate` aren't exposed for objective-c.  The actual delegate methods are exposed but I am unable to implement the actual delegate.

**Comment by billyking991** [comment]
On top of this, would you please change the VoiceControllerDelegate in RouteVoiceController from:

public weak var voiceControllerDelegate: VoiceControllerDelegate?

to:

@objc public weak var voiceControllerDelegate: VoiceControllerDelegate?

I've been changing it for each upgrade, but it would be awesome if it could be built in.  Thank you!!

**Comment by billyking991** [comment]
Thank you!!
