### ISSUE TITLE
Possible to show multiple routes for navigation?

### ISSUE THREAD

**Issue by prgorasiya** [mapbox/mapbox-navigation-ios#1531]
Is it possible to show multiple routes on `MBNavigationViewController` for iOS and allow users to select which one to pick?

I am only using navigation in my app.

Mapbox navigation SDK V0.18.1

**Comment by bsudekum** [comment]
Hi @prgorasiya,

Currently, no. This will be accomplished with https://github.com/mapbox/mapbox-navigation-ios/pull/1289. However, it is possible to show multiple routes with [`NavigationMapView`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.18.1/Classes/NavigationMapView.html#/c:@M@MapboxNavigation@objc(cs)MBNavigationMapView(im)showRoutes:legIndex:). This might be helpful to show when previewing your route before navigation.

**Comment by ch05enOne** [comment]
I see that it is possible to include multiple stops in mapbox navigation docs. I'm having trouble implementing this. They say I need to use a profile but im not sure exactly what that means. I have tried using the profileIdentifier whil initializing my routeOptions but It still didn't work.
