### ISSUE TITLE
Visual Instructions Index should not be incremented until the user passes the correct distance remaining value

### ISSUE THREAD

**Issue by vincethecoder** [mapbox/mapbox-navigation-ios#1532]
We bypass a pre-existing defect addressed by updating `visualInstructionIndex` whenever `stepProgress.visualInstructionIndex == 0`. The `distanceTraveled` provided at the beginning of a step could be greater than the `currentStepProgress.distanceTraveled`, hence the hack to advance the `visualInstructionIndex`.

This ticket will address the aforementioned issue with an elegant solution to ensure this `visualInstructionIndex` can be shared with the visual instructions consumed by the `sub` components of the instructions banner. 

Resolves: https://github.com/mapbox/mapbox-navigation-ios/pull/1514

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/1514
