### ISSUE TITLE
Mapbox re-routing remove all intermediate waypoints

### ISSUE THREAD

**Issue by DKetaki** [mapbox/mapbox-navigation-ios#1536]
I am using  `'MapboxNavigation', '~> 0.18'` for my turn by turn navigation.

It works fine if I create route with `MBRouteOptions`.

But when the navigation re-route it lost track of all intermediate waypoints.

This was working earlier.

I was tracking following issue
[https://github.com/mapbox/mapbox-navigation-ios/issues/980](https://github.com/mapbox/mapbox-navigation-ios/issues/980)

It was given that all the waypoints are taken care while re routing.

But my route omit the waypoint and draw new route.

Please update me ASAP.

**Comment by bsudekum** [comment]
Hi @DKetaki, I'm unable to reproduce this issue in the demo app. 

Are you implementing `routeController(_:shouldRerouteFrom:)` by chance? In most cases, it's not necessary to do this.

![new3](https://user-images.githubusercontent.com/1058624/42284707-3442197c-7f62-11e8-9e74-92c5e372c163.gif)

**Comment by DKetaki** [comment]
Hello thanks for the quick response.
First I started my journey with one waypoint. In the middle of the drive I took wrong path and continue driving.
as soon as route re-routed it vanished the waypoint and directed me for destination location.I will check for video if I can provide by evening .

**Comment by DKetaki** [comment]
Hello Please find below gif.
My route has two waypoint.

As soon as I went on path it re-routed and completely neglected waypoint 1.


![ezgif com-optimize](https://user-images.githubusercontent.com/39909659/42317595-62b6018e-806a-11e8-851d-7c49d6d84356.gif)

Let me know for further update

**Comment by DKetaki** [comment]
This particular happens when I add new waypoint dynamically.
Please find below snippet.

```
MBRouteOptions *options = [[MBRouteOptions alloc] initWithWaypoints:updatedWaypoints profileIdentifier:MBDirectionsProfileIdentifierAutomobile];
    options.includesSteps = YES;
    options.routeShapeResolution = MBRouteShapeResolutionFull;
    options.includesSpokenInstructions = YES;
    options.includesVisualInstructions = YES;
    [[MBDirections sharedDirections] calculateDirectionsWithOptions:options
                                                  completionHandler:^(NSArray<MBWaypoint *> * _Nullable points,
                                                                      NSArray<MBRoute *> * _Nullable route,
                                                                      NSError * _Nullable error)
    {
                [SVProgressHUD dismiss];
                if (![route firstObject]) {
                    NSLog(@"No route found");
                    [self showNoRoutesPopup];
                    return;
                }
                dispatch_async(dispatch_get_main_queue(), ^{
                    MBRoute *newRoute = route.firstObject;
                    [nav.mapView showRoutes:route legIndex:0];
                    [nav.mapView showWaypoints:newRoute legIndex:0];
            });
        }];
```
