### ISSUE TITLE
Turf error "Type 'Number' does not conform to protocol 'Equatable'"

### ISSUE THREAD

**Issue by CheemaAneet** [mapbox/mapbox-navigation-ios#1538]
**Mapbox Navigation SDK version:**0.18.1 

We are seeing swift compilation issues with Mapbox Navigation sdk integrated into one of our projects, currently on Xcode 9.2 and swift 4. We are using pods(Version 1.5.3) to set this up(Followed this link https://www.mapbox.com/mapbox-navigation-ios/navigation/).

Have already tried things like Clean build, clearing derived data, switching to older versions of the mapbox navigation sdk without much help.

Here's are some relevant parts of our podfile.lock if it can be of any help:

- Mapbox-iOS-SDK (4.1.1)
  - MapboxCoreNavigation (0.18.1):
    - MapboxDirections.swift (~> 0.21.0)
    - MapboxMobileEvents (~> 0.4)
    - Turf (~> 0.1)
  - MapboxDirections.swift (0.21.0):
    - Polyline (~> 4.2)
  - MapboxMobileEvents (0.4.2)
  - MapboxNavigation (0.18.1):
    - Mapbox-iOS-SDK (~> 4.0)
    - MapboxCoreNavigation (= 0.18.1)
    - MapboxSpeech (~> 0.0.1)
    - Solar (~> 2.1)
  - MapboxSpeech (0.0.1)
  - Polyline (4.2.0)
  - SDWebImage (3.8.2):
    - SDWebImage/Core (= 3.8.2)
  - SDWebImage/Core (3.8.2)
  - Solar (2.1.0)
  - Turf (0.2.0)

Kindly help.

**Comment by frederoni** [comment]
This looks like a duplicate of https://github.com/mapbox/mapbox-navigation-ios/issues/1520 however, with a more recent version of Swift.

Can you verify that the `Pods` target → Turf → Build Settings → `Swift Language Version` says `Swift 4`? Can you try with the latest stable version of Xcode 9.4?

**Comment by CheemaAneet** [comment]
Yes can confirm Turf swift version says Swift 4, check out the screenshot below,

![screen shot 2018-07-04 at 8 15 47 pm](https://user-images.githubusercontent.com/22000081/42283447-1a01a69e-7fc7-11e8-8c5f-a0234d4212c7.png)

Also, xcode-select -p && swift --version gave me this:

/Applications/Xcode.app/Contents/Developer
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

I will try updating my Xcode to the version you mentioned and see if it helps. Thanks !!

**Comment by CheemaAneet** [comment]
Can confirm upgrading to Xcode 9.4(swift 4.1) fixes this issue, hence closing this.
