### ISSUE TITLE
User puck would move at a constant rate 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1541]
![new3](https://user-images.githubusercontent.com/1058624/42285414-69bf766a-7f64-11e8-8e2b-04cb66e78fd5.gif)

If the user is moving at constant speed, I feel like the user puck should also move at a constant rate. Right now, there is some jumpiness that can occur where the puck stops and jumps ahead by many meters.

@frederoni is there anything we can do on this front?

**Comment by frederoni** [comment]
> is there anything we can do on this front?

Yes. Let's hook up a CADisplayLink to interpolate between location updates. It should fix the constant speed and avoid having a floating puck.
