### ISSUE TITLE
Voice Distorted 

### ISSUE THREAD

**Issue by DKetaki** [mapbox/mapbox-navigation-ios#1544]
The voice got distorted and sometimes echoed.
Its randomly generated no particular pattern.
but most of the time if we rapidly close and reopen navigation screen this happens.
 Not able to reproduce on simulator but it happens on actual device.

**Comment by frederoni** [comment]
Are you using the `RouteVoiceController`, `MapboxVoiceController`, or a custom voice controller? What's the spoken language? Do you have an example route where this occurred?

**Comment by bsudekum** [comment]
Also noting if you go offline and we cannot make a network request, we call back to the default iOS speech synthesizer.

**Comment by DKetaki** [comment]
```
 MBNavigationViewController *nav = [[MBNavigationViewController alloc]initWithRoute:routeFinded directions:[MBDirections sharedDirections] styles:@[daystyle] locationManager:location];
 [self presentViewController:nav animated:YES completion:^{
}];
```

This is the only thing I am doing.
Also its a random case.Like if I switch on -off navigation screen multiple time or changed route.I have encounter one place where I changed my network preference and it started echoing.

@bsudekum The default iOS synthesizer working as expected.

I have recorded one video please go through this so you can understand.
Also please use headphone to watch recording.

[ScreenRecording_07-06-2018 12-19-49.MP4.zip](https://github.com/mapbox/mapbox-navigation-ios/files/2169339/ScreenRecording_07-06-2018.12-19-49.MP4.zip)

**Comment by DKetaki** [comment]
Hello,
Any update on this particular behaviour.
We are about to go on live with the application but stuck because of this issue.
please let me know asap.

**Comment by akitchen** [comment]
Hello,

Have you profiled the active allocations during this workflow using Instruments? 

This symptom makes me wonder if there could be multiple instances of the voice controller or speech synthesizer being created in short succession. We don't have this symptom in any of our applications, so without seeing more sample code (ideally a working project example) it is difficult to provide more of an analysis. 

I hope that helps

**Comment by DKetaki** [comment]
Thanks a lot!
I did couple of setting and it worked.

```
-(void)navigationViewControllerDidDismiss:(MBNavigationViewController *)navigationViewController byCanceling:(BOOL)canceled
{
  if ([self.presentedViewController isKindOfClass:[MBNavigationViewController class]]) {
    MBNavigationViewController *nav = (MBNavigationViewController *)self.presentedViewController;
    [nav dismissViewControllerAnimated:true completion:^{
      nav.voiceController = nil;
    }];
  }
  
}
```

**Comment by luskin** [comment]
I had this issue as well, we had to move the `present` to a NavigationController to fix it, not sure why...
