### ISSUE TITLE
`labelCurrentRoadFeature(at:)` should be public

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1545]
Let's make `labelCurrentRoadFeature(at:)` and give developers the option of adding it to their view. Maybe we can stick this on `NavigationMapView`?

https://github.com/mapbox/mapbox-navigation-ios/blob/245901d26d9b67fe2a05e2252e39744e402a1bee/MapboxNavigation/RouteMapViewController.swift#L739-L750

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
NavigationMapView is not the place to be adding ornamentation. That should be the role of a view controller. Otherwise, we can easily get into a situation where the map view needs to be its own delegate, game over.
