### ISSUE TITLE
RouteVoiceController - instructionVoiceVolume property

### ISSUE THREAD

**Issue by dacvrijma** [mapbox/mapbox-navigation-ios#1553]
In the RouteVoiceController you have the option to set the instructionVoiceVolume property as a string. However I can't find any documentation on which string options there are. The description says "SSML option that specifies the voice loudness." However when I try to google this I can't find any useful documentation. Can anyone help me with what the options are?

I am trying to increase the the voice volume. I've tried a bunch of random strings, but nothing seems to change. 

Thanks in advance!

**Comment by bsudekum** [comment]
Yeah, this should have been removed a long time ago actually. Currently, it does not nothing and I think it should remain this way. It should be up to the user to set the volume of their device.

@dacvrijma what is your use case for overriding the volume here?

**Comment by 1ec5** [comment]
> Yeah, this should have been removed a long time ago actually. Currently, it does not nothing and I think it should remain this way. It should be up to the user to set the volume of their device.

#1567 removed this option. However, #1977 tracks re-adding something similar. #1826 tracks making the default behavior better match user expectations.
