### ISSUE TITLE
Constant re-routing if initial user location is too far off the road

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-ios#1557]
**Mapbox Navigation SDK version:**
0.18.1

If user is located inside of massive building, or somewhere where there are no OSM roads within 100-200 meters, re-routes happen non-stop. Is their a way to stop that or limit the number frequency of re-route attempts so it's not every second (if a re-route is needed immediately after the re-route, slow it down by X seconds, then by 2*X etc.)

**Comment by akitchen** [comment]
Hello @kozyr 

`RouteControllerDelegate` has [an optional method](https://github.com/mapbox/mapbox-navigation-ios/blob/cf49800c3635e9cb84b201b0a971a4996ffdae1a/MapboxCoreNavigation/RouteController.swift#L73) you can implement in order to control this behavior. Hopefully this should meet your needs; if not, please let us know. 

Thanks!

**Comment by kozyr** [comment]
We actually did implement this method (returning false and restarting our custom navigation), but it seems there's no functionality that sits in front of this method call and checks whether re-route just happened like in Android
```
  private boolean validOffRoute(Location location, MapboxNavigationOptions options) {
    // Check if minimum amount of distance has been passed since last reroute
    Point currentPoint = Point.fromLngLat(location.getLongitude(), location.getLatitude());
    double distanceFromLastReroute = 0d;
    if (lastReroutePoint != null) {
      distanceFromLastReroute = TurfMeasurement.distance(lastReroutePoint,
        currentPoint, TurfConstants.UNIT_METERS);
    } else {
      // If null, this is our first update - set the last reroute point to the given location
      updateLastReroutePoint(location);
    }
    return distanceFromLastReroute > options.minimumDistanceBeforeRerouting();
  }
```
We can implement a similar thing on our own, but just wanted to make sure there's nothing like that in the iOS SDK already.

**Comment by kozyr** [comment]
@akitchen yes, I know this function exists, but I guess my question is why iOS doesn't implement the same logic as Android before re-route? We did an implementation with Android first, and then with iOS, and re-routes behave differently - on Android, everything is handled out of the box (and we still can have more control via similar function we can override, but it's not even called if re-route is not valid), but on iOS, this code has to be implemented by us. 

And I guess the second question is - there's no validOffRoute (or similar) method is iOS that's already implemented by you? If we're implementing this ourselves,  I just want to know the existing logic already running before the re-route.

**Comment by kozyr** [comment]
@akitchen any updates on this?

**Comment by akitchen** [comment]
> there's no validOffRoute (or similar) method is iOS that's already implemented by you?

Does `RouteController`'s [userIsOnRoute()](https://github.com/mapbox/mapbox-navigation-ios/blob/cf49800c3635e9cb84b201b0a971a4996ffdae1a/MapboxCoreNavigation/RouteController.swift#L720) help in any way?

And could you share a specific test case or two with us?

Some of the platform-specific discrepancies will be addressed over time, but thanks for letting us know this was a pain point for you. 

/cc @coxchapman @taraniduncan
