### ISSUE TITLE
MapBox navigation

### ISSUE THREAD

**Issue by grass008** [mapbox/mapbox-navigation-ios#1559]
1.How to change navigation route line according to traffic?
2. How can I switch to avoiding toll roads and highways?

**Comment by bsudekum** [comment]
HI @grass008 

1. [`NavigationMapView.showRoutes(_:legIndex:)`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.18.1/Classes/NavigationMapView.html#/c:@M@MapboxNavigation@objc(cs)MBNavigationMapView(im)showRoutes:legIndex:) does this for your. 
2. When creating your NavigationRouteOptions, you can specify the [`roadClassesToAvoid`](https://www.mapbox.com/mapbox-navigation-ios/directions/0.21.0/Classes/RouteOptions.html#/c:@M@MapboxDirections@objc(cs)MBRouteOptions(py)roadClassesToAvoid). Noting, you can only avoid one road class currently.
