### ISSUE TITLE
Events manager should not rely on RouteController.deinit to send arrival messages

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1563]
Hey all, so right now the `RouteController` sends the `cancel` event (with rating and comment) at the [very end](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L312) of it's lifecycle, at `deinit` time.

This is dangerous because if a user force-quits the app, or otherwise makes a hasty exit, the `MMEEventsManager` might not have time to send the arrival event.

A better plan here would be to send the cancel event (with rating and comment) as soon as the user dismisses the EORVC, and also setting a "skip" flag that would skip code that otherwise sends a cancel event at the appropriate time (taking care of the edge-case of not using the EORVC or something).

/cc @mapbox/navigation-ios @rclee

**Comment by JThramer** [comment]
Posterity: Emitted out of work in #1533

**Comment by akitchen** [comment]
I agree it's unfortunate to have a dependency on object lifecycle for key analytics events. Let's please make this eager and explicit. The MMEEventsManager has its own queueing mechanism; let's not reinvent the wheel here. 

It's probably worth reviewing what it's doing under the hood. I don't believe we need to be doing any local queueing and flushing of events. Let's let the MMEEventsManger do its job.
