### ISSUE TITLE
Mapbox routes UI

### ISSUE THREAD

**Issue by grass008** [mapbox/mapbox-navigation-ios#1578]
Hello, i am using last version of Mapbox SDK and Swift 4.1
Is it normal that main route shows under secondary?

![screen shot 2018-07-25 at 13 10 15](https://user-images.githubusercontent.com/12618936/43200996-f6a1a406-901f-11e8-90aa-86a38eb1c433.png)

```swift
_ = self.directions.calculate(options) { [weak self] (waypoints, routes, error) in
            guard let weakSelf = self else { return }
            if let routes = routes {
                weakSelf.routes = routes
                weakSelf.collectionView.reloadData()
            }
            
            if let routes = routes{
                weakSelf.mapView.showRoutes(routes, legIndex: 0)
            }
            
            
            guard let route = routes?.first else {
                return
            }
        }
```

**Comment by grass008** [comment]
And i don't get route with traffic as you can see #1559

**Comment by grass008** [comment]
@frederoni RouteOptions

**Comment by grass008** [comment]
I changed RouteOptions to NavigationRouteOptions, one my problem disappeared, but i don't get routes with traffic

**Comment by grass008** [comment]
But know, I dont know how, its work. Thanks @frederoni

**Comment by frederoni** [comment]
Can you verify that the `profileIdentifier` on your `NavigationRouteOptions` is set to `.automobileAvoidingTraffic`?

**Comment by grass008** [comment]
Now everything work fine.
Want to asked, when it will be possible choose more than one `roadClassesToAvoid`?
