### ISSUE TITLE
traffic layers

### ISSUE THREAD

**Issue by grass008** [mapbox/mapbox-navigation-ios#1586]
Hello
I am using the last version of SDK 
Want get to know, is it possible to make this traffic layers more rounded ?
![screen shot 2018-08-06 at 12 38 05](https://user-images.githubusercontent.com/12618936/43709591-ec25c1d8-9975-11e8-8385-3082ef8b1a79.png)

**Comment by ReSpawN** [comment]
How did you get the traffic to work? Flagging true for showsTraffic nor injecting mapbox-traffic-v1 doesn't work...
