### ISSUE TITLE
NavigationMapView should not remove existing application-specific annotations

### ISSUE THREAD

**Issue by joshpuente** [mapbox/mapbox-navigation-ios#1592]
SDK version:

Mapbox-iOS-SDK (4.2.0)
MapboxCoreNavigation (0.18.1):
MapboxDirections.swift (> 0.21.0)
MapboxMobileEvents (> 0.4)
Turf (> 0.1)
MapboxDirections.swift (0.21.0):
Polyline (> 4.2)
MapboxMobileEvents (0.4.3)
MapboxNavigation (0.18.1):
Mapbox-iOS-SDK (> 4.0)
MapboxCoreNavigation (= 0.18.1)
MapboxSpeech (> 0.0.1)
Solar (~> 2.1)
MapboxSpeech (0.0.1)
Installed with: CocoaPods
iOS: 11.1.2
iPad model: iPad mini MF069LL/A
Xcode version: 9.4.1

Steps to reproduce:
1. Add multiple annotations by calling navigationViewController.mapView.addAnnotations(annotations) before presenting the navigationViewController.
2. Present the navigationViewController.
3. Notice that the annotations are not added to the mapView.

Here is the part of the code in NavigationMapView from the SDK that removes these annotations (line 510):
<img width="655" alt="screen shot 2018-08-08 at 3 09 33 pm" src="https://user-images.githubusercontent.com/15850673/43858873-27ca9dbe-9b1d-11e8-8ed3-c92a9a047c12.png">

Prefer:
These annotations are not removed at the time of creation.

**Comment by 1ec5** [comment]
I’m not sure if there are additional problems, but one thing that jumps out at me is that the navigation SDK automatically removes all annotations before adding the annotations representing waypoints:

https://github.com/mapbox/mapbox-navigation-ios/blob/7de2c5318aabb2d2ddbd91c8f430beb7e8b56fd4/MapboxNavigation/RouteMapViewController.swift#L413
https://github.com/mapbox/mapbox-navigation-ios/blob/b9b241f59c232c0232e9ee55b91508a75e79a4bf/MapboxNavigation/NavigationMapView.swift#L501

**Comment by 1ec5** [comment]
> we need to differentiate between annotations from the SDK vs. annotations from the user

The standard approach is to subclass MGLPointAnnotation and filter `annotations` by class membership.

**Comment by Ahmeddben** [comment]
Any update on this guys?

**Comment by akitchen** [comment]
> Any update on this guys?

Not really, we've been heads-down on other things, although it is on our list of priorities. we'd welcome a pull request though if anyone wants to take this on. 

essentially the SDK needs to be able to easily filter between SDK-provided annotations and user-provided annotations, possibly via using different types or different internal collections.
