### ISSUE TITLE
Which average speed is used for .cycling profile & does core routing adopt the average speed value ??

### ISSUE THREAD

**Issue by leviathan** [mapbox/mapbox-navigation-ios#1626]
In my context we’re using the `MapboxCoreNavigation.RouteController` for turn-by-turn navigation directly. Out user interface is so customised, that we're unable to use the default mapbox navigation user-interface.

Route calculation in `MapboxDirections` has been performed with the `.cycling` profile.
```
let routeOptions = RouteOptions(waypoints: waypoints, profileIdentifier: .cycling)
routeOptions.includesSteps = true
routeOptions.includesAlternativeRoutes = true
routeOptions.includesVisualInstructions = true
routeOptions.includesSpokenInstructions = true
routeOptions.routeShapeResolution = .full
```

We’ve noticed that the ETA (Estimated Time of Arrival), which is available during navigation in the `RouteController` `RouteProgress.durationRemaining` is inaccurate for higher bike traveling speed (e.g. bike speed 26 km/h).

#### 1. Is there a pre-defined average speed for `.cycling` that mapbox core navigation is using?

Note: The default OSRM bike profile defines a travel speed of 16 (maybe km/h).
See: https://github.com/Project-OSRM/osrm-backend/blob/9b779c704f2cfe4e25c3609da7e30e0bc751a633/profiles/bicycle.lua#L12

#### 2. Does mapbox core navigationn adopt the used average speed based on the user's actual speed?

If duration calculation is based on the travel speed of 16 km/h. Then a bike traveling considerably faster (and 26 km/h counts as considerably faster) than 16 km/h will cause the ETA to be off, correct?

**Mapbox Navigation SDK version:**

taken from our `Cartfile.resolved`
```
github "mapbox/MapboxDirections.swift" "v0.21.0"
github "mapbox/mapbox-navigation-ios" "v0.18.1"
```

**Comment by 1ec5** [comment]
> Is there a pre-defined average speed for `.cycling` that mapbox core navigation is using?

Core Navigation doesn’t make any speed or duration judgments of its own. It relies entirely on the behavior of the Directions API. I can confirm that the Directions API’s cycling profile uses the same `default_speed` value as the profile that comes with OSRM.

> Does mapbox core navigationn adopt the used average speed based on the user's actual speed?

`RouteProgress.durationRemaining` sums up the remaining expected speeds found in the Directions API response. It doesn’t adapt to a user who has been consistently traveling faster or slower than the API’s assumed speed. (This issue also comes up in the `automobile` profile, but that’s mitigated by the `automobileAvoidingTraffic` profile and the proactive rerouting feature that refreshes the route data on a timer.)

/cc @danpat

**Comment by danpat** [comment]
@1ec5 is correct - the Core Nav library is wholly dependent on the values that the Directions API is returning.  It assumes  an average cycling speed of 15 km/h, with variations for a few different road classes/properties (rough surfaces slow things down, for example).

We're definitely looking at how we can expand options for bike routing - in some ways, I've always considered it a harder problem than car routing, as there is so much variation in rider preferences (speed, safety tolerances, fitness, bike type, effects of weather, etc).

I don't have anything concrete to offer right now on the Directions API side, other than we're definitely looking at options for exposing a lot more knobs to adjust for bikes.

A very simple approach here might be to naively scale down all the durations by 15/<measured average speed> to correct for rider variations - @1ec5 is there a spot where this kind of adjustment could be made to a Directions API response prior to the Nav SDK taking over?

**Comment by 1ec5** [comment]
> is there a spot where this kind of adjustment could be made to a Directions API response prior to the Nav SDK taking over?

Making this adjustment prior to the SDK taking over would be the most thorough approach, but objects like RouteLeg and RouteStep have immutable `expectedTravelTime` properties, so it isn’t just a matter of setting a property; you’d have to rebuild a transformed Route object.

Since you’re using Core Navigation directly in conjunction with custom UI classes, you could treat this as a purely display issue: multiply `RouteProgress.durationRemaining` by a factor that would correspond to the speed increase. However, note that decisions based on `RouteStep.durationRemaining`, such as the placement of spoken instruction points, would not be affected by this approach.
