### ISSUE TITLE
High CPU when camera is not moving

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1636]
Steps to reproduce:

1. Run example-swift app
1. Turn off navigation simulation
1. Set the simulator location to `Apple` (so it does not move)
1. Start navigation

### Expected:

CPU is near 0% because the camera is not moving.

### Actual: 

CPU is near 100%.

If this line https://github.com/mapbox/mapbox-navigation-ios/blob/5ff994a1c6445cef690d10f6758724763a5e5510/MapboxNavigation/NavigationMapView.swift#L336
is changed simply to `setCamera(newCamera, animate: true)`, CPU drops to 0%. If any setCamera function involves a completion handler, CPU jumps to 100%

/cc @mapbox/navigation-ios @mapbox/ios

**Comment by 1ec5** [comment]
@knov @julianrex this performance issue is triggered by setting an edge padding even though the camera is otherwise the same as before.
