### ISSUE TITLE
Round about icon direction

### ISSUE THREAD

**Issue by margvl** [mapbox/mapbox-navigation-ios#1637]
**Mapbox Navigation SDK version:**

0.19.0

**Steps to reproduce:**

1. Run example-swift app
2. Select a route with roundabout
3. Turn on navigation simulation
4. Start default UI navigation
5. Drive through roundabout

**Expected:**

Visual instruction icon should show direction to left

**Actual:**

![img_1071](https://user-images.githubusercontent.com/22786719/44836723-64926400-ac40-11e8-83c8-576b67e5bc38.PNG)

Reproduced in: Lithuania
Driving direction: Right

**Comment by frederoni** [comment]
Would you mind trying the fix in #1639?

Point your Podfile to:
```ruby
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :branch => "fred/roundabout-driving-side"
```

or your Cartfile to:
```ruby
github "mapbox/mapbox-navigation-ios" "fred/roundabout-driving-side"
```
