### ISSUE TITLE
Continue rerouting after a destination way point is reached

### ISSUE THREAD

**Issue by CheemaAneet** [mapbox/mapbox-navigation-ios#1657]
**Mapbox Navigation SDK version:**

Hi Guys,

I need my app to continue rerouting the user back to the intended destination if the user is off course post arrival beyond a certain threshold.

I have tried to make use of the **userIsOnRoute** method, but it would keep returning *true* even if i have travelled beyond the arrival point(on android as well). 

I have tried setting the **shouldPreventReroutesWhenArrivingAt** delegate to *false* but seems to have no effect because **userHasArrivedAtWaypoint** is set to *true* at that point(on arrival).

Also, shouldn't methods like these(**userIsOnRoute**) should work without any preconditions(i.e arrival checks) ? As per me these should be left to the developer to configure based on their needs, unless there is another/better way to accomplish this.

I guess the assumption behind prohibiting rerouting after arrival is the fact that normally after arrivals we are expected to run post arrival procedures(prompting users for rating/feedback like a typical navigation app would do) and suspend location updates all togather at this point and that works perfectly well for point to point navigation apps.

In our case we need the navigation to continue to work until the user chooses to confirm their arrival, So consider a use case where a user accidently drove beyond the point of arrival and now needs to figure out how to get back, but is left all on his own because there's no rerouting available beyond the point of arrival.

Please help me figure out the best way we can achieve this.

I need urgent help w.r.t this issue pls !!

**Comment by CheemaAneet** [comment]
Guys Thoughts ?

**Comment by akitchen** [comment]
Hello @CheemaAneet 

Apologies for the delay in triaging and replying to this issue. It sounds like you may have run into an issue with how/when `shouldPreventReroutesWhenArrivingAt` is asked of the delegate, which has been addressed in a recent release. 

Previously, the logic was [like this](https://github.com/mapbox/mapbox-navigation-ios/blob/89c1b4642194a7c4781351f87e87a0a5b3ceea00/MapboxCoreNavigation/RouteController.swift#L436). Now, it has been corrected to look [like this](https://github.com/mapbox/mapbox-navigation-ios/blob/1cfae0a4dc5312aac8b43871655c88f7b84f6d7c/MapboxCoreNavigation/RouteController.swift#L241). This whole bit of code might be more intuitive if it were inverted not to use a guard statement, but that's another story.

Could you please take another look? Sorry for the delay in replying; please reopen if still encountering this issue.

Thank you!
