### ISSUE TITLE
User position on screen when navigation is running

### ISSUE THREAD

**Issue by tezqa** [mapbox/mapbox-navigation-ios#1666]
**Mapbox Navigation SDK version:** 0.20.0

I'm using my own navigation views for instructions. The issue is they are located on the bottom of the screen and the user position is hidden behind these views.

I'm using `navigationViewController.mapView?.setUserLocationVerticalAlignment(.center, animated: false)` but it does not work.

Any idea?

**Comment by 1ec5** [comment]
You may need to set the map view’s `contentInsets` property to account for the views overlapping part of the map view.
