### ISSUE TITLE
RouteControllerDelegate v0.16.1

### ISSUE THREAD

**Issue by gobarcanin** [mapbox/mapbox-navigation-ios#1711]
**v0.16.1**

Hello,

I' ve noticed in this version that method
```@objc(routeController:didArriveAtWaypoint:) optional public func routeController(_ routeController: MapboxCoreNavigation.RouteController, didArriveAt waypoint: MapboxDirections.Waypoint) -> Bool ```

In it's description parameter ```finalDestination``` has been declared, either parameter has not been implemented, needs to be implemented or .....

Just to give you heads up

**Comment by akitchen** [comment]
Thanks for the note, but this is a rather old version of the SDK and it's not clear that there is anything to do here.
