### ISSUE TITLE
Mapbox.framework file exceeds Github's recommended maximum file size of 50.00 MB

### ISSUE THREAD

**Issue by dhsu210** [mapbox/mapbox-navigation-ios#1729]
**Mapbox Navigation SDK version:**
0.21

After updating via pod update MapboxNavigation from 0.19 to 0.21, I'm unable to push to our remote repo due to this error msg:

`warning: File Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework/Mapbox is 70.95 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB`

Any ideas?

**Comment by frederoni** [comment]
Checking in dependencies is debatable when it comes to CocoaPods but usually not with Carthage where it shouldn't be checked in. In your case, it's ok to check in the Pods directory but you shouldn't check in binaries, which is how the Mapbox Maps SDK for iOS is distributed.

I would add `Pods/Mapbox-iOS-SDK` to `.gitignore`.

**Comment by dhsu210** [comment]
Thanks, this was helpful!
