### ISSUE TITLE
UserCourseView should update instantaneously when user gestures cause camera changes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1731]
When the user manually rotates the map using gestures, the puck should rotate synchronously with the map. Currently, there’s a bit of a lag that, while smooth, makes the puck look like it’s on a turntable. Similarly and more noticeably, when the user manually pans the map using gestures, the puck should move synchronously with the map instead of casually mosying over to the new location.

Both these issues would be fixed by disabling UserCourseView’s animation (or setting the animation duration to 0&nbsp;seconds) when the map view’s camera changes for reasons other than course tracking. #1506 fixed the same issue, but only when transitioning between overview and turn-by-turn modes.

/cc @vincethecoder

**Comment by 1ec5** [comment]
In CarPlay, it’s easy to reproduce this issue by showing and hiding the navigation bar:

![delay](https://user-images.githubusercontent.com/1231218/45849599-6901e800-bce7-11e8-9560-3aff84ddb6ce.gif)

**Comment by akitchen** [comment]
We've run into this pretty consistently recently. Per @1ec5 we should remove use of UIView animations in cases where the puck's location on screen changes in response to a map camera change.

Related: https://github.com/mapbox/mapbox-navigation-ios/issues/1949#issuecomment-469380779 (likely the same fix)

**Comment by 1ec5** [comment]
We’re synchronizing the puck to the map on each frame of the map, but only when course tracking is enabled:

https://github.com/mapbox/mapbox-navigation-ios/blob/aef144b976f63206cb1a03543d297a4ffc844cd2/MapboxNavigation/NavigationMapView.swift#L271-L273

A pan gesture is enough to kick the map view out of course tracking mode, but we should still synchronize the puck to the map on every frame. The only exception should be when the puck is moving due to a user location update; we don’t want this code to preempt that animation. I suppose we can address that edge case with a simple Boolean guarding around the animation.

**Comment by 1ec5** [comment]
We are synchronizing the puck on every rendered frame, even when not in course tracking mode:

https://github.com/mapbox/mapbox-navigation-ios/blob/aef144b976f63206cb1a03543d297a4ffc844cd2/MapboxNavigation/NavigationMapView.swift#L271-L273

All the while, location updates are coming in, so the map view has a legitimate reason to kick off animations:

https://github.com/mapbox/mapbox-navigation-ios/blob/aef144b976f63206cb1a03543d297a4ffc844cd2/MapboxNavigation/NavigationMapView.swift#L341-L343

The problem is with `beginFromCurrentState`: we kick off an animation, then atomically set the center a number of times during the animation (due to user gestures). The animation builds upon those explicit camera changes, resulting in a wonky additive effect. We probably need to cancel any animations when synchronizing the puck to the map due to a frame getting rendered.
