### ISSUE TITLE
Removing and re-adding NavigationViewController.view to superview causes puck to stop tracking movement

### ISSUE THREAD

**Issue by curtinmartis** [mapbox/mapbox-navigation-ios#1738]
Found in v0.21.0.

We have logic in our app that works around some theming issues if we're showing the `NavigationViewController` by doing the following: 

1. `navigationViewController.view?.removeFromSuperview()`
2. Manually set the `backgroundColor` of `InstructionsBannerView`, `InstructionsBannerContentView`, and `StepInstructionsView`.
3. Set `navigationViewController.mapView?.styleURL` to the current `styleURL`.
4. `view.insertSubview(navigationViewController.view, belowSubview: someOtherView)`
5. `navigationViewController.view?.anchorEdgesToSuperview().isActive = true`

It seems that in the process of removing and re-adding the view, the puck will no longer respond to orientation or location changes. This also happens if step 2 and 3 are taken out of the mix, so it doesn't have anything to do with our theming logic.

This wasn't an issue on the previous version of the SDK that we were using (0.18.1), so it seems to have appeared in the last few releases.

**Comment by frederoni** [comment]
It could be that the `NavigationMapView` loses the reference to the puck after its super view has been removed and added back. Can you put a breakpoint in `NavigationMapView.updateCourseTracking(location:camera:animated:)` and verify if the `userCourseView` is set to nil?

Also, what's the reason why you're working around the theme manager’s behavior?
This custom style should produce the same behavior without step 2 and 3.
```swift
class MyCustomStyle: DayStyle {
    
    public required init() {
        super.init()
        mapStyleURL = URL(string: "mapbox://mystyle…")!
        styleType = .day
        statusBarStyle = .default
    }
    
    override func apply() {
        super.apply()
        InstructionsBannerContentView.appearance().backgroundColor = .green
    }
}
```

**Comment by curtinmartis** [comment]
Breakpoints I put inside `updateCourseTracking()` aren't getting hit (I'm actually unable to hit a breakpoint anywhere in the SDK), but I tried setting a breakpoint after `view.insertSubview(navigationViewController.view, belowSubview: someOtherView)` and `userCourseView` was not nil.

The workaround we have in place for the theming behavior seemed to be related to #1540. That issue has been closed, but we're still not getting any theming on `InstructionsBannerView`, `InstructionsBannerContentView`, or `StepInstructionsView` unless we manually set the `backgroundColor` ourselves. I tried your example and it had no effect when I called `MyCustomStyle.apply()`.

**Comment by frederoni** [comment]
> I tried your example and it had no effect when I called MyCustomStyle.apply()

This needs to happen before the view gets added to a super view.

**Comment by frederoni** [comment]
> but it sounds like calling theme.apply() after the view has been added to a superview shouldn't be expected to work?

that's correct.

From https://developer.apple.com/documentation/uikit/uiappearance
```
Note

iOS applies appearance changes when a view enters a window, it
doesn’t change the appearance of a view that’s already in a window.
To change the appearance of a view that’s currently in a window, remove
the view from the view hierarchy and then put it back.
```

**Comment by curtinmartis** [comment]
Gotcha. Theming issues aside, I'm not sure why the puck stops tracking you now when it used to work before with the same code. If you have any other things you'd like me to check for, I'm all ears. I'll also see if I can do some digging.

**Comment by frederoni** [comment]
We need to get those breakpoints to trigger. Are you using Carthage or CocoaPods?
Verify that the Run action for the target you're running has its Build Configuration set to Debug.
If you're using Carthage, you'll have to pass the `--configuration Debug` flag when running the update or bootstrap command.

Can you add an observer `NotificationCenter.default.addObserver(self, selector: #selector(progressDidChange(notification:)), name: .routeControllerProgressDidChange, object: nil)` and verify if you receive these notifications when the puck stops updating so we can rule out location updates?

**Comment by joshpuente** [comment]
We (@curtinmartis and the rest of team) are using CocoaPods @frederoni. And yes, we are running the debug build configuration. I added the . routeControllerProgressDidChange observer and noticed that we do NOT receive these notifications when the puck stops updating. So it looks like we stop getting location updates after removing and re-adding the navigationViewController.view.

I used the following versions:
Mapbox-iOS-SDK: 4.4.1
MapboxCoreNavigation: 0.22.1
MapboxDirections.swift: 0.24.0
MapboxMobileEvents: 0.5.1
MapboxNavigation: 0.22.1 
MapboxNavigationNative: 3.1.5

**Comment by joshpuente** [comment]
Hey @akitchen. Thank you for looking into this deeply and for all of this helpful information. We can try calling start on the Navigation Service when we re-tackle this issue. We'll keep you updated and we'll also stay tune for adjustments made in the upcoming release. Thanks!
