### ISSUE TITLE
Could not find storyboard named 'Navigation'

### ISSUE THREAD

**Issue by Threepwood9985** [mapbox/mapbox-navigation-ios#174]
I have an existing Objective-C project and installed MapboxNavigation via cocoapods
` pod 'MapboxNavigation'` and run `pod install`

```
Installing AWSCore (2.5.5)
Installing AWSPolly (2.5.5)
Installing Mapbox-iOS-SDK (3.5.2)
Installing MapboxCoreNavigation (0.3.0)
Installing MapboxDirections.swift (0.9.0)
Installing MapboxNavigation (0.3.0)
Installing OSRMTextInstructions (0.1.1)
Installing Polyline (4.1.1)
Installing Pulley (1.3.1)
Installing SDWebImage (4.0.0)
```

I used [this](https://github.com/mapbox/mapbox-navigation-ios/blob/master/docs/Storyboards.md) guide to set up the turn by turn navigation in a storyboard. 
But when I build and run the app and tap on "start navigation" to display the view controller, i get the following error:

`Could not find a storyboard named 'Navigation' in bundle NSBundle`

Do i have to add the folder "MapboxNavigation" like in the Objective-C Example? Because the named storyboard is in there...

Or do i have to embed the Frameworks manually into the "embedded binaries" section? 
Thanks for your support.

**Comment by frederoni** [comment]
Thanks for reporting this issue.
You only have to embed the framework manually if you're using Carthage, not when using CocoaPods.

Can you try to update your Podfile to use the master branch of this repo?
```
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :branch => 'master'
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :branch => 'master'
```
this will take care of the `Could not find a storyboard named 'Navigation' in bundle NSBundle` error until we release a new version.

**Comment by 1ec5** [comment]
It looks like @Threepwood9985 is using v0.3.0, which is the latest version released several hours ago. [This documentation](https://github.com/mapbox/mapbox-navigation-ios/blob/69e69e4aa0f2215718e78f362e174f60294e3b1a/docs/Storyboards.md) would be up-to-date. Do you have a particular fix in mind, @frederoni?

**Comment by frederoni** [comment]
Oh, ignore https://github.com/mapbox/mapbox-navigation-ios/issues/174#issuecomment-297042301

CocoaPods renames the bundle identifier.
Try set the bundle to `org.cocoapods.MapboxNavigation` in your storyboard reference.

**Comment by 1ec5** [comment]
> We need to update the [documentation](https://github.com/mapbox/mapbox-navigation-ios/blob/master/docs/Storyboards.md) or find a way to make the bundle identifier persistent.

Let’s just update the documentation then. CocoaPods doesn’t appear to have a built-in way to force the bundle identifier. _Maybe_ we could set `PRODUCT_BUNDLE_IDENTIFIER` in `pod_target_xcconfig`, but that would probably cause other problems.

**Comment by Threepwood9985** [comment]
Thanks for your support! Changing the bundle identifier worked, but now I have a new error:

```
Unknown class _TtC16MapboxNavigation24NavigationViewController in Interface Builder file.

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: 

'[<UIViewController 0x1098f55d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key drawerContentContainerView.'
```

Can I use this storyboard reference in a View Controller embedded in a NavigationController?

**Comment by frederoni** [comment]
That error was fixed yesterday in https://github.com/mapbox/mapbox-navigation-ios/commit/01d213ddea971a2938f4776f5d8137b95a1b408e. Pin your podfile to that commit or set the correct class `MBNavigationViewController` in `Navigation.storyboard` temporarily.

Yes, you can present the navigation view contained in a UINavigationController.

**Comment by Threepwood9985** [comment]
Ok, thanks, now i tried this:

```
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => '01d213d'
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :commit => '01d213d'
```

with the result:

`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by frederoni** [comment]
Did you follow the rest of the guide [here](https://github.com/mapbox/mapbox-navigation-ios/blob/69e69e4aa0f2215718e78f362e174f60294e3b1a/docs/Storyboards.md)?
Looks like your route or directions object is not set.

Put a breakpoint in your `override func prepare(for segue: UIStoryboardSegue, sender: Any?) {` and verify that it enters the correct case and sets the route object.

**Comment by Threepwood9985** [comment]
True, thanks! now it's working...

but the storyboard documentation for Objective-C should be this:

```
-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
	
	if ([segue.identifier isEqualToString:@"StartNavigation"]) {
		MBNavigationViewController *controller = (MBNavigationViewController *)[segue destinationViewController];
		controller.route = self.route;
		controller.directions = [MBDirections sharedDirections];
	}
}
```

**Comment by frederoni** [comment]
Great that it works now.
Separate ticket for the storyboard documentation in #181
