### ISSUE TITLE
Type 'CarPlayManager' has no member 'searchTemplate'

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1744]
Hi, 
After updating to '~> 0.21', I copy, paste the AppDelegate+CarPlay.swift file to my project. There are two errors: 
![image](https://user-images.githubusercontent.com/10751092/46102751-b1f8e700-c194-11e8-9cb8-9c6beca94f6d.png)

After removed those two errors, I can run the app to Car-play simulator successfully.

**Comment by akitchen** [comment]
Hi there -

It sounds like perhaps you are already using MapboxGeocoder in your project, but not using the CarPlayManager+Search.swift extension (and perhaps not using the example search template built on top of the MapboxGeocoder)?

In this case it is fine to remove those lines. Otherwise, you would also want to include CarPlayManager+Search.swift (or a similar implementation) in your project.

Hope that helps!

**Comment by zijiazhai** [comment]
After I uninstall the MapboxGeocoder in my project, two errors goes away.  But, I still can not see the search template button on the left top corner, still can not input address.  How to fix this? Thanks again.

**Comment by akitchen** [comment]
if you want to try the example search template, MapboxGeocoder.swift should be included, as should the code in CarPlayManager+Search.swift

How are you integrating MapboxNavigation into your project? It sounds like the CarPlayManager+Search.swift file is missing

**Comment by zijiazhai** [comment]
Yes, I want to try the example search template. I reinstalled the MapboxGeocoder.swift v0.10 and MapboxNavigation 0.21 by using CocoaPods, I can see both MapboxGeocoder.swift and CarPlayManager+Search.swift in Pods(so CarPlayManager+Search.swift file is not missing? ):
![image](https://user-images.githubusercontent.com/10751092/46154462-d7d8c700-c23a-11e8-8efb-e416c737c617.png)
But, there are two errors shows Type 'CarPlayManager' has no member 'searchTemplate' and carPlayManager. So, why I can not use class of 'extension CarPlayManager: CPSearchTemplateDelegate' with  MapboxGeocoder.swift v0.10 installed.
Sorry for my poor English.

**Comment by zijiazhai** [comment]
guys, any update for my problem? The code inside of #if canImport(MapboxGeocoder) #endif never been executed. Any suggestions I can try to fix this problem?

**Comment by zijiazhai** [comment]
@akitchen @1ec5 @frederoni 
I am so confused why this happen, but can u guys help me fix this problem?

**Comment by akitchen** [comment]
I'm not sure why this is happening, @zijiazhai , I agree it is very confusing.

As far as I can tell, the code inside the `#canImport(CarPlay)` blocks is being included in your app at compile time, but the code inside the `#canImport(CarPlay) && #canImport(MapboxGeocoder)` is not. Can you verify this somehow?

This could be a bug in our code organization strategy here, perhaps only when using CocoaPods. I'm honestly not sure. We will try to verify but I can't offer a timeline right now. Meanwhile, if you reconfigure our Example-CarPlay app in the SDK project to use your provisioning and entitlement does it work correctly for you?

Do you think you could try reconfiguring your project to use Carthage instead?  Alternatively, you could try editing the code to remove the `#canImport()` statements for now unless you need to support multiple compile-time SDKs. Either of these could help troubleshoot the problem, for you as well as us.

Thank you

**Comment by 1ec5** [comment]
Does your Podfile include the `use_frameworks!` directive? If I’m not mistaken, CocoaPods uses static frameworks by default, so the navigation SDK dynamic framework gets linked into a static Pods.framework and the application is statically linked against that framework. I wouldn’t be surprised if `#if canImport()` breaks whenever static linking is involved.

**Comment by zijiazhai** [comment]
Hi, @1ec5  
`Does your Podfile include the use_frameworks! directive?`
Yes.
![snip20181003_11](https://user-images.githubusercontent.com/10751092/46421666-3816af80-c6f8-11e8-9997-fca18a34be20.png)


I am not very familiar what `use_frameworks!` can do, but I found this:
![snip20181003_12](https://user-images.githubusercontent.com/10751092/46421771-77450080-c6f8-11e8-981f-0245937a37be.png)
So, does that mean my CocoaPods support dynamic framework, and support navigation SDK dynamic framework??
So, my Podfile is not the reason why `if #if canImport()` break?  Is that right?

Thank your so much for your reply

**Comment by akitchen** [comment]
Without an entitlement from Apple I'm afraid you won't be able to get very far. I'm assuming that you are completely unable to run the example app with CarPlay functionality enabled, even after working around the compiler issues? 

Meanwhile we'll have to look and see if there is a more systemic issue with our CarPlay integration vs. CocoaPods. Check back in with us once you've obtained an entitlement from Apple! The turnaround time should be pretty reasonable (a couple days).

**Comment by 1ec5** [comment]
`use_frameworks!` ensures that dependencies such as MapboxGeocoder are built as dynamic frameworks instead of static frameworks. However, even with that flag, CocoaPods statically links each dynamic framework into a consolidated “Pods” static framework, which probably ends up breaking `canImport()` anyways.

#1839 is a related issue about exposing a way for applications to customize the CarPlay search functionality, including when using CocoaPods. That issue might potentially lead us to remove the optional dependency on MapboxGeocoder from this SDK but require applications to bring in their own geocoder (such as MapboxGeocoder), sidestepping this `canImport()` incompatibility.
