### ISSUE TITLE
WillVoice

### ISSUE THREAD

**Issue by vincent-caron** [mapbox/mapbox-navigation-ios#1745]
Hi,

I want to use the WillVoice event in ios sdk but I can't find example.

Does anyone know where I can find one to implement it ?

Thanks in advance

Vincent

**Comment by JThramer** [comment]
👋 Hi @vincent-caron, 

It sounds like you're looking for the [voiceController:willSpeak:instruction:routeProgress](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteVoiceController.swift#L264) `RouteVoiceControllerDelegate` method. 

Be sure and set the delegate after you create the `NavigationViewController` by something like `navigationViewController.voiceController.delegate = <delegate>` shortly after you initialize the `NavigationViewController`, or you'll never receive messages.

I'm going to head and close this as "answered." for now, If you have any other questions or if you need additional context, please feel free to reopen.

Best,
-Jerrad

**Comment by frederoni** [comment]
@vincent-caron set the delegate after you initialized the `NavigationViewController` and conform to the `VoiceControllerDelegate` as seen in the example below:

```swift
Directions.shared.calculateRoutes(matching:` options) { (waypoints, routes, error) in
    guard let route = routes?.first else { return }
    let viewController = NavigationViewController(for: route)    
    self.present(viewController, animated: true, completion: nil)
    navigationViewController?.voiceController.voiceControllerDelegate = self // Set the `voiceControllerDelegate`
}

extension MyViewController: VoiceControllerDelegate {
    func voiceController(_ voiceController: RouteVoiceController, willSpeak instruction: SpokenInstruction, routeProgress: RouteProgress) -> SpokenInstruction? {
        // Modify instruction and return it
    }
}
```

**Comment by vincent-caron** [comment]
@frederoni , I've tried it and it works amazingly.

I can't believe that it was so easy. ( I'm a real noob in swift :) )

Thanks a million times, I can continue my project now.
