### ISSUE TITLE
Mapbox Navigation SDK Installation via CocoaPods

### ISSUE THREAD

**Issue by brascene** [mapbox/mapbox-navigation-ios#1748]
I'm trying to go through the example tutorial for navigation, and during pod install I receive an error that some Swift pods cannot be integrated as static libraries.

Pod version: 1.5.3
Podfile content:  pod 'MapboxNavigation', '~> 0.21.0'

XCode version: 10.0 (10A255)
Language: objC

Received error: 
![screen shot 2018-09-27 at 1 46 33 pm](https://user-images.githubusercontent.com/20214107/46143915-ce138b80-c25b-11e8-9cd3-c50939af5a3e.png)

How can this be solved, or am I supposed to use objC for using this SDK at all since I'm using XCode 10?  As I saw,  in the documentation:
> The Mapbox Navigation SDK and Core Navigation are compatible with applications written in Swift 4 or Objective-C in Xcode 9.0.

Thanks in advance!

P.S. I can install the pods without any errors if I use Swift as the language.

**Comment by 1ec5** [comment]
Thanks, I’ve opened mapbox/mapbox-events-ios#73 to track this issue upstream. For now, as the message states, you can set `use_modular_headers!` or `:modular_headers => true` in your Podfile.

/cc @frederoni @rclee

**Comment by brascene** [comment]
Thank you for your feedback, I've tried with _modular headers_ and then I get 

> Unsupported Swift version

as in the screenshot

![screen shot 2018-09-27 at 7 35 34 pm](https://user-images.githubusercontent.com/20214107/46163865-af79b880-c28c-11e8-8611-289615fc7433.png)

This error is also strange since I'm not using XCode 9, but 10..

**Comment by fahad840** [comment]
Go to your pod settings and then change your swift language from unspecified to 4.0 if you already did that then go to your target build settings and press + button on top and select Add User-Defined Settings then add SWIFT_VERSION as key and 4.0 as value .

**Comment by akitchen** [comment]
Thanks @fahad840 for the suggestion - @brascene , did this work for you?

**Comment by brascene** [comment]
@akitchen I've tried it but I still have the same errors about swift versions, even though I've added it separately for each reported target inside build settings.. and I'm moving away from this for now, I'll use Swift version

**Comment by 1ec5** [comment]
v1.0 will drop support for Objective-C. v0.38.1 was the last release that supported Objective-C.
