### ISSUE TITLE
MapboxNavigationTests build failure — Module 'MapboxDirections' was not compiled for testing

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1753]
#1737 and #1740 introduced `@testable` import statements for external libraries, which fails locally in Xcode 10 but somehow not on CI:

https://github.com/mapbox/mapbox-navigation-ios/blob/42b0872b421207d930cf967fc7c3beb1e791f7a7/MapboxNavigationTests/Fixtures/Fixture.swift#L4

```
Swift Compiler Error Group
/path/to/mapbox-navigation-ios/MapboxNavigationTests/Fixtures/Fixture.swift:4:18: Module 'MapboxDirections' was not compiled for testing
/path/to/mapbox-navigation-ios/MapboxNavigationTests/RouteControllerSnapshotTests.swift:6:18: Module 'MapboxDirections' was not compiled for testing
/path/to/mapbox-navigation-ios/MapboxNavigationTests/SimulatedLocationManagerTests.swift:5:18: Module 'MapboxDirections' was not compiled for testing
```

/cc @mapbox/navigation-ios @nitaliano

**Comment by frederoni** [comment]
> which fails locally in Xcode 10 but somehow not on CI

dependencies must be installed with `configuration --Debug` flag. Setting the flag doesn't override the currently installed release version so you have to delete `./Carthage/Build/iOS/MapboxDirections.swift` and then carthage bootstrap/update `--configuration Debug`.

**Comment by 1ec5** [comment]
> Testable dependencies must be installed with `--configuration Debug` flag.

This is a new requirement for this repository; we should document it somewhere. But looking at the existing uses of `@testable`, none of them are necessary. The one call to an internal method is in a fixture-loading helper utility that doesn’t get run as part of the tests – can it be `#ifdef`’d out until it’s needed? (Too bad there’s no `#if canTestableImport`, eh?)

**Comment by akitchen** [comment]
I don't think we understand why only some developers' local environments are running into this. I've never seen it happen FWIW
