### ISSUE TITLE
Route simulation is always active in the simulator

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1756]
v0.22.0 introduced a new behavior of always simulating the route when running in the iOS Simulator. The “Simulating Locations” banner doesn’t show up when this happens.

One hypothesis is that perhaps the location readings are coming in from Core Location too far apart to satisfy the 1½-second patience heuristic:

```
(Date) $R32 = 2018-10-01 22:54:00 UTC
(Date) $R34 = 2018-10-01 22:54:00 UTC
(Date) $R36 = 2018-10-01 22:54:00 UTC
(Date) $R38 = 2018-10-01 22:54:03 UTC
(Date) $R40 = 2018-10-01 22:54:05 UTC
(Date) $R42 = 2018-10-01 22:54:06 UTC
(Date) $R44 = 2018-10-01 22:54:07 UTC
(Date) $R46 = 2018-10-01 22:54:08 UTC
(Date) $R48 = 2018-10-01 22:54:10 UTC
(Date) $R50 = 2018-10-01 22:54:11 UTC
```

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
If it does turn out to be caused by a too-impatient navigation service, then we should increase the default and make the threshold configurable by applications:

https://github.com/mapbox/mapbox-navigation-ios/blob/882a56bf5c30d5f914b8624e4416864cf6421621/MapboxCoreNavigation/NavigationService.swift#L121

**Comment by 1ec5** [comment]
I was reproducing this issue when using the Debug ‣ Location ‣ Custom Location option in the iOS Simulator (as opposed to Xcode).

@JThramer pointed out that this option produces a location update only once when starting the location manager, unlike the Apple preset, which continually produces location updates at the same coordinate. If that’s the case, then the behavior is somewhat expected, though we should follow up by mentioning the new behavior as a feature in the changelog. Maybe we should also restore the “Weak GPS Signal” banner that was added in #490 but removed in #1163.

**Comment by datwelk** [comment]
Note that when using the iOS Simulator's Custom Location option, no "Simulating location" or "Weak GPS signal" status view is displayed. As a consequence, if I'm not mistaken, one cannot adjust simulation speed when using a custom location from the simulator, since this requires swiping on that status view (https://github.com/mapbox/mapbox-navigation-ios/pull/915). This seems unintended behavior.
