### ISSUE TITLE
Memory leak in 0.22.1

### ISSUE THREAD

**Issue by marhas** [mapbox/mapbox-navigation-ios#1776]
Hi!

After upgrading to Mapbox-navigation-ios version 0.22.1 it looks like there's a memory leak that prevents the NavigationService and it's RouteController from being released. We see this in our own app and notice the same behaviour in the sample app navigation-ios-examples using e.g. the "basic" example; every time a new navigation is started a new NavigationService is created and the old one is still hanging around.

Best,
Marcel

**Comment by akitchen** [comment]
hi @marhas 

Yes, we have noticed this as well, and in fact have already identified a fix which should have a PR coming shortly. We already have a patch release in flight but a fix for this will be in our next release.

**Comment by akitchen** [comment]
@marhas This has been addressed in v0.22.3 via https://github.com/mapbox/mapbox-navigation-ios/pull/1782

Please give it a try when you have a moment - thank you!

**Comment by marhas** [comment]
Thanks for the update Andrew.

I can confirm that it fixes the retain issue 👍 

Thanks!
Marcel
