### ISSUE TITLE
No such module found "Polyline"

### ISSUE THREAD

**Issue by Rogho** [mapbox/mapbox-navigation-ios#1788]
Can't run sample project.
Error is no such module found "Polyline"

**Comment by Rogho** [comment]
also can't find pod file

**Comment by akitchen** [comment]
Hello,

This issue does not contain enough information to be actionable. Mapbox publishes many different sample projects and apps. If you are referring to the example app in this codebase, please refer to the documentation in contributing.md to get started.

**Comment by akitchen** [comment]
Is this the same issue? The [comment above](https://github.com/mapbox/mapbox-navigation-ios/issues/1788#issuecomment-430570101) mentions a podfile...
