### ISSUE TITLE
CarPlay functionality is broken without MapboxGeocoder.framework

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1793]
Discovered during a pair today with @vincethecoder.

STR: Try to remove the MapboxGeocoder framework, build, and see what happens.

Two major problems here: 

1. The CarPlay code won't build without the MapboxGeocoder.framework linked to it.
2. We [force the client developer](https://github.com/mapbox/mapbox-navigation-ios/blob/jerrad-kobe/carplaymanager-instance/Examples/Swift/AppDelegate+CarPlay.swift#L91) to call into the default functionality, only [warning them](https://github.com/mapbox/mapbox-navigation-ios/blob/jerrad-kobe/carplaymanager-instance/MapboxNavigation/CarPlayManager+Search.swift#L24) of non-implementation if they fail to implement the delegate method. That warning does _not_ get called if [the Geocoder is not linked](https://github.com/mapbox/mapbox-navigation-ios/blob/jerrad-kobe/carplaymanager-instance/MapboxNavigation/CarPlayManager+Search.swift#L1).

What we should be doing here is automatically using the default implementation if the client-dev does not provide a delegate method, and only give the "not implemented" warning if the user does not import `MapboxGeocoder.framework`.

/cc @mapbox/navigation-ios

**Comment by JThramer** [comment]
Better yet: Instead of giving a "Not Implemented" warning, just hide/omit the Loupe button.

**Comment by akitchen** [comment]
This is specific to work in progress in https://github.com/mapbox/mapbox-navigation-ios/pull/1792 and is not an issue on master or in a release; closing
