### ISSUE TITLE
Road name / way name label should only be updated once per maneuver

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1802]
Following on https://github.com/mapbox/mapbox-navigation-ios/pull/1576, it has been suggested that we introduce an optimization to only perform these calculations on each maneuver as opposed to on each location update.

We would also benefit from profiling the CPU time before and after such a change.

**Comment by 1ec5** [comment]
Now that mapbox/mapbox-navigation-ios#1440 has been fixed, we aren’t as concerned about these frequent recalculations resulting in blinking and other issues. We’re also doing a bit less work, having shifted some of it to the navigator.
