### ISSUE TITLE
Is there a way to prevent the NavigationMapView from animating as it loads?

### ISSUE THREAD

**Issue by dhsu210** [mapbox/mapbox-navigation-ios#1806]
**Mapbox Navigation SDK version:** 0.22.1

I'd like to just have it show the map as some iPhones load at slower speeds than the newer ones.

**Comment by JThramer** [comment]
Hi @dhsu210,

Yes. Check out `NavigationViewController.pendingCamera` ([docs](
https://www.mapbox.com/mapbox-navigation-ios/navigation/0.23.0/Classes/NavigationViewController.html#)). If you set that to where you want the camera to go before the [view appears on screen](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L172-L173), the map should not animate.

Hope this helps! Please don't hesitate to reopen the ticket if you require more assistance.

-J

**Comment by dhsu210** [comment]
Oh I was referring to the NavigationMapView which I initialized in the background with some UI for selecting directions (this is before NavigationViewController shows up with the actual directions). There isn't a .pendingCamera property for NavigationMapView
