### ISSUE TITLE
Question - default tracking altitude

### ISSUE THREAD

**Issue by tomaszkorab** [mapbox/mapbox-navigation-ios#1807]
Hello,
I couldn't find answer to my question so I decided to open up issue - if there is somewhere answer, sorry!

My question is if there is possibility to **change altitude during tracking** - `followWithHeading`. I'm building custom navigation controller which contains `NavigationMapView`. Unfortunately, the default altitude seems to be too big for my app. I see there is `defaultAltitude` in `NavigationMapView` but I cannot change it.

Best regards

**Comment by 1ec5** [comment]
`NavigationMapView.defaultAltitude` is public and variable as of #1709 in v0.21.0, so it should be possible to modify the altitude now. Note that there’s also a `zoomedOutMotorwayAltitude` for long straightaways on freeways and expressways.
