### ISSUE TITLE
Is it possible to use MapboxNavigation within a UIView (instead of UIViewController)?

### ISSUE THREAD

**Issue by paul019** [mapbox/mapbox-navigation-ios#1814]
Hi!

For some reason I want to use MapboxNavigation within a UIView, because I have no access to its UIViewController. Is it possible to use the Turn-by-turn navigation within such a UIView?

In all your examples the map is used within a UIViewController, e.g.:

```
import Foundation
import UIKit
import MapboxCoreNavigation
import MapboxNavigation
import MapboxDirections
 
class BasicViewController: UIViewController { 
...
```

**Comment by paul019** [comment]
Thank you for the fast answer. I don't know if I've understood you quite right, because I'm not really deep into Xcode.

In the following code you can see the UIView I want to attach the Turn-by-turn window to. In the `extension UIView` I search for the parent UIViewController of my UIView. In its init function I then try to attach an instance of NavigationViewController to my UIViewController.

```
import Foundation
import UIKit
import MapboxCoreNavigation
import MapboxNavigation
import MapboxDirections

@objc(TurnByTurnView)
class TurnByTurnView : UIView {
    var params:NSDictionary;
    weak var viewController: UIViewController?
    
    override init(frame: CGRect) {
        self.params = [:];
        super.init(frame: frame);
        self.frame = frame;
        
        let navigationService = MapboxNavigationService(route: route, simulating: .always)
        let navigationController = NavigationViewController(for: route, navigationService: navigationService)
        viewController.addChildViewController(navigationController);
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func setParams(params: NSDictionary) {
        self.params = params;
    }
}

extension UIView {
    var parentViewController: UIViewController? {
        var parentResponder: UIResponder? = self
        while parentResponder != nil {
            parentResponder = parentResponder!.next
            if let viewController = parentResponder as? UIViewController {
                return viewController
            }
        }
        return nil
    }
}
```

Unfortunately, when I do this, Xcode prints the following error: `Command failed due to signal: Abort trap: 6`. When printing the error, it refers to my init function.

I tried removing the line `viewController.addChildViewController(navigationController);`, but this didn't change anything; the error is still there. So one of the following lines of code has to be responsible for the error:

```
let navigationService = MapboxNavigationService(route: route, simulating: .always)
        let navigationController = NavigationViewController(for: route, navigationService: navigationService) 
```

Do you have any idea, what's going on here? I'm sorry if my code is complete bullshit...

**Comment by frederoni** [comment]
> viewController.addChildViewController(navigationController)

looks correct so far but you also need to add the view
```swift
addSubview(navigationController.view)
```

**Comment by paul019** [comment]
Thank you! Nevertheless, there's still the above mentioned error (`Command failed due to signal: Abort trap: 6`)...

**Comment by frederoni** [comment]
> viewController.addChildViewController(navigationController)

your `viewController` is most likely nil at this point.

**Comment by paul019** [comment]
I've now put the critical lines of code into another function:

```
override func viewDidAppear(animated: Bool) {
        let navigationService = MapboxNavigationService(route: route, simulating: .always)
        let navigationController = NavigationViewController(for: route, navigationService: navigationService)
        viewController.addChildViewController(navigationController);
        viewController.addSubview(navigationController.view);
    }
```

But I'm still getting the same error.

**Comment by paul019** [comment]
Maybe this error results out of my hacky solution for this issue: https://github.com/mapbox/mapbox-events-ios/pull/85. There I had several problems too install MapboxNavigation via CocoaPods. After the installation I always got the following error in Xcode:

<img width="1792" alt="bildschirmfoto 2018-11-05 um 20 40 35" src="https://user-images.githubusercontent.com/39464035/48080708-9e5a8a80-e1ee-11e8-97f7-f35f071847e2.png">

To solve this issue I commented out the line of code that created the error (`#import <MapboxDirections/MapboxDirections.h>`) without getting other errors. But maybe this comment-out leads to the error I'm experiencing now. Can this be the case?

**Comment by paul019** [comment]
@frederoni Do you have any idea to solve my error (`Command failed due to signal: Abort trap: 6`)? Unfortunately, I found nothing helpful on the internet to solve it...
