### ISSUE TITLE
CarPlayManager should take route options as input

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1822]
`CarPlayManager.calculateRouteAndStart(from:to:completionHandler:)` only accepts origin and destination waypoints, but some use cases require multiple waypoints or other route options, such as whether the destination must be on the passenger side upon arrival. We should replace this method with `CarPlayManager.preview(_:completionHandler:)` that takes a RouteOptions object as an argument.

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
Replace, or supplement? Seems like both methods have utility?

**Comment by 1ec5** [comment]
In my opinion, it’s fine to use composition with NavigationRouteOptions here, but if we do keep a version of the method that takes coordinates directly – which is inconsistent with NavigationViewController – then it should be named `CarPlayManager.previewRoute(from:to:completionHandler:)`.
