### ISSUE TITLE
CarPlay map style should be customizable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1823]
CarPlayMapViewController and CarPlayNavigationViewController both hard-code the built-in DayStyle and NightStyle. A developer can specify a custom style for NavigationViewController, so they may want to customize the CarPlay map style, for example to match the style being used on the phone.

https://github.com/mapbox/mapbox-navigation-ios/blob/ae19419a0b30b97eb35f670cca973462625a6257/MapboxNavigation/CarPlayMapViewController.swift#L63 https://github.com/mapbox/mapbox-navigation-ios/blob/ae19419a0b30b97eb35f670cca973462625a6257/MapboxNavigation/CarPlayNavigationViewController.swift#L101

Just as `NavigationViewController(for:styles:navigationService:voiceController:)` takes the initial styles as an argument, CarPlayMapViewController and CarPlayNavigationViewController probably should as well, and that argument should be plumbed through to `CarPlayManager(_:)`. This is a reasonable place to expose the style option, now that CarPlayManager is no longer a singleton (#1792). Still, it may be worth exploring a mechanism to change the style after the fact, since the application delegate typically creates CarPlayManager long before setting up any UI options that might affect the style (such as a street/satellite toggle).

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
First pass: standard plumbing to pass Styles on init; ultimately we will need delegate methods for optimal just-in-time customizability.

**Comment by 1ec5** [comment]
A fix is ready in #1836.
