### ISSUE TITLE
MapboxNavigation (0.16.2) module was not compiled in Xcode 10

### ISSUE THREAD

**Issue by paultnp** [mapbox/mapbox-navigation-ios#1835]
I am facing issue with MapboxNavigation iOS SDK with Xcode 10. I have installed the SDK by Pod

pod 'MapboxNavigation'

**Mapbox Navigation SDK version:**
MapboxNavigation (0.16.2)

Error is:

**Multiple commands produce '/Users/............./Xcode/DerivedData/.............../Build/Products/Debug-iphonesimulator/MapboxNavigation/MapboxNavigation.framework/Info.plist**

Making the build system to "Legacy build system" from "New build system(default)" fixes the issue, but this is a workaround and code is not compiling with new build system of Xcode 10 rather compiling with the old build system.

Also the SDK has a "info.plist" file (please see the attached screen shot). When I remove this file from MapboxNavigation target(from Pod target), the error goes away. Next pod install will again add the "info.plist" file to the MapboxNavigation target. So this is not a permanent solution.

Please suggest.
<img width="272" alt="screen shot 2018-11-13 at 10 56 40 am" src="https://user-images.githubusercontent.com/886293/48392889-38608c80-e733-11e8-9be7-ef3a2088957c.png">

**Comment by frederoni** [comment]
@paultnp Can you post a minimal `Podfile` or project you used to reproduce this? Your CocoaPods version is also relevant.

**Comment by 1ec5** [comment]
[Version 0.16.2](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v0.16.2) is quite old, from before Xcode 10 was announced at WWDC. The navigation SDK didn’t officially support Xcode 10 until [version 0.21.0](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v0.21.0).

Regardless, this SDK is distributed as source, not as a binary, leaving CocoaPods to configure the project and workspace. Please ensure that you have the latest version of CocoaPods installed (currently 1.5.3 or 1.6.0.beta.2) and that you have run `pod repo update && pod update`.
