### ISSUE TITLE
Arrival Lifecycle Management

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1844]
Hey all,

Persuant to #247, we actually send the `didArrive` message quite early, maybe 400m early. 

This causes some serious problems during multi-waypoint navigation where the leg index is auto-incremented on arrival. Basically the voice controller gets as far as "You have arr---"  before the leg increments and the user puck skips ahead 400m to put the origin of the next waypoint in the center of the map.

No bueno.

Suggestion: have a `willArrive:in:distance:` along with a `didArrive:`, where the `willArrive` is your early-message (that the VC will key off of), and then we don't actually manipulate the route model until you actually arrive at the waypoint.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> Basically the voice controller gets as far as "You have arr---" before the leg increments and the user puck skips ahead 400m to put the origin of the next waypoint in the center of the map.

Note that the voice instruction is more likely to get cut off when `NavigationViewController.showsEndOfRouteFeedback` is false.
