### ISSUE TITLE
Erratic GPS behaviour

### ISSUE THREAD

**Issue by KaterGreg** [mapbox/mapbox-navigation-ios#1863]
Hello, I've run into an issue with some erratic GPS behaviour.

We ran a test of our app on Friday and the first trip we did, the gps coordinates seemed to teleport to a location about 1km away and stayed there for around 3 minutes re-routing until the GPS finally locked back onto a real location.  We weren't able to reproduce the same result today, but our Android developer mentioned he had a similar issue on the Android app before. Android ran a similar test at the same time on Friday, but without any erratic behaviour.  If Android had experienced the same behaviour, I would have definitely blamed poor GPS as the culprit, but it's harder to explain when they stayed on path perfectly.

Is there anything I should be watching out for to make sure Mapbox Navigation is getting the best GPS data?  My Android guy mentioned he had to remove any other access to Location Services, which I have not yet done on iOS.  Could my calls to the LocationManager affect the data quality during navigation?

I've added a text file to show some of the GPS data collected.  The first 35 data points are incorrect, before snapping back to a real location and continuing to the destination.  7 more trips that day all worked well after that rocky start.

I converted a screen capture into a GIF so you can see it (sorry, video quality didn't turn out as well as expected).

![gps glitch mp4](https://user-images.githubusercontent.com/36899222/49105324-26074800-f235-11e8-831e-79541baf283e.gif)

[GPS Error.txt](https://github.com/mapbox/mapbox-navigation-ios/files/2621205/GPS.Error.txt)

**Comment by 1ec5** [comment]
Hi @KaterGreg, does the data in the attached log come directly from CLLocationManager, or are you getting these locations from the navigation SDK’s route controller?

**Comment by 1ec5** [comment]
We’ll need to try this again once mapbox/turf-swift#74 lands, because the route controller’s location snapping behavior depends on `LineString.closestCoordinate(to:)`.

/cc @frederoni @JThramer

**Comment by frederoni** [comment]
This looks very much like two location managers running simultaneously. IIRC, we had a similar issue in v0.24.x. Would you mind sharing the version you are using along with a short snippet of how you instantiate and start the Nav SDK? It looks like you are using the `NavigationViewController` with a custom bottom banner, is that assumption correct?

You could also try to `print(locationManager)` 
in `{Portable}/RouteController.locationManager(_:didUpdateLocations:)` and verify that the locations are coming from the same location manager unless you are traveling through a tunnel in which case it will be two different location managers intentionally.

**Comment by KaterGreg** [comment]
I'm a bit out of date on the Navigation version.  I'm still using MapboxNavigation 0.19.0, which I think does not use the separate simulatedLocationManager used for tunnels.  If you've resolved this in a later version, I'll make sure to get an upgrade going on my side ASAP.

I am using multiple navigation views.  One to provide a main overhead map, and then another using turn-by-turn navigation as a subview.  It's using the standard NavigationViewController as a subview, with my own collection view controller on top of it.

Main map view initializer:
`    func setUpMapView() {
        guard navigationMapView == nil else { return }
        navigationMapView = NavigationMapView(frame: view.bounds)
        weak var weakSelf = self
        navigationMapView.delegate = weakSelf
        navigationMapView.frame = view.bounds
        navigationMapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        navigationMapView.setUserTrackingMode(.follow, animated: true)
        navigationMapView.isRotateEnabled = false
        navigationMapView.isPitchEnabled = false
        view.addSubview(navigationMapView)
        view.insertSubview(navigationMapView, belowSubview: menuButton)
        navigationMapView.showsUserLocation = false
    }`

Turn-by-turn view initializer:
`    func startEmbeddedNavigation() {
        
        if navView != nil { return }
        guard let route = driveScreenTripViewModel.route else { return }
        
        if SimulateLocation.shared.simulationEnabled {
            let simulatedLocationManager = SimulatedLocationManager(route: route)
            simulatedLocationManager.speedMultiplier = 2.0
            navView = NavigationViewController(for: route, styles: [CustomDayStyle()], locationManager: simulatedLocationManager)
        } else {
            navView = NavigationViewController(for: route, styles: [CustomDayStyle()])
        }
        weak var weakSelf = self
        navView!.delegate = weakSelf
        navView!.showsEndOfRouteFeedback = false
        
        addChildViewController(navView!)
        view.insertSubview(navView!.view, belowSubview: collectionView)
        view.isHidden = false
        navView!.view.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            navView!.view.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 0),
            navView!.view.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: 0),
            navView!.view.topAnchor.constraint(equalTo: self.view.topAnchor, constant: 0),
            navView!.view.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: 0)
            ])
        didMove(toParentViewController: self)
        
        let pickupAnnotation = WaypointAnnotation()
        guard let rideDetails = DataManager.shared.currentRideDetails else {
            navigationController?.popViewController(animated: true)
            return
        }
        pickupAnnotation.coordinate = rideDetails.pickUp.coordinates
        navView!.mapView?.addAnnotation(pickupAnnotation)
        
        LocationTracking.shared.routeController = navView!.routeController
        LocationTracking.shared.updateMovement()
    }
`
