### ISSUE TITLE
Exit number shields look blurry in CarPlay

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1866]
We’ve gotten a report that exit number shields (and presumably also generic route shields) look blurry in turn-by-turn navigation on CarPlay devices.

![blurry](https://user-images.githubusercontent.com/1231218/49262800-e8edb200-f3fc-11e8-969f-35394763168b.png)

This is on a 2× CarPlay device, presumably connected to a 2× iPhone.

/ref #1556 #1696
/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
`InstructionPresenter.takeSnapshot(on:)` generates an image with the correct scale of 2:

<img width="42" alt="image tiff" src="https://user-images.githubusercontent.com/1231218/49262826-fefb7280-f3fc-11e8-9a02-20b59df994f4.png">

Or, with a background:

<img width="42" alt="image tiff 2" src="https://user-images.githubusercontent.com/1231218/49262966-821cc880-f3fd-11e8-8a9f-bcff433c9292.png">

This image measures 83×41&nbsp;pixels or 41.5×20.5&nbsp;points, whereas it ends up displayed with a height of 16&nbsp;points. [The CarPlay programming guide](https://developer.apple.com/carplay/documentation/CarPlay-Navigation-App-Programming-Guide.pdf#page=22) mentions some maximum sizes for various image assets but doesn’t mention any limits to images inside attributed strings. Perhaps there is a limit of 16&nbsp;points tall.

`CarPlayNavigationViewController.updateManeuvers(for:)` does set a shield height of 16&nbsp;points:

https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/CarPlayNavigationViewController.swift#L31 https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/CarPlayNavigationViewController.swift#L319 https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/VisualInstruction.swift#L48

But as far as I can tell, `InstructionLabel.shieldHeight` is ignored when laying out ExitView and GenericRouteShield. Both views have height constraints based on the font size of the text within:

https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/ExitView.swift#L114-L116 https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/GenericRouteShield.swift#L82

**Comment by akitchen** [comment]
https://github.com/mapbox/mapbox-navigation-ios/pull/1868 may help with this - we will be issuing a beta release soon and would appreciate your feedback!
