### ISSUE TITLE
Shields missing in CarPlay simulator

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1867]
Route shields and exit numbers don’t appear in turn-by-turn mode in the CarPlay simulator, even though they show up in CarPlay devices.

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/1652#issuecomment-419486177
/cc @JThramer

**Comment by 1ec5** [comment]
Hard-coding an image size of 16×16&nbsp;points in `UIView.imageRepresentation` makes the image show up in the CarPlay simulator, which strongly suggests to me that this issue and #1866 are both caused by images exceeding an undocumented maximum image size in text attachments in attributed instruction strings in CarPlay.

https://github.com/mapbox/mapbox-navigation-ios/blob/84ffc890a5a1bd6754fb84ad901b1f01591b1264/MapboxNavigation/UIView.swift#L141

![16](https://user-images.githubusercontent.com/1231218/49264080-cf029e00-f401-11e8-89d1-d443e68303d9.png)

**Comment by akitchen** [comment]
huh... 🤔 I wonder if it's related to the line height of the font being used, etc. I recommend enabling the extended carplay simulator options and trying different form factors & pixel depths

nice catch!

**Comment by 1ec5** [comment]
CarPlay [ignores font and paragraph attributes](https://developer.apple.com/carplay/documentation/CarPlay-Navigation-App-Programming-Guide.pdf#page=30) in `attributedInstructionVariants`. NSAttributedString is only used for embedding text attachments in the instruction. Given that there are [size limits](https://developer.apple.com/carplay/documentation/CarPlay-Navigation-App-Programming-Guide.pdf#page=22) to all the other image assets that go over the (presumably XPC-like) communication protocol, it wouldn’t surprise me that text attachments also have a size limit.
