### ISSUE TITLE
Music from some apps stops playing when my step by step navigation app starts

### ISSUE THREAD

**Issue by hastiranjkesh** [mapbox/mapbox-navigation-ios#1872]
I want audio from my app (a voice in a turn-by-turn navigation app) to be heard over music or other currently playing audio. My app’s audio is occasional and spoken. I'm having issues with some applications like Telegram, WhatsApp, Slack. Music from these apps stops playing when my app starts. This is my code:
In RouteVoiceController class: 

    func duckAudio() throws {
    var categoryOptions: AVAudioSessionCategoryOptions = [.duckOthers, .interruptSpokenAudioAndMixWithOthers, .allowBluetooth, .defaultToSpeaker]
    try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeSpokenAudio)
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, with: categoryOptions)  
    try AVAudioSession.sharedInstance().setActive(true)
    }

    func unDuckAudio() throws {
    try AVAudioSession.sharedInstance().setActive(false, with: [.notifyOthersOnDeactivation])
    }

It works fine with Apple Music, Spotify, and SoundCloud apps but It stops Telegram, WhatsApp, Slack player. I also have these warnings in the console when my audio starts playing. I am using iOS12.1, XCode Version 10.1 :

[avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)

**Mapbox Navigation SDK version: 0.22**

**Comment by jim-martin** [comment]
@hastiranjkesh was this issue resolved, or closed for some other reason?

**Comment by hastiranjkesh** [comment]
@jim-martin It was my fault, I replaced AVAudioSessionCategoryPlayAndRecord with AVAudioSessionCategoryPlayback and removed allowBluetooth from category options and It resolved.
