### ISSUE TITLE
 'MapboxDirections/MapboxDirections.h' file not found

### ISSUE THREAD

**Issue by mhs2342** [mapbox/mapbox-navigation-ios#1889]
**Mapbox Navigation SDK version:**
`v0.26.0`
Xcode version: `10.1`

Followed the setup guide in the readme and was met with the following errors upon the first build: 
**MapboxCoreNavigation**
`'MapboxDirections/MapboxDirections.h' file not found`
**Mapbox Navigation**
`Could not build Objective-C module 'MapboxDirections'`
`Missing required module 'SwiftShims'`

Any thoughts? 

**Edit:**
Had mistakenly written the wrong version. The actual version I am using is `v0.26`

**Comment by 1ec5** [comment]
It looks like your project may be set up for Objective-C but not Swift. Does the error reproduce if you set the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting to `YES`?

**Comment by mhs2342** [comment]
Yep, error reproduces with that flag set. If it's of any help, it was set by default to `YES`

**Comment by frederoni** [comment]
@mhs2342 can you include a minimal sample project? Also, are you using CocoaPods or Carthage?

**Comment by mhs2342** [comment]
I am using cocoapods. The only thing that this project consists of is running `pod install` and opening the resulting `.xcworkspace` file for a single view app. I am strictly following the tutorial [here](https://www.mapbox.com/ios-sdk/navigation/examples/advanced/).

**Podfile**
```
target 'MapboxNavStarter'
use_modular_headers!

pod 'MapboxNavigation', '~> 0.26.0'
```
@frederoni Not sure what you are looking for specifically in the "sample" but I attached the `.xcodeproj` file
[MapboxNavStarter.xcodeproj.zip](https://github.com/mapbox/mapbox-navigation-ios/files/2653947/MapboxNavStarter.xcodeproj.zip)

**Comment by frederoni** [comment]
Do you have other dependencies that doesn't support modules or can you replace?
```
use_modular_headers!
```
with
```
use_frameworks!
```

**Comment by mhs2342** [comment]
@frederoni That did the trick. Totally makes sense that I needed to `use_frameworks` instead of modules.
