### ISSUE TITLE
Customize waypoint markers ?

### ISSUE THREAD

**Issue by mglodack** [mapbox/mapbox-navigation-ios#1893]
**Mapbox Navigation SDK version:** v0.22.3

I have been using the navigation SDK to generate turn-by-turn navigation with > 1 waypoints. I want to modify the style of the waypoints and add the ability to select each marker that will display a custom view. So far, I have been able to modify the end destination marker, but I can't seem to find the protocol which allows me to modify the waypoint marker style.

I'm going to keep digging, but it would be awesome if someone could point me in the direction of how I can accomplish.

**Comment by tezqa** [comment]
+1

I'm trying to change or hide default waypoints markers. Is there a way to hide the default ugly numbers on waypoints?

**Comment by sujalfm** [comment]
I also want to accomplish the same. I had posted in [stackoverflow](https://stackoverflow.com/questions/53332100/how-to-change-marker-for-locations-other-than-destination-in-mapbox) as well but did not get any answer to it.

**Comment by mglodack** [comment]
I haven't tried it, but this was the response I got after emailing their support team.

---------------------------------------------------------------------------

There are least two delegate methods that need to be used:
1) navigationMapView(_:routeStyleLayerWithIdentifier:source:) to return the shape source of the waypoints
2) navigationMapView(_:waypointStyleLayerWithIdentifier:source:) to return a generic style layer to be used for the waypoints
3) navigationMapView(_:waypointSymbolStyleLayerWithIdentifier:source:) to return a symbol style layer to be used for the waypoints (optional)

There is an unfinished implementation of this here: 
https://github.com/mapbox/navigation-ios-examples/blob/f913b2e5fe83186dc4a3c0251d9e848dd6ede310/Navigation-Examples/Examples/Styled-Waypoints.swift#L38-L71

And the documentation for it can be found here: https://www.mapbox.com/ios-sdk/api/navigation/0.27.0/Protocols/NavigationMapViewDelegate.html#/

**Comment by tezqa** [comment]
It works perfectly. Now I can customize these waypoints or hide them. Thanks!

**Comment by mrRedSun** [comment]
Doesn't work for the newest version, any ideas how do it with a newer version (0.38)?
