### ISSUE TITLE
Voice Controller Stops After Rerouting

### ISSUE THREAD

**Issue by hastiranjkesh** [mapbox/mapbox-navigation-ios#1894]
In RouteVoiceController class in pauseSpeechAndPlayReroutingDing method, you stop speechSynth at first and then check if playRerouteSound is true or not. I have a custom Navigation Controller where I set the playRerouteSound variable to false. My voice controller stops after rerouting. I changed the order of the first lines of this method to solve my problem:

    @objc func pauseSpeechAndPlayReroutingDing(notification: NSNotification) {
        guard playRerouteSound && !NavigationSettings.shared.voiceMuted else {
            return
        }
        speechSynth.stopSpeaking(at: .word) 
        do {
            try mixAudio()
        } catch {
            voiceControllerDelegate?.voiceController?(self, spokenInstructionsDidFailWith: error)
        }
        rerouteSoundPlayer.play()
    }

**Mapbox Navigation SDK version:0.26**

**Comment by akitchen** [comment]
Thanks for opening an issue. If you have a fix, would you mind opening a pull request?

**Comment by frederoni** [comment]
A fix for this issue landed in #1903
