### ISSUE TITLE
Feedback UI is squashed.

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1900]
![img_2c4725c8f4d7-2](https://user-images.githubusercontent.com/887225/49961932-1ba1ab00-fed1-11e8-9d2a-bd45e8b3f209.jpeg)

Feedback UI is squashed on iPhone X, at least. Bottom row of text is getting cut off.

/cc @mapbox/navigation-ios

**Comment by JThramer** [comment]
![img_1453](https://user-images.githubusercontent.com/887225/49975381-ff1a6880-fefa-11e8-9c82-dcdc4bebb3cf.PNG)

Seems to be problems in Landscape as well.

**Comment by vincethecoder** [comment]
Expected Result:
Device **iPhone X**, **iOS 12.0.1**

![simulator screen shot - iphone x - 2019-01-22 at 11 43 22](https://user-images.githubusercontent.com/2340650/51550943-710b9900-1e3b-11e9-81f9-f663d5d0a716.png)

![simulator screen shot - iphone x - 2019-01-22 at 11 48 28](https://user-images.githubusercontent.com/2340650/51551070-b8922500-1e3b-11e9-80d6-140fb311e880.png)
