### ISSUE TITLE
Remove redundant map view methods from NavigationViewControllerDelegate

### ISSUE THREAD

**Issue by bikeced** [mapbox/mapbox-navigation-ios#1918]
I'm trying to set the destination annotation image of my NavigationController by implementing navigationViewController(navigationViewController::imageFor annotation:) but the method is never called;

After investigation, some NavigationMapViewDelegate methods from NavigationMapView are never invoked like this one:

```swift
optional func navigationMapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?
```

I think one possible solution would be to set the NavigatinMapView delegate to itself and dispatch the missing MGLMapViewDelegate method to navigationMapDelegate.

An example that solves the issue, in NavigatinMapView.swift:

```swift
fileprivate func commonInit() {
    self.delegate = self
    // Rest of the code
    // ...
  }
```

```swift
extension NavigationMapView: MGLMapViewDelegate {
    public func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
        return self.navigationMapDelegate?.navigationMapView?(mapView, imageFor: annotation)
    }
}
```

I am using MapboxCoreNavigation 0.27.0. Same issue with 0.26.0.

**Comment by samuelm77** [comment]
Same problem for the current location image annotation

**Comment by roddyr2** [comment]
I have the same problem with **destination** and **current** location images annotations

**Comment by SergeyMobile** [comment]
I have the same problem with **current** and **destination** location image annotation

**Comment by kkxmshu** [comment]
Same problem. Please fix

**Comment by 1ec5** [comment]
As of #1601, you’ll need to set `NavigationMapView.delegate` to your class and implement MGLMapViewDelegate methods such as `mapView(_:imageFor:)`. I’m leaving this issue open to track removing the vestigial NavigationMapViewDelegate methods. Some NavigationMapViewDelegate methods remain functional, but you need to set the `NavigationMapView.navigationMapDelegate` to make use of them.
