### ISSUE TITLE
LocationLayerPlugin alternative in iOs

### ISSUE THREAD

**Issue by khataha92** [mapbox/mapbox-navigation-ios#1919]
Hi,
I'm using mapbox sdk for android and using the LocationLayerPlugin which contains a method named: forceUpdateLocation which will make the location to another location. 

Is there alternative for the LocationLayerPlugin in swift ?

**Comment by 1ec5** [comment]
There is SimulatedLocationManager for simulating locations along a route. Other than that, the expectation is that the SDK would reflect the user’s actual location. Or is there some other functionality that’s missing compared to LocationLayerPlugin?
