### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#192]
One item that would be useful for me while driving would to know why a reroute occurred. I think there is potential for more useful information that would be relevant to a developer or a curious driver.

off the cuff list:

* why reroute event occurred (_you were greater than x feet away_)
* number of seconds left on step

This could activated by shake whilst in `DEBUG` release mode. Or just a simple param option the developer sets to true. 

/cc @mapbox/navigation

**Comment by planemad** [comment]
A sample log of reroute events might be worth investigating for potential data issues on OpenStreetMap.

The existing [direction-feedback](https://github.com/mapbox/directions-feedback/issues) and routing failures is inspected by @srividyacb, and rerouting logs could be a potential source to make more data improvements.

cc @shvrm @oini

**Comment by ericrwolfe** [comment]
Addressed by #304.
