### ISSUE TITLE
Instant Trip Completion on very short trips

### ISSUE THREAD

**Issue by KaterGreg** [mapbox/mapbox-navigation-ios#1921]
- Mapbox-iOS-SDK (4.6.0)
  - MapboxCoreNavigation (0.26.0):
  - MapboxDirections.swift (0.25.2):
  - MapboxMobileEvents (0.6.0)
  - MapboxNavigation (0.26.0):
  - MapboxNavigationNative (3.4.11)

I'm using a navigation view by allocating a driver to drive to a customer and tapping an "Arrived at Client" button before we re-calculate the route from pickup to destination.

If a driver has been assigned a trip for a customer that is very close to the driver, it can trigger the endOfRoute view before the delegate methods can even be set for the navigation view.  The app then becomes stuck in a state where the trip has ended before it even had a chance to begin.

```        
        let navigationService = MapboxNavigationService(route: route, simulating: .never)
        navView = NavigationViewController(for: route, styles: [CustomDayStyle()], navigationService: navigationService)// endOfRouteFeedback is immediately triggered here
        weak var weakSelf = self
        navView!.delegate = weakSelf
        navView!.mapView?.delegate = weakSelf
        navView!.showsEndOfRouteFeedback = false
```

How can I prevent the NavigationView from ending the trip when it's just about to begin?

**Comment by S2Ler** [comment]
Please try the latest available version.

If you still observe the issue, feel free to reopen the bug. 

Closing as outdated.
