### ISSUE TITLE
Mapbox Search Framework with CarPlay Support

### ISSUE THREAD

**Issue by vincethecoder** [mapbox/mapbox-navigation-ios#1923]
**Mapbox Navigation SDK version: 0.27**

As a developer, I should be able to experiment with the `CarPlay` Search feature using a sample Mapbox Search framework dedicated to CarPlay. 

* The Mapbox Search framework will depend on the `MapboxGeocoder` for all search functionalities and high-level search functionalities with a UI example.

* Given `CarPlay` is available, the `MapboxSearch.framework` will provide a `CarPlay` search template.

* The main class, `CarPlaySearchController` will manage the `CarPlay` search template wired up to use the `MapboxGeocoder`.

* The `CarPlaySearchController` will provide delegates to allow the developer to provide custom implementations. Such as:

```
public func carPlaySearchController(_ carPlaySearchController: CarPlaySearchController,
                       searchTemplate: CPSearchTemplate,
                       updatedSearchText searchText: String,
                       completionHandler: @escaping ([CPListItem]) -> Void)

public func carPlaySearchController(_ carPlaySearchController: CarPlaySearchController,
                       searchTemplateSearchButtonPressed searchTemplate: CPSearchTemplate)

public func carPlaySearchController(_ carPlaySearchController: CarPlaySearchController,
                       searchTemplate: CPSearchTemplate,
                       selectedResult item: CPListItem,
                       completionHandler: @escaping () -> Void)

public func carPlaySearchController(_ carPlaySearchController: CarPlaySearchController,
                       searchTemplate: CPSearchTemplate,
                       interfaceController: CPInterfaceController,
                       traitCollection: UITraitCollection) -> CPBarButton

public func carPlaySearchController(_ carPlaySearchController: CarPlaySearchController,
                       item: CPListItem, completionHandler: @escaping () -> Void)
```

* Some the fields that should be included are:

```
/**
 The completion handler that will process the list of search results initiated 
 on CarPlay.
*/
var searchCompletionHandler: (([CPListItem]) -> Void)?
    
/**
 The most recent search results.
*/
var recentSearchItems: [CPListItem]?
    
/**
 The most recent search text.
 */
var recentSearchText: String?
    
/**
 The most recent search place.
 */
public var recentSearchPlace: GeocodedPlacemark?
    
/**
 The `CarPlaySearchController` delegate.
*/
public weak var delegate: CarPlaySearchControllerDelegate?
```

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
I think this post needs some updates -- while a search framework makes sense, it shouldn't be specific to CarPlay.

Instead, a `MapboxSearch.framework` would optionally offer a CarPlay search template wired up to use the MapboxGeocoder, in the event that CarPlay is available (via `canImport(CarPlay)` pre-processor directives)

Eventually, a canonical Mapbox search UI widget for iOS would also be offered by this framework, but none exists at the moment, so this would still effectively be a framework just for the CarPlay search functionality. But I wouldn't want to name it after that, if we can avoid it.

**Comment by 1ec5** [comment]
There has been movement towards a Mapbox Search SDK for iOS, but not based on the search-in-CarPlay functionality. Haven’t looked into whether the SDK would be eventually compatible with CarPlay or whether the navigation SDK will continue to vend its own search functionality.

/cc @mapbox/search-sdk
