### ISSUE TITLE
Setting a new route should not result in the delegate receiving a `willRerouteFrom` event

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1927]
When a new `Route` is set on the `RouteController`, we create and set a new `RouteProgress` object behind the scenes ([link](https://github.com/mapbox/mapbox-navigation-ios/blob/523a598c266cccf65de9858a41a256320fc69ce6/MapboxCoreNavigation/RouteController.swift#L91)). This is fine, but when a new `RouteProgress` is set we conditionally send a `willRerouteFrom` delegate message, before then "announcing" the re-route which results in a `didRerouteAlong` delegate message also being sent (which seems appropriate)

https://github.com/mapbox/mapbox-navigation-ios/blob/523a598c266cccf65de9858a41a256320fc69ce6/MapboxCoreNavigation/RouteController.swift#L71-L77

`willRerouteFrom` should be sent *before* obtaining the new route, which I believe already happens, at least it does [here](https://github.com/mapbox/mapbox-navigation-ios/blob/523a598c266cccf65de9858a41a256320fc69ce6/MapboxCoreNavigation/RouteController.swift#L489). So the fix here should be as simple as removing the call to `willRerouteFrom` in the `routeProgress` setter on `RouteController` 

**Mapbox Navigation SDK version:**

<= v0.27.0

/cc @JThramer @1ec5 @frederoni @marhas

**Comment by akitchen** [comment]
This came out of investigations related to https://github.com/mapbox/mapbox-navigation-ios/issues/1777

**Comment by 1ec5** [comment]
Fixed in #1931.
