### ISSUE TITLE
Do not ask the delegate `shouldRerouteFrom` if already working to obtain a new route following an off-route event

### ISSUE THREAD

**Issue by akitchen** [mapbox/mapbox-navigation-ios#1929]
Inside of `RouteController`.`locationManager(_:didUpdateLocations:)` we continue to process GPS updates while a re-route is in progress, potentially continuing to send 'shouldRerouteFrom` messages to the delegate even though we are in the process of obtaining a new route.

Just as we do inside of `reroute(from:along:)`, while rerouting, we should avoid sending this delegate message, and we should probably avoid other processing related to off-route determination since we are already in the process of obtaining a new route.

(related to conversation in #1777 )

**Mapbox Navigation SDK version:**

<= v0.27.0

**Comment by 1ec5** [comment]
Fixed in #1930.
