### ISSUE TITLE
Overriding the first spoken instruction

### ISSUE THREAD

**Issue by maliesa96** [mapbox/mapbox-navigation-ios#1937]
Hi,

I'm trying to override the first spoken instruction (the one that is played as soon as the navigation view controller appears). Apparently the delegate method `voiceController(_ voiceController: RouteVoiceController, willSpeak instruction: SpokenInstruction, routeProgress: RouteProgress)` isn't called for the first instruction (but works for every instruction after that).

My current solution is to manually call 
`navigationViewController.voiceController.speak(firstInstruction)` (where `firstInstruction` is a `SpokenInstruction` object I create) from within the `self.directionsRoute` closure.

This sometimes works, but other times the app crashes on this line in MapboxVoiceController:
` assert(routeProgress != nil, "routeProgress should not be nil.")`.

Why is routeProgress nil and how do I fix this?

Thanks for the help.

**Comment by billyking991** [comment]
I am having issues with this as well.  Is there a way to delay the first instruction until the voiceControllerDelegate is set?  Here is my code:

self->_navViewController = [[MBNavigationViewController alloc] initWithRoute:route
                                                                              styles:nil
                                                                   navigationService:nil
                                                                     voiceController:nil];
        
        self->_navViewController.voiceController.voiceControllerDelegate = self;
        self->_navViewController.delegate = self;
    
        [self presentViewController:self->_navViewController animated:YES completion:nil];

Thank you!

**Comment by billyking991** [comment]
This happens on both 0.27.0 and 0.28.0.  I figured I would update to make sure 0.28.0 didn't fix the issue.  Thank you for the help.

**Comment by maliesa96** [comment]
My solution was to manually edit the speak() function in the MapboxVoiceController.swift file. I just edited every `instruction` to my liking. I know this is bad practice because running `pod update` in the future will delete my edits but its the only working solution I've found at the moment. @billyking991 What exactly are you trying to achieve?

**Comment by maliesa96** [comment]
So move your modifications from the willSpeak delegate function into the speak() function. This will modify the instruction/voice for every spoken instruction, including the first one. You will have to clean your build folder and rebuild for the changes to take effect though. As an example, here's my speak function:

`    @objc open override func speak(_ instruction: SpokenInstruction) {
        if let audioPlayer = audioPlayer, audioPlayer.isPlaying, let lastSpokenInstruction = lastSpokenInstruction {
            voiceControllerDelegate?.voiceController?(self, didInterrupt: lastSpokenInstruction, with: instruction)
        }
        
        audioTask?.cancel()
        audioPlayer?.stop()
        
        assert(routeProgress != nil, "routeProgress should not be nil.")
        
        guard let _ = routeProgress!.route.speechLocale else {
            speakWithDefaultSpeechSynthesizer(instruction, error: nil)
            return
        }

        let modifiedInstruction = voiceControllerDelegate?.voiceController?(self, willSpeak: instruction, routeProgress: routeProgress!) ?? instruction
        
        let newInstruction: SpokenInstruction
        let newInstructionText: String
        
        if let range = modifiedInstruction.text.range(of: " on") {
            
            if let thenRange = modifiedInstruction.text.range(of: ", then") {
                
                // seperate instruction into two parts and get rid of road names
                
                let firstPart = String(modifiedInstruction.text[..<thenRange.lowerBound])
                let secondPart = String(modifiedInstruction.text[thenRange.lowerBound..<modifiedInstruction.text.endIndex])
                
                let fixedFirstPart: String
                let fixedSecondPart: String
                
                if let firstPartRange = firstPart.range(of: " on") {
                    fixedFirstPart = String(firstPart[..<firstPartRange.lowerBound]).lowercased().replacingOccurrences(of: "continue", with: "continue straight")
                }
                else {
                    fixedFirstPart = firstPart
                }
                
                if let secondPartRange = secondPart.range(of: " on") {
                    fixedSecondPart = String(secondPart[..<secondPartRange.lowerBound]).lowercased().replacingOccurrences(of: "continue", with: "continue straight")
                }
                else {
                    fixedSecondPart = secondPart
                }
                
                newInstructionText = fixedFirstPart + fixedSecondPart
                
            }
            
            else {
            
                newInstructionText = String(modifiedInstruction.text[..<range.lowerBound]).lowercased().replacingOccurrences(of: "continue", with: "continue straight")

            }
            
            newInstruction = SpokenInstruction(distanceAlongStep: modifiedInstruction.distanceAlongStep, text: newInstructionText, ssmlText: "<speak>"+newInstructionText+"</speak>")
        }
            
        else {
            newInstruction = modifiedInstruction
        }
        
        
        lastSpokenInstruction = newInstruction
        
        

        if let data = cachedDataForKey(newInstruction.ssmlText) {
            play(data)
            return
        }
        
        fetchAndSpeak(instruction: newInstruction)
    }`

**Comment by billyking991** [comment]
Oh, I see what you're doing.  That would be a pretty involved change each time I update the Mapbox libraries.  I will play around with this, but I'm hoping they will pick this issue up so it can be fixed properly.  I really appreciate the update.  Thank you!

**Comment by maliesa96** [comment]
The better way to do this would be to fork the navigation SDK, make your modifications, and point to your own version in your podfile. This way updates won't effect the changes you've made, but again you won't get updates for MapboxNavigation. No problem!

**Comment by trwarner44** [comment]
I found another solution where it's not necessary to fork the SDK. I added an observer on the `routeProgress` which gives a callback when it's no longer nil and then can send my voice instructions from there.

```swift        
_ = navigationService.routeProgress.observe(\.currentLegProgress, options: [.old, .new, .initial, .prior]) { (legProgress, change) in
            print("leg progress changed from \(change.oldValue)to \(change.newValue)")
            // call your instruction here after routeProgress is set
}
```
