### ISSUE TITLE
Problem while fetching mapbox-speech-swift

### ISSUE THREAD

**Issue by impresyjna** [mapbox/mapbox-navigation-ios#1939]
Hi, 
I am using Carthage in version 0.31.2
While I am trying to get MapboxNavigation in version 0.27.0 (github "mapbox/mapbox-navigation-ios" ~> 0.27.0) I got the following error: 
```
Fetching mapbox-speech-swift
2019-01-22 13:34:12.076 carthage[55331:4123441] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRunLoop addPort:forMode:]: port argument cannot be nil'
```

The same scenario is when I use github "mapbox/MapboxNavigation.swift" "master"
What should I do next?

**Comment by frederoni** [comment]
Would you mind including your Cartfile?

> The same scenario is when I use github "mapbox/MapboxNavigation.swift" "master"

~**mapbox/MapboxNavigation.swift**~ should be **mapbox/mapbox-navigation-ios**

**Comment by impresyjna** [comment]
```
github "IBM-Swift/BlueSocket" ~> 1.0
github "Alamofire/Alamofire" ~> 4.3
github "Alamofire/AlamofireImage" ~> 3.1
github "radex/SwiftyTimer"
github "Quick/Quick"
github "Quick/Nimble"
github "SwiftyJSON/SwiftyJSON"
github "Alamofire/AlamofireNetworkActivityIndicator" ~> 2.0
github "Orderella/PopupDialog" ~> 0.7
github "DaveWoodCom/XCGLogger" ~> 6.0
github "marmelroy/PhoneNumberKit"
github "krzyzanowskim/CryptoSwift"
github "marmelroy/Zip"
github "TimOliver/TOCropViewController"
github "mapbox/turf-swift" ~> 0.1.0
github "mapbox/mapbox-events-ios" ~> 0.3.1
github "mapbox/mapbox-navigation-ios" "master"
```

**Comment by frederoni** [comment]
`mapbox/mapbox-events-ios@0.3.1` is mutually incompatible with `mapbox-navigation-ios@master` .

Try to drop 
```
github "mapbox/turf-swift" ~> 0.1.0
github "mapbox/mapbox-events-ios" ~> 0.3.1
```
and let `mapbox-navigation-ios` bring in the relevant compatible dependencies.

Run `carthage update --platform ios --cache-builds --configuration Debug --no-use-binaries`

If you're still seeing an issue, try purging the cache:
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
rm -rf ~/Library/Caches/carthage/
```

and re-run carthage update.

**Comment by impresyjna** [comment]
It worked, thanks :) 

But the package with MapboxNavigationNative is so big and needs really good network to be downloaded ;)
