### ISSUE TITLE
Enable traffic in free-roam/usertrackingmode

### ISSUE THREAD

**Issue by ReSpawN** [mapbox/mapbox-navigation-ios#1956]
**This is more of a question than a bug... sorry if it's the wrong place; StackOverflow isn't really helpful in answering Mapbox related questions...**

I'm currently using the latest builds on all pods and I've had a fair amount of success in creating a navigation app. At the moment, I'd really like to implement traffic show when in free roam. Basically bundling the tutorial https://docs.mapbox.com/help/tutorials/ios-navigation-sdk/ with free roam before launching actual navigation.

Naturally I found various sources of information which include "mapbox-traffic-v1", though I read the following that says that the v1 is deprecated:
_Originally posted by @bsudekum in https://github.com/mapbox/mapbox-navigation-ios/issues/216#issuecomment-300551122_

Additionally, I also tried adding style layers, with which I had a fair amount of success as well, but they only show up when color the line read, thus not distinguishing actual heavy, moderate and light traffic.

At the end of the road, or rather, the beginning, I stumbled upon showsTraffic which should be flagged on mapView/MGLMapView but the method isn't even called in my case.

Can anybody point me in the right direction?

**Comment by 1ec5** [comment]
Set `MGLMapView.styleURL` to `MGLStyle.navigationPreviewDayStyleURL` to show the Mapbox Navigation Preview Day style, which shows traffic congestion on every road. There’s also an `MGLStyle.navigationPreviewNightStyleURL` for Mapbox Navigation Preview Night. You can use the Style class to automatically switch between the two styles as appropriate.
