### ISSUE TITLE
Mispelled Variable Name in RouteMapViewController

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-navigation-ios#1958]
I was poking around the code day and came across the following type in a local variable convention:

https://github.com/mapbox/mapbox-navigation-ios/blob/187fd6ea886a183a0ee4c31df2ad078d4e082583/MapboxNavigation/RouteMapViewController.swift#L736

https://github.com/mapbox/mapbox-navigation-ios/blob/187fd6ea886a183a0ee4c31df2ad078d4e082583/MapboxNavigation/RouteMapViewController.swift#L758

`snappedLoction` vs. `snappedLocation`

As far as I can tell there's no impact to functionality because the variable is consistently misspelled, but would be worthwhile to fix for future readability and searchability.

Though, because it's an arg, this might _technically_ be a `semver` change.

**Comment by 1ec5** [comment]
It’s an internal method, so there aren’t any implications for semantic versioning.
