### ISSUE TITLE
dyld: Library not loaded, version 0.3, all other Carthage libs compile just fine

### ISSUE THREAD

**Issue by JustasL** [mapbox/mapbox-navigation-ios#196]
Hello, I am having difficulties adding MapboxNavigation.framework
I did follow the installation process, but Xcode can not load frameworks inside MapboxNavigation.framework. 

Just to confirm, I only should add MapboxNavigation.framework and MapboxCoreNavigation.framework, right?
When trying to run app, I get this error:

dyld: Library not loaded: @rpath/MapboxDirections.framework/MapboxDirections
  Referenced from: /Users/Justin/Library/Developer/CoreSimulator/Devices/SOME-NUMEBS-AND-LETTERS/data/Containers/Bundle/Application/SOME-NUMEBS-AND-LETTERS/APP-NAME.app/Frameworks/MapboxCoreNavigation.framework/MapboxCoreNavigation
  Reason: image not found

I've also tried just adding everything to the project (Mapbox, AWSPolly, AWSCore, SDWebImages...) and that works, until I try to upload project to TestFlight.

**Comment by frederoni** [comment]
You have to add all underlying dependencies listed in the `Cartfile` as well.
Drag all these frameworks from `Carthage/Build/iOS` into "Embedded Binaries" in Xcode.
- AWSCore.framework
- AWSPolly.framework
- MapboxCoreNavigation.framework
- Pulley.framework
- SDWebImage.framework
- MapboxDirections.framework
- OSRMTextInstructions.framework
- Polyline.framework
- Mapbox.framework

**Comment by JustasL** [comment]
Ok, so I've added all frameworks. Just to be on same page I added them to “Linked Frameworks and Libraries” as documented in Carthage Installation process for iOS.

App works just fine now, but I'll get a bunch of errors trying to upload app to TestFlight (because I've tried it already). I am currently archiving an app, to get those errors

**Comment by frederoni** [comment]
You need to add a new Run Script Phase that copies all frameworks.
This is a Carthage issue. Check [#4 If you're building for iOS, tvOS, or watchOS](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)
 > This script works around an App Store submission bug triggered by universal binaries and ensures that necessary bitcode-related files and dSYMs are copied when archiving.

**Comment by JustasL** [comment]
Yes, I've added. 
<img width="393" alt="screen shot 2017-05-02 at 15 58 21" src="https://cloud.githubusercontent.com/assets/14614780/25618587/33a3609c-2f50-11e7-9045-3aa4c8546f51.png">

My project has several frameworks added using Carthage, and all other frameworks works just fine. 
So, here are the errors I get while uploading .ipa to TestFlight:

>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.dailymotion.SDWebImage.ios' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.mapbox.sdk.ios' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.mapbox.MapboxDirections' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.amazonaws.sdk.ios.AWSCore' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.amazonaws.sdk.ios.AWSPolly' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.ramoapps.Polyline' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.project-osrm.OSRMTextInstructions' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.52inc.Pulley.Pulley' under the iOS application 'MY-APP.app'."
>ERROR ITMS-90056: "This bundle Payload/MY-APP.app/Frameworks/MapboxNavigation.framework/Frameworks/SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
>ERROR ITMS-90056: "This bundle Payload/MY-APP.app/Frameworks/SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
>ERROR ITMS-90205: "Invalid Bundle. The bundle at 'MY-APP.app/Frameworks/MapboxNavigation.framework' contains disallowed nested bundles."
>ERROR ITMS-90206: "Invalid Bundle. The bundle at 'MY-APP.app/Frameworks/MapboxNavigation.framework' contains disallowed file 'Frameworks'."

**Comment by frederoni** [comment]
Looks like duplicates indeed. Make sure there are no duplicates in the Project Navigator.
The nested dependency hierarchy you're using might work but I have never tried it.
That might explain the duplicates. Extract the frameworks from within MapboxNavigation.framework so you get a flat hierarchy.

**Comment by JustasL** [comment]
What do you mean by:
>The nested dependency structure you're using ...

I didn't do anything. Simple `carthage update` + drag'n'drop frameworks. I've got this nested structure out of the box. Also by: 
>I would extract the frameworks from within MapboxNavigation.framework 
You mean to delete them, right? I've did it, and it helped, I am down to 2 errors:

>ERROR ITMS-90056: "This bundle Payload/MY-APP.app/Frameworks/SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
>ERROR ITMS-90206: "Invalid Bundle. The bundle at 'MY-APP.app/Frameworks/MapboxNavigation.framework' contains disallowed file 'Frameworks'."

**Comment by frederoni** [comment]
This image indicates that MapboxNavigation.framework contains all other frameworks in your project.

<img src="https://cloud.githubusercontent.com/assets/14614780/25619020/f955593e-2f51-11e7-930a-92420cb56b9b.png" width=200>

I don't know how that happened but try to remove all frameworks and readd them in a flat structure like this:
![screenshot 2017-05-02 19 30 15](https://cloud.githubusercontent.com/assets/764476/25630625/13ba33c8-2f6e-11e7-991a-f4922d35ab17.png)

**Comment by JustasL** [comment]
Well now, could you expand MapboxNavigation.framework? Also I do not have MapboxNavigation**UI**.framework, which is odd.

In addition, what I've decided is to remove "Frameworks" folder from MapboxNavigation.framework
And as for missing CFBundleVersion, I've checked bundle version as suggested on [Apple Developer Forum](https://forums.developer.apple.com/thread/23778) and it turns out, SDWebImage.framework does not have a BundleVersion. 

So, just to be clear, how I was supposed to add MapkitNavigation to my project using Carthage? Because official documentation just doesn't work for me, at least when trying to upload app to TestFlight/iTunesConnect

**Comment by JustasL** [comment]
Great news, finally it all went through. Thanks for the help and quick responses

**Comment by frederoni** [comment]
Oh nvm, it matches. 👍 

MapboxNavigationUI was renamed to MapboxNavigation recently. There might be some documentation updates that are still lagging behind. If that's the case, please let us know.

The bundle identifier of SDWebImage seems to be unique and correct here "com.dailymotion.SDWebImage.ios"

We recently submitted an internal example app to Testflight and the submission process went through just fine.

**Comment by frederoni** [comment]
Great! 👍

**Comment by JustasL** [comment]
>We recently submitted an internal example app to Testflight and the submission process went through just fine.

Did you use Carthage?

**Comment by frederoni** [comment]
Verified using both CocoaPods and Carthage quite recently.
Please let us know if you run into any more issues.
