### ISSUE TITLE
CarPlay voice: Localize instructions

### ISSUE THREAD

**Issue by alfonsomiranda** [mapbox/mapbox-navigation-ios#1960]
Hi,

In iOS navigation we have NavigationRouteOptions.locale to change language, but in CarPlay I don't find that option, exists?

Thanks.

**Comment by 1ec5** [comment]
As long as you use `CarPlayManager.previewRoutes(for:completionHandler:)` as opposed to `CarPlayManager.previewRoutes(to:completionHandler:)`, you can pass in the same NavigationRouteOptions object that you’d pass in when creating a NavigationViewController for iOS. Note that `NavigationRouteOptions.locale` only overrides the spoken instruction language; the default language for both spoken instructions and UI elements is based on your application’s available localizations and the current system language. There’s more information about localization options in [this guide](https://docs.mapbox.com/ios/navigation/overview/localization-and-internationalization/).

**Comment by alfonsomiranda** [comment]
Thanks @1ec5! 
For any reason NavigationRouteOptions.locale is not change with my system language (Spanish in my case). If I override locale is working fine.

**Comment by 1ec5** [comment]
By default, the property only uses a locale if the application is localized into that locale. This avoids inconsistencies between different parts of the same application, for example in number formatting and units. Ideally, your application would be translated into Spanish; if that isn’t feasible, you can either override the locale in NavigationRouteOptions or add a stub Spanish localization file with nothing in it.
