### ISSUE TITLE
Visual instruction banners missing when using LegacyRouteController

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1972]
As of v0.29.0, no visual instruction banner appears when using LegacyRouteController, rendering LegacyRouteController unusable. (But so is RouteController for urban navigation: https://github.com/mapbox/mapbox-navigation-ios/pull/1904#issuecomment-462021877.)

```diff
diff --git a/Example/ViewController.swift b/Example/ViewController.swift
index 44f13745..2fe32cd3 100644
--- a/Example/ViewController.swift
+++ b/Example/ViewController.swift
@@ -266,7 +266,7 @@ class ViewController: UIViewController {
         guard let route = routes?.first else { return nil }
         let simulate = simulationButton.isSelected
         let mode: SimulationMode = simulate ? .always : .never//.onPoorGPS
-        return MapboxNavigationService(route: route, directions: Settings.directions, simulating: mode)
+        return MapboxNavigationService(route: route, directions: Settings.directions, simulating: mode, routerType: LegacyRouteController.self)
     }
 
     func presentAndRemoveMapview(_ navigationViewController: NavigationViewController) {
```

LegacyRouteController | RouteController
----|----
<img src="https://user-images.githubusercontent.com/1231218/52518597-98b37d00-2c01-11e9-9f36-330eb7799632.png" width="300" alt="legacy-nav"> | <img src="https://user-images.githubusercontent.com/1231218/52518598-9cdf9a80-2c01-11e9-8342-675ffa6b4287.png" width="300" alt="portable-nav">
<img src="https://user-images.githubusercontent.com/1231218/52518605-baacff80-2c01-11e9-8c2d-fd20bd3328dc.png" width="300" alt="legacy-steps"> | <img src="https://user-images.githubusercontent.com/1231218/52518607-bbde2c80-2c01-11e9-849c-a0b8d00b258d.png" width="300" alt="portable-steps">

/cc @mapbox/navigation-ios

**Comment by pleerock** [comment]
I'm having same issue right now on `0.38.1` (android works fine btw), is it a new regression?
