### ISSUE TITLE
Simple left turn caused a reroute

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#199]
![image](https://cloud.githubusercontent.com/assets/1058624/25637153/e43c264a-2f38-11e7-93a9-ac845c85b1b1.png)
> [Link](http://geojson.io/#id=gist:anonymous/909d397a69b67bd5e6cd60b68c67fd59&map=19/37.77346/-122.43642)

This one boggles my mind, but moving a normal speed through this turn caused a reroute soon after exiting the maneuver. I'm assuming we never entered the desired exit course and then moved x units away from the route.

ref https://github.com/mapbox/mapbox-navigation-ios/issues/192 which might of helped here.

**Comment by bsudekum** [comment]
What if:

* The user enters the maneuver radius
* Their course is not within x degrees of the exit bearing
* We check if the user is within x units of the following step.
 * Or we check the user is traveling in the direction of the next step
* If so, the user has completed the step

**Comment by 1ec5** [comment]
I agree that the current check is too strict. If I understand https://github.com/mapbox/mapbox-navigation-ios/issues/199#issuecomment-298752199 correctly, we should also consider the maneuver complete if the user is already on the next step and moving in the right direction. But that “right direction” means comparing the `course` reading with the route data’s exit bearing, so I’m not sure how that would differ from the current behavior. Perhaps we just need to loosen our course threshold for considering the maneuver complete?

**Comment by frederoni** [comment]
@bsudekum 
I think this is what's happening;
<img src="https://cloud.githubusercontent.com/assets/764476/25671873/cebe510e-3031-11e7-938f-b8dbb8ae3683.png" width=320>
(Color codes explained in https://github.com/mapbox/mapbox-navigation-ios/pull/205)
Why do we use dead reckoning when we have a good accurate fixed position?
When the horizontal accuracy is good (probably this case) the blue dot won't snap to the green dot (causing a reroute), which it shouldn't, it also shouldn't be there in the first place.
