### ISSUE TITLE
CarPlay needs `didArriveAt: -> Bool` delegate method 

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#2000]
The CarPlay framework needs a `carPlayManager:didArriveAt: -> Bool` method that mirrors the `NavigationService.navigationService(_:didArriveAt:) -> Bool` mechanism.

Reference: https://github.com/mapbox/mapbox-navigation-ios/blob/64f07b745decbd2d7ed761bb46c2b24f8aa72289/MapboxNavigation/CarPlayNavigationViewController.swift#L501-L506

The waypoint argument is important because it's a common case to different things based on whether or not a waypoint is intermediate or final.

The boolean return is important because it gives the developer the opportunity to either increment the leg index immediately (vanilla case) or increment it after relevant app-logic is complete.

We also need to give the developer the ability to not show the UI at all. This can be accomplished by moving the waypoint UI arrival code into the example app, or removing it entirely.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Fixed in #2005.
