### ISSUE TITLE
No Match Found Error

### ISSUE THREAD

**Issue by PriyeshMohan** [mapbox/mapbox-navigation-ios#2001]
Pod File :
 pod 'MapboxNavigation', '~> 0.29.1'

Error: No Route Found

API: 
https://api.mapbox.com/matching/v5/mapbox/driving/10.345336,76.115668;10.346483,76.114301;10.354087,76.11218;10.356534,76.110388;10.363408,76.107624;10.366167,76.106462;10.368444,76.105837;10.372496,76.104251;10.374892,76.103285;10.377437,76.102046?steps=true&tidy=true&waypoints=0;6&waypoint_names=Home;Work&banner_instructions=true&access_token=pk.eyJ1IjoicHJpeWVzaDk5OTkiLCJhIjoiY2pyOHp2cHB0MGNrbjQzcGQzdGFodjBtbiJ9.4Jlf8Im9z1uQ82MlAVBB-g

GeoJson:
{
    "type": "LineString",
    "coordinates": [
       [76.115668, 10.345336],
[76.114301,10.346483],
[ 76.11218,10.354087],
[76.110388,10.356534],
[76.107624,10.363408],
[76.106462,10.366167],
[76.105837,10.368444],
[76.104251,10.372496],
[76.103285,10.374892],
[76.102046,10.377437]
    ]
}

This is a subset of points from my coordinate array of a specific route. I was able to narrow it down to these points.  No Map Matched Route is returning.

**Comment by PriyeshMohan** [comment]
Is there any other conditions that this could happen, in an old ticket road marked as private seems to return no route on map matching. Has anyone encountered other such exceptions?

**Comment by geografa** [comment]
@PriyeshMohan looking at the API request, it appears you have the coordinates in a reverse order (`latitude,longitude`). Try switching these to `longitude,latitude` to see if that fixes things. Example:
```
https://api.mapbox.com/matching/v5/mapbox/driving/76.10124656985505,10.380067051019353;76.10330103808496,10.374678083928359;76.10569791770467,10.369625842999511;76.10706756322747,10.364910344579044;76.10957857996505,10.358398349138056;76.11243200805603,10.353121288061487;76.11311683083568,10.349977464780793?geometries=geojson&radiuses=26;26;26;26;26;26;26&steps=true&access_token=<token>
```

**Comment by PriyeshMohan** [comment]
Hi @geografa ,
Thanks for pointing out. But my issue still exists. I will share the whole coordinate array. It all works fine when I removed one coordinate from the array. 
`    let coordinates = [
    
      CLLocationCoordinate2D(latitude: 10.223188, longitude: 76.157344),
      CLLocationCoordinate2D(latitude: 10.224452, longitude: 76.15678),
      CLLocationCoordinate2D(latitude: 10.228371, longitude: 76.154982),
      CLLocationCoordinate2D(latitude: 10.230133, longitude: 76.15456),
      CLLocationCoordinate2D(latitude: 10.231491, longitude: 76.154314),
      CLLocationCoordinate2D(latitude: 10.233772, longitude: 76.153536),
      CLLocationCoordinate2D(latitude: 10.236124, longitude: 76.153047),
      CLLocationCoordinate2D(latitude: 10.236871, longitude: 76.152994),
      CLLocationCoordinate2D(latitude: 10.239233, longitude: 76.152034),
      CLLocationCoordinate2D(latitude: 10.240566, longitude: 76.151534),
      CLLocationCoordinate2D(latitude: 10.242585, longitude: 76.150636),
      CLLocationCoordinate2D(latitude: 10.244888, longitude: 76.149581),
      CLLocationCoordinate2D(latitude: 10.246198, longitude: 76.149075),
      CLLocationCoordinate2D(latitude: 10.246435, longitude: 76.14914),
      CLLocationCoordinate2D(latitude: 10.246576, longitude: 76.149399),
      CLLocationCoordinate2D(latitude: 10.247382, longitude: 76.149106),
      CLLocationCoordinate2D(latitude: 10.249128, longitude: 76.148568),
      CLLocationCoordinate2D(latitude: 10.251586, longitude: 76.147767),
      CLLocationCoordinate2D(latitude: 10.2532, longitude: 76.147198),
      CLLocationCoordinate2D(latitude: 10.255331, longitude: 76.146485),
      CLLocationCoordinate2D(latitude: 10.257713, longitude: 76.145631),
      CLLocationCoordinate2D(latitude: 10.259335, longitude: 76.145086),
      CLLocationCoordinate2D(latitude: 10.262277, longitude: 76.144016),
      CLLocationCoordinate2D(latitude: 10.265049, longitude: 76.142824),
      CLLocationCoordinate2D(latitude: 10.267428, longitude: 76.14185),
      CLLocationCoordinate2D(latitude: 10.269435, longitude: 76.141009),
      CLLocationCoordinate2D(latitude: 10.272156, longitude: 76.139905),
      CLLocationCoordinate2D(latitude: 10.274001, longitude: 76.139242),
      CLLocationCoordinate2D(latitude: 10.274842, longitude: 76.139052),
      CLLocationCoordinate2D(latitude: 10.276003, longitude: 76.139381),
      CLLocationCoordinate2D(latitude: 10.27671, longitude: 76.139245),
      CLLocationCoordinate2D(latitude: 10.278778, longitude: 76.138376),
      CLLocationCoordinate2D(latitude: 10.280092, longitude: 76.137963),
      CLLocationCoordinate2D(latitude: 10.27996, longitude: 76.137401),
      CLLocationCoordinate2D(latitude: 10.27989, longitude: 76.136985),
      CLLocationCoordinate2D(latitude: 10.28071, longitude: 76.136654),
      CLLocationCoordinate2D(latitude: 10.282693, longitude: 76.136657),
      CLLocationCoordinate2D(latitude: 10.283046, longitude: 76.136799),
      CLLocationCoordinate2D(latitude: 10.28907, longitude: 76.13523),
      CLLocationCoordinate2D(latitude: 10.293285, longitude: 76.133773),
      CLLocationCoordinate2D(latitude: 10.296262, longitude: 76.132309),
      CLLocationCoordinate2D(latitude: 10.297171, longitude: 76.132646),
      CLLocationCoordinate2D(latitude: 10.298799, longitude: 76.132001),
      CLLocationCoordinate2D(latitude: 10.300814, longitude: 76.131378),
      CLLocationCoordinate2D(latitude: 10.302671, longitude: 76.130085),
      CLLocationCoordinate2D(latitude: 10.305646, longitude: 76.129321),
      CLLocationCoordinate2D(latitude: 10.307111, longitude: 76.128583),
      CLLocationCoordinate2D(latitude: 10.310404, longitude: 76.127788),
      CLLocationCoordinate2D(latitude: 10.313287, longitude: 76.126758),
      CLLocationCoordinate2D(latitude: 10.320235, longitude: 76.124563),
      CLLocationCoordinate2D(latitude: 10.324158, longitude: 76.12332),
      CLLocationCoordinate2D(latitude: 10.330182, longitude: 76.121534),
      CLLocationCoordinate2D(latitude: 10.335143, longitude: 76.119161),
      CLLocationCoordinate2D(latitude: 10.341219, longitude: 76.116982),
      CLLocationCoordinate2D(latitude: 10.345336, longitude: 76.115668),
      CLLocationCoordinate2D(latitude: 10.346483, longitude: 76.114301),
      CLLocationCoordinate2D(latitude: 10.354087, longitude: 76.11218),
      CLLocationCoordinate2D(latitude: 10.356534, longitude: 76.110388),
      CLLocationCoordinate2D(latitude: 10.363408, longitude: 76.107624),
      CLLocationCoordinate2D(latitude: 10.366167, longitude: 76.106462),
      CLLocationCoordinate2D(latitude: 10.368444, longitude: 76.105837),
      CLLocationCoordinate2D(latitude: 10.372496, longitude: 76.104251),
      CLLocationCoordinate2D(latitude: 10.374892, longitude: 76.103285),
      CLLocationCoordinate2D(latitude: 10.377437, longitude: 76.102046),//This is the point that makes the issue/
      CLLocationCoordinate2D(latitude: 10.382282, longitude: 76.100474),
      CLLocationCoordinate2D(latitude: 10.385931, longitude: 76.099006),
      CLLocationCoordinate2D(latitude: 10.388007, longitude: 76.098269),
      CLLocationCoordinate2D(latitude: 10.393629, longitude: 76.096121),
      CLLocationCoordinate2D(latitude: 10.393969, longitude: 76.095562),
      CLLocationCoordinate2D(latitude: 10.401174, longitude: 76.096066),
      CLLocationCoordinate2D(latitude: 10.404756, longitude: 76.09547),
      CLLocationCoordinate2D(latitude: 10.410245, longitude: 76.093995),
      CLLocationCoordinate2D(latitude: 10.415192, longitude: 76.092463),
      CLLocationCoordinate2D(latitude: 10.418025, longitude: 76.091028),
      CLLocationCoordinate2D(latitude: 10.421053, longitude: 76.09009),
      CLLocationCoordinate2D(latitude: 10.423375, longitude: 76.088895),
      CLLocationCoordinate2D(latitude: 10.424974, longitude: 76.08839),
      CLLocationCoordinate2D(latitude: 10.426201, longitude: 76.087464),
      CLLocationCoordinate2D(latitude: 10.425774, longitude: 76.084944),
      CLLocationCoordinate2D(latitude: 10.427778, longitude: 76.084487),
      CLLocationCoordinate2D(latitude: 10.428916, longitude: 76.083094),
      CLLocationCoordinate2D(latitude: 10.43048, longitude: 76.082926),
      CLLocationCoordinate2D(latitude: 10.431757, longitude: 76.08218),
      CLLocationCoordinate2D(latitude: 10.432428, longitude: 76.082185),
      CLLocationCoordinate2D(latitude: 10.433578, longitude: 76.081896),
      CLLocationCoordinate2D(latitude: 10.434576, longitude: 76.081544),
      CLLocationCoordinate2D(latitude: 10.436002, longitude: 76.081058),
      CLLocationCoordinate2D(latitude: 10.437122, longitude: 76.08163),
      CLLocationCoordinate2D(latitude: 10.438976, longitude: 76.07927),
      CLLocationCoordinate2D(latitude: 10.438273, longitude: 76.077238),
      CLLocationCoordinate2D(latitude: 10.437504, longitude: 76.075817)
    ]
    let mathcOptions = NavigationMatchOptions(coordinates: coordinates, profileIdentifier: MBDirectionsProfileIdentifier.automobileAvoidingTraffic)
    for waypoint in mathcOptions.waypoints.dropFirst().dropLast() {
      waypoint.separatesLegs = false
    }
    Directions.shared.calculateRoutes(matching: mathcOptions) { (waypoints, routes, error) in
      guard let route = routes?.first, error == nil else {
        return
      }
      print(route)
    }
 }`

**Comment by PriyeshMohan** [comment]
The issue was fixed by changing the coordinate accuracy.

**Comment by HoereeBauke** [comment]
Can you please provide me where and how you changed the coordinate accuracy?

**Comment by PriyeshMohan** [comment]
@HoereeBauke ,
 We can set coordinate accuracy for each waypoint like this. 

```
let routeOptions = NavigationMatchOptions(coordinates:routeCoordinates)
for wayPoint in routeOptions.waypoints {
      wayPoint.coordinateAccuracy = CLLocationAccuracy(exactly: <coordinateAccuracyValueInMeter>) 
}
// Then call map matching
```
