### ISSUE TITLE
Improve StepsViewController table UI when user is on final step

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-navigation-ios#2015]
**Mapbox Navigation SDK version:** 0.32.0

When a user is on the last step of turn-by-turn navigation, the top pull-down menu (controlled by the `StepsViewController`) is empty:

![image](https://user-images.githubusercontent.com/1242056/54152621-dff87d80-43fa-11e9-82e9-e8e35fcee43e.png)

It would be nice if there was some type of messaging or visual cue to the user in this case. Some ideas:

1. Always show all previous steps, but dim out the old ones and scroll them out of view by default (h/t @1ec5)
2. Allow the disabling of that pull-down menu when a user is on the last step.
3. Create an easier way for a developer to subclass `StepsViewController` and `StepTableViewCell` and inject that subclass into the built-in step table so they can customize it.

**Comment by akitchen** [comment]
Thanks for logging, @samfader 

FWIW I'm definitely in favor of `#3` from a UI customization perspective; `#1` sounds like it could be surprising as it would be an inversion of what the user sees during the rest of TBT directions -- I'd like more design input here.  No strong opinion or intuition on `#2`.

**Comment by Sherlaine** [comment]
Hey @samfader,

I consulted with our designer and we like option 1. Is it possible to add "Trip Completed" as the last line item of the trip as well?

**Comment by samfader** [comment]
Hi @Sherlaine - appreciate the input! Just to clarify, this is a public ticket to track this feature request for all users of our iOS Navigation SDK. It's also worth noting that if we are able to implement option three, you'd have the widest range of customization opportunities out of all the options.

**Comment by Sherlaine** [comment]
@samfader - yes that is a very valid point. Please change our option to number 3. Thank you.

**Comment by 1ec5** [comment]
> \#1 sounds like it could be surprising as it would be an inversion of what the user sees during the rest of TBT directions

The suggestion is that all previous steps would always be accessible, but dimmed out and scrolled out of view by default. You can try out this approach in Apple Maps.

We’d need to change how the current banner is presented, to ensure chronological order. Instead of a separate view that always appears above the table, it would be a row of the table that sticks to the top of the scroll view when you scroll down, just like `display: sticky` in CSS.

**Comment by frederoni** [comment]
Option 3 doesn't contradict option 1, we can implement both.

Perhaps we could show a vertical progress bar or breadcrumbs connecting each cell (de-emphasized completed steps) representing your current progress.

**Comment by MaximAlien** [comment]
@mapbox/navigation-android can you please share what's the logic on Android side at this point? Should be align this functionality on both iOS and Android?

**Comment by Zayankovsky** [comment]
On Android we expand the view to only show two additional instructions. The user has to scroll the list to see more. If there are less than two additional instructions, then the list will be partially or fully empty. 
![1](https://user-images.githubusercontent.com/2395284/142600697-111fc04d-088e-4908-86ff-7ee7c278e7c2.png)![2](https://user-images.githubusercontent.com/2395284/142600707-3ee53876-e893-41c3-a92f-ee95b5d87582.png)![3](https://user-images.githubusercontent.com/2395284/142600711-5b0612ec-fc1b-41b6-b30a-820abfc96574.png)
