### ISSUE TITLE
Route ends after each Waypoint

### ISSUE THREAD

**Issue by JustasL** [mapbox/mapbox-navigation-ios#204]
Not sure if this is more of Mapbox Directions or Mapbox Navigation question/problem

I would like to navigation over route with multiple specified points (up to 25), so that the path would be specific to my needs.
The problem is, that Mapbox Navigation thinks that every coordinate specified in `RouteOptions` for `Directions.shared.calculate` is a destination, while in reality I destination should be the last point.
Now, the Mapbox Navigation UI seems to understand, that my destination is final coordinate, as it continues to show route to that coordinate + arrival time is correct. What is incorrect, is that after first point it says, that I have arrived to destination and is stuck.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/14614780/25658842/96078908-300d-11e7-98f0-ddd8851d4454.jpg)

So what should I do, that Navigation would not show 

> You have arrived at your destination

Until user actually arrives at its destination?

**Comment by bsudekum** [comment]
Currently multiple waypoint navigation is not supported.

**Comment by JustasL** [comment]
By not supported you mean, I can create a `RouteOptions` with multiple coordinates (up to 25), but  MapboxNavigation will not be able to provide proper navigation, right?

Then follow up question, will such feature be implemented in the near future?

**Comment by 1ec5** [comment]
Also tracking on Android in mapbox/mapbox-navigation-android#27.

**Comment by bsudekum** [comment]
> By not supported you mean, I can create a RouteOptions with multiple coordinates (up to 25), but MapboxNavigation will not be able to provide proper navigation, right?

The Mapbox Directions API and MapboxDirections.swift honor waypoints however, the waypoints are not supported in this library yet.

> Then follow up question, will such feature be implemented in the near future?

Currently, this is not on our roadmap.

**Comment by 1ec5** [comment]
This feature is under development in #270.

**Comment by ericrwolfe** [comment]
Basic multiple waypoint support was merged into master with https://github.com/mapbox/mapbox-navigation-ios/pull/270 and will be part of the next release.
