### ISSUE TITLE
compile error after upgrading Mapboxnavigation from 0.19 to 0.30

### ISSUE THREAD

**Issue by RahulGusain** [mapbox/mapbox-navigation-ios#2062]
on passing direction to NavigationViewController is shows error: "Assigning to read only property", but before 0.30 version its working properly.
![Navigation](https://user-images.githubusercontent.com/48059937/55004717-b8133780-5000-11e9-902f-926f2093afb5.png)

**Comment by 1ec5** [comment]
> ```objc
> controller.directions = [MBDirections sharedDirections];
> ```

It isn’t necessary to set `MBNavigationViewController.directions` to `+[MBDirections sharedDirections]`, since that’s the default.

> ```objc
> controller.navigationService.locationManager = [[MBSimulatedLocationManager alloc]initWithRoute:self.route];
> ```

To simulate a route, create a navigation service with `MBNavigationSimulationOptionsAlways` to override the default navigation service that comes with MBNavigationViewController:

```objc
MBNavigationService *service = [[MBNavigationService alloc] initWithRoute:route
                                                               directions:nil
                                                           locationSource:nil
                                                        eventsManagerType:nil
                                                               simulating:MBNavigationSimulationOptionsAlways
                                                               routerType:nil];
MBNavigationOptions *options = [[MBNavigationOptions alloc] init];
options.navigationService = service;
MBNavigationViewController *controller = [[MBNavigationViewController alloc] initWithRoute:route options:options];
```
