### ISSUE TITLE
Mapbox Core Navigation and Swift 5 compile errors

### ISSUE THREAD

**Issue by z-mp** [mapbox/mapbox-navigation-ios#2063]
Would you pls add support for Swift5/Xcode 10.2?

**Comment by ianthetechie** [comment]
In related news, the 0.30.0 release doesn't build with Xcode 10.2.

**Comment by 1ec5** [comment]
We’re working on the issue in #2074 and mapbox/MapboxDirections.swift#363.

**Comment by frederoni** [comment]
Just wanted to add that one of the issues with Xcode 10.2 compatibility and Carthage was caused by merging Swift headers. There's a fix in Carthage on master but not yet released. (`brew unlink carthage && brew install carthage --HEAD` installs latest Carthage from master)
