### ISSUE TITLE
NavigationMatchOptions should default to polyline6

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-navigation-ios#2069]
For consistency with `NavigationRouteOptions`, `NavigationMatchOptions` should default to polyline6 encoding. Also, the navigator only supports polyline6 currently.

**Comment by 1ec5** [comment]
In https://github.com/mapbox/mapbox-navigation-ios/issues/631#issuecomment-452933320, I thought we had already quietly switched to polyline6. In any case, we may need to investigate #1924 further if we’re going to upgrade from polyline5 to polyline6.
