### ISSUE TITLE
Set `NavigationRouteOptions.includesSpokenInstructions` to false will cause exception in MapboxNavigationNative

### ISSUE THREAD

**Issue by seanphoenix** [mapbox/mapbox-navigation-ios#2073]
**Mapbox Navigation SDK version:**
v0.30.0

Hi guys,

I found that if I set the `NavigationRouteOptions.includesSpokenInstructions` to false, it will cause exception in MapboxNavigationNative. However, I am not gonna use the voice function.
Here is the exception:
```
*** Terminating app due to uncaught exception 'Invalid last_traversable_step voice count', reason: 'Invalid last_traversable_step voice count'
```
Any idea?

Thanks,
Sean Chiu

**Comment by akitchen** [comment]
Thanks for opening an issue @seanphoenix . This will be addressed in our next release.
