### ISSUE TITLE
Verify jazzy finds USRs on CI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2078]
To prevent #1795 from regressing a third time or less widespread USR issues from cropping up on individual symbols, we should add a step to the CircleCI configuration that runs jazzy and looks for any USR in a generated HTML file. Even better, we could parse jazzy’s output to look for USR warnings and fix the few that remain.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
It happened again: #2312.

**Comment by S2Ler** [comment]
Shall we prioritize this? @truburt @1ec5

**Comment by chezzdev** [comment]
I'm working on generating docs on CI, so I'll integrate warning checks in that scope.
