### ISSUE TITLE
`RouterDelegate.willArriveAt` and `RouterDelegate.didArriveAt` will never be called without voiceInstructions

### ISSUE THREAD

**Issue by seanphoenix** [mapbox/mapbox-navigation-ios#2099]
**Mapbox Navigation SDK version:**
0.31.0

Hi guys,

Found that the delegate will not be called if no voice instructions included in the route.
```swift
    func updateRouteLegProgress(status: MBNavigationStatus) {
        
        let legProgress = routeProgress.currentLegProgress
        let currentDestination = routeProgress.currentLeg.destination
        guard let remainingVoiceInstructions = legProgress.currentStepProgress.remainingSpokenInstructions else { return }
        
        // We are at least at the "You will arrive" instruction
        if legProgress.remainingSteps.count <= 2 && remainingVoiceInstructions.count <= 2 {
        ....
```
[https://github.com/mapbox/mapbox-navigation-ios/blob/f3c7ddd713ac2294e1922dc14a15c3e003d05e68/MapboxCoreNavigation/RouteController.swift#L228](https://github.com/mapbox/mapbox-navigation-ios/blob/f3c7ddd713ac2294e1922dc14a15c3e003d05e68/MapboxCoreNavigation/RouteController.swift#L228)

Is this designed behavior? 

Thanks,
Sean Chiu

**Comment by JThramer** [comment]
@seanphoenix Thanks for reporting! Yeah, this is an edge-case that was not considered at design-time. Adding this ticket to the board to track progress.
