### ISSUE TITLE
Allow the WayNameView to be removed from the map

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2104]
**Mapbox Navigation SDK version: 0.31.0**

To hide this view, we tried to supply an alpha to the following components in the style:
- `WayNameLabel.appearance().normalTextColor`
- `WayNameView.appearance().backgroundColor`
- `WayNameView.appearance().borderColor`

After doing this, the street symbols still appear in this area while driving. We want to remove the `WayNameView` from the map to avoid this, so we currently loop through subviews looking for the right instance and we remove it. It would be great if there was an official API to remove this button.

**Comment by nastasiupta** [comment]
Any update on this one ?

**Comment by johnnewman** [comment]
I don't know of an official API yet. We started experiencing a crash when the Mapbox Nav SDK attempted to add constraints after the `WayNameView` was removed from the hierarchy, so instead of `removeFromSuperview()`, we've had better luck with `isHidden`:
```Swift
let mbNavigationViewController = NavigationViewController(...)
// <add navigation view to hierarchy here>
mbNavigationViewController.view.allSubviews()
    .filter { $0 is WayNameView }
    .forEach { $0.isHidden = true }
```

**Comment by MaximAlien** [comment]
Will be fixed in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3758. This PR will make certain properties of `NavigationView` public (e.g. top and bottom banners). It'll also be possible to use `NavigationView` as a standalone component, similarly to `NavigationMapView`.

**Comment by MaximAlien** [comment]
As of https://github.com/mapbox/mapbox-navigation-ios/pull/4017 `WayNameView` is now exposed publicly in `NavigationView`, so it can be hidden by accessing either its `alpha` or `isHidden` properties.
