### ISSUE TITLE
Allow the Resume button to be customized

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2107]
**Mapbox Navigation SDK version: 0.31.0**

We would like to add custom styling to the Resume button that appears in the bottom corner when you pan away from your route while navigating. We're looking to change its text, image, corner radius, and position.

**Comment by S2Ler** [comment]
@1ec5 Any reasons why we can't expose `NavigationView.resumeButton` and make this class more open for customisations?

**Comment by obabovic** [comment]
Is there really no way to add corner radius to the `ResumeButton`?

**Comment by MaximAlien** [comment]
@obabovic, https://github.com/mapbox/mapbox-navigation-ios/pull/3996 will give the ability to set appearance styling for `borderColor`, `borderWidth` and `cornerRadius`.

@johnnewman, `NavigationView` will be made public in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3758, this will give the ability to modify properties of `ResumeButton` directly.
