### ISSUE TITLE
Out-of-band usage of RouteController.location causes instructions to be skipped

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2113]
As a Cocoa developer, I’d expect a getter such as `RouteController.location` or `RouteController.snappedLocation` to have no side effects (even if it may be expensive to get). But in fact, `RouteController.snappedLocation` calls `MBNavigator.getStatusForTimestamp(_:)` every time without caching the result:

https://github.com/mapbox/mapbox-navigation-ios/blob/fb2873cd6815e6aa795b85b3a3342576839e8821/MapboxCoreNavigation/RouteController.swift#L92

`MBNavigator.getStatusForTimestamp(_:)` is stateful: it’ll return a given spoken or visual instruction just once, so the extra calls to this method end up snarfing instructions that should be accessible to RouteController itself when updating the route progress in response to a location update.

A fix upstream in MapboxNavigationNative will distinguish between the two use cases for accessing the status, fixing this issue. Until then, applications should avoid accessing `location` or `snappedLocation` out of band or redundantly. I think we need to issue a warning when the getters are used this way or at least document the problem until we have a fix.

/cc @mapbox/navigation-ios @kevinkreiser

**Comment by 1ec5** [comment]
The following workarounds are available:

* Implement `NavigationServiceDelegate.navigationService(_:didUpdate:with:rawLocation:)` and use the passed-in `location` and `rawLocation` arguments.
* Observe `Notification.name.routeControllerProgressDidChange` notifications from the route controller and use the values associated with `RouteControllerNotificationUserInfoKey.locationKey` and `rawLocationKey` in the `userInfo` dictionary.
* Specify `LegacyRouteController` as the router type when initializing the NavigationService.

**Comment by andrlee** [comment]
update from @kevinkreiser: 
> its quite a big refactor and we'll have to do a lot of work to get the test coverage back up
its basically a major api change
so i guess the only thing blocking it really is that its a decent amount of work

@1ec5 could we roll with one of the workarounds? i'd like to discuss tradeoffs of each workaround if possible.

**Comment by frederoni** [comment]
Simplifying the first workaround with this patch should be a valid workaround.

<details><summary>Patch</summary>

```diff
diff --git a/MapboxCoreNavigation/RouteController.swift b/MapboxCoreNavigation/RouteController.swift
index d009f49b..b6006767 100644
--- a/MapboxCoreNavigation/RouteController.swift
+++ b/MapboxCoreNavigation/RouteController.swift
@@ -88,13 +88,7 @@ open class RouteController: NSObject {
      The raw location, snapped to the current route.
      - important: If the rawLocation is outside of the route snapping tolerances, this value is nil.
      */
-    var snappedLocation: CLLocation? {
-        let status = navigator.getStatusForTimestamp(Date())
-        guard status.routeState == .tracking || status.routeState == .complete else {
-            return nil
-        }
-        return CLLocation(status.location)
-    }
+    var snappedLocation: CLLocation?
     
     var heading: CLHeading?
     
@@ -172,6 +166,14 @@ open class RouteController: NSObject {
         
         let status = navigator.getStatusForTimestamp(location.timestamp)
         
+        // Updated snapped location if status is tracking or stale.
+        let snappedStates: [MBRouteState] = [.tracking, .stale]
+        if snappedStates.contains(status.routeState) {
+            snappedLocation = CLLocation(status.location)
+        } else {
+            snappedLocation = nil
+        }
+        
         // Notify observers if the step’s remaining distance has changed.
         update(progress: routeProgress, with: CLLocation(status.location), rawLocation: location)
         

```

</details>

**Comment by kevinkreiser** [comment]
If it helps we can also rename the method so that it doesnt give the impression that it isnt an input to a state machine. In the native code we signal modification of the underlying object by omitting a qualifier on the method, of course the bindings we provide may not follow this pattern and it may not even make sense in some target languages so we can't rely on this anyway. It would be great if you could point out any other other warts in the API that are not idiomatic.

**Comment by 1ec5** [comment]
The patch in https://github.com/mapbox/mapbox-navigation-ios/issues/2113#issuecomment-513833620 would be valid, but at the risk of even more parallel state between Core Navigation and MapboxNavigationNative. We already see this risk play out when it comes to applications manually advancing from one leg to another and so on.

**Comment by MaximAlien** [comment]
Looks like this issue is no longer reproducible after switching to `Navigator.getStatusForMonotonicTimestampNanoseconds(_:)` instead of `Navigator. getStatusForTimestamp(_:)` in Navigation Native `22.0.5`. Also instead of adding new test which verifies that existing test `testOrderOfExecution` was updated in https://github.com/mapbox/mapbox-navigation-ios/pull/2454.

**Comment by MaximAlien** [comment]
@1ec5, unit test was slightly improved. If you feel like we need to do additional work here please let me know. Otherwise, I think we can close this ticket.

**Comment by 1ec5** [comment]
> Looks like this issue is no longer reproducible after switching to `Navigator.getStatusForMonotonicTimestampNanoseconds(_:)` instead of `Navigator.getStatusForTimestamp(_:)` in Navigation Native `22.0.5`.

The two methods behave similarly from an SDK perspective. What must’ve done the trick is being consistent about the timestamps we pass into the status getter and not allowing the developer to pass in an arbitrary timestamp: #2610. In hindsight, that’s pretty obvious, but this ticket was about trying to support arbitrary timestamps, which we now know is unsupportable. Thanks for following up with a test to ensure consistency.
