### ISSUE TITLE
No RouteProgress updates when shape format is geoJSON

### ISSUE THREAD

**Issue by nilsthamm** [mapbox/mapbox-navigation-ios#2125]
**Mapbox Navigation SDK version:** 0.32.0 (CocoaPods)
**Xcode Version:** 10.2.1
**Tested on various iPads (simulator and real) with iOS 12.2**

Hi everyone,
First of all, thanks for the solid framework you are providing, it's really good to work with!
While working with the results from the Mapbox Navigation API within the SDK, I discovered a bug:

If the `shapeFormat` parameter of the `NavigationRouteOptions` is set to `RouteShapeFormat.geoJSON` the `routeProgress` object is not updated during simulation. In the UI this leads to not updating route statistics, missing voice commands, and not updating direction instructions. And as shown in the example below, all properties of the `routeProgress` object are not updated.
Through debugging I could only narrow it down to a not correct calculated `status` object in `RouteController.locationManager(_:didUpdateLocations:)`. All called update functions afterwards can't read any progress from the retrieved status object.

To reproduce the error just execute this modified version of the basic example:
```swift
import UIKit
import MapboxCoreNavigation
import MapboxNavigation
import MapboxDirections

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let origin = CLLocationCoordinate2DMake(37.77440680146262, -122.43539772352648)
        let destination = CLLocationCoordinate2DMake(37.76556957793795, -122.42409811526268)
        let options = NavigationRouteOptions(coordinates: [origin, destination])
        
        
        /* ADDED TO SIMULATE THE ERROR */
        options.shapeFormat = RouteShapeFormat.geoJSON
        NotificationCenter.default.addObserver(self, selector: #selector(routeProgressUpdate(_:)), name: .routeControllerProgressDidChange, object: nil)
        
        Directions.shared.calculate(options) { (waypoints, routes, error) in
            guard let route = routes?.first, error == nil else {
                print(error!.localizedDescription)
                return
            }
            options.profileIdentifier = MBDirectionsProfileIdentifier.automobile
            
            // For demonstration purposes, simulate locations if the Simulate Navigation option is on.
            let navigationService = MapboxNavigationService(route: route, simulating: .always)
            let navigationOptions = NavigationOptions(navigationService: navigationService)
            let navigationViewController = NavigationViewController(for: route, options: navigationOptions)
            
            self.present(navigationViewController, animated: true, completion: nil)
        }
    }
    
    /* ADDED TO SIMULATE THE ERROR */
    @objc func routeProgressUpdate(_ notification: NSNotification) {
        let progress = notification.userInfo![RouteControllerNotificationUserInfoKey.routeProgressKey] as! RouteProgress
        print(progress.currentLegProgress.remainingSteps.count)
    }


}
```

**Comment by 1ec5** [comment]
@kevinkreiser, do you know if MapboxNavigationNative supports GeoJSON-formatted route geometries, or only Polyline-encoded geometries?

**Comment by kevinkreiser** [comment]
@1ec5 right now it only supports polyline6 geometries but it would be a very small amount of effort to add both polyline5 and geojson imho

**Comment by 1ec5** [comment]
That would be desirable. We effectively regressed this functionality when migrating to MapboxNavigationNative, because even though the default changed to polyline6, there has always been an option to customize the format.

**Comment by 1ec5** [comment]
The workaround is to leave the shape format as the default. The default value, `polyline6`, consumes much less bandwidth and processing time than `geojson` and doesn’t affect the shape data that application code has access to.

A possible workaround in the SDK itself would be to hardcode `polyline6` as the shape format when serializing back to JSON for MapboxNavigationNative’s consumption, though we’d need to first make a copy of the options object to avoid affecting rerouting requests.

https://github.com/mapbox/mapbox-navigation-ios/blob/8ca6122e56d2cce996b505e843989d32b1f9d70d/MapboxCoreNavigation/Route.swift#L7
