### ISSUE TITLE
Refactor voice controller

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-navigation-ios#2131]
The voice controller’s mute and volume behavior should be reusable. Currently, RouteVoiceController doesn't respect `NavigationSettings.voiceVolume`. `AVSpeechUtterance` exposes a `volume` property which may be a good candidate.

The voice controller should also become a protocol to make it possible to extend the functionality and add supported languages via Objective-C, which can't subclass Swift classes, but can conform to Swift protocols.

Modifying SpeechOptions on `MapboxVoiceController` is a bit convoluted because it has to be recreated each time. See https://github.com/mapbox/mapbox-navigation-ios/issues/2127

@mapbox/navigation-ios

**Comment by frederoni** [comment]
iOS 13 users should default to Siri Neural TTS if the language is supported.

**Comment by 1ec5** [comment]
> iOS 13 users should default to Siri Neural TTS if the language is supported.

If I’m not mistaken, this capability isn’t available to developers.

**Comment by 1ec5** [comment]
Superseded by #2268.
