### ISSUE TITLE
StatusView refactor

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#2135]
👋 

`StatusView` really needs a refactor. It purports itself as a general-purpose view to display status messages, which it can do, but the `StatusViewDelegate.statusView(_:valueChangedTo:)` message is the only way to capture interaction with the status view, and that doesn't really make sense when there's no "value" involved.

We should replace this with a generic "didSwipe" delegate message and leave the business logic of changing the simulation speed up to the `NavigationViewController.`

It's also worth pointing out that refactoring was called for in #1367, but that ticket has since grown stale.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
After hemming and hawing over this class, I finally decided that it can keep its `value` property, but because of that property, we should treat it like a UIControl instead of an ordinary view. #2136 turns it into a UIControl subclass. The idea is that it’s a multifaceted hybrid of UISlider, NSScrubber, NSStepper, and status bars. 🤷‍♂

**Comment by 1ec5** [comment]
Ideas for future improvements to StatusView:

* Turn StatusView into a subclass of UISlider, replacing the scrubbing gesture with a more intuitive sliding gesture that has better perceived performance.
* Embed explicit + and − buttons on either side of the StatusView for whenever the control is adjustable (“interactive”). The view controller could manage those buttons directly.
* StatusView could have a `leftAccessoryView` and `rightAccessoryView`, and the right accessory view could be either a + button or a spinner. Again, the view controller would be responsible for managing those accessory controls’ actions.

Both those options would require ditching the scrubbing gesture, which I only learned of the other day anyways. If we need another affordance for quickly adjusting the speed, we could have the + and − buttons [fire continuously while held down](https://stackoverflow.com/a/997464/4585461).

**Comment by JThramer** [comment]
Closing as stale.
