### ISSUE TITLE
Notification needed when style changes between day/night

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/mapbox-navigation-ios#2139]
Users working with day/night styles have no way of being notified when a style is applied  in order to swap out UI elements added as style-specific overlays. The map style and UI within NavigationViewController update automatically given the time of day but there is no way to be notified when the style is applied.

A proposed option would be setting up style manager anywhere except a subclass of `NavigationViewController`. However, the user wouldn’t be notified when the style changes due to entering/exiting a tunnel.

cc @frederoni

**Comment by achhaiba** [comment]
My proposed idea is to use The NotificationCenter mechanism of iOS SDK in the overridden apply() method of any Style subclass (in CustomDayStyle/CustomNightStyle in my case).

```
class CustomDayStyle: DayStyle {
    
   override func apply() {
        super.apply()
        
// Notify style type change
        notifyStyleChange()
    }

}


class CustomNightStyle: NightStyle {
    
   override func apply() {
        super.apply()
        
// Notify style type change
        notifyStyleChange()
    }

}


extension Style {

    func notifyStyleChange() {
        let styleTypeDict:[String: StyleType] = ["styleType": styleType]
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "StyleChangeNotification"), object: nil, userInfo: styleTypeDict)
    }
}

```



Add observer to listen to style change anywhere even NavigationViewController subclass
 
```
class CustomNavigationViewController: NavigationViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(self, selector: #selector(styleDidChange(_ :)), name: NSNotification.Name(rawValue: "StyleChangeNotification"), object: nil)
    }
    
    @objc func styleDidChange(_ notification: NSNotification) {
        let styleType = notification.userInfo!["styleType"] as! StyleType
        print(styleType) // This log whether day or night value
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self, name: NSNotification.Name(rawValue: "StyleChangeNotification"), object: nil)
    }
}
```

This solution also notify entering/exiting tunnel, ensures a simultaneously refresh of all UI elements and no two StyleManager instances running witch could be valuable for memory footprint.
