### ISSUE TITLE
Update pod to Mapbox 5.0

### ISSUE THREAD

**Issue by diegogarciar** [mapbox/mapbox-navigation-ios#2140]
Hello, I'm trying to install via pods 'Mapbox-iOS-SDK' 5.0.0 but MapboxNavigation is preventing me from doing it. I have 'Mapbox-iOS-SDK' 4.3 and when forcing to 5.0 I received this error message

```
[!] CocoaPods could not find compatible versions for pod "Mapbox-iOS-SDK":
  In Podfile:
    Mapbox-iOS-SDK (~> 5.0)

    MapboxNavigation (~> 0.33.0) was resolved to 0.33.0, which depends on
      Mapbox-iOS-SDK (~> 4.3)

Specs satisfying the `Mapbox-iOS-SDK (~> 5.0), Mapbox-iOS-SDK (~> 4.3)` dependency were found, but they required a higher minimum deployment target.
```
My current deployment target is iOS 10.0, here are my pods
```
pod 'Mapbox-iOS-SDK' , '~> 5.0'
pod 'MapboxNavigation' , '~> 0.33.0'
```

I also commented out the  MapboxNavigation pod to succesfully install 'Mapbox-iOS-SDK' 5.0, but received the same error after uncommenting 'MapboxNavigation'

**Comment by diegogarciar** [comment]
I just pointed the pod to the master branch and it worked, so I'm guessing it will be automatically fixed on next release. We can close this for now.

here's the solution in case others have the same issue in the meantime:
`pod 'MapboxNavigation',  :git => 'https://github.com/mapbox/mapbox-navigation-ios', :branch => 'master'`

**Comment by frederoni** [comment]
> fixed on next release

That's correct.
