### ISSUE TITLE
Can't opt-out out of faster-route detection

### ISSUE THREAD

**Issue by noway** [mapbox/mapbox-navigation-ios#2153]
**Mapbox Navigation SDK version:**
```
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" "5.0.0"
binary "https://www.mapbox.com/ios-sdk/MapboxNavigationNative.json" "6.2.1"
github "ceeK/Solar" "2.1.0"
github "mapbox/MapboxDirections.swift" "v0.28.0"
github "mapbox/mapbox-events-ios" "v0.9.4"
github "mapbox/mapbox-navigation-ios" "v0.34.0"
github "mapbox/mapbox-speech-swift" "v0.1.1"
github "mapbox/turf-swift" "v0.3.0"
github "raphaelmor/Polyline" "v4.2.1"
```

**The issue:**

As described here (https://docs.mapbox.com/ios/navigation/overview/rerouting/#faster-route-detection), i'm trying to do:

```
      MBNavigationService *mbNavigationService = [[MBNavigationService alloc] initWithRoute:route directions:nil locationSource:nil eventsManagerType:nil simulating:MBNavigationSimulationOptionsNever routerType:routerType];
      mbNavigationService.router.reroutesProactively = false;
```

but I'm getting 
```
Assignment to readonly property
```
 error.

The router property doesn't seem to have a setter. Is there really a working way to disable that property?

**Comment by 1ec5** [comment]
`MBNavigationService.router` is of type `Router`, which is a protocol that only requires a getter for the property. But both MBRouteController and MBLegacyRouteController provider a setter; cast it to the class specified by `routerType`. We’ll get the documentation corrected. Thanks for reporting the issue!

/cc @JThramer

**Comment by noway** [comment]
```
  ((MBRouteController *) mbNavigationService.router).reroutesProactively = false;
```

compiles good for me (my routerType is `nil`, using MBRouteController atm). I'm not quite sure if it actually works, it's pretty hard to test it, but I'll just leave it at that.

Thank you!!
