### ISSUE TITLE
Example app shows blank map after ending navigation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2155]
In Xcode 11.0 beta (11M336w), after ending a navigation session, the example application shows a blank map.

<img src="https://user-images.githubusercontent.com/1231218/59809900-a4056c00-92b7-11e9-986b-6355ae51010b.png" width="300" alt="blank">

This probably has something to do with the new view controller presentation style.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
`ViewController.presentAndRemoveMapview(_:completion:)` removes the map view from the view hirerarchy to economize on memory, per [these instructions](https://docs.mapbox.com/ios/api/navigation/0.34.0/reduce-memory-usage.html). Then it relies on `viewWillAppear(_:)` to reinstall the map view:

https://github.com/mapbox/mapbox-navigation-ios/blob/0fcaf83b1e5b2dbfba739ba23986bbcecb111914/Example/ViewController.swift#L124-L133

Starting with iOS 13.0, `viewWillAppear(_:)` and `viewDidAppear(_:)` won’t get called after a modally presented view controller is dismissed, because the modal only covers part of the window.

**Comment by JThramer** [comment]
Serendipitously fixed by #2182.
