### ISSUE TITLE
How to disable traffic?

### ISSUE THREAD

**Issue by JustasL** [mapbox/mapbox-navigation-ios#216]
How to disable traffic? I've tried like this:
`navigationViewController.mapView?.showsTraffic = false` 
I'm setting it before preseting navigationViewController, mapView may be nil there, but I've tried to set it inside navigationViewController viewWillAppear, did nothing.
I've also tried modifying source code, like this:

```
   public var showsTraffic: Bool {
         (...)
        set {
            if let style = style {
                for layer in style.layers {
                    if let layer = layer as? MGLForegroundStyleLayer {
                        if layer.sourceIdentifier == "mapbox://mapbox.mapbox-traffic-v1" {
THIS LINE HERE ->           layer.isVisible = false//newValue
                        }
                    }
                }
            }
        }
    }
```

Did not work either

**Comment by bsudekum** [comment]
Yeah there are 2 issues here:

* `mapbox://mapbox.mapbox-traffic-v1` is no longer used, we're using v2 now
* The style on the mapview is not yet loaded causing `if let style = style {` to always be false if set before presenting.

Looking into this.

**Comment by JustasL** [comment]
I guess it's fairly easy, just add `public var showsTraffic: Bool?` to `NavigationViewController`, expand `RouteMapViewControllerDelegate` with `func navigationMapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)`, implement it in `NavigationViewController` 
```
    func navigationMapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
        guard let showsTraffic = showsTraffic else { return }
        mapView.showsTraffic = showsTraffic
    }
``` and of course call it in `RouteMapViewController.mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)`

**Comment by bsudekum** [comment]
@JustasL want to PR this?

**Comment by JustasL** [comment]
I've never done this, thus I have a feeling it will take a while for me to do it (for the first time), so just for this time I'll pass. 
On the positive side I just wrote whole code, which works, I've tested it,
