### ISSUE TITLE
Expanding the top instructions banner breaks animations

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2165]
**Mapbox Navigation SDK version: 0.35.0**

When the default instruction banner view is expanded, the instruction labels can animate incorrectly as they are appearing. They can be seen growing from the 0,0 origin.

The offset of the map also seems to change, causing it to recenter to the user's location after closing the instructions. You can see the circular route and volume buttons moving with the banner change as well.

I am supplying `nil` as the `topBanner` to `NavigationOptions`.

Here is a zip of a screen recording showing the issues: [Banner.MOV.zip](https://github.com/mapbox/mapbox-navigation-ios/files/3336670/Banner.MOV.zip)

**Comment by JThramer** [comment]
@johnnewman Thanks for reporting! Will look into this ASAP.

**Comment by johnnewman** [comment]
Thank you for looking into this! After trying out the changes in `0.36.0`, the labels appear fiexed, but I am still seeing:

>The offset of the map also seems to change, causing it to recenter to the user's location after closing the instructions. You can see the circular route and volume buttons moving with the banner change as well.

**Comment by 1ec5** [comment]
Good to hear that the labels are fixed. I didn’t notice the bit about the map offset until now – thanks for following up. This sounds like what we’re tracking in #2145, which is ultimately caused by mapbox/mapbox-gl-native#15233.
