### ISSUE TITLE
Day/night changes while navigating don't update the top instructions banner

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2166]
**Mapbox Navigation SDK version:0.35.0**

The default top banner no longer changes its background color when the time of day changes. If you start navigation, change the time in settings, then reopen the app, the top banner will not properly reflect the background color change.

Below are two screenshots from the same build. The one on the left shows what the top banner looks like when starting navigation at night. The screenshot on the right is from transitioning from day to night while navigating. 

| Starting nav at Night | Transitioning to Night from Day |
| ---- | ---- |
| ![IMG_2842](https://user-images.githubusercontent.com/1591735/60302574-24ece500-9902-11e9-9c70-9cc51bbd7379.jpg) | ![IMG_2843](https://user-images.githubusercontent.com/1591735/60302585-2a4a2f80-9902-11e9-8472-63aacb8edcfe.jpg) |

**Comment by JThramer** [comment]
👋 @johnnewman,

Thanks for reporting! Looks like there were a couple of lingering bugs in the UI customization work that we recently completed. I'll take a look ASAP.
