### ISSUE TITLE
I can't start navigation on iOS 13

### ISSUE THREAD

**Issue by Alejandro99aru** [mapbox/mapbox-navigation-ios#2171]
On navigation settings.swift

public static let shared = NavigationSettings() <-------error in this line (56 line)

Thread 1: signal SIGABRT

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by 1ec5** [comment]
Which version of the navigation SDK are you seeing this crash on? #2156 fixed a similar-looking crash and made it into v0.35.0.

**Comment by Alejandro99aru** [comment]
> Which version of the navigation SDK are you seeing this crash on? #2156 fixed a similar-looking crash and made it into v0.35.0.

in v0.33.0

**Comment by 1ec5** [comment]
OK, let us know if you still see the issue in v0.35.0.

**Comment by Alejandro99aru** [comment]
Hi, in v0.35.0 as I have attached it works for ios 13 but the button banner is not showed. In ios 12 if I run the same project all works fine.
![Simulator Screen Shot - iPhone Xs - 2019-07-23 at 23 50 19](https://user-images.githubusercontent.com/19738222/61750085-b423d600-ada4-11e9-9f76-8bffeb4ff27d.png)

**Comment by denis-couras** [comment]
Hi, I'm recreate the constraints for CancelButton, DistanceRemainingLabel, TimeRemainingLabel, ArrivalTimeLabel and BottomBannerContainerView
