### ISSUE TITLE
Test CarPlay with iOS 13

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-navigation-ios#2172]
This ticket tracks CarPlay changes introduced with iOS 13 and their impact on mapbox navigation SDK for iOS. The scope of test range from UI to new carplay dashboard. Details TBD.

**Comment by 1ec5** [comment]
So far we’ve found #2191 by testing on the simulator. We still need to test on a CarPlay device.

**Comment by S2Ler** [comment]
Closing as stale. CarPlay evolved and tested on real devices a lot since the ticket was opened.
