### ISSUE TITLE
Guidance Cards - Snapshot tests to harden visual outputs.

### ISSUE THREAD

**Issue by vincethecoder** [mapbox/mapbox-navigation-ios#2174]
Add snapshot tests for the following component outputs:

1. Basic visual representation of instructions on a guidance card.

2. Compounded visual representation of instructions on a guidance card.
     i. Next Banner instructions
    ii. Lane Indications

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Snapshot tests have been added to #2149.
