### ISSUE TITLE
Guidance Cards - multi-leg routes.

### ISSUE THREAD

**Issue by vincethecoder** [mapbox/mapbox-navigation-ios#2176]
Extend the guidance cards to permit multi-leg navigation. 

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Context: https://github.com/mapbox/mapbox-navigation-ios/pull/2149#pullrequestreview-251807970

**Comment by JThramer** [comment]
Action Plan Suggestion: 

- Turn `InstructionsCardViewController.steps` into a two-dimensional array (or weakly refer to route model`
- `InstructionsCardViewController.currentStepIndex` needs to turn into an `IndexPath` that can track both the current step and leg.

**Comment by 1ec5** [comment]
@nishant-karajgikar determined that guidance cards were functioning properly with multileg routes after all.
