### ISSUE TITLE
Device Volume Low status not disappearing

### ISSUE THREAD

**Issue by imaginaris** [mapbox/mapbox-navigation-ios#2180]
**Mapbox Navigation SDK version: 0.35.0**

After starting navigation with low volume a status is presented but it's not hidden after 3s.
It can disappear only if replaced with "Rerouting..." status.

Root cause:
`isCurrentlyVisible` flag in StatusView.swift is set to true only after `show()` animation is completed but `hide()` checks this flag before scheduling its animation when show animation is ongoing

I can suggest moving line 179 (guard) into the beginning of dispatch async body.

**Comment by 1ec5** [comment]
Thanks for the report and suggested bug fix: #2183.
