### ISSUE TITLE
Waypoint Confirmation issues

### ISSUE THREAD

**Issue by JurajKub** [mapbox/mapbox-navigation-ios#2186]
Hello.
I am building an enterprise application using MapBox. The application will need to incorporate an in app turn by turn navigation with multiple waypoints.
I tried your example with all navigations using Simulator iOS 12.2 and iPhone XS. In both cases when pausing the navigation using didArriveAt returning false and then manually advancing route leg along with starting navigation it does not work.
I am attaching a code:

>             guard let navigationViewController = self.presentedViewController as? NavigationViewController,
>                   let navService = navigationViewController.navigationService else { return }
> 
>             let router = navService.router!
>             guard router.route.legs.count > router.routeProgress.legIndex + 1 else { return }
>             
>             router.routeProgress.legIndex += 1
>             navService.start()

**Actual result:**
When the user arrives at the waypoint and clicks continue the leg is not advanced and navigation gets stuck at the first waypoint. It never receives top banner instructions or voice instructions. Sometimes it will switch to next leg and then switch back to first again making navigation stuck.

**Expected result:**
The leg should be advanced and navigation should continue navigating.

Quick solution: I found returning true and having the navigation handle the leg switch automatically helps and it will continue with navigation.

Please mark the feature as not supported or provide some solution as this functionality is required in the app I am building.

**Mapbox Navigation SDK version:** 0.35.0 and some older

**Comment by JurajKub** [comment]
Any news? I thought Mapbox as a paid service should have some kind of support. Maybe I am doing something wrong, but my solution was just to skip Waypoint Confirmation and directly continue navigation. This is not what I expected from SDK.

**Comment by 1ec5** [comment]
Hi @JurajKub, thank you for your bug report. At a glance, this is unexpected behavior and we’ll look into it.

> I thought Mapbox as a paid service should have some kind of support.

This is the right place to file bug reports, but if you need support, especially a time-sensitive response, please [reach out to our support team](https://www.mapbox.com/contact/). Thank you.

**Comment by 1ec5** [comment]
Fixed in #2229.
