### ISSUE TITLE
CarPlay route preview does not fit to the route

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2190]
When previewing a route on CarPlay in v0.35.0 with map SDK v5.2.0, the route rarely fits the screen. The camera never takes into account the left sidebar:

<img width="539" alt="" src="https://user-images.githubusercontent.com/1231218/61982314-3aad0300-afb1-11e9-8221-3946408f48c3.png">
<img width="539" alt="" src="https://user-images.githubusercontent.com/1231218/61982320-3da7f380-afb1-11e9-8d9c-0dd2aeeaf54e.png">
<img width="539" alt="" src="https://user-images.githubusercontent.com/1231218/61982306-354fb880-afb1-11e9-8054-7c277ab8f104.png">

It’s usually fine when the preview map first appears, but the problem starts as soon as you switch to an alternative route. At the point where `CarPlayManager.mapTemplate(_:selectedPreviewFor:using:)` calls `NavigationMapView.showcase(_:animated:)`, there’s never a left content inset, even though the content inset would’ve already been set to the CarPlay safe area insets in `CarPlayMapViewController.viewSafeAreaInsetsDidChange()`.

This issue appears to be caused primarily by a combination of mapbox/mapbox-gl-native#15232 and mapbox/mapbox-gl-native#15233, but it used to reproduce less frequently in previous versions of the map SDK, so there may be other compounding factors as well.

/cc @mapbox/navigation-ios @mapbox/maps-ios

**Comment by astojilj** [comment]
@1ec5 The workaround in https://github.com/mapbox/mapbox-navigation-ios/pull/2211 makes this look correct. PTAL.
