### ISSUE TITLE
Repeatedly swiping down on the instructions banner breaks UI/animations

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2195]
**Mapbox Navigation SDK version: 0.33.0 and 0.36.0**

Swiping down on the default top instructions banner after it has already been presented breaks the instruction presentation animation.

Only seen on 0.36.0: it can also cause the close button on the instructions list to become unresponsive. When this happens, swiping down one more time on the top banner will re-run the animation and cause the close button to start working again.

Attached is a recording from an iPhone 6 showing the animations from a few repetitive swipes on the top banner before closing it on 0.36.0.

[banner_swipes.MOV.zip](https://github.com/mapbox/mapbox-navigation-ios/files/3443390/banner_swipes.MOV.zip)

**Comment by JThramer** [comment]
@johnnewman Have reproduced. Thanks for reporting. Working on this now.
