### ISSUE TITLE
"Faster Route Found" Message Appearing

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-ios#2196]
I keep seeing a "Faster Route Found" message that spins endlessly at the top of my NavigationMapView.  However, nothing ends up happening with it.  Is that suppose to issue a reroute command automatically or do I need to catch it somehow and do something with it (calculate a new route based on the current location)?  Please see the attached screenshot.

**Mapbox Navigation SDK version:**
0.35.0

Expected Result:
I guess I'm not sure what is supposed to happen.  Any help you can give me is greatly appreciated.

Actual Result:
The message appears indefinitely and spins until I restart the navigation.

![IMG_8836](https://user-images.githubusercontent.com/5864607/62090829-3ea08580-b23c-11e9-830a-d0a9a836dc41.PNG)

**Comment by 1ec5** [comment]
Can you try upgrading to v0.36.0? I suspect #2183 may have fixed the issue.

**Comment by billyking991** [comment]
Will do.  I will let you know once I test a bit.  Thank you!!

**Comment by andrlee** [comment]
@billyking991 any updates?

**Comment by billyking991** [comment]
I apologize for the delay in getting back to you.  I got side tracked.  It's all fixed with 0.36.0.  Thank you!
