### ISSUE TITLE
stop navigation programmatically

### ISSUE THREAD

**Issue by pintonos** [mapbox/mapbox-navigation-ios#2201]
Is it possible to stop the navigation correctly in a programmatically way?
If i use `navigationViewController.dismiss(animated: true, completion: nil)` the view is hidden but the navigation runs in background and instructions are still played.
The goal is to have the same functionality as pressing the cancel button in the navigation view as a function call.
Is there a way to do this?

**Comment by imaginaris** [comment]
In my case removing NavigationViewController from ui stack (and making sure no other object holds strong reference to it) works fine. navigationViewControllerDidDismiss delegate method is called in both cases

**Comment by 1ec5** [comment]
> If i use `navigationViewController.dismiss(animated: true, completion: nil)` the view is hidden but the navigation runs in background and instructions are still played.

This is because NavigationViewController continues to hold a strong reference to the navigation service. NavigationViewController’s `viewWillDisappear(_:)` should probably stop the navigation service.

**Comment by JThramer** [comment]
@pintonos: 

Use `navigationViewController.navigationService.stop()` to stop the navigation session, then `dismiss` the UI.

**Comment by benorgan** [comment]
We are also experiencing this, calling `navigationViewController.navigationService.stop()` and `navigationViewController.navigationService.endNavigation()` before dismiss doesn't seem to resolve it.

**Comment by Hitchlet** [comment]
I am having the issue as well. The work around doesn't appear to work. I called navigationViewController.navigationService.stop() and navigationViewController.navigationService.endNavigation() before dismiss, but delegate does not receive navigationViewControllerDidDismiss. Any other alternatives?

**Comment by AbleCable1** [comment]
Having the same issue. Calling `navigationViewController.navigationService.stop()` doesn't solve the issue. What's the current workaround?

**Comment by 1ec5** [comment]
I haven’t tried it myself, but I think the suggestion in https://github.com/mapbox/mapbox-navigation-ios/issues/2201#issuecomment-528035987 was not only to call `stop()` but to also call `NavigationViewController.dismiss(animated:completion:)`.

**Comment by dawidvdh** [comment]
Using both the `NavigationViewController.dismiss(animated:completion:)` and `.stop()` doesn't work, I still receive voice instructions in the background.

**Comment by amisolani-simformsolutions** [comment]
I have manually stopped the navigation service before dismissing UI, and that worked properly for me.

```
func navigationViewControllerDidDismiss(_ navigationViewController: NavigationViewController, byCanceling canceled: Bool) {
        navigationViewController.navigationService.stop()
        self.navigationViewController?.dismiss(animated: true, completion: nil)
 }
```

**Comment by younusmahmood** [comment]
Anyone have any luck solving this? I've been trying to just get navigationViewControllerDidDismiss to fire but none of my logs in the function are being printed.

**Comment by JanTG1** [comment]
Same thing. using stop() stopped the process (When closing out of the app, the iPhone doesn't show that navigation is running anymore) but user location is still being tracked and logged.

**Comment by Udumft** [comment]
It is now possible to stop the navigation using `Router.finishRouting()`, see details in this PR: https://github.com/mapbox/mapbox-navigation-ios/pull/3880
