### ISSUE TITLE
iOS Error installing Mapbox-iOS-SDK (5.2.0)

### ISSUE THREAD

**Issue by tharssh** [mapbox/mapbox-navigation-ios#2202]
pod 'MapboxNavigation', '~> 0.36.0'

Installing Mapbox-iOS-SDK (5.2.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/j2/5crw33913rd_gb9n8hfpyn4r0000gn/T/d20190806-4045-cg0p22/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.2.0-dynamic.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4  126M    4 6331k    0     0  21069      0  1:44:39  0:05:07  1:39:32     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by SaraQiam** [comment]
Getting the same issue

**Comment by SaraQiam** [comment]
<img width="569" alt="Screen Shot 2019-08-01 at 11 17 33 PM" src="https://user-images.githubusercontent.com/14029281/62520721-015f6900-b7e3-11e9-88fb-1709fad21089.png">

**Comment by frederoni** [comment]
Looks like the url or SSL certs was temporarily unavailable. Do you still see this error if you update or install again? If so, what version of CocoaPods are you using?

**Comment by 1ec5** [comment]
Please open a new issue if you upgrade to the latest CocoaPods version and continue to experience this issue.

**Comment by chandresh777** [comment]
Installing Mapbox-iOS-SDK 6.2.1 (was 5.9.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/m0/tdfxb38s0lbg8rrb57381v440000gp/T/d20201015-12862-aj7q6y/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.2.1/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0.rc.1 cocoapods-downloader/1.4.0'

**Comment by DhirenBharadava143** [comment]
also, I m having the same issue

Analyzing dependencies
Downloading dependencies
Installing Mapbox-iOS-SDK (6.3.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/ff/13k7y0vn5f98gmr0gkvg1tcw0000gn/T/d20210122-7292-lnq0va/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized

**Comment by chandresh777** [comment]
Hi Dhiren

i have solved this problem you need add secrete key in your mac user
location folder.
after that you need to reinstall mac SDK


Thanks & Regards
Chandresh patel

**Comment by shamdass** [comment]
=> I guess, You are misplacing your .netrc.
=> The .netrc file should be in your home directory (~ on the command line, or use Go ‣ Home in Finder).

In terminal type: cd ~
touch .netrc
open .netrc
paste below to .netrc with SecretKey
machine api.mapbox.com
login mapbox
password
Enjoy: pod install will work without error

**Comment by abraamgtr** [comment]
You can fix it with adding this lines to ~/.netrc

machine api.mapbox.com
login mapbox
password <INSERT SECRET API TOKEN>
