### ISSUE TITLE
Premature maneuver completion announcements

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#222]
Sometimes, maneuver completion announcements can happen prematurely. 

An example of a driver that's told to make a left turn:

> He arrives at the light and stops at the intersection. While he's stationary and waiting for the light to turn, the SDK considers the maneuver complete (presumably because the GPS location moved around slightly) and gives him the next instruction as if he's continued driving. Despite the announcement, the confused user is still waiting for the light to turn green.

iOS version of https://github.com/mapbox/mapbox-navigation-android/issues/35

**Comment by 1ec5** [comment]
Currently we proactively advance to the next step (mark a turn complete) or reroute the user based on whether their course matches the expected post-maneuver course. What if we wait to give the post-maneuver announcement until that happens?

**Comment by bsudekum** [comment]
I think this should be easy to reproduce via simulating a route. @ericrwolfe do you have any routes we can investigate?

**Comment by ericrwolfe** [comment]
I don't, and from my own experience these types of things are pretty random based on GPS noise.

On my recent test drive I saw Google Maps exhibit this issue ([left turn here](http://map.project-osrm.org/?z=17&center=40.586301%2C-122.351893&loc=40.586553%2C-122.353379&loc=40.585115%2C-122.347527&hl=en&alt=0)) but the Mapbox SDK seemed fine.

**Comment by ericrwolfe** [comment]
From test drives, this problem isn't as much of an issue with typical left/right turns, but rather maneuvers with only slight changes in bearing from the user's current course, such as continue straight, merge, and exit maneuvers.

In particular, alerts while taking exit ramps are especially confusing since the announcement will often be made before the ramp while there are multiple other ramp options available.

We consider whether a maneuver has been completed by looking at whether a user has entered a certain radius around the maneuver, as well as checking that user's current course matches the final maneuver bearing.

Instead of checking whether a user has entered a certain maneuver radius, we should consider instead checking for entry + exit of a certain maneuver radius.

cc @bsudekum

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/378
