### ISSUE TITLE
Progress of Current user location can't check in Navigation

### ISSUE THREAD

**Issue by naeemAkee** [mapbox/mapbox-navigation-ios#2222]
Hello Sir, 

I'm using Mapbox, and want to get the **progress** of the user.

Like when user click on **cross(x) button**, I want to check its **position** at that point and save it to the data base, So that when next time he starts, he start's from that place, 

and get the information when user reaches the destination point.

**Info like Latitude Longitude, Name of place etc.**

Please help me it that, 

Thank you in advance.

**Comment by saddahussain** [comment]
Try this.

```
override public func viewDidLoad() {
    super.viewDidLoad()
    NotificationCenter.default.addObserver(self, selector: #selector(progressDidChange(notification:)), name: .routeControllerProgressDidChange, object: nil)
}

@objc func progressDidChange(notification: NSNotification) {
    let routeProgress = notification.userInfo![RouteControllerNotificationUserInfoKey.routeProgressKey] as! RouteProgress
    let location = notification.userInfo![RouteControllerNotificationUserInfoKey.locationKey] as! CLLocation
}
```

**Comment by naeemAkee** [comment]
It's working. Thank you
