### ISSUE TITLE
Switch to night style when Dark Mode is enabled

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2223]
When Dark Mode is enabled in iOS 13 and above, NavigationViewController should default to the night style regardless of the time of day.

[This guide to Dark Mode](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface) recommends using semantic colors and custom color assets, which long-term would be a superior solution to the SDK’s Style system, at least as far as colors are concerned. [There is more granular control](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface/choosing_a_specific_interface_style_for_your_ios_app) over the mode by setting [`UIView.overrideUserInterfaceStyle`](https://developer.apple.com/documentation/uikit/uiview/3238086-overrideuserinterfacestyle). These APIs would be more reliable than Style, but they require iOS 13 or above.

#539 would similarly switch styles when Smart Invert Colors is enabled.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
User interface style is a [trait](https://developer.apple.com/documentation/uikit/uitraitcollection/1651063-userinterfacestyle) that we could observe changes to.

**Comment by zappycode** [comment]
Hey I'd like to do this as part of Hacktober. Do I need to be assigned?

**Comment by MaximAlien** [comment]
To better align between iOS and CarPlay we should also consider adding switch that allows users to decide whether they want to change UI appearance whenever it changes in settings.
