### ISSUE TITLE
Missing MapBox Access Token

### ISSUE THREAD

**Issue by coder4567** [mapbox/mapbox-navigation-ios#2225]
Hy I'm trying the Examples project and I'm getting the following: 

error: Missing Mapbox access token
error: Get an access token from <https://www.mapbox.com/studio/account/tokens/>, then create a new file at /Users/lion/Downloads/ios-sdk-examples-master-2/mapbox_access_token that contains the access token.

Although I have added the token to info.plist under MGLMapboxAccessToken. And I have created the file: mapbox_access_token and included the Access Token in it. 

Would you kindly advise

**Comment by gfoldv** [comment]
If you are providing your access token in the Info.plist, then you can delete the "Apply Mapbox Access Token" build phase.

**Comment by coder4567** [comment]
Thank you I have removed it, 

I'm getting now the following:

Showing Recent Messages
:-1: dyld: Library not loaded: @rpath/libswiftCore.dylib

:-1:   Referenced from: /Users/lion/Downloads/ios-sdk-examples-master-2/Pods/SwiftLint/swiftlint

:-1:   Reason: image not found

:-1: /Users/lion/Library/Developer/Xcode/DerivedData/Examples-faagjnjnpdysahfyhgxtwlrvncgx/Build/Intermediates.noindex/Examples.build/Debug-iphonesimulator/Examples.build/Script-07CF859D20F41654007B26B6.sh: line 2:  1909 Abort trap: 6           "${PODS_ROOT}/SwiftLint/swiftlint"

**Comment by gfoldv** [comment]
It makes it a bit suspicious that you have the mapbox-navigation-ios git repo cloned to the ios-sdk-examples directory. Also your original error message is triggered from the ios-sdk-examples code. Are you sure you do not have a mess up over there?

**Comment by coder4567** [comment]
It finally worked, thank you for your assistance.
