### ISSUE TITLE
didUpdateProgress代理方法不执行

### ISSUE THREAD

**Issue by 183959633** [mapbox/mapbox-navigation-ios#2241]
我的代码是这样，但是没有执行didUpdateProgress代理方法，我想在导航的同时得到用户位置信息，可以给我一些帮助吗，Thinks！

<img width="821" alt="屏幕快照 2019-09-23 下午2 53 53" src="https://user-images.githubusercontent.com/29021369/65406393-ffdd1500-de11-11e9-8080-6e6733b59486.png">

**Comment by andrlee** [comment]
@troyyip can you help with this ticket?
