### ISSUE TITLE
How to perform action when end Navigation is pressed

### ISSUE THREAD

**Issue by mogsten** [mapbox/mapbox-navigation-ios#2244]
Is there a way to perform an action when End Navigation is Pressed on the End of Route View Controller?

Is there some function in the library that allows this?

**Mapbox Navigation SDK version:**
0.34.0

**Comment by JThramer** [comment]
👋 @mogsten 
Check out `NavigationViewControllerDelegate.navigationViewControllerDidDismiss(_ navigationViewController: NavigationViewController, byCanceling canceled: Bool)`, documented [here.](https://docs.mapbox.com/ios/api/navigation/0.37.0/Protocols/NavigationViewControllerDelegate.html#/c:@M@MapboxNavigation@objc(pl)MBNavigationViewControllerDelegate(im)navigationViewControllerDidDismiss:byCanceling:)

This delegate method will fire when the user either cancels a trip or completes the EORVC steps, which you can determine by looking at the `canceled: Bool` argument that is passed in.

Hope this helps! Please feel free to reopen this ticket if you have further questions.
