### ISSUE TITLE
Carthage Update fails

### ISSUE THREAD

**Issue by tezrosolutions** [mapbox/mapbox-navigation-ios#225]
Here is what is happening for me, when I am running carthage update to install example project: 

carthage update --platform ios
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Fetching Pulley
*** Fetching MapboxDirections.swift
*** Fetching SDWebImage
*** Fetching osrm-text-instructions.swift
*** Fetching Polyline
*** Checking out aws-sdk-ios at "1a8432b03c22326fb7ed86fac978212106e2d465"
*** Checking out Polyline at "v4.1.1"
*** Checking out MapboxDirections.swift at "v0.9.0"
*** Checking out osrm-text-instructions.swift at "v0.1.2"
*** Checking out Pulley at "1.4"
*** Checking out SDWebImage at "4.0.0"
*** xcodebuild output can be found in /var/folders/yj/j3z3mnnj387_x1kfk3kxygyw0000gn/T/carthage-xcodebuild.AtyGNm.log
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSPolly" in AWSiOSSDKv2.xcodeproj
*** Building scheme "Polyline" in Polyline.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/muhammad/Desktop/projects/Spotella/mapbox-navigation-ios/Carthage/Checkouts/Polyline/Polyline.xcodeproj -scheme Polyline -configuration Release -derivedDataPath /Users/muhammad/Library/Caches/org.carthage.CarthageKit/DerivedData/Polyline/v4.1.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yj/j3z3mnnj387_x1kfk3kxygyw0000gn/T/carthage-xcodebuild.AtyGNm.log

My MacOSX and XCode version is attached:
![2017-05-13_14-59-13](https://cloud.githubusercontent.com/assets/4765806/26024574/6cc43e32-37ed-11e7-896d-d0fb2d2036fc.png)
![2017-05-13_14-59-22](https://cloud.githubusercontent.com/assets/4765806/26024586/b04ee2e2-37ed-11e7-96fb-d7a2ad785b40.png)

**Comment by 1ec5** [comment]
> Please check the xcodebuild log for more details: /var/folders/yj/j3z3mnnj387_x1kfk3kxygyw0000gn/T/carthage-xcodebuild.AtyGNm.log

Can you provide the contents of this file (preferably in a gist so that it doesn’t clutter up this issue)? Thank you!

**Comment by tezrosolutions** [comment]
@1ec5 here you go: https://gist.github.com/tezrosolutions/f24a8ea66fa666f50fd3a48c2f778242

**Comment by frederoni** [comment]
What version of Carthage are you using and what does your Cartfile look like?
Have you tried purging Carthage’s cache? `rm -rf ~/Library/Caches/org.carthage.CarthageKit`
What does `xcode-select -p` output?

**Comment by tezrosolutions** [comment]
@frederoni Carthage version is 0.22.0 and Cartfile is below:
```
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 3.5
github "mapbox/MapboxDirections.swift" ~> 0.9.0
github "52inc/Pulley" ~> 1.3.1
github "rs/SDWebImage" ~> 4.0
github "Project-OSRM/osrm-text-instructions.swift" ~> 0.1.2
github "frederoni/aws-sdk-ios" "1a8432b03c22326fb7ed86fac978212106e2d465"
```


 xcode-select -p output is below:
/Applications/Xcode.app/Contents/Developer

Even after clearing cache same error is being produced.

**Comment by 1ec5** [comment]
From the errors in the attached log, it looks like Xcode is compiling Polyline as Swift 2.3. I’m not sure how that’s even possible in Xcode 8.3, which dropped support for Swift 2.3.

**Comment by tezrosolutions** [comment]
I got an older version of Xcode that was creating this mess. Uninstalling it did the job. Thanks for your help.
