### ISSUE TITLE
Mapbox navigation rating issue

### ISSUE THREAD

**Issue by AnamikaDeb** [mapbox/mapbox-navigation-ios#2250]
![110790](https://user-images.githubusercontent.com/4938979/66102146-1c780a80-e5d3-11e9-9402-db290ee4f3ef.png)

Is it mapbox default feature to give a option of rating after end of a trip navigation?
If yes, Should I stop this?

**Comment by 1ec5** [comment]
To disable the end-of-route feedback UI, set [`NavigationViewController.showsEndOfRouteFeedback`](https://docs.mapbox.com/ios/api/navigation/0.38.0/Classes/NavigationViewController.html#/c:@M@MapboxNavigation@objc%28cs%29MBNavigationViewController%28py%29showsEndOfRouteFeedback) to `true`.

The screenshot shows the UI in a seemingly broken state. Are you doing any customization that could be causing the UI to have the wrong shape?

**Comment by S2Ler** [comment]
You can disable end of route feedback UI stated above.

Looks like you are placing this "SOS" button in a way which breaks the UI. Consider debugging the problem using [Xcode View Hierarch Viewers](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html).

Closing as stale.
