### ISSUE TITLE
NavigationOptions is buried in documentation.

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#2253]
`NavigationOptions` is [documented](https://docs.mapbox.com/ios/api/navigation/0.38.0/Classes/NavigationOptions.html) in the SDK docs, but under ["Other Classes"](https://docs.mapbox.com/ios/api/navigation/0.38.0/Other%20Classes.html), which is quite misleading, as it is an important class to know about for most client use-cases.

Should we move it to the ["Turn-by-Turn UI"](https://docs.mapbox.com/ios/api/navigation/0.38.0/Turn-by-turn%20UI.html) section instead?

Or perhaps we should have a "Customizing your experience" section that focuses on the Options classes?

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
NavigationRouteOptions and NavigationMatchOptions are even more important and also buried in that section. We should move all three types to a Configuration section toward the top, right below the Guides section.

**Comment by JThramer** [comment]
Closing as stale.
