### ISSUE TITLE
 Unable to toggle between Default and Satellite map views while navigating

### ISSUE THREAD

**Issue by jilujoy** [mapbox/mapbox-navigation-ios#2254]
We have a requirement to switch between Satellite view  and default map view while the user is in map navigation screen.

Is  this feature available in the current MapboxCoreNavigation SDK? 

MapboxCoreNavigation  SDK version currently in use is 0.27.0

**Comment by 1ec5** [comment]
MapboxCoreNavigation specializes in non-UI functionality like location tracking. MapboxNavigation is what provides a map view.

In general, yes, it is possible for your application to switch the map view’s style during navigation. You’d set the map view’s `styleURL` property or subclass `Style`. However, switching the style requires restoring overlays such as the route line. If you plan to show satellite imagery at certain zoom levels and not at others, you may find it more convenient and aesthetically pleasing to create a hybrid style containing a satellite layer that is enabled at those zoom levels.
