### ISSUE TITLE
Navigation instructions not updated after the first turn.

### ISSUE THREAD

**Issue by IAmMisterFrank** [mapbox/mapbox-navigation-ios#2255]
Hi all, 

First things first:

- The navigation SDK version: **Mapbox Navigation SDK version:** 0.38.0
- Installed through CocoaPods
- The iOS version (13.1.2), iPhone model (Xs Max 64GB MT592LL/A), and Xcode version (11.1 (11A1027)), as applicable

I'm experiencing issues with route simulation. After the simulation passes a step, the directions don't update even though the simulation continues.  This happens with all routes that we have set up.

I tried hardcoding waypoints into the code. This results in a working route. I have routes set up on the database. I wanted to verify these routes by verifying the JSON's of both versions. I have found out that the JSON's are pretty similar so I do not expect the problem to be buried within there.

I have tried setting several breakpoints in the code to isolate where the code fails. I have come to the conclusion that route steps aren't being updated because the code returns as a result of a guard statement. Our function: updateStep() is called from out a NavigationViewController. It calls to the function which is defined in a separate file in which the guard statement returns.

```swift
func updateStep(routeProgress: RouteProgress, altStep: RouteStep? = nil) {
        let routeStep = altStep ?? routeProgress.currentLegProgress.currentStep
        print ("RouteProgressService - altStep: \(altStep)")
        let steps = routeProgress.currentLeg.steps
        guard let newStepIndex = steps.index(of: routeStep), newStepIndex > currentStepIndex  else {
            print("return")
            return
        }
```

Colleague recommended me to create an issue for this since it sounds like a Mapbox-related issue.

**Comment by 1ec5** [comment]
I’m afraid we can’t diagnose this issue further without knowing the context in which `updateStep(routeProgress:altStep:)` is being called. Is it called in response to a `routeControllerProgressDidChange` notification or `NavigationServiceDelegate.navigationService(_:didUpdate:with:rawLocation:)`, for instance?

If the guard statement is returning, that just means that either the `altStep` isn’t part of the current leg or the new step is earlier in a step array than the current step is in a step array. But for instance, if you have a route with two legs, `newStepIndex` will be 0 the moment the user arrives at the first destination and proceed to depart on the second leg.
