### ISSUE TITLE
Downloaded Tiles not shown for Offline Routing

### ISSUE THREAD

**Issue by annathomasQB** [mapbox/mapbox-navigation-ios#2256]
Hi,

I've checked the [Docs](https://docs.mapbox.com/ios/navigation/overview/offline-routing/) and [example](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Example/OfflineViewController.swift) of offline routing. 

I'm setting the configureRouter method inside completion of unpackTilePack method. But when i check with airplane mode, no tiles are displayed. 

Pasting bits (not complete) of my code here : 

```
Directions.shared.fetchAvailableOfflineVersions { (versions, error) in 
_ = Directions.shared.downloadTiles(in: cordinateBounds, version: version, completionHandler: { (url, response, error) in
NavigationDirections.unpackTilePack(at: url, outputDirectoryURL: outputDirectoryURL!, progressHandler: { (totalBytes, bytesRemaining) in
                    // progress handler
                }, completionHandler: { (result, error) in
                let navigationDirections = NavigationDirections(accessToken: NavigationDirections.shared.accessToken)
                 if let tilesURL = tilesURL {
                   navigationDirections.configureRouter(tilesURL: tilesURL) { (tiles) in
            }
        }
                })

```

I'm guessing the issue is with the navigationDirections object not getting assigned back to navigation controller.. but I'm at lost as to how to do that ? 

Coudn't find the configureRouter code inside the example, and the documentation also didn't have the correct implementation. Please do help out.

**Comment by annathomasQB** [comment]
Pod version
 pod 'Mapbox-iOS-SDK', '4.7'
  pod 'MapboxNavigation', '0.27.0'

**Comment by frederoni** [comment]
`Directions.shared.downloadTiles` downloads non-visual routing tiles.
Please check out this [Example](https://docs.mapbox.com/ios/maps/examples/offline-pack/) on how to download an offline pack with map tiles.

**Comment by annathomasQB** [comment]
Hi @frederoni  : 
Thanks for your input. 
So I should use this example along with `Directions.shared.downloadTiles` ?

**Comment by frederoni** [comment]
Exactly. `Directions.shared.downloadTiles` will download tiles necessary to calculate a route, while the other example shows how to download tiles for rendering a map offline.

**Comment by annathomasQB** [comment]
Thanks a lot @frederoni.

Its working now :)
