### ISSUE TITLE
[!] Error installing Mapbox-iOS-SDK

### ISSUE THREAD

**Issue by pjl1234567** [mapbox/mapbox-navigation-ios#2257]
pod repo update && pod install
Updating spec repo `master`
  $ /usr/bin/git -C /Users/shanren/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 590, done.        
  remote: Counting objects: 100% (590/590), done.        
  remote: Compressing objects: 100% (338/338), done.        
  remote: Total 820 (delta 364), reused 242 (delta 242), pack-reused 230        
  Receiving objects: 100% (820/820), 129.73 KiB | 17.00 KiB/s, done.
  Resolving deltas: 100% (443/443), completed with 141 local objects.
  From https://github.com/CocoaPods/Specs
     67095e03c8d..24fc230b380  master     -> origin/master
  $ /usr/bin/git -C /Users/shanren/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/shanren/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 24fc230b380 [Add] TiendeoCore 1.1.7-APPS-755-beta1

CocoaPods 1.8.3 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.8.3

Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.7.0)
Using MJExtension (3.0.17)
Installing Mapbox-iOS-SDK (5.4.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/fh/dxvsn3455td0np0hts6873f00000gp/T/d20191014-12209-1uphmmp/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.4.0-dynamic.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 14  129M   14 18.4M    0     0  16362      0  2:18:23  0:19:40  1:58:43     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by JyyJDast1** [comment]
same error

**Comment by 1ec5** [comment]
Unfortunately, it looks like you’re experiencing a network connectivity error.

**Comment by subhani-ali** [comment]
i m facing issue :
- [!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/45/5jgvsfg94l9flyj1ct03dn6w0000gn/T/d20210712-69158-vco2ko/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by abraamgtr** [comment]
You can fix it with adding this lines to ~/.netrc

machine api.mapbox.com
login mapbox
password <INSERT SECRET API TOKEN>
