### ISSUE TITLE
carthage  mapbox-navigation-ios   failure

### ISSUE THREAD

**Issue by pjl1234567** [mapbox/mapbox-navigation-ios#2258]
carthage update --platform iOS
*** Cloning mapbox-navigation-ios
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/mapbox/mapbox-navigation-ios.git /Users/shanren/Library/Caches/org.carthage.CarthageKit/dependencies/mapbox-navigation-ios) failed with exit code 128:
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by 1ec5** [comment]
Unfortunately, it looks like you’re experiencing a network connectivity error, similar to the one in #2257.
