### ISSUE TITLE
Ensure compatibility with CPTemplateApplicationSceneDelegate

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2260]
In iOS 13, [CPApplicationDelegate](https://developer.apple.com/documentation/carplay/cpapplicationdelegate) has been deprecated in favor of [CPTemplateApplicationSceneDelegate](https://developer.apple.com/documentation/carplay/cptemplateapplicationscenedelegate). I _think_ the developer can safely call `CarPlayManager.application(_:didConnectCarInterfaceController:to:)` and `application(_:didDisconnectCarInterfaceController:from:)` from within `CPTemplateApplicationSceneDelegate.templateApplicationScene(_:didConnect:to:)` and `templateApplicationScene(_:didDisconnect:from:)`, respectively, but we should add tests to be sure and also update the documentation. (Apple hasn’t even gotten around to updating [their CarPlay getting started documentation](https://developer.apple.com/documentation/carplay/adding_carplay_support_to_your_navigation_app) yet.)

/cc @mapbox/navigation-ios @mapbox/docs

**Comment by 1ec5** [comment]
When building an application against the iOS 13 SDK, the following warning appears due to CarPlayManager conforming to CPApplicationDelegate:

```
/path/to/Carthage/Build/iOS/MapboxNavigation.framework/Headers/MapboxNavigation-Swift.h:383:64: 'CPApplicationDelegate' is deprecated: first deprecated in iOS 13.0
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CarPlay.framework/Headers/CPInterfaceController.h:129:11: 'CPApplicationDelegate' has been explicitly marked deprecated here
```

**Comment by avi-c** [comment]
I have most of this coded up in a branch. `ac-CarPlayUpdates` that deals with updating to the newest CarPlay API. It needs cleanup with an eye to public release, but I think all the engineering work is done there.

**Comment by avi-c** [comment]
The branch I have includes a couple of unrelated changes, so I am prepping a branch that is only focused on this change and also adds support for the new API to the Example app.
