### ISSUE TITLE
Problem using library with Xcode11

### ISSUE THREAD

**Issue by tdermaris** [mapbox/mapbox-navigation-ios#2263]
I am trying to install library in Xcode11.1 and I get the following errors:
Multiple commands produce '/Users/tom/Library/Developer/Xcode/DerivedData/MyProject-../Build/Products/Staging-iphoneos/MyProject-app/Assets.car'
1. Target 'MyProject' has compile command with input '/Users/tom/Desktop/MyProject/MyProject/Assets.xcassets'
2. That command depends on command in Target 'MyProject' (project: 'MyProject'): script phase "[CP] Copy Pods Resources"

I have no idea how to solve this. Can you please give me any tips? 
Thanks in advance

**Comment by Jackyaung** [comment]
I got the same problem, it took me two days already, it looks like there is something to do with use_framework, I have tried to add use_framework in the cocoapod, the problem solved but my other frameworks are messed up. Anyone knows how to use it without use_framework ?

**Comment by 1ec5** [comment]
Assuming this is a CocoaPods `use_frameworks!`-related issue, see #2309 for further details.
