### ISSUE TITLE
'MapboxDirections/MapboxDirections.h' file not found when building project through react-native or XCode

### ISSUE THREAD

**Issue by Davidvision** [mapbox/mapbox-navigation-ios#2265]
Hi everybody,

I'm currently trying to create a react-native wrapper around MapBoxDirections.

When trying to build the projet with "react-native run-ios --simulator "iPhone 11" command, i get the following error:
![Capture d’écran 2019-11-06 à 15 08 44](https://user-images.githubusercontent.com/45124558/68305120-627b2f00-00a7-11ea-8470-6fda749622b8.png)

I get the same error when trying to build within Xcode

my current podfile looks like this:
![Capture d’écran 2019-11-06 à 15 16 57](https://user-images.githubusercontent.com/45124558/68305745-7ffcc880-00a8-11ea-9d71-f903bca1a508.png)

and i tried with/without commenting use_frameworks! or use_modular_headers!

I also tried initiating a full iOs project through XCode, then I created a podfile (pod init) and run pod install. It builds and works perfectly but I cannot figure out a way to wrap this project and get it to work with React Native...

Any idea on how to solve this ? Help would be really appreciated, 
Thanks a lot in advance

### Steps to reproduce
create react native project using react-native init "project name"
cd "project name"/ios
pod init
add   "pod 'MapboxNavigation', '~> 0.38'" to the Podfile
cd ..
react-native run-ios --simulator "iPhone 11"

### Configuration

**Mapbox SDK versions: pod 'MapboxNavigation', '~> 0.38.0' **
**macOS versions: iOS 10.15.1 **
**Device/simulator models: Iphone 11 iOs 13.2  **
**Xcode version: Version 11.0  **
**react-native : Version 0.61.4  **

**Comment by Davidvision** [comment]
Figured out I simply had missing dependencies!

**Comment by andfs** [comment]
@Davidvision  what dependencies did you miss?
