### ISSUE TITLE
Misleading guard statement in NavigationDirections.calculate(_:)

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#2273]
https://github.com/mapbox/mapbox-navigation-ios/blob/420b287b0f865e8df8e389921b54973a24524369/MapboxCoreNavigation/OfflineDirections.swift#L151-L157

Currently we're only returning the `OFFLINE_NO_RESULT` error if the directions client is improperly handled (`self` is `nil` when the asynchronous closure executes.)  We should have a separate error for that, and actually check the result to ensure no error was returned from nav native.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
The suggestion is to break up the `guard` statement so that it only checks whether `self` (NavigationDirections) is still around; a `let` further down can call `getRouteForDirectionsUri(_:)`.
