### ISSUE TITLE
Acquiring a coordinate at a distance ahead along the navigation route?

### ISSUE THREAD

**Issue by wegotthekeys** [mapbox/mapbox-navigation-ios#2286]
**Mapbox Navigation SDK version:** v0.38.0

I'm trying to see if it's possible to acquire a coordinate that is an arbitrary distance ahead along the route. I can't seem to figure out a way to do this. Is it possible?

**Comment by wegotthekeys** [comment]
Figured it out. Take your route object and access the `coordinates` property, then iterate through that list.

**Comment by 1ec5** [comment]
That approach may be unreliable in some cases because the coordinates aren’t guaranteed to be a consistent distance apart from each other. Instead, use [Turf](https://github.com/mapbox/turf-swift/)’s `LineString.trimmed(from:distance:)` and get the last coordinate out of the resulting LineString.

**Comment by wegotthekeys** [comment]
@1ec5 Thanks so much for that. Much easier solution :)
