### ISSUE TITLE
Abbreviating multiple lines

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#229]
![simulator screen shot may 16 2017 10 00 14 am](https://cloud.githubusercontent.com/assets/1058624/26118370/7e2a5a34-3a1e-11e7-9181-fc6d43aa6831.png)

This should probably read:

> Alves Drive

or 

> Alves
> Drive

/cc @frederoni @1ec5

**Comment by 1ec5** [comment]
There should be enough room to expand out “Drive”, unless the (hidden) shield view is taking up space still?

**Comment by frederoni** [comment]
Yep, we need to check the shield first and the bounds currently depend on what the text was previous to this update. We should get `maximumAvailableBounds` instead of `bounds` on the label. 
(I can pick up this ticket)
