### ISSUE TITLE
Minimize NSObject inheritance

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2294]
As a followup to #2230, we should minimize the number of classes that explicitly inherit from NSObject. NSObject inheritance hinders Codable adoption and potentially has other subtle side effects.

The following classes look like good candidates for becoming ordinary Swift classes, though we’ll need to make sure there isn’t any KVO lurking around. Not listed here are any classes that need to conform to NSObjectProtocol because of some Foundation protocol inheritance such as CLLocationManagerDelegate.

* [ ] RouteProgress, RouteLegProgress, and RouteStepProgress
   #2229 registered key-value observers on these classes. Clients can set indices directly and a third object, RouteController, needs to update in response to the change. Though Foundation’s Progress class also inherits from NSObject, it solves this problem by allowing an object to register blocks to handle specific changes. It’s basically a hard-coded subset of KVO, more structured than the delegate pattern. Removing NSObject usage here will unblock codability: #1940.

* [ ] NavigationSettings
   This class also uses KVO, but I think only it registers on its own key paths, for the purpose of sending out notifications. Given the manageable number of properties and outstanding reflection mysteries like #2262, we should replace this mechanism with a series of `didSet`s that call a common method.

* [ ] MapboxNavigationService
* [ ] NavigationOptions
* [x] NavigationEventsManager: #2297
* [ ] EndOfRouteFeedback
* [ ] FeedbackItem
* [ ] CarPlaySearchManager
* [ ] StyleManager
* [ ] DataCache

/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
I think there are some problems with following classes.
`MapboxNavigationService` conforms to `CLLocationManagerDelegate`. So it is required to implement `NSObjectProtocol`:
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxCoreNavigation/NavigationService.swift#L370

I couldn't find `CarPlaySearchManager`. There are `CarPlaySearchController` and `CarPlayManager` classes, inheriting `NSObject` but both require such inheritance due to protocols implementation:
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxNavigation/CarPlaySearchController%2B%20CPSearchTemplateDelegate.swift#L8
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxNavigation/CarPlayManager.swift#L244

**Comment by Udumft** [comment]
If I understood the suggested change, `RouteProgress.legIndex` notifications should use something like this:

  ```
    dynamic public var legIndex: Int {
        didSet {
            // ...
            legIndexHandler?(oldValue, legIndex)
        }
    }

    public typealias LegIndexSubscriptionAction = (_ oldValue: Int, _ newValue: Int) -> ()
    public var legIndexHandler: LegIndexSubscriptionAction?
```

But what if there will be more than 1 observer needed? What if user wants to observe any other property?
Maybe I should spend a bit more time on that and implement something that allow multiple subscribers and can be expanded to other properties?

**Comment by 1ec5** [comment]
> `MapboxNavigationService` conforms to `CLLocationManagerDelegate`. So it is required to implement `NSObjectProtocol`

Ah, good point. That’s a legitimate reason to inherit from NSObject.

> I couldn't find `CarPlaySearchManager`.

That was a typo; I meant CarPlaySearchController. But you’re right, CPSearchTemplateDelegate forces NSObjectProtocol conformance here too.

> If I understood the suggested change, `RouteProgress.legIndex` notifications should use something like this:
> …
> But what if there will be more than 1 observer needed? What if user wants to observe any other property?

Do we want developers to be able to observe RouteProgress model changes directly, or should they observe `routeControllerProgressDidChange` notifications instead?

**Comment by Udumft** [comment]
Disabling KVO for `NotificationSettings` will also update our own usage of subscriptions to settings updates. For example `RouteVoiceController` and `MapboxVoiceController` will be updated too:
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxNavigation/RouteVoiceController.swift#L122-L126
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxNavigation/MapboxVoiceController.swift#L52-L65

This change will conflict with #2268 PR.
