### ISSUE TITLE
NavigationMapView how to disable start animation - zoom in and move to your current location

### ISSUE THREAD

**Issue by pingus-nikalex** [mapbox/mapbox-navigation-ios#2316]
how to disable start animation - zoom in and move to your current location and set camera?

I added NavigationMapView to custom view, and then need to set camera position and zoom level from other MGLMapView. And I can't do this. 

I will try to do something like this
navMapView?.camera((navigateToPin?.mapView!.camera)!, fitting: (navigateToPin?.mapView!.visibleCoordinateBounds)!, edgePadding: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0))

or trying this

navMapView?.camera = navigateToPin?.mapView!.camera

All this don't work. After added NavigationMapView I see zoomin and move to your current location animation.

**Comment by lfongaroScp** [comment]
No news? Maybe this is fixed in the new release?
