### ISSUE TITLE
IPA failures when trying to upload Ad-hoc

### ISSUE THREAD

**Issue by runwalle** [mapbox/mapbox-navigation-ios#2318]
**Mapbox Navigation SDK version:**
Cloned Github project.
After successful Archive build  of "Example" and tried to upload it for Ad-hoc testing on my iphone.
But I faced error message of "IPA failure" during very beginning of Ad-hoc process.
Anyone tried Ad-hoc?
By th way, iPhone simulator worked fine.

Xcode: 11.3
Swift: 5.0

Inside Cartfile:
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 5.6
binary "https://www.mapbox.com/ios-sdk/MapboxNavigationNative.json" ~> 6.2.1
github "mapbox/mapbox-directions-swift" == 1.0.0-alpha.1
github "mapbox/turf-swift" ~> 0.3
github "mapbox/mapbox-events-ios" ~> 0.10
github "ceeK/Solar" ~> 2.1.0
github "mapbox/mapbox-speech-swift" ~> 0.3.0

**Comment by 1ec5** [comment]
Was there any additional information besides the “IPA failure” message, such as in a log somewhere?
