### ISSUE TITLE
Truck Routing

### ISSUE THREAD

**Issue by cloudtenlabs** [mapbox/mapbox-navigation-ios#2320]
I heard Mapbox added a truck routing feature as beta version in 2018.
When will it be available to use in my iOS App?
https://blog.mapbox.com/truck-routing-is-live-84435da18e37

**Comment by 1ec5** [comment]
Hi @cloudtenlabs, please [contact Mapbox technical support](https://support.mapbox.com/) for details about services that are in private beta testing. Thanks!
