### ISSUE TITLE
Mapbox Navigation is incompatible with Mapbox-iOS-SDK 5.6.0

### ISSUE THREAD

**Issue by wojciech-kulik** [mapbox/mapbox-navigation-ios#2326]
We need to migrate to `Mapbox-iOS-SDK 5.6.0`, but when resolving dependencies via CocoaPods, we get the following error:

```
[!] CocoaPods could not find compatible versions for pod "Mapbox-iOS-SDK":
  In Podfile:
    Mapbox-iOS-SDK (~> 5.6.0)

    MapboxNavigation (~> 0.38.3) was resolved to 0.38.3, which depends on
      Mapbox-iOS-SDK (= 5.5.0)

Specs satisfying the `Mapbox-iOS-SDK (~> 5.6.0), Mapbox-iOS-SDK (= 5.5.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by 1ec5** [comment]
Unfortunately, v5.6.0 contains backwards-incompatible changes that prevent it from working with v0.38._x_: #2299. If you need to use v5.6.0 rather than v5.5.0, you’ll need to upgrade to navigation SDK v1.0.0-alpha.1. We’re expecting a beta release shortly.

**Comment by wojciech-kulik** [comment]
Thank you for a quick response!

**Comment by 1ec5** [comment]
v0.40.0 and above depends on v5.6.0 and above.
