### ISSUE TITLE
MBNavigationMapView not found error

### ISSUE THREAD

**Issue by tezrosolutions** [mapbox/mapbox-navigation-ios#233]
Hi,

The problem is that MBNavigationMapView class is not recognized.

Attached are screenshots of my storyboard, embedded binaries and linked framework sections and the ViewController file.

Here is my Cartfile:

github "mapbox/mapbox-navigation-ios" ~> 0.3.0
github "mapbox/MapboxDirections.swift" ~> 0.9.0

Any advice

![frameworks](https://cloud.githubusercontent.com/assets/4765806/26260950/b3f19aac-3ce8-11e7-8693-b038bf2f6f4b.png)
![viewcontroller](https://cloud.githubusercontent.com/assets/4765806/26260951/b403d99c-3ce8-11e7-99d1-9af260e4625a.png)
![storyboard](https://cloud.githubusercontent.com/assets/4765806/26260953/b4130bce-3ce8-11e7-9cd3-0fb974925f1e.png)

**Comment by frederoni** [comment]
Interface builder will use the Objective-C name of the class but your Swift class wants to use the Swift name. Try to drop the prefix in your Swift class and use `NavigationMapView` for your outlet but keep `MBNavigationMapView` in IB.

FWIW, it doesn't look like you need the navigation map view in that view controller and so you could also change the type to `MGLMapView`. MGLMapView is not refined for Swift so it will be the same in IB and in code.
