### ISSUE TITLE
Custom cursor GPS in navigation

### ISSUE THREAD

**Issue by VincenzoMan** [mapbox/mapbox-navigation-ios#2331]
Hi,
is it possible to change the navigation cursor (the black arrow on a circular white background)?
Thanks
**Mapbox Navigation SDK version: 0.38.3**

**Comment by SebastianOsinski** [comment]
@VincenzoMan You can both customize the cursor or completely replace it with your custom view.
To do the latter, just set `userCourseView` property of `NavigationMapView` to your view. This can be any `UIView` subclass. You can also conform to optional protocol `UserCourseView` to get some more information in your view, e.g. course and heading. 

If you just want to customize colors of default course view, initialize `userCourseView` to `UserPuckCourseView` with non-zero frame. Then you can set `puckColor`, `fillColor` and `shadowColor` on it.
