### ISSUE TITLE
Resume Button Hide/Position

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-navigation-ios#2339]
Hello, is it possible to hide or change position of the Resume button during navigation?

I tried using the accessible `ResumeButton.appearance().isHidden = true` but doesn't seems to work. Thank you in advance!

**Comment by richterCLX** [comment]
i haven't fully tested this yet, but this seems to work

use the [NavigationMapViewCourseTrackingDelegate](https://docs.mapbox.com/ios/api/navigation/0.38.3/Protocols/NavigationMapViewCourseTrackingDelegate.html)


```
// delegate after creating mapviewcontroller
navigationViewController.mapView.courseTrackingDelegate = self;

// hide and show your button in these functions
 func navigationMapViewDidStartTrackingCourse(_ mapView: NavigationMapView)
 func navigationMapViewDidStopTrackingCourse(_ mapView: NavigationMapView)

//in your button action you call
navigationViewController?.mapView?.recenterMap();
```

**Comment by MarcoCarnevali** [comment]
Hello @richterCLX and thank you. Yes I'm able to re-center the map and use a custom button, but the Resume button will appear anyway

**Comment by MarcoCarnevali** [comment]
The only fix I just found is set its alpha to zero:
`ResumeButton.appearance().alpha = 0`
 instead of controlling it with `isHidden = true`

but probably is not the best solution

**Comment by richterCLX** [comment]
`navigationViewController.mapView.courseTrackingDelegate = self;`

with this call the resume button doesn't appear to me

**Comment by MarcoCarnevali** [comment]
you are right! That's awesome thank you very much! Sorry I was using another delegate so wasn't working. You saved my life! Would love be able to change its position but creating a custom button it's just fine. Thank you!

**Comment by engelzero** [comment]
@MarcoCarnevali @richterCLX can you guys possibly provide some of the source of how you got it working, trying to achieve the same but fairly new to swift. Appreciate the help! :)
