### ISSUE TITLE
Add button to provide feedback

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#234]
We should incorporate a button into the UI that allows the user to provide feedback about the route. The simplest implementation would open the [Directions Feedback](https://www.mapbox.com/directions-feedback/mapbox/) tool in the default Web browser.

The feedback tool’s URL looks like this:

https://www.mapbox.com/directions-feedback/mapbox/?profile=driving&route=-122.45082378387451,37.778991539440696;-122.43445944855921,37.776074412060694

The feedback tool itself has lots of room for improvement:

* It uses mapbox.js, so it can’t display the navigation style used by this SDK.
* It uses Directions API v4, so the `driving-traffic` profile is unsupported.
* It only displays the submit button in landscape orientation.

In due time, we’ll replace this tool with something better suited to an iOS application or even some sort of automated telemetry, but this is the most actionable approach at the moment.

/cc @bsudekum @frederoni @ericrwolfe @daniel-j-h

**Comment by daniel-j-h** [comment]
Sweet! @miccolis had some work on feedback planed for our upcoming Directions sprint. It could be possible that we're re-vamping directions-feedback completely when time permits. If we go the route to invest some time here we should huddle before and talk about what's needed for all our Directions clients.

**Comment by miccolis** [comment]
My understanding is that this ticket is stale & we're moving forward with a [different approach](https://github.com/mapbox/navigation/issues/15) that doesn't push folks to our web based feedback tool. 

Closing.

**Comment by ericrwolfe** [comment]
Basic feedback button added with https://github.com/mapbox/mapbox-navigation-ios/pull/304/commits/c48a740abd957cad5848be2daaf77b431da2580f
