### ISSUE TITLE
Rerouting does not work on final waypoint

### ISSUE THREAD

**Issue by twprzybysz** [mapbox/mapbox-navigation-ios#2346]
**Mapbox Navigation SDK version: 1.0.0-alpha.1** 
While testing tracking mode I've noticed that after reaching final waypoint rerouting is not occurring. 
I've checked the SDK and implemented delegate which should be responsible for handling this situation:
```
func navigationService(_ service: NavigationService, shouldPreventReroutesWhenArrivingAt waypoint: Waypoint) -> Bool {
    return false
}
```
Still it wasn't working.

I've found that there source of this problem might be in `userIsOnRoute` method:
```
public func userIsOnRoute(_ location: CLLocation, status: MBNavigationStatus?) -> Bool {
    
    guard let destination = routeProgress.currentLeg.destination else {
        preconditionFailure("Route legs used for navigation must have destinations")
    }
    
    // If the user has arrived, do not continue monitor reroutes, step progress, etc
    if routeProgress.currentLegProgress.userHasArrivedAtWaypoint &&
        (delegate?.router(self, shouldPreventReroutesWhenArrivingAt: destination) ??
            DefaultBehavior.shouldPreventReroutesWhenArrivingAtWaypoint) {
        return true
    }
    
    let status = status ?? navigator.getStatusForTimestamp(location.timestamp)
    let offRoute = status.routeState == .offRoute
    return !offRoute
}
```
When user is close to destination point `status.routeState` returns `.completed` with the implemented delegate.

Caller of userIsOnRoute to get the status argument uses also `getStatusForTimestamp` - it looks like `getStatusForTimestamp` method have some problems with determining correct routeState without taking into consideration delegate `shouldPreventReroutesWhenArrivingAt` value.

**Comment by benorgan** [comment]
We are also experiencing this issue. 

We are trying to get Mapbox to continue re-routing after the user has arrived at the destination. This is in case they miss the destination and continue driving, we want to re-route them back to the destination.

To reproduce arrive at the destination (arrival state is triggered) and then continue moving past the destination. We are expecting that with the following code it would continue to re-route after arrival:

```
func navigationService(_ service: NavigationService, shouldPreventReroutesWhenArrivingAt waypoint: Waypoint) -> Bool {
    return false
}
```

However, this seems to stop the puck being updated after arrival. 

We have got it kind of working by removing the conditionals which check `snapsUserLocationAnnotationToRoute` and `userHasArrivedAndShouldPreventRerouting` in `NavigationViewController` (https://github.com/mapbox/mapbox-navigation-ios/blob/6e311dd4b40c634d094721fa880b63f9ea2a6044/MapboxNavigation/NavigationViewController.swift#L494)

We have also changed the `offRoute` variable in `RouteController` (https://github.com/mapbox/mapbox-navigation-ios/blob/6e311dd4b40c634d094721fa880b63f9ea2a6044/MapboxCoreNavigation/RouteController.swift#L391) to be as follows:

```
let offRoute = status.routeState == .offRoute || status.routeState == .complete
```

However, this doesn't seem like the right way to fix it and I suspect will introduce other issues!

We also have a similar issue for Android here: https://github.com/mapbox/mapbox-navigation-android/issues/3087
