### ISSUE TITLE
pod error bug

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-navigation-ios#2349]
**Mapbox Navigation SDK version:**
0.39

I have two issues to report. First one is:

 CocoaPods could not find compatible versions for pod "Mapbox-iOS-SDK":
  In Podfile:
    Mapbox-iOS-SDK (= 5.7.0)

    MapboxNavigation (~> 0.39.0) was resolved to 0.39.0, which depends on
      Mapbox-iOS-SDK (= 5.5.1)

    MapboxPlugins (from `/Users/kacerac/Desktop/Patroler verzije/mapbox-plugins-ios-master`) was resolved to 0.0.1, which depends on
      MapboxPlugins/PluginKit (= 0.0.1) was resolved to 0.0.1, which depends on
        Mapbox-iOS-SDK (~> 5.7.0)

Can you make that navigation SDK depends always on newest version of mapbox iOS SDk?

And second one, is it possible to somehow use navigation SDK but not to exclude ios 9 users? Because now I must set to 10 deployment target...

<img width="682" alt="Screenshot 2020-03-10 at 11 37 48" src="https://user-images.githubusercontent.com/4254736/76304421-ab482c00-62c3-11ea-8bd1-28bf7da4702f.png">

**Comment by 1ec5** [comment]
It looks like you’ve installed [MapboxPlugins](https://github.com/mapbox/mapbox-plugins-ios/), which is incompatible with the latest versions of the Mapbox Maps SDK and Mapbox Navigation SDK.

/cc @chloekraw @knov

**Comment by nole87** [comment]
How can I get navigation v1.0.0-alpha.1 pod? I try but I get error ...

**Comment by 1ec5** [comment]
We aren’t pushing prereleases to CocoaPods trunk because prereleases aren’t necessarily appropriate for developers to receive by default. But you can follow [these instructions](https://github.com/mapbox/mapbox-navigation-ios#using-cocoapods) to download alpha 1 using CocoaPods.

**Comment by kishansbs** [comment]
same -- 
  pod 'MapboxNavigation', '~> 0.39.0' --

CocoaPods could not find compatible versions for pod "MapboxNavigation":
  In Podfile:
    MapboxNavigation (~> 0.39.0)

Specs satisfying the `MapboxNavigation (~> 0.39.0)` dependency were found, but they required a higher minimum deployment target.
