### ISSUE TITLE
Use with other Directions Api

### ISSUE THREAD

**Issue by desmeit** [mapbox/mapbox-navigation-ios#2354]
Is it possible to use this Mapbox Navigation SDK with another Directions API than Mapbox Directions? For example with Graphhopper?

**Comment by andfs** [comment]
@desmeit did you find out how to do that?

**Comment by joshuageronimo** [comment]
I'm also curious if this is possible. I was able to use Graphhopper API for version 0.38.0 -> but with the new update, the Route class got refactored. I'm no longer able to create a `Route` object. The `Route` decoder function fails.

**Comment by rdvelazquez** [comment]
The MapHopper package (https://github.com/Gadda27/maphopper) converts GraphHopper directions into a form consumable by the MapBox SDK but, as @joshuageronimo pointed out above, there is an issue with version 0.40.0 of the SDK when trying to use the MapHopper route response.

**Comment by rdvelazquez** [comment]
The issue with 0.40.0 SDK was addressed by overriding the mapHopper manual polyline5 -> polyline6 conversion.
