### ISSUE TITLE
Attribution and info button should be visible

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#236]
![image](https://cloud.githubusercontent.com/assets/1058624/26321353/56c7e0e4-3edb-11e7-8dc3-e07ea187c774.png)

![image](https://cloud.githubusercontent.com/assets/1058624/26321386/7905fd30-3edb-11e7-9b94-2db86a6a37be.png)

/cc @frederoni

**Comment by 1ec5** [comment]
This should be unblocked as soon as we pull in mapbox/mapbox-gl-native#7716.
