### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MapboxNavigation": In Podfile: MapboxNavigation (~> 0.39.0)

### ISSUE THREAD

**Issue by kishansbs** [mapbox/mapbox-navigation-ios#2372]
CocoaPods could not find compatible versions for pod "MapboxNavigation":
  In Podfile:
    MapboxNavigation (~> 0.39.0)

Specs satisfying the `MapboxNavigation (~> 0.39.0)` dependency were found, but they required a higher minimum deployment target.

 pod 'Mapbox-iOS-SDK', '~> 5.9.0'
pod 'MapboxNavigation', '~> 0.39.0'

**Comment by kishansbs** [comment]
which  MapboxNavigation version i need for 'Mapbox-iOS-SDK', '> 5.9.0'?

platform :ios, '9.0'

**Comment by 1ec5** [comment]
v0.37.2 was the last release of MapboxNavigation that supported iOS 9._x_: #2206. The Mapbox Maps SDK continues to support iOS 9._x_ for now, but future versions are expected to drop support for that version.
