### ISSUE TITLE
Mapbox Navigation SDK dependency binary > 100 MB

### ISSUE THREAD

**Issue by mattrobmattrob** [mapbox/mapbox-navigation-ios#2384]
FYI, this is similar to https://github.com/mapbox/mapbox-gl-native/issues/12947 but related to the usage of the Navigation SDK (and dependencies).

## Background

**Mapbox Navigation SDK version:** `v0.40.0`

**Example Carthage Cartfile:** 
```
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK-stripped.json" == 5.9.0
github "mapbox/mapbox-navigation-ios" ~> 0.40
````
To get around the fact that, `mapbox/mapbox-navigation-ios` is dependent on the non-stripped iOS Mapbox SDK.

https://github.com/mapbox/mapbox-navigation-ios/blob/94a29e3888eaa18abad3dc641c70d4d3482d04bd/Cartfile#L2

We can run something like this to ensure the version in our repo is stripped for filesystem size reasons:
```shell
# First, update all dependencies. This will cause the non-stripped Mapbox SDK to 
# exist in the Carthage output directory.
$ carthage update --platform iOS
# Second, update just the Mapbox SDK so the stripped is stored in our repo.
$ carthage update Mapbox-iOS-SDK-stripped --platform iOS
```

**With `.gitignore` entry:**
```
Carthage/Build/iOS/Mapbox*.dSYM
```
This avoids checking in the stripped Mapbox SDK's `dSYM` file since it's greater than 100 MB. This avoids using Git LFS on Github. We upload the symbols to our crash processor service anytime we change the Mapbox SDK version to, once again, only store them there and not in our Github repository.

## Problem with Navigation SDK

Even with this hack to use the stripped Mapbox SDK instead, the `MapboxNavigationNative` dependency from the Navigation SDK is too large to store without using Git LFS.

https://github.com/mapbox/mapbox-navigation-ios/blob/94a29e3888eaa18abad3dc641c70d4d3482d04bd/Cartfile#L3

```shell
$ find . -type f -size +100M
./Carthage/Build/iOS/MapboxNavigationNative.framework/MapboxNavigationNative
./Carthage/Build/iOS/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox
./Carthage/Build/iOS/MapboxNavigationNative.framework.dSYM/Contents/Resources/DWARF/MapboxNavigationNative
```

Example Github non-LFS error for searchability as a result of `git push`:
```shell
$ git push ...
...
remote: Resolving deltas: 100% (316/316), completed with 87 local objects.
remote: warning: File Carthage/Build/iOS/Mapbox.framework/Mapbox is 79.17 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 4128cdcefdb201dd3f938efee8fc4d48
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Carthage/Build/iOS/MapboxNavigationNative.framework/MapboxNavigationNative is 140.95 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Carthage/Build/iOS/Mapbox.framework/Mapbox is 139.61 MB; this exceeds GitHub's file size limit of 100.00 MB
```

## Question

Is there a recommended approach to work around this issue similar to the stripped Mapbox SDK? Am I doing something wrong?

**Comment by mattrobmattrob** [comment]
I've tried to work around it by moving from the downloaded `MapboxNavigationNative.framework` to an `xcframework` approach.

```shell
# Create directories
$ mkdir -p iphoneos
$ mkdir -p iphonesimulator

# Copy Carthage output into platform specific directories
$ cp -R Carthage/Build/iOS/MapboxNavigationNative.framework ./iphoneos/MapboxNavigationNative.framework
$ cp -R Carthage/Build/iOS/MapboxNavigationNative.framework ./iphonesimulator/MapboxNavigationNative.framework

# Look at the architectures in the binary
$ lipo -info ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative 
Architectures in the fat file: ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative are: i386 x86_64 armv7 arm64 

# Remove slices that aren't relevant to each slice of the xcframework
$ lipo -remove i386 ./iphoneos/MapboxNavigationNative.framework/MapboxNavigationNative -o ./iphoneos/MapboxNavigationNative.framework/MapboxNavigationNative
$ lipo -remove x86_64 ./iphoneos/MapboxNavigationNative.framework/MapboxNavigationNative -o ./iphoneos/MapboxNavigationNative.framework/MapboxNavigationNative

# Remove slices that aren't relevant to each slice of the xcframework
$ lipo -remove armv7 ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative -o ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative
$ lipo -remove arm64 ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative -o ./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative

# Create xcframework from 
$ xcodebuild -create-xcframework -framework iphoneos/MapboxNavigationNative.framework/ -framework iphonesimulator/MapboxNavigationNative.framework/ -output "MapboxNavigationNative.xcframework"
xcframework successfully written out to: /Users/mattrobinson/Desktop/MapboxNavigationTest/MapboxNavigationNative.xcframework
```

But the `iphoneos` xcframework slice (no `x86_64` nor `i386`) is still 100+ MB.

```shell
$ find . -type f -size +100M
./MapboxNavigationNative.xcframework/ios-armv7_arm64/MapboxNavigationNative.framework/MapboxNavigationNative
./iphonesimulator/MapboxNavigationNative.framework/MapboxNavigationNative
```

**Comment by 1ec5** [comment]
FYI @mapbox/navnative in case there’s low-hanging fruit for reducing the MapboxNavigationNative binary size.

**Comment by 1ec5** [comment]
> This avoids checking in the stripped Mapbox SDK's dSYM file since it's greater than 100 MB. This avoids using Git LFS on Github. We upload the symbols to our crash processor service anytime we change the Mapbox SDK version to, once again, only store them there and not in our Github repository.

Makes sense. Does your workflow depend on committing the binaries, or would it be possible to run `carthage bootstrap --platform iOS` in each local clone? I don’t think the map SDK and MapboxNavigationNative were developed with the expectation that they’d be committed to repositories, but I understand that it is a workflow supported by Carthage.

**Comment by mattrobmattrob** [comment]
> > This avoids checking in the stripped Mapbox SDK's dSYM file since it's greater than 100 MB. This avoids using Git LFS on Github. We upload the symbols to our crash processor service anytime we change the Mapbox SDK version to, once again, only store them there and not in our Github repository.
> 
> Makes sense. Does your workflow depend on committing the binaries, or would it be possible to run `carthage bootstrap --platform iOS` in each local clone? I don’t think the map SDK and MapboxNavigationNative were developed with the expectation that they’d be committed to repositories, but I understand that it is a workflow supported by Carthage.

At this point, it's not ideal to do a bootstrap for each clone. We've always operated with CocoaPods and Carthage dependencies committed to the repo. If forced, we could investigate that approach.

**Comment by Udumft** [comment]
Unfortunately, there is no "stripped version" of `MapboxNavigationNative` available at the moment. I contacted the NavNative team but they couldn't provide any additional info on when it may be resolved.
To resolve current issue, we could link to stripped versions on dependencies libs, whenever Navigation Native provides such. Before that, since `git lfs` is not an option, some additional actions should be performed after the checkout like `carthage bootstrap` or anything else that would download the binary.

**Comment by Udumft** [comment]
Also, in case your minimum iOS version supported is 11, you can get rid of `armv7` arch in `xcframework` approach, and thus resulting `framework` file will not exceed 100M limit.

**Comment by mattrobmattrob** [comment]
> Also, in case your minimum iOS version supported is 11, you can get rid of `armv7` arch in `xcframework` approach, and thus resulting `framework` file will not exceed 100M limit.

Minimum iOS version is 12 right now. But thanks for the suggestion!

**Comment by Udumft** [comment]
12 > 11, so there are no `armv7` devices which use iOS 12) You can safely purge these symbols.

**Comment by mattrobmattrob** [comment]
> 12 > 11, so there are no `armv7` devices which use iOS 12) You can safely purge these symbols.

Ah, misunderstood the `>` to be `<`. Will look into this right now.

**Comment by Udumft** [comment]
I am going to close this ticket because work on reducing binary size is not a priority at the moment and will be performed in separate ticket(s) across dependent modules.
@mattrobmattrob, can you please confirm the workaround succeeded?

**Comment by mattrobmattrob** [comment]
> I am going to close this ticket because work on reducing binary size is not a priority at the moment and will be performed in separate ticket(s) across dependent modules.
> @mattrobmattrob, can you please confirm the workaround succeeded?

`xcframework` has been validated on `arm64` and simulator devices, yes. 

Do you happen to know if the dSYMs should work without change, @Udumft? We haven't began validation of that yet but wanted to make sure!

**Comment by mattrobmattrob** [comment]
FWIW, using another 3rd party framework (with a known crash) that we have pieced into an `xcframework` similar to [this set of commands](https://github.com/mapbox/mapbox-navigation-ios/issues/2384#issuecomment-637100032,) I _believe_ I have validated that the symbolication (at least in local debug builds) behaves as expected. Feel free to close for now and I will comment again if an issue crops up!
