### ISSUE TITLE
Bug opening and closing the detailed view

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-navigation-ios#2391]
**Mapbox Navigation SDK version: 0.39.1**
**Mapbox Navigation Native SDK version: 6.2.1**

Steps to reproduce: 
1. Open navigation with a route
2. open and close the detailed instructions view 
3. sometimes the dot representing your position is hidden.

![ezgif-6-27e7fc296eaa](https://user-images.githubusercontent.com/9656572/83972567-30ea7080-a8e1-11ea-9776-fb07ea5019ff.gif)

**Comment by Udumft** [comment]
Hello @MarcoCarnevali and thank you for submission! I reproduced this and there is already ongoing work on similar issue, which also resolves this one. You can track it's progress [here](https://github.com/mapbox/mapbox-navigation-ios/pull/2387)
