### ISSUE TITLE
Get route progress without presenting NavigationViewController

### ISSUE THREAD

**Issue by orim55353** [mapbox/mapbox-navigation-ios#2400]
Hello, im trying to use mapbox navigation sdk to show navigation route on a NavigationMapView.
I want to get route progress notifications or delegate updates without presenting the viewcontroller, i just wanna show it on a NavigationMapView on my custom view controller.

I cant figure a way to do so and i would love to get some help with that.

Thanks alot.

**Comment by Udumft** [comment]
Hello, @orim55353!

[NavigationViewController](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationViewController.swift#L24) is an `open` class, so you can easily subclass it to provide your custom UI/features or even implement your own version, using the original one as an example.

Another option is to embed `NavigationViewController`'s view into your custom View Controller (as an example, you can see how Top and Bottom banners are [embedded](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L206) in the SDK), and use `NavigationViewController` [delegate](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationViewController.swift#L67) to receive required events.

**Comment by Pic2490** [comment]
@Udumft

I'm doing:
`.onAppear(perform: {
       self.myNavController!.navigationService.routeProgress.durationRemaining
})
`

in SwiftUI but the duration remains the same unless I call self.myNavController..... in my UIViewControllerRepresentable. Basically, the in app navigation has to show for self.myNavController to show the correct time remaining. Can you give some examples on how to correctly show the correct time remaining without showing the NavigationViewController? Thank you!

**Comment by TimoninD** [comment]
why it closed? It not solved, give any way please
