### ISSUE TITLE
Calling Directions.shared.calculate() more than once on one navigationViewController

### ISSUE THREAD

**Issue by bmilagre** [mapbox/mapbox-navigation-ios#2407]
Hi guys

Since I haven't found anything, I'll ask here. Would it be possible to address the method Directions.shared.calculate() several times and output everything together in one navigationViewController? I just have a route that has more than 25 waypoints, so it is not possible at the moment with the example on the docs.

Thanks

**Comment by mazn403** [comment]
https://github.com/mapbox/mapbox-gl-native.wiki.git

**Comment by 1ec5** [comment]
What you’ll get from calling `Directions.calculate(_:completionHandler:)` is a RouteReponse containing one or more Route objects containing several legs. You could in principle pull the Route out of each RouteResponse and concatenate their arrays of legs together before feeding the resulting Route into NavigationViewController. RouteResponse and Route have initializers that take the required members as arguments.
