### ISSUE TITLE
IB Designables issue.

### ISSUE THREAD

**Issue by toothpiggystudio** [mapbox/mapbox-navigation-ios#241]
Hi, I have this error popping up when I open my storyboards but when i run the app it compiles successfully. How i can get rid of this error? I already tried removing MapboxNavigation from pod and install it again but got the same thing. please see attached image.

![mapboxerror](https://cloud.githubusercontent.com/assets/28891494/26346858/a57055fe-3fb8-11e7-9d8e-c0ff4fcf144c.png)

Thanks. :)

**Comment by frederoni** [comment]
You need to open `Navigation.storyboard` once for Xcode to refresh the views in that storyboard.
If Xcode isn't refreshing automatically, go to Editor->Refresh all views when the storyboard is open.

**Comment by toothpiggystudio** [comment]
Hi Fredrik, 

Thanks for your quick reply, i have tried what you said. and its still the same. I refractor the other scene and tried to refresh but still the same.
I got this error (please see attached), but other scene doesn’t use mapbox framework.

Thanks,
Rene

**Comment by frederoni** [comment]
Email attachments on Github issue are currently ignored. You'll have to attach directly on Github.

**Comment by toothpiggystudio** [comment]
![screen shot 2017-05-23 at 1 52 29 pm](https://cloud.githubusercontent.com/assets/28891494/26349194/2056f2c6-3fc0-11e7-9729-50fe05413ee4.png)

**Comment by frederoni** [comment]
I also get these error messages every now and then. There's nothing wrong but it's very annoying.
However, they seem to always go away after:
- Clean the build folder (<kbd>⌘</kbd><kbd>⇧</kbd><kbd>K</kbd>)
- Delete Derived Data
- Run `pod update`
- Open `Navigation.storyboard` and wait until all libraries are compiled.

**Comment by toothpiggystudio** [comment]
Thanks @frederoni ... trying it now. 👍

**Comment by toothpiggystudio** [comment]
Hi frederoni, sorry for disturbing and i just read your last message about "Just to be sure, how do you reference the Navigation SDK? Is it a storyboard reference or in code?" it was reference in  a UIView on 2 storyboards but it also affect other storyboards that doesn't used mapbox.
