### ISSUE TITLE
Special-case GB locales to use imperial units

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#242]
https://github.com/mapbox/mapbox-navigation-ios/issues/211#issuecomment-303495328 points out that 🇬🇧 uses the metric system officially but still measures road distances in miles (and yards). `Locale.usesMetricSystem` returns `true` when the locale’s region code is `GB`, so we need to special case `GB` to format distances with miles instead of kilometers. In this case, we may also want to disable the workaround in DistanceFormatter that [replaces yards with feet](https://github.com/mapbox/mapbox-navigation-ios/blob/7952bdc88244db90bdbe348ff9920919d2ca6d7f/MapboxNavigation/DistanceFormatter.swift#L41), assuming that Britons are more accustomed to yardages than Americans.

/cc @bsudekum @andrey-str

**Comment by bsudekum** [comment]
@1ec5 is this the only case?

**Comment by 1ec5** [comment]
The UK is in [a unique position](https://en.wikipedia.org/wiki/Road_signs_in_the_United_Kingdom#Units_of_measurement). As far as I can tell, all the other countries for which `Locale.usesMetricSystem` returns `true` do use metric distances on road signage. (Just as there’s [a highway in the U.S. that uses meters and kilometers](https://en.wikipedia.org/wiki/Interstate_19), there are some metric distance signs in the UK, but not enough to matter for our purposes.)

**Comment by andrey-str** [comment]
This is what my Briton client was asking for: change kmh to mph, etc. 

Hope he don't mind a quote:

> yep, we're a stupid country, sell stuff in metric, measure distance when driving in imperial
> clever aren't we ;)

I personally did a quick patch for my needs, but I'm not really aware of that yards situation. Basically I left all as was except special case for "GB" region. 

PS: if you'll open Apple Maps with active UK region, you'll see miles :)

**Comment by andrey-str** [comment]
👍 thanks!

**Comment by troyibm** [comment]
@1ec5 is there a way to change the navigation to on-the-fly use metrics system?  I know it is based on the system locale, but I need to demo different locales on the fly inside an app.  Thanks.

**Comment by 1ec5** [comment]
> Even setting my iPad system language to German doesn't use metric units. I thought that would be a work around.

It’s based on the system region, not the system language or preferred language. If you set the region to Germany or Australia, it’ll be in metric.

An explicit measurement system option would be a good idea. Let’s track that in #589.

**Comment by troyibm** [comment]
@1ec5 Ah.. the region.  Cool.  That works for me.  Thanks.
