### ISSUE TITLE
Methods not firing

### ISSUE THREAD

**Issue by cmtoomey** [mapbox/mapbox-navigation-ios#2426]
**Setup**
I am working on updating an iPhone app. The app allows a user to go through 1 or more stops on their Route. Once they have selected their spots they'll be taken to a view that displays a map that draws out that route & also displays an InstructionsBannerView to show the directions.

**Desired Outcome**
Get the directions displaying in my InstructionsBannerView (which will be spoken from the device's synth as well)
When a user reaches a destination there is more interaction they will do in the app. This is all controlled in the routing methods which are not getting called so that is my top priority.

---

**Initial Issue**

This UIViewController was using RouteControllerDelegate but after updating my pods it seems that it was deprecated. I switched this to RouterDelegate, but the view still isn't working. I was able to get the InstructionsBannerView to display the direction arrow, the distance away label, but it's not displaying the routing/directions info.

All of my routing methods are not getting called. I have tried using RouterDelegate and NavigationServiceDelegate. 

The only thing it is during correctly is drawing out where I will be going from my current location.

When I started the update, here are the versions the app was running:

MapboxNavigation ~> 0.16.2
Mapbox-iOS-SDK ~> 3.6
MapboxGeocoder.swift ~> 0.8

Here are the versions I am currently running:
MapboxNavigation ~> 0.39.1
Mapbox-iOS-SDK ~> 5.5.1
MapboxGeocoder.swift ~> 0.12.0

---

**Details**

Checking my ViewController, I am using this in a method for calculating my route, like so:

`let options = NavigationRouteOptions(waypoints: point, profileIdentifier: .automobile)`

I have another method for getting my route if I were to go off the route that was using RouteOptions. I converted it to use NavigationRouteOptions with no change.

I did find yesterday that I had both NavigationService & RouterDelegate methods firing. Which is good, but the methods I need to fire still aren't. 

These are the ones I need to fire:

`func routeController(_ routeController: RouteController, didUpdate locations: [CLLocation])`

`func router(_ router: Router, didArriveAt waypoint: Waypoint) -> Bool`

Right now I'm testing with my house as the current location & my destination to be a few houses down, ~150 ft.  So I can go outside and walk and see that the distance moves from 150 ft. to 0 ft. & I get the voice telling me my instructions. What is displayed in my InstructionsBannerView is incorrect but I'll move to that later. But I can be standing right at my marker at 0 ft, but the methods above aren't firing. 

cc @1ec5

**Comment by 1ec5** [comment]
This sounds reminiscent of the behavior reported in #2125, which has been fixed but the fix hasn’t been released yet. Are you setting any other settings on `routeOptions`, like the `shapeFormat` property?

**Comment by lukeirvin** [comment]
@1ec5 I'm not. I am setting `routeShapeResolution`, but `shapeFormat` is not used anywhere in my project.

**Comment by lukeirvin** [comment]
If there is anything else I can provide that will help please let me know.

**Comment by lukeirvin** [comment]
Update: I believe I have the majority of this working now. I can see my Instructions Banner does update & I have my route system improved. I do have a consistent issue though where when I get to the last step or to the destination my instruction banner displays a dictionary & it's read via the synth. This should be displaying the actual address. I have opened a new ticket that focuses on this task itself.
