### ISSUE TITLE
Junction views do not appear when guidance cards are enabled

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2434]
#2408 adds a JunctionView to the top banner stack so that junction views appear whenever the Directions API response calls for them. However, if guidance cards are enabled, no JunctionView appears because the component stack isn’t part of the view hierarchy in that case. When guidance cards are enabled, we should add a JunctionView as a floating view somewhere in the main part of the view controller, constrained to avoid the cards themselves (which may vary in height) and any floating buttons.

/cc @mapbox/navigation-ios @avi-c @fabian-guerra

**Comment by avi-c** [comment]
This work is contained in my additions to #2408.

**Comment by zugaldia** [comment]
@fabian-guerra we'd love your eyes on https://github.com/mapbox/mapbox-navigation-ios/pull/2408, apparently I can't tag you to review your own PR :-)

**Comment by 1ec5** [comment]
Fixed in #2408.
