### ISSUE TITLE
CarPlayManagerTests.testManagerTellsDelegateWhenNavigationStartsAndEndsDueToArrival sporadically crashes on CI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2441]
`CarPlayManagerTests.testManagerTellsDelegateWhenNavigationStartsAndEndsDueToArrival()` has been crashing sporadically on CI since we upgraded MapboxNavigationNative in #2412. First step is to see if it keeps happening now that #2417 has landed.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/2439#issuecomment-654908491
/cc @mapbox/navigation-ios @avi-c

**Comment by 1ec5** [comment]
This might be fixed as part of #2477.

**Comment by 1ec5** [comment]
This crash was happening sporadically on CI, but I can reproduce it reliably on release-v1.0-pre-release as of db1bb8a4edb7c9f12bb2dbe92d7fe6ae671eb5d7 when running the test individually:

```
2020-07-21 18:09:45.481062-0700 Example[88352:8231871] Warning: Attempt to present <MapboxNavigationTests.CarPlayNavigationViewControllerTestable: 0x7fbed2c76a60> on <MapboxNavigation.CarPlayMapViewController: 0x7fbed3b24c90> whose view is not in the window hierarchy!
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /path/to/mapbox-navigation-ios/MapboxNavigationTests/CarPlayManagerTests.swift, line 214
2020-07-21 18:09:45.483130-0700 Example[88352:8231871] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /path/to/mapbox-navigation-ios/MapboxNavigationTests/CarPlayManagerTests.swift, line 214
```

`manager.currentNavigator` is `nil` each time. It never gets retained outside of `CarPlayManager.mapTemplate(_:startedTrip:using:)`, because `CarPlayManager.carPlayMapViewController` isn’t part of the view hierarchy and can’t present it.

**Comment by 1ec5** [comment]
We saw basically the same thing in https://github.com/mapbox/mapbox-navigation-ios/pull/2360#issuecomment-615410538, but here we are testing whether the CarPlayNavigationViewController (`currentNavigator`) can exit correctly.

**Comment by dersim-davaod** [comment]
Checked the current implementation, 

testManagerTellsDelegateWhenNavigationStartsAndEndsDueToArrival is stable now.
