### ISSUE TITLE
Update instructions regarding using .netrc workflow

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-navigation-ios#2444]
Currently the latest internal dependencies require the configuration of .netrc file.
We should provide a simple step-by-step instruction on .netrc workflow for contributors (README.md and custom-navigation.md).

**Comment by 1ec5** [comment]
#2442 updated the documentation to mention these things. If anything is missing, please feel free to PR a fix. Thanks!

**Comment by dersim-davaod** [comment]
Thanks for pointing that.
Changes in #2442 is fine, closing the issue.
