### ISSUE TITLE
Fix error during the updating Carthage dependencies

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-navigation-ios#2445]
While running `carthage update --platform ios --use-netrc` command, there's an error:

```
***  Skipped installing ios-snapshot-test-case.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)."

    Falling back to building from the source
```

# Steps to reproduce:
By trying to build iOS SDK from scratch.

# Goal

Need to fix it to mitigate the error and potentially speed up the building process.

**Comment by 1ec5** [comment]
Carthage automatically recovers from this error by rebuilding from source. This is expected behavior whenever you upgrade to a newer version of Xcode. Are you seeing a different, unrecoverable error further down?

**Comment by dersim-davaod** [comment]
Yes, that's right. I was wondering more about if we can avoid the rebuilding from source to speed it up. If there's a pre-built Swift 5+ ios-snapshot-test-case.framework binary is available?

Seems in our case
> expected behavior whenever you upgrade to a newer version of Xcode

can be mitigated starting for minor releases starting Swift 5.

**Comment by 1ec5** [comment]
> can be mitigated starting for minor releases starting Swift 5.

Only if the framework has library evolution enabled. Turf and Polyline have it enabled but not the other Carthage dependencies. For what it’s worth, this is a nonissue when building with CocoaPods and SPM, the two supported dependency managers in v2._x_ and above.

**Comment by dersim-davaod** [comment]
Closing as we agreed that currently this is not an issue that affects the dev process.
