### ISSUE TITLE
Indicate current road name during free-driving

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2456]
The navigation SDK should indicate the name of the road the user is currently on even during “free-driving” outside of turn-by-turn navigation, so that the developer can stick this information in WayNameLabel/WayNameView.

MapboxNavigationNative provides this information via the `MBNavigationStatus.roadName` property. One possibility is to expose this information as part of the location manager being added in #2410.

/ref #2259 #590
/cc @mapbox/navigation-ios @d-prukop

**Comment by avi-c** [comment]
In my brief look at the current road name provided in the status updates it looked like it isn't set by NN for simulation. Is this expected?

**Comment by 1ec5** [comment]
#2410 adds a `roadNameKey` key to the user info dictionary of passive location update notifications.

> In my brief look at the current road name provided in the status updates it looked like it isn't set by NN for simulation. Is this expected?

Unfortunately, the navigator only populates this field during free-driving, not during turn-by-turn navigation, even if route simulation is enabled. Once a future version of MapboxNavigationNative exposes the current road name during turn-by-turn navigation, we’ll find a way to expose it as part of a route controller location update and potentially route progress as well.
