### ISSUE TITLE
Crash when attempting to use Custom navigation UI in Example app

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2476]
The example app in the v1.0 pre-release branch in will crash if you select "Custom UI" as the option when starting a nav session.

I believe the issue is the XIB file for the CustomViewController contains references to some view classes that have been renamed for Swift, specifically:

MBInstructionsBannerView -> InstructionsBannerView
MBNavigationMapView -> NavigationMapView

**Comment by 1ec5** [comment]
Likely a regression from #2230.

**Comment by MaximAlien** [comment]
I think this ticket is the same to [this one](https://github.com/mapbox/mapbox-navigation-ios/issues/2414) I've created some time ago. PR can be found [here](https://github.com/mapbox/mapbox-navigation-ios/pull/2478).

**Comment by avi-c** [comment]
Agreed. Closing this ticket.
