### ISSUE TITLE
Polly voice no longer works after upgrading to 0.40.0 (from 0.38.1)

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-ios#2480]
I have upgraded the iOS SDK from 0.38.1 to 0.40.0 and have fixed all of the discrepancies.  The app works properly like it did before, but I can no longer get the Polly voice to play.  I'm only hearing a male voice and the Polly directions formatting is not available.  I believe I'm hearing a Siri voice instead of the Polly voice.  

Here is my NavigationRouteOptions:

let routeOptions: NavigationRouteOptions?
routeOptions = NavigationRouteOptions(waypoints: [origin, destination], profileIdentifier: .automobileAvoidingTraffic) 
routeOptions?.locale = NSLocale(localeIdentifier: getLocale()) as Locale
routeOptions?.distanceMeasurementSystem = .metric

Here is my Directions calculation and NavigationViewController creation:

Directions.shared.calculate(routeOptions!) { [weak self] (session, result) in
            switch result {
            case .failure(let error):
                return
            case .success(let response):
                guard let route = response.routes?.first, let strongSelf = self else {
                    return
                }
                
                let navigationViewController = NavigationViewController(for: route, routeOptions: routeOptions!)
                navigationViewController.delegate = self
                navigationViewController.voiceController.voiceControllerDelegate = self
                navigationViewController.modalPresentationStyle = .currentContext
                self!.present(navigationViewController, animated: true, completion: nil)
            }
        }

The posted is the updated version of the code I was using before (so it's compatible with 0.40.0.  I am hitting the VoiceControllerDelegate function:

func voiceController(_ voiceController: RouteVoiceController, willSpeak instruction: SpokenInstruction, routeProgress: RouteProgress) -> SpokenInstruction? {
}

Instead of hearing the instruction.ssmlText, the spoken voice is defaulting 100% of the time to the instruction.text.  If I change the instruction.text in the willSpeak delegate function, the changed instruction.text is what I hear.  It never plays the instruction.ssmlText like it did in SDK version 0.38.1. 

I have a good connection (this happens over WiFi and broadband).  Am I missing something?  I've gone through the documentation and I used the updated "Build A Navigation App" tutorial to update my code.

iOS version:  13.5
Mapbox Navigation SDK Version: 0.40.0

**Comment by Udumft** [comment]
Hello, @billyking991!
This is a known issue. It comes from incorrect API endpoint URL construction inside Mapbox Speech Synthesizer. [There](https://github.com/mapbox/mapbox-navigation-ios/pull/2348/files#diff-4a0635e15da9271f275e40b32a022a7bR51-R56) is major Speech Synthesizer refactoring going on, which will also resolve that issue.
In the meantime, you can workaround it like this:
```
let credentials = Directions.shared.credentials // your credentials here
let navigationService = MapboxNavigationService(route: route, routeOptions: routeOptions!)
let speechSynthesizer = SpeechSynthesizer(accessToken: credentials.accessToken, host: credentials.host.host!) // note we pass 'host.host!' to extract exactly the hostname from the URL
let voiceController = MapboxVoiceController(navigationService: navigationService, speechClient: speechSynthesizer)
let navigationOptions = NavigationOptions(navigationService: navigationService, voiceController: voiceController)

let navigationViewController = NavigationViewController(for: route, routeOptions: routeOptions!, navigationOptions: navigationOptions)
// ...
```
This is to manually configure `SpeechSynthesizer` host argument to strip URL schema and contain only the hostname.

**Comment by billyking991** [comment]
Wow!  Works like a charm.  Thank you so much for the code snippet.  I would have never been able to come up with that on my own.  Do you have an idea on when the SpeechSynthesizer refactoring will be done?  I'm assuming in time for v.1.0.0, correct?  Thanks again for the help!

**Comment by Udumft** [comment]
> I'm assuming in time for v.1.0.0, correct?

That's correct :)
