### ISSUE TITLE
Feedback event should be created when tapping feedback button, not when completing the form

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2484]
For feedback events, `NavigationEventDetails` is populated with coordinates, a screenshot, etc. when the structure is initialized as part of a call to `NavigationEventsManager.recordFeedback(type:description:)`. With the normal built-in feedback flow, this method gets called by side effect when getting `FeedbackViewController.uuid`, which currently only happens once the user taps a feedback category, right before we complete the feedback event with a category:

https://github.com/mapbox/mapbox-navigation-ios/blob/50def9e3dacb22c9ae3c95d54067afbcf1584afd/MapboxNavigation/FeedbackViewController.swift#L230-L234 https://github.com/mapbox/mapbox-navigation-ios/blob/50def9e3dacb22c9ae3c95d54067afbcf1584afd/MapboxNavigation/FeedbackViewController.swift#L126-L128

However, if the user taps the feedback button in CarPlay, `CarPlayNavigationViewController.createFeedbackUI()` creates the event and populates it right away when showing the feedback UI. mapbox/mapbox-navigation-android#3274 also moved the coordinate and screenshot capturing earlier to when the user taps the feedback button and the feedback UI appears.

For consistency with CarPlay and Android, we should do the same on iOS by getting `uuid` when initializing the FeedbackViewController. To avoid future confusion, we should also turn `uuid` into a method that obviously has a side effect.

/cc @mapbox/navigation-ios @avi-c @JunDai

**Comment by AlehKu** [comment]
@1ec5 Are there any updates about this issue?
