### ISSUE TITLE
NextBannerView is overlapping with StatusView.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2489]
**Mapbox Navigation SDK version:** `1.0.0-beta.1`

In some cases NextBannerView is overlapping with StatusView which leads to broken UI. See example:
<img width="395" alt="Screen Shot 2020-07-26 at 12 14 57 PM" src="https://user-images.githubusercontent.com/1496498/88487448-02306400-cf3a-11ea-9a21-10cf6e2b151c.png">

**Comment by 1ec5** [comment]
This issue reproduces easily by choosing a route that has two very closely spaced maneuvers right at the beginning of the route. For example, set the iOS Simulator’s simulated location to Apple, then get a route out to De Anza Boulevard. The two turn maneuvers in the IL2 parking lot cause this next banner to appear and persist across multiple maneuvers. Only showing and hiding the step banner clears it out.
