### ISSUE TITLE
Is it possible to have a custom route?

### ISSUE THREAD

**Issue by functionaltair** [mapbox/mapbox-navigation-ios#252]
Do you know If I am able to provide routing data from Here maps, could I overlay that on top of / and use MapBox turn by turn?

**Comment by frederoni** [comment]
Have a look at the [Route](https://github.com/mapbox/MapboxDirections.swift/blob/master/MapboxDirections/MBRoute.swift) object in [MapboxDirections](https://github.com/mapbox/MapboxDirections.swift). If you can transform the Here response to something that's compatible with that Route, then it would work.

Support for OSRM routes in MapboxDirections is being tracked here https://github.com/mapbox/MapboxDirections.swift/issues/121

**Comment by arrabidas92** [comment]
Hi @functionaltair, did you manage to feed MapBox turn by turn by providing your routing data ?
I have the same issue.

**Comment by andfs** [comment]
@arrabidas92 did you figure out how to do that?
