### ISSUE TITLE
Indicate reduced accuracy location mode

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2555]
Starting in iOS 14, the system Location Services prompt will offer the user an option to share only crude location updates with the application. Reduced accuracy is unlikely to be quite as useful for turn-by-turn navigation as full accuracy, though it might be a valid use case for free-driving, depending on the application.

mapbox/mapbox-gl-native-ios#372 tracks adding an accuracy halo to the user puck during course tracking, similar to the halo around the user dot during location or heading tracking. The UserPuckCourseView drawing code is more or less a straight copy of the course mode of the map SDK’s MGLFaux3DUserLocationAnnotationView, so it should be straightforward to keep UserPuckCourseView in sync.

Accurate location tracking is critical to turn-by-turn navigation functionality, so we should revive the “Weak GPS Signal” status bar that was introduced in #490. We can call `NavigationViewController.showStatus(title:spinner:duration:animated:interactive:)` to display that status bar.

/ref #2554
/cc @mapbox/navigation-ios @mapbox/maps-ios

**Comment by jill-cardamon** [comment]
Clarification on status banner: Could you even generate a route with user's precise location?
It would require a lot of steps for a person to turn precise location off in the middle of turn-by-turn navigation, so this banner is a bit of an edge case. This case might be more likely to show up during free driving.
