### ISSUE TITLE
Replace Route with RouteResponse plus route index

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2589]
The original vision behind mapbox/mapbox-directions-swift#391 was that a client such as the navigation SDK would operate mostly in terms of a whole RouteResponse plus a route index into that response. That way, we don’t have to copy attributes of the response into each individual route, as seen in mapbox/mapbox-directions-swift#452. Unfortunately, we never got quite that far in mapbox/mapbox-navigation-ios#2350:

* [ ] `MapboxNavigationService(route:routeOptions:directions:locationSource:eventsManagerType:simulating:routerType:)` should take a RouteResponse, not an individual Route.
* [ ] `NavigationViewController(for:routeOptions:navigationOptions:)` should take a NavigationService instead of a Route.

This much sounds simple, but there are potentially quite a few knock-on effects throughout the codebase. It’s too late to get these backwards-incompatible changes into v1.0. We can get them into a subsequent minor release as long as we take steps to ensure backwards compatibility. A convenience initializer for MapboxNavigationService can wrap a Route in a RouteResponse, and a convenience initializer for NavigationViewController can wrap a Route in a RouteResponse and MapboxNavigationService.

/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
Corresponding changes happen in these PRs for [directions](https://github.com/mapbox/mapbox-directions-swift/pull/562) and for [NavSDK](https://github.com/mapbox/mapbox-navigation-ios/pull/3182).
