### ISSUE TITLE
Navigation doesn't dismiss 

### ISSUE THREAD

**Issue by dawidvdh** [mapbox/mapbox-navigation-ios#2594]
This issue can also be seen on [navigation-ios-examples](https://github.com/mapbox/navigation-ios-examples) in the Advanced example, one can only dismiss the modal in simulate mode, I am experiencing the same issue with mapbox dismissal in an app I am working on. Is there currently a workaround? As simply attempting the following:

```
    func navigationViewControllerDidDismiss(_ navigationViewController: NavigationViewController, byCanceling canceled: Bool) {
        self.navigationViewController?.dismiss(animated: true, completion: nil)
    }
```

The above does dismiss the modal however the voice instructions still go off as if though the UI is gone but the routing is still on going. When reopening the navigation after attempting to close with this method causes the previous voice instructions to sound off while the current is also going off.

This may be related to #2201. I have also tried the workaround mentioned in the issue with no success.

**Mapbox Navigation SDK version: 0.40.0**

**Comment by amisolani-simformsolutions** [comment]
@dawidvdh  Just need to stop the navigation service manually before dismiss, that worked for me.

```
 func navigationViewControllerDidDismiss(_ navigationViewController: NavigationViewController, byCanceling canceled: Bool) {
        navigationViewController.navigationService.stop()
        self.navigationViewController?.dismiss(animated: true, completion: nil)
    }
```

**Comment by younusmahmood** [comment]
Can we reopen this? This is still an issue and no solutions online are working.
