### ISSUE TITLE
Buildings fail to highlight if the route is shorter than 250 meters

### ISSUE THREAD

**Issue by d-prukop** [mapbox/mapbox-navigation-ios#2597]
The building won't highlight on a route that starts with less than 250 meters to the first waypoint or destination. This seems to only affect the first stop.

**Comment by abhishek1508** [comment]
@langsmith It would be great if we can check Android as well to make sure we don't have the bug.

cc @asinghal22 @zugaldia

**Comment by langsmith** [comment]
@abhishek1508 , won't be an issue on Android. We don't hardcode a distance like what's done on iOS.

**Comment by zugaldia** [comment]
Removing the milestone for now until we decide the timing for the next iteration.

**Comment by Udumft** [comment]
I could not reproduce the issue neither on 1.4.2 nor on 2.0 latest beta. Buildings are highlighted even if are in 250m radius from user's location. If it is still actual, please reopen the task.
