### ISSUE TITLE
Route refresh is causing vanishing route line flickering.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2602]
After implementing route line refresh feature vanishing route line started flickering whenever there is an update from `navigationService(_:didRefresh:)`. Here's example:

![output](https://user-images.githubusercontent.com/1496498/92195821-b61eec00-ee22-11ea-845d-c3950904e8c3.gif)

One noticeable difference is that there is discrepancy between routeProgress received in `navigationService(_:didRefresh:)` and `navigationService(_:didUpdate:with:rawLocation:)` (updates are performed from these two methods). For example, here's difference between `fractionTraveled`:
```
navigationService(_:didUpdate:with:rawLocation:) 0.22210326922037532
navigationService(_:didUpdate:with:rawLocation:) 0.22825447740186164
navigationService(_:didUpdate:with:rawLocation:) 0.234405677210044
navigationService(_:didUpdate:with:rawLocation:) 0.24055686864482664
navigationService(_:didUpdate:with:rawLocation:) 0.24670805170795918
navigationService(_:didUpdate:with:rawLocation:) 0.2528592263976986
navigationService(_:didUpdate:with:rawLocation:) 0.25901039271647575
navigationService(_:didRefresh:) 0.0786438308283817
```

**Comment by 1ec5** [comment]
Does the screen recording above reflect the actual frequency of the issue, or is it sped up because of this debugging line?

https://github.com/mapbox/mapbox-navigation-ios/blob/0fd7fc9d1c084250564f161a806f583291e63ba3/Example/ViewController.swift#L244-L245

**Comment by MaximAlien** [comment]
> Does the screen recording above reflect the actual frequency of the issue, or is it sped up because of this debugging line?
> 
> https://github.com/mapbox/mapbox-navigation-ios/blob/0fd7fc9d1c084250564f161a806f583291e63ba3/Example/ViewController.swift#L244-L245

Actually I've decreased interval to be 5 seconds to receive updates more often. It should still be visible with higher intervals as well (route has to be longer though).
