### ISSUE TITLE
Resume button keeps showing in china language!

### ISSUE THREAD

**Issue by kamellababidi** [mapbox/mapbox-navigation-ios#2608]
Hey guys, I'm facing a small issue with Mapbox navigation on IOS, 
I set everything to English (development language, system language, and app language).
everything is showing in English in the navigation view **except** the resume button showing in Chinese.  
Anyone can help?

  - MapboxNavigation (0.40.0)
  - react-native (0.60.0)

**Comment by kamellababidi** [comment]
![WhatsApp Image 2020-09-05 at 1 30 10 PM](https://user-images.githubusercontent.com/30745783/92302317-5b99a300-ef7c-11ea-9458-85eace5a50ee.jpeg)

**Comment by kamellababidi** [comment]
<img width="339" alt="Screen Shot 2020-09-05 at 1 33 55 PM" src="https://user-images.githubusercontent.com/30745783/92302328-753aea80-ef7c-11ea-80e9-cab1875a27b7.png">

**Comment by bartlomiejlechowski** [comment]
@kamellababidi  I have the same issue, in my case the "Resume / Re-center" button on Physical Device is in Turkish "RESUME" = "Devam et"` (Chinese on Simulator)

Did you resolve that?
