### ISSUE TITLE
Icons go blank if app has custom tint color set

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-navigation-ios#261]
Navigation icons go blank if used within an application that has a custom tint color set - notice how the user location icon and the route overview icons are white. Occurs in version `0.4.0`. The workaround in this case is to override the navigation style's tint color. 

cc @ericrwolfe @bsudekum 

![img_1849](https://cloud.githubusercontent.com/assets/10850812/26749055/2af8483c-47b9-11e7-9b63-a288c49c0dc1.PNG)

**Comment by ericrwolfe** [comment]
Actually, it looks like in the above example, there wasn't actually a tint color set in the test application. Also note that the problem only occurred on device, the simulator was fine.

Interestingly @captainbarbosa, I can't recreate this on my device :/.

cc @frederoni

**Comment by bsudekum** [comment]
Haven't seen this in a long time, going to close this out.
