### ISSUE TITLE
Top banner swiping is not mirrored for right-to-left languages

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2626]
TopBannerViewController allows the user to swipe to the left to reveal the subsequent maneuver coming in from the right. In right-to-left languages, such as Arabic or Hebrew, the user should swipe to the right to reveal the subsequent maneuver coming in from the left. However, the interface isn’t currently mirrored, so the user has to swipe in a direction that is counterintuitive for them.

InstructionsCardViewController correctly shows the subsequent maneuver peeking in from the left, but swiping either left or right tends to make the carousel get confused and fast-forward to the end of the route.

/cc @mapbox/navigation-ios @mapbox/1tap-ios

**Comment by 1ec5** [comment]
Might be good to look at at the same time as #2695.

**Comment by MarcoCarnevali** [comment]
@1ec5 can we add an option to hide subsequent maneuvers ?

**Comment by jill-cardamon** [comment]
Looks like top banner swiping is hard-coded as right and left:
https://github.com/mapbox/mapbox-navigation-ios/blob/b7280efb6cc77eb111a4afd4bd5d956a2bfd3191/MapboxNavigation/NavigationViewController.swift#L802-L810

**Comment by 1ec5** [comment]
> can we add an option to hide subsequent maneuvers ?

Can you elaborate? Do you mean hiding a particular maneuver? Or disabling the feature where the next maneuver’s card always peeks in from the side? Or the feature where a subsequent maneuver in close proximity is attached to the current card? Either way, it would be an unrelated feature request, so please open a separate issue so we can track it. Thanks!

**Comment by truburt** [comment]
@jill-cardamon , can we close this one?

**Comment by jill-cardamon** [comment]
yep will close today!
