### ISSUE TITLE
Compiler warning in FeedbackViewController — Initialization of immutable value 'titleHeight' was never used

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2639]
#2630 introduced the following compiler warning by making a local variable unused:

```
/path/to/Pods/MapboxNavigation/MapboxNavigation/FeedbackViewController.swift:312:13: Initialization of immutable value 'titleHeight' was never used; consider replacing with assignment to '_' or removing it
```

Do we still need this height anywhere in the calculations, or is it safe to remove it outright?

/cc @avi-c @mapbox/navigation-ios

**Comment by avi-c** [comment]
This can be removed. I should have cleaned up the warning in the other PR.
