### ISSUE TITLE
Selecting a current leg programatically when initialising MBNavigationService

### ISSUE THREAD

**Issue by noway** [mapbox/mapbox-navigation-ios#2641]
Hello, we are using Mapbox Navigation with multiple legs setup and sometimes the view is loaded when a user already driven a portion of the route (1 or few legs). Is it possible to programmatically set currentLeg during initialization or shortly after?

I can see that RouteProgress class can be initialized with a leg index:

https://github.com/mapbox/mapbox-navigation-ios/blob/7866e550a9b363d2fe438669c2da2429361a4ce4/MapboxCoreNavigation/RouteProgress.swift#L184

But this is not actually used in Router:

https://github.com/mapbox/mapbox-navigation-ios/blob/7866e550a9b363d2fe438669c2da2429361a4ce4/MapboxCoreNavigation/Router.swift#L261

And neither in the RouteController:

https://github.com/mapbox/mapbox-navigation-ios/blob/7866e550a9b363d2fe438669c2da2429361a4ce4/MapboxCoreNavigation/RouteController.swift#L156

What is the way to set legIndex during/shortly after initialization? I would love to be able to do something like
```objective-c
[(mbNavigationService.router) setLegIndex:2];
```

I've searched documentation for "leg index" and "current leg" but haven't found anything relevant.

Cheers.

**Comment by 1ec5** [comment]
Here’s one way to programmatically advance to a leg beyond the first leg of the route:

https://github.com/mapbox/mapbox-navigation-ios/blob/7866e550a9b363d2fe438669c2da2429361a4ce4/Example/ViewController.swift#L520-L523

Note that this method was broken for RouteController before #2610, which went into v1.0.0-rc.4.

**Comment by noway** [comment]
thanks

**Comment by Zayankovsky** [comment]
@1ec5 on Android we added a similar option in mapbox/mapbox-navigation-android#4739. So maybe something should be done on iOS as well to keep feature parity between platforms.
