### ISSUE TITLE
ETA label is too small

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2645]
The ETA label is the same size as the distance traveled label. It should be considerably larger as seen in #2569.

b30c71533e884bd807367690a06fbc569b5b5168 | 7866e550a9b363d2fe438669c2da2429361a4ce4
----|----
<img src="https://user-images.githubusercontent.com/1231218/91210315-e13a6a80-e6c1-11ea-85da-b2d8ee6c4229.png" width="300" alt="big"> | <img src="https://user-images.githubusercontent.com/1231218/93814668-b3d1d580-fc09-11ea-8b53-05ccb34e14e4.png" width="300" alt="small">

This regression was introduced toward the end of the v1.0 release cycle.

/cc @mapbox/navigation-ios

**Comment by avi-c** [comment]
Looks like the UIAppearance font property is not being applied properly. Indeed, even the small size seen now for the distance travelled label is incorrect at 16pts and not the 18pts it was before. 16 points is what's inherited from the base `StylableLabel` class, not the 18 intended for the`DistanceRemainingLabel` subclass.

Not sure why this changed partway through the release though.
