### ISSUE TITLE
App Crashed after 150 km distance ride

### ISSUE THREAD

**Issue by sridharnatarajan89** [mapbox/mapbox-navigation-ios#2647]
**Mapbox Navigation SDK version:**
'MapboxNavigation', '~> 0.31.0'

**Comment by sridharnatarajan89** [comment]
```
0   MapboxNavigationNative        	google::protobuf::RepeatedPtrField<navigator::DirectionsIntersection>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<navigator::D... + 12 (repeated_field.h:1523)
1   MapboxNavigationNative        	google::protobuf::RepeatedPtrField<navigator::DirectionsIntersection>::Get(int) const + 12 (repeated_field.h:1989)
2   MapboxNavigationNative        	navigator::DirectionsStep::intersections(int) const + 12 (directions.pb.h:5921)
3   MapboxNavigationNative        	navigator::NavigatorImpl::Predict(navigator::NavigationStatus&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > > ... + 1684 (navigator_impl_status.cpp:738)
4   MapboxNavigationNative        	navigator::NavigatorImpl::BearingOnShape(unsigned long) const + 68 (navigator_impl_status.cpp:754)
5   MapboxNavigationNative        	navigator::NavigatorImpl::Predict(navigator::NavigationStatus&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > > ... + 1560 (navigator_impl_status.cpp:727)
6   MapboxNavigationNative        	navigator::NavigatorImpl::getStatus(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > > const&) + 1272 (navigator_impl_status.cpp:267)
7   MapboxNavigationNative        	-[MBNavigator getStatusForTimestamp:] + 124 (MBNavigator+Private.mm:99)
```

**Comment by 1ec5** [comment]
Thanks for this crash report! Are you able to reproduce this issue consistently? How about in a newer version of MapboxNavigation? MapboxNavigation v0.31.0 used MapboxNavigationNative 6.1.1, which is very old. MapboxNavigation v0.40.0 uses MapboxNavigationNative v6.2.1, and MapboxNavigation v1.0.0-rc.4 uses MapboxNavigationNative v18.0._x_. If you’re running into this crash consistently, I’d try it in v1.0.0-rc.4 or newer, since we could’ve fixed the issue in the interim in a rewrite.

/cc @mapbox/navnative

**Comment by sridharnatarajan89** [comment]
We are still facing the crash in MapboxNavigation version 0.40.0 also. Please update on this.

**Comment by zugaldia** [comment]
@sridharnatarajan89 I agree with the re commendation from @1ec5 above https://github.com/mapbox/mapbox-navigation-ios/issues/2647#issuecomment-696971675. We'd recommend upgrading to any 1.x release that includes a newer version of navigation native that possibly addresses the issue and that we're actively maintaining. Our ability to reproduce issues in the older 0.x series is limited. Let us know if you run into any issues upgrading, we'd be happy to assist you.

**Comment by sridharnatarajan89** [comment]
Thanks @zugaldia, I tried to use 1.1 version. But I am getting **RouteStatus is MBRouteStateInvalid** always. Please check the below issue  https://github.com/mapbox/mapbox-navigation-ios/issues/2767

**Comment by zugaldia** [comment]
Thanks @sridharnatarajan89 for trying v1.1 and for opening #2767 (I'll follow up on that one separately). 

About this crash, would you be able to share the crash logs you're getting with v1.1 and any additional information we could use on our end to reproduce the issue? (coordinates, history files, small project set up...).
