### ISSUE TITLE
Route line obscures labels and shields

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2657]
Calling `NavigationMapView.show(_:legIndex:)` places the route line above any labels and shields, obscuring them:

![labels](https://user-images.githubusercontent.com/1231218/94454944-630d3000-0167-11eb-9192-5f30f6a316a6.jpeg)

Reproduces in navigation SDK v1.0.0-rc.5 with map SDK v6.2.1. Does not reproduce in navigation SDK v1.0.0-rc.4 with map SDK v6.1.0.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
It’s unlikely that any [changes in v1.0.0-rc.5](https://github.com/mapbox/mapbox-navigation-ios/compare/v1.0.0-rc.4...v1.0.0-rc.5) would’ve caused this regression. This could maybe be fallout from mapbox/mapbox-gl-native-ios#463: MGLMapView’s built-in symbol layer for point annotations might get in the way of the logic for determining where to put the route line, but I’m unsure right now.

**Comment by asinghal22** [comment]
cc: @hbahlool FYI

**Comment by 1ec5** [comment]
> This could maybe be fallout from mapbox/mapbox-gl-native-ios#463: MGLMapView’s built-in symbol layer for point annotations might get in the way of the logic for determining where to put the route line, but I’m unsure right now.

Never mind, I crossed some wires. This method would only be called long after style load, so mapbox/mapbox-gl-native-ios#463 is definitely unrelated.

**Comment by 1ec5** [comment]
I believe this is an issue specific to the Example application and any application based on it. It has been present ever since #2410. I had mistakenly narrowed the issue down to v1.0.0-rc.4 versus v1.0.0-rc.5 because the application I tested v1.0.0-rc.4 in did not implement PassiveLocationManager, while the application I tested v1.0.0-rc.5 in did implement that feature.

#2410 added a demonstration of PassiveLocationManager that plots the user’s raw and snapped location track on the main map. It uses polyline annotations instead of raw line layers, because that allows MGLPolyline to manage updates to the shape geometry with minimal code overhead:

https://github.com/mapbox/mapbox-navigation-ios/blob/e810a461d571083ed9682a8d6302bf27815c9415/Example/ViewController.swift#L616

(This is all that’s required to extend the tracks to include each new location update:)

https://github.com/mapbox/mapbox-navigation-ios/blob/e810a461d571083ed9682a8d6302bf27815c9415/Example/ViewController.swift#L612-L613

Unlike line layers, shape annotations are always placed at the top of the layer stack, with no option to insert the annotation layer below another layer: mapbox/mapbox-gl-native#991. This means the layer stack ends up looking something like this:

```
  [0] = "com.mapbox.annotations.points"
  [1] = "com.mapbox.annotations.shape.1"
  [2] = "com.mapbox.annotations.shape.0"
  [3] = "country-label"
  [4] = "state-label"
  [5] = "settlement-label"
…
```

The tried-and-true algorithm for automatically inserting the route line in the layer stack looks for the first non-symbol layer and inserts the route line above that layer:

https://github.com/mapbox/mapbox-navigation-ios/blob/e810a461d571083ed9682a8d6302bf27815c9415/MapboxNavigation/NavigationMapView.swift#L532-L537

Normally, that would be above the roads but below the road labels. However, in this case, that would end up being between `com.mapbox.annotations.shape.0` and `country-label`.

To make the method safe to call multiple times on the same style, this algorithm specifically skips any layer added by the navigation SDK:

https://github.com/mapbox/mapbox-navigation-ios/blob/e810a461d571083ed9682a8d6302bf27815c9415/MapboxNavigation/NavigationMapView.swift#L523-L529

A simple fix would be to also skip over any annotation layer.

**Comment by zugaldia** [comment]
@1ec5 Thanks for the quick investigation - I concur with the recommended next steps. v1.0.1 (or v1.1 depending on timing) continue to be a safe target for resolving this ticket.
