### ISSUE TITLE
Minimum deployment target warnings when linting CocoaPods podspec with Xcode 12

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2666]
Xcode 12 raises build warnings about invalid minimum deployment targets in the project that CocoaPods generates. These warnings also cause CocoaPods to reject any attempt to push the MapboxCoreNavigation or MapboxNavigation pod to CocoaPods trunk.

These warnings are in addition to the linker error reported in #2665.

## Problem details

To validate the fix in #2662 for the CocoaPods linter error in https://github.com/mapbox/mapbox-navigation-ios/pull/2646#issuecomment-699028278, I tried pushing to a throwaway pod on CocoaPods trunk and ran into errors doing so with the combination of CocoaPods 1.10.0.rc.1 and Xcode 12:

```
$ pod trunk push test-1ec5-MapboxCoreNavigation.podspec 
Updating spec repo `trunk`
Validating podspec
 -> test-1ec5-MapboxCoreNavigation (1.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Polyline' from project 'Pods')
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'MapboxMobileEvents' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

[!] The spec did not pass validation, due to 1 error.
```

## Workaround

As a temporary workaround, I `xcode-select`ed Xcode 11.7 and tried again, this time successfully: CocoaPods/Specs@23ef62369f96659bc1c80a64ca3615509eabb329.

```
$ pod trunk push test-1ec5-MapboxCoreNavigation.podspec --allow-warnings
Updating spec repo `trunk`
Validating podspec
 -> test-1ec5-MapboxCoreNavigation (1.0.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Polyline' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'MapboxMobileEvents' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Turf' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'MapboxDirections' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'test-1ec5-MapboxCoreNavigation' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

Updating spec repo `trunk`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  test-1ec5-MapboxCoreNavigation (1.0.0) successfully published
 📅  September 29th, 18:13
 🌎  https://cocoapods.org/pods/test-1ec5-MapboxCoreNavigation
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

## Solution

The recommendation in https://github.com/CocoaPods/CocoaPods/issues/9884#issuecomment-695083729 is for each pod author to increase the minimum deployment target from iOS 8.0 to iOS 9.0 or above. Of the navigation SDK’s dependencies and transitive dependencies, two currently have a minimum deployment target of iOS 8.0:

* [x] [Polyline](https://github.com/raphaelmor/Polyline/blob/8f7facc6a6fba33bc5ba7715667c18eb98b31001/Polyline.podspec#L62-L65): fixed in raphaelmor/Polyline#63, slated for v5.0.0
* [x] MapboxMobileEvents: fixed in mapbox/mapbox-events-ios#250 for [v0.11.0-beta.1](https://github.com/mapbox/mapbox-events-ios/releases/tag/v0.11.0-beta.1), slated for v0.10.5

~~The MapboxMobileEvents fix is awkward: currently the navigation SDK depends on v0.10.2–v0.10._x_, but the fix is scheduled to land in v0.11.0. We can easily make the SDK compatible with v0.10.2–v0._x_ for CocoaPods users, but [due to a Carthage design decision](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement), it isn’t possible to be compatible with that range of releases for Carthage users. We’d like to keep the MapboxMobileEvents dependency consistent between package managers if possible.~~

/cc @mapbox/navigation-ios @mapbox/mobile-telemetry-ios @frederoni @nagineni

**Comment by 1ec5** [comment]
> The MapboxMobileEvents fix is awkward: currently the navigation SDK depends on v0.10.2–v0.10._x_, but the fix is scheduled to land in v0.11.0. We can easily make the SDK compatible with v0.10.2–v0._x_ for CocoaPods users, but [due to a Carthage design decision](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement), it isn’t possible to be compatible with that range of releases for Carthage users. We’d like to keep the MapboxMobileEvents dependency consistent between package managers if possible.

MapboxMobileEvents v0.11.0 will be released as v0.10.5 instead, so the navigation SDK will automatically pull in the fix for the warning in MapboxMobileEvents.

**Comment by 1ec5** [comment]
Now that MapboxMobileEvents v0.10.5 is released, the only library left causing this warning is Polyline: raphaelmor/Polyline#62.

**Comment by MaximAlien** [comment]
@1ec5, PR which increases minimum deployment targets can be found here: https://github.com/raphaelmor/Polyline/pull/63.

**Comment by 1ec5** [comment]
raphaelmor/Polyline#63 has landed in master, but I’ll leave this issue to track upgrading mapbox-directions-swift to Polyline v5.0.0 once it’s out.
