### ISSUE TITLE
Cannot archive, corrupted or unreadable

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-navigation-ios#2677]
After upgrading Navigation SDK to version 1.0.0 I cannot archive anymore. Archive is successful but I can't find it on the Organizer. force opening it from finder gives an error: Archive is corrupted or unreadable. 
If I downgrade navigation to v.0.39.0 it works again.

**Mapbox Navigation SDK version: v1.0.0**

**Comment by 1ec5** [comment]
I haven’t been able to reproduce this issue in Xcode 12. Which version of Xcode are you using? Do you see anything from Xcode in your system log from around the time you archive the application?

What are you force-opening from within Finder: an .ipa or an .xcarchive? .xcarchive is a bundle format, so you should be able to right-click and choose Show Package Contents, since it’s an ordinary folder.

**Comment by MarcoCarnevali** [comment]
@1ec5 thank you for helping me.. It seems that it's something related to CocoaPods 1.10. I'll open a ticket there. 
Do you have any inputs on how to use navigation sdk 1.0 with CocoaPods 1.9.3 ?

**Comment by 1ec5** [comment]
With CocoaPods 1.9.3, you’d run into CocoaPods/CocoaPods#10026. It might be possible to apply the fix yourself in a local working copy of CocoaPods, but these issues are all related, so I wouldn’t be very confident about getting 1.9.3 to work.

**Comment by MarcoCarnevali** [comment]
Problem fixed, thank you for your help! https://github.com/CocoaPods/CocoaPods/issues/10135

**Comment by byvalentino** [comment]
At the following link a description of how to replicate.
In my case, just add the following package to the Podfile, prevent Archiving the App, which compiles, builds, and runs on a real device. Archive generated, however, are corrupted and do not show on the Organizer. Multiple versions of Cocoapods, Xcode, and macOS, tried without success.

pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

https://github.com/CocoaPods/CocoaPods/issues/10135#issuecomment-730722345
