### ISSUE TITLE
Only send departure and arrival events about leg-separating waypoints

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2688]
NavigationEventsManager should only send a departure or arrival event when departing from or arriving at a waypoint whose `separatesLegs` property is `true`. There doesn’t seem to be such a check at the moment, so these events get fired even for silent “via” waypoints:

https://github.com/mapbox/mapbox-navigation-ios/blob/e8abb39222563efc56d4721bb25a0167fba95091/MapboxCoreNavigation/NavigationEventsManager.swift#L374-L377 https://github.com/mapbox/mapbox-navigation-ios/blob/e8abb39222563efc56d4721bb25a0167fba95091/MapboxCoreNavigation/RouteController.swift#L291-L299 https://github.com/mapbox/mapbox-navigation-ios/blob/e8abb39222563efc56d4721bb25a0167fba95091/MapboxCoreNavigation/LegacyRouteController.swift#L323-L327

/ref mapbox/mapbox-navigation-android#3164
/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
I did check provided code points and it didn't hit them with a silent waypoint. Is there any more exotic way to reproduce it then marking "middle" waypoint `separatesLegs = false`?

**Comment by Udumft** [comment]
I did a code check and found that all events sends are dependent on `legProgress.remainingSteps` which in it's turn is calculated from incoming `legs` data. Thus, silent waypoints are accounted automatically when route is split by `legs` and event sending code is not triggered.
