### ISSUE TITLE
I keep getting "curl: (22) The requested URL returned error: 401 Unauthorized" when trying to install the pod

### ISSUE THREAD

**Issue by atomicpartyIT** [mapbox/mapbox-navigation-ios#2692]
I have read many tutorials and cannot seem to pin down the issue I do have the .netrt file in the build folder when running and it still reads unauthorized. How do we fix this?

Downloading dependencies
Installing Mapbox-iOS-SDK (6.2.1)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/ld/4nl9mlr57jv9ztcy354jzp7w0000gn/T/d20201013-65282-1rdedim/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.2.1/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized

**Comment by 1ec5** [comment]
Hi, thanks for taking the navigation SDK for a spin! The .netrc file should be in your home directory (`~` on the command line, or use Go ‣ Home in Finder). If it’s located anywhere else, CocoaPods is unable to use it when connecting to the Mapbox Downloads API, so the API returns a 401 error.

**Comment by atomicpartyIT** [comment]
Thanks for following up. I have done that and ensured my key matches my
account and that the .netrc file per the documentation and i am still
having the issue.

**Comment by atomicpartyIT** [comment]
the .netrc file is as follows 

"
machine api.mapbox.com
login mapbox
password <API Secret Key>

"

**Comment by atomicpartyIT** [comment]
I figured it out, when I was using terminal I was typing 
`vi .netrc ` to create the file and it added an extension of .swp at the end so it didn't work. I resolved the issue by entering as follows to create and open the file. Im not sure if this is due to the Mac OS Catalina update or not but we are good to go! Thanks!
`% touch .netrc
  % open .netrc
`

**Comment by iiasceri** [comment]
> .net

Your answer explained it better than their own documentation, thank you spent like stupid 1 hour looking into this

**Comment by Beltry201** [comment]
> I figured it out, when I was using terminal I was typing
> `vi .netrc ` to create the file and it added an extension of .swp at the end so it didn't work. I resolved the issue by entering as follows to create and open the file. Im not sure if this is due to the Mac OS Catalina update or not but we are good to go! Thanks!
> `% touch .netrc`
> `% open .netrc`

Where exactly did you store de .netrc inside the flutter project folder?

**Comment by ZumelzuR** [comment]
> > I figured it out, when I was using terminal I was typing
> > `vi .netrc ` to create the file and it added an extension of .swp at the end so it didn't work. I resolved the issue by entering as follows to create and open the file. Im not sure if this is due to the Mac OS Catalina update or not but we are good to go! Thanks!
> > `% touch .netrc`
> > `% open .netrc`
> 
> Where exactly did you store de .netrc inside the flutter project folder?

"Your secret token enables you to download the SDK directly from Mapbox. To use your secret token, you will need to store it in a .netrc file in your home directory (not your project folder). This approach helps avoid accidentally exposing your secret token by keeping it out of your application's source code. Depending on your environment, you may have this file already, so check first before creating a new one."

-- https://docs.mapbox.com/ios/maps/guides/install/

Should be in your home folder

**Comment by johhansantana** [comment]
For anyone wondering where's your home folder:

`/Users/<your username>/.netrc`
