### ISSUE TITLE
`NavigationViewController.indexedRoute` is inaccessible due to its protection level

### ISSUE THREAD

**Issue by dmitry-yashkin** [mapbox/mapbox-navigation-ios#2701]
https://github.com/mapbox/mapbox-navigation-ios/blob/5055b7399b4ba2b51157c050a39c0c4cb5217b07/MapboxNavigation/NavigationViewController.swift#L30

According to [docs](https://docs.mapbox.com/ios/navigation/api/1.0.0/) this property should be used to update a route and so it should be `public`:

> The NavigationViewController.route and NavigationService.route properties are now read-only. To change the route that the user is traveling along, set the NavigationViewController.indexedRoute or NavigationService.indexedRoute property instead, pairing the route with the index of the route in the original RouteResponse object. (#2366)

Is it a bug or I just try to use the SDK in a wrong way?

**Comment by 1ec5** [comment]
Looks like an oversight on our part, introduced in #2366.
