### ISSUE TITLE
Route alternatives should include a callout showing estimated duration of each route

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2702]
If there are multiple possible routes returned and we are presenting the alternatives to the user, it would be great if each route is annotated with a callout showing it's estimated duration. This will help the user choose the best one for them.

If there is additional information available, like delays or tolls along the route it would be great to include that as well.

**Comment by avi-c** [comment]
Support for this was added for Nva SDK v1.2 here: https://github.com/mapbox/mapbox-navigation-ios/pull/2734

Awaiting port to v2.0, which is currently blocked by https://github.com/mapbox/mapbox-maps-ios/issues/172

Could workaround the blocker by using multiple symbol style layers but I don't want to go down that route until we discuss it more.

**Comment by nishant-karajgikar** [comment]
https://github.com/mapbox/mapbox-maps-ios/issues/172 will be fixed by https://github.com/mapbox/mapbox-maps-ios/pull/185

**Comment by 1ec5** [comment]
This feature is being implemented in #2873.

**Comment by 1ec5** [comment]
Fixed in #2734 and #2873.
