### ISSUE TITLE
App keeps getting rejected because of "Non-public API usage" in MapboxNavigationNative

### ISSUE THREAD

**Issue by melvinmt** [mapbox/mapbox-navigation-ios#2720]
**Mapbox Navigation SDK version: 1.0.0**

**Mapbox Navigation Native SDK version: 18.0.5**
> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/MapboxNavigationNative.framework/MapboxNavigationNative: appBuildNumber, getVersionString, userAgentComponents. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
> 

Does anyone know how to resolve this? All my builds are getting rejected by the App Store because of this issue.

**Comment by melvinmt** [comment]
update: also tried it with the latest beta `v1.1.0-beta.2`  but having the same issue

**Comment by 1ec5** [comment]
We’ve seen the same thing intermittently with an internal dogfooding application on TestFlight. As far as I can tell, upgrading to CocoaPods 1.10.0.rc.1 or above should fix the issue. Let us know if the issue persists after upgrading CocoaPods (including in your Gemfile, if you have one).

**Comment by melvinmt** [comment]
@1ec5 thanks, that worked!
