### ISSUE TITLE
Automatically hide "enable precise location" banner

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-navigation-ios#2723]
[#2693 ](https://github.com/mapbox/mapbox-navigation-ios/pull/2693) prompts the user (running iOS 14) to enable precise location to navigate. Currently, the banner hides after 20 seconds. However, it would be better if the accuracy authorization banner persists until precise location is enabled, then automatically hides.

We are already able to observe the notification for a change of accuracy authorization. `StatusView.hide(delay:animated:)` needs to be exposed and used in `NavigationViewController.navigationServiceDidChangeAuthorization(_ service:didChangeAuthorizationFor:)` to hide the authorization accuracy banner at the right time.

**Comment by truburt** [comment]
@jill-cardamon and this one - can close?

**Comment by jill-cardamon** [comment]
yep! will close today for 1.3

**Comment by 1ec5** [comment]
Fixed in mapbox/mapbox-navigation-ios#2747.
