### ISSUE TITLE
framework not found MapboxCommon.xcframework

### ISSUE THREAD

**Issue by samuelail** [mapbox/mapbox-navigation-ios#2729]
**Mapbox Navigation SDK version:** 

MapboxNavigation 1.0

I am building an app that requires the MapboxNavigation library . I already have the MapboxDirections.swift ~> 0.9 and Mapbox-iOS-SDK installed using cocoa pods and they work fine. Once I add the MapboxNavigations library however, I get that error when I attempt to build the project.  My project's deployment target is iOS 13.0 and swift version is swift 5 . Any help will be greatly appreciated.

**Comment by 1ec5** [comment]
The “MapboxDirections.swift” pod is deprecated. Please replace it with the “MapboxDirections” pod. (CocoaPods trunk offers no way to rename a pod, so deprecating the old name is the best we can do.) To avoid any potential version mismatches in the future, you can remove the MapboxDirections line from your Podfile outright, relying on the MapboxNavigation pod to pull in the version of MapboxDirections that it needs.

**Comment by 1ec5** [comment]
If you continue to encounter this error after fixing your Podfile, you may need to upgrade CocoaPods to the latest release, v1.10, to address a linker error in Xcode 12.

**Comment by samuelail** [comment]
I appreciate your response. I’ve done these and the issue has been fixed.

**Comment by 1ec5** [comment]
Great to hear!
