### ISSUE TITLE
CocoaPods lint failure — could not find module 'MapboxNavigation' for target 'arm64-apple-ios-simulator' — v1.1.0 not available on CocoaPods trunk

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2739]
I’m unable to push v1.1.0 to CocoaPods trunk because of the following linting error:

```
    /var/folders/cl/8cgpg37n5cl78pjkbpgml94w0000gn/T/CocoaPods-Lint-20201112-87858-1cn1qqt-MapboxNavigation/App/main.swift:1:8: error: could not find module 'MapboxNavigation' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator
    import MapboxNavigation
           ^
    
    Ld /Users/mxn/Library/Developer/Xcode/DerivedData/App-folfjejeyqdekkgzlqcapuxagvpj/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/Binary/App normal i386 (in target 'App' from project 'App')
```

The CocoaPods integration test didn’t catch this error on CI for some reason.

/ref #2674
/cc @mapbox/navigation-ios @frederoni

**Comment by zugaldia** [comment]
What has changed compared to the RC that could be impacting our ability to publish to Cocoapods?

**Comment by 1ec5** [comment]
I’m concerned that this may be fallout from mapbox/mapbox-gl-native-ios#482, which implemented a slightly different workaround for CocoaPods/CocoaPods#10065 CocoaPods/CocoaPods#10104 than #2667. The two settings can conflict, which is why we were hoping to replace the workaround in #2667 with proper support for Apple Silicon via XCFrameworks: #2672.

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native-ios#482 doesn’t appear to be the culprit: `pod spec lint` is even failing if I pin the Mapbox-iOS-SDK dependency to `= 6.2.2`. I wonder if the workaround is even working at all in Xcode 12.1.

**Comment by 1ec5** [comment]
v6.2.1 is unaffected by the linker error, but v6.2.2 and v6.3.0 are affected.

**Comment by 1ec5** [comment]
The podspec for map SDK v6.2.2 doesn’t contain the problematic `EXCLUDED_ARCHS` build setting from mapbox/mapbox-gl-native-ios#482:

https://github.com/mapbox/mapbox-gl-native-ios/blob/ios-v6.2.2/platform/ios/Mapbox-iOS-SDK.podspec

But it’s in the v6.2.2 podspec on CocoaPods trunk:

https://github.com/CocoaPods/Specs/blob/6c5b50f2141de20aa09ef1d7fb2c7eea92715edd/Specs/a/5/9/Mapbox-iOS-SDK/6.2.2/Mapbox-iOS-SDK.podspec.json#L33-L38

The Pods/Mapbox-iOS-SDK/Mapbox-iOS-SDK.{debug,release}.xcconfig that `pod spec lint` generates ends up with this setting:

```sh
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64 arm64e
```

I wonder if mapbox/mapbox-gl-native-ios#482 had been applied manually without being committed anywhere. https://github.com/mapbox/mapbox-gl-native-ios/tree/release-z doesn’t have anything after mapbox/mapbox-gl-native-ios#509.

**Comment by 1ec5** [comment]
The only immediate workaround I know of is to constrain the Mapbox-iOS-SDK dependency to exclude v6.2.2 and above:

```diff
Index: /Users/mxn/hub/mapbox-navigation-ios/MapboxNavigation.podspec
index a9421d5f..416ffba4 100644
--- a/MapboxNavigation.podspec
+++ b/MapboxNavigation.podspec
@@ -44,7 +44,8 @@ Pod::Spec.new do |s|
   s.module_name = "MapboxNavigation"
 
   s.dependency "MapboxCoreNavigation", "#{s.version.to_s}"
-  s.dependency "Mapbox-iOS-SDK", "~> 6.0"
+  s.dependency "Mapbox-iOS-SDK", ">= 6.0.0"
+  s.dependency "Mapbox-iOS-SDK", "< 6.2.2"
   s.dependency "Solar", "~> 2.1"
   s.dependency "MapboxSpeech", "~> 1.0"
   s.dependency "MapboxMobileEvents", "~> 0.10.2" # Always specify a patch release if pre-v1.0
```

However, v6.2.2 contains important fixes like mapbox/mapbox-gl-native-ios#501 and mapbox/mapbox-gl-native-ios#483 that very noticeably impact the navigation SDK. I don’t think we’d be willing to put out a v1.1.0 that effectively regresses #2658.

(This double dependency does lint successfully, demonstrating that CocoaPods allows a dependency to be constrained to avoid a future semver violation without pinning to a specific patch version. However, only CocoaPods and SPM allow this kind of range dependency, not Carthage.)

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native-ios#549 would align the map SDK’s workaround build settings to those of MapboxCoreNavigation, theoretically ensuring compatibility with MapboxNavigation. I pushed the patched podspec under a throwaway pod at CocoaPods/Specs@a1b0a72547bc6cb91a6e9fa21826a84b0ce91f27, as well as a podspec that requires it at CocoaPods/Specs@c641e3076080da07a0007f7b716169e4d08ce140. Unfortunately, in a test project that requires both the test Mapbox-iOS-SDK and test MapboxNavigation pods, simulator builds in Release configuration fail to build because the MapboxNavigation module can’t be found:

```
/path/to/ViewController.swift:3:8: No such module 'MapboxNavigation'
```

The same error arises when importing MapboxCoreNavigation. It’s unclear to me whether this error is due to the punctuated test pod name or whether it’s a fundamental limitation of the workaround.

**Comment by 1ec5** [comment]
I tried removing the hyphens in CocoaPods/Specs@751fdbed0b1fdbe98b14fd24ca0a374e445be9a3, to no avail.

**Comment by 1ec5** [comment]
I tried pushing to the main pod in CocoaPods/Specs@9634dee57a76a13ab21c5de8e2f8c05aa18c632c, and the error persists.

**Comment by mhamzasani** [comment]
Can't run Mapbox Navigation on Apple Silicon Xcode Simulator: Here's the error message: 
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/user/projects/rewr/Pods/MapboxAccounts/MapboxAccounts.framework/MapboxAccounts' for architecture arm64

**Comment by 1ec5** [comment]
@mhamzasani, MapboxAccounts v2.3.1 added M1 simulator support via an XCFramework; can you try updating your dependencies again?

**Comment by mhamzasani** [comment]
> @mhamzasani, MapboxAccounts v2.3.1 added M1 simulator support via an XCFramework; can you try updating your dependencies again?

Yes, updated and issue resolved. Thank you!
