### ISSUE TITLE
Roundabout exit number missing from RouteStep

### ISSUE THREAD

**Issue by FestiFete** [mapbox/mapbox-navigation-ios#2742]
Hi MapBox team,

I'm trying in vain to get the exit number at a roundabout to be able to display it to my user.
I do get the exitNames from a RouteStep but the exitIndex and exitCodes are always nil.

I did set the RouteOptions like below:

```
let routeOptions = RouteOptions(coordinates: coordinates, profileIdentifier: .cycling)
routeOptions.includesSteps = true
routeOptions.includesExitRoundaboutManeuver = true
routeOptions.allowsUTurnAtWaypoint = true
```

I did try to get the info from the NavigationServiceDelegate method below:

```
func navigationService(_ service: NavigationService, didPassVisualInstructionPoint instruction: VisualInstructionBanner, routeProgress: RouteProgress) {

service.router.routeProgress.priorStep?.exitIndex
service.router.routeProgress.upcomingStep?.exitIndex

or

routeProgress.priorStep?.exitIndex
routeProgress.upcomingStep?.exitIndex
}
```

I'm using the latest version of MapBox 1.1.0:

```
  - MapboxAccounts (2.3.0)
  - MapboxCommon (4.0.1)
  - MapboxCoreNavigation (1.0.0):
    - MapboxAccounts (~> 2.3.0)
    - MapboxDirections (~> 1.0)
    - MapboxMobileEvents (~> 0.10.2)
    - MapboxNavigationNative (~> 18.0.5)
    - Turf (~> 1.0)
  - MapboxDirections (1.1.0):
    - Polyline (~> 5.0)
    - Turf (~> 1.0)
  - MapboxMobileEvents (0.10.5)
  - MapboxNavigation (1.0.0):
    - Mapbox-iOS-SDK (~> 6.0)
    - MapboxCoreNavigation (= 1.0.0)
    - MapboxMobileEvents (~> 0.10.2)
    - MapboxSpeech (~> 1.0)
    - Solar (~> 2.1)
  - MapboxNavigationNative (18.0.5):
    - MapboxCommon (= 4.0.1)
  - MapboxSpeech (1.0.0)
```

And I did try with iOS 12 and iOS 14.

I guess it's an issue but I may have misunderstood something.

Thanks

**Comment by 1ec5** [comment]
Can you share an example route that reproduces this problem? (Just the waypoint coordinates is fine.) Also, just to narrow down the issue, is it specific to the cycling profile, or does it also reproduce if you switch to the default `automobileAvoidingTraffic` profile?

**Comment by FestiFete** [comment]
Here is the coordinates:

From
- latitude : 43.60340646081809
- longitude : 1.4596269778820716
To
- latitude : 43.54186809999999
- longitude : 1.5096514

I tried with the default value `automobileAvoidingTraffic` but it's the same behaviour.

**Comment by FestiFete** [comment]
Do you have any updates? @1ec5

**Comment by FestiFete** [comment]
@1ec5 I saw this issue which is similar!

https://github.com/mapbox/mapbox-directions-swift/issues/508

**Comment by S2Ler** [comment]
@FestiFete The issue will be fixed in the next release. Thanks for contribution!

**Comment by S2Ler** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.0.0-beta.22
