### ISSUE TITLE
Female Australian Polly Voice (en-AU)

### ISSUE THREAD

**Issue by billyking991** [mapbox/mapbox-navigation-ios#2754]
I've now received a bunch of upset emails because the female Australian voice is now a male voice.  I know it's silly, but apparently it's important to some people.  The en-IN, en-US, and en-GB voices are all the same as they were before.  Does anyone know why this has happened or how to change it back?

I had previously filed an issue (#2127) to see if I could change the gender and it didn't seem possible.  Well, the gender has definitely changed.  Any help you can give me is greatly appreciated.  Ideally, selecting gender is the best option.  Switching it back to a female voice would also be nice.

**Mapbox Navigation SDK version:**
0.40.0

### Steps to reproduce

 1.  Set Locale to "en-AU"
 2.  Start navigation.
 3.  Voice is now male.

### Expected behavior
It's been a female voice for the last year and a half...basically since I created the app.

### Actual behavior
Voice is now male.

**Comment by 1ec5** [comment]
Thanks for relaying this feedback, @billyking991. We noticed that Amazon Polly recently added a second female Australian English voice, [Olivia](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-polly-launches-new-australian-english-neural-text-to-speech-voice/), so maybe the default has changed from Nicole to Russell as well. We’re internally tracking an update to override the default to Nicole.

In general, for other locales, you should be able to set the [`SpeechOptions.speechGender`](https://github.com/mapbox/mapbox-speech-swift/blob/acc2af5a1eaec29e7da3e2cd02d7dcde7a3df433/Sources/MapboxSpeech/MBSpeechOptions.swift#L60) property to `.female` when making a request from a `SpeechSynthesizer` (from the MapboxSpeech framework). Unfortunately, #1649 means you’d still have to either patch your local copy of the SDK or [write your own SpeechSynthesizing implementation](https://docs.mapbox.com/ios/navigation/examples/custom-voice-controller/) that integrates with MapboxSpeech.

We’re also internally tracking a proposal to extend the Voice API to allow you to specify a specific voice by name, but I don’t know what the timeline on that addition would be.

**Comment by 1ec5** [comment]
@billyking991, we just deployed a server-side fix for the issue so that you should at least be able to request a female voice, if it doesn’t choose the female one by default. Can you double-check whether you get the Olivia voice when setting the locale to Australian English?

/cc @danpaz

**Comment by billyking991** [comment]
Like an old bagel.

I think this has been fine for a while.
