### ISSUE TITLE
Announcements should optionally ignore the hardware mute switch

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-navigation-ios#276]
Our voice announcements handle the hardware mute switch differently:

- Polly ignores it and will always speak.
- The system fallback obeys the mute switch and will not speak if the switch is enabled.

We should consistify this behavior and possibly add a developer-facing setting that controls whether or not the mute switch is ignored.

/cc @ericrwolfe @1ec5

**Comment by ericrwolfe** [comment]
This will be addressed by a volume/mute button #363 along with voice announcements that obey the software mute button over the hardware mute switch #364.

**Comment by bsudekum** [comment]
This occurs now.
