### ISSUE TITLE
Mapbox Annotation View Misplacement in Navigationviewcontroller

### ISSUE THREAD

**Issue by mittalios21** [mapbox/mapbox-navigation-ios#2762]
**Mapbox Navigation SDK version:**

### Steps to reproduce

 1. Added NavigationViewController as child view controller in main viewcontroller and added annotation in mapview of NavigationViewController but annotation not added in route of NavigationViewController as per given coordinate.

### Expected behavior
I want annotation on NavigationViewController's map view on route and main viewcontroller's mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) method is not calling.

[### Actual behavior](url
![SS_Issue](https://user-images.githubusercontent.com/75682237/101497700-42482e80-3991-11eb-971f-21f49d288951.png)
)

**Comment by 1ec5** [comment]
Can you share more of the code you’re using to place the annotation on the map? Unfortunately it isn’t possible to diagnose this issue from the description alone.
