### ISSUE TITLE
Convert Directions API JSON to DirectionsRoute object for Navigation

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#2778]
Hi,

We are planning on building our app using MapBox but we would like to do all the API requests on our backend and simply provide the directions to the app to be visualized using the Navigation SDK for both iOS and Android. However, I have not been able to find a way to convert the JSON response from your Direction API (https://docs.mapbox.com/api/navigation/directions/#use-http-post-to-retrieve-directions) to a DirectionsRoute object that can be passed to the Navigation SDK. Hopefully, you can help me with this.

Thanks!

**Comment by sridharnatarajan89** [comment]
@nastasiupta Did you get any update on this?

**Comment by nastasiupta** [comment]
@sridharnatarajan89  nothing yet...

**Comment by iBinh** [comment]
I think you should have a look at https://github.com/Project-OSRM/osrm-backend
then customize https://github.com/mapbox/mapbox-directions-swift

**Comment by 1ec5** [comment]
If your server API takes input and produces output identical to the Mapbox Directions API, use the [MapboxDirections](https://github.com/mapbox/mapbox-directions-swift/) library like normal but pass your hostname into the `DirectionsCredentials(accessToken:host:)` initializer. If your server API’s request format differs in some way but the response format is the same, use JSONDecoder to [decode a `RouteResponse`](https://docs.mapbox.com/ios/navigation/examples/route-deserialization/). If your server API’s response format also differs, [use the `RouteResponse` initializer](https://docs.mapbox.com/ios/navigation/examples/route-initialization/). Once you have a RouteResponse, you can pass a Route into the navigation SDK like normal.

**Comment by 1ec5** [comment]
I think this has been answered in https://github.com/mapbox/mapbox-navigation-ios/issues/2778#issuecomment-754725723, but feel free to reopen if anything is amiss about this answer.
