### ISSUE TITLE
Refactor monitorStepProgress

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#278]
[`monitorStepProgress(_:)`](https://github.com/mapbox/mapbox-navigation-ios/blob/8e8bb5aa8a626cc13facf66774088b909be07caf/MapboxCoreNavigation/RouteController.swift#L317-L390) has grown unwieldy and would frustrate any attempt to unit test Core Navigation. We should break it up into logical units based on specific decisions being made.

/cc @bsudekum @frederoni

**Comment by 1ec5** [comment]
We may want to hew to mapbox/mapbox-navigation-android#30 when refactoring this method.

**Comment by 1ec5** [comment]
This will happen as part of #282.

**Comment by ericrwolfe** [comment]
This didn't happen as part of #282.
