### ISSUE TITLE
App build is rejected by App Store because of "Non-public API usage" in MapboxNavigationNative

### ISSUE THREAD

**Issue by noway** [mapbox/mapbox-navigation-ios#2784]
**Mapbox Navigation SDK version:** v1.2.0-alpha.3

>Dear Developer,
>
>We identified one or more issues with a recent delivery for your app, "Turnout Navigation & Convoys" 4.4.2 (5). Please correct the following issues, then upload again.
>
>ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/MapboxNavigationNative.framework/MapboxNavigationNative: appBuildNumber, getVersionString, osName, userAgentComponents. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
>
>Best regards,
>
>The App Store Team

I'm having the same issue as #2720, but in my case I'm using Carthage (0.36.0) so updating CocoaPods won't change anything (I'm already on version 1.10.0 which is supposed to be the version on which this issue is resolved, as suggested by @1ec5)

Any way to solve it for Carthage?

**Comment by noway** [comment]
Updated Carthage to 0.36.1 and made a new build, still same issue.

**Comment by 1ec5** [comment]
We’ve seen this issue periodically from the App Store but it seems to be intermittent. MapboxNavigationNative has included a `getVersionString` method for a long time, but it’s completely unrelated to the selector that the App Store intends to reject. In my few run-ins with this error, it has gone away after a few days. I realize this isn’t a great experience for you, so we’re tracking an internal change to rename the method to avoid this error.

**Comment by noway** [comment]
@1ec5 Tried after a few days, still experiencing the same issue. To me this issue is pretty major because it makes the latest version of mapbox navigation complely unusable with Carthage

**Comment by noway** [comment]
Adding this https://github.com/mapbox/mapbox-gl-native-ios/issues/556#issuecomment-731553116 actually seemed to help

**Comment by 1ec5** [comment]
Interesting, we should add that step to the navigation SDK’s installation instructions for good measure. Thank you for your feedback!

**Comment by noway** [comment]
Here's what I did specifically:

I've added a new "Run Script" after "Embed Frameworks (2 items)":
![image](https://user-images.githubusercontent.com/2031472/105780332-13375c00-5fd5-11eb-808e-1b1ef154577a.png)

Script body:
```bash
"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh" MapboxAccounts
"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh" MapboxCommon
```

Script body is something I came up with on my own, I had trouble with signing MapboxAccounts and MapboxCommon, so initially, I was just trying to submit the app with them completely not linked to the binary. Which was a bad idea to begin with, because when I tried running the app with Ad-Hoc Deployment, the app was crashing on launch. The crashing build was the one rejected by App Store with the "Non-public API usage" error. When I linked & stripped MapboxAccounts and MapboxCommon, everything magically worked and the build got accepted. Not sure if stripping MapboxAccounts & MapboxCommon frameworks and the Non-public API usage errors are related.

**Comment by rossmartin** [comment]
Thank you @noway for opening this issue and thank you @1ec5 for the response. We are facing this issue as well and have been unable to solve it no matter what version of cocoapods we use. We also tried the suggestion in the previous comment by @noway. I suspect that was coincidence for why it worked.

We are trying to get a build ready for testing and every binary we submit is being invalidated because of this same issue.  We're coming up close on a deadline and REALLY need this `1.3.0` version to have this resolved and released as soon as possible.

**Comment by 1ec5** [comment]
Hi @rossmartin @noway, we understand that this is an urgent issue for you. We’re trying to get everything lined up for a patch release as soon as possible. (It’ll be a patch release of the navigation SDK as well as a couple of its dependencies, because the ostensibly offending symbol is down in MapboxCommon.) I don’t have a precise timeline for the patch release, but it’s the highest priority for us at the moment. In the meantime, I’d suggest retrying the submission periodically, because I’ve personally seen the buggy validation error come and go on its own for no apparent reason.

**Comment by rossmartin** [comment]
Thank you for getting this resolved. Will `v1.2.1` be published to cocoapods soon? Your changelog shows `v1.2.1` but it doesn't appear to be available - https://github.com/mapbox/mapbox-navigation-ios/blob/main/CHANGELOG.md#v121

**Comment by 1ec5** [comment]
Thanks for your patience – v1.2.1 is now available on CocoaPods trunk as of CocoaPods/Specs@652f62bf9390366c060a38b1249190fad44e8094 and CocoaPods/Specs@184f235a2eec38c1a27fdb2fe0d96594a6dbee5c. Please let us know if the issue persists for you after upgrading, performing a clean build, and resubmitting.

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  MapboxCoreNavigation (1.2.1) successfully published
 📅  February 2nd, 15:39
 🌎  https://cocoapods.org/pods/MapboxCoreNavigation
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  MapboxNavigation (1.2.1) successfully published
 📅  February 2nd, 16:31
 🌎  https://cocoapods.org/pods/MapboxNavigation
 👍  Tell your friends!
--------------------------------------------------------------------------------
```
