### ISSUE TITLE
Revisit how route duration annotations are laid out once Nav SDK adopts newer Maps SDK.

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2785]
This issue tracks the tail work needed to improve the robustness of the layout code used in #2734.

The hope is that changes in the Maps SDK will give us more information about the visual state of the Map and that we can use this information to better inform the placement of annotations along a visible route line.

**Comment by 1ec5** [comment]
> changes in the Maps SDK

This is a reference to map SDK v10: #2794.
