### ISSUE TITLE
Feedback UI always appears for short routes

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2786]
**Mapbox Navigation SDK version: 1.1.0 and 1.2.0-rc.1**

_This is similar to https://github.com/mapbox/mapbox-navigation-ios/issues/2056, but I'm filing anew since that one is stale._

### Steps to reproduce

 1. Initialize a `NavigationViewController` with a very short route, one where you're basically on the destination.
 2. Immediately after the initializer, set `showsReportFeedback` to false.
 3. Show the `NavigationViewController`.

```Swift
let route: IndexedRoute = ...
let navigationViewController = NavigationViewController(
    for: route.0,
    routeIndex: route.1,
    routeOptions: routeOptions,
    navigationOptions: navigationOptions
)
navigationViewController.showsReportFeedback = false
...
// embed or show the navigationViewController
```

### Expected behavior

When the `NavigationViewController` is presented, there will be no feedback UI on screen because `showsReportFeedback` was set to false.

### Actual behavior

The [`navigationService(_:, didArriveAt:)`](https://github.com/mapbox/mapbox-navigation-ios/blob/v1.1.0/MapboxNavigation/NavigationViewController.swift#L626) delegate method within `NavigationViewController` is firing during the initializer, which presents the end of route feedback before the assignment to `showsReportFeedback` (or `showsEndOfRouteFeedback`) is applied.

I know this is a bit of an edge case because it only happens for short routes, but any advice on how to avoid this would be greatly appreciated! The feedback UI doesn't match our app's branding and we'd like to avoid presenting it. This wasn't an issue in SDK 0.39.0, which is what I'm upgrading from.

I'm not able to override the `showEndOfRouteFeedback(duration:, completionHandler:)` extension method, nor can I override the `showsEndOfRouteFeedback` or `showsReportFeedback` variables.

**Comment by johnnewman** [comment]
Because this happens during the initializer, the delegate of `NavigationViewController` hasn't been set yet. The client implementation misses the call to `navigationViewController(_:, didArriveAt:)` which is fired [here](https://github.com/mapbox/mapbox-navigation-ios/blob/v1.1.0/MapboxNavigation/NavigationViewController.swift#L629). That delegate is what I'm hooking to show my custom arrival state UI.

It's not great, but I've created a hack to detect this case, manually hide the feedback view, and manually fire the delegate with the last waypoint.
```Swift
// After showing the NavigationViewController
...
let subviews: [UIView] = // recurse through all subviews of navigationViewController
subviews.forEach {
    if $0 is EndOfRouteContentView {
        // Manually hide the feedback view.
        $0.isHidden = true

        // Manually trigger our delegate implementation (which we hook to detect the arrival state)
        if let lastWaypoint = route.legSeparators.last as? Waypoint {
            let _ = self.navigationViewController(navigationViewController, didArriveAt: lastWaypoint)
        }
    }
}
```

Thanks in advance for assistance with this!

**Comment by bramseynhaeve** [comment]
Thanks @johnnewman for the clear information. We have the exact same issue in our code base, but don't want to apply this little hack.

A fix from Mapbox would be great
