### ISSUE TITLE
Shield image is not downloaded from AWS

### ISSUE THREAD

**Issue by gfoldv** [mapbox/mapbox-navigation-ios#2788]
AWS gives back 403 HTTP error when the library tries to download the shield image. It can be easily reproduced in the example app - https://github.com/mapbox/navigation-ios-examples - by running the Basic example between 
let origin = CLLocationCoordinate2DMake(37.7370482, -122.2170117)
let destination = CLLocationCoordinate2DMake(37.493201, -119.972146)

Mapbox Navigation SDK version: 1.0 pulled in the navigation-ios-examples project

**Comment by 1ec5** [comment]
Unfortunately, this is a known issue: the default Directions API endpoint returns URLs to shield images that were deleted last year.

/cc @mandeepsandhu

**Comment by mandeepsandhu** [comment]
@gfoldv the shield urls have been fixed (the shield images were moved to a different location on AWS). Can you try again and let us know if its working for you or not?

CC: @1ec5

**Comment by gfoldv** [comment]
It works. Thank you!
