### ISSUE TITLE
Mocked tests don’t run under Swift Package Manager

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2792]
#2771 excluded a number of Core Navigation integration tests when implementing Swift Package Manager support. These tests depend on TestHelper, primarily to load test fixtures. We’ll probably have to break up TestHelper into at least two targets: it includes Objective-C headers and also includes some mocks that depend on MapboxNavigation, which does not yet support SPM.

Here are the affected test suites in MapboxCoreNavigationTests:

* LocationTests
* MapboxCoreNavigationTests
* MapboxNavigationServiceSpec
* NavigationEventsManagerTests
* NavigationServiceTests
* OfflineRoutingTests
* PassiveLocationDataSourceTests
* RouteProgressTests (partial)
* TunnelAuthorityTests

There will be other affected test suites in MapboxNavigationTests once MapboxNavigation supports SPM. Some of these test suites may need to be rewritten first due to dependencies on testing frameworks that don’t support SPM: #2791. The gap in test coverage is similar to mapbox/mapbox-directions-swift#494, but this repository’s tests don’t depend on OHHTTPStubs and don’t need to support watchOS.

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
This issue is fixed by #2911
