### ISSUE TITLE
Dual-use lane icons are highlighted incorrectly

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2796]
In the lane view that appears below the turn banner, the icon for a dual use lane – a lane that can be used for multiple maneuvers – is highlighted incorrectly.

## Problem

If the user is supposed to continue straight at an intersection and one of the lanes can be used for going straight or turning right, the lane icon is highlighted as if the user is supposed to turn right from that lane.

## Diagnosis

6dc222c618602561504378a2be790d2dc2d840d5 for #1514 removed the ability for LaneView to know the corresponding step’s maneuver direction. Instead, the drawing code takes the maneuver direction from the lane’s own turn indications. If a turn lane can be used for two different maneuvers, then LaneView tries to convert the JSON representation of the array of maneuvers into a ManeuverDirection, which fails. The resulting `nil` value causes us to fall back to a code path that, by process of elimination, is implicitly meant for highlighting the right turn maneuver on a straight-right lane:

https://github.com/mapbox/mapbox-navigation-ios/blob/b6d3a3acbd7c67f75878e7b6a7905a64c41211ad/MapboxNavigation/LaneView.swift#L84 https://github.com/mapbox/mapbox-navigation-ios/blob/b6d3a3acbd7c67f75878e7b6a7905a64c41211ad/MapboxNavigation/LaneView.swift#L126-L128

## Solution

We need to restore the `direction` argument that 6dc222c618602561504378a2be790d2dc2d840d5 removed from LaneView’s initializer and populate it with the step’s maneuver. Because the step went unused after this change, LanesView’s ability to pass in a step also atrophied. We‘ll also need to add a `direction` argument to `LanesView.update(for:)`, to be populated by the upcoming step.

This issue went unnoticed for a long time because of a sprawling nest of conditionals with implicit fallbacks and no assertions. We should take this opportunity to reorganize `LaneView.draw(_:)` with a pattern-matching `switch` statement on a tuple that combines `indications` with `maneuverDirection`.

/cc @mapbox/navigation-ios @avi-c @abhishek1508

**Comment by avi-c** [comment]
A reproducible route is one with these coordinates:
Origin: latitude: 37.783574, longitude: -122.403181
Destination: 37.691817, longitude: -122.468033

Things to note. The first visual instruction on that route will render essentially correctly. It shows that you should use the 2 middle lanes to turn slight right onto the freeway onramp as seen on this screenshot:

![Correct Straight-Right combo arrow](https://user-images.githubusercontent.com/10037825/106666913-12667300-655d-11eb-94fa-e0d34fa7c4ac.png)

The second visual instruction on that route will render incorrectly. It is attempting to describe that you should use one of the 3 left-most lanes to continue straight. The screenshot shows the error, where the middle lane indicates that you should turn right.

![Incorrect Straight-Right combo arrow](https://user-images.githubusercontent.com/10037825/106667059-42ae1180-655d-11eb-8603-d5473f494d81.png)

**Comment by 1ec5** [comment]
mapbox/mapbox-directions-swift#516 would add a new property to Intersection that explicitly indicates which LaneIndication is appropriate to highlight. #2798 demonstrates that we don’t really need this property, but we can make good use of it in a future iteration that narrows down the highlights to just the preferred lane(s).

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-android#3934 tracks the same symptom but with a different root cause.

**Comment by 1ec5** [comment]
> #2798 demonstrates that we don’t really need this property most of the time, but we can make good use of it in a future iteration that narrows down the highlights to just the preferred lane(s).

Tracking the more robust fix in #2801.

**Comment by 1ec5** [comment]
#2809 rewrote the lane selection logic to handle more edge cases in a more maintainable way.
