### ISSUE TITLE
Refactor voice controller

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-navigation-ios#280]
Factor out AV and Polly from RouteVoiceController. 

OOP - RouteVoiceController, AVVoiceController, PollyVoiceController
or
POP - Speakable protocol.

This will make it easier to make AWSPolly optional when that proposal is implemented.

@1ec5 @bsudekum

**Comment by 1ec5** [comment]
> This will make it easier to make AWSPolly optional when that proposal is implemented.

It’s already possible to make AWSPolly optional for CocoaPods users: as long as we isolate the code that touches Polly into dedicated files, we can modify the podspec to define a subspec with Polly support.

A subspec may sound like a bad idea, given #140, but this is a different situation. In #140, we were trying to make one subspec depend on another (both subspecs being required) and simultaneously keep the two frameworks separate for Carthage users. In this case, we’d have one subspec be optional without any dependency between it and the surrounding spec, and there would only be one framework for Carthage users, same as for CocoaPods users.
