### ISSUE TITLE
Move CMapboxCoreNavigation files up one level

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2800]
Per mapbox/mapbox-events-ios#277, Swift Package Manager 5.4 in Xcode 12.5 beta 1 requires Objective-C headers to reside directly in the target’s directory under the Sources/ directory, rather than under an includes/ subdirectory. We’ll need to move [these files](https://github.com/mapbox/mapbox-navigation-ios/tree/0d2b12de12456f2c2203efbd261f88515277b5b3/Sources/CMapboxCoreNavigation/include) up one level and update the Xcode project and podspecs. It’s unclear to me whether this change will be backwards-compatible with the version of SPM in Xcode 12.4 and below.

/cc @mapbox/navigation-ios @OdNairy

**Comment by frederoni** [comment]
MBXPeerWrapper should already be exposed in recent NavNative builds which could alleviate the need for a CMapboxCoreNavigation target.

Does Xcode 12.5 beta deviate from the 3 cases listed under [Creating C language targets](https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets)?

**Comment by OdNairy** [comment]
@1ec5 Xcode 12.5 beta 1 requires public headers folder (`include/` by default) to have a flat structure without subfolders.
In MME there were `Sources/MapboxMobileEvents/include/MapboxMobileEvents/*.h`
It's totally okay to have headers in the `include/` root.

**Comment by 1ec5** [comment]
> MBXPeerWrapper should already be exposed in recent NavNative builds which could alleviate the need for a CMapboxCoreNavigation target.

You’re right, MapboxNavigationNative v40.0.2 includes MapboxCommon to obviate the forward declaration. I don’t think that change made it into v31.0.0, but eventually we’ll be able to upgrade to v40._x_ as part of upgrading to map SDK v10 (#2794). We won’t quite be able to remove CMapboxCoreNavigation, because of MBXAccounts+CoreNavigationAdditions.h/.m: Swift has no similar way to load code automatically at launch.

**Comment by 1ec5** [comment]
I think v1.4._x_ turned out to be in good shape in Xcode 12.5 after all.
