### ISSUE TITLE
Highlight lanes based on active direction

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2801]
Lane indication icons should be highlighted correctly even at non-four-way-intersections, where the lane indications may not precisely match the overall maneuver’s direction.

## Rationale

Beyond the basic fix for #2796 in #2798, we have an opportunity to make the logic for highlighting turn lane icons more robust. At forks and complex intersections, the lane indications may not literally match the direction of the maneuver. For example:

* [This way](https://www.openstreetmap.org/way/754401923#map=19/37.77953/-122.39832) is tagged `turn:lanes=through|through|through;right|right` based on the turn lane signs and road markings, not `left|left|left;right|right` as a routing engine might infer based on the road geometry. The maneuver onto Bryant Street is considered going straight through, whereas a left turn would end up on 4th Street; this left turn maneuver is prohibited.
* At a fork, the left lanes may go straight, in terms of both road geometry and road markings, but the Directions API still sets the maneuver modifier to `left` so that the main maneuver icon and voice instructions will say “keep left”.

After #2798 lands, these mismatches will cause the lanes in question to be completely unhighlighted, even if they can or should be used for the maneuver.

## Implementation notes

`LaneView.draw(_:)` should consider `Intersection.preferredApproachLanes` and `Intersection.usableLaneIndication` when deciding which part of a lane indication icon to highlight. mapbox/mapbox-directions-swift#516 tracks adding these properties. They’ll depend on the `mapbox/driving` profile, so much of the existing logic in `LaneView.draw(_:)` is still required as a fallback for the Valhalla-based cycling profile and the OSRM-based `mapbox/driving-traffic` profile, though I continue to see this spaghetti code as ripe for a thorough rewrite based on a pattern-matching `switch` statement.

/ref mapbox/mapbox-navigation-android#3935
/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Now that #2809 has landed, the call to `LaneIndication.ranked(favoring:)` in `LaneView.draw(_:)` should pass in the active direction if it’s available, falling back to the existing maneuver direction. Actually, that fallback might happen further up the stack in `LanesView.update(for:)`.

**Comment by 1ec5** [comment]
Like #2882, I don’t think we’ll be able to meaningfully test this feature until we can run MapboxNavigationTests again: #2791.

**Comment by jill-cardamon** [comment]
Fixed in #2942 .
