### ISSUE TITLE
Navigation issue showing long route in iOS

### ISSUE THREAD

**Issue by Chandreshe2logy** [mapbox/mapbox-navigation-ios#2806]
Hi team,

We are getting different navigation in iOS and Android . Android looks correct and iOS showing long navigation .

Current location :- 67 Hartman Dr, Wangara WA 6065, Australia
Destination location :- 36 Lenore Rd, Wanneroo WA 6065, Australia

iOS MapBox Navigation SDK & Pods
**pod 'MapboxNavigation', '~> 1.0'
**SDK Version :- 6.0****

<img width="1398" alt="Screenshot 2021-02-11 at 2 56 55 PM" src="https://user-images.githubusercontent.com/64770544/107619927-ef814080-6c79-11eb-8f69-798f72e1f9b3.png">

![Android iOSScreen](https://user-images.githubusercontent.com/64770544/107620047-193a6780-6c7a-11eb-888b-80eb4252ca5f.jpg)

Please check attachment screen shot for compare iOS and Android. Please provide solutions as soon as possible. its effect to business.

Thanks!

**Comment by avi-c** [comment]
Is this reproducible?

Can you provide more detail about the precise directions request URL sent to the directions API in each case (Android & iOS) and the reply received from the server?

Differences in what was requested are likely the cause of the difference.

Please update with more info if possible.

**Comment by Chandreshe2logy** [comment]
I have changed profile identifier then it's working fine.

Solutions :-
Changed :- automobileAvoidingTraffic To automobile

Thanks
