### ISSUE TITLE
Delegate function didArriveAt waypoint: Waypoint never called

### ISSUE THREAD

**Issue by jcfrk101** [mapbox/mapbox-navigation-ios#2811]
**Mapbox Navigation SDK version:**
6.3.0
### Steps to reproduce

 1. add NavigationViewController as a subview
 2. enable simulation
 3. wait till the simulated location arrives as the destination
### Expected behavior
didArriveAt waypoint: Waypoint is called 
### Actual behavior
didArriveAt waypoint: Waypoint  is not called

**Comment by 1ec5** [comment]
Can you provide an example of a route (and waypoints) that reproduces this issue? Thanks!

**Comment by kried** [comment]
Unable to reproduce
