### ISSUE TITLE
MapView disappears after panning.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2815]
MapView style disappears after panning. For example:

https://user-images.githubusercontent.com/1496498/108547179-038ef880-729f-11eb-8e2c-3dae5eeab59f.mov

Current issue depends on fix provided on Mapbox Maps SDK side reported here: https://github.com/mapbox/mapbox-maps-ios/issues/59.

**Comment by zugaldia** [comment]
https://github.com/mapbox/mapbox-maps-ios/issues/59 is closed. Assuming we are not closed anymore?

**Comment by MaximAlien** [comment]
No longer reproducible. Closing.
