### ISSUE TITLE
Archivation fails for Navigation SDK 2.0 integrated with SPM

### ISSUE THREAD

**Issue by bamx23** [mapbox/mapbox-navigation-ios#2824]
**Mapbox Navigation SDK version:** v2.0.0-alpha.1

### Steps to reproduce

 1. Integrate Mapbox Navigation SDK with SPM using `2.0.0-alpha.1` version
 2. Run "Archive" task in Xcode

### Expected behavior

The app builds with no errors.

### Actual behavior

> /Users/bamx23/Library/Developer/Xcode/DerivedData/MyApp-asddjsghfaiuysdtgfoasdgfoaasfjkasdh/SourcePackages/checkouts/mapbox-navigation-ios/Sources/CMapboxCoreNavigation/include/MBXAccounts+CoreNavigationAdditions.h:1:9: 'MapboxAccounts/MapboxAccounts.h' file not found

<img width="1369" alt="Screen Shot 2021-02-22 at 17 30 12" src="https://user-images.githubusercontent.com/443972/108729764-eb87d500-753b-11eb-8fe6-c15e5fc015a2.png">

**Comment by 1ec5** [comment]
What version of Xcode are you using? I’m able to archive an application that pulls in MapboxNavigation using Xcode 12.4, but for Xcode 12.5, MapboxAccounts may need to move its headers up one directory level, as described in #2800.

**Comment by bamx23** [comment]
It's Xcode 12.5.0 beta 2. I've tried to build with Xcode 12.4, but there is another SDK that requires Xcode 12.5 because of some issue fixed in the latest betas.

**Comment by 1ec5** [comment]
Actually, I only tried archiving in Debug configuration.

**Comment by 1ec5** [comment]
Archiving works as of v2.0.0-alpha.2, which no longer depends on MapboxAccounts. But MapboxCoreNavigation v1._x_ still depends on MapboxAccounts while supporting SPM, so we’ll need to look into this issue anyways.

**Comment by azarovalex** [comment]
I can reproduce this issue, an empty project can't archive with Mapbox Navigation SDK v2.0.0-alpha.1 integrated through SPM.
At the same time versions 1.3.0 and v2.0.0-alpha.2 archive fine.
I suggest that we add an archiving pipeline to our CI, so we can notice such bugs in the future.

**Comment by azarovalex** [comment]
As I mentioned in my last comment, the archivation issue was solved in the next alpha release, so I will close this ticket.
I also created a new issue #2904 to ensure that this problem will not appear in the future.
