### ISSUE TITLE
Upgrade to MapboxNavigationNative v45.x

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2831]
[MapboxNavigationNative v43.x](https://github.com/mapbox/mapbox-navigation-native-ios/releases/tag/43.0.0) is out. Not expecting any significant changes beyond the version bump.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
[v43.0.1](https://github.com/mapbox/mapbox-navigation-native-ios/releases/tag/43.0.1)

**Comment by avi-c** [comment]
There seems to be some changes in the Route Alerts data model that need to be addressed.

**Comment by 1ec5** [comment]
Fixed in #2837 on the release-v2.0 branch for v2.0.0-alpha.3.
