### ISSUE TITLE
Maneuver arrow is sometimes partly visible on iOS and CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2839]
**Mapbox Navigation SDK version:** `2.0.0-alpha.1`

Maneuver arrow is sometimes partly visible on iOS and CarPlay as shown on screenshot:

<img width="297" alt="Screen Shot 2021-02-19 at 1 09 38 PM" src="https://user-images.githubusercontent.com/1496498/109336480-4a896a80-7818-11eb-8be4-79ba07ad3cc3.png">

**Comment by ShanMa1991** [comment]
This issue seems to be fixed. Cannot reproduce the partially visible maneuver arrow bug.
