### ISSUE TITLE
MapView annotation selection doesn't work

### ISSUE THREAD

**Issue by bamx23** [mapbox/mapbox-navigation-ios#2841]
**Mapbox Navigation SDK version:** 2.0.0-alpha.2

### Steps to reproduce

 1. Create NavigationMapView
 2. Set `navigationMapView.mapView.annotationManager.interactionDelegate = self`
 3. Add annotation `navigationMapView.mapView.annotationManager.addAnnotation(PointAnnotation(coordinate: coordinate))`
 4. Tap on the annotation

### Expected behavior

`func didSelectAnnotation(annotation: Annotation)` is called.

### Actual behavior

No delegate method is triggered.

### Suggested solution

I guess a bug is here:
https://github.com/mapbox/mapbox-navigation-ios/blob/bb4cfb6cea1391e88bf2ae6b79b7584fac2621b8/Sources/MapboxNavigation/NavigationMapView.swift#L283

`mapView.gestureRecognizers` should be used instead of `gestureRecognizers`(or a combination of both).

cc: @1ec5 @MaximAlien

**Comment by bamx23** [comment]
Eventually, the suggested solution breaks route selection.

**Comment by 1ec5** [comment]
> Set `navigationMapView.mapView.annotationManager.interactionDelegate = self`

This seems like a responsibility of the map SDK, not the navigation SDK. It does seem like there should be only one interaction delegate in the application overall – should it be the responsibility of the application?

This issue also affects the DocsCode target in navigation-ios-examples, which is used for the “First steps” guide.

**Comment by MaximAlien** [comment]
Route line selection is a regression on Navigation SDK side. @jill-cardamon, can you please check what might be wrong here?

**Comment by jill-cardamon** [comment]
Yep. Already working on it.

**Comment by MaximAlien** [comment]
This is not Navigation SDK issue. Ticket was created on Maps SDK side.

**Comment by jill-cardamon** [comment]
Fixed in [#2909](https://github.com/mapbox/mapbox-navigation-ios/pull/2909).
