### ISSUE TITLE
Shortest Route Showing Alternate Route 

### ISSUE THREAD

**Issue by Chandreshe2logy** [mapbox/mapbox-navigation-ios#2845]
Hi team,

We are getting issue in route. shortest route showing alternate route can you provide me solutions.

Please check code and below screen shot.
Current Address :- 288 Gnangara Rd, Landsdale WA 6065, Australia
Destination Address :-  14 Sturtridge Rd, Lockridge WA 6054, Australia

` guard let routes = response.routes, let strongSelf = self else {
     return
}
strongSelf.routeOptions = routeOptions
strongSelf.routes = routes
strongSelf.mapView?.show(routes)
strongSelf.mapView?.showWaypoints(on: strongSelf.currentRoute!)`

**Android**
![Android_Screen_Shot](https://user-images.githubusercontent.com/64770544/109650765-b1de4c00-7b83-11eb-80a7-baa2846d3a59.png)

**iOS**

![iOS_Screen_Shot](https://user-images.githubusercontent.com/64770544/109650773-b4d93c80-7b83-11eb-95df-9e83cd273ef4.png)

**Google**
![Google_ScreenShot](https://user-images.githubusercontent.com/64770544/109650768-b440a600-7b83-11eb-8046-6e49d45c2e27.png)

**Comment by 1ec5** [comment]
The Directions API generally returns the fastest route (within reason), not necessarily the shortest route. Based on current traffic conditions, the Directions API considered the Tonkin Highway route to be faster.
