### ISSUE TITLE
Migrate to asynchronous navigator status

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2846]
RouteController exposes the current route progress and snapped location synchronously, but MapboxNavigationNative’s Navigator class’s synchronous status accessor is apparently deprecated in favor of an asynchronous, callback-based interface. We’ll need some way to bridge that expectation, perhaps by polling and storing the latest value.

https://github.com/mapbox/mapbox-navigation-ios/blob/0f45ff22cc0702b9d2246bdb113d14aad7f53a37/Sources/MapboxCoreNavigation/Navigator.swift#L5-L9 https://github.com/mapbox/mapbox-navigation-ios/blob/0f45ff22cc0702b9d2246bdb113d14aad7f53a37/Sources/MapboxCoreNavigation/RouteController.swift#L110-L120

/cc @mapbox/navigation-ios

**Comment by Guardiola31337** [comment]
For reference, Android integration is moving in https://github.com/mapbox/mapbox-navigation-android/pull/4093

**Comment by Guardiola31337** [comment]
@Udumft could you take a look at https://github.com/mapbox/mapbox-navigation-android/pull/4093 and confirm if the `RunLoop` approach will work in iOS when you have a chance?

**Comment by Udumft** [comment]
As far as I can understand from Android PR, the approach is to asynchronously observer status updates and store latest data for SDK usage. And yes, such solution is feasible for iOS: we can introduce an observer and store status updates in `RouteController`.

**Comment by Guardiola31337** [comment]
Awesome! Thanks for the update.

I'm also wondering if you can prototype something up and test the iOS artifacts to confirm that the `RunLoop` implementation will work on your side.

cc @DmitryAk

**Comment by Guardiola31337** [comment]
Any updates here @DmitryAk?

**Comment by DmitryAk** [comment]
@Guardiola31337 there are no updates from my side currently, can I help here? Maybe, something iOS-specific is required, and I can provide it in NavNative?

**Comment by Guardiola31337** [comment]
Sorry wrong label, I meant to tag @Udumft 😅

**Comment by Udumft** [comment]
Sorry, this one is not in priority atm, and I had no chance to even try it out.

**Comment by Guardiola31337** [comment]
Any updates here @chezzdev?

**Comment by chezzdev** [comment]
Didn't have a chance to look at it yet.

**Comment by dersim-davaod** [comment]
@1ec5, @azarovalex is going to work on https://github.com/mapbox/navigation-sdks/issues/826. The latter requires us to refactor several methods including `getStatusForMonotonicTimestampNanoseconds`.

Please make sure you both do not have intersection here.

**Comment by 1ec5** [comment]
> We’ll need some way to bridge that expectation, perhaps by polling and storing the latest value.

`RouteController.locationManager(_:didUpdateLocations:)` feeds the navigator the latest location update from Core Location as it comes in on a regular basis, then immediately asks for the status, updating various models, and posts notifications, all synchronously. We’ll need to split up this method so that it continues to feed the navigator the latest location update, but everything else happens in `NavigatorObserver.onStatus(for:status:)`. Similarly, `PassiveLocationDataSource.didUpdate(locations:)` will be limited to only calling `Navigator.updateLocation(for:)`.

`RouteController.advanceLegIndex()` changes the leg that the navigator is actively tracking. The developer currently expects the route progress model to immediately reflect this change. We can explicitly update the route progress to reflect the new leg, but everything else that would happen inside `NavigatorObserver.onStatus(for:status:)` would still be outdated. I think our only option is to make this method synchronous with a callback. The method is part of a protocol that LegacyRouteController also conforms to; I think it’s acceptable for `LegacyRouteController.advanceLegIndex()` to continue to be synchronous despite looking like an asynchronous method. Similarly, we’ll need to make `PassiveLocationDataSource.updateLocation(_:)` an asynchronous method with a callback.

`Navigator.status(at:)` is also called from a couple other places that are more difficult to make asynchronous. For `RouteController.snappedLocation`, RouteController will need to store the latest snapped location any time it gets a status update from the navigator. For `RouteController.userIsOnRoute(_:status:)`, we need to also store the latest route status from the status update. (Incidentally, this method should be private to avoid exposing MBNNNavigatorStatus to the public. Its caller, `RouteController.userIsOnRoute(_:)`, needs to remain public however.)

**Comment by Guardiola31337** [comment]
Android work is moving now in https://github.com/mapbox/mapbox-navigation-android/pull/4354 (`'da-common-runloop-callback-11-SNAPSHOT' `).

**Comment by 1ec5** [comment]
Fixed in #3006.
