### ISSUE TITLE
Crash occurs right after starting active guidance navigation in PredictiveCacheManager.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2849]
**Mapbox Navigation SDK version:** https://github.com/mapbox/mapbox-navigation-ios/pull/2837

### Steps to reproduce

 1. Open Example application.
 2. Select destination.
 3. Start basic navigation.

### Expected behavior

Active guidance navigation should start without any issues.

### Actual behavior

Crash occurs right after starting active guidance navigation in PredictiveCacheManager. Here's crash log:
[Example_2021-03-04-144846_MacBook-Pro.txt](https://github.com/mapbox/mapbox-navigation-ios/files/6087125/Example_2021-03-04-144846_MacBook-Pro.txt)

/cc @mapbox/navigation-ios

**Comment by MaximAlien** [comment]
After upgrade to Mapbox Navigation Native v44.0.0 crash is gone.

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-ios#2837 upgraded to navigation-native v45.
