### ISSUE TITLE
Merge main to release-v2.0

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2850]
main has diverged from the point at which release-v2.0 branched. To avoid regressions from v1.3.0 to v2.0.0, we need to merge main to release-v2.0. The main source of conflicts will be #2734, once it lands.

/cc @mapbox/navigation-ios @avi-c

**Comment by 1ec5** [comment]
> The main source of conflicts will be #2734, once it lands.

If porting #2734 to the map SDK v10 runtime styling API turns out to be nontrivial, we can merge an earlier commit of main to release-v2.0 as a stopgap.

**Comment by 1ec5** [comment]
#2853 takes care of the merge except for the changes in #2734.

**Comment by MaximAlien** [comment]
PR with merge can be found in https://github.com/mapbox/mapbox-navigation-ios/pull/2995.

**Comment by 1ec5** [comment]
Fixed in #2995.
