### ISSUE TITLE
Navigator.shared only accepts access token from Info.plist

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2851]
#2823 introduced unconditional usage of `Directions.shared`, which means there’s no way to set the access token other than in Info.plist. There needs to be a way to preemptively, programmatically set the access token or DirectionsCredentials that the first instance of Navigator would use. Probably this would end up being a static property on the Navigator class, backed by a global static variable, as unfortunate as that would be.

https://github.com/mapbox/mapbox-navigation-ios/blob/df75965f1eb92c03db21b9ad548200b2fe5e0312/Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift#L60

Info.plist is supposed to be an optional way of setting the access token; we always officially support a programmatic alternative for developers who can’t put the token in their Info.plist for various reasons, such as dynamically switching between access tokens. Moreover, as seen in https://github.com/mapbox/mapbox-navigation-ios/pull/2834#issuecomment-791829886, automated tests often need to be able to mock an access token.

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
It would be fixed by the #2876 to allow the Navigator accepting access token from PassiveLocationDataSource and RouteController.

**Comment by ShanMa1991** [comment]
This issue is fixed by #2876 .
