### ISSUE TITLE
End-of-route feedback view looks wrong in dark mode.

### ISSUE THREAD

**Issue by bamx23** [mapbox/mapbox-navigation-ios#2857]
**Mapbox Navigation SDK version:** 2.0.0-alpha.3

### Steps to reproduce

 1. Start active guidance session
 2. Drive to the destination point

### Expected behavior

The end-of-route feedback view is visible and correct.

### Actual behavior

Text is invisible. See screenshots.

<img src="https://user-images.githubusercontent.com/443972/110604022-b06ede00-8198-11eb-86b7-8f7e8975ebe5.jpg" width="300"/> <img src="https://user-images.githubusercontent.com/443972/110604034-b238a180-8198-11eb-828c-2d20f543da90.jpg" width="300"/>

**Comment by ShanMa1991** [comment]
It's fixed in #2859
