### ISSUE TITLE
Cannot build on IOS devices

### ISSUE THREAD

**Issue by AKACC** [mapbox/mapbox-navigation-ios#2860]
**Mapbox Navigation SDK version:** v1.2, v1.3.0-beta.1
**Xcode version:** Version 12.4 (12D4e)
**IOS version:** 14.0.1

### Steps to reproduce

 1. add  pod 'MapboxNavigation', '~> 1.2' to Podfile
 2. pod install
 3. connect to iphone and run

### Expected behavior

build successfully

### Actual behavior
build succeeded, but this shows and app is not installed.

_Unable to install "MyAppName"_

<pre>
Details

Unable to install "MyAppName"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
--
Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000125aa0c8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000125adf241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000102bd164b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x0000000125adef82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000012594fa10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000102d0017e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000102d01da0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff2023d5dd _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff2023e7c7 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202445fe _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff202450cb _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff2024ec5d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff203e6499 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff203e5467 start_wqthread + 15
);
}
--

System Information

macOS Version 11.2.3 (Build 20D91)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-03-11T10:01:55-05:00
</pre>

**Comment by azarovalex** [comment]
Hi @AKACC, thanks for reporting this issue!
Unfortunately, I'm unable to reproduce this on my iPhone. May I ask you to create an empty project and try to reproduce this issue there? Doing so will allow us to help you with your problem.
Also, do you have any special flags in your Podfile besides `pod` lines?

**Comment by AKACC** [comment]
@azarovalex I just created a new project and installed following the instructions, no additional step. It runs fine on simulators but not on physical devices.

Luckily, I fixed by adding relevant frameworks of mapbox.
<img width="733" alt="Screen Shot 2021-03-15 at 8 50 22 AM" src="https://user-images.githubusercontent.com/22218449/111155956-8720ca00-856b-11eb-9346-6cf75264d65e.png">

**Comment by 1ec5** [comment]
Unlike with Carthage, I don’t think it’s expected that you’d need to manually add any .xcframeworks to your project when you use CocoaPods.

The error above looks like a stack trace from Xcode’s iOS support code that might be worth reporting to Apple.
