### ISSUE TITLE
Maneuver arrow size is not proportional to route line on low zoom levels.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2867]
**Mapbox Navigation SDK version:** `v2.0.0-beta.1`

### Expected behavior

Maneuver arrow should be proportional to route line width on low zoom levels. Process of showing and hiding maneuver arrows should also match Mapbox Navigation SDK `v1.x` (in `1.x` maneuver arrow is hidden on low zoom levels).

### Actual behavior

Maneuver arrow size is not proportional to route line on low zoom levels. This leads to issues shown on screenshot below:

<img width="317" alt="Screen Shot 2021-03-15 at 1 42 39 PM" src="https://user-images.githubusercontent.com/1496498/111219556-6e2d0e80-8595-11eb-9c0e-37889e33265c.png">

**Comment by ShanMa1991** [comment]
Fixed in #2984
