### ISSUE TITLE
Unify RoadObjectType, RoadObjectMetadata, and RouteAlert.Alert

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2868]
The three enumerations `RoadObjectType`, `RoadObjectMetadata`, and `RouteAlert.Alert` cover basically the same information, but only two of them hold associated values and only two of them are related to the electronic horizon feature that landed in #2834. To reduce developer confusion and improve test coverage, we should unify these types as much as possible, allowing that some associated values or cases may be unused in some situations. Ideally, MapboxNavigationNative would unify its underlying types to align with this change.

/cc @mapbox/navigation-ios

**Comment by truburt** [comment]
@chezzdev , please make sure you sync with @korshaknn to synchronise the approach with Android ( mapbox-navigation-android/pull#4109 and one upcoming PR ).

**Comment by 1ec5** [comment]
This is technically not blocked by mapbox/mapbox-navigation-native#2127, because we can take care of the refactoring ahead of time and change the underlying nav-native usage as tail work. We’ll need to figure out what to do about any alert types that aren’t roa object types and vice versa.

**Comment by 1ec5** [comment]
Fixed in #2991.
