### ISSUE TITLE
Route simulation no longer works

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2883]
On the release-v2.0 branch, enabling the Simulate Route option in the Example application no longer seems to have any effect when the iOS Simulator is also set to simulate a route. SimulatedLocationManager is supposed to cause RouteController to ignore any location updates that come in through Core Location in favor of synthesized location updates along the route. But that doesn’t seem to be working anymore, so the only way to simulate a route using SimulatedLocationManager is to switch the iOS simulator to the None preset.

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
It's fixed in #2931 .
