### ISSUE TITLE
Incorrect route is requested on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2893]
**Mapbox Navigation SDK version:** `maxim/camera-viewport-api`

### Steps to reproduce

 1. Open `Example-CarPlay` application on iOS and CarPlay, request route and start active guidance navigation.
 2. After active guidance navigation starts finish it.
 3. Request different route, but using CarPlay head-unit directly.
 4. Select route, which was found and start active guidance navigation. Observe behavior.

### Expected behavior

It is expected that CarPlay uses route, which was requested using head-unit directly, not the one which was requested on iOS. For more clarity on this follow similar steps on `1.x` version of Navigation SDK.

### Actual behavior

CarPlay uses incorrect route (route which was requested on iOS).

**Comment by MaximAlien** [comment]
Cannot reproduce this issue anymore. Likely because of other fixes to CarPlay, which landed recently. I'll keep this ticket opened to make sure we verify on real CarPlay head-unit.

**Comment by pavel-4** [comment]
Work as it expected on `0.4 (115)`(device: **_iPhone 8, iOS v. 14.6_**): creating a different route via CapPlay returns to customer its geometry on iPhone and not repeats older one, that was created before via iPhone.

**Comment by MaximAlien** [comment]
No longer reproducible as of [v2.0.0-rc.2](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.0.0-rc.2).
