### ISSUE TITLE
Add `SwiftPackageManagerTest` by analogy with `CocoaPodsTest/PodInstall`

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#2903]
Currently, we have the [CocoaPodsTest](https://github.com/mapbox/mapbox-navigation-ios/tree/main/Tests/CocoaPodsTest/PodInstall), which verifies that a test project can be built with Navigation SDK installed via CocoaPods.
Swift Package Manager gradually becoming the preferable way to install Navigation SDK, so I propose to add a new SwiftPackageManagerTest that will try to build a test project that has our Navigation SDK installed via SPM, similar to the CocoaPods one that we already have.

**Comment by 1ec5** [comment]
Unlike CocoaPods, SPM is integrated into this repository’s build system, so some kinds of SPM breakage would cause the Xcode project’s Example target to fail to build. That said, the way we’re pulling the MapboxNavigation package into the Example target is somewhat unusual, in that the Xcode project includes a file reference to the Package.swift instead of using the .xcodeproj format’s built-in Swift package support. Do you think that would impact our ability to catch SPM installation issues?

**Comment by azarovalex** [comment]
@1ec5 As you've mentioned, currently we are using an approach from [this page in Apple docs](https://developer.apple.com/documentation/swift_packages/developing_a_swift_package_in_tandem_with_an_app).
The installation process for our clients will look a little bit different, I propose adding a new sample project with dependencies inside of `.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`.
Because we don't have MapboxNavigation and MapboxCoreNavigation inside of our development xcodeproj's `Package.resolved` file.

**Comment by 1ec5** [comment]
> the Xcode project includes a file reference to the Package.swift instead of using the .xcodeproj format’s built-in Swift package support

As it happens, this repository does contain [a Package.resolved inside xcshareddata](https://github.com/mapbox/mapbox-navigation-ios/blob/8511a7fe73ec8788cd2744549fa8a2b66c7d16a1/MapboxNavigation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved). I think this file is only being used by the Example target, so my earlier statement was incorrect in that the Xcode project includes both forms. The two Package.swift files can get out of sync, as seen in https://github.com/mapbox/mapbox-navigation-ios/pull/2854#discussion_r589798864. Maybe we need a CI check that the one in xcshareddata is equivalent to or a superset of the one at the project root.

**Comment by 1ec5** [comment]
Fixed in #2927 in the release-v2.0.
