### ISSUE TITLE
Electronic horizon position notification should directly contain pointer to edge tree

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2906]
As of #2834, the `electronicHorizonDidUpdatePosition` notification’s user info dictionary’s `treeKey` is set to an instance of the `ElectronicHorizon` struct, whose only purpose is to hold the starting `ElectronicHorizon.Edge` of the tree. This is redundant. Assuming we don’t intend to add more properties to `MapboxNavigationNative.ElectronicHorizon` in the future, we should eliminate the struct and place the starting edge directly in the user info dictionary. The extensive struct documentation comment should be split between `ElectronicHorizon.Edge`, `ElectronicHorizonOptions`, and `treeKey`. Nested types like `ElectronicHorizon.Edge` should be renamed to no longer nest underneath `ElectronicHorizon`.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/2834#discussion_r592032215
/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> Assuming we don’t intend to add more properties to `MapboxNavigationNative.ElectronicHorizon` in the future

@mapbox/navnative is this a reasonable assumption? Are there any other reasons for the indirection around the `ElectronicHorizon` type?

**Comment by SiarheiFedartsou** [comment]
> > Assuming we don’t intend to add more properties to `MapboxNavigationNative.ElectronicHorizon` in the future
> 
> @mapbox/navnative is this a reasonable assumption? Are there any other reasons for the indirection around the `ElectronicHorizon` type?

The main idea why we don't send `ElectronicHorizonEdge` directly, but have this `ElectronicHorizon` is that we potentially may add some fields to `ElectronicHorizon` itself, which may be helpful for end user. Tbh I don't have examples of those, but who knows? :)

**Comment by 1ec5** [comment]
> The main idea why we don't send ElectronicHorizonEdge directly, but have this ElectronicHorizon is that we potentially may add some fields to ElectronicHorizon itself, which may be helpful for end user. Tbh I don't have examples of those, but who knows? :)

Most likely we’d add any such fields to the notification itself rather than a separate ElectronicHorizon type, but if necessary we do have the flexibility to put an object of a different type in the notification, because notifications aren’t strongly typed.

**Comment by azarovalex** [comment]
PR merged.
