### ISSUE TITLE
Maneuver arrow is not fully drawn on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2907]
**Mapbox Navigation SDK version:** `release-v2.0`

### Steps to reproduce

 1. Start active guidance navigation.
 2. Wait till maneuver appears on screen.
 3. Observer behavior.

### Expected behavior

Maneuver arrow should be fully visible.

### Actual behavior

<img width="653" alt="Screen Shot 2021-03-31 at 1 52 59 PM" src="https://user-images.githubusercontent.com/1496498/113210073-adf82500-9228-11eb-9830-e1a462e83ca4.png">

**Comment by jill-cardamon** [comment]
This issue is also present in Custom UI example (using `release-v2.0` version of SDK):

![Simulator Screen Shot - iPhone 8 - 2021-04-14 at 21 42 32](https://user-images.githubusercontent.com/43434254/114879705-71532e80-9dcf-11eb-9b2d-bd1f59542fd4.png)

**Comment by MaximAlien** [comment]
Yep, it's fixed in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/2825.
