### ISSUE TITLE
End of route view is not presented on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2908]
**Mapbox Navigation SDK version:** `release-v2.0`

### Steps to reproduce

 1. Start active guidance navigation on CarPlay.
 2. Wait till the end of the navigation session.
 3. Observe behavior.

### Expected behavior

Similarly to iOS, CarPlay should present end of route view. Functionality for it is currently available, but not used anywhere. Method which allows to do this is present in: `CarPlayNavigationViewController.presentArrivalUI()`.

### Actual behavior

End of route view doesn't appear at the end of navigation session on CarPlay.

It's still an open question whether end of route is hidden on CarPlay intentionally and is not needed.

**Comment by ShanMa1991** [comment]
The 1.x now doesn't have the Arrival UI either. I think it's removed by https://github.com/mapbox/mapbox-navigation-ios/pull/2005 . Maybe we should add it back like https://github.com/mapbox/mapbox-navigation-ios/pull/1997 ?

**Comment by 1ec5** [comment]
Fixed in #3016 on the release-v2.0.
