### ISSUE TITLE
Maneuver selection doesn't work correctly.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2912]
**Mapbox Navigation SDK version:** `maxim/camera-viewport-api`

### Steps to reproduce

 1. Start active guidance navigation.
 2. Select maneuver from top banner menu.
 3. Observe behavior.

### Expected behavior

It is expected that after maneuver selection maneuver is centered in the middle of the screen.

### Actual behavior

https://user-images.githubusercontent.com/1496498/113632475-0d3aa880-9620-11eb-907c-baa8bb010206.mov

**Comment by ShanMa1991** [comment]
fixed in #2975
