### ISSUE TITLE
Application bundle misidentified as MapboxCoreNavigation when building with SPM

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2922]
`Bundle.mapboxCoreNavigation` and `Bundle.mapboxNavigationIfInstalled` return the host application bundle when MapboxCoreNavigation is built as an SPM target. These computed variables rely on the old canary class trick, which is unreliable when the target produces a static framework, as it does under SPM:

https://github.com/mapbox/mapbox-navigation-ios/blob/70020623e427a32239b344f48d0af6428fcbe565/Sources/MapboxCoreNavigation/BundleAdditions.swift#L26-L42

By contrast, `Bundle.mapboxNavigation` uses `Bundle.module` to reliably return the bundle associated with the MapboxNavigation target, which SPM synthesizes for this purpose:

https://github.com/mapbox/mapbox-navigation-ios/blob/70020623e427a32239b344f48d0af6428fcbe565/Sources/MapboxNavigation/Bundle.swift#L7-L15

The incorrect `Bundle.mapboxCoreNavigation` and `Bundle.mapboxNavigationIfInstalled` behavior causes several bugs:

* Events are misstating the application version as the SDK version.
* User agent strings for junction views and routing tiles state the name and version of the application where it should state that of MapboxCoreNavigation.
* At launch, NavigationService and LegacyRouteController check for updates based on the application version instead of the SDK version.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> By contrast, `Bundle.mapboxNavigation` uses `Bundle.module` to reliably return the bundle associated with the MapboxNavigation target, which SPM synthesizes for this purpose

This is the correct change for SPM. However, in some places, we’re using `Bundle.mapboxCoreNavigation` to get certain keys out of the Info.plist in the bundle. SPM [generates an Info.plist](https://forums.swift.org/t/add-info-plist-on-spm-bundle/40274) that doesn’t contain the `CFBundleShortVersionString` key maintained by Apple Generic Versioning. There is a potential workaround that involves specifying an override Info.plist in an .xcconfig file. But the workaround requires command-line `swift` users to pass some unwieldy arguments that I’m not sure Xcode will respect anyways.

For now, we’ll need to maintain a different plist file alongside Info.plist that contains the usual keys. update-version.sh can copy the normal Info.plist to the new one, or maybe we can find a way to make SPM copy the Info.plist under a different name in the resource bundle instead of excluding it.

**Comment by ShanMa1991** [comment]
This issue is fixed by #2924
