### ISSUE TITLE
TileStore config for MapView and Navigator

### ISSUE THREAD

**Issue by Udumft** [mapbox/mapbox-navigation-ios#2926]
As a part of API updating, MapsView and Navigator configs will now expect a `TileStore` instance to be passed instead of a path string.
We need to provide a setting which will allow to configure this `TileStore` which should be shared by both `MapView` and `Navigator` objects. Default value should be taken from `TileStore.getInstance()`.
Also, there should be a less obvious way to configure `MapView` and `Navigator` independently to support advanced use-cases.

Currently, `MapView` tile store path is [configured](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/Sources/MapboxNavigation/NavigationMapView.swift#L289) via `ResourceOptions` inside `NavigationMapView`. This is not configurable atm. and should be changed.
`Navigatorr` config is also [encapsulated](https://github.com/mapbox/mapbox-navigation-ios/blob/release-v2.0/Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift#L22) and not configurable at runtime.
Existing defaulting to `.caches` directory is obsolete.

**Comment by 1ec5** [comment]
> As a part of API updating, MapsView and Navigator configs will now expect a TileStore instance to be passed instead of a path string.

This happened in mapbox/mapbox-navigation-ios#2930, but this issue tracks making the TileStore publicly configurable.

**Comment by Udumft** [comment]
Resolved by #2956
