### ISSUE TITLE
Banner instruction attributed strings cache should be invalidated upon UI color mode change

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2938]
When the color mode is flipped from light to dark mode, the SDK will continue to reuse cached attributed strings for things like Exit numbers in banner instructions. this can lead to color mismatches, as seen in the "Exit 50" image in the banner below, even when using dynamic colors:
![Simulator Screen Shot - iPhone 11 - 2021-04-15 at 10 32 35](https://user-images.githubusercontent.com/10037825/114913498-1bce5000-9dd6-11eb-90f2-6795f3ef5e1e.png)

**Mapbox Navigation SDK version:**
v1.4

### Steps to reproduce

 1. Assign a dynamic color to the PrimaryLabel for the DayStyle
 2. Bring up a banner instruction with an exit number
 3. Switch UI color mode to Dark

### Expected behavior
All text follows the dynamic color

### Actual behavior
Regular text changes but any generated images do not.

This occurs because we cache these exit images in the function `private func exitShield(side:text:dataSource:cacheKey:)` and similar. The `ImageRepository` cache should be cleared when the color mode changes.

**Comment by avi-c** [comment]
To be clear, the exit number image should also have turned white and not remained in black as it was in "light" mode.

**Comment by ShanMa1991** [comment]
It's fixed in #2977
