### ISSUE TITLE
Setting routeLineTracksTraversal to true on the navigation view controller has no effect

### ISSUE THREAD

**Issue by MalcolmScoffable** [mapbox/mapbox-navigation-ios#2941]
**Mapbox Navigation SDK version:** v2.0.0-beta.5 (and latest v2.0 branch)

### Steps to reproduce

 1. Set the `routeLineTracksTraversal` property on a `NavigationViewController` to `true` 
 2. Navigate a route

### Expected behavior
The directions line trailing the puck should disappear as the device moves around. Testing this with https://github.com/mapbox/mapbox-navigation-ios-examples pointing at the v1.0 SDK has this effect.

### Actual behavior
No visible effect. The puck moves but the line stays static with no visible change. The line sections behind the puck do not disappear or change colour. Testing this with the https://github.com/mapbox/mapbox-navigation-ios-examples project pointing at the V2.0 SDK has the same behaviour. Also noticed on the app that I am currently developing. I would expect the route to have the effect of the directions line being "eaten" up by the puck with this parameter set to true.

It may be that I am missing something, and that more steps are required to enable this. Also, I haven't found any other issues that state this to be broken, which makes me think that I am missing something. However any documentation and comments that I've seen suggest that setting `routeLineTracksTraversal` to true should have the effect of the route disappearing behind the puck.

**Comment by MaximAlien** [comment]
@MalcolmScoffable, can you please verify whether it works on the most recent `v2.0.0-beta.7` version of Navigation SDK?

**Comment by MalcolmScoffable** [comment]
I've just tried `v2.0.0-beta.8` using the "Styled Example" in https://github.com/mapbox/mapbox-navigation-ios-examples and it does seem to work correctly now. I haven't tried it in our own app yet however as I've reverted to the stable version of the nav sdk for now. I will upgrade soon and report back though.

**Comment by MalcolmScoffable** [comment]
Seems to be working ok now in terms of route eating in the latest beta.

**Comment by MaximAlien** [comment]
@MalcolmScoffable, thanks for the update. In case if you see other issues please create another ticket. Closing this one.
