### ISSUE TITLE
Expose EHorizonEdgeMetadata isOneWay property

### ISSUE THREAD

**Issue by truburt** [mapbox/mapbox-navigation-ios#2943]
NavNative `EdgeMetadata` has a new `isOneway` property. It should be exposed by SDK.

**Comment by chezzdev** [comment]
`isOneWay` is represented as [`directionality`](https://docs.mapbox.com/ios/navigation/api/2.0.0-beta.5/Structs/ElectronicHorizon/Edge/Metadata.html#/s:16MapboxNavigation17ElectronicHorizonV4EdgeV8MetadataV14directionalityAE14DirectionalityOvp) property which can take `oneWay` or `bothWays` values.
