### ISSUE TITLE
NavigationView's camera pans when view is being dismissed from modal in non-fullscreen mode

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#2947]
**Mapbox Navigation SDK version:**2.0.0-beta.5

### Steps to reproduce

 1. Open the nav sdk's Example app
 2. Comment out the line setting `modalPresentationStyle` to `.fullscreen` here:         
 https://github.com/mapbox/mapbox-navigation-ios/blob/d6f0a1c1ebcfdde62875ceb7f0112862559e6082/Example/ViewController.swift#L454
 3. Observe behavior where dragging down the modal with the gesture initiating in the map causes both views to move. (video attached)

### Expected behavior
Map pans and modal does not dismiss

### Actual behavior
Map pans and modal dismiss at the same time

https://user-images.githubusercontent.com/630204/115797212-01c5dc00-a399-11eb-8f4a-5c97f1577600.mov

**Comment by Udumft** [comment]
Hello. That is quite interesting use-case. Usually non-modal presentation is used for some small or temporary screens. What is the motivation to avoid modal presentation style for navigation?
Also, what is the minimal iOS version you are aiming for? Presentation logic was updated starting iOS 13.

**Comment by irtemed88** [comment]
Apologies for the late reply. We have a delivery optimization app and our UX flow involves users navigating along a route stopping frequently. After each stop we exit the navigation flow at which point the user will reinitiate when ready (presenting the navigation flow again). This continues until the route is complete.

Our app's minimum target version is iOS 14.

**Comment by MaximAlien** [comment]
It looks like clash of gesture handlers. Can also be reproduced in custom navigation example provided by Navigation SDK. Was reported on Maps SDK side.

**Comment by MaximAlien** [comment]
This issue was resolved on Maps SDK side and is no longer reproducible. @irtemed88, please re-check and re-open this ticket if needed.
