### ISSUE TITLE
Problems when changing the route in the NavViewController while navigating.

### ISSUE THREAD

**Issue by MalcolmScoffable** [mapbox/mapbox-navigation-ios#2948]
**Mapbox Navigation SDK version:**  v2.0.0-beta.5 (and latest v2.0 branch)

I'm currently having an issue with updating waypoints in the NavViewController after navigating a previous route. Basically, my use case is this:
- Driver navigates a series of waypoints. On completion of the final waypoint the driver is asked if they want to navigate back to the start.
- If the driver chooses to navigate back to the start, then a new route is generated consisting of the current location of the driver as the start point, and a destination waypoint being where they start. This should then replace the previous route in the navigation view controller and the driver would navigate to the new destination, any re-routes etc would be to that destination.

However, I'm having problems with this. I update NavViewController with the new route as follows:
```swift
Directions.shared.calculate(returnRouteOptions) { (session, result) in
   switch result {
    case .failure(let error):
        print("Error getting directions: \(error.localizedDescription)")
    case .success(let response):
        guard let route = response.routes?.first else {
            return
        }
        self.currentMapRoute = route
        // If we've already got a nav service then update it, otherwise create a new one
        self.currentNavigationViewController?.indexedRoute = IndexedRoute(route, 0)
        
    }
}
```

This does then plot the new route, however the map also shows the old destination waypoint from the previous route in addition to the new destination waypoint. The route also seems to take account of both. If the driver subsequently goes off route and a re-route event is triggered the update route always changes to go solely to the old destination rather than the new one. It seems that when updating the route data then some state is retained pointing to the old route.

Of course I could be missing something fundamental here and not updating the route correctly. I am struggling to find any references that would show me how to do this though. It does feel like a bug, however.

The following screenshots attempt to illustrate what I'm talking about:
- Initial route:
![IMG_8163](https://user-images.githubusercontent.com/24914554/115865292-07bacc00-a430-11eb-94ad-7c2bd47ac3eb.jpg)

- After stating that the 1st waypoint is complete and I want to navigate back to the beginning (initiated via a popup alert). Note the 2 destination markers:
![IMG_8164](https://user-images.githubusercontent.com/24914554/115865400-291bb800-a430-11eb-87a3-5ace630ebf23.jpg)

Also, weirdly there seems to be another bug around the Mapbox logo.. I end up with multiples in various scenarios... This is probably a different bug.

### Steps to reproduce

 1. Start navigating a route with some waypoints
 2. Create a new route with different waypoints
 3. Change the route used by the navigation controller to be the new route.

### Expected behavior
I would expect that the route that is shown in the navigation view controller along with the waypoints change and that re-routes apply to the new route.

### Actual behavior
The destination markers for both routes are shown. Re-routing applies to the first route.

**Comment by MalcolmScoffable** [comment]
Update on this using v2.0.0-beta.10 and v2.0.0-beta.11, the mapbox logo issue has now been resolved. Multiple logos are no longer shown after various events. However, the key issue that the above alludes to is still present. Old destination markers are still shown after changing the route.

**Comment by MalcolmScoffable** [comment]
I also managed to find a workaround for the routing problem by implementing `shouldRerouteFrom` in the nav service delegate, returning false and forcing my own routing code. The problem still remains though that if this isn't done then any re-routing is for the original route passed into the Mapbox SDK and not the updated one. It's as if the original state isn't being cleared when the route has been updated.

**Comment by S2Ler** [comment]
Here is what I found: Updating https://github.com/mapbox/mapbox-navigation-ios/blob/a8ad873cc581c170e2dcd1d203d5f3983cf6e569/Sources/MapboxNavigation/NavigationViewController.swift#L32 doesn't update https://github.com/mapbox/mapbox-navigation-ios/blob/a8ad873cc581c170e2dcd1d203d5f3983cf6e569/Sources/MapboxCoreNavigation/RouteProgress.swift#L21 in https://github.com/mapbox/mapbox-navigation-ios/blob/a8ad873cc581c170e2dcd1d203d5f3983cf6e569/Sources/MapboxCoreNavigation/Router.swift#L50 So, updating this property only works if waypoints stay the same. 

If my understanding is correct than I propose adding a new method on ``NavigationViewController``, ``NavigationService``, ``Router``:
```swift
    func updateRoute(with indexedRoute: IndexedRoute, routeOptions: RouteOptions?)
```
It will update https://github.com/mapbox/mapbox-navigation-ios/blob/a8ad873cc581c170e2dcd1d203d5f3983cf6e569/Sources/MapboxCoreNavigation/Router.swift#L50 with the new routeOptions. 

I've tried implementing this method and manual rerouting starts to work as expected from my very limited testing. 

@mapbox/navigation-ios Do I miss some important details here? @1ec5

**Comment by 1ec5** [comment]
Yes, I agree with the proposed addition. A dedicated method would be consistent with how, as of #2610, `Router.advanceLeg()` is the correct way to advance to the next leg, rather than setting `indexedRoute` directly. Adding the method to NavigationViewController, NavigationService, and Router may be unnecessarily complex, so I think it would be reasonable to add it only to NavigationService and Router, as long as we make sure to turn `indexedRoute` into a read-only property.

We originally introduced the `route` setter (now the `indexedRoute` setter) as a generic implementation of rerouting, a situation in which the waypoints should stay the same, but we thought it expedient to allow developers to arbitrarily set the route as well. (The waypoints are often obtained from the route options because the route response doesn’t contain silent waypoints, that is, non-leg-separating waypoints.) We apparently didn’t consider that the arbitrary route could have nothing to do with the route options of the previous route, but in hindsight that’s exactly what a developer would be tempted to use this capability for.

**Comment by S2Ler** [comment]
``NavigationViewController`` has the following logic: https://github.com/mapbox/mapbox-navigation-ios/blob/99b16129b7e67ec6c072b495828466da810b4050/Sources/MapboxNavigation/NavigationViewController.swift#L39-L41

But it turns out it isn't necessary because the reroute will be propagated from ``Router`` to ``NavigationViewController`` anyway.

**Comment by MalcolmScoffable** [comment]
I think a specific method for replacing the route would be great.

**Comment by S2Ler** [comment]
> add it only to NavigationService and Router, as long as we make sure to turn `indexedRoute` into a read-only property.

I decided to keep the new method only in `Router` and link to this method from documentation comments to reduce duplication.

**Comment by JanTG1** [comment]
I am having a similar issue. Could you please state how updating a running NavigationViewController should be done? navigationViewController.route.updateRoute(with: ,routeOptions: ,completion: ) is still inaccessible due to internal protection level.
