### ISSUE TITLE
Current road name label flashes previous road name on unnamed road

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2954]
If the user travels along a named road then turns onto an unnamed road, the current road name label flashes the previous road’s name when toggling between overview mode and course tracking mode.

When the current road is unnamed, the current road name label continues to contain the previous road name. Every code path should set the label’s `text`, even if it just sets it to `nil`:

https://github.com/mapbox/mapbox-navigation-ios/blob/1555074946d80cd3c9b86c0f140af0e2c8b33e6b/Sources/MapboxNavigation/RouteMapViewController.swift#L555-L560 https://github.com/mapbox/mapbox-navigation-ios/blob/1555074946d80cd3c9b86c0f140af0e2c8b33e6b/Sources/MapboxNavigation/RouteMapViewController.swift#L688-L697

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
A contributing factor is that we unconditionally show the current road name label when transitioning back to following mode, even if there’s no text to show in the label:

https://github.com/mapbox/mapbox-navigation-ios/blob/1555074946d80cd3c9b86c0f140af0e2c8b33e6b/Sources/MapboxNavigation/RouteMapViewController.swift#L222

**Comment by zugaldia** [comment]
@ShanMa1991 @jill-cardamon would either of you be able to pick this one up?

**Comment by ShanMa1991** [comment]
I could pick this up.

**Comment by zugaldia** [comment]
PR open here: https://github.com/mapbox/mapbox-navigation-ios/pull/2958 (thanks @ShanMa1991!).

/cc: @OttyLab

**Comment by ShanMa1991** [comment]
This issue is fixed in #2958 .
/cc: @OttyLab
