### ISSUE TITLE
Custom Floating Buttons & Adjusting SpeedLimitView top padding?

### ISSUE THREAD

**Issue by spotelf13** [mapbox/mapbox-navigation-ios#2972]
**Mapbox Navigation SDK version: v1.4.0**

Hey guys, what's the best way to add custom floating buttons and adjust the padding of the SpeedLimitView? 

Is this something I can do in a custom DayStyle class? 

i.e. setting custom floating buttons as part of a custom DayStyle & passing into NavigationOptions.
`FloatingButton.appearance().backgroundColor = #colorLiteral(red: 0.9999960065, green: 1, blue: 1, alpha: 1)
  FloatingButton.appearance().tintColor = blueColor`
  
 `let navigationOptions = NavigationOptions(styles: [MapboxMapStyle], navigationService: navigationService, topBanner: topBanner, bottomBanner: bottomBanner)`

**Comment by spotelf13** [comment]
Found my answer! https://github.com/mapbox/mapbox-navigation-ios/pull/2763#issue-534765148

But MapOrnamentPosition sets the position of both the floating buttons and speed limit view? How would I go about setting the padding/position for the two individually?

**Comment by ShanMa1991** [comment]
Hi @spotelf13 , right now the positions of the speedLimitView and floatingButtons are designed to be placed on the opposite sides of the view during turn by turn navigation. This issue could be tracked in #2953 .

**Comment by spotelf13** [comment]
Hi @ShanMa1991 thanks for the update, will wait for future updates. In the meantime I'll continue to use the MapOrnamentPosition positions for now. :)
