### ISSUE TITLE
Camera / puck appears to reset to route start when resuming navigation service

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#2981]
**Mapbox Navigation SDK version:** 2.0.0-beta.7

We're prototyping a new navigation experience in the Straightaway app where a user can now remain within `NavigationViewController` for all stops along their route. At each stop we pause navigation until the user manually instructs navigation to continue.

Attached is a video demonstrating this behavior. See time markings 0:30 and 0:59 for two instances of this behavior.

### Steps to reproduce

 1. Create a NavigationViewController with a route containing multiple waypoints
 2. Return `false` from `navigationService(_:didArriveAt:)`
 3. After arrival at a waypoint, restart navigation by calling:
 ```swift
navigationService.router.advanceLegIndex()
navigationService.start()
```

### Expected behavior
The puck and camera should continue navigation from their current position

### Actual behavior
The puck and camera appear to briefly reset to the start of the route before animating back into position

https://user-images.githubusercontent.com/630204/117195160-91f91d80-adaa-11eb-80c6-ca987d9cdae7.mov

**Comment by MaximAlien** [comment]
@irtemed88, could you please re-test with the latest version of Mapbox Navigation SDK for iOS [v2.0.0-beta.19](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.0.0-beta.19). I've been trying to emulate similar behavior, but cannot reproduce it. For example, here's behavior when after arrival switch to next leg is delayed by 5 seconds:

https://user-images.githubusercontent.com/1496498/127071380-7ff70878-efcd-4e35-9511-063195d90501.mov

**Comment by MaximAlien** [comment]
No longer able to reproduce. @irtemed88, feel free to re-open/create new ticket in case if you still see similar issues.
