### ISSUE TITLE
Improve documentation coverage

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#299]
The Mapbox Navigation API reference currently lives at https://mapbox.github.io/mapbox-navigation-ios/navigation/ but there are still a number of core classes and properties that need to be documented.

We can hide undocumented methods and classes (e.g. viewDidLoad on NavigationViewController), but until we can confidently say we have sufficient documentation coverage, I've kept everything undocumented visible.

Obvious examples:
* [x] NavigationViewController.route
* [x] RouteController: explain difference compared to NavigationViewController: easy to confuse the two
* [ ] RouteController.simulatesLocationUpdates
* [x] RouteProgress.route
* [ ] [RouteProgress.TODO](https://mapbox.github.io/mapbox-navigation-ios/navigation/0.4.0/Classes/RouteProgress.html#/TODO:%20Set%20stepIndex%20to%200%20or%20last%20index%20based%20on%20whether%20leg%20index%20was%20incremented%20or%20decremented.)
* [x] RouteProgress.remainingWaypoints
* [x] RouteProgress.currentLegProgress
* [x] RouteLegProgress.leg
* [x] RouteLegProgress.currentStepProgress
* [x] RouteLegProgress.init
* [x] RouteStepProgress.init
* [x] NavigationMapView
* [ ] NavigationMapViewDelegate
* [x] MGLMapView.showsTraffic
* [ ] StyleKitArrows
* [x] StylableButton
* [x] StyleableLabel
* [x] RouteVoiceController
* [x] RouteTableViewController
* [ ] NavigationPulleyViewController
* [x] UI Components (Button, CellSubtitleLabel, ProgressBar, LineView, etc)
* [x] RouteController notifications + keys

Some of the above examples will probably make sense to hide + keep undocumented, however we should consider making anything that's undocumented private. 

@bsudekum @frederoni can you go through the sidebar in https://mapbox.github.io/mapbox-navigation-ios/navigation/ and document anything that you'd like to remain visible? I'll switch on `hide_undocumented` tomorrow afternoon after you take a final pass.

Can you also add a list of anything that we specifically that we _want_ to hide, even if we have documented it?

**Comment by 1ec5** [comment]
#307 addressed nearly all of the undocumented symbols, either by adding documentation or by making them private. This is good enough for the v0.5.0 release.
