### ISSUE TITLE
currentLegProgress.currentStepProgress is `nil` when navigation start

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#2997]
**Mapbox Navigation SDK version:** v2.0

### Steps to reproduce

 1.  choose  `Features/Location/City run` in Smulator
 2. choose a destination
 3.  start navigation in simulation mode

### Expected behavior
Navigation starts
### Actual behavior
The navigation stops related with the `currentStepProgress`

**Comment by ShanMa1991** [comment]
Cannot reproduce it. But it's seems to be related with #2980 that the `currentStepProgress` is `nil` when we try to access it with `routeProgress.currentLegProgress.currentStepProgress`

**Comment by 1ec5** [comment]
Does the current step progress become non-nil after the first location update, or does it remain nil for the duration of the trip?

**Comment by ShanMa1991** [comment]
@1ec5  The navigation just stops due to the `nil`  of the `routeProgress.currentLegProgress.currentStepProgress` during the run time. After switching the sequence of the `self.stepIndex = stepIndex` and `currentStepProgress = RouteStepProgress(step: leg.steps[stepIndex], spokenInstructionIndex: spokenInstructionIndex)` in the `RouteLegProgress.init(leg:stepIndex:spokenInstructionIndex:)` and build again, the problem could not be reproduced again and it seemed to be fixed.

**Comment by ShanMa1991** [comment]
After tests, the `nil` of `currentLegProgress.currentStepProgress` is not reproducible. I haven't find another case for the recent several weeks. Although the #3298 still could be observed, the `nil` value is not. Feel safe to close this issue.
