### ISSUE TITLE
Camera shaking during navigation

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#2998]
**Mapbox Navigation SDK version:** v2.0.0

When start navigation with `Features/Location/Freeway Drive` under simulation mode, the camera is shaking during the navigation.

### Actual Behavior

![cameraShaking](https://user-images.githubusercontent.com/48976398/118058001-fafc0a80-b341-11eb-94e8-e1e722f18689.gif)

**Comment by zugaldia** [comment]
Could you attach a video/GIF of what you're seeing?

**Comment by ShanMa1991** [comment]
@zugaldia  Thanks for the suggestion, I just made one GIF as attached in the issue description.

**Comment by ShanMa1991** [comment]
It's fixed in #3010 with the Mapbox Maps fix included.

**Comment by ShanMa1991** [comment]
The shaking of camera still exits during the navigation with the Mapbox Maps `10.0.0-beta.20`, but at a smaller rate.

**Comment by macdrevx** [comment]
This will be fixed in Maps SDK by https://github.com/mapbox/mapbox-maps-ios/pull/519

**Comment by macdrevx** [comment]
@ShanMa1991 the Maps SDK fix has been merged and will be included in RC5 next week.

**Comment by ShanMa1991** [comment]
@macdrevx Thanks for the update! I'll keep track of the RC5 integration to solve this issue.

**Comment by ShanMa1991** [comment]
Because #3162 has updated the Mapbox Maps to v10.0.0-rc.5, this issue is fixed with the last release.
