### ISSUE TITLE
Continue rerouting after a destination way point is reached

### ISSUE THREAD

**Issue by MalcolmScoffable** [mapbox/mapbox-navigation-ios#3001]
**Mapbox Navigation SDK version:** v2.0.0-beta.8

Currently struggling to get my route to update after continuing past a waypoint but not having moved to the next leg. I've set the `shouldPreventReroutesWhenArrivingAt` delegate method to return `false` and have  set the `didArriveAt` delegate method to also return false (to avoid the SDK automatically moving to the next leg). However, what then happens is that the puck just freezes in place, will not progress past the waypoint and will not trigger a re-route if the driver drives past the waypoint.

I've tried a number of hacks such as setting `service.routeProgress.currentLegProgress.userHasArrivedAtWaypoint = false`) etc in the `didArriveAt` delegate method but with limited success. Doing this allows the puck to keep moving but does not trigger re-routes and causes some glitching.

Ultimately what I want to happen is that if the driver goes past the waypoint for some reason, then until they mark that waypoint as complete then the directions should update to bring them back to the incomplete waypoint. On marking it as complete (via a UI button) then the directions should continue to the next waypoint.

I'm really struggling to see how I could achieve this. I've noted that there was a similar issue with an older version of the SDK in the past https://github.com/mapbox/mapbox-navigation-ios/issues/1657 but which has been closed but doesn't appear to be resolved. There also seems to be a similar issue on Android (although a colleague of mine was able to get a workaround in place for this) https://github.com/mapbox/mapbox-navigation-android/issues/3087.

I may be missing something fundamental here, but really struggling to see how to achieve this.

### Steps to reproduce

 1. `shouldPreventReroutesWhenArrivingAt` delegate method returns false
 2. `didArriveAt` delegate method returns false
 3. Drive past waypoint without marking it as completed.

### Expected behavior
I would expect the puck to reflect the user's position after driving past the waypoint. I would also expect a re-route to take place bringing the driver back to the waypoint.

### Actual behavior
The puck freezes just before the waypoint. No re-routing takes place. Setting `service.routeProgress.currentLegProgress.userHasArrivedAtWaypoint = false` results in some odd behaviour where the puck keeps moving, but the map centres on the waypoint, with the puck eventually moving off screen, no re-routing takes place in this situation either.

**Comment by MalcolmScoffable** [comment]
Just adding a comment to say that this behaviour is still an issue in v2.0.0-beta.11 too. Would be good if there was a way to show the driver's location after they've driven past the waypoint without having to move them to the next waypoint (i.e, navigate back to the waypoint that they've just passed).

**Comment by MalcolmScoffable** [comment]
This video highlights the problem. Car stops just short of the waypoint. I've added a normal map puck to show actual car location. I thought there might be a way of getting this to re-route back to the waypoint but all navigation seems to freeze until the waypoint index is bumped. 

https://user-images.githubusercontent.com/24914554/121663235-1de32100-ca9e-11eb-8967-bdb9e82b5ad5.mov

**Comment by MalcolmScoffable** [comment]
So, in trying to work around this I changed the code in my `didArriveAt` delegate method to regenerate the route from scratch and replace it in the navigation controller before returning false. I thought this might work in terms a being a full refresh of all waypoints etc at the point of checking if the driver has arrived at a waypoint (so regenerating all the legs etc). This sort of works in that the marker keeps moving, however the general view still freezes over the original waypoint so that the marker goes off screen. Seems like very strange behaviour. Like not all state is being refreshed on a route update. This is probably the wrong approach to be fair but I'm clutching at straws at this point. 

See this video for an example:

https://user-images.githubusercontent.com/24914554/121667502-42d99300-caa2-11eb-970c-0e427604cd73.mov

**Comment by S2Ler** [comment]
@MalcolmScoffable Thank you for the detailed report and a good use case.  I'm looking into the issue, and from what I can tell right now, this functionality doesn't work as you would expect. I'm working on a fix.
