### ISSUE TITLE
Create a separate section for Electronic Horizon APIs in reference docs

### ISSUE THREAD

**Issue by chezzdev** [mapbox/mapbox-navigation-ios#3012]
Right now reference documentation puts EH-related objects into "Other" category, while it may deserve a separate section.

**Comment by 1ec5** [comment]
We need to add a section to this file that explicitly lists every top-level symbol associated with electronic horizon functionality:

https://github.com/mapbox/mapbox-navigation-ios/blob/6dae1580d8ec5fac7757868c6a5a7f64b2586d5b/docs/jazzy.yml#L14

**Comment by 1ec5** [comment]
Fixed in #3099 on the release-v2.0 branch.
