### ISSUE TITLE
Display Route object on map for preview, before starting the navigation

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#3018]
Context:
So before we had the following SDKs versions:
  pod 'Mapbox-iOS-SDK', '5.5.0'
  pod 'MapboxDirections.swift', '0.30.0'
  pod 'MapboxNavigation', '0.38.0'
So we used Route.coordinates to draw the lines on the map, also to include an annotation where we had a merge between 2 Route objects.

A simple example how we draw on map before (single Route):
![Screenshot 2021-05-19 at 23 29 15](https://user-images.githubusercontent.com/13376064/118880001-07f89b00-b8fa-11eb-9352-a02f6c384e81.png)

Right now we updated to the last version SDKs as follows:
  pod 'Mapbox-iOS-SDK', '6.3.0'
  pod 'MapboxDirections', '1.2.0'
  pod 'MapboxNavigation', '1.2.0'

Right now, the logic we used before is no longer valid because in the first place Route object did change, and coordinates are no longer available.
I checked the documentation and I'm a little bit confused. I'm not sure exactly what is the best practice to draw (display) the route directions on the map as a preview before the user will start the navigation.

**Comment by 1ec5** [comment]
For MapboxDirections v1.2.0 and map SDK v6.3.0, consult [this example code](https://github.com/mapbox/mapbox-directions-swift/tree/v1.2.0#drawing-the-route-on-a-map). Note that some of this code will have to change in the future when you upgrade to navigation SDK v2.0, MapboxDirections v2.0, and map SDK v10.

**Comment by nastasiupta** [comment]
Thanks @1ec5
