### ISSUE TITLE
User annotation not updated on map when using cameraThatFitsShape and setCamera

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#3020]
**Mapbox Navigation SDK version:**
Mapbox-iOS-SDK 6.3.0
MapboxDirections 1.2.0
MapboxNavigation 1.2.0

### Steps to reproduce

1.  I create an array of CLLocationCoordinate2D 
2. I create a MGLPolyline using that coordinates and add it to the map
        let routeLine = MGLPolyline(coordinates: polylineCoordinates, count: UInt(polylineCoordinates.count))
        addAnnotation(routeLine)
3. I want to update the map to display the created Polyline
        let camera = cameraThatFitsShape(routeLine, direction: 0, edgePadding: UIEdgeInsets.init(top: topPadding, left: 30, bottom: bottomPadding, right: 30))
       setCamera(camera, animated: true)

4. The map is updated correctly, the map displays the full polyline, but the issue is that the user annotation is not updated. If I move the map just a bit, the user annotation is updated.

After set camera:
![Screenshot 2021-05-20 at 20 35 28](https://user-images.githubusercontent.com/13376064/119023756-0044ff00-b9ab-11eb-8e6c-6e18c909b8c3.png)

After I move the map just a little bit:
![Screenshot 2021-05-20 at 20 35 41](https://user-images.githubusercontent.com/13376064/119023785-0935d080-b9ab-11eb-9ac4-2a26b270b919.png)

**Comment by benorgan** [comment]
I am also seeing this issue in Mapbox Navigation 1.4

**Comment by nastasiupta** [comment]
@benorgan  did you manage to find a solution for this?

**Comment by nastasiupta** [comment]
@benorgan I found a solution to this. Instead of using:

```
let camera = self.cameraThatFitsShape(routeLine, direction: 0, edgePadding: .init(top: topPadding, left: 30, bottom: bottomPadding, right: 30))
setCamera(camera, animated: true)
```


I used:
```
 let edgePadding: UIEdgeInsets = .init(top: topPadding, left: 30, bottom: bottomPadding, right: 30)
setVisibleCoordinates(polylineCoordinates, count: UInt(polylineCoordinates.count), edgePadding: edgePadding, animated: true)
```

And now is working fine, the user annotation is keeping it's place, properly

**Comment by benorgan** [comment]
I don't have `setVisibleCoordinates` available on my `mapView` - perhaps we're using different versions? Here's what I did to fix it:

```
    // We set showsUserLocation to false and then true after the call to setOverheadCameraView so that the user location is in the correct place
    mapView.showsUserLocation = false
    
    mapView.setOverheadCameraView(from: currentLocation, along: LineString(routeShape.coordinates), for: UIEdgeInsets(top: padding * 2, left: padding, bottom: padding + bottomMargin, right: padding))

    mapView.showsUserLocation = true
```

**Comment by nastasiupta** [comment]
@benorgan  I use those versions:
  pod 'Mapbox-iOS-SDK', '6.3.0'
  pod 'MapboxDirections', '1.2.0'
  pod 'MapboxNavigation', '1.4.0'
