### ISSUE TITLE
UserPuckCourseView should be subclassable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3033]
UserPuckCourseView should be `open` instead of `public` so that applications can customize some aspect of it without having to reimplement the basic design, integration with the UI style, or the arrow fading feature added in #2359.

https://github.com/mapbox/mapbox-navigation-ios/blob/5e5f4bd7aabbb7b7251b8feb908eafca0b8ebee3/Sources/MapboxNavigation/UserCourseView.swift#L38

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
It will be addressed in #2968 .

**Comment by 1ec5** [comment]
Fixed in #2968 on the release-v2.0 branch.
