### ISSUE TITLE
Add new methods to RoadGraph

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#3035]
There are new methods in MBNNGraphAccessor, which are not yet supported in our RoadGraph API.

- [x] `getPathShape(for path: MBNNGraphPath) -> [CLLocation]?`
- [x] `getPositionCoordinate(for position: MBNNGraphPosition) -> CLLocation?`

We should add corresponding public methods in our Navigation SDK.

**Comment by 1ec5** [comment]
For simplicity, perhaps we should consolidate this method into a single method that returns a Geometry.

**Comment by azarovalex** [comment]
@1ec5 I don't see a way to unite these methods because they take different arguments, can you expand your proposal in more details, please?

**Comment by 1ec5** [comment]
> I don't see a way to unite these methods because they take different arguments, can you expand your proposal in more detail, please?

You’re right, I was under the mistaken impression that we still had an enumeration with associated values to unify Path and Position into a single type, but I don’t see that anymore. Still, we can overload the same method signature for these two different types.
