### ISSUE TITLE
Rename RoadObjectsStore to RoadObjectStore

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3041]
We should rename RoadObjectsStore and RoadObjectsStoreDelegate to RoadObjectStore and RoadObjectStoreDelegate, respectively. The latter names are more grammatical and consistent with the majority of types that begin with “RoadObject”.

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
It's fixed in #3045
