### ISSUE TITLE
Overview camera icon doesn't change its appearance on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3042]
**Mapbox Navigation SDK version:** `2.0.0-beta.11`

### Steps to reproduce

 1. Start active guidance Navigation on CarPlay.
 2. Switch camera to overview mode.
 3. Verify that overview camera icon doesn't change its appearance.

### Expected behavior

Overview camera icon should change its appearance.

### Actual behavior

Overview camera icon doesn't change its appearance. For example:

<img width="400" alt="Screen Shot 2021-05-30 at 11 37 25 PM" src="https://user-images.githubusercontent.com/1496498/120119465-ada6d800-c14c-11eb-95ab-797a5844e84c.png">

**Comment by 1ec5** [comment]
Related to-do comments:

https://github.com/mapbox/mapbox-navigation-ios/blob/39bcdb29a2386bd6d7fd3eb311b7b9bf0a710149/Sources/MapboxNavigation/CarPlayManager.swift#L557 https://github.com/mapbox/mapbox-navigation-ios/blob/39bcdb29a2386bd6d7fd3eb311b7b9bf0a710149/Sources/MapboxNavigation/CarPlayManager.swift#L584
