### ISSUE TITLE
Navigator starts before the present of navigationViewController in Example

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3060]
**Mapbox Navigation SDK version:** `release-v2.0`

Crash sometimes occurs right after starting active guidance navigation in Example app.

Crash log:
[Example_2021-06-08-153112_MacBook-Pro.txt](https://github.com/mapbox/mapbox-navigation-ios/files/6616408/Example_2021-06-08-153112_MacBook-Pro.txt)

**Comment by ShanMa1991** [comment]
According to the log below, the sequence when we call `func presentAndRemoveNavigationMapView(_:completion:)` in ViewController is as:
```
1. navigator starts, providing route progress
2. Two location updates source exist, one from the still existing navigationMapView with the `passiveLocationManager`, one from the navigator
3. the `present(navigationViewController, animated: true)` is called, the navigationMapView is later removed from the superView and set to nil, only one location update source exists.
```
So when we try to start the navigation, the navigator starts before the navigationMapView is removed. It caused rerouting behavior under simulation and also the previous crush.

**Comment by 1ec5** [comment]
This issue appears to be unreproducible and may have gone away with newer versions of MapboxNavigationNative. Please reopen if the crash persists.
