### ISSUE TITLE
`UserCourseView` is visible in `NavigationMapView` on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3071]
**Mapbox Navigation SDK version:** `release-v2.0`

`UserCourseView` is visible in `NavigationMapView` on CarPlay:

<img width="400" alt="Screen Shot 2021-06-11 at 12 23 14 PM" src="https://user-images.githubusercontent.com/1496498/121664810-bb1d6580-ca5c-11eb-8a81-b81a2dde31de.png">

This might be a regression, which was caused by https://github.com/mapbox/mapbox-navigation-ios/pull/2968.

By default `UserCourseView` should not be visible in preview mode on both iOS and CarPlay.

/cc @ShanMa1991

**Comment by ShanMa1991** [comment]
Fixed in #3075
