### ISSUE TITLE
Fix failing MapboxCoreNavigation unit tests.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3078]
**Mapbox Navigation SDK version:** `2.0.0-beta.13`

In scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3039 such unit-tests were temporarily commented out:
- testNotReroutingForAllSteps
- testNewStep

to prevent sporadic build failures. 

In scope of this ticket these unit-tests should be enabled and if needed re-written to accomodate new Navigation Native behavior.

/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
UPD:
`testNotReroutingForAllSteps` may have been related to internal NN behavior. I've requested some help on this topic.
`testNewStep` is working fine with NN v53.0.1, but enabling it makes another test (`testOrderOfExecution`) fail. I see there are log messages about NN skipping some location updates during test. Hopefully it will be resolved together with previous point.

**Comment by S2Ler** [comment]
All tests from this issue restored after #3401 is merged
