### ISSUE TITLE
Move "Example", "Example-CarPlay", "Bench", "BenchTests" to separate project

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3104]
Currently, our `MapboxNavigation.xcodeproj` project contains SPM dependency for "Example", "Example-CarPlay", "Bench", "BenchTests" which isn't needed for "MapboxCoreNavigation", "MapboxNavigation" and corresponding tests. The problem is that when we build "MapboxCoreNavigation", "MapboxNavigation" on CI, the `xcodebuild` also downloads not relevant SPM dependency, which takes a considerable amount of time. 

By separating the targets, we will:
1. Safe money on CircleCI.
2. Reduce the time it takes to run CI workflows.

cc @mapbox/navigation-ios

**Comment by zugaldia** [comment]
Does a new project mean a new repo (e.g. https://github.com/mapbox/mapbox-navigation-ios-examples), or within this repo?

**Comment by S2Ler** [comment]
Given that we use this Example project as a playground for development, these target shall stay in the same (this) repository.

**Comment by 1ec5** [comment]
Splitting the Example target into a separate project will also allow us to remove SPM-related settings from the remaining Carthage-based project. We’ll be able to open and build that project faster, and Xcode’s project navigator and project find won’t get confused by the presence of two items in the project structure named MapboxNavigation.

**Comment by S2Ler** [comment]
@mapbox/navigation-ios How "BenchTests" and "Bench" are supposed to be used? Do we still need these targets?
