### ISSUE TITLE
mapbox-navigation-ios arm64

### ISSUE THREAD

**Issue by Martifan** [mapbox/mapbox-navigation-ios#3119]
**Mapbox Navigation SDK version: 1.4**

### Steps to reproduce
Hello I am trying to install Mapbox Navigation SDK for iOS on Apple Silicon Mac (arm64) processor
 1. cd ~ (go to the home directory)
touch .netrc (create file)
open .netrc (open .netrc)
Set required data.
Save
 2. Create Podfile (pod init)
 3. I open and add text (pod 'MapboxNavigation', '~> 1.4') and saved
 4. I run the command to install the library (pod install) 

### Actual behavior
**I get an error**

```
Installing Mapbox-iOS-SDK (6.3.0)
[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/_l/8x9m9wv16hn8xn_3jk1pfk9m0000gn/T/d20210626-9032-colqj3/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
```
**help me please any ideas**
**Thanks in advance everyone**

**Comment by 1ec5** [comment]
> Hello I am trying to install Mapbox Navigation SDK for iOS on Apple Silicon Mac (arm64) processor

Note that navigation SDK v1._x_ unfortunately does not support Apple Silicon: #2672. Navigation SDK v2.0, which is in beta, does support Apple Silicon.

Closing because it looks like your immediate issue with the download error has a resolution above. Please reopen if you continue to experience installation issues.
