### ISSUE TITLE
SimulatedLocationManager on long routes consumes a lot of CPU on the main thread

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3129]
**Mapbox Navigation SDK version:** release-v2.0 aa442b9191e8efe79cf35dd790526c8e3a45615b

### Steps to reproduce

 1. Take a 10000 km long route
 2. Start simulated navigation
 3. Check CPU usage on the main thread

### Expected behavior
SimulatedLocationManager doesn't consume a lot of CPU on the main thread.

### Actual behavior
SimulatedLocationManager consumes a lot of CPU on the main thread. 

### Proposed solution 

Move time consuming work in SimulatedLocationManager to a non-main DispatchQueue.

**Comment by truburt** [comment]
Nav Native also has some simulation capabilities, so we should also discuss if we'd like to extend it and move to it, cc @chezzdev
