### ISSUE TITLE
`update-version.sh` fails after introducing two xcprojects.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3143]
**Mapbox Navigation SDK version:** `main`

### Steps to reproduce

 1. Run `scripts/update-version.sh` from the root folder.

### Expected behavior

Script should not fail and increase version of the projects.

### Actual behavior

Script fails with error:
```
There are multiple projects in this directory.  agvtool does not work with multiple projects in the same directory.
```

**Comment by 1ec5** [comment]
Oof, I guess we can work around the issue by moving MapboxNavigation-SPM.xcodeproj aside while running `agvtool` on MapboxNavigation.xcodeproj and vice versa.
