### ISSUE TITLE
Edge case where RouteOptions having same start and end locations causes a crash

### ISSUE THREAD

**Issue by azharaali** [mapbox/mapbox-navigation-ios#315]
This would be an unusual case, however I experienced in my use case when trying to calculate the route between two coordinates which are same, it causes the app to crash in line 26 of RouteTableViewController `headerView.progress = CGFloat(routeController.routeProgress.fractionTraveled)`
Where `fractionTraveled` computed property ends up having a division by zero case:
`public var fractionTraveled: Double {
        return distanceTraveled / route.distance
    }` since route.distance ends up being zero

Some defense against this would be good so as to stop Mapbox from causing the app to crash

**Comment by bsudekum** [comment]
This bug has been fixed.
