### ISSUE TITLE
[!] Error installing Mapbox-iOS-SDK

### ISSUE THREAD

**Issue by subhani-ali** [mapbox/mapbox-navigation-ios#3160]
I am facing this issue: 

- [!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/45/5jgvsfg94l9flyj1ct03dn6w0000gn/T/d20210712-69158-vco2ko/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by usamadanish4** [comment]
+1

**Comment by sultan-arshi** [comment]
+1

**Comment by S2Ler** [comment]
Please follow the instructions on https://docs.mapbox.com/ios/navigation/guides/install/. In particular, make sure that you set up `.netrc` file correctly. It should be in the home directory: `~/.netrc`.

**Comment by S2Ler** [comment]
Closing the issue. If you still have the issue, feel free to reopen the ticket with the following details:
- [ ] `file ~/.netrc` command returns that the file exists. 
- [ ] My `.netrc` file contains the valid token with `Downloads:Read` permissions scope.
