### ISSUE TITLE
NavigationViewController lag issue

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#317]
hi, I am using a gpx file to test the navigationViewController, the controller is laggy when it reroute every time. Also, I feel laggy when I test it on the real driving.

**Comment by frederoni** [comment]
Interacting with the map view is not a smooth experience in the simulator, especially not when the traffic layer is turned on. Are you using the built-in gpx files or custom?

> Also, I feel laggy when I test it on the real driving.

What device are you testing on? What version of the SDK? Is the traffic layer enabled?

**Comment by zijiazhai** [comment]
hi frederoni, I am using a built-in gpx files, the device is iPhone 5s, the version of the SDK is the latest one 0.40, and the traffic layer is enabled. Thank you!
