### ISSUE TITLE
Color-code traffic congestion along route line

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#319]
NavigationMapView should display color-coded segments along the route line indicating where there’s traffic congestion. Here’s what it looks like in an internal application based on this SDK:

![congestion](https://user-images.githubusercontent.com/1231218/27666581-9553a382-5c29-11e7-93bf-38b2a8bf9fa9.png)

This feature would build on the route line customization hooks added in #116 and #135. It would require the congestion level attribute added in mapbox/MapboxDirections.swift#123 and would only be functional when the profile is set to `automobileAvoidingTraffic`.

/cc @bsudekum @frederoni @ericrwolfe @ericdeveloper

**Comment by ericrwolfe** [comment]
Closed via https://github.com/mapbox/mapbox-navigation-ios/pull/359
