### ISSUE TITLE
Migrate classes to core navigation

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#321]
Some of the following classes and logic would be useful to move over to MapboxCoreNavigation from the UI module, to give developers better building blocks for creating custom navigation apps from scratch:

- [x] Distance formatter
- [x] Location simulation
- [ ] Voice instruction formatting (should be extracted from voice controller) #367 
- [ ] Voice controller
- [ ] Location snapping #373 

cc @bsudekum @frederoni

**Comment by 1ec5** [comment]
We performed the most straightforward parts of this task in #309 and #310. Moving to v0.6.0 for the rest.

**Comment by frederoni** [comment]
> Voice instruction formatting (should be extracted from voice controller)

Requires adding OSRMTextInstructions.swift as a dependency to core navigation.

**Comment by ericrwolfe** [comment]
@frederoni seems like OSRMTextInstructions.swift is already a dependency of Core Navigation, at least in Cocoapods land: https://github.com/mapbox/mapbox-navigation-ios/blob/c113e518aa38274cf67d64d95c4cb638e732c0a7/MapboxCoreNavigation.podspec#L44

**Comment by 1ec5** [comment]
Heh, that was probably an oversight, but I guess it’s OK to have Core Navigation depend on OSRM Text Instructions. The more important consideration is making Polly an optional dependency somehow, because the AWS dependencies are enormous compared to Core Navigation proper.

**Comment by bsudekum** [comment]
The checklist has been moved to core.
