### ISSUE TITLE
Transitioning from day to night removes the route polyline from the map

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#3212]
**Mapbox Navigation SDK version: 1.4.2**
CocoaPods 1.10.1
Xcode 12.5.1
iPhone 12 Pro (iOS 14.6) and iPad mini 4 (iPadOS 14.4)

_This issue only happens when NavigationViewController is embedded as a child controller._

### Steps to reproduce

 1. Embed the instance of NavigationViewController as a child controller instead of presenting it modally.
 2. Do not override its `styleManager.delegate`.
 3. Wait for a night transition or open Settings and change the system time to trigger one.

### Expected behavior

When transitioning to night, the route polyline should not disappear when you reenter the app.

### Actual behavior

When you reenter the app, the route polyline will be removed from the map. Everything else successfully transitioned to night mode, including the map style.

### Notes

If the NavigationViewController is embedded as a child, the only way I have been able to work around this issue is to:
- hook the NavigationViewController's `styleManager.delegate` in the parent controller
- proxy all the delegate methods to the NavigationViewController except `styleManager(_: viewForApplying:)`
- for `styleManager(_: viewForApplying:)`, return a view higher up the hierarchy, like `self.view` or `self.view.superview`

Gist with the code to reproduce the issue: https://gist.github.com/johnnewman/b2e634c51dbfc27bfbe5f565ee7cd0b6
[Video showing the issue](https://drive.google.com/file/d/1DnPgQQEmoz2xmPzHgmmUlzm1HxmTA-j5/view?usp=sharing) (too large for GitHub)

If NavigationViewController is presented modally, I don't see the bug and there's no need to hook the StyleManager's delegate. This appears related to the changes in https://github.com/mapbox/mapbox-navigation-ios/pull/2897. (Thank you for fixing the iOS 14 SwiftUI bug!)

**Comment by MaximAlien** [comment]
Hello @johnnewman. I think similar issue was reported some time ago in https://github.com/mapbox/mapbox-navigation-ios/issues/2545 for `1.x` and it was fixed in Navigation SDK `2.0`, so my question is: would you be able to switch to Navigation SDK 2.0 (it's still in beta, but pretty stable at this point). `1.x` is mostly in maintenance mode at this point.

**Comment by johnnewman** [comment]
Hi @MaximAlien, thanks for the insight. If this bug is fixed in SDK 2.0, that's great. With the workaround mentioned in the description, we can work around the bug until we decide to upgrade our app to v2.0.

**Comment by MaximAlien** [comment]
@johnnewman, here's PR which fixes similar issue in `2.0`: https://github.com/mapbox/mapbox-navigation-ios/pull/3136. If you don't mind I'll close this ticket as we already have one in https://github.com/mapbox/mapbox-navigation-ios/issues/2545.
