### ISSUE TITLE
Change user location to custom image wehn in turn by turn navigation

### ISSUE THREAD

**Issue by nick70007** [mapbox/mapbox-navigation-ios#3213]
Hello sir,
I want to change user location image to custom image let's say car image when in turn by turn navigation mode but i am unable to change. below is the screenshot
![Simulator Screen Shot - iPhone 11 - 2021-07-30 at 09 51 00](https://user-images.githubusercontent.com/52743988/127599893-83575f63-2e04-43ba-a671-ce2623e5d9c9.png)
and below is the code snippet of what i have tried:

How can i set custom puck to default puck using external xib view which i have created and the code is below:
class CustomPuckView: UIView {

    @IBOutlet var contentView: UIView!
    
    //MARK:- Life Cycle
    override init(frame: CGRect) {
        super.init(frame: frame)
        configureView()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        configureView()
    }
    
    func configureView() {
        contentView = configureNib()
        contentView.frame = bounds
        contentView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        addSubview(contentView)
    }
   
    func configureNib() -> UIView {
        let bundle = Bundle(for: type(of: self))
        let nib = UINib(nibName: "CustomPuckView", bundle: bundle)
        let view = nib.instantiate(withOwner: self, options: nil)[0] as! UIView
        return view
    }
}

func setNVMapNavigationData(_ route : Route, routeOptions: NavigationRouteOptions,mHeight:CGFloat) {
        
        self.nvMAp = NavigationViewController(for: route, routeIndex: 0, routeOptions: routeOptions)
        self.nvMAp.delegate = self
        self.nvMAp.routeLineTracksTraversal = true
        self.nvMAp.mapView?.delegate = self
        self.nvMAp.mapView?.camera.pitch = 100
        self.nvMAp.mapView?.attributionButton.isHidden = true
        self.nvMAp.showsEndOfRouteFeedback = false
        self.add(asChildViewController: self.nvMAp)
        self.nvMAp.navigationService.start()

        let img : UIImage = UIImage(named: "ic_carMarker")!
        let imgView : UIImageView = UIImageView(image: img)
        imgView.frame = (self.nvMAp.mapView?.userCourseView.bounds)!
        imgView.contentMode = .scaleAspectFit
        self.nvMAp.mapView?.userCourseView.bringSubviewToFront(imgView)
        self.nvMAp.mapView?.userCourseView.addSubview(imgView)
        
        self.nvMAp.view.frame = CGRect(x: 0, y: 0, width: self.vWidth, height: (self.vHeight - 130))
        
//        self.nvMAp.viewFrame = CGRect(x: 0, y: 0, width: self.vWidth, height: (self.vHeight - 130))
        self.nvMAp.viewDidLayoutSubviews()
        self.vMapBoxView.isHidden = false
        self.vMapBoxViewBottom.constant = self.vRide.frame.size.height
        self.vMapBoxView!.frame = CGRect(x: 0, y: 0, width: self.vWidth, height: mHeight - self.LblOnOff.frame.size.height)

        if let coordinates = self.nvMAp.route.shape, let userLocation = self.nvMAp.mapView?.userLocation?.location {
            
            delay(durationInSeconds: 0.01) {
                CATransaction.begin()
                CATransaction.setValue(2.0, forKey: kCATransactionAnimationDuration)
                CATransaction.setAnimationTimingFunction(CAMediaTimingFunction(name: CAMediaTimingFunctionName.easeInEaseOut))
                self.nvMAp.mapView?.setOverheadCameraView(from: userLocation, along: coordinates, for: UIEdgeInsets(top: 50, left: 50, bottom: self.vRide.frame.height + 50, right: 100))
                CATransaction.commit()
            }
        }
        
        DispatchQueue.main.async {
            self.HideExtraButtonAndBanner()
        }
    }
    
    // MARK: - MapBox Action
    func setNVMap(_ route : Route, routeOptions: NavigationRouteOptions)
    {
        var mHeight : CGFloat = CGFloat()
        if self.isSwipe == 2 || self.isSwipe == 4
        {
            mHeight = currentDevice == "X" ? (self.vHeight - (56 + 72 + self.topPadding + self.LblOnOff.frame.size.height)) : (self.vHeight - (36 + 72 + self.topPadding + self.LblOnOff.frame.size.height))
        }
        else if self.isSwipe == 1 || self.isSwipe == 3
        {
            mHeight = self.vHeight - (self.vRide.frame.size.height + self.topPadding + self.LblOnOff.frame.size.height)
        }

        if self.vMapBoxView.subviews.count > 0
        {
            self.isNavigationStarted = false
            self.remove(asChildViewController: self.nvMAp)
            self.setNVMapNavigationData(route, routeOptions: routeOptions, mHeight: mHeight)
        }
        else
        {
            self.setNVMapNavigationData(route, routeOptions: routeOptions, mHeight: mHeight)
            self.nvMAp.navigationController?.isNavigationBarHidden = true
        }
    }

**Comment by MaximAlien** [comment]
Hello @nick70007. We're currently in process of developing new version of Navigation SDK 2.0 (it's in beta now), which uses new version of [Mapbox Maps](https://github.com/mapbox/mapbox-maps-ios). One of the features of Navigation SDK 2.0 is the ability to show 2D and 3D pucks. It can be controlled via `NavigationMapView.userLocationStyle` property. We also have [example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Custom-User-Location.swift) here.

Would you be interested in using Navigation SDK 2.0 in first place?

**Comment by nick70007** [comment]
lets say i dont want to update to v2 as it gives me lots of error of deprecation thats why i reverted it to default. So in my current version is it possible to add custom puck image
