### ISSUE TITLE
SimulationMode Improvements

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3216]
This is a cut from #2365 PR, see original discussion there. 

Action points:
- [ ] Introduction of a new simulation mode: .inTunnels
- [ ] Make simulation mode more discoverable. 

cc @mapbox/navigation-ios @LukasPaczos @Guardiola31337 @Skoti

**Comment by Udumft** [comment]
As I got from linked ticket, current proposal is next:
* Introduce additional simulation mode `.inTunnels`, which will kick in simulation when 1) poor GPS signal (same logic as in `.onPoorGPS`), 2) [SDK detects](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxCoreNavigation/NavigationService.swift#L292) current location as in tunnel.
* make `inTunnels` a default simulation mode(?)
* add `SimulationMode` setting to `NavigationOptions`

Is there any other user-requests or ideas regarding this topic? Or do you know of potential issues?
/cc @mapbox/navigation-ios
