### ISSUE TITLE
Rename RouteController

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#322]
From user testing, we've found that the class name `RouteController` is confusing and developers have a tendency to reach for it instead of `NavigationViewController` thinking it's a view controller subclass that they can use.

We should rename it to something that follows the iOS `*Manager` paradigm (e.g. `CLLocationManager`, `CMMotionManager`). 

Ideas:
* `NavigationManager`
* `RouteManager`
* `GuidanceManager`

cc @frederoni @bsudekum @ericdeveloper

**Comment by 1ec5** [comment]
“Manager” is not so much a paradigm as it’s a last resort in API naming. 😉 On the other hand, there is precedent for naming something “manager” if it can be said to be managing (that is, manipulating) something, as FileManager manages files, UndoManager manages the undo stack, CLLocationManager manages the location sensors, and so on.

NavigationManager does have a nice parallel to NavigationViewController. RouteManager is misleading in that it’s largely reactive; it doesn’t primarily manipulate the route.

Are there any alternatives beyond “manager”?

* LocationInterpreter
* RouteProgressManager
* RouteObserver – which would entail renaming `suspendLocationUpdates()` to `stopObserving()`
