### ISSUE TITLE
Route preview doesn't show route line on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3228]
**Mapbox Navigation SDK version:** `v2.0.0-beta.21`

### Steps to reproduce

 1. Open Example-CarPlay application on CarPlay.
 2. Search for destination and select it.
 3. Observe behavior.

### Expected behavior

It is expected that after selecting specific route on route preview screen it is shown on the map.

<img width="400" alt="Screen Shot 2021-08-09 at 12 44 20 PM" src="https://user-images.githubusercontent.com/1496498/128764892-c7e1da4a-ba5b-4226-82e5-7c44366bf370.png">

### Actual behavior

<img width="400" alt="Screen Shot 2021-08-09 at 12 41 43 PM" src="https://user-images.githubusercontent.com/1496498/128764838-19edc9a1-e23f-43bc-b89f-bf40c243fc46.png">

This issue is a regression after landing https://github.com/mapbox/mapbox-navigation-ios/pull/3182.

**Comment by ShanMa1991** [comment]
The problem is here :

https://github.com/mapbox/mapbox-navigation-ios/blob/40b17184f7b67f0019121cdedad190df55b9ea00/Sources/MapboxNavigation/CarPlayManager.swift#L640-L641
