### ISSUE TITLE
Growing back vanishing route line if user moves past destination

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3267]
**Mapbox Navigation SDK version:** 2.0.0-beta.23

### Steps to reproduce

 1. Checkout "s2ler/rerouting-debug" branch and run Example
 2. Simulate a drive
 3. Drive past destination

### Expected behavior
Vanishing route line stops changing.

### Actual behavior
Vanishing route line starts growing back.

https://user-images.githubusercontent.com/413986/129866155-71a39a66-1fae-4dc5-af55-d6877c58a216.mp4

**Comment by S2Ler** [comment]
Can be moved to v2.1RC if needed.

**Comment by S2Ler** [comment]
Related #3255

**Comment by ShanMa1991** [comment]
It should be fixed in #3218 and #3255 .

**Comment by ShanMa1991** [comment]
It's fixed in #3255 .
