### ISSUE TITLE
Audio alerts don't work if app is in the background

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#328]
If the app is moved into the background, audio alerts are no longer announced, even though local notifications appear. 

This is separate from the issue with no audio while the vibrate switch is enabled.

cc @bsudekum

**Comment by 1ec5** [comment]
Does the application have the `audio` `UIBackgroundMode` in Info.plist? Is the application using Polly, or is it using (or falling back to) the built-in AVSpeechSynthesizer?
