### ISSUE TITLE
Make `NavigationViewportDataSourceOptions` more restrictive.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3281]
**Mapbox Navigation SDK version:** `main`

At this point `NavigationViewportDataSourceOptions` contains various options, which allows to control camera behavior. Types of certain options are pretty tolerant to values, which can be set by the end user. For example `FollowingCameraOptions.maximumZoomLevel` uses `Double`, which might lead to some undefined behavior if value is not set within 0 to 22 zoom level range.

In scope of this ticket such APIs should be revised and updated to be more restrictive.

**Comment by 1ec5** [comment]
Also make this type and its initializer `open`.
