### ISSUE TITLE
Need to manually clean up NavigationViewController resources when using NavigationMapView injection

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#3286]
**Mapbox Navigation SDK version:** 2.0.0-beta.22

When using the NavigationMapView injection API, it is currently the responsibility of the API consumer to clean up after NavigationViewController when navigation has completed. 

### Expected behavior

Either:
- NavigationViewController removes annotations and other resources it has added to NavigationMapView when it is removed

or

- NavigationViewController exposes a method for removing all resources and leave it to the API consumer to call this (if desired)

### Actual behavior

No cleanup occurs. Route lines and annotations are still rendered on the map.

### Workaround

Calling the following methods on NavigationMapView when finished with navigation seems to do the trick:

```swift
removeArrow()
removeRoutes()
removeWaypoints()
```

**Comment by MaximAlien** [comment]
After some investigation I came to a conclusion that Navigation SDK should not be responsible for any clean-up. Idea is to leave `NavigationMapView` in almost the same state as it was before active navigation. Most agile behavior would be to leave it up to users to decide what to do after finishing active navigation, so I'd recommend using delegate methods like `NavigationViewControllerDelegate.navigationViewControllerDidDismiss(_:byCanceling:)` to know when `NavigationViewController` is no longer present.

We currently modify some `NavigationMapView` properties during active navigation, but do not reset them correctly, this leads to undefined behavior. Ticket, which tracks re-work there can be found here: https://github.com/mapbox/mapbox-navigation-ios/issues/3576.
