### ISSUE TITLE
Update camera behavior upon exiting NavigationViewController when using NavigationMapView injection

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#3287]
**Mapbox Navigation SDK version:** 2.0.0-beta.22

When using the NavigationMapView injection API, it seems reasonable the consumer of the API will wish to reset the map's camera after navigation has completed. Currently, there are a few methods that need to be called to cancel out NavSDK-defined behavior of the camera before applying any custom camera animation.

### Expected behavior

Camera animations may be applied after exiting NavigationViewController without needing to manually cancel existing camera animations.

### Actual behavior

Camera animations need to be manually cancelled before applying any new animation.

### Workaround

This is what I'm calling currently and it seems to work well. I'm not sure if `endNavigation` is absolutely necessary, but it doesn't seem to hurt anything so I've kept it in (if it is unnecessary feel free to ignore!).

```swift
navigationViewController.navigationService.endNavigation(feedback: nil)
navigationMapView.mapView.camera.cancelAnimations()
```

**Comment by MaximAlien** [comment]
This task is a bit more complex than it looks. In case of `NavigationMapView` injection we override certain properties of injected `NavigationMapView` (e.g. `delegate`, `navigationCamera` etc). At the same time we do not remember modified properties. This can lead to unpredicted behavior like using incorrect `NavigationMapView.delegate` or `NavigationViewportDataSource.viewportDataSourceType`. I was thinking about some generic `NavigationMapView` copy mechanism in case of its override, but it doesn't seem to work well with Maps SDK classes. 

I think at this point the best option is to go through all properties, which are changed by `NavigationViewController`, cache them, and then re-apply back during dismissal.

**Comment by MaximAlien** [comment]
I'm closing this issue in favor of https://github.com/mapbox/mapbox-navigation-ios/issues/3576. Some insight about the reason can be found here: https://github.com/mapbox/mapbox-navigation-ios/issues/3286#issuecomment-964676892. The reason camera behavior is different after finishing active navigation is that `NavigationView` overrides camera data source in: 
https://github.com/mapbox/mapbox-navigation-ios/blob/1c07425c8470be69f891fc78feae5e14dd58196c/Sources/MapboxNavigation/NavigationView.swift#L74-L76

but doesn't revert it back, so canceling animations will not help here. In scope of https://github.com/mapbox/mapbox-navigation-ios/issues/3576 we'll be able to reset back to original camera source, which should in turn fix issue reported here.
