### ISSUE TITLE
Enable NavigationView elements to be animated into position on load of NavigationViewController

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#3288]
**Mapbox Navigation SDK version:** 2.0.0-beta.22

Currently there isn't a publicly accessible means to animate the different UI elements of NavigationView into place when a NavigationViewController is loaded. My particular use case is with NavigationMapView injection, but I could see this also being beneficial for other consumers of NavigationViewController who aren't necessarily using the injection API.

For my use case I walk the view hierarchy and manipulate the views manually to achieve a fade / slide-in effect. I have a method on NavigationViewController I defined to do this:

```swift
func setSubviewsHidden(_ hidden: Bool, animated: Bool, completion: ((Bool) -> Void)? = nil) {
    // Walk the view hierarchy looking for top and bottom banner containers. We'll animate those into position
    // and modify the alpha channel for everything else.
    let bannerSubviews = view.subviews
        .compactMap { $0 as? BannerContainerView }
    let otherSubviews = view.subviews.filter { !($0 is BannerContainerView) && $0 !== navigationMapView }

    bannerSubviews.forEach { $0.layoutIfNeeded() }
    let animations = {
        otherSubviews.forEach { $0.alpha = hidden ? 0 : 1 }
        bannerSubviews.forEach { banner in
            banner.alpha = hidden ? 0 : 1
            if hidden {
                let translationYComponent: CGFloat = (banner.center.y < (self.view.frame.height / 2)) ? -1 : 1
                banner.transform = .init(translationX: 0, y: banner.frame.height * translationYComponent)
            } else {
                banner.transform = .identity
            }
        }
    }

    if animated {
        UIView.animate(withDuration: 0.5, animations: animations, completion: completion)
    } else {
        animations()
        completion?(true)
    }
}

```

Obviously this isn't ideal because any change to the structure / typing of NavigationView and its subviews could break this logic. If NavigationView and its subviews were public, walking the hierarchy would no longer be necessary.

Another option would be to define a few pre-baked animation styles for entry and exit that had completion handlers for the end of the animation.

Here's an example of what this animation looks like in action:

https://user-images.githubusercontent.com/630204/130254608-e6ef4f33-be6f-4c0f-b502-68b4569e6224.mp4

**Comment by 1ec5** [comment]
Perhaps a more concise, robust workaround would be to pretend to customize the top banner: create an instance of the usual TopBannerViewController and pass it into NavigationOptions; now you have a reference to that view controller and its subviews.

If you do need access to the container view itself, I suppose we could expose `NavigationView.topBannerContainerView` publicly, but it would be nice to know if there are any use cases for that sort of access beyond animation. For animation specifically, we could consider an optional, built-in animation whenever a map view gets injected, because we would expect the developer to not want a jarring pop-in effect for the banners.

**Comment by MaximAlien** [comment]
Top and bottom banner container views can now be shown and hidden in animated way. See `BannerContainerView.swift` in https://github.com/mapbox/mapbox-navigation-ios/pull/3758.
