### ISSUE TITLE
Abridge instructions under time pressure

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#331]
When a maneuver is impending or two maneuvers are close enough to be linked together, the SDK should progressively shorten the instruction to comfortably fit within the available time. For example, an [on-ramp instruction](http://map.project-osrm.org/?z=18&center=39.098600%2C-84.509609&loc=39.098540%2C-84.509958&loc=39.099339%2C-84.504942&hl=en&alt=0) like:

> Take the ramp on the left towards US 50 East: Columbia Parkway

might be shortened to:

> Take the ramp on the left towards US 50 East

or:

> Take the ramp on the left

depending on the time remaining until the user reaches the maneuver point. It’s the voice analogy to the road name abbreviation we implemented for the turn banner in #215.

Besides optimizing for rapid-fire scenarios, this change would also improve the behavior of this SDK in certain localizations where the instruction strings tend to be longer, such as Spanish.

/cc @bsudekum @frederoni @freenerd

**Comment by bsudekum** [comment]
The text for instructions is now coming from the server. Moving this upstream.
