### ISSUE TITLE
user-agent doesn't include SDK versions when SPM is used.

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3312]
**Mapbox Navigation SDK version:** v2.0.0-beta.24

The implementation from https://github.com/mapbox/mapbox-navigation-ios/blob/d2e6223dceae929c7affb95709494a4a6d968a94/Sources/MapboxCoreNavigation/URLSession.swift#L10-L66 doesn't work with SPM based distribution.

**Comment by ShanMa1991** [comment]
The implementation of the `stringForShortVersion` from the `MBXInfo`, is because the SPM would automatically generate the `Info.plist ` which doesn't contain some certain keys, which include the bundle short version string. I'm not sure how it works right now with the SPM.
