### ISSUE TITLE
3d puck not being set

### ISSUE THREAD

**Issue by nick70007** [mapbox/mapbox-navigation-ios#3328]
i am trying to set 3d puck configuration as given in your example but it is crashing. it says: Fatal error: 'try!' expression unexpectedly raised an error: MapboxMaps.StyleError(rawValue: "Source \'puck-model-source\' not found")

**Comment by ShanMa1991** [comment]
Hi @nick70007, I tried to set the 3D puck for `userLocationStyle` in our latest version,  and it works as expected.

Could you check your 3D puck Model configuration, especially the `Model(uri:position:orientation:)` configuration?  The `orientation` for the 3D Model source should be `[Double, Double, Double]` format, while the `position` should be `[longitude, latitude]` in ` [Double, Double]` format.  

And for the `Puck3DConfiguration(model: modelScale:modelRotation:)`, the `modelRotation` is `[lon, lat, z]` in `[Double, Double, Double]` format, and the `modelScale` also in `[Double, Double, Double]` format.

**Comment by nick70007** [comment]
What model did you used..i have used as it was in the example but didnt
worked for me

**Comment by ShanMa1991** [comment]
Hi @nick70007, have you put your model file, the `.gltf` format file in the associated bundle?

**Comment by nick70007** [comment]
Yes, I did.

**Comment by nick70007** [comment]
Acrually i have used a file from the example which was from nasa link. Can
you tell me exactly where can i get free .gltf format so that i can test if
its working or not
