### ISSUE TITLE
[Bug]: PassiveLocationManager not stopped

### ISSUE THREAD

**Issue by Udumft** [mapbox/mapbox-navigation-ios#3329]
### Mapbox Navigation SDK version

v2.0.0-beta.25

### Steps to reproduce

1. Run Example App
2. FreeDrive starts
3. [Optional] disable route simulation
3. Build a route and start Active Guidance session

### Expected behavior

If route simulation is enabled, user puck should traverse the route. No warnings pushed to the log.

### Actual behavior

Debug log is spammed with messages like:
```
2021-09-06 16:37:50.155748+0300 Example[5326:4424383] Warning: <nav-native> Location at timestamp 1630935470000145408ns was filtered out.
2021-09-06 16:37:50.155895+0300 Example[5326:4424647] Warning: <nav-native> Got location timestamp from the past: 1630935471000145408ns <= 1630935471000145408ns. No status will be produced.
```
If route simulation was enabled - user puck jumps between traversing route and origin point until freezes.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Quick check showed that this is caused by `PassiveLocationManager` not being shut down when starting ActiveGuidance, which results in `Navigator` being fed with duplicate location data. This issue seems to affect CarPlay too.

**Comment by bamx23** [comment]
My bad, thanks for mentioning it. And thanks @S2Ler for fixing it in #3147.
