### ISSUE TITLE
[Bug]: Paused billing trip sessions might result in requests made inside NavNative billed per request

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3348]
### Mapbox Navigation SDK version

v2.0.0-rc.1

### Steps to reproduce

1. Start passive navigation with PassiveLocationManager
2. Pause trip session with `pauseTripSession`
3. Continue driving in passive navigation

### Expected behavior

NavNative's Navigator isn't updated with locations so that it won't try to download tiles. 

### Actual behaviour

NavNative's Navigator continues to work and download tiles.

### Is this a one-time issue or a repeatable issue?

repeatable

# Sub tasks
- [ ] Integrate pause/resume from NavNative.

**Comment by 1ec5** [comment]
On that note, should `PassiveLocationProvider.stopUpdatingLocation()` call `PassiveLocationManager.pauseTripSession()`? The map SDK automatically calls `PassiveLocationProvider.stopUpdatingLocation()` when the application goes to the background or the screen is locked.

**Comment by S2Ler** [comment]
I thinking of deprecating `PassiveLocationManager.startUpdatingLocation` and make it call `PassiveLocationManager.resumeTripSession` where `PassiveLocationManager.resumeTripSession ` will resume location updates and resume billing session. And make `PassiveLocationProvider.stopUpdatingLocation` call `PassiveLocationManager.pauseTripSession` that will also pause location updates. 

@1ec5 How does it sound to you?

**Comment by 1ec5** [comment]
> I thinking of deprecating `PassiveLocationManager.startUpdatingLocation` and make it call `PassiveLocationManager.resumeTripSession` where `PassiveLocationManager.resumeTripSession ` will resume location updates and resume billing session. And make `PassiveLocationProvider.stopUpdatingLocation` call `PassiveLocationManager.pauseTripSession` that will also pause location updates. 

https://github.com/mapbox/mapbox-navigation-ios/pull/3362#pullrequestreview-755676216
