### ISSUE TITLE
Planning to release v2-beta or v2-rc MapboxNavigation in CocoaPods?

### ISSUE THREAD

**Issue by oguzhnatly** [mapbox/mapbox-navigation-ios#3357]
The latest version in [CocoaPods/Specs/MapboxNavigation](https://github.com/CocoaPods/Specs/tree/master/Specs/5/8/b/MapboxNavigation) is 1.4.2 which does not support arm64. MapboxNavigation does not have any v2 version in cocoapods. Currently, Podspec does not have a method to install dependency directly from git.

If there is no critical bug in the SDK, could you please release the v2 version as a beta or rc and make them available at least? If not, what is the estimated date you will release?

Thanks.

**Comment by S2Ler** [comment]
Hi @oguzhnatly, we will discuss this today within the team. So far, I think we should release RC1 to CocoaPods, stay tuned.

**Comment by azarovalex** [comment]
@oguzhnatly Hi! Can you, please, share what are you trying to achieve, so we can better understand the use cases of our library? 

RC and beta version of our library can be already integrated inside of an application using these lines in `Podfile`.
```
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-rc.1'
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-rc.1'
```

Why do you want to use `Podspec` file?

**Comment by oguzhnatly** [comment]
Hi @azarovalex,

I'm trying to import v2-rc MapboxNavigation and MapboxCoreNavigation into a package that will be used in Google's Flutter Architecture to handle the package's interdependencies using `Podspec`. Besides that, I need to develop the package with my M1, and the Mapbox Navigation SDK for iOS v1 does not support arm64. The source of dependencies cannot be specified in the podspecs, according to [CocoaPods/issues/922](https://github.com/CocoaPods/CocoaPods/issues/922#issuecomment-15771597). We can only use the `s.dependency 'MapboxNavigation', 'v2.0.0-rc.1'`, according to [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html#dependency), but [there](https://github.com/CocoaPods/Specs/tree/master/Specs/5/8/b/MapboxNavigation) is no matched version in Cocoapods, that's why it cannot be installed.

In addition, I discovered a solution but it did not work. I've developed a new Framework that uses v2.0.0-rc.1 MapboxNavigation and MapboxCoreNavigation, using `Podfile` as you described the way, for the package to be used in `Podspec`, but every time the framework is linked to Xcode Development Pods Project, the iOS 14 app crashes immediately after it is initialized, due to Fatal `MapboxNavigation_MapboxCoreNavigation` Bundle Error.

![Screen Shot 2021-09-13 at 14 31 01](https://user-images.githubusercontent.com/54781138/133076138-4ec69ff2-b71f-4edb-a361-84dfa428ad08.png)

To sum it all up, the only way to install v2-rc MapboxNavigation **more securely and cleanly** is that it should be released in CocoaPods. Everything will be perfectly alright at that point.

Thanks.

**Comment by 1ec5** [comment]
Agreed, your podspec would require a pod on CocoaPods trunk. We already push prereleases of MapboxDirections to the MapboxDirections-pre pod, so we can push corresponding MapboxCoreNavigation-pre and MapboxNavigation-pre pods to trunk for now, until we release v2.0.0. We can think of it as a beta release channel.

**Comment by 1ec5** [comment]
Podspecs for v2.0.0-rc.2 have been pushed to CocoaPods trunk under the `MapboxCoreNavigation-pre` and `MapboxNavigation-pre` pods in CocoaPods/Specs@9a8cab28d492eae7e3e5db76d1784e02a9ac571e and CocoaPods/Specs@cd854329207da524e0a56b2eea837fad1111f2ec. #3382 stages these podspecs during the release process.
