### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MapboxCommon"

### ISSUE THREAD

**Issue by xinghaizhiming** [mapbox/mapbox-navigation-ios#3358]
### Mapbox Navigation SDK version

1.4.2

### Steps to reproduce

1.pod 'MapboxNavigation', '~> 1.4.2'
2.pod 'MapboxSearchUI', ">= 1.0.0-beta.12", "< 2.0"
3.Run "pod repo update && pod install"

### Expected behavior

Successful installation

### Actual behavior

![image](https://user-images.githubusercontent.com/29653868/133057452-35f67e8d-1794-43dd-bff9-fe85d3a4b780.png)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by azarovalex** [comment]
@xinghaizhiming Hi, this particular beta version `MapboxSearchUI` is incompatible with this version of `MapboxNavigation`. 
I would advise you to use `MapboxSearchUI` `1.0.0-beta.11` and `MapboxNavigation` `2.0.0-rc.1`.

```
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-rc.1'
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-rc.1'
pod 'MapboxSearchUI', ">= 1.0.0-beta", "< 2.0"
````

**Comment by xinghaizhiming** [comment]
Thank you for your reply.
