### ISSUE TITLE
Destroy Navigator singleton along with last Navigator client

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3360]
# Description

There is no way to release the memory used by [Navigator](https://github.com/mapbox/mapbox-navigation-ios/blob/03f7871ad4894a41a7bc1595919214404079ced7/Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift#L5) once the [singleton](https://github.com/mapbox/mapbox-navigation-ios/blob/03f7871ad4894a41a7bc1595919214404079ced7/Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift#L45) is created. 

# Backward Compatibly

The change is backward compatible, but we should be careful when to destroy Navigator. 

# Proposed change

Destroy Navigator singleton along with the last Navigator client.

# Next

- [ ] Identify all the code which depends on shared `Navigator` to be alive.
- [ ] Investigate if we can manage `Navigator` lifetime safely or we need help from developers. If the latter, we can start thinking about how to change API in v3. 
- [ ] Implement the change that will destroy the `Navigator` singleton when the last object that depends on `Navigator` is destroyed. `Navigator` should be recreated next time needed.

**Comment by Udumft** [comment]
Resolved in #3724
