### ISSUE TITLE
roads are black and icon are blank sometimes

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#338]
@hi, guys, I am using version 0.4.0, this only appears on the device of iPhone 6 sometimes, but it is very annoying, please help. 
![wechat_image_20170630153328](https://user-images.githubusercontent.com/10751092/27920573-a71aabee-623a-11e7-9803-1a449ef4f32e.jpg)

**Comment by bsudekum** [comment]
@zijiazhai can you share your setup?
* simulator
* phone version
* ios version

**Comment by zijiazhai** [comment]
~ none
~ iPhone 6 and 5s
~ both 10.3.2
~ did not custom map style
![snip20170706_1](https://user-images.githubusercontent.com/10751092/27930060-e33cc754-625a-11e7-85fd-02be7a8f8b88.png)

icons are fine, black lines only appear a few times  on device of 5s.
but blank icons and black lines appear lots of times on device of iPhone 6.

**Comment by 1ec5** [comment]
#339 should’ve fixed this issue; it’ll be in v0.5.0. Please reopen this issue if you continue to experience the black lines and icons in master.

**Comment by bsudekum** [comment]
@1ec5 do you think #339 fixed the blank UI elements though?

**Comment by 1ec5** [comment]
Oh right, that change in itself does not fix the UI elements.

@zijiazhai, is your application's tint color white, by any chance? That would cause the user puck and overview button to appear to have no content. Does this issue persist if you give the NavigationViewController a different tint color?
