### ISSUE TITLE
Navigation not working when app going to background and back to foreground.

### ISSUE THREAD

**Issue by ronak4567** [mapbox/mapbox-navigation-ios#341]
When I start navigation and after my app going to background and I open app that time navigation not working properly.

**Comment by frederoni** [comment]
Thank you for your report.
Can you explain what's not working properly? Is the map view not updating your location?

**Comment by ronak4567** [comment]
I am checking demo project and select the source and destination location and click on simulates navigation then after few min app going to background and Reopen app that time current location icon not working properly icon going to other place

**Comment by frederoni** [comment]
Ok. Yep, I see there are two simulations running simultaneously. Working on a fix.

**Comment by ronak4567** [comment]
Thank You
