### ISSUE TITLE
`tryUnduckAudio` mutes the application audio

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#3433]
[Code in the function `tryUnduckAudio`](https://github.com/mapbox/mapbox-navigation-ios/blob/6b827eeb5009f0fe6ddf6db7fc61494232180d82/Sources/MapboxNavigation/AVAudioSession.swift) disables audio playback if it happens in the same application.
It works fine only if the audio is playing in another application.

**tl;dr:** We shouldn't call `setActive(false)` after announcing the voice instruction, because it disables audio in the whole application

**Comment by 1ec5** [comment]
As a workaround, the developer could implement `SpeechSynthesizingDelegate.speechSynthesizer(_:willSpeak:with:)` and `SpeechSynthesizingDelegate.speechSynthesizer(_:didSpeak:with:)` to call `AVAudioSession.setActive(_:)` on the shared audio session with the option `.notifyOthersOnDeactivation`.

/cc @avi-c

**Comment by azarovalex** [comment]
Fix is now available in this PR: https://github.com/mapbox/mapbox-navigation-ios/pull/3572
An application can set `managesAudioSession` flag to false and we won't mess with AVAudioSession ourselves.
