### ISSUE TITLE
[Enhancement] Original CPRouteChoice.userInfo data should not be overridden by a developer

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-navigation-ios#3435]
**Why**

As per [this code][1], `CPRouteChoice.userInfo` can be overwritten by a developer unknowingly and this can cause some code to not execute. 

**Proposals**

- Additional `userInfo` can be added to CPRouteChoice without modifying the data that navigation needs
- Create a detailed documentation on what parameters cannot be overwritten in `userInfo`

**Priority**

Low ~ Medium: There is no immediate impact at this moment but this is a known risk for current use.

[1]: https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-rc.3/Sources/MapboxNavigation/CarPlayManager.swift#L587

**Comment by MaximAlien** [comment]
Based on priority moved to `v2.2`.
