### ISSUE TITLE
[Bug]: Crashed navigation session. Precondition failed: The stepIndex is higher than steps count

### ISSUE THREAD

**Issue by DiegoResnik** [mapbox/mapbox-navigation-ios#3461]
### Mapbox Navigation SDK version

2.0 rc4

### Steps to reproduce

application crash due to navigation error:

MapboxCoreNavigation/RouteController.swift:284: Precondition failed: The stepIndex: 2 is higher than steps count: 2 of the leg :0 or not included. The old leg index: 0 will not be updated in this case.

Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x3a5a8 _assertionFailure(_:_:file:line:flags:) + 304
1  MapboxCoreNavigation           0xccdf8 $s20MapboxCoreNavigation15RouteControllerC13updateIndexes6status8progressySo20MBNNNavigationStatusC_AA0D8ProgressCtF + 1344
2  MapboxCoreNavigation           0xcbae0 $s20MapboxCoreNavigation15RouteControllerC6update33_6B801B604541F85AC28F671ADE7224AFLL2toySo20MBNNNavigationStatusC_tF + 756
3  MapboxCoreNavigation           0xcb780 $s20MapboxCoreNavigation15RouteControllerC25navigationStatusDidChange33_6B801B604541F85AC28F671ADE7224AFLLyySo14NSNotificationCFyycfU_ + 152
4  MapboxCoreNavigation           0x34e90 $sIeg_IeyB_TR + 48
5  libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
7  libdispatch.dylib              0x11d30 _dispatch_main_queue_callback_4CF + 940
8  CoreFoundation                 0x51ce4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
9  CoreFoundation                 0xbebc __CFRunLoopRun + 2540
10 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x51b0bc -[UIApplication _run] + 1100
13 UIKitCore                      0x298be8 UIApplicationMain + 2124
14 iCarMode                       0x5a90 main + 15 (main.m:15)
15 ???                            0x102aada24 (Missing)

### Expected behavior

should not crash

### Actual behavior

crashed

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by S2Ler** [comment]
Fixed in #3432 

@DiegoResnik Feel free to reopen if you see the crash after updating to upcoming this week release.
