### ISSUE TITLE
Allow NavigationServiceDelegate to supply new route when rerouting

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3464]
NavigationServiceDelegate should have an optional method `navigationService(_:willRerouteFrom:completion:)` that accepts a callback that the method implementation should call once a new route has been calculated asynchronously. This will enable applications that use the Map Matching API or a custom routing engine (“Bring Your Own Route”) to more seamlessly reroute the user when the user goes off-route. Currently, the application is expected to implement `navigationService(_:shouldRerouteFrom:)` by returning false and asynchronously calling `Router.updateNavigator(with:)`, but this part of the workflow is unintuitive and requires reaching into the Router.

/cc @mapbox/navigation-ios

**Comment by Udumft** [comment]
Resolved by mapbox/mapbox-navigation-ios/pull/3472

**Comment by 1ec5** [comment]
The fix was backed out in #3668.
