### ISSUE TITLE
Route line traversal is accessible but nonfunctional to the public

### ISSUE THREAD

**Issue by IAntolK** [mapbox/mapbox-navigation-ios#3473]
'travelAlongRouteLine' doesn't update the route style layer and its casing style layer to gradually disappear as the user location puck travels along the displayed route. I'm calling 'travelAlongRouteLine' and 'updateUpcomingRoutePointIndex' on every progress change but route line doesn't change as user is traveling along it. 

I think the cause of the problem is in 'routeLineTracksTraversal' property of NavigationMapView which is internal type and set to false by default.

v2.0.0-rc.4

**Comment by IAntolK** [comment]
Ok, thanks for the answer. I already tried with this option, but was hopping that there is another way to do it, without NavigationController, because I don't need it for anything except this.

**Comment by IAntolK** [comment]
After a few tries I didn't manage to make this workaround with NavigationViewController to work for my use case. Is there any possibility to make 'routeLineTracksTraversal' public in next version/s? 
Whats the point of having public functions  'updateUpcomingRoutePointIndex'  and 'travelAlongRouteLine' if calling of those doesn't make any effect because of internal flag, 'routeLineTracksTraversal', which is set to false and can't be changed?

**Comment by ShanMa1991** [comment]
Right now we're using `RouteProgress` to calculate the `NavigationMapView.fractionTraveled` for the  `routeLineTracksTraversal` effect. If we're using the `NavigationMapView` without `NavigationViewController` for active navigation, we could add observers to `RouteController` notifications about the reroute, refresh and routeProgress change to update the route line, with the `RouteProgress` and location coordinate from `NavigationService`, like the `CustomViewController` in our `Example` app.

But if we want to have the `routeLineTracksTraversal` effect for `passive` navigation or free drive or `previewing` on `NavigationMapView`, we don't have a `NavigationService` or a valid `RouteProgress` to calculate the `fractionTraveled`. We only have the `Route` and the location coordinate. We need to explore the method to calculate the `fractionTraveled` based on `Route` and the location coordinate only for this purpose.
