### ISSUE TITLE
Events use wrong SDK version

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#3501]
`NavigationEventsManager` fetches SDK version from `Bundle.mapboxCoreNavigation` which is alias for `Bundle(for: RouteController.self)` on non-SPM integration.

https://github.com/mapbox/mapbox-navigation-ios/blob/894854a257b8c50f1e0899470acdf9f744b6c391/Sources/MapboxCoreNavigation/Feedback/NavigationEventsManager.swift#L155-L158

Since NavSDK links statically bundle for `RouteController` will be `Bundle.main` and fetching `CFBundleShortVersionString` from there will result in fetching application version instead of NavSDK version.

**Comment by 1ec5** [comment]
Related: #3312.

**Comment by azarovalex** [comment]
Closing the ticket, since I can't reproduce it anymore.

1. On SPM `Bundle.mapboxCoreNavigation` resolves to the `Bundle.module` and `CFBundleShortVersionString` is fetched correctly.
1. On Cocoapods integration `Bundle.mapboxCoreNavigation` resolves to `.app/Frameworks/MapboxCoreNavigation.framework` and `CFBundleShortVersionString` is also presented inside the `Info.plist`.

It should be possible technically to link MapboxCoreNavigation statically even in Cocoapods integration, and this might lead to problems, but by default all Mapbox libraries are linked dynamically.
