### ISSUE TITLE
Access to MapboxCoreNavigation Geometry.swift inaccessible

### ISSUE THREAD

**Issue by RoninSTi** [mapbox/mapbox-navigation-ios#354]
When trying to use functions defined in Geometry.swift  from MapboxCoreNavigation, I get the error: "`direction` is inaccessible due to `internal` protection level."

Any suggestions?

**Comment by bsudekum** [comment]
Currently, nothing in Geomtry.swift does not contain public functions.

@1ec5 @frederoni what do you think about opening these functions up?

**Comment by frederoni** [comment]
I think Geometry.swift should reside in a framework and repo of its own. There's seems to be no history that needs to be migrated so should be fairly straight forward.

**Comment by 1ec5** [comment]
Yes, Geometry.swift needs to live in its own framework and repository. That would also make it possible to use Geometry.swift on other Apple platforms.

Among the reasons we shouldn’t simply expose Geometry.swift publicly as part of Core Navigation is that almost none of it bridges to Objective-C, whereas Core Navigation is expected to bridge to Objective-C. Another reason is that, as written, Geometry.swift somewhat pollutes the global namespace and its extensions on built-in types are a bit indiscrete. That’s fine if a library chooses to link against a separate MapboxGeometry framework, but merely linking against Core Navigation shouldn’t automatically expose you to all these extensions.

**Comment by frederoni** [comment]
Fixed in #653
