### ISSUE TITLE
Route line shows `routeCasingColor` instead of associated congestion color.

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#3542]
From `v2.0.0-rc.6`, we have noticed that the route line would show `routeCasingColor` instead of associated congestion color during the active navigation as the following. A customer also found this issue since `v2.0.0-rc.6`. And this bug leads to the route line disappearing during the active navigation when they set the `routeCasingColor` to `.clear`, which is tracked in [slack](https://mapbox.slack.com/archives/C8LQNA2R1/p1635342782119900).

We could see the route line color from `trafficLowColor` the lighter blue turns to `routeCasingColor` as darker blue, gif contributed by @OttyLab in [slack](https://mapbox.slack.com/archives/C8LQNA2R1/p1635752824193700?thread_ts=1635342782.119900&cid=C8LQNA2R1)
![rc6_routeCasingColor](https://user-images.githubusercontent.com/48976398/139735284-b12a7fec-c931-4f68-872c-330f37932d36.gif)

It's caused by the following:
https://github.com/mapbox/mapbox-navigation-ios/pull/3413/commits/3722a0ee1ab47b98144cb65479c083302cfb0f6b#diff-2b1a7feb6a6afb29ecf66effdb70c04c63a6fc30da5499c64d081f9f6bfef42aR246 

The `associatedFeatureColor` set as `routeCasingColor` would have 2 causes:
1. The compiling issue leads to `nil` `CongestionLevel` info. We have observed in an internal dogfooding application and notified by a customer that there're jam / congestion band disappearing suddenly during active navigation. Before `v2.0.0-rc.6`, if we have `nil` for congestion level information, we would assign the `trafficUnknownColor` to it. 
https://github.com/mapbox/mapbox-navigation-ios/blob/3d4db0c89c16721a0631c4ba6f0c76bdbb0fd973/Sources/MapboxNavigation/NavigationMapView%2BVanishingRouteLine.swift#L240-L243
https://github.com/mapbox/mapbox-navigation-ios/blob/3d4db0c89c16721a0631c4ba6f0c76bdbb0fd973/Sources/MapboxNavigation/NavigationMapView%2BVanishingRouteLine.swift#L337
But after `v2.0.0-rc.6`, in https://github.com/mapbox/mapbox-navigation-ios/commit/3722a0ee1ab47b98144cb65479c083302cfb0f6b#diff-2b1a7feb6a6afb29ecf66effdb70c04c63a6fc30da5499c64d081f9f6bfef42aR246 , we combined the two check. When the  `nil` `CongestionLevel` comes, it would default choose the `routeCasingColor` instead of the `trafficUnknownColor`.

2. The wrong `legIndex` that passed to `RouteLineController.navigationService(_:didUpdate:with:rawLocation:)` by `RouteController.update(progress:with:rawLocation:upcomingRouteAlerts)` . Because a customer provided the information that when the route line disappearing, it would have the information of route layer and source removal, which caused by `NavigationMapView.show(_:legIndex:)`. When the  `legIndex` is wrong, the current leg would have a `false` `isCurrentLeg` in feature properties, it would also lead to the default `routeCasingColor` instead of congestion color. We may need to look into the core to figure out the reason for the possible wrong `legIndex`.

**Comment by 1ec5** [comment]
> We may need to look into the core to figure out the reason for the possible wrong legIndex.

Should we open a separate issue to track the incorrect leg index, which still requires investigation?

**Comment by ShanMa1991** [comment]
@1ec5 Yes, sure, I think we can open a separate issue to track the incorrect leg index. Because without refresh, when there's a  possible wrong legIndex, it would lead to the  re-drawing of the route line and also the `routeCasingColor`.

**Comment by ShanMa1991** [comment]
#3577 fixed part of the issue. Right now when the congestion information is missing, the route line would default to show the `trafficUnknownColor` or `alternativeTrafficUnknownColor` instead of the `routeCasingColor`. 

And the possible cause of wrong `legIndex` still needs investigation.

**Comment by ShanMa1991** [comment]
After tests, this issue is happening on `main` branch and is repeatable, by decreasing the refresh rate of `RouteControllerProactiveReroutingInterval ` to 5 or less in `Example`, and start/cancel the navigation for several times.

During navigation, the congestion level is suddenly missing  when `navigationMapView.show(:legIndex:)` is called.  And this issue is coming from the following:
https://github.com/mapbox/mapbox-navigation-ios/blob/d40a21a05ea515e0a3f13dceffe525b562bd0bab/Sources/MapboxNavigation/Route.swift#L56

By checking, the issue comes from the check of `congestionLevels.count < coordinates.count`.  For example, in some cases, the `congestionLevels` count is `91`, while the `coordinate` count is `90`. So even there's useful congestion information, it blocks the congestion feature generation.

@1ec5

**Comment by 1ec5** [comment]
Do we need to update anything in the navigation SDK in response to the change in mapbox/mapbox-directions-swift#587? @Udumft mentioned a small change as part of #3603 that could be related to a fix.

**Comment by ShanMa1991** [comment]
> Do we need to update anything in the navigation SDK in response to the change in [mapbox/mapbox-directions-swift#587](https://github.com/mapbox/mapbox-directions-swift/pull/587)? @Udumft mentioned a small change as part of #3603 that could be related to a fix.

Yes, #3603 should work to solve this issue in `Route.restrictedRoadsFeatures()`, and it should also be added into the `Route.congestionFeatures(legIndex: roadClassesWithOverriddenCongestionLevels :)`

https://github.com/mapbox/mapbox-navigation-ios/blob/b55430b2bb8439887f8b6ba4994ffbb30304458e/Sources/MapboxNavigation/Route.swift#L47-L56
