### ISSUE TITLE
[Bug]: Conflict with mapbox sdk v6.x

### ISSUE THREAD

**Issue by tungvustarglobal** [mapbox/mapbox-navigation-ios#3546]
### Mapbox Navigation SDK version

v2.0.0

### Steps to reproduce

In podfile:
```
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'MapboxNavigation', '~> 2.0'
```

ios minimum target: iOS 11

### Expected behavior

pod install succssfully

### Actual behavior

``` 
Mapbox-iOS-SDK (~> 6.3.0) was resolved to 6.3.0, which depends on
      MapboxMobileEvents (~> 0.10.4)

Specs satisfying the `MapboxMobileEvents (= 1.0.6, ~> 1.0), MapboxMobileEvents (~> 0.10.4)` dependency were found, but they required a higher minimum deployment target.
```

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by S2Ler** [comment]
Hello @tungvustarglobal, 

While v2 of `MapboxNavigation` doesn't work with v6 of `Mapbox-iOS-SDK`, it does work with [v10](https://github.com/mapbox/mapbox-maps-ios/blob/main/MapboxMaps.podspec) 'MapboxMaps'. I encourage you to check it out. It has many significant enhancements. You can read more in a [blog post](https://www.mapbox.com/blog/maps-sdk-v10-release-candidate).
