### ISSUE TITLE
[Bug]: Current leg route is being rendered under the next leg

### ISSUE THREAD

**Issue by boryst** [mapbox/mapbox-navigation-ios#3565]
### Mapbox Navigation SDK version

2.0

### Steps to reproduce

Create a route with multiple waypoints where current leg can overlap next leg. Not sure about previous legs.

### Expected behavior

Current leg should be rendered on top of previous and next legs.

### Actual behavior

Current leg being rendered under next leg, which makes it hard to see the current leg.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by boryst** [comment]
![IMG_0045](https://user-images.githubusercontent.com/1310397/140587839-adabac16-68c5-4cc4-b96d-91960be7cc42.jpg)
Example

**Comment by MaximAlien** [comment]
I'm not sure that there is an easy fix for this on Navigation SDK side, as route line uses `LineLayer`, which is part of Maps SDK. I also do not see that we can control how parts of `LineLayer` can be highlighted differently in case of overlapping. 

So my question is: @boryst, would it work for you if we provide an option to disable leg highlighting when using `NavigationViewController`? Basically similar option as in `NavigationMapView.show(_:legIndex)`.

**Comment by boryst** [comment]
If I understand correctly this options would hide all other legs except the current one? If yes - then yes, that would be perfect. In our app we need to hide next legs before completing the current one. This would solve the overlapping issue as well.

**Comment by ShanMa1991** [comment]
@boryst If you need to hide other legs except the current one, you could try the following to hide other legs by setting the other leg color to `UIColor.clear`.  Please let us know whether it works for your case.

```
navigationViewController.navigationMapView.routeCasingColor = UIColor.clear
```

**Comment by boryst** [comment]
Yes, setting `routeCasingColor` to `.clear` does the trick. Thank you.

**Comment by MaximAlien** [comment]
@boryst, it's good to hear that such approach works for you. Thanks @ShanMa1991. Closing this ticket.
