### ISSUE TITLE
NavigationViewControllerDelegate unable to override instruction label

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3567]
As of #1530, the recommended approach to override the contents of the maneuver instruction label is to implement `VisualInstructionDelegate.label(_:willPresent:as:)` within a `NavigationViewControllerDelegate`-conforming class, because `NavigationViewControllerDelegate` conforms to `VisualInstructionDelegate`. However, this method is never called on a `NavigationViewControllerDelegate`.

Here’s where the override would take place:

https://github.com/mapbox/mapbox-navigation-ios/blob/d2d031317a7fdb888265d643993a4e41d3e8de15/Sources/MapboxNavigation/InstructionLabel.swift#L36

However, nothing ultimately sets `instructionDelegate` beyond the containing banner’s delegate. By code inspection, this issue seems to apply to both traditional banners and guidance cards.

This issue was reported in v1.4.2 but likely affects v2._x_ too.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
`InstructionsBannerViewIntegrationTests.testCustomVisualInstructionDelegate()` purports to be an integration test of this functionality, but it doesn’t cover the whole chain of delegates all the way up to NavigationViewController.

**Comment by 1ec5** [comment]
The fix will likely involve plumbing VisualInstructionDelegate usage further up the stack. One complication is that InstructionsCardContainerViewDelegate, part of the guidance cards feature, splits the method in two to distinguish between primary and secondary instructions.

**Comment by ShanMa1991** [comment]
The issue for `InstructionsCardContainerViewDelegate` is that developers could directly extends the `InstructionsCardCollectionDelegate` by setting the `InstructionsCardViewController.cardCollectionDelegate` to itself, and use the `InstructionsCardViewController` as the top banner of `NavigationOptions`, like we did in the  guidance cards in the `Example`. 
So the customization of the `InstructionsCardViewController` is already capable to developers. Should we still address that in #3575 ?

**Comment by 1ec5** [comment]
Ah, you’re right. It’s inconsistent with how traditional banners work, but it looks like we’re all set there. Thanks for explaining that – we can close this issue once #3575 lands then.
