### ISSUE TITLE
Entering navigation can take a couple of seconds

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#357]
When selecting `Default UI` in the demo app, there can be a pause up to 5 seconds before anything happens. Originally I thought this was due to calculating intermediate coordinates in simulation mode, but it seems to occur while not in simulate route mode as well. 

/cc @frederoni @1ec5 @ericrwolfe

**Comment by frederoni** [comment]
I think this is due to loading assets on the main thread and creating unnecessary AVAudioPlayers before we need them on the main thread. I'll run some profiling.

**Comment by frederoni** [comment]
My assumption was incorrect. Out of 3.92s on the main thread, 3.55s are spent in `mbgl::Painter`.

<img src="https://user-images.githubusercontent.com/764476/28117531-11783eac-670e-11e7-9f02-0107313eae30.png" width=600>

Can we delay the route line by .5 seconds or incrementally add traffic? Any other ideas?

**Comment by bsudekum** [comment]
We should continue to take a look at this. @ericrwolfe has a hunch this may due to all the storyboards.

**Comment by 1ec5** [comment]
It would be surprising if the two storyboards themselves were the cause of this delay. Have you been able to reproduce this reliably? On a device or in a simulator?
