### ISSUE TITLE
[Bug]: Can't resolve dependencies in Swift Package Manager

### ISSUE THREAD

**Issue by ir-fuel** [mapbox/mapbox-navigation-ios#3578]
### Mapbox Navigation SDK version

>= 2.0.0

### Steps to reproduce

Add `https://github.com/mapbox/mapbox-navigation-ios.git` to Swift Package Dependencies, using `up to next major` and version `2.0.0`, in Xcode 13.1

### Expected behavior

The packages should be resolved and the project should build

### Actual behavior

I get the following error message:

Dependencies could not be resolved because 'mapbox-navigation-ios' >= 2.0.0-rc.6 depends on 'mapbox-maps-ios' 10.0.0..<11.0.0 and root depends on 'mapbox-navigation-ios' 2.0.0..<3.0.0.
'mapbox-maps-ios' is incompatible with 'mapbox-navigation-ios' because 'mapbox-navigation-ios' >= 2.0.0-beta.13 depends on 'mapbox-events-ios' 1.0.0..<2.0.0.
'mapbox-maps-ios' >= 10.0.0 practically depends on 'mapbox-events-ios' 1.0.5..<1.0.5 because 'mapbox-maps-ios' >= 10.0.1 depends on 'mapbox-events-ios' 1.0.6 and 'mapbox-maps-ios' 10.0.0..<10.0.1 depends on 'mapbox-events-ios' 1.0.5.

I tried deleting the derived data folder, resetting package caches etc etc. Nothing worked.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ir-fuel** [comment]
FYI, using exact version `2.0.0-beta.18` works

**Comment by S2Ler** [comment]
Hello @ir-fuel, 

I just tried to add MapboxNavigation v2.0.0 to Xcode 13.1, and everything went smoothly. I find it suspicious that the error message says " 'mapbox-navigation-ios' >= 2.0.0-rc.6" and "root depends on 'mapbox-navigation-ios' 2.0.0..<3.0.0" at the same time. There is something not quite right with the project configuration. You probably reference to `'mapbox-navigation-ios' >= 2.0.0-rc.6` from some of your other packages. They should be updated to v2.0.0 as well. 

If you submit the minimum reproducible example, I will help you correct it.

**Comment by ir-fuel** [comment]
The problem is I have no idea where to look.
These are all the Swift packages I include, and there is no Cocoapods or Carthage in my project (I put back the beta so I can continue developing)

![Screenshot 2021-11-11 at 10 10 01](https://user-images.githubusercontent.com/1573715/141270349-9d395712-76fa-4f0c-879d-a1811318422e.jpg)
:

And this is the list of Package Dependencies according to Xcode when looking at the bottom in my project:
![Screenshot 2021-11-11 at 10 11 46](https://user-images.githubusercontent.com/1573715/141270569-cc3f7743-d732-4dd8-b2bd-8f56053935b9.jpg)

**Comment by bamx23** [comment]
It seems to be an Xcode/SPM issue. I had similar before.

@ir-fuel could you try updating to Mapbox Navigation 2.0.0 and then press `File - Packages - Clean Package Cache` and `File - Packages - Update to Latest Package Versions`? I haven't tried but removing `Package.resolved` might solve the issue too. I see that you've already done this, but maybe some extra cleanup can help. Also, here is a list of commands I use for Xcode/SPM issues like this:

```bash
rm -rf $HOME/Library/Developer/Xcode/DerivedData/*
rm -rf $HOME/Library/Caches/com.apple.dt.Xcode/*
rm -rf $HOME/Library/Caches/org.swift.swiftpm/*
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.${USER}/ModuleCache"
```

Once it is resolved in the `Package.resolved` inside your project file, it should work fine. If you don't want to update other packages there you can roll back unwanted changes.

**Comment by ir-fuel** [comment]
I just deleted `Package.resolved` and executed all `rm -rf` commands listed here above.
It seems to have solved the issue.
