### ISSUE TITLE
Let the user switch to a different alternative route during turn-by-turn navigation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3598]
During turn-by-turn navigation, the user should be able to explicitly stop following the current route and instead follow an alternative route to the same destination.

## Background

In typical usage of the navigation SDK, the application initially receives multiple routes from the Directions API and lets the user select one of them, the default selection being the most optimal route. Then the navigation SDK takes over, sticking to that route selection. Even after the user gets rerouted or proactively rerouted, the SDK attempts to stick to the route that most closely resembles the user’s original selection.

The current heuristic for sticking to the user’s original selection, described in https://github.com/mapbox/mapbox-navigation-ios/issues/818#issue-272406754, does not assume the user went off-route (because it could be invoked due to proactive rerouting). It’s also optimized for cases where the user deviated from the route for minor reasons, such as to stop for fuel or because of intermittent poor GPS readings. On a long-distance route, ignoring the original selection due to such minor detours would be counterintuitive.

mapbox/mapbox-navigation-android#3333 tracks sticking to the user’s original selection on Android.

## Problem

A user might deviate from the current route for reasons other than a pit stop. If the user simply changes their mind and wants to take the original optimal route, the current heuristic would stubbornly send them right back to the current route. This could be particularly annoying on short-distance trips. Broadly, the problem is that the user has no control over route selection after the trip begins, so neither the application nor the SDK knows the reason they’re triggering a reroute.

## Proposal

NavigationViewController should show all the routes, including alternative routes. Alternative routes should be annotated with their time differences with respect to the current route. The user should be able to tap on an alternative route to trigger a reroute that ignores the original selection (and therefore does not rank routes by similarity to the original selection).

In CarPlay, which does not support robust user gestures, the user should be able to tap a button to reveal something resembling the `previewing` activity. Other CarPlay navigation applications such as Waze already have a UI like this.

Similarly, #2740 proposes to let the user confirm or reject a proactive reroute.

/cc @mapbox/navigation-ios @kmadsen

**Comment by 1ec5** [comment]
MapboxNavigationNative has a “continuous route alternatives” feature that mapbox/mapbox-navigation-android#4892 integrated on Android. RoutesAlternativeController would help ensure that an alternative route disappears from the map (or the route selection list on CarPlay), ideally replaced by an updated alternative, as soon as the user passes the point where the alternative route deviates from the current route.

**Comment by 1ec5** [comment]
> Alternative routes should be annotated with their time differences with respect to the current route.

Specifically, #3132 tracks adding an option to show delays instead of absolute driving time, which would be used here.

**Comment by linsd75** [comment]
Hi @1ec5  Could you confirm the status of this ticket? 
If we close this issue, we can close the NCS issue[ #335 ](https://github.com/mapbox-collab/ncs-collab/issues/335)

**Comment by 1ec5** [comment]
> https://github.com/mapbox/mapbox-navigation-ios/pull/3850 would display alternative routes on the map, and it would be straightforward to hook up the tap gesture recognizer to switch to the alternative route based on that display.

This is now implemented, at least for the iPhone/iPad screen: https://github.com/mapbox/mapbox-navigation-ios/pull/3850#issuecomment-1141975597. @Udumft @MaximAlien, are we feeling good about how this works on CarPlay, or should we open a new issue to track the idea in https://github.com/mapbox/mapbox-navigation-ios/pull/3850#discussion_r890716429 for less touch-capable CarPlay head units?

**Comment by Udumft** [comment]
I'm already working on CarPlay adaptation (+relative duration callouts display). PR will be posted shortly

**Comment by Udumft** [comment]
promised PR: https://github.com/mapbox/mapbox-navigation-ios/pull/3956
