### ISSUE TITLE
[Bug]: Advancing legIndex crashes the app

### ISSUE THREAD

**Issue by aw1875** [mapbox/mapbox-navigation-ios#3608]
### Mapbox Navigation SDK version

2.0.1

#### Step 1: Create route with 3 waypoints (origin, waypoint 1, waypoint 2)
In my case I used the user's current location as origin and then set 2 more waypoints.

#### Step 2: Create Waypoint arrival screen (default one from documentation)

```swift
    func navigationViewController(_ navigationViewController: NavigationViewController, didArriveAt waypoint: Waypoint) -> Bool {
        let isFinalLeg = navigationViewController.navigationService.routeProgress.isFinalLeg
        if isFinalLeg {
            return true
        }
        
        let alert = UIAlertController(title: "Arrived at \(waypoint.name ?? "Unknown").", message: "Would you like to continue?", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: { _ in
            // Begin the next leg once the driver confirms
            if !isFinalLeg {
                navigationViewController.navigationService.routeProgress.legIndex += 1
                navigationViewController.navigationService.start()
            }
        }))
        navigationViewController.present(alert, animated: true, completion: nil)
        
        return false
    }
```

### Expected behavior

After pressing "Ok" on popup message the expected behavior is the navigation system now starts its navigation for the next waypoint.

### Actual behavior

The navigation keeps rerouting and trying to send you back to the waypoint you just reached until `navigationViewController.navigationService.routeProgress.legIndex += 1` throws an out of bounds index

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by S2Ler** [comment]
Thanks for report @aw1875,

You shouldn't modify `routeProgress` manually. To manually advance to the next leg use the `Router.advanceLegIndex(completionHandler:)` method. Obtain `Router` via the `NavigationViewController.navigationService` and `NavigationService.router` properties.

cc @1ec5, I think we need to migrate RouteProgress to the struct and make `routeProgress` readonly for public access level.

**Comment by aw1875** [comment]
@S2Ler Thanks for the help! Seems to have fixed the issue for me so I appreciate it. Just a heads up the code I gave above comes straight from the [documentation](https://docs.mapbox.com/ios/navigation/examples/waypoint-arrival-screen/)

**Comment by S2Ler** [comment]
@aw1875 Will fix it, thanks!
