### ISSUE TITLE
Mapbox Core Navigation with MKMapView

### ISSUE THREAD

**Issue by aodhol** [mapbox/mapbox-navigation-ios#361]
Can I use the Core Navigation module with MKMapView as a replacement for MKDirections / MKRouteStep API? I'm trying to providing pedestrian turn-by-turn navigation with the facility to check if the user is still on the route and the current _step_ (a feature lacking in the MKDirections API..

**Comment by bsudekum** [comment]
@aodhol MapboxDirections.swift is a hard dependency however Mapbox iOS SDK is not. I think it would be technically possible, however it would require a lot of work and we cannot provide much technical support. 

Noting our directions API does support walking directions by using the profile `MBDirectionsProfileIdentifier`.

**Comment by aodhol** [comment]
Thank you!
