### ISSUE TITLE
Add framework to project using swift 2  

### ISSUE THREAD

**Issue by ChanchalW** [mapbox/mapbox-navigation-ios#362]
Hi, I want to add turn by turn navigation in one of my old project, it is in swift 2 and at this point, i can't update the whole project. 
Is there any way to add this framework to my project?

Thanks in advance

**Comment by 1ec5** [comment]
This library has always been written in Swift 3. We have no plans to backport it to Swift 2. If you’re interested in writing your own turn-by-turn navigation logic and UI, the last Swift 2–compatible version of MapboxDirections.swift was [v0.7.0](https://github.com/mapbox/MapboxDirections.swift/releases/tag/v0.7.0).
