### ISSUE TITLE
Update instructions when rerouting goes in the opposite direction

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-navigation-ios#3627]
After landing #3620, we should consider not suppressing the initial "Head north on" instruction after a reroute if it starts out going in the opposite direction. This change should only apply to walking instructions.

**Comment by 1ec5** [comment]
There’s a line somewhere that increments the voice instruction index past 0 when rerouting.

**Comment by MaximAlien** [comment]
Linking code, which can be useful: https://github.com/mapbox/mapbox-navigation-ios/blob/85f1e2217ed5d4ebb4bd8957cf6effda975c5bc5/Sources/MapboxCoreNavigation/Router.swift#L280-L282

**Comment by jill-cardamon** [comment]
Current code does not suppress the first instruction after a reroute or route refresh:
https://github.com/mapbox/mapbox-navigation-ios/blob/cd92c891296c9260c186b9423fb51596871529fa/Sources/MapboxCoreNavigation/RouteController.swift#L405-L408

We can close this ticket since this logic is already in place.
