### ISSUE TITLE
Fix issues, which cause test failures in `testPausedFreeDrivePausesNavNativeNavigator` and `testRouteSnappingOvershooting`.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3628]
In scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3614 `testPausedFreeDrivePausesNavNativeNavigator` and `testRouteSnappingOvershooting` were disabled as cause of their failures was unclear.

In scope of this ticket cause of these issues should be found and tests re-written as per new Navigation Native behavior. See `FIXME` tags for these tests to check additional details.

**Comment by S2Ler** [comment]
I suspect that one of the reason we have issues in tests is that there can be more than one RouteController. I'm currently investigating this in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3652

**Comment by MaximAlien** [comment]
Thanks @S2Ler. I've added [PR](https://github.com/mapbox/mapbox-navigation-ios/pull/3763) that removes FIXME statements for tests you've fixed.
