### ISSUE TITLE
[Bug]: Navigation Simulation Camera does not work after update to 2.0

### ISSUE THREAD

**Issue by jcfrk101** [mapbox/mapbox-navigation-ios#3640]
### Mapbox Navigation SDK version

2.0.1

### Steps to reproduce

Setup navigation simulation as shown below.

`let simulationIsEnabled = ALFConfiguration.sharedInstance()!.navSimEnabled
            let navigationService = MapboxNavigationService(routeResponse: route, routeIndex: 0, routeOptions: options, simulating: simulationIsEnabled ? .always : .onPoorGPS)
            if let speed = ALFConfiguration.sharedInstance()?.emulationSpeed {
                if speed > 0 {
                    navigationService.simulationSpeedMultiplier = speed;
                }else{
                    navigationService.simulationSpeedMultiplier = 3;
                }
            }else{
                if(simulationIsEnabled){
                    navigationService.simulationSpeedMultiplier = 3;
                }
            }
            let navigationOptions = NavigationOptions(styles: [CustomNightStyle()], navigationService: navigationService)
            self.navigationVC = NavigationViewController.init(for: route, routeIndex: 0, routeOptions: options, navigationOptions: navigationOptions);`
            
Start navigation. 

### Expected behavior

Arrow appears to move along the route, along with the map, progress should update in delegate methods.

### Actual behavior

Arrow appears to move along the route, but map and camera do not follow, progress is never updated in delegate methods.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by jcfrk101** [comment]
This appears to be happening because I calculated directions using RouteOptions instead of NavigationRouteOptions.

**Comment by MaximAlien** [comment]
You can consider this code, which can be helpful (uses logic you've shared before):

```swift
class ViewController: UIViewController, NavigationViewControllerDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let origin = CLLocationCoordinate2DMake(37.77440680146262, -122.43539772352648)
        let destination = CLLocationCoordinate2DMake(37.76556957793795, -122.42409811526268)
        let options = NavigationRouteOptions(coordinates: [origin, destination])
        
        Directions.shared.calculate(options) { [weak self] (_, result) in
            switch result {
            case .failure(let error):
                print(error.localizedDescription)
            case .success(let response):
                guard let strongSelf = self else {
                    return
                }
                
                let simulationIsEnabled = true
                let navigationService = MapboxNavigationService(routeResponse: response,
                                                                routeIndex: 0,
                                                                routeOptions: options,
                                                                simulating: simulationIsEnabled ? .always : .onPoorGPS)
                
                let emulationSpeed: Double? = 2.0
                if let speed = emulationSpeed {
                    if speed > 0 {
                        navigationService.simulationSpeedMultiplier = speed
                    } else {
                        navigationService.simulationSpeedMultiplier = 3
                    }
                } else {
                    if simulationIsEnabled {
                        navigationService.simulationSpeedMultiplier = 3
                    }
                }
                
                let navigationOptions = NavigationOptions(styles: [NightStyle()], navigationService: navigationService)
                let navigationViewController = NavigationViewController.init(for: response,
                                                                                routeIndex: 0,
                                                                                routeOptions: options,
                                                                                navigationOptions: navigationOptions)
                navigationViewController.delegate = self
                
                strongSelf.present(navigationViewController, animated: true)
            }
        }
    }
    
    func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {
        return false
    }
}
```

**Comment by jcfrk101** [comment]
Yeah, my issue was the use of RouteOptions instead of NavigationRouteOptions. With NavigationRouteOptions, simulations works properly.
