### ISSUE TITLE
Left-aligned highway shields

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#365]
We should left align the highway shields in the turn banner making them appear inline with the rest of the instruction text. 

cc @frederoni @1ec5

**Comment by 1ec5** [comment]
At the same time, let’s avoid making the shield any smaller than it is now. The numbers inside certain shield images can already be difficult to discern at the current size.

**Comment by 1ec5** [comment]
Started work in the [1ec5-inline-shield-365](https://github.com/mapbox/mapbox-navigation-ios/tree/1ec5-inline-shield-365) branch.

**Comment by 1ec5** [comment]
We’re also eliding any cardinal direction from the turn banner whenever we choose to display a shield. As part of this feature, we should make sure to display any cardinal direction next to the shield.

**Comment by michaelsteffen** [comment]
🎉 yes pls

**Comment by bsudekum** [comment]
This has been implemented.

**Comment by 1ec5** [comment]
Specifically, the shields were inlined in #745.
