### ISSUE TITLE
Upgrade to MapboxMaps v10.2.0

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3657]
Now that [MapboxMaps v10.2.0](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.2.0) is released, we should either relax the minimum MapboxMaps version requirement to be “from” v10.1.2 or increase it to v10.2.0 if we need anything that’s new to that release.

https://github.com/mapbox/mapbox-navigation-ios/blob/1ecc321139f3e08780aef7b6ed42f6e272ee2830/Package.swift#L28 https://github.com/mapbox/mapbox-navigation-ios/blob/1c6bbfa2f8e235a3a87ef18c31e9ff702a791884/Package.swift#L28

This is blocked until MapboxNavigationNative upgrades to MapboxCommon v21._x_.

/cc @mapbox/navigation-ios

**Comment by LearnWithTung** [comment]
Please update this asap.
