### ISSUE TITLE
[Bug]: no such module 'MapboxCommon_Private'

### ISSUE THREAD

**Issue by jcfrk101** [mapbox/mapbox-navigation-ios#3658]
### Mapbox Navigation SDK version

2.1

### Steps to reproduce

Compile using swift package manager using GitHub actions

### Expected behavior

Application should compile

### Actual behavior

Compilation often fails. Though the failures aren’t consistent. Some times they succeed sometimes they fail.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
Hello @jcfrk101. We also encounter this build error from time to time, but there is no reliable fix as of now. It happens more often if there are a lot of dependencies, which are linked via SPM. One approach, which works for me in such cases is full cache reset of Xcode, for example:
```swift
killall Xcode
xcrun -k
xcodebuild -alltargets clean
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.$(whoami)/ModuleCache"
rm -rf ~/Library/Developer/Xcode/DerivedData/*
rm -rf ~/Library/Caches/com.apple.dt.Xcode/*
rm -rf .build
swift package reset
swift package update
open /Applications/Xcode.app
```

**Comment by azarovalex** [comment]
Please check that you are using the latest version of Xcode, it should be already fixed on the Apple's side.

**Comment by jcfrk101** [comment]
We did switch to the laziest version 2 weeks ago, and I have not seen this problem since.
