### ISSUE TITLE
Disable cancel button when route table view is visible

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#366]
Right now, if you slide open the route table view, the cancel button remains visible at the top. To most users, tapping a "Cancel" button should dismiss the current modally presented view, but instead, tapping the cancel button actually exits out of navigation.

Ideally we'd replace the cancel button with a downward facing arrow that dismisses the route table view.

However, as a quick win we could either:
* Override the behavior of the cancel button to dismiss the route table view
* Disable the cancel button altogether

cc @frederoni @mayagao

**Comment by 1ec5** [comment]
> Ideally we'd replace the cancel button with a downward facing arrow that dismisses the route table view.

This doesn’t seem outlandish at all. Can we try this, or at least temporarily replace “Cancel” with “Hide” while the table is visible?

**Comment by bsudekum** [comment]
No longer applicable.
