### ISSUE TITLE
[Bug]: ios. change userLocation's image

### ISSUE THREAD

**Issue by Celia-Jiang** [mapbox/mapbox-navigation-ios#3671]
### Mapbox Navigation SDK version

2.2.0-beta.1

### Steps to reproduce

 var puck2DConfiguration = Puck2DConfiguration()
      if #available(iOS 13.0, *) {
            puck2DConfiguration.topImage = #imageLiteral(resourceName: "navigation_default_avatar")
            puck2DConfiguration.scale = .constant(5.0)
        }
        let userLocationStyle = UserLocationStyle.puck2D(configuration: puck2DConfiguration)
        navigationViewController.navigationMapView?.userLocationStyle = userLocationStyle

### Expected behavior

change the userLocation image to the custom image

### Actual behavior

there is no change

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
Hello @Celia-Jiang. We have similar example in https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Custom-User-Location.swift#L218-L228 and it works as expected:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-04 at 11 38 41](https://user-images.githubusercontent.com/1496498/148115443-9207a353-08b2-44a3-be0a-938f0db3ddfc.png)

Can you make sure that:
- Image resource you have is valid.
- You're testing on iOS version > `13.0`.
- `NavigationMapView` is valid and is not `nil` at the time of setting `userLocationStyle` property.

**Comment by MaximAlien** [comment]
@Celia-Jiang, I'm closing this ticket. Feel free to ask if you have any other questions.
