### ISSUE TITLE
How to display custom annotation pins on NavigationViewController in V2

### ISSUE THREAD

**Issue by kanikadrgaur** [mapbox/mapbox-navigation-ios#3680]
I have implemented turn by turn navigation in my app with custom images. Now I want to show some annotation pins on this NavigationViewController can any one please help me how can I display annotation pin with custom image on NavigationViewController. With Earlier version it was working fine but in V2 it is not showing any option to show annotation on NavigationViewController

**Comment by MaximAlien** [comment]
Hello @kanikadrgaur. You can check this [example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Custom-Destination-Marker.swift) to see how final destination annotation can be added (it also uses custom image).

**Comment by MaximAlien** [comment]
If you'd like to directly work with annotation you can consider using `NavigationMapView.pointAnnotationManager`. For example:
```swift
navigationViewController.navigationMapView?.mapView.mapboxMap.onNext(.mapLoaded) { _ in
    let pointAnnotationManager = navigationViewController.navigationMapView?.pointAnnotationManager
    var pointAnnotation = PointAnnotation(coordinate: CLLocationCoordinate2D(latitude: 37.769234, longitude: -122.389229))
    pointAnnotation.image = .init(image: UIImage(named: "CUSTOM_IMAGE")!, name: "annotation")
    pointAnnotationManager?.annotations.append(pointAnnotation)
}
```

**Comment by MaximAlien** [comment]
@kanikadrgaur, closing this ticket. Feel free to open another ticket if you have other questions.
