### ISSUE TITLE
Compatibility issue with MapboxMaps iOS v10.2.0

### ISSUE THREAD

**Issue by gsilvaPF** [mapbox/mapbox-navigation-ios#3681]
Getting dependency conflicts trying to download with cocoapods while using Mapbox Maps 10.2.0. Error Below.

ERROR: 
[!] CocoaPods could not find compatible versions for pod "MapboxCommon":
  In Podfile:
    
    MapboxMaps (= 10.2.0) was resolved to 10.2.0, which depends on
      MapboxCommon (= 21.0.1)

    MapboxNavigation (~> 2.1) was resolved to 2.1.1, which depends on
      MapboxCoreNavigation (= 2.1.1) was resolved to 2.1.1, which depends on
        MapboxNavigationNative (~> 80.0) was resolved to 80.0.2, which depends on
          MapboxCommon (~> 20.1)

**Comment by MaximAlien** [comment]
Mapbox Maps SDK `v10.2.0` and Mapbox Navigation SDK `v2.1.1` are not compatible. Can you try pointing to Navigation SDK [v2.2.0-beta.1](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.2.0-beta.1)? It should fix build issues.
