### ISSUE TITLE
[Bug]: POI icons are located below highlighted building layer.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3690]
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Start active navigation by selecting building (make sure that it gets highlighted).
2. Observe behavior.

### Expected behavior

POI icons should be located above highlighted building layer.

### Actual behavior

POI icons are located below highlighted building layer.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Resolved by #3692
