### ISSUE TITLE
Throttle map rendering when device unplugged

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#370]
Right now, rendering 60fps animations between location updates is taxing on the device + battery. When the device is unplugged, we should not animate between location updates.

cc @bsudekum @1ec5

**Comment by 1ec5** [comment]
This requires #352.

**Comment by ericrwolfe** [comment]
This also depends on a fix for the general battery monitoring crash: https://github.com/mapbox/mapbox-navigation-ios/issues/371

**Comment by ericrwolfe** [comment]
@1ec5 Is this something we could achieve in a first pass without a complete overhaul of course tracking, for example with a category on MGLMapView?

**Comment by 1ec5** [comment]
Unfortunately not without changes to the map SDK proper or a risky hack. The CADisplayLink frame rate is determined by [a constant](https://github.com/mapbox/mapbox-gl-native/blob/175e7e26e2008d1e55664bd1064536c23b6de86a/platform/ios/src/MGLMapView.mm#L114). We could swizzle [`-[MGLMapView didUpdateLocationIncrementallyAnimated:]`](https://github.com/mapbox/mapbox-gl-native/blob/175e7e26e2008d1e55664bd1064536c23b6de86a/platform/ios/src/MGLMapView.mm#L4470), but I’m not a fan of that approach.

**Comment by ericrwolfe** [comment]
Yeah, overriding `-[MGLMapView didUpdateLocationIncrementallyAnimated:]` is along the lines of what I was thinking. Could we override with a category or in the `NavigationMapView` subclass without needing to swizzle and break instances outside of the navigation UI?

**Comment by 1ec5** [comment]
I agree that swizzling would be a bad idea for the reason that it would break non-NavigationMapView instances of MGLMapView. A category method override would be nondeterministic, right? Overriding in NavigationMapView would be safer, although `-_setCenterCoordinate:edgePadding:zoomLevel:direction:duration:animationTimingFunction:completionHandler:`, `-edgePaddingForFollowing`, and `-directionByFollowingWithCourse` are also internal, so they would need to be forward-declared as well.

**Comment by frederoni** [comment]
This has been implemented in #402 but it's blocked upstream by some camera refinements.

**Comment by 1ec5** [comment]
By the way, if we need a tightly-scoped fix for a patch release, we can override `-_setCenterCoordinate:edgePadding:zoomLevel:direction:duration:animationTimingFunction:completionHandler:` in a separate PR while #402 bakes.

**Comment by ericrwolfe** [comment]
I think we should continue to consider throttling when the device is unplugged, though from tests anything that involves a significant change in course (e.g. turns) looks pretty bad without animations.

Could we disable animations if the device is unplugged and the change in course/heading is small (i.e. <10-15°), otherwise animate between location updates?

**Comment by ericrwolfe** [comment]
Reopening as a follow on to #402.
