### ISSUE TITLE
[Bug]: Missing argument for parameter 'config' in call

### ISSUE THREAD

**Issue by PJCSpencer-ClearMotion** [mapbox/mapbox-navigation-ios#3732]
### Mapbox Navigation SDK version

Latest main branch for SPM

### Steps to reproduce

Try to build a project with libraries imported

### Expected behavior

Compile without error

### Actual behavior

/Library/Developer/Xcode/DerivedData/.../SourcePackages/checkouts/mapbox-navigation-ios/Sources/MapboxCoreNavigation/MapboxRoutingProvider.swift:31:69: Missing argument for parameter 'config' in call

<img width="1383" alt="Screenshot 2022-02-10 at 12 34 19" src="https://user-images.githubusercontent.com/78368586/153410391-d898e216-4595-46da-93ac-ffa5f16bc80e.png">

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
@PJCSpencer-ClearMotion, feel free to open new ticket if you experience any other build issues. Closing this one.
