### ISSUE TITLE
[Question]: Polygon border fade-out / smooth border

### ISSUE THREAD

**Issue by andreas-ullrich** [mapbox/mapbox-navigation-ios#3737]
Dear Mapbox team,

if i use fil-in pattern in ios sdk with a geojson file it creates a straight border or better so say sharp edges.
Is there a possibility to fade out the border or to give the appearance of more smooth border.
See my example: 

<img width="302" alt="Bildschirmfoto 2022-02-13 um 10 46 44" src="https://user-images.githubusercontent.com/68023686/153747624-e9d53485-4cae-46ae-8b56-1724fd873d88.png">

`      let polygon = Polygon(polygon)
                
        let polygonAnnotationManager: PolygonAnnotationManager
        
        polygonAnnotationManager = mapView.annotations.makePolygonAnnotationManager(id: managerID, layerPosition: nil)
        
        // Create the polygon annotation
        var polygonAnnotation = PolygonAnnotation(polygon: polygon)
                
        // Style the polygon annotation
        polygonAnnotation.fillPattern = imageName
        polygonAnnotationManager.fillAntialias = true
        
        // Add the polygon annotation to the manager
        polygonAnnotationManager.annotations = [polygonAnnotation] `

Thank you in advance!
Best regards,
Andreas

**Comment by MaximAlien** [comment]
I think folks from @mapbox/maps-ios might have a better answer for this question. If I'm not mistaken we do not use `PolygonAnnotationManager` at this point in Navigation SDK for iOS.

**Comment by andreas-ullrich** [comment]
@MaximAlien ah ok thank you for you reply. I created an issue in https://github.com/mapbox/mapbox-maps-ios i hope it was the right place to do so. BR.

**Comment by MaximAlien** [comment]
Thanks @andreas-ullrich, feel free to let us know if you need any help with Navigation SDK for iOS.
