### ISSUE TITLE
Update CI builds to Xcode 13.2.1 and iOS 15.2

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#3745]
Right now we only have jobs on Xcode 12 and Xcode 11.

Xcode 13 jobs should replace all jobs, but we still want to run tests on Xcode 11 & 12 as part of our extended workflow.

As part of this update, we need to generate reference screenshots for iOS 15.2 as well.

### Already supported devices for screenshot tests:
- iPhone 11 Pro Max, iOS 13.7
- iPhone 12 Pro Max, iOS 14.4

### Will be added as part of this ticket:
- _iPhone 13 Pro Max, iOS 15.2_

**Comment by MaximAlien** [comment]
@azarovalex, can we close this ticket?
