### ISSUE TITLE
Update or remove testPuck3DLayerPosition

### ISSUE THREAD

**Issue by bamx23** [mapbox/mapbox-navigation-ios#3790]
This test was disabled during the update to Maps SDK `10.4.0-rc.1` in this PR: https://github.com/mapbox/mapbox-navigation-ios/pull/3765.

The failing code is this one:
https://github.com/mapbox/mapbox-navigation-ios/blob/9e42a853023d9ff1c0ed5535fd693a1b8ceb8411/Tests/MapboxNavigationTests/NavigationViewControllerTests.swift#L368-L372

The test fails as the logic behind puck setting is changed in the Maps SDK: https://github.com/mapbox/mapbox-maps-ios/pull/1090#discussion_r829979416

We should either update the test to wait for a layer to be added to the map view, or remove the test at all as it might not be relevant for Nav SDK testsuit.

**Comment by MaximAlien** [comment]
Will be fixed in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3933.
