### ISSUE TITLE
Discard improbable headings

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#381]
When course snapping is enabled, we should discard any headings exactly equal to 0 or -1. 

![](https://user-images.githubusercontent.com/1594300/27805910-423a2556-5fec-11e7-819b-42841f885a10.jpg)

cc @bsudekum

**Comment by ericrwolfe** [comment]
Likewise, we might want to prevent any course snapping changes when the user is stopped at a light and the speed is close to zero.

![](https://user-images.githubusercontent.com/1594300/27805905-3d1f09a6-5fec-11e7-8431-f30140d287c8.jpg)

**Comment by bsudekum** [comment]
So in cases where we have a course of -1, 0 or a speed of 0, we should just snap the user to the route line?

Currently, we returning early and using the course from the device https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L362-L364

@1ec5 this make sense to you?

**Comment by 1ec5** [comment]
It’s probably possible for a CLLocation’s course to be −1 at the same time its coordinate is valid. So at this point, we’d create a new CLLocation with all the same information but a course based on the route line, then continue to use that synthesized CLLocation throughout the method.

Only negative values are invalid; 0° is no more improbable than 35°. If we were to discard 0° in favor of a course based on the route line, we’d introduce inconsistent behavior. For example, if the route continues due east but the user turns left, we’d snap the course up to −30°, then accurately reflect `CLLocation.course` after that, until the user gets to 0°. At that point, we swing back to due east before swinging northward again as the user crosses over to 359°.

**Comment by ericrwolfe** [comment]
> 0° is no more improbable than 35°

Noting here that we're talking about the exact value of 0.0000000...°, which is highly improbable with real world, unrounded, double precision coordinates. A simple `course > 0` instead of `course != -1` would suffice.

**Comment by 1ec5** [comment]
My point is that negative values are the only ones documented to be invalid. Guarding against `course < 0` is 👌.

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/445

**Comment by ericrwolfe** [comment]
I don't think #445 actually fixes this issue.

**Comment by ericrwolfe** [comment]
This was directly addressed in https://github.com/mapbox/mapbox-navigation-ios/pull/449.

However, @bsudekum I think we could take this even further and filter out course values (+ snap to the route's course) when the user's speed is < 1-2 m/s.

<img width="441" alt="screen shot 2017-08-08 at 5 49 36 pm" src="https://user-images.githubusercontent.com/664805/29100692-0a27224e-7c62-11e7-86e7-8627c976d8cd.png">

We can replay that exact gps trace in voyage if you need something to test with.

**Comment by ericrwolfe** [comment]
Edit: here's a trace you can use: https://gist.github.com/ericrwolfe/8c79181e7df8741ab1e317c5abf47173

**Comment by ericrwolfe** [comment]
This should be fixed with #475.

**Comment by ericrwolfe** [comment]
Just kidding, this is being addressed in https://github.com/mapbox/mapbox-navigation-ios/pull/481.

**Comment by ericrwolfe** [comment]
Closed with #540.
