### ISSUE TITLE
[Bug]: `UserPuckCourseView` becomes stale after starting active navigation even if location is available.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3812]
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Open Example application and modify line 187 in ViewController.swift from:
```swift
navigationMapView.userLocationStyle = .puck2D()
```
to:
```swift
navigationMapView.userLocationStyle = .courseView()
```

2. Start active navigation and stop it.
3. Wait for a couple of seconds and see how `UserPuckCourseView` changes its style.

### Expected behavior

`UserPuckCourseView` should not change its style if location is available.

### Actual behavior

`UserPuckCourseView` changes its style to stale because internally it listens to updates from `.routeControllerProgressDidChange` only.

![Simulator Screen Shot - iPhone 13 - 2022-04-06 at 12 48 35](https://user-images.githubusercontent.com/1496498/162060541-02e70f3e-8437-4923-8076-b4d48e6b8df1.png)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by 1ec5** [comment]
Do we still need this graying-out functionality anymore, now that MapboxNavigationNative simulates locations automatically as the locations become stale? Or maybe we should generalize the feature to be a disabled timer that anything can trigger and untrigger?

**Comment by ShanMa1991** [comment]
So the graying-out functionality used to be used during the active navigation. When there's no valid `NavigationStatus`, the notification of `routeControllerProgressDidChange` won't be sent out, and the `UserPuckCourseView` will show a fading style.

But right now we support both the use of the `UserPuckCourseView` in passive and active navigation. And both the `PassiveLocationManager` and `RouteController` listens to the  change of `NavigationStatus` from navigator, and which is valid per second with simulated status sometimes. The `UserPuckCourseView` used in passive and active navigation would always have the valid `NavigationStatus` update and the location information per second. 

So I think the timer for the graying-out functionality in the `UserPuckCourseView` is not useful anymore and we could remove it for listening to the  `routeControllerProgressDidChange` notification.
