### ISSUE TITLE
[Bug]: Error installing MapboxCommon

### ISSUE THREAD

**Issue by Raamzeez** [mapbox/mapbox-navigation-ios#3813]
I am unable to install the Mapbox iOS Navigation SDK despite following all steps and doing them repeatedly to ensure that I did not make any mistakes. Please keep in mind that I am using React Native with Expo and a bare workflow project. When I try to build an expo project, the build fails at this point. 

<img width="1024" alt="Screen Shot 2022-04-06 at 4 52 57 PM" src="https://user-images.githubusercontent.com/37488506/162068829-99c9461a-5826-41fe-bbc3-9798478d53dc.png">
 
After research online, many people suggested that it could be a problem with the .netrc file that is in the home directory. However, I have confirmed that the .netrc file is in my home directory with the proper extension and with the proper credentials. Does anyone know what else could have caused the error, and what steps I can do to fix them? I really want to integrate the Mapbox iOS Navigation SDK into my project.

**Comment by MaximAlien** [comment]
@Raamzeez, If you say that your `~/.netrc` is valid there might be a problem with `--netrc-optional` option expo is using. This option makes `.netrc` optional, so there is a chance that it's not used at all.

**Comment by Raamzeez** [comment]
@MaximAlien Thanks for the help! How exactly would I address this? Would I have to do something like pass a flag when I build an expo project by typing `--netrc-optional=false`? Is it something within the code? I tried researching the `--netrc-optional` online relating to expo and I couldn't find much information about it.

**Comment by MaximAlien** [comment]
@Raamzeez, it's hard to comment how it can be fixed on expo's side. Maybe there is a way to fix this on curl's side using configuration file, but it needs more testing. You can also easily check whether there are any problems with your `.netrc` by creating plain CocoaPods application that uses Navigation SDK for iOS and see if it was fully downloaded. If so - there are no problems with your `.netrc`.

**Comment by MaximAlien** [comment]
More info on curl config files is [here](https://everything.curl.dev/cmdline/configfile). Try to add `--netrc-optional=false` to your `.curlrc`, maybe it'll fix the problem with expo.

**Comment by Raamzeez** [comment]
Ok, I will experiment with this later and see if I am able to fix this by creating a plain CocoaPods application. If it doesn't work I will update this issue and also start a new issue with Expo since Expo could be the source of the problems.

**Comment by Raamzeez** [comment]
@MaximAlien I can confirm that there are no issues with my .netrc file because I was able to successfully download the Mapbox library for iOS when I created a plain CocoaPods application without any modifications to the .netrc file. I have attached an image of this below. Based on your response I will try as my next step to mess with the curl configuration files. 

<img width="1097" alt="Successful_Mapbox_Install" src="https://user-images.githubusercontent.com/37488506/164787201-69875e83-fec4-4726-9b3c-de856c902a12.png">

**Comment by ricardodolnl** [comment]
I do not use expo and I have the same error. Any solution?

**Comment by elbarryamine** [comment]
In my case i created the .netrc manually in my home directory using vscode 
but it turns out maybe there is some issues with that (Spacing i suppose)
<img width="396" alt="Screenshot 2023-03-30 at 12 29 46 PM" src="https://user-images.githubusercontent.com/81116690/228836754-2f44a257-649a-43f7-b886-5610bb45097f.png">

So i tried doing it like this and it worked
```
touch ~/.netrc
echo "machine api.mapbox.com" > ~/.netrc
echo "login mapbox" >> ~/.netrc 
echo "password ${MAPBOX_TOKEN}" >> ~/.netrc
```

**Comment by figureai** [comment]
> In my case i created the .netrc manually in my home directory using vscode but it turns out maybe there is some issues with that (Spacing i suppose) <img alt="Screenshot 2023-03-30 at 12 29 46 PM" width="396" src="https://user-images.githubusercontent.com/81116690/228836754-2f44a257-649a-43f7-b886-5610bb45097f.png">
> 
> So i tried doing it like this and it worked
> 
> ```
> touch ~/.netrc
> echo "machine api.mapbox.com" > ~/.netrc
> echo "login mapbox" >> ~/.netrc 
> echo "password ${MAPBOX_TOKEN}" >> ~/.netrc
> ```

Thanks! I can't successfully pod install by copying files directly from other computers, but create files through your above instructions

**Comment by UdayVinaik** [comment]
If you have tried with creating ~/.netrc file and still it is not working, please try to put following line in podFile:
$RNMapboxMapsVersion = '~> 10.11.1'
just after $RNMapboxMapsImpl = 'mapbox'
