### ISSUE TITLE
Replace lineGradient with lineTrimOffset

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3818]
An upcoming version of the map SDK will introduce a `LineLayer.lineTrimOffset` paint property as a more performant alternative to the `lineGradient` property that we currently use for deemphasizing (vanishing) the route line behind the user puck. We should adopt this new property to minimize the route line’s jankiness due to location updates. 

https://github.com/mapbox/mapbox-navigation-ios/blob/12ed832c21472674e92e7d4dab6fc65ed9c4d20c/Sources/MapboxNavigation/NavigationMapView.swift#L541-L549

It doesn’t sound like this new property fully supports the styling options we provide for traffic congestion segments. It’s designed for hard stops only, so the crossfading option introduced in #3307 would probably need to remain on `lineGradient`.

/ref mapbox/mapbox-navigation-android#5673
/cc @mapbox/navigation-ios @zmiao

**Comment by LukasPaczos** [comment]
cc @cafesilencio for visibility

**Comment by LukasPaczos** [comment]
We should wait for https://github.com/mapbox/change-management/issues/841 before we merge the integration on the iOS side.
