### ISSUE TITLE
Manually rerouting user impossible due to internal protection

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#3822]
My app is pulling routing information from our backend every few seconds. In some specific scenarios, I want to be able to completely re-route a user with a new route, without closing and re-opening the navigationController.  It should behave like the normal re-routing that is done with functions like 
`navigationService(_ service: [NavigationService](https://docs.mapbox.com/ios/navigation/api/2.3.1/Protocols/NavigationService.html), shouldRerouteFrom location: CLLocation)`, but with a completely new route. If that does not work, a workaround would be to change the waypoint Array and thus update the route from there. 
How can that be achieved?

**Comment by JanTG1** [comment]
I am still looking for a solution to this problem. I basically need to pass a new route object to the current NavigationController... How can I do that?

**Comment by Udumft** [comment]
Hello @JanTG1 ! [This example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Custom-RoutingProvider.swift#L15-L19) demonstrates how user is able to override and control rerouting, including modifying the resulting route or it's calculation options.
Please take a look and let me know if that helped or you need more info!

**Comment by andersoncanteiro** [comment]
@Udumft the provided example didn't show how to update the current route with a new one. Btw I am using the MapboxNavigation (2.5.0), I had access to the updateRoute function by the router (navigationService.router.updateRoute), I had success from the completion handler callback, but the route didn't update on the UI (NavigationViewController). I am working with the NavigationViewController wrapped into a SwiftUI representable (UIViewControllerRepresentable). 
Could you help me ?

**Comment by Udumft** [comment]
`updateRoute` should also update the UI. Please make sure that you've passed correct `indexedRouteResponse` (and `routeOptions` if needed) and check that this method is called from the main thread. Also, please consider upgrading to v2.5.1 as it contains important fix for rerouting mechanism.

**Comment by andersoncanteiro** [comment]
@Udumft the update is working at first time of a reroute, but if the user change the directions a second time, the following func it is not getting called again.

```SWIFT
func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool 
```

And there is some debug logs saying that the reroute is still in progress on native side.

```
[Mapbox] [Debug, nav-native]: Reroute is in progress, skipping reroute.
```

A bit of my implementation, the navigation view is wrapped on a `UIViewControllerRepresentable`, because our project is in SwiftUI. 

```SWIFT
    func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {

        if !content.isReRouting {
            content.isReRouting = true
            content.reRouteCall(location.coordinate)
        }

        return true
    }
```

The update is using the following code:

```SWIFT
self?.navigationViewController?.navigationService.router.updateRoute(
                        with: IndexedRouteResponse(routeResponse: response, routeIndex: 0),
                        routeOptions: opt,
                        completion: { _ in })
```

And the during a debug, all results were `true` about updating the route.

**Comment by Udumft** [comment]
There's some questions I'd like to ask about it:
* Could you verify if `willReroute` and `didReroute` delegate methods were called at the first reroute?
* I assume you are using `customRoutingProvider`? (your own implementation of `RoutingProvider` protocol) could you please share it's implementation?
* Where do you place your 'The update' code snippet? Is it inside a `RoutingProvider` impl?

**Comment by andersoncanteiro** [comment]
- Could you verify if willReroute and didReroute delegate methods were called at the first reroute?
  - Yes, they were called after the first reroute.

- I assume you are using customRoutingProvider? (your own implementation of RoutingProvider protocol) could you please share it's implementation?
  - Yes, I am using a custom server and I have implemented the ```RoutingProvider```
 
- Where do you place your 'The update' code snippet? Is it inside a RoutingProvider impl?
  - No, it is outside of the ```RoutingProvider```. Also I didn't use the match opt, because I do the encode to Mapbox RouteResponse before.

Here it is the code, for better understanding: 

```SWIFT
import SwiftUI
import Combine
import MapboxDirections
import MapboxNavigation
import MapboxCoreNavigation
import MapboxMaps
import CoreLocation

struct MapNavigation: UIViewControllerRepresentable {
    typealias UIViewControllerType = NavigationViewController

    var routeResponse: MapboxDirections.RouteResponse
    var routeOpt: NavigationRouteOptions
    var selectedRouteIndex: Int
    let reRoutePublisher: AnyPublisher<(response: MapboxDirections.RouteResponse, opt: NavigationRouteOptions)?, Never>
    @Binding var isReRouting: Bool
    @Binding var manuallyClosed: NavigationCloseDestinationEnum
    let reRouteCall: (CLLocationCoordinate2D) -> Void

    func makeUIViewController(context: Context) -> NavigationViewController {

        let navigationService = MapboxNavigationService(
            routeResponse: routeResponse,
            routeIndex: selectedRouteIndex,
            routeOptions: routeOpt,
            customRoutingProvider: SolinftecProvider(),
            credentials: Credentials(),
            simulating: .never
        )

        let navigationOptions = NavigationOptions(navigationService: navigationService)
        let viewController = NavigationViewController(for: routeResponse, routeIndex: selectedRouteIndex, routeOptions: routeOpt, navigationOptions: navigationOptions)

        viewController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
        viewController.delegate = context.coordinator
        viewController.showsReportFeedback = false
        viewController.navigationMapView?.mapView.mapboxMap.style.uri = StyleURI.satellite
        viewController.navigationMapView?.mapView.hideMapboxReferences()

        context.coordinator.navigationViewController = viewController
        return viewController
    }

    func updateUIViewController(_ navView: NavigationViewController, context: Context) {}

    func makeCoordinator() -> MapNavigationCoordinator {
        MapNavigationCoordinator(self)
    }
}

final class MapNavigationCoordinator: NavigationViewControllerDelegate {

    private var content: MapNavigation
    private var subscriptions = [AnyCancellable]()
    internal var navigationViewController: NavigationViewController?

    init(_ content: MapNavigation) {
        self.content = content
        
        self.content.reRoutePublisher
            .subscribe(on: DispatchQueue.global(qos: .userInteractive))
            .compactMap { $0 }
            .receive(on: DispatchQueue.main)
            .sink { [weak self] response, opt in
                
                if self?.content.isReRouting == true {
                    self?.content.isReRouting = false
                    self?.navigationViewController?.navigationService.router.updateRoute(
                        with: IndexedRouteResponse(routeResponse: response, routeIndex: 0),
                        routeOptions: opt,
                        completion: { _ in })
                }
            }.store(in: &subscriptions)
    }

    func navigationViewController(_ navigationViewController: NavigationViewController, routeLineLayerWithIdentifier identifier: String, sourceIdentifier: String) -> LineLayer? {

        navigationViewController.navigationMapView?.mapView?.mapboxMap?.style.createFieldsLayer()

        return nil
    }

    func navigationViewControllerDidDismiss(_ navigationViewController: NavigationViewController, byCanceling canceled: Bool) {

        if canceled {
            content.manuallyClosed = nearToFieldEntrance ? .cab : .anotherDestination
        }
    }

    func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {

        if !content.isReRouting {
            content.isReRouting = true
            content.reRouteCall(location.coordinate)
        }

        return true
    }

    deinit {
        subscriptions.removeAll()
    }
}

final class SolinftecProvider: RoutingProvider {
    func calculateRoutes(options: RouteOptions, completionHandler: @escaping Directions.RouteCompletionHandler) -> NavigationProviderRequest? {
        nil
    }

    func calculateRoutes(options: MatchOptions, completionHandler: @escaping Directions.MatchCompletionHandler) -> NavigationProviderRequest? {
        nil
    }

    func refreshRoute(indexedRouteResponse: IndexedRouteResponse, fromLegAtIndex: UInt32, completionHandler: @escaping Directions.RouteCompletionHandler) -> NavigationProviderRequest? {
        nil
    }
}

```

**Comment by Udumft** [comment]
Your `RoutingProvider` implementation is empty. `calculateRoutes` method should actually call a `completionHandler` with a resulting route response for the reroute to work. Since it is not called, reroute process is stuck.

**Comment by andersoncanteiro** [comment]
Oh, I got it, will do that. Many thanks.

**Comment by andersoncanteiro** [comment]
> Your `RoutingProvider` implementation is empty. `calculateRoutes` method should actually call a `completionHandler` with a resulting route response for the reroute to work. Since it is not called, reroute process is stuck.

It worked, thanks again.
