### ISSUE TITLE
[Bug]: Pitch updates are not smooth when approaching a maneuver

### ISSUE THREAD

**Issue by jill-cardamon** [mapbox/mapbox-navigation-ios#3835]
### Mapbox Navigation SDK version

v2.4.0

### Steps to reproduce

1. Select a route (example route below from `(37.808391,-122.276005)` to somewhere off of 880 -- didn't see this issue with routes going north on 980)
2. Observe pitch updates are jerky when approaching the second (left turn onto 980 freeway) and fourth (merging from 980 freeway to 880 freeway in video below) maneuvers.

### Expected behavior

Pitch changes should be smooth when approaching a maneuver.

### Actual behavior

When approaching the two maneuvers mentioned above, the camera's pitch and zoom are updated along with location updates which cause the pitch and zoom to jump instead of smoothly transition.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by jill-cardamon** [comment]
Video of second maneuver:

https://user-images.githubusercontent.com/43434254/163601183-0327ad5a-dfeb-444e-a81a-1e4a8a88bd44.mp4

Video of fourth maneuver:

https://user-images.githubusercontent.com/43434254/163601308-898a2a57-ad90-4bee-95bd-174f18954366.mp4

**Comment by MaximAlien** [comment]
@jill-cardamon, can you still reproduce this issue with the latest Maps SDK version?

**Comment by jill-cardamon** [comment]
Nope. I'll close this one, and we can reopen if it comes up again.
