### ISSUE TITLE
Logo + resume button overlap

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#384]
We should fix this: 

![image](https://user-images.githubusercontent.com/1058624/28178017-bef29a2a-67b1-11e7-9b77-d353f0adc8a5.png)

/cc @frederoni

**Comment by 1ec5** [comment]
How about horizontally centering the Resume button? That would overlap with the current street name label, but I think we can hide that label when the user is looking at an overview.

**Comment by bsudekum** [comment]
I'd like to keep both in view. The current way name label is still useful while in overview mode.

**Comment by 1ec5** [comment]
In that case, we could stack the Resume button and current street name label, as long as we give the two elements the same width.

**Comment by ericrwolfe** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/issues/421
