### ISSUE TITLE
Implement the ability to detect taps on the route duration annotations.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#3847]
At this point `NavigationMapView.showRouteDurations(along:)` allows to show route duration annotations for a list of routes. In scope of this ticket user should be given the ability to detect taps on such annotation (similarly to waypoints and routes).

**Comment by MaximAlien** [comment]
These annotations are shown as a `SymbolLayer` provided by Maps SDK, @mapbox/maps-ios do you have any suggestions here? What would be the best way to detect tap on such `SymbolLayer`.

**Comment by macdrevx** [comment]
You can use query rendered features:

- https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Foundation/MapboxMap.swift#L689

If you search our examples for that method, you'll find some sample uses.

**Comment by MaximAlien** [comment]
View annotations can be considered in this case as well.

**Comment by 1ec5** [comment]
View annotations would also address the poor image stretching due to mapbox/mapbox-maps-ios#381.
