### ISSUE TITLE
my music is interrupted by the navigationViewController.

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#388]
my music is interrupted by the navigationViewController. is there a way to fix it?

**Comment by 1ec5** [comment]
Hi, which version of the navigation SDK are you using? #356 might be related somehow; it went into v0.5.0.

/cc @frederoni

**Comment by zijiazhai** [comment]
thanks a lot, after I update the SDK from 0.4.0 to 0.5.0, my problem is solved.
