### ISSUE TITLE
[Bug]: Label layers are above the waypoint layers.

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#3887]
### Mapbox Navigation SDK version

v2.5.0-beta.3 

### Steps to reproduce

1. Build the `Example` app.
2. Choose multiple waypoints, place the waypoints on the road label
3. Start navigation

### Expected behavior

The waypoint layer is above the road labels.

### Actual behavior

The waypoint layer is below the label layers as below. Checking the layer position, the waypoint layer is below all the label layers and road shield layers.
![waypointLayer](https://user-images.githubusercontent.com/48976398/168185581-83f03940-b660-49e7-a56f-36286ba6ba96.png)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
Waypoint layers are always shown either arrow layer (if it's present) or above main route layer. I guess we should support agile approach by allowing user to decide what layer should be used as a parent layer as it was implemented in https://github.com/mapbox/mapbox-navigation-ios/pull/3897.

**Comment by jill-cardamon** [comment]
Resolved by #4030. Custom layering is added in separate PR.
