### ISSUE TITLE
Pausing Navigation in Simulation Mode

### ISSUE THREAD

**Issue by enigma-studios-development** [mapbox/mapbox-navigation-ios#3890]
When I pause the navigation service (with the .stop() method), the arrow puck stops moving but the camera in the navigationViewController continues along the route. Then, when calling 'start' again, the arrow puck jumps to where the camera is currently at. 

Should .stop() not pause navigation? It does when not in simulate mode. So the same behavior should be observed when in simulation mode.

**Comment by MaximAlien** [comment]
@enigma-studios-development, this is indeed an issue. Even though you can pause location updates internal `Navigator` object will send location status updates. I think that we'll have to introduce the ability to pause and resume it as well.

**Comment by enigma-studios-development** [comment]
Got it. This is critical, as we're using the Simulation mode for user-facing content. 

The only way to make it work as it is right now is to set the simulation speed multiplier to 0.0, then it effectively pauses the route and navigator and then set it back to 1.0 in order to resume.

**Comment by MaximAlien** [comment]
@enigma-studios-development, fix will land in https://github.com/mapbox/mapbox-navigation-ios/pull/3928. `NavigationViewController.navigationService.stop()` will give the ability to fully stop service and then recover it from the place where it was stopped with `NavigationViewController.navigationService.start()`.

**Comment by MaximAlien** [comment]
https://github.com/mapbox/mapbox-navigation-ios/pull/3928 landed. @enigma-studios-development, feel free to re-open if you still see any issues.
