### ISSUE TITLE
Thicken casing of maneuver arrow on route line

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#393]
#390 thickened the route line, so now you can see an unsightly gap between the arrow’s casing and the route line’s casing in which traffic congestion segments are sometimes visible:

![arrow](https://user-images.githubusercontent.com/1231218/28242748-065724e0-6969-11e7-9e5a-8779cc4dba63.png)

We should thicken the casing to fill in this gap. A nice side effect is that it’ll be much easier to distinguish the arrow from an ordinary road.

/cc @bsudekum

**Comment by 1ec5** [comment]
This is happening in #671.

**Comment by bsudekum** [comment]
This has been fixed.
