### ISSUE TITLE
[Bug]: Set WayNameView always hidden

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#3961]
### Mapbox Navigation SDK version

2.5.1

### Steps to reproduce

Is there a way to set WayNameView to be always hidden? I saw another ticket where someone tried to set the alpha value to 0 for all this view components but is not working properly.
I tried to set it hidden but I don't have access to the navigation view
Set `navigationViewController.navigationView.wayNameView.isHidden = true` but I get the following error: 'navigationView' is inaccessible due to 'internal' protection level

### Expected behavior

A way to set it always hidden...

### Actual behavior

Cannot be set as hidde. Always displayed and in some cases, it's covering the MapBox logo and information button it's not looking very good.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
Will be fixed in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/3758. This PR will make certain properties of `NavigationView` public (e.g. top and bottom banners). It'll also be possible to use `NavigationView` as a standalone component, similarly to `NavigationMapView`.

**Comment by nastasiupta** [comment]
@MaximAlien I included
InstructionsCardContainerView.appearance().backgroundColor = .red
In a custom CustomNightStyle: NightStyle & CustomDayStyle: DayStyle but is not working as expected.
Can you elaborate ?

**Comment by MaximAlien** [comment]
`WayNameView` is now public (but not yet documented). It can be accessed via `NavigationViewController.NavigationView.wayNameView` property. Such ability was implemented in scope of https://github.com/mapbox/mapbox-navigation-ios/pull/4017.
