### ISSUE TITLE
[Bug]: InstructionsCardView background color is not changing

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#3962]
### Mapbox Navigation SDK version

2.5.1

### Steps to reproduce

Create a class class that conforms to DayStyle, and NightStyle as you can see in this example: https://github.com/mapbox/mapbox-navigation-ios-examples/blob/039bf04dec45a0c0876d347a80990c133fea97cf/Navigation-Examples/Examples/Styled-UI-Elements.swift#L120

In the apply() functions include just this part.
InstructionsCardView.appearance().tintColor = .systemPink

Start route navigation and for header use: InstructionsCardViewController
As you can see in the attached photo, the header is not changing the color. What property do I have to set? Or how do I have to use InstructionsCardView.appearance and `whenContainedInInstancesOf` ? The navigation styling is a pain in the ...

### Expected behavior

To change the background color on top

### Actual behavior

The color is the default one

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
@nastasiupta, if I you'd like to modify background color of the actual instruction card perform changes to `InstructionsCardContainerView`. Let me know if ti helps. E.g.:

![Simulator Screen Shot - iPhone 13 - 2022-06-27 at 09 51 34](https://user-images.githubusercontent.com/1496498/175994274-6c647805-2cd1-4134-8015-f1e7bdb391cc.png)

**Comment by MaximAlien** [comment]
Also you can use [this](https://docs.mapbox.com/ios/navigation/guides/turn-by-turn-navigation/user-interface/#app-styling) approach to simplify process of selecting what view to style.

**Comment by nastasiupta** [comment]
@MaximAlien I included
InstructionsCardContainerView.appearance().backgroundColor = .red
In a custom CustomNightStyle: NightStyle & CustomDayStyle: DayStyle but is not working as expected.
Can you elaborate?

**Comment by nastasiupta** [comment]
```
class CustomDayStyle: DayStyle {

    required init() {
        super.init()
        mapStyleURL = URL(string: RESTURL.mapBoxLightStyle.value)!
        styleType = .day
    }

    override func apply() {
        super.apply()
        InstructionsCardContainerView.appearance().backgroundColor = .red
    }
    
}

```

**Comment by MaximAlien** [comment]
@nastasiupta, sorry, I forgot to mention that we use `customBackgroundColor` instead. This was made to support `highlightedBackgroundColor` as well. More info on behavior [here](https://docs.mapbox.com/ios/navigation/api/2.5.1/Classes/InstructionsCardContainerView.html).

**Comment by nastasiupta** [comment]
@MaximAlien 
```
InstructionsCardContainerView.appearance().customBackgroundColor = .red
InstructionsCardContainerView.appearance().highlightedBackgroundColor = .red
```

I just set both of them but still not working :|. The apply() function is called in the styling class but is not shown as expected.

**Comment by MaximAlien** [comment]
@nastasiupta, I've just changed our `DayStyle` in https://github.com/mapbox/mapbox-navigation-ios/blob/d3fd83eb3598b93a230c1a632e5065bda8f74031/Sources/MapboxNavigation/DayStyle.swift#L153-L154

and it works as expected. 

I've also tested it in our example application by modifying `CustomDayStyle` to:

```swift
class CustomDayStyle: DayStyle {
    
    required init() {
        super.init()
        
        mapStyleURL = URL(string: StyleURI.satelliteStreets.rawValue)!
        previewMapStyleURL = mapStyleURL
        styleType = .day
    }
    
    override func apply() {
        super.apply()
        
        BottomBannerView.appearance().backgroundColor = .orange
        
        InstructionsCardContainerView.appearance(whenContainedInInstancesOf: [InstructionsCardCell.self]).customBackgroundColor = .red
        InstructionsCardContainerView.appearance(whenContainedInInstancesOf: [InstructionsCardCell.self]).highlightedBackgroundColor = .green
    }
}
```

![Simulator Screen Shot - iPhone 13 - 2022-07-06 at 11 57 24](https://user-images.githubusercontent.com/1496498/177623016-de19b508-c1ab-460a-be98-42d9354c78d5.png)

Can you post more details about Navigation SDK version and code samples?

Also beware that in `v2.6.0` there will be some changes in styling and you'll have to provide appearance styling for iOS and CarPlay independently. Example is here: https://github.com/mapbox/mapbox-navigation-ios/blob/d3fd83eb3598b93a230c1a632e5065bda8f74031/Sources/MapboxNavigation/DayStyle.swift.
