### ISSUE TITLE
[Bug]: Directions endpoints called with driving parameters in cycling profile

### ISSUE THREAD

**Issue by jaeggerr** [mapbox/mapbox-navigation-ios#3966]
### Mapbox Navigation SDK version

2.5.0 and following

### Steps to reproduce

Probably similar to this issue
https://github.com/mapbox/mapbox-navigation-ios/issues/3495

Easiest approach to copy the tutorial here:
https://docs.mapbox.com/api/navigation/directions/
And add
`options.profileIdentifier = .cycling`
Which will result to this error:
`The operation couldn’t be completed. annotations value must be one of duration, distance, speed, maxspeed, congestion
`

Another case where the Directions API fails is by providing an initial cycling route to the navigation SDK, then follow another way to force the default Mapbox rerouting to trigger.

```
2022-06-24 16:49:28.155732+0200 COWBOY[11859:27554431] [Mapbox] [Error, nav-native]: Couldn't build reroute request URI. Skipping reroute.
16:49:28.1830 :blue_heart: INFO [tracking] MixPanelTracker.log(_:_:):111 - :female-detective::skin-tone-3: event.navigation.rerouting
2022-06-24 16:49:28.192885+0200 COWBOY[11859:27554429] [Mapbox] [Debug, nav-native]: Directions Service: Get route request: https://api.mapbox.com/directions/v5/mapbox/cycling/4.4,50.83%3B4.632334,51.003044?alternatives=false&continue_straight=false&avoid_maneuver_radius=1000.0&geometries=polyline6&overview=full&steps=true&language=en_US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=326.7431335449219,90.0;&access_token=*******
2022-06-24 16:49:28.239776+0200 COWBOY[11859:27556705] [Mapbox] [Warning, nav-native]: Directions Service: FetchDirections No Response code found!
2022-06-24 16:49:28.239898+0200 COWBOY[11859:27556705] [Mapbox] [Debug, nav-native]: Directions Service: FetchDirections Get route request error (type '5'): Invalid query param avoid_maneuver_radius.
```

Looks like the `avoid_maneuver_radius` parameter is used to build the URL while the API documentation states that it should only be used for driving.

### Expected behavior

API calls to the the Directions API should not use driving parameters when cycling.

### Actual behavior

Requests fail and no route is found when rerouting.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by 1ec5** [comment]
Thanks for identifying the issue. Looks like this statement needs to be conditionalized on the routing profile, or alternatively MapboxDirections needs to omit `avoid_maneuver_radius` when converting RouteOptions to a request URL:

https://github.com/mapbox/mapbox-navigation-ios/blob/4cf848ead556b76a1e4a03ce857e0f9c5b620687/Sources/MapboxCoreNavigation/Router.swift#L400-L402

**Comment by axelasa** [comment]
I keep getting this error when I add in a list of waypoints 

W/Mapbox  (32142): [nav-native]: Directions Service: FetchDirections Get route request error (type '6'): Route exceeds maximum distance limitation
E/Mapbox  (32142): [nav-native]: OnlineRouter::getRoute req id 0 failed w/error: Route exceeds maximum distance limitation

**Comment by Udumft** [comment]
Hi @axelasa! The error message seems to be related to total route distance, not with request parameters misuse. Please verify if your total route distance matches your driving profile's limitations, as states in [this doc section](https://docs.mapbox.com/api/navigation/directions/#directions-api-restrictions-and-limits).

**Comment by axelasa** [comment]
Thank you For your support I have resolved this issue.
one more question is, how do i make the multiple stops  start, I have multiple stops but the error I get is
" W/Mapbox  (26796): [nav-native]: Directions Service: FetchDirections Get route request error (type '1'): No route found
E/Mapbox  (26796): [nav-native]: OnlineRouter::getRoute req id 0 failed w/error: No route found. " 

When i do a debug of waypoints I have 3 waypoints, that I can confirm exist, what could i be doing wrong?
I have even tried inverting the lat ,long to long,lat and I still get the same error, but when i have 2 waypoints, then I get the route from origin to destination, or could it be that mapbox does not allow for more than 2 waypoints, or in other words multiple stops?
or does it not work with lists?
