### ISSUE TITLE
app downloaded from testflight crash 

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#398]
hi, guys, I updated the SDK from 0.4.0 to 0.5.0.  everything worked fine, then I uploaded my app to testflight and downloaded it. The app crash immediately every time on the real devices when I launch the app.

I am not really sure what is wrong here, do you guys have any ideas?

log: 
dyld: Symbol not found: _MGLStyleFunctionOptionDefaultValue

  Referenced from: /private/var/containers/Bundle/Application/750770C7-B5A6-4A6F-A278-B34E4B8AB6BE/XXXXXXX.app/Frameworks/MapboxNavigation.framework/MapboxNavigation

  Expected in: /private/var/containers/Bundle/Application/750770C7-B5A6-4A6F-A278-B34E4B8AB6BE/XXXXXXX.app/Frameworks/Mapbox.framework/Mapbox

 in /private/var/containers/Bundle/Application/750770C7-B5A6-4A6F-A278-B34E4B8AB6BE/XXXXXXX.app/Frameworks/MapboxNavigation.framework/MapboxNavigation

Message from debugger: Terminated due to signal 6

**Comment by frederoni** [comment]
Thank you for your report.

Would it be correct to assume that you are using Carthage?
If that's the case, did you follow Step 3 in https://github.com/mapbox/mapbox-navigation-ios#installation
More information about that in https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos
