### ISSUE TITLE
[Bug]: Unable to customize the Style

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#3982]
### Mapbox Navigation SDK version

v2.6.0-rc.1

### Steps to reproduce

1. In the `Example` App, create a custom `MapboxNavigation.Style` as below. 
```
class NightStyleSpy: NightStyle {
    override func apply() {
        super.apply()
        UILabel.appearance(whenContainedInInstancesOf: [FeedbackViewController.self]).textColor = .red
    }
}
```
2. And replace the `styleManager.styles = [DayStyle(), NightStyle()]` with `styleManager.styles = [DayStyle(), NightStyleSpy()]` in `ViewController.setupStyleManager()`
3. Choose the night style by choose to `Toggle Day/Night Style`
4. Click to see the `FeedbackViewController` label.

### Expected behavior

The label is red in text color
![expected](https://user-images.githubusercontent.com/48976398/176787263-c57ccef4-15d6-40de-8c62-cfd3733314e2.png)

### Actual behavior

The label shows the default white color.
![actual](https://user-images.githubusercontent.com/48976398/176787302-f56af8f1-e2e6-4940-a369-6e91f39e6231.png)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
I think that this is expected behavior. Appearance changes for certain trait collections now have precedence over global change, this means that appearance change you've posted in example will not have any effect. Instead, for iOS such styling should be used:
```swift
UILabel.appearance(for: UITraitCollection(userInterfaceIdiom: .phone), whenContainedInInstancesOf: [FeedbackViewController.self]).textColor = .red
```

I've also created [this](https://github.com/mapbox/mapbox-navigation-ios-examples/issues/179) ticket in our examples repo to refresh legacy styling.

**Comment by ShanMa1991** [comment]
@MaximAlien Thanks for the information and the example, it works as expected.

**Comment by jinny-nam** [comment]
hi @MaximAlien and @ShanMa1991, does it mean that the way for customzing style in this [example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Styled-UI-Elements.swift#L71) no longer valid? 
When testing this example by setting different color to manuevers (e.g. `LanesView.appearance().backgroundColor`, `ManeuverView.appearance().backgroundColor`), the [code](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Styled-UI-Elements.swift#L88) doens't change the color.

**Comment by ShanMa1991** [comment]
@jinny-nam Yes, right now we may need to add `UITraitCollection` to customize the style as in the [comment](https://github.com/mapbox/mapbox-navigation-ios/issues/3982#issuecomment-1171772651). We'll update the Example repo for this issue. Thanks!

**Comment by ShanMa1991** [comment]
Hi @jinny-nam , https://github.com/mapbox/mapbox-navigation-ios-examples/pull/188 has been merged to provide a code snippet for custom styling. https://github.com/mapbox/mapbox-navigation-ios-examples/pull/188 will be merged to update the Example for Styled UI Elements. The major change is that now users need to add the `UITraitCollection` for `UIAppearance` when customize UI components for styling.
