### ISSUE TITLE
[Bug]: SDK keeps crashing on iOS 16 beta (Simulator only)

### ISSUE THREAD

**Issue by martin-dzuro** [mapbox/mapbox-navigation-ios#3984]
### Mapbox Navigation SDK version

6.4.1

### Steps to reproduce

Please use attached project.  Add Mapbox access token, run pod install. Run in Xcode 14.0 beta 2 14A5229c 
[MapBoxIssue.zip](https://github.com/mapbox/mapbox-navigation-ios/files/9027880/MapBoxIssue.zip)
  

### Expected behavior

App should present the MGLMapView centred on the specific coordinates (not crash on iOS 16 beta simulator)

### Actual behavior

The app will crash when presenting view controller with MGLMapView view, running on iOS 16 beta simulator (Xcode 14.0 beta 2 14A5229c) 
*it is working fine on an actual device (iPhone 13 Pro) with iOS16 beta installed or iOS15 simulator, so it might be a bug on Apple's side

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
@martin-dzuro, what version of Navigation SDK you're using? Is it `v1.x`? You've mentioned that it's `v6.4.1`, but it's Maps SDK dependency version.

**Comment by MaximAlien** [comment]
This is not a Navigation SDK issue. Something is wrong with `MGLMapView` presentation when using iOS 16 Beta 2. I've created a ticket on Maps SDK side [here](https://github.com/mapbox/mapbox-gl-native-ios/issues/657). I'll also run some more tests on iOS 16 Beta 3 to see if it's fixed there.

**Comment by MaximAlien** [comment]
@martin-dzuro, issue is no longer reproducible when using Xcode 14 Beta 3.
