### ISSUE TITLE
Cartfile is being updated, but README says it's not supported

### ISSUE THREAD

**Issue by sundeepgupta** [mapbox/mapbox-navigation-ios#3994]
Is Carthage supported for the latest version? 

The [`Cartfile` history](https://github.com/mapbox/mapbox-navigation-ios/commits/main/Cartfile) suggests it is, but the README explicitly states it's not:

> MapboxNavigation no longer supports Carthage as of v2.0.0-alpha.1

**Comment by MaximAlien** [comment]
@sundeepgupta, that's correct. `MapboxNavigation` module is not available in Carthage (other dependencies we rely on are not available in Carthage). `MapboxCoreNavigation` is still available in Carthage though.
