### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AmitSiliconOrchard** [mapbox/mapbox-navigation-ios#4005]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

Apply custom DayStyle or NightStyle for modification of Navigation UI.

let proxyCancelButton = CancelButton.appearance()
proxyCancelButton.setImage(nil, for: .normal)

Apply custom style using navigationOptions.

### Expected behavior

Always should clear the cross icon in the exit button.

### Actual behavior

It we run navigation first time, everything works fine. But if we exit and run again, then the cross doesn't go away. It stays rest of the apps life cycle, no matter how many times you reopen the navigation.

Note: The issue started after updating Navigation SDK to 2.6.0. Everything was working fine till than.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
Hello @AmitSiliconOrchard. Can you try to use such appearance styling now:
```swift
let phoneTraitCollection = UITraitCollection(userInterfaceIdiom: .phone)
let cancelButtonPhoneAppearance = CancelButton.appearance(for: phoneTraitCollection)
cancelButtonPhoneAppearance.setImage(nil, for: .normal)
```

Recent changes were made to support independent appearance styling for iOS and CarPlay, so from now on you'll have to modify appearance for specific platform instead of global.

**Comment by AmitSiliconOrchard** [comment]
Issue solved. Thank You. Closing it.
