### ISSUE TITLE
Module compiled with Swift 5.5.1 cannot be imported by the Swift 5.6.1 compiler

### ISSUE THREAD

**Issue by johncadengo** [mapbox/mapbox-navigation-ios#4014]
### Mapbox Navigation SDK version

2.6

### Steps to reproduce

I'm just including it in my podfile

### Expected behavior

I expect to be able to build my project

### Actual behavior

It prevents me from building my project with this error:

`module compiled with Swift 5.5.1 cannot be imported by the Swift 5.6.1 compiler`

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by johncadengo** [comment]
Version 13.4.1 (13F100)

I'm on an M1 Mac with Mac OS version 12.3.1

**Comment by MaximAlien** [comment]
@johncadengo, that's strange. I have no issues building it with Xcode `v13.4.1` and macOS `v12.4` (not on M1 though). Our examples [repo](https://github.com/mapbox/mapbox-navigation-ios-examples) also builds just fine. Would you be able to share your `Podfile`?

**Comment by johncadengo** [comment]
I removed the irrelevant pods in the file. Two pods come from Mapbox.

```source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Outreach Grid User' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MapboxMaps', '10.6.1'
  pod 'MapboxStatic.swift', '~> 0.12'

  target 'Outreach Grid UserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Outreach Grid UserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end```

**Comment by MaximAlien** [comment]
@johncadengo, I've tried to reproduce with your configuration, but have no issues. I recommend cleaning CocoaPods cache (e.g. `/Users/USER_NAME/Library/Caches/CocoaPods`) and derived data (e.g. in `/Users/USER_NAME/Library/Developer/Xcode/DerivedData`) and re-build everything from scratch.
