### ISSUE TITLE
SpeedLimitView always show during navigation

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#4025]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

Create instance of NavigationViewController, try to set speedLimitView.isHidden = false

What I want to achieve is that I want to display the speed limit indicator always.
Right now, the single option regarding speed limit is 
```
navigationViewController.showsSpeedLimits = true
```
Which by default is true, but is not showing the speed limit always
I tried to access the SpeedLimitView via ornaments controller or navigationView but it's showing compilation issue because those are internal private level protected

### Expected behavior

An option to set the SpeedLimitView always shown

### Actual behavior

No way to access it to set it always display.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
@nastasiupta, would `SpeedLimitView.shouldShowUnknownSpeedLimit` property work for you in this case? If it's set to `true` `SpeedLimitView` will always be show and `--` text will be shown if the is no speed limit information.

**Comment by nastasiupta** [comment]
@MaximAlien 'navigationView' is inaccessible due to 'internal' protection level
The next SDK version will make this properly public?

**Comment by MaximAlien** [comment]
@nastasiupta, it was made public in `v2.7.0-beta.3`, so you can modify its properties now.
