### ISSUE TITLE
Present NavigationViewController from NavigationMatchOptions with traffic data

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#4026]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

This is the way I set up the navigation screen: https://github.com/mapbox/mapbox-navigation-ios/issues/3991
I don't find a way to enable/disable traffic information displayed on the navigation screen. 
I searched the documentation but I couldn't find something useful :| ... there should be a way, but I think is something I don't understand...

### Expected behavior

An option to set display traffic data on/off when I setup the navigation screen

### Actual behavior

Traffic toggle traffic information not available?

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by MaximAlien** [comment]
@nastasiupta, you can use `MapView.showsTraffic` public property to disable traffic. Make sure to do that only after fully loading the style.
