### ISSUE TITLE
Route preview and turn-by-turn UI in the same view?

### ISSUE THREAD

**Issue by sundeepgupta** [mapbox/mapbox-navigation-ios#4031]
Hi there, I've been looking at how things are done and it seems that the route preview needs to be shown in a `NavigationMapView`, but then the navigation is done by presenting/pushing/embedding a `NavigationViewController` - which also has its own `NavigationMapView`. 

I haven't seen any docs/examples where the same `NavigationMapView` is used. Is there a reason for this? Did I miss something in the docs? Is it possible to use the same view for both - perhaps with `NavigationViewController`?

One thing I see is that navigation is started when `NavigationViewController` loads: https://github.com/mapbox/mapbox-navigation-ios/blob/84c804fb2a9b7c1682170ccffaa6e93caffa5481/Sources/MapboxNavigation/NavigationViewController.swift#L256-L257

**Comment by MaximAlien** [comment]
@sundeepgupta, that's correct, one clarification regarding `NavigationViewController` case is that internally it uses `NavigationView`, that actually contains `NavigationMapView`. `NavigationView` adds some more UI on top: top and bottom banner containers , floating buttons, speed limit and road name label. https://github.com/mapbox/mapbox-navigation-ios/pull/4017 added that ability to access some of `NavigationView` APIs via `NavigationViewController` (not in GA yet). I think that you can use it independently as well.

Speaking of `MapboxNavigationService` usage with `NavigationMapView`: it's possible, to use it outside of `NavigationViewController` but we do not have public docs for this at this point (I'll create a ticket to document it). You can check our internal [example](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Example/CustomViewController.swift) as a reference.

Regarding `NavigationMapView` re-usage between preview and active navigation state: it's also possible (with some caveats). There is `NavigationOptions.navigationMapView` [property](https://docs.mapbox.com/ios/navigation/api/2.6.0/Classes/NavigationOptions.html#/s:16MapboxNavigation0B7OptionsC17navigationMapViewAA0beF0CSgvp), you can assign your current `NavigationMapView` instance there, it'll then be used by `NavigationViewController`. Beware that `NavigationViewController` will apply several changes to that `NavigationMapView` (`NavigationCamera` will be switched to `.following` state etc), that will not be reverted when dismissing `NavigationViewController`, so at this point end user is responsible for this (e.g. setting gesture recognizers, changing `MapView` style etc).

In https://github.com/mapbox/mapbox-navigation-ios/pull/4022 we try to improve these transitions and then document them, but at this point such functionality is not released yet.

**Comment by MaximAlien** [comment]
So in short here're some configurations you can have:
- Preview in `NavigationMapView` - active navigation in `NavigationViewController`.
- Preview in `NavigationMapView` - active navigation in `NavigationViewController` with `NavigationMapView` instance re-usage from preview state. See [NavigationOptions.navigationMapView](https://docs.mapbox.com/ios/navigation/api/2.6.0/Classes/NavigationOptions.html#/s:16MapboxNavigation0B7OptionsC17navigationMapViewAA0beF0CSgvp).
- Preview and active navigation in `NavigationMapView`. See [example](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Example/CustomViewController.swift).
- Preview and active navigation with `NavigationView`. Will be available in `v2.7`.

**Comment by sundeepgupta** [comment]
Thanks for the comprehensive answer. Based on what you say, would you agree that the more advisable route is to use the first configuration if there's not too much customization needed:

- Preview in `NavigationMapView` - active navigation in `NavigationViewController`

If so, I'd want make it _look_ like everything is being done in a single view, so I'd want to embed the `NavigationViewController` into the VC holding the original `NavigationMapView` with the route preview and show/hide preview and navigation. 

When the navigation is in progress, and the user wants to pause/stop the navigation, I'd want to show an updated route preview. Is there a way to update the route preview automatically? Or would a new `Directions.shared.calculate` call be needed in this case? Or is there a way to do this more simply via `NavigationViewController`. I see `NavigationCameraState.following` and `.overview`, but don't see how to set this explicitly.

**Comment by MaximAlien** [comment]
@sundeepgupta, guide for navigation camera APIs can be found [here](https://docs.mapbox.com/ios/navigation/guides/map-and-camera/navigation-camera/#how-to-use-navigation-viewport-camera). Basically everything related to work with navigation camera is done via `NavigationMapView.navigationCamera` property. 

Speaking of preferred presentation choice: it depends on your application features and how you want to extend certain functionality in future. `Preview in NavigationMapView - active navigation in NavigationViewController` approach is the most popular one and we showcase it in our examples, but there is more work to do if you want a seamless transition. We actually try to improve this part by refining our APIs. You can look at https://github.com/mapbox/mapbox-navigation-ios/pull/4022 as a reference.

> I'd want to show an updated route preview. Is there a way to update the route preview automatically? Or would a new `Directions.shared.calculate` call be needed in this case?

Depends on a level of changes that were made to the route line during active navigation. If a lot of changes were made to the `MapView` style we cannot guarantee it, if a route line was simply shown without major changes you can directly access `NavigationMapView` APIs to present original route line using `NavigationMapView.showcase(_:routesPresentationStyle:animated:)` or `NavigationMapView.show(_:layerPosition:legIndex:)` after dismissing `NavigationViewController`.

**Comment by sundeepgupta** [comment]
Thank you, I will look into those things you mention.

**Comment by sundeepgupta** [comment]
@MaximAlien, #4022 , is what we're after and I see there are changes required to the SDK. I'm trying to decide if we should

1. Wait for GA release.
2. Wait for Beta release.
3. Consume the PR branch/code via fork. 

Can you share any ETAs on the first two options?

**Comment by MaximAlien** [comment]
Hello @sundeepgupta, please see my answers:
1. https://github.com/mapbox/mapbox-navigation-ios/pull/4022 will be available in `v2.7.0 GA` (will be released in three weeks, during a week of August 15th).
2. `v2.7.0-beta.3` will be available this week, possibly tomorrow, or on Friday. It'll contain this PR.
3. I'll merge this PR today, beware that this is not a "final look" of the APIs, we will do some testing to make a decision, also even though some APIs were made public, they're undocumented yet. I'd also like to note that there is quite some work to be done on a client side (presentation and dismissal transitions should be implemented by the client). I've also noticed some issues here and there, I'll be addressing them in further releases.

After releasing GA we plan to create several examples to showcase such functionality in https://github.com/mapbox/mapbox-navigation-ios-examples/issues/171 and https://github.com/mapbox/mapbox-navigation-ios-examples/issues/170.

**Comment by sundeepgupta** [comment]
Thanks @MaximAlien those timelines will be helpful for us. 

Can you elaborate on:
>  I've also noticed some issues here and there

**Comment by MaximAlien** [comment]
> I've also noticed some issues here and there

It'll depend on the level of complexity of your app, but if you heavily modify `NavigationMapView` you have to remember to revert all previous modifications (e.g. I've noticed that gesture recognizers might not work, if `NavigationViewController.routeLineTracksTraversal` is set to true after dismissal route line might end up trimmed, route duration annotations will have to be removed (shown via `NavigationMapView.showRouteDurations(along:)`) etc).

**Comment by sundeepgupta** [comment]
Ok I see. thank you.

**Comment by samuelalake** [comment]
> After releasing GA we plan to create several examples to showcase such functionality in [mapbox/mapbox-navigation-ios-examples#171](https://github.com/mapbox/mapbox-navigation-ios-examples/issues/171) and [mapbox/mapbox-navigation-ios-examples#170](https://github.com/mapbox/mapbox-navigation-ios-examples/issues/170).

Hey @MaximAlien , do you know if these examples are released?
