### ISSUE TITLE
Migrate Transifex configuration to v3 API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#4052]
This project’s Transifex configuration is written for Transifex API v2, which was deprecated in January and [will be decommissioned](https://docs.transifex.com/client/client-configuration) on November 30. We need to install a newer version of the `tx` client and [migrate the configuration](https://github.com/transifex/cli#migrating-from-older-versions-of-the-client) to the new format by running `tx migrate`. Transifex says the `tx pull` step will be faster as a result.

https://github.com/mapbox/mapbox-navigation-ios/blob/64d3158528cdf0eb8c32a04710bdb42b291e5894/.tx/config#L7

Thanks to @S2Ler for the heads-up.

/cc @mapbox/navigation-ios @mapbox/language

**Comment by azarovalex** [comment]
@SevaZhukov Can you take a look at this issue?
