### ISSUE TITLE
[Bug]: No Speed Limit data come through in the Free Drive mode

### ISSUE THREAD

**Issue by dmitry-yashkin** [mapbox/mapbox-navigation-ios#4066]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

Run the Examples app and notice that no speed limit view is being displayed.

![IMG_6061](https://user-images.githubusercontent.com/38925202/183887280-3d735e79-23c5-49a1-bb37-37716f2c220f.PNG)

If I start TxT navigation then a speed limit view will show up on the main map.

![IMG_6062](https://user-images.githubusercontent.com/38925202/183887557-94508777-db16-4632-8316-b040193b4e4d.PNG)

![IMG_6063](https://user-images.githubusercontent.com/38925202/183887533-391a1f47-a3e8-4794-8d30-4bcec3c13b0d.PNG)

Free Drive is activated on the app start. Could you clarify if I'm expected to make any special api calls or set something up to start getting speed limit data in the Free Drive mode?

### Expected behavior

Speed Limit view is being displayed when Free Drive is active.

### Actual behavior

No Speed Limit data is being displayed when Free Drive is active.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
@dmitry-yashkin The speed limit data in `Example` app during Free Drive is active. Could you try to choose the `Simulator - Features - Location` as `Freeway Drive`? It should show the speed limit data. If there's no valid speed limit data, the speed limit view will be hidden.

**Comment by dmitry-yashkin** [comment]
Confirmed. It's working good on my side. Thank you @ShanMa1991!
