### ISSUE TITLE
[Bug]: Could not get the new Navigation SDK 2.0 UI

### ISSUE THREAD

**Issue by golets-dev-team** [mapbox/mapbox-navigation-ios#4092]
### Mapbox Navigation SDK version

2.7.0

### Steps to reproduce

- Go read the whole documentation: https://docs.mapbox.com/ios/navigation/examples/basic/
- Try to use the drop in UI
- Can only get the old Navigation UI
<img width="413" alt="Capture d’écran 2022-08-23 à 08 22 43" src="https://user-images.githubusercontent.com/108757525/186085545-2dd0bed5-1a42-4a3e-bad3-0b7fd07c6bc9.png">

### Expected behavior

- Should show the new UI
<img width="1370" alt="Capture d’écran 2022-08-23 à 08 57 36" src="https://user-images.githubusercontent.com/108757525/186091602-4e6d1d15-7561-4cac-9ebf-0da762b4599d.png">

### Actual behavior

-Shows the old UI
<img width="413" alt="Capture d’écran 2022-08-23 à 08 22 43" src="https://user-images.githubusercontent.com/108757525/186085545-2dd0bed5-1a42-4a3e-bad3-0b7fd07c6bc9.png">

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
Hi @golets-dev-team The [link](https://docs.mapbox.com/ios/navigation/examples/basic/) you sheared is for the basic navigation functionality which has the same UI as before. The new Drop-in UI for iOS is currently under development. And it's not included in [v2.7.0](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.7.0) yet.

**Comment by azarovalex** [comment]
Thanks Shan!
@golets-dev-team also note that in general NavSDK is highly customizable and you can build any UI you want on top of the map and Core navigation logic from `MapboxCoreNavigaiton` package (which includes route request, rerouting, map-matching, etc.).
For now I'll close the issue since there isn't much we can do.
