### ISSUE TITLE
[Bug]: Undefined symbol for MapboxNavigation.NavigationMapView.highlightedBuildingIdentifiersByCoordinate

### ISSUE THREAD

**Issue by latargere** [mapbox/mapbox-navigation-ios#4107]
### Mapbox Navigation SDK version

Starting from 2.7.0-rc.1

### Steps to reproduce

Trying to update from 2.7.0-beta3 to every above version but there is an undefined symbol for arm64:

Showing All Messages
Undefined symbol: MapboxNavigation.NavigationMapView.highlightedBuildingIdentifiersByCoordinate.modify : Swift.Dictionary<__C.CLLocationCoordinate2D, Swift.Int64>

Undefined symbol: MapboxNavigation.NavigationMapView.highlightedBuildingIdentifiersByCoordinate.getter : Swift.Dictionary<__C.CLLocationCoordinate2D, Swift.Int64>

Undefined symbol: MapboxNavigation.NavigationMapView.highlightedBuildingIdentifiersByCoordinate.setter : Swift.Dictionary<__C.CLLocationCoordinate2D, Swift.Int64>

Probably related to this PR:
https://github.com/mapbox/mapbox-navigation-ios/pull/4034

Reason is the hashable extension for CLLocationCoordinate2D conflict with the one from our package. The one from mapbox should stay inside the scope of the framework

### Expected behavior

Just compile :) 

### Actual behavior

Cannot compile

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
@latargere Thanks for the information, we'll work on this issue.

**Comment by ShanMa1991** [comment]
@latargere This issue is fixed by #4109 and is included in the [v2.7.2 release](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.7.2). Please feel free to reopen this ticket if your issue is not solved by the fix.
