### ISSUE TITLE
Skipping an unreachable waypoint 

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4122]
While testing our App, we encountered a small problem that has large consequences. The Route we calculated on our own backend had a waypoint that was on a private road, which was unreachable for the driver. However, since the driver could never get to the waypoint, any re-routing that occurred when the driver tried skipping it was routing him back to the first waypoint. 

As a fix, we wanted to add a button that appeared as soon as the driver gets to a certain distance from the waypoint. This can be achieved using a routeProgress Notification
`NotificationCenter.default.addObserver(self, selector: #selector(progressDidChange(notification:)), name: .routeControllerProgressDidChange, object: nil)`

This could alert the client when the user has a certain distance or percentage left to reach the waypoint. 
However, I am not able to find a function that could skip the current waypoint or make it as if I had reached it already. We want to avoid reloading a new navigation as we are already doing this multiple times and if I understand correctly, this would cost one additional navigation call - when doing this hundred of thousands of times, it could get nasty. 

Is there a way to sort of fake DidArriveAtWaypoint in some sort?

**Comment by 1ec5** [comment]
> While testing our App, we encountered a small problem that has large consequences. The Route we calculated on our own backend had a waypoint that was on a private road, which was unreachable for the driver. However, since the driver could never get to the waypoint, any re-routing that occurred when the driver tried skipping it was routing him back to the first waypoint.

Which version of the navigation SDK are you using? #3943 fixed a similar-sounding issue; it went into v2.5.2.

> However, I am not able to find a function that could skip the current waypoint or make it as if I had reached it already.

The [`Router.advanceLegIndex(completionHandler:)`](https://docs.mapbox.com/ios/navigation/api/2.7.2/Protocols/Router.html#/s:20MapboxCoreNavigation6RouterP15advanceLegIndex17completionHandleryys6ResultOyAA13RouteProgressCs5Error_pGcSg_tF) method forces the route controller to advance to the next leg of the route, no matter how far away the user is from the upcoming waypoint.

**Comment by JanTG1** [comment]
Tried it and seems to be working at first glance. I will be closing this issue and will reopen in case it did not work as expected. Thanks!
