### ISSUE TITLE
Something similar to Android's `Status` UI component?

### ISSUE THREAD

**Issue by sundeepgupta** [mapbox/mapbox-navigation-ios#4137]
Is there something similar to Android's [`Status`](https://docs.mapbox.com/android/navigation/guides/ui-components/status-view/)? Or some kind of loading/spinner UI? 

I didn't see when when searching the docs, and wanted to confirm before making any decisions.

**Comment by MaximAlien** [comment]
Hello @sundeepgupta. I do not think that we have exactly the same component as it's mostly aligns with Android UI guidelines and there is no concept of a "toast" view on iOS.

The closest UI component we have is called [StatusView](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxNavigation/StatusView.swift). It's shown at the bottom of `TopBannerViewController` and allows to show and hide `Status`. For example:

![Screen Shot 2022-09-08 at 10 21 36 AM](https://user-images.githubusercontent.com/1496498/189185838-a40935f0-f49b-4328-be8b-b00c09bac8ca.png)

**Comment by sundeepgupta** [comment]
Thanks - not sure why I couldn't find when searching the docs. 

We're looking for a non-interact-able loading UI that shows up on the map while fetching the route data, (`Directions.calculate(...)`). So this may not work, in which case we'll use/write our own loading UI.

**Comment by sundeepgupta** [comment]
Or I suppose we could use StatusView as well directly in the map view.
