### ISSUE TITLE
[Bug]: Multiple crashes occur in `SpriteRepository` during offline navigation.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#4141]
### Mapbox Navigation SDK version

main

### Steps to reproduce

1. Start active navigation that contains shield icons.
2. Switch to offline mode.
3. Open `StepsViewController` and start scrolling.
4. Observe behavior.

### Expected behavior

Crash should not occur.

### Actual behavior

Crash occurs while scrolling `StepsViewController`.

Here're are some of crash logs:

[Example  9-2-22, 1-04 PM.crash.zip](https://github.com/mapbox/mapbox-navigation-ios/files/9537891/Example.9-2-22.1-04.PM.crash.zip)
[Example  9-2-22, 12-30 PM.crash.zip](https://github.com/mapbox/mapbox-navigation-ios/files/9537892/Example.9-2-22.12-30.PM.crash.zip)
[Example  9-2-22, 12-34 PM.crash.zip](https://github.com/mapbox/mapbox-navigation-ios/files/9537893/Example.9-2-22.12-34.PM.crash.zip)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
This issue will happen when no network provided. When the instruction is updated to `InstructionLabel`,  `InstructionPresenter` will check if there's cache ready to use, if not, it will use generic shield but keep sending downloading requests to the `SpriteRepository`. The tasks in `ImageDownloader` will keep adding the operation to the queue and cause crash. 
I think we could add timeout interval constraint to the `ImageDownloader`, and avoid the repeating request for shield if no image cached in `InstructionPresenter`
