### ISSUE TITLE
Add option to make borderCrossing initializer(s) publicly accessible

### ISSUE THREAD

**Issue by unatarajan** [mapbox/mapbox-navigation-ios#4148]
Request for a new feature / improvement to an existing feature based on a user’s request.
Switch to public OR have option to switch to public the [BorderCrossing](https://docs.mapbox.com/ios/navigation/api/2.7.2/Other%20Structs.html#/s:20MapboxCoreNavigation14BorderCrossingV) struct or borderCrossing initializer. Currently both are only available as internal.

**Comment by kried** [comment]
[BorderCrossing](https://docs.mapbox.com/ios/navigation/api/2.12.0/Structs/BorderCrossing.html#/s:20MapboxCoreNavigation14BorderCrossingV4from2toAC0A10Directions20AdministrativeRegionV_AHtcfc) initializer is public starting from [v2.9.0](https://github.com/mapbox/mapbox-navigation-ios/blob/main/CHANGELOG.md#other-changes-3)
