### ISSUE TITLE
Rename StatusPollingConfig

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#4149]
#4135 introduced a StatusPollingConfig struct, which doesn’t follow Swift API naming guidelines because it abbreviates “configuration” as “config”. At least it should be renamed StatusPollingConfiguration or, for consistency with the containing struct, StatusPollingSettings. “Polling” is also an implementation detail; better to call it StatusUpdatingSettings or just StatusTiming.

More broadly, I’m unsure why we have a struct as opposed to two standalone properties, but I guess it keeps the initializer from getting even more unwieldy. We’re at the point where NavigationSettings itself should probably be a struct and we’d track an instance of it as a global property or something along those lines.

Marking this as a release blocker so we fix the issue before fixing it would become a backwards-incompatible change.

/cc @mapbox/navigation-ios

**Comment by ShanMa1991** [comment]
Close this issue because it's fixed by #4152 4152
