### ISSUE TITLE
Omit parens in voice instruction

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#415]
Currently they are spoken. 

/cc @1ec5

**Comment by 1ec5** [comment]
This is related to our use of the `interpret-as="address"` SSML tag.

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/286#issuecomment-315584617

**Comment by bsudekum** [comment]
The root issue here has been fixed.

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-ios#418 fixed the issue by removing the parentheses. Was there another “root” fix?
