### ISSUE TITLE
[Bug]: NavigationViewController forgets Waypoint names after rerouting

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4180]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

1. Create a Route with a given set of Waypoints, each with a custom name. 
2. Start driving in a simulator and go off-road to trigger a reroute from shouldRerouteFrom. 
3. Check the names of your waypoints.  

### Expected behavior

The waypoints should keep their attributes such as their name/descriptions.

### Actual behavior

The waypoints are renamed to describe the position they are at, like the road name for example. This creates issues because I use the waypoint names to identify what kind of waypoint it is and handle logic based on that information. This breaks as soon as a reroute is called even once. 

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by JanTG1** [comment]
Any updates on this issue? It's breaking our concept since we use the waypoint names to identify the kind of waypoint. Forgetting the names breaks this functionality...

**Comment by JanTG1** [comment]
HI @S2Ler, thanks for responding! I can't seem to get v2.8.1 to work with cocoapods, as stated in my initial issue, the bug happens on 2.6.0.

To avoid having to write a test project, I'll try to demonstrate it step by step. Hope this makes it clear.

1. Create a Mapview, very simple. 
2. Add a button that calculates a route with three waypoints: a current location, a random test waypoint with a given set of coordinates, and a destination coordinate. Make sure to name the test Coordinate to test the bug. Make the button start a navigation with the navigationViewController we just created for it and present the view.
3. Look for the waypoint we created in the trip overview as I have done here.
![IMG_7231](https://user-images.githubusercontent.com/92864392/198560159-71936c89-1b1c-42ed-9542-fe4e594bc7cd.PNG)
As you can see, the waypoint is named "TestWaypoint".
4. Move around to trigger a new route calculation, which should happen when you go the wrong way or seem to be near another road. This happens in this screenshot: ![IMG_7232](https://user-images.githubusercontent.com/92864392/198560562-5b161389-a4ee-4bb0-85eb-17838dd5aa5d.PNG)
5. After the popup disappears, look for the waypoint once again.
![IMG_7233](https://user-images.githubusercontent.com/92864392/198560702-d6121588-3a1c-4120-89e7-a7efc7bb435a.PNG)
As can be seen very clearly, the waypoint is now called "B9", which is simply the name of the road it is on. This seems to be the default name that is given to a waypoint that has not been given a name. 

Are you able to reproduce this? If not I will try to create a test project that does exactly this. However it seems to be so simple, I'd assume that by using the same version, you should get this same behavior.

**Comment by JanTG1** [comment]
@S2Ler were you able to recreate the behavior? Need any other information?

**Comment by kried** [comment]
@JanTG1 Please update Navigation SDK to [v2.7.0](https://github.com/mapbox/mapbox-navigation-ios/blob/main/CHANGELOG.md#routing-3) or newer. The problem with missed name fields in waypoints after rerouting is already fixed. 

> * Fixed lost target and name fields in waypoints after rerouting, and the bearing calculation error during tunnel dead reckoning. (https://github.com/mapbox/mapbox-navigation-ios/pull/4044)
