### ISSUE TITLE
How to adjust size of the compass in mapview for IOS SDK

### ISSUE THREAD

**Issue by BlandHite** [mapbox/mapbox-navigation-ios#4206]
How to adjust size of the compass in mapview for IOS SDK

Use MapboxNavigation 2.5.0, I can change the position,but I don't know how to change size

**Comment by evil159** [comment]
@BlandHite You can affect the compass size by providing a custom image for the compass view:
```swift
mapView.ornaments.options.compass.image = UIImage(systemName: "safari")
```
