### ISSUE TITLE
[错误]：When the navigation to the destination, the navigation route appears many turns, resulting in the route error, resulting in the current navigation cannot end

### ISSUE THREAD

**Issue by xiaoxin3838438** [mapbox/mapbox-navigation-ios#4221]
### Mapbox Navigation SDK version

2.5.1

### Steps to reproduce

When I set the destination to the place after the turn, and then run it on the official DEMO, the result of unable to finish the navigation appeared. If the first navigation is unsuccessful, you can try several times, which is inevitable. The speed of my simulation operation is 5 times faster, and the longitude and latitude coordinates of the test are:

Start: CLLocationCoordinate2DMake(29.7486629486084, 106.55250549316406)
end: CLLocationCoordinate2DMake(29.748327255249023, 106.54768371582031)

DEMO_Video: [https://oss1.support.thinkerride.com/company/2022/11/normal-video.mp4](url)

### Expected behavior

The navigation ends normally

### Actual behavior

Navigation does not end automatically, it just pauses

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by jill-cardamon** [comment]
Hi @xiaoxin3838438! Your video links don't appear to be working. Could you add a video to the ticket?

**Comment by xiaoxin3838438** [comment]
> Hi @xiaoxin3838438! Your video links don't appear to be working. Could you attach a video to the ticket?

Okay, so now we've got a new link and you can try it out, I've compressed the video into a gif and you can see what it looks like, you can copy the connection address and open it up in a new browser window and try it out on github and it looks like you can't see the video.
gif images can be slow to load, I compressed 35 seconds of video, gif images are about 5 meters long

gif:
![tutieshi_544x960_35s](https://user-images.githubusercontent.com/11389246/199374501-263e1735-1fbe-4417-b552-4289f247483e.gif)

new video link：
[https://thinkerride.oss-cn-zhangjiakou.aliyuncs.com/company/2022/11/normal-video.mp4](url)

**Comment by jill-cardamon** [comment]
Is this the same code as in https://github.com/mapbox/mapbox-navigation-ios/issues/4207? What happens with simulation at 1x speed? Does the puck still jump back and forth? Are you indicating an approach side for this waypoint?

**Comment by xiaoxin3838438** [comment]
> 这与#4207中的代码相同吗？1倍速度的模拟会发生什么？冰球还在来回跳跃吗？您是否正在为这个路线点指明接近一侧？

That's right, the code is the same. My destination is not far to the left of the road after the sharp turn. From the gif, it can be seen that the destination does not end, but retrace the route before the sharp turn

**Comment by 1ec5** [comment]
Does the issue also reproduce if you set the simulation speed to 1× rather than 5×?

**Comment by xiaoxin3838438** [comment]
> Does the issue also reproduce if you set the simulation speed to 1× rather than 5×?

There is no abnormality in 1x velocity simulation for the time being, and the follow-up is under observation test

**Comment by kried** [comment]
We were able to reproduce a problem similar to what you described with Navigation SDK `v2.5.1`. It should be fixed in `v2.7.0`.
@xiaoxin3838438 Could you please try updating Navigation SDK to [v2.7.0](https://github.com/mapbox/mapbox-navigation-ios/blob/main/CHANGELOG.md#v270) or newer?
