### ISSUE TITLE
[Bug]: Skipping a Waypoint forcefully breaks the camera placement

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4228]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

1. Create a Mapview
2. Generate a route with at least one waypoint in it and start a navigation session
3. Forcefully "skip" a waypoint before having reached it using `self.navigationViewController.navigationService.router.advanceLegIndex(completionHandler: nil)`
4. See the result

### Expected behavior

The Navigator should be informed that the waypoint no longer needs to be driven to. Instead, the waypoint should behave like a silent waypoint (to which you drive over without it being a specified destination/waypoint in the navigator) while staying on the map (with less opacity, just like if you would have driven through it already). The Navigator should still keep your current location in the center and keep giving you the right instructions based on where you currently are.

### Actual behavior

The Navigator will do most of the things I stated above: It will lower the opacity of the waypoint and act as if I have already passed it since I told the router to advance to the next leg. However, the big issue is that the camera will then also act like you have passed that point and will be stuck on a road that is just after where the waypoint was. There is no way to reset the camera and the driver does not see where he is going. 

Demonstrating this with screenshots is not easy but here are two, one before skipping the waypoint and one after doing so. Note that on both screenshots I am in the standard camera view and not in the free topdown view!

Before:
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-02 at 16 24 03](https://user-images.githubusercontent.com/92864392/199530421-56efa15e-95c8-4c51-a4b1-a10bb4e4a57b.png)
After:
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-02 at 16 24 23](https://user-images.githubusercontent.com/92864392/199530416-03a05827-816c-47ed-8a03-476b9b807ee3.png)

The issue is rather logical given the name of the function. This is the only way I could find to "forget" a waypoint mid-way, which is core functionality for my app. 

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by jill-cardamon** [comment]
Hi @JanTG1! Could you attach a video/gif that shows the behavior you're seeing?

**Comment by JanTG1** [comment]
Hey @jill-cardamon, 
I've recorded a short gif demonstrating the issue. 
Note that I have two waypoints on the map at the beginning (can be seen) and I have a few extra floating buttons. When the QR Code shows up, a background task checks if it has been scanned or not by another phone. If it has been, it will trigger the code I mentioned before  (`self.navigationViewController.navigationService.router.advanceLegIndex(completionHandler: nil)`).

**Comment by jill-cardamon** [comment]
Hi @JanTG1! I see what you're saying. Yes this is how to call is intended, but the camera behavior is unexpected. To clarify, you're calling this method before arriving at the waypoint correct? Are you calling `navigationViewController(_ , didArriveAt:)` delegate at all?

**Comment by JanTG1** [comment]
@jill-cardamon any updates on this issue?

**Comment by JanTG1** [comment]
@jill-cardamon sorry for pressing but I need to know whether or not a solution to this is coming as I need this functionality to release my app. If not I need to work around it but it is far from optimal. I feel like it shouldn't be too much of an issue to add that functionality.
To make it clear, I need a function that basically turns a waypoint into a silent waypoint. The navigation should act as if the driver has already passed the waypoint even if he has not reached it yet. This can also come in handy when a waypoint is somewhere unreachable (for example a private road). This would make it possible to skip the waypoint with the touch of a button and continue the navigation session without restarting it completely.
