### ISSUE TITLE
Automatically switch to night style

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#423]
NavigationMapView should automatically switch to the Navigation Guidance Night v2 style (`mapbox://styles/mapbox/navigation-guidance-night-v2`) when the ambient light level is low or when the Smart Invert Colors option is enabled in iOS 11.

Ideally we’d darken the rest of the UI at the same time, perhaps using a Style. But that can be a separate task if it would require significant changes. Just swapping the style would be a welcome improvement in low-light conditions.

/cc @bsudekum @frederoni @ericrwolfe @aparlato

**Comment by frederoni** [comment]
We can rename DefaultStyle to DayStyle and create a NightStyle.
The ambient light or SIC trigger then just have to toggle `NavigationViewController.view.isHidden`
in order to switch between the day and night style for the UI.

A time-based trigger could also be interesting.

**Comment by 1ec5** [comment]
> or when the Smart Invert Colors option is enabled in iOS 11

I still think we should do this, based on [`UIAccessibilityIsInvertColorsEnabled()`](https://developer.apple.com/documentation/uikit/1615167-uiaccessibilityisinvertcolorsena) or the [`UIAccessibilityInvertColorsStatusDidChange`](https://developer.apple.com/documentation/foundation/nsnotification.name/1615196-uiaccessibilityinvertcolorsstatu) notification.

**Comment by ericrwolfe** [comment]
@1ec5 This is an iOS 11 beta feature, can you please ticket separately?

**Comment by 1ec5** [comment]
→ #539

**Comment by TCOA** [comment]
Is there a way for a developer to know which style is active?  I've had a request to do some features which require me to change the font depending on which is shown.

**Comment by 1ec5** [comment]
Yes, you can access the navigation view controller’s map view using the [`NavigationViewController.mapView`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.11.0/Classes/NavigationViewController.html#/c:@M@MapboxNavigation@objc%28cs%29MBNavigationViewController%28py%29mapView) property:

```swift
let styleURL = navigationViewController.mapView?.styleURL
```

**Comment by TCOA** [comment]
Thanks, I do get some info, though it is confusing....

When I start the app, I have the mapView, which shows in light background (I would call that 'day') and I get 
THE STYLE FOR DAY/NIGHT IS  mapbox://styles/mapbox/streets-v10

When I put routes to the map, it shows in dark background (I would say 'night' there...) and see
in startBasicNavigation THE STYLE FOR DAY/NIGHT IS  mapbox://styles/mapbox/navigation-guidance-day-v2
in setRideData THE STYLE FOR DAY/NIGHT IS  mapbox://styles/mapbox/streets-v10

after waiting for 'day', I get 
in startBasicNavigation THE STYLE FOR DAY/NIGHT IS  mapbox://styles/mapbox/navigation-guidance-day-v2
in setRideData THE STYLE FOR DAY/NIGHT IS  mapbox://styles/mapbox/streets-v10

I.e., no difference in the responses I get, so no use for what I need......

Is there something I'm missing - or a different way to get anything different for the day/night active screen/style/whatever?

**Comment by 1ec5** [comment]
> When I start the app (early in the morning - i.e., "night" outside), I have the mapView, which shows in light background (I would call that 'day' - not sure why it doesn't change on first load...) and I get
THE STYLE FOR DAY/NIGHT IS mapbox://styles/mapbox/streets-v10

The day/night setting only affects the map during turn-by-turn navigation. Standalone usage of NavigationMapView, such as in an application’s preview screen, is unaffected.

The map view’s `styleURL` should accurately reflect what you see, as long as you access that property after the day/night switching code runs. If you aren’t seeing the behavior you expect, please open a separate issue describing the problem. Alternatively, please feel free to [contact our support team](https://www.mapbox.com/contact/support/) if you need to share your code to better explain what you’re seeing.
