### ISSUE TITLE
[Bug]: RESUME BUTTON: Language discrepancies across devices & simulator 

### ISSUE THREAD

**Issue by engelzero** [mapbox/mapbox-navigation-ios#4263]
### Mapbox Navigation SDK version

v2.9.0

### Steps to reproduce

  pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.9.0'
  pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.9.0'

React native hybrid app 

### Expected behavior

Should default to project language / device localisation 

### Actual behavior

Different language to device setting

This bug only seems to occur on MapboxNavigation versions 2.0 onwards 

MapboxNavigation v1.2 language is set to device localisation and works as expected 

![Simulator Screen Shot - iPhone 8 - 2022-11-20 at 00 34 32](https://user-images.githubusercontent.com/16312538/202848820-ce50edc4-27b7-4342-b179-10aaec593fff.png)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by engelzero** [comment]
related: https://github.com/mapbox/mapbox-navigation-ios/issues/4038

**Comment by jill-cardamon** [comment]
Hi @engelzero! Are you using static frameworks with Cocoapods? Cross linking a response from the related ticket here: https://github.com/mapbox/mapbox-navigation-ios/issues/4038#issuecomment-1322559156
