### ISSUE TITLE
Rationalize freeway alert level thresholds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#427]
This is a proposal to overhaul the logic that determines the current alert level to make voice announcements more straightforward and predictable for off-ramp steps, potentially as a first step to overhauling the rest of the alert level logic.

Essentially, the `medium` and `high` alert levels would occur at specific distances ahead of the maneuver, with time thresholds still in place as fallbacks. Hopefully this approach will make the SDK feel more predictable to the user, so that they can better intuit the level of urgency of a particular voice announcement.

## Current behavior

`RouteController.monitorStepProgress(_:)` tracks the expected time until the user reaches the maneuver point and the distance to the maneuver point. Whichever threshold is reached first determines when the alert level changes to medium then high. The time threshold gives us the flexibility to handle diverse speeds and traffic conditions, while the distance threshold serves as a failsafe for the time threshold.

Unfortunately, we arrived at the current thresholds by trial and error, making them difficult to explain in a coherent manner. We’ve had to put lots of band-aids on top of this logic just to make it work. Some of these thresholds actually assume that the user is traveling in a parking lot, even if they’re on a freeway:

* We change to the `high` alert level 15 seconds or 100 meters ahead of a maneuver, regardless of the type of road. However, at a typical Canadian expressway speed of 100 km/h, a driver would cover 417 meters in 15 seconds or 100 meters in 3.6 seconds. In order for the distance threshold to kick in, the driver would need to be traveling no more than 24 km/h (15 mph).
* Similarly, we change to the `medium` alert level 70 seconds or 400 meters ahead of a maneuver. At 100 km/h, a driver would cover 1.9 km in 70 seconds or 400 meters in 14.4 seconds. The distance threshold assumes a speed of 21 km/h (13 mph).

Alert level | Time remaining | Distance remaining | Effective distance remaining<br>(65&nbsp;mph / 100&nbsp;km/h) | Speeds triggering distance threshold
----|----|----|----|----
`low` | — | — | — | — | —
`medium` | 70 s | 400 m | 1¼ mi<br>1.9 km | <13 mph<br><21 km/h
`high` | 15 s | 100 m | ¼ mi<br>417 m | <15 mph<br><24 km/h

## Proposed rationale

Even though both time and distance thresholds are ultimately necessary, one as a backup for the other, we should consider deemphasizing the time threshold in favor of the distance threshold while driving on a freeway. Drivers have learned to receive instructions at specific distances on freeways, based on where advance guide signage is placed.

Here are some relevant passages from the MUTCD, which is the standard for road signage in the United States:

* [Advance Guide Signs](https://mutcd.fhwa.dot.gov/htm/2009/part2/part2e.htm#section2E33) (for freeways):
  > For major and intermediate interchanges, Advance Guide signs should be placed at 1/2 mile and at 1 mile in advance of the exit with a third Advance Guide sign placed at 2 miles in advance of the exit if spacing permits. At minor interchanges, only one Advance Guide sign should be used. It should be located 1/2 to 1 mile from the exit gore. If the sign is located less than 1/2 mile from the exit, the distance displayed should be to the nearest 1/4 mile. Fractions of a mile, rather than decimals, should be displayed in all cases.
* [Advance Route Turn Assembly](https://mutcd.fhwa.dot.gov/htm/2009/part2/part2d.htm#section2D31) (for surface roads, excerpted here for comparison):
   > In low-speed areas, the Advance Route Turn assembly should be installed not less than 200 feet in advance of the turn. In high-speed areas, the Advance Route Turn assembly should be installed not less than 300 feet in advance of the turn. In rural areas, the minimum distance between an Advance Route Turn assembly and either a Destination sign or a Junction assembly should be 200 feet.

## Proposed behavior

Based on the MUTCD guidelines, I propose the following set of heuristics as a starting point for discussion. On a freeway (where the road classes include `motorway`), we’d continue to change to `low` alert level when completing a maneuver. Otherwise:

Alert level | At distance ahead (U.S./UK) | At distance ahead (metric) | Effective time remaining (60 mph) | Effective time remaining (100 km/h)
----|----|----|----|----
`low` | — | — | — | —
`medium` | 1 mi | 1 km | 55 s | 36 s
`high` | ½ mi | 500 km | 28 s | 18 s

The thresholds should vary based on the measurement system associated with the current system region: miles for the U.S. and UK, meters everywhere else. The values in the “effective time remaining” columns would inform the time thresholds we use as backup, but we can be flexible in order to accommodate a wider range of typical speeds. According to [this survey of traffic engineering studies](https://deepblue.lib.umich.edu/bitstream/handle/2027.42/894/80190.0001.001.pdf?sequence=2), the `high` threshold would comfortably allow for a couple lane changes.

I’m uncertain about a few aspects of this proposal:

* The `high` threshold is still far enough away from the maneuver that the user is unlikely to think of it as a “turn now” type of announcement, more like a “make sure you’re in the correct lane” announcement. Is it reasonable to expect the turn lane to be present a full half-mile out? Should we move the `high` threshold to ¼ mile, so that the user expects this announcement to be more urgent?
* As the above excerpts from the MUTCD indicate, there’s a significant distinction between major and minor interchanges. Should we double the distance thresholds for major interchanges? We can detect a major interchange by the presence of a `motorway` following the off-ramp instruction (at either a `turn` or `merge` instruction).
* In some cases, these new thresholds would cause announcements to be delivered later than before. If this is a concern, we should investigate timing the announcement to _end_ at the threshold rather than beginning at it, since we know how long a Polly-powered speech utterance will take to play.

/cc @mapbox/navigation @mapbox/directions

**Comment by 1ec5** [comment]
#448 implements thresholds at ½ mile and 2 miles for freeways.

**Comment by ericrwolfe** [comment]
Noting here that the timing for the proposed distances of 1mi, 0.5mi, 1km, and 500m are inconsistent with our existing heuristics and can lead to premature announcements. 

At 0.5mi, highway announcements are too early (28s) compared to our typical 15s announcement timing (https://github.com/mapbox/voyage-ios/issues/860).

The initial announcement should also be further out than 1mi and 1km on the highway, to allow sufficient time for switching across multiple lanes of traffic, exiting HOV lanes, etc.

Here's a refined set of highway timing heuristics based on some initial feedback until we can test more extensively:
* Imperial:
  * 2mi (110s)
  * 0.25mi (14s)
* Metric:
  * 2km (72s)
  * 0.5km (18s)

**Comment by 1ec5** [comment]
I’d be interested in finding out whether the following approach could mitigate the concerns about lane switching time:

> In some cases, these new thresholds would cause announcements to be delivered later than before. If this is a concern, we should investigate timing the announcement to end at the threshold rather than beginning at it, since we know how long a Polly-powered speech utterance will take to play.

**Comment by bsudekum** [comment]
These distances have been moved to the server.
