### ISSUE TITLE
Navigation Crashes

### ISSUE THREAD

**Issue by toothpiggystudio** [mapbox/mapbox-navigation-ios#428]
Hi, i have tried to test the navigation and my app crashes when i close the navigation and after 5-10 seconds the app crashed. i also test the sample script on the documentation and it still crashes.

I tried this one

let origin = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 38.9131752, longitude: -77.0324047), name: "Mapbox")
let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 38.8977, longitude: -77.0365), name: "White House")

let options = RouteOptions(waypoints: [origin, destination], profileIdentifier: .automobileAvoidingTraffic)
options.routeShapeResolution = .full
options.includesSteps = true

Directions.shared.calculate(options) { (waypoints, routes, error) in
    guard let route = routes?.first else { return }

    let viewController = NavigationViewController(for: route)
    viewController.simulatesLocationUpdates = true
    self.present(viewController, animated: true, completion: nil)
}

and i got an (lldb) error on AppDelegate.swift and there is no other explanations, 

hope you can help me.

Thanks :)

**Comment by frederoni** [comment]
Thank you for your report.
It looks like you are using a slightly outdated version of the SDK.
We used `simulateLocationUpdates` in version 0.3.0 but the current release is 0.5.0 and 0.6.0 is just around the corner. Would you mind giving the latest version a try?

Updated readme in https://github.com/mapbox/mapbox-navigation-ios/pull/429

**Comment by toothpiggystudio** [comment]
Hi, 

Thank you for your reply,  I have test  0.5.0 right now and still the same, i’ll will try to test the 0.6.0

Thanks Again :)

**Comment by toothpiggystudio** [comment]
Hi, i just update all the mapbox and still the same, when i tried to use the turn-by-turn navigation and close it after 10 seconds then the app crashes after 5-10 seconds with this error with no details on the console us this (lldb) error on AppDelegate.swift, please see attached. 

![screen shot 2017-07-26 at 4 34 06 pm](https://user-images.githubusercontent.com/28891494/28620967-4e65cbf0-7220-11e7-98d1-39f7cc3df123.png)
![screen shot 2017-07-26 at 4 33 27 pm](https://user-images.githubusercontent.com/28891494/28620968-4e695f04-7220-11e7-9abf-6e2d2dc2d092.png)

**Comment by frederoni** [comment]
This issue was fixed 8 days ago in #399 which is scheduled for released in [v0.6.0](https://github.com/mapbox/mapbox-navigation-ios/releases).

Try a build from master or wait for the 0.6.0 release.

**Comment by toothpiggystudio** [comment]
Hi Fredrik, thanks for your reply. yes i’ll just wait for the released of V. 0.6.0
