### ISSUE TITLE
Add a annotation on the Navigation map view other than destination

### ISSUE THREAD

**Issue by NiketanG** [mapbox/mapbox-navigation-ios#4313]
I want to add a new marker in the mapview that can be visible while the user is navigating. I have tried using the PointAnnotationManager but no luck. The annotation I want to add is not limited to be on the route itself, but should be visible when when zoomed out/in as well. 

A snippet of the code I tried:

```
let pointAnnotationManager = navigationMapView.mapView.annotations.makePointAnnotationManager()


let pointCoordinate = CLLocationCoordinate2D(latitude: latitude as! CLLocationDegrees, longitude: longitude as! CLLocationDegrees)
var customPointAnnotation = PointAnnotation(coordinate: pointCoordinate)
customPointAnnotation.image = .init(image: UIImage(named: "default_marker")!, name: "red_pin")

// Add the annotation to the manager in order to render it on the map.
pointAnnotationManager.annotations.append(customPointAnnotation)
```
To be specific, I need to add a marker on this screen:
<img width="335" alt="Screenshot 2022-12-20 at 12 29 53 PM" src="https://user-images.githubusercontent.com/22788998/208603487-fca0260b-c07c-4721-842a-f4ab5003c490.png">

Is there a way to do so? Or am I missing something ?

**Comment by MaximAlien** [comment]
@NiketanG, could you please check whether `MapView`'s style is fully loaded before creating `AnnotationManager`? You can use `.styleLoaded` event for that.

**Comment by NiketanG** [comment]
Solved by using NavigationMapViewDelegate methods and using pointAnnotationManager from the parameters.  

Reference: https://docs.mapbox.com/ios/navigation/examples/custom-destination-marker/
