### ISSUE TITLE
Filter inaccurate GPS

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#433]
GPS locations are not guaranteed to be accurate. We should filter out any locations with poor accuracy (>= 100m horizontal, <= 0m horizontal, >= 30m vertical, <= 0m vertical).

cc @mapbox/navigation-ios

**Comment by ericrwolfe** [comment]
Noting that we should still store these in the [`pastLocations`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L395) array, but discard them when calculating any route step/off route/etc.

**Comment by 1ec5** [comment]
> We should filter out any locations with poor accuracy (>= 100m horizontal, <= 0m horizontal, >= 30m vertical, <= 0m vertical).

Are you referring to the `horizontalAccuracy` property, or to the distance from the route line? It’s interesting that iOS would send us locations with such high reported `horizontalAccuracy` values when the `desiredAccuracy` is set to `kCLLocationAccuracyBestForNavigation` or `kCLLocationAccuracyBest`. Could it be that some of these highly inaccurate readings are from cell tower triangulation before the location manager is able to get a GPS reading?

**Comment by ericrwolfe** [comment]
@1ec5 `horizontalAccuracy`. 

From the docs (https://developer.apple.com/documentation/corelocation/cllocationmanager/1423836-desiredaccuracy):

> The receiver does its best to achieve the requested accuracy; however, the actual accuracy is not guaranteed.

> When requesting high-accuracy location data, the initial event delivered by the location service may not have the accuracy you requested. The location service delivers the initial event as quickly as possible. It then continues to determine the location with the accuracy you requested and delivers additional events, as necessary, when that data is available.

**Comment by 1ec5** [comment]
Filtering based on `horizontalAccuracy` makes sense. I’m uncertain about `verticalAccuracy` simply because we don’t make use of the altitude anywhere, but if you think that’s a good indicator of a coarse sensor being used, then we could filter on that too.

**Comment by ericrwolfe** [comment]
`verticalAccuracy` isn't something we have to use in a first pass fix, but we should look into how best to use it.

From work I've done previously in GPS tracking, `verticalAccuracy` has been useful for knowing if a location came from GPS. There are often cases (such as a location coming from wifi triangulation) where the `horizontalAccuracy` is reasonable (<100m), but the `verticalAccuracy` is quite inaccurate. GPS generally has great `verticalAccuracy` (~3m).

From what I've seen, it's common for locations from coming from wifi triangulation to have `horizontalAccuracy=65` and `verticalAccuracy=10`.

**Comment by frederoni** [comment]
Negative speed has been a good indicator for an inaccurate location from previous experience, but it might filter out too much when moving at walking speed.
