### ISSUE TITLE
[Question]: is it possible to track traveled distance for a complete navigation session?

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4373]
I am building a custom "end of Route Feedback" view, which also shows some information about the route the user took. During a navigation session, the Route may change multiple times, which means that the traveled distance cannot be calculated using the original distance times the routeProgress percentage. 
I could try to calculate the traveled distance for the route each time the router will reroute and add everything up to get the final result, however, this feels like a bad solution. 

Is there a way to track a complete navigation Session? The user will always stay within one navigation View, but the route will change regularly. I feel like this should be possible since rerouting can happen anytime, even without trying to do so actively. If not, what would be the best way to calculate it on my own?

**Comment by osvaldoln** [comment]
I think with NavigationViewControllerDelegate you can obtain this data. 
`navigationViewController(_ navigationViewController: NavigationViewController, didUpdate progress: RouteProgress, with location: CLLocation, rawLocation: CLLocation)`
