### ISSUE TITLE
[Question]: Is there any way to show user current speed on navigation view.

### ISSUE THREAD

**Issue by arslanraza90** [mapbox/mapbox-navigation-ios#4378]
### Mapbox Navigation SDK version

2.9.1

### Steps to reproduce

.

### Expected behavior

<img width="924" alt="Screenshot 2023-02-22 at 2 50 58 PM" src="https://user-images.githubusercontent.com/106626080/220584537-fa2657a9-9718-46e7-be34-b4f0f8439765.png">

### Actual behavior

.

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by kried** [comment]
Hi @arslanraza90 

You can definitely use the custom speed limit and current speed view.
You can hide the standard speedLimitView by setting
`navigationViewController.navigationView.speedLimitView.isAlwaysHidden = true`

You can get the updated current speed value in `NavigationViewControllerDelegate.navigationViewController(_:,didUpdate:, with:, rawLocation:)`. Please take a look at a sample implementation in [CustomSpeedIndication.txt](https://github.com/mapbox/mapbox-navigation-ios/files/11264260/CustomSpeedIndication.txt)
