### ISSUE TITLE
Delay high alert level for unnamed road

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#439]
For unnamed roads, RouteController should delay raising the alert level to `high` until the user passes the preceding intersection.

If the upcoming step represents a road with no name, code, destination, or anything else, and the maneuver isn’t an on- or off-ramp maneuver, the road is likely to be a very minor road, such as a shared driveway, alley, or parking aisle. Currently, the low alert level can be issued far in advance of the maneuver, making it ambiguous as to which road should be used. For example, [this route](http://map.project-osrm.org/?z=17&center=37.338342%2C-121.863248&loc=37.340180%2C-121.863828&loc=37.336005%2C-121.864391&hl=en&alt=0) requires a right turn onto one unnamed shared driveway among several. The `high` alert level begins one or two driveways earlier, depending on the user’s speed. Upon hearing the resulting voice announcement, “Turn right”, the user is liable to turn onto the wrong driveway.

<img width="185" alt="2nd" src="https://user-images.githubusercontent.com/1231218/28703926-fdfeb396-731b-11e7-8a42-c4309895db33.png">

The proposed heuristic could logically be applied to named and unnamed roads alike, but it’s far more important for unnamed roads. Absent a road name or number – and absent the distance that the turn banner hides for the `high` alert level – the user must assume an immediate turn.

The catch is that there may not be enough time to read the entire announcement if the intersections are spaced too close together. As a failsafe, we should time the announcement to _end_ (rather than begin) at least one or two seconds before the user reaches the maneuver. (#427 which would also benefit from timing the end of the utterance.) We can accurately determine the time taken to read an announcement when it is synthesized by Amazon Polly.

/cc @mapbox/navigation-ios @daniel-j-h

**Comment by bsudekum** [comment]
Not actionable in this repo anymore.
