### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MapboxNavigation"

### ISSUE THREAD

**Issue by reaganscofield** [mapbox/mapbox-navigation-ios#4412]
### Mapbox Navigation SDK version

2.9

### Steps to reproduce

Followed the installation steps from https://docs.mapbox.com/ios/navigation/guides/get-started/install/ via CocoaPods

Pod  Version: 1.12.0

### Expected behavior

Successfully Installed 

### Actual behavior

```
[!] CocoaPods could not find compatible versions for pod "MapboxNavigation":
  In Podfile:
    MapboxNavigation (~> 2.9)

Specs satisfying the `MapboxNavigation (~> 2.9)` dependency were found, but they required a higher minimum deployment target.
```

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by azarovalex** [comment]
Hey @reaganscofield, release 2.9 definitely [exists on Cocoapods](https://github.com/CocoaPods/Specs/blob/114d58be9482d841a46f9181a516ff49bfff3e7c/Specs/5/8/b/MapboxNavigation/2.9.0/MapboxNavigation.podspec.json)

I would advise you to do `pod repo update` or use [Cocoapods CDN](https://blog.cocoapods.org/CocoaPods-1.8.0-beta/) in your Podfile.
