### ISSUE TITLE
FireBase + Mapbox-navigation-ios

### ISSUE THREAD

**Issue by davidasimov** [mapbox/mapbox-navigation-ios#442]
Hi! I would really appreciate your advise. For simple example lets talk about "Swift-Example" :)

I have installed FireBase to "Swift-Example", but I cant do the same for MapboxNavigation target. I need to save user location while navigation. I think my trouble is that there is no AppDelegate in MapboxNavigation target. I dont have enough skills to deal with it. Please help.

**Comment by frederoni** [comment]
MapboxNavigation is a [framework](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WhatAreFrameworks.html) that you embed in your application, Swift-Example in this case. There is no need to add Firebase to the MapboxNavigation framework. Read up on [CoreLocation](https://developer.apple.com/documentation/corelocation/cllocationmanager) to figure out how to retrieve a user location and [Firebase](https://firebase.google.com/docs/ios/setup) on how to store the location.

**Comment by davidasimov** [comment]
@frederoni Thanks for your answer. I know how to retrieve a user location and how to use FB, but I dont know how to do it while user use "Drop-in turn-by-turn navigation UI".

**Comment by frederoni** [comment]
In the case of Swift-Example, you could start recording in `ViewController.startButtonPressed(_:)` and stop recording in `navigationViewControllerDidCancelNavigation(_:)` and/or `navigationViewController(_:didArriveAt:)`.
