### ISSUE TITLE
[Bug]: Cocoapods installation error 401

### ISSUE THREAD

**Issue by itd-vladislav-k** [mapbox/mapbox-navigation-ios#4423]
### Mapbox Navigation SDK version

2.9.0

### Steps to reproduce

1. Have an account :)
2. Generate Private Token and apply needed options:
<img width="1156" alt="Screenshot 2023-04-07 at 17 27 51" src="https://user-images.githubusercontent.com/109576511/230625647-f8799aab-f909-494e-b1a3-be7337582393.png">

3. Setup .netrc file.

4. Setup podfile:

```
pod 'MapboxCoreNavigation', '~> 2.9.0'
pod 'MapboxNavigation', '~> 2.9.0'
```

5. Run `pod install`
6. See it fails

I'm pretty sure private token is setup correctly, because I have no issues installing these Mapbox dependencies:
```
pod 'MapboxMaps', '10.9.1'
pod 'MapboxSearch', ">= 1.0.0-beta", "< 2.0"
pod 'MapboxDirections', '~> 2.9'
```

Also I should mention that I had `MapboxNavigation` pod installed before with no issues. It started happening not so while ago when I tried to install new or update existing pods.

### Expected behavior

Mapbox Navigation module will install successfully

### Actual behavior

Installation fails with error:
```
Installing MapboxNavigationNative (119.0.6)

[!] Error installing MapboxNavigationNative
[!] /usr/bin/curl -f -L -o /var/folders/b9/q9dn656n0wq279293gmhmwzh0000gn/T/d20230407-46961-ep5h78/file.zip https://api.mapbox.com/downloads/v2/mobile-navigation-native/releases/ios/packages/119.0.6/MapboxNavigationNative.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.0 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   213    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401
```

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by azarovalex** [comment]
@itd-vladislav-k thanks for reporting the issue,
```
/usr/bin/curl -f -L -o ./file.zip https://api.mapbox.com/downloads/v2/mobile-navigation-native/releases/ios/packages/119.0.6/MapboxNavigationNative.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.0 cocoapods-downloader/1.6.3'
```
definitely works for me, could you please check your `~/.netrc` once again? 
It should look like this:
```
machine api.mapbox.com
login mapbox
password sk.eyJ....
```

Could you also try `curl`ing other versions of the framework like `130.0.0` or `110.0.0`?

**Comment by itd-vladislav-k** [comment]
Hi @azarovalex,

.netrc is definitely ok. I've managed to install everything using Swift Package Manager  without any problems by that day when this issue was reported. Also as I mentioned before, other Mapbox dependencies were successfully installed as well. 

I've tried again today with CocoaPods and issue seems to be resolved now.

Thanks
