### ISSUE TITLE
[Bug]: Build error when using Navigation SDK 2.13.0 and Maps 10.13.1

### ISSUE THREAD

**Issue by jcfrk101** [mapbox/mapbox-navigation-ios#4467]
### Mapbox Navigation SDK version

2.13.0

### Steps to reproduce
include Navigation SDK 2.13.0 and Core Maps 10.13.1 in your SPM dependencies, and try to build using github actions.

Sources/MapboxCoreNavigation/CoreNavigationNavigator.swift:486:7: type 'NavigatorRouteAlternativesObserver' does not conform to protocol 'RouteAlternativesObserver'

This is happening on both macOS 12 and macOS 13 with xCode 14.1,14.2,14.3

The issue is resolved using Navigation SDK 2.11.0 with Core Maps 10.13.1

### Expected behavior

The build should compile, in fact it did compile earlier today, but sometime about afternoon today, I encountered this error.

### Actual behavior

Build does not compile due to error in dependency 

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by azarovalex** [comment]
Hey @jcfrk101, we've released MapboxNavigationNative v132.4.0, which addresses the build issue.
You don't have to pin MapboxNavigationNative anymore as @kried suggested in the previous comment.

Make sure to update your dependencies using `File -> Packages -> Update to the Latest Package Versions` if you use SPM or run `pod update` with CocoaPods.
