### ISSUE TITLE
[Bug]: CarPlay - Interrupting the initial pan/zoom animation breaks all future touch based panning

### ISSUE THREAD

**Issue by MatthewFolbigg** [mapbox/mapbox-navigation-ios#4511]
### Mapbox Navigation SDK version

2.14.0

### Steps to reproduce

When connecting to CarPlay and launching the app, if the initial pan/zoom animation is interrupted by a touch based pan gesture. All future touch based pan gestures will move the map in incorrect directions at incorrect speeds.

I'm able to replicate it reliably in our app and other MapBox CarPlay apps such as [ROADS](https://www.mapbox.com/blog/the-worlds-most-epic-drives-now-on-carplay-with-roads-by-porsche)
I'm able to replicate in car and on the CarPlay Simulator.

- Start fresh (Force quit the iPhone App)
- Launch the app on CarPlay (Doesn't seem to matter if the main app is running first or not)
- Immediately interrupt the initial pan/zoom to user location with a touch based pan gesture. 
    - Gesture can be started any time before the initial pan/zoom is 100% complete
    
- The same state can be reached without force quitting. Instead it can be triggered on any connection to CarPlay. 
    - Start disconnected, connect to CarPlay, open app, interrupt the initial animation 
    - This is the more common scenario in real use

### Expected behavior

- The touch based pan gesture successfully interrupts the pan animation
- All future pan animations work as expected

### Actual behavior

- The touch based pan gesture successfully interrupts the pan animation
- Once the initial gesture ends, 
    - Any future gesture (During free drive or navigation) will now move in a seemingly random direction at a random speed
    - For example continuously swiping left then right will cause the map to continuously move downwards

- The issue persists until:
    - Triggering a re-center
    - Force quitting and starting again without interrupting the initial animation
    - Disconnecting and reconnecting to CarPlay without interrupting

As best as I can tell this initial animation is driven by starting free drive navigation via `startFreeDriveNavigation`. (Very new here so could be mistaken.)

Thanks for your help. Please let me know if there's any other info I can provide.

<img src="https://github.com/mapbox/mapbox-navigation-ios-examples/assets/75224610/fbe5804f-aeb8-42aa-a149-e6ec152227fa" height="200"> <img src=" " height="200">

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @MatthewFolbigg 
Thank you for the report. We were able to reproduce the issue. We will fix the issue in one of the next releases.

**Comment by MatthewFolbigg** [comment]
Thanks @kried
That's great news!
