### ISSUE TITLE
2.14Version of bad experience

### ISSUE THREAD

**Issue by ytx0574** [mapbox/mapbox-navigation-ios#4541]
1. When simulated navigation is used, the bearing and pitch of CameraOptions are abnormal, and the page does not slide and jumps frequently.
2. The memory usage exceeds 500 MB
3. Can adjust the token setting? My project requires users to register mapbox to provide services by themselves, which cannot be specified in info.plist
video: https://youtube.com/shorts/LdBYU2f5H6A

**Comment by kried** [comment]
Hi @ytx0574 

Thank you for reporting the issue. Could you please provide the sample project to reproduce the problems with the camera and memory usage? Some kind of memory leak might cause it.

Please elaborate on what you mean by adjusting the token settings. The token can be provided in the runtime by passing credentials to the [NavigationService initializer](https://github.com/mapbox/mapbox-navigation-ios/blob/f45acf52916a1c5011230fc1427a946e977e6ffe/Sources/MapboxCoreNavigation/NavigationService.swift#L497), [the Directions initializer](https://github.com/mapbox/mapbox-directions-swift/blob/fc7c5177216a272af536af8f434b80eb6c261f26/Sources/MapboxDirections/Directions.swift#L93)

**Comment by ytx0574** [comment]
相机的问题, 在视频中重现了. https://youtube.com/shorts/LdBYU2f5H6A

**Comment by ytx0574** [comment]
I want the token to be configured in code, not in info.plist. Our users need to register mapbox themselves

**Comment by ytx0574** [comment]
❌,❌,❌, When I start the simulated navigation, I repeat the same simulated navigation again when I finish, and after doing this many times, the following callback does not match the direction/name in the topbanner in the NavigationViewController.

> **func navigationViewController(_ navigationViewController: NavigationViewController, didUpdate progress: RouteProgress, with location: CLLocation, rawLocation: CLLocation)**

**Comment by ytx0574** [comment]
> Hi @ytx0574
> 
> Thank you for reporting the issue. Could you please provide the sample project to reproduce the problems with the camera and memory usage? Some kind of memory leak might cause it.
> 
> Please elaborate on what you mean by adjusting the token settings. The token can be provided in the runtime by passing credentials to the [NavigationService initializer](https://github.com/mapbox/mapbox-navigation-ios/blob/f45acf52916a1c5011230fc1427a946e977e6ffe/Sources/MapboxCoreNavigation/NavigationService.swift#L497), [the Directions initializer](https://github.com/mapbox/mapbox-directions-swift/blob/fc7c5177216a272af536af8f434b80eb6c261f26/Sources/MapboxDirections/Directions.swift#L93)


1. I want the token to be configured in code, not in info.plist. Our users need to register mapbox themselves
2. The problem of camera, reproduced in the video. https://youtube.com/shorts/LdBYU2f5H6A The video begins with it swinging from side to side, followed by the swing of the hammer

**Comment by kried** [comment]
> 1. I want the token to be configured in code, not in info.plist. Our users need to register mapbox themselves

Yes, there is a way to configure the token in the code. As I mentioned in my message above, you can pass the token to the [NavigationService initializer](https://github.com/mapbox/mapbox-navigation-ios/blob/f45acf52916a1c5011230fc1427a946e977e6ffe/Sources/MapboxCoreNavigation/NavigationService.swift#L497) and [the Directions initializer](https://github.com/mapbox/mapbox-directions-swift/blob/fc7c5177216a272af536af8f434b80eb6c261f26/Sources/MapboxDirections/Directions.swift#L93).
You'll also need to add a stub value to  the`Info.plist`, you can take a look [at the Info.plist in the example](https://github.com/mapbox/mapbox-navigation-ios/blob/83f89e0f0c5c5529e5138be341c6203c6b64d22d/Example/Info.plist#L26) and use the same stub value. This stub value won't be used if you configure `Directions` and `NavigationService` in the code.


The configuration code might look like this:
```swift
        let accessToken = "YOUR_TOKEN"
        let directions = Directions(credentials: .init(accessToken: accessToken))
        NavigationSettings.shared.initialize(with: .init(directions: directions))
        let routingProvider = MapboxRoutingProvider(settings: .shared)
....
        let navigationService = MapboxNavigationService(indexedRouteResponse: indexedRouteResponse,
                                                        credentials: .init(accessToken: accessToken))
```

**Comment by ytx0574** [comment]
> > 2. The problem of camera, reproduced in the video. https://youtube.com/shorts/LdBYU2f5H6A The video begins with it swinging from side to side, followed by the swing of the hammer
> 
> @ytx0574 Please share your code for starting and stopping the navigation or a sample project to reproduce the issue. We were not able to reproduce the problem. How do you stop the previous navigation before starting a new one? Are you sure you not storing the instances of `MapboxNavigationService` from the previous navigation session?

<img width="956" alt="image" src="https://github.com/mapbox/mapbox-navigation-ios/assets/12493700/0c7da1ae-425b-4fd2-bf45-86377fb26050">

I make sure that I do not have MapboxNavigationService, and I release the slef.navigationViewController directly after the navigation
