### ISSUE TITLE
[Bug]: 'navigationMapView' is inaccessible due to 'internal' protection level mapbox ios react native

### ISSUE THREAD

**Issue by satyamrathor16** [mapbox/mapbox-navigation-ios#4542]
### Mapbox Navigation SDK version

2.14.0

### Steps to reproduce

I am implementing the mapbox ios sdk for the react native and trying to implement the Transition from free-drive to turn-by-turn navigation and following the document but I am getting an error of "'navigationMapView' is inaccessible due to 'internal' protection level".
please check the below image url.
[https://drive.google.com/file/d/1bOTFGoNIq-2A6gpTumiuyMmyt1MFDMJN/view?usp=sharing](url)

### Expected behavior

The method should accessible from the other file.

### Actual behavior

The function is not able to access.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi

The property `navigationMapView` is defined as public in [NavigationView](https://github.com/mapbox/mapbox-navigation-ios/blob/f6d8bb3d18ec4f2e847474f804f5655e5cdddb23/Sources/MapboxNavigation/NavigationView.swift#L65). Please check if you copy the example correctly.
