### ISSUE TITLE
[Question]: Access Mapbox Telemetry total distance traveled in one session

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4565]
I want to display the total distance traveled using a navigation session to the user. Currently I do this by listening to the delegates and, each time a reroute is triggered, adding the route progress to any possible old route progress I had. The reason for this is that users often get reroutet on our navigation  sessions due to some features we provide. 
I am thinking that there must be a way to get access to the telemetry data, since mapbox is recording the total distance traveled in each session for billing purposes. How can I get access to that data?

**Comment by kried** [comment]
Hi @JanTG1

There is no API to access this data. It is collected for Telemetry, analytics purposes.

**Comment by JanTG1** [comment]
@kried Thanks for your reply! Would it be possible to make that data available? My implementation seems buggy at best and often fails to correctly add up all distances traveled, because users regularly get reroutet (often up to ten times per session). I don't see any reason why developers should not get access to that telemetry data, it would be way easier, safer and would avoid doing things twice.
