### ISSUE TITLE
[Bug]: Cocoapods install failed - The target has transitive dependencies

### ISSUE THREAD

**Issue by mumensh** [mapbox/mapbox-navigation-ios#4568]
### Mapbox Navigation SDK version

2.17

### Steps to reproduce

Upgrade mapbox navigation from '~> 2.10' to '~> 2.17' will result in Cocoapods error

### Expected behavior

`pod install` should work just fine

### Actual behavior

It gives the following error when executing `pod install`:

[!] The 'Pods-AppName-iOS' target has transitive dependencies that include statically linked binaries: (/projectPath/AppName/Pods/MapboxCommon/MapboxCommon.xcframework and /projectPath/AppName/Pods/MapboxCoreMaps/MapboxCoreMaps.xcframework)

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @mumensh 

We tested our `PodInstall` example with `MapboxNavigation (2.17.0)`, `MapboxMaps (10.16.3)`, `MapboxCommon (23.8.5)` with CocoaPods 2.12.1 and 1.14.3. We saw no problems.

Please tell us which version of Cocoapods you are using. Could you please also share a small sample to reproduce the issue with us?

**Comment by mumensh** [comment]
@kried after updating cocoapods to latest stable version, it worked fine.

Thank you
