### ISSUE TITLE
[Bug]: Swift Package Manager - incompatible with Maps 11.0.0

### ISSUE THREAD

**Issue by denhams** [mapbox/mapbox-navigation-ios#4570]
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

In Xcode, update or add the Mapbox Maps Package version 11.0.0.

### Expected behavior

Mapbox Maps 11.0.0 and Mapbox Navigation packages 2.17.0 should be installed.

### Actual behavior

Failed to resolve dependencies Dependencies could not be resolved because root depends on 'mapbox-navigation-ios' 2.17.0.
'mapbox-navigation-ios' 2.17.0 cannot be used because 'mapbox-navigation-ios' 2.17.0 depends on 'mapbox-maps-ios' 10.16.1..<11.0.0 and root depends on 'mapbox-maps-ios' 11.0.0.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Nav SDK v2.17 does not support Maps SDK v11. You can use the Nav SDK v2.17 together with Maps SDK [v10.16.3](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.16.3).

We plan to add support for the v11 Maps SDK to the new version of the Navigation SDK. We will provide detailed information about this update soon.

**Comment by talal-tilted** [comment]
Hello @kried Do you have an estimated live timeline ?

**Comment by denhams** [comment]
@kried , any update? Your original response said "We will provide detailed information about this update soon." It's now 4 months later.

**Comment by kried** [comment]
Hi
You can try to migrate to the [v3.0.1](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v3.0.1) Nav SDK to adopt the Maps SDK v11.

**Comment by denhams** [comment]
Thanks, that seems to work okay.
