### ISSUE TITLE
[Bug]: while rerouting the annotation stop until reroute finish

### ISSUE THREAD

**Issue by sunhongjihaha** [mapbox/mapbox-navigation-ios#4571]
### Mapbox Navigation SDK version

2.13.0

### Steps to reproduce

When using navigation, the annotation stops for a period of time and does not continue tracking until the rerouting is successful. Is there any way to track your current position while reroute 
![截屏2023-12-07 18 52 13](https://github.com/mapbox/mapbox-navigation-ios/assets/16420834/d398b7e8-828e-4f03-b5f9-73fe89d824f9)

### Expected behavior

annotation tracking the location while reroute

### Actual behavior

it stop until reroute finish

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @sunhongjihaha 

Thank you for the report.
The Nav SDK allows to track the current user position on the map.  The new route line cannot be drawn until it's requested by SDK. 

The delay before the reroute is finished should be that large. Are you using default reroute logic? 
Do you test simulation mode to test reroute? Then faster simulation may result in more visible delays.
