### ISSUE TITLE
[Bug]: change localized to Chinese, all the naivgationView's text have changed except unit text

### ISSUE THREAD

**Issue by sunhongjihaha** [mapbox/mapbox-navigation-ios#4581]
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

1.change routeOptions.locale to chinese.
2.navigationView's text have changed but except unit text, it always display previous language.
3.I used InstructionsBannerView as top banner, the distanceLabel used distanceFormatter's locale, but this value just set  once at naivigationView first lanuch,when I changed language, back to navigationView, it also use first value, it did't update,so I try to set new value to distanceFormatter's locale, but distanceFormatter is internal. so can you change distanceFormatter authority from internal to open or public?
or other ways to update distanceFormatter locale.
thank you so much

### Expected behavior

unit text change to 米

### Actual behavior

unti text still mi

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @sunhongjihaha

 [DistanceFormatter](https://docs.mapbox.com/ios/navigation/api/2.17.0/Classes/DistanceFormatter.html#/s:20MapboxCoreNavigation17DistanceFormatterC6locale10Foundation6LocaleVvp) uses the [nationalizedCurrent](https://docs.mapbox.com/ios/navigation/api/2.17.0/Extensions/Locale.html#/s:10Foundation6LocaleV20MapboxCoreNavigationE19nationalizedCurrentACvpZ) locale. So it uses the preferred language on the device. You can add Chinese localization to your app to support Chinese distance units. 

<img width="375" alt="Screenshot 2024-02-08 at 19 18 16" src="https://github.com/mapbox/mapbox-navigation-ios/assets/3630656/e78d8dc1-0295-4786-83ee-63f1c776d107">

You can also use a custom view navigation controller with any type of top banner. You can find the code example [here](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Example/CustomViewController.swift).
