### ISSUE TITLE
EXC_BAD_ACCESS memory issue in Router

### ISSUE THREAD

**Issue by faliinitse** [mapbox/mapbox-navigation-ios#4590]
Mapbox is giving an EXC_BAD_ACCESS error in the Router Class. This issue is strange and difficult to debug. Let me explain a little about our app. We have an app with blocks, each containing many trips. The app is working fine for all the blocks and their trips. However, for just one block and its trip, the app is crashing when rerouting occurs. We don't know why it's crashing only for that particular trip of a block, and only in the case of rerouting. I am attaching a screenshot; perhaps you can guide us on how to track this bug. I even checked the route data by converting it into plain json string; there is not much change when it first loads and when the reroute occurs. Even all the properties routeData,routeRequest and responseOrigin have data but as soon as it reach the line 75 it gives this error. So, I am confused about what the exact issue is. Just for your information, we are loading a custom route and not using Mapbox Direction API for loading routes. Routes are coming from our own server. 

<img width="1067" alt="Screenshot 2024-01-19 at 16 16 06" src="https://github.com/mapbox/mapbox-maps-ios/assets/57752873/297511a3-ffb9-40f0-8544-af16416f1f62">

**Comment by faliinitse** [comment]
> Could you share a full log that includes the error?

Here is the log file of crash

[logFile.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14038787/logFile.txt)

**Comment by faliinitse** [comment]
Hi, @baleboy , do you need anything else regarding this issue to be solved? We are stuck for our next release, and this issue is a major roadblock for us. Could you please help me in this case?

**Comment by kried** [comment]
Hi @faliinitse 
Could you please share the SDK version you are using?
Is the problem reproducing consistently during the reroute?

Would it be possible to share the route response that cause the crash?

**Comment by faliinitse** [comment]
Hi @kried 

Following is the screenshot of my podfile.lock

<img width="327" alt="Screenshot 2024-02-13 at 09 14 13" src="https://github.com/mapbox/mapbox-navigation-ios/assets/57752873/6cdf27fa-0c27-4b8c-82eb-5f708b5e2152">

Here is the `routeResponse` output as `p routeResponse` and `po routeResponse` for the initial load when no crash has occurred, and after rerouting when the actual crash is occurring.

First load when no crash occurred
[poResponseFirstLoad.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257970/poResponseFirstLoad.txt)
[pResponseFirstLoad.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257971/pResponseFirstLoad.txt)

After rerouting when crash occurred.

[poResponseAfterRerouting.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257976/poResponseAfterRerouting.txt)
[PResponseAfterRerouting.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257977/PResponseAfterRerouting.txt)

I also converted the `routeData` to plain JSON string; it may also help in identifying the crash.

[routeDataJsonAfterRerouting.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257987/routeDataJsonAfterRerouting.txt)
[routeDataJsonFirstLoad.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257988/routeDataJsonFirstLoad.txt)

**Comment by faliinitse** [comment]
> Is the problem reproducing consistently during the reroute?

Yes, it always crashes when rerouting occurs for one of our trips. For all other trips, it works fine. However, it only crashes during rerouting for this particular trip. I've shared the JSON data and `routeResponse`. I hope it will help to find the bug.

**Comment by faliinitse** [comment]
Hi @kried,

Any update on this issue? Our new release is stalled because of this problem. Could you please provide an update if you've found anything based on the data I provided? I would highly appreciate it if you could respond to my comment.

**Comment by kried** [comment]
Hi @faliinitse

Thank you for the recorded data, we were able to reproduce the problem. We will fix the crash in upcoming SDK releases.

But the response [routeDataJsonAfterRerouting.txt](https://github.com/mapbox/mapbox-navigation-ios/files/14257987/routeDataJsonAfterRerouting.txt) seems to be incorrect. It contains the 11 waypoints, but only 9 legs instead of 10. The SDK definitely should not crash in such cases, but the waypoints list should be decreased in the response.
After looking at the legs in the response, it seems like the last waypoint is redundant.
 
So the [response.json](https://github.com/mapbox/mapbox-navigation-ios/files/14858604/response.json) with the removed last waypoint does not cause the crash.

Could you please answer if you received this response from Directions API or did you use the custom routing provider? Or did you manually change some properties in the response?

**Comment by kried** [comment]
@faliinitse 
This exact crash won't happen on Android, but please validate the response to the [Directions API](https://docs.mapbox.com/api/navigation/directions/) response scheme to avoid incorrect response parsing.

E.g. the response does not contain the required field `name` for the [Waypoint](https://docs.mapbox.com/api/navigation/directions/#waypoint-object) object in the response and there is no `code` at the [top level of the response.](https://docs.mapbox.com/api/navigation/directions/#response-retrieve-directions)

**Comment by faliinitse** [comment]
Hi Kried, could you please let us know if the following crash has been fixed in any new version that has been released?

**Comment by kried** [comment]
Hi @faliinitse 

The fix should be available in [v2.18.0](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.18.0) with NavigationNative v204.0.1
