### ISSUE TITLE
[Bug]: Cannot install the SDK alongside Mapbox Maps v11

### ISSUE THREAD

**Issue by fawzirifai** [mapbox/mapbox-navigation-ios#4604]
### Mapbox Navigation SDK version

v2.18.0-rc.2

### Steps to reproduce

Cannot install the SDK alongside Mapbox Maps v11

### Expected behavior

We should able to use Mapbox Navigation SDK alongside Mapbox Maps v11

### Actual behavior

Cannot install the SDK alongside Mapbox Maps v11

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hi @fawzirifai. 2.18 is not supposed to support Maps v11. This will be added later. Stay tuned for the updates

**Comment by fawzirifai** [comment]
What do you mean by later? 1 month? 6 months? 1 year? @Udumft
