### ISSUE TITLE
CarPlay instruction panel border

### ISSUE THREAD

**Issue by William-Coates** [mapbox/mapbox-navigation-ios#4612]
The instruction panel would benefit from a border. Currently, It blends with the map's background and may hide roads/roundabouts/junctions.

![SCR-20240313-kjlb](https://github.com/mapbox/mapbox-navigation-ios/assets/149601233/d27dc3cf-8b9e-45a9-805d-521aa0797626)

**Comment by azarovalex** [comment]
Hey @William-Coates, thanks for reporting this issue, however I think in this case we are limited by the API Apple gives us.
CarPlay UI is different from usual UIKit hierarchy and based on templates, in case of the guidance banner, the only thing we can change in the background color: https://developer.apple.com/documentation/carplay/cpmaptemplate.

My suggestion would be to use a slightly different map style, where background is not a plane white color.

![Main-VideoStream-2024-04-03-07-57-10](https://github.com/mapbox/mapbox-navigation-ios/assets/1976216/2eed3896-cbbe-4d17-9f20-b48ba0cc9f35)

Submitting a radar might help attract Apple's attention to this issue and hopefully they'll support more customization in future iOS versions.
Feel free to reopen the issue if you find a workaround that we can use in the SDK.
