### ISSUE TITLE
[Bug]: Unable to adjust position of ResumeButton 

### ISSUE THREAD

**Issue by mBaldasty** [mapbox/mapbox-navigation-ios#4638]
### Mapbox Navigation SDK version

2.18.0

### Steps to reproduce

Not really a bug but is it possible to move the position of the ResumeButton?
I hid the BottomBannerView and the waynamelabel and want to move towards the bottom and center.

But I cant really access the ResumeButton on the mapView or navigationMapView.

### Expected behavior

Some way to adjust position of resume button.

### Actual behavior

Not able to access resume button positioning.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hello, @mBaldasty! Indeed, there is no designed way to adjust `ResumeButton` or similar components positions, but you could try to manually iterate over `NavigationView`'s children and modify it's layout.
```
let resumeButton = navigationView.subviews.first { subview in
    subview is ResumeButton
}
// Modify resumeButton's layout constraints.
```

**Comment by mBaldasty** [comment]
resolved, thank you
