### ISSUE TITLE
[Bug]: TopBannerView not adjusting brightness according to device brightness

### ISSUE THREAD

**Issue by mBaldasty** [mapbox/mapbox-navigation-ios#4640]
### Mapbox Navigation SDK version

2.18.0

### Steps to reproduce

Dont know if it is a bug or I am missing sth.
I have the navigationView embedded into another view.
While the expanded maneuvers "darken" or "brighten" according to the device brightness (when changed, as well as the rest of my app) the TopBannerView alway remains way brighter.
The view it is embedded in is white and the TopBannerView always looks way more brighter unless I put the device brightness to 100% as well.

### Expected behavior

Adjust TopBannerView background color brightness according to device brightness

### Actual behavior

TopBannerView remains way brighter

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hi! There is no brightness adjustments in views, but there is a dark/light theme switching that may be triggered by different events. Do you mean that one of the views did not switch the theme? If so, could you please provide a screenshot and some reproduction steps.
If this is exactly the screen brightness you are referring to, the screenshot won't help, so the only way to show this is to record your device's screen with another camera...

**Comment by mBaldasty** [comment]
@Udumft you were right. I using .night as style solved it for me. Thank you
