### ISSUE TITLE
[Bug]: Incompatible with mapbox-search-ios v2

### ISSUE THREAD

**Issue by jvanderwee** [mapbox/mapbox-navigation-ios#4643]
### Mapbox Navigation SDK version

3.0.2

### Steps to reproduce

Install latest versions of mapbox-search-ios and mapbox-navigation-ios using SPM

### Expected behavior

Package resolution succeeds

### Actual behavior

Package resolution fails:
> 'search-ios' is incompatible with 'mapbox-navigation-ios' because 'search-ios' 2.0.1 depends on 'mapbox-common-ios' 24.4.0-beta.2..<25.0.0 and 'mapbox-navigation-ios' 3.0.2 depends on 'mapbox-common-ios' 24.3.1.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @jvanderwee 

The Search SDK 2.0.1 depends on the pre-release [Common SDK version 24.4.0-beta.2](https://github.com/mapbox/mapbox-search-ios/blob/55c1ab48d88da77c706783f65cfe43bd65c5d526/Package.swift#L9). This version is too new for the Navigation SDK. From what I see, at the moment only Search SDK 2.0.0-rc.3 can be used together with Nav SDK v3.

Our next pre-release Nav SDK iOS 3.1.0-rc.1 will use the updated pre-release of the Common SDK.

**Comment by kried** [comment]
Hi @jvanderwee 
Please use the latest [Search SDK v2.0.3](https://github.com/mapbox/mapbox-search-ios/releases/tag/v2.0.3) which is compatible with Nav SDK v3.0.2.
