### ISSUE TITLE
[Bug]: mapbox-navigation-ios v3 is incompatible with mapbox-maps-ios v11+

### ISSUE THREAD

**Issue by lpeancovschi** [mapbox/mapbox-navigation-ios#4663]
### Mapbox Navigation SDK version

3+

### Steps to reproduce

1. Create a new iOS project
2. Using SPM add mapbox-maps-ios v11 (up to next major version)
3. Using SPM add mapbox-navigation-ios v3 (up to next major version)

### Expected behavior

Both libraries should be aded without error and the project should compile

### Actual behavior

When trying to add mapbox-navigation-ios library I'm getting an error saying that mapbox-navigation-ios depends on mapbox-maps-ios 10.17.0..<11.0

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by amzada** [comment]
Related issue: https://github.com/mapbox/mapbox-maps-ios/issues/2188#issuecomment-2127300086
