### ISSUE TITLE
Update Transifex with v3 .strings file URLs

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#4671]
558979144f0cf77e6b1c7e2e2fed1cfd24d25b11 renamed Sources/MapboxCoreNavigation/ to Sources/MapboxNavigationCore/ and Sources/MapboxNavigation/ to Sources/MapboxNavigationUIKit/. This caused the Transifex configuration to get out of sync. You’ll need to update the Transifex project’s autoupdating settings to point to the files’  new URLs, or autoupdating will stop.

/cc @azarovalex

**Comment by azarovalex** [comment]
Thanks for the heads up Minh, my email also got spammed by Transifex. We don't use it these days and I think the autoupdate feature is now disabled, I also removed you from maintainters so you won't be disturbed by Transifex issues in the future.

**Comment by 1ec5** [comment]
Thank you! I [removed Mapbox](https://wiki.openstreetmap.org/wiki/Special:Diff/2719101) from the list of translatable software on the OSM Wiki so that prospective translators won’t contribute translations and get frustrated that they aren’t appearing in releases. Feel free to restore Mapbox to the list if you have a new preferred place to accept translations (even if it’s just a GitHub ticket).
