### ISSUE TITLE
[Bug]: NavigationMatchOptions(waypoints: , profileIdentifier: ) fails to map match when waypoints have separateLegs = false

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#4676]
### Mapbox Navigation SDK version

3.1.1

### Steps to reproduce

1. get list of longitudes and latitudes 
2. loop trough them, generate waypoints out of them and set (some of) them to w.separateLegs = false
```
let coordinates = leg.routeSteps.map { CLLocationCoordinate2D(latitude: $0.waypoint.lat, longitude: $0.waypoint.lng) }
        var waypoints: [MapboxDirections.Waypoint] = []
        for (i, c) in coordinates.enumerated() {
            var w = Waypoint(location: CLLocation(latitude: c.latitude, longitude: c.longitude))
            //Only set false on all middle waypoints (to avoid showing waypoint markers on them)
            if i == 0 || i == waypoints.count - 1 {
                w.separatesLegs = true
            }else{
                w.separatesLegs = false
            }
            waypoints.append(w)
        }
```
3. use those waypoints as NavigationMatchOptions waypoints: 
```
let matchOptions = NavigationMatchOptions(waypoints: waypoints, profileIdentifier: .automobileAvoidingTraffic)
```
4. calculate Route with that using Map Matching
```
        Task {
            do{
                let routeResponse = await self.myNavigationProvider.routingProvider().calculateRoutes(options: matchOptions).result
                
                switch routeResponse {
                case .failure(let error): LogManager.logToFile("Error calculating map matched route: \(error)")
                    //Calculation not successful
                    //TODO: HANDLE!
                case .success(let response):
                    myRoute = try routeResponse.get().mainRoute.route
                    self.bookingMapView.showcase(response)
                }
            }catch {
                LogManager.logToFile("Error occured while requesting map matched routes: \(error.localizedDescription)")
            }
        }
```

### Expected behavior

- The route should get calculated correctly and displayed on the map thanks to `showcase`
- Only the first and last waypoints should be displayed as such, the rest should be driven trough but not have a marker on them
- The Route should get calculated the same, no matter the separateLegs variable of the waypoints

### Actual behavior

- The route calculation fails and runs into the .failure case as soon as some waypoints have separateLegs = false set
- The route calculation works if all waypoints are set to (default) separateLegs = true
- The route then gets displayed correctly, but showing hundreds of annotations where I don't want any to be shown

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by YoussefHenna** [comment]
Can confirm this is an issue. Consistently reproducible.

**Comment by kried** [comment]
Hi @JanTG1  and @YoussefHenna 

Thank you for the report. We were able to reproduce the issue, it is caused by the Map Matching response parsing in the case of silent waypoints. 
We will work on a fix to release it faster.

**Comment by JanTG1** [comment]
@kried Thank you for letting me know and fixing the issue so quickly! I will test this as soon as 3.3.0-beta.1 is compatible with a mapboxSearch version and will re-open if the issue re-appears.
