### ISSUE TITLE
Show subsequent step under turn banner

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#469]
When the next two maneuvers are sufficiently close together, we should display a mini banner beneath the turn banner for the second maneuver. The mini banner would parallel the “linked” voice instructions that the SDK already provides, but we could display it for slightly less closely spaced maneuvers as well.

/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
Would it be appropriate to put `Then turn left` into the `statusView`?

**Comment by ericrwolfe** [comment]
> Would it be appropriate to put Then turn left into the statusView? Or would this be it's own UI element.

This wouldn't be visible enough and would conflate the purpose of the status view, to alert the user of something that's out of the ordinary.

@mayagao could work on some mockups of what this could look like next week.

**Comment by Sealos** [comment]
Hello, any updates on this feature 😃 ?
