### ISSUE TITLE
[Bug]: Building project invalid archive returned

### ISSUE THREAD

**Issue by nnhubbard** [mapbox/mapbox-navigation-ios#4693]
### Mapbox Navigation SDK version

3.1.0

### Steps to reproduce

Checkout this project and follow the instructions. Build in Xcode and get the errors: 

![Screenshot 2024-07-16 at 6 28 15 PM](https://github.com/user-attachments/assets/b8d117c1-ecb6-404e-a049-5fb2952894bd)

![Screenshot 2024-07-16 at 5 33 56 PM](https://github.com/user-attachments/assets/29016509-26f5-4bee-b6c1-bbaccc97643c)

### Expected behavior

The project should build so that I can view the examples.

### Actual behavior

Build errors

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi 

Please try the latest v3.2.0 version. This version is open-source, so it downloads fewer binary dependencies.

Please make sure you [configure your secret token](https://docs.mapbox.com/ios/navigation/guides/get-started/install/#step-3-configure-your-secret-token) to access the binary dependencies.
Please try to clean up DerivedData and SPM cache  (possibly `~/Library/Caches/org.swift.swiftpm`,  `~/Library/org.swift.swiftpm`). 

If all above did not help, please provide us with your Xcode version.

**Comment by nnhubbard** [comment]
Still didn't work. I continue to get a `Package Resolution Failed` message when adding the package:

![Screenshot 2024-07-17 at 9 47 29 AM](https://github.com/user-attachments/assets/0a026c20-5a9d-4fc4-aedb-ebffa8e7f15e)

**Comment by cufapaez** [comment]
Same here. Only have MapboxMaps - Exact @ 11.5.1 and MapboxDirections - Up To Next Major @ 2.14.0.
![Screenshot 2024-07-17 at 7 07 44 PM](https://github.com/user-attachments/assets/21f91301-2b8b-4e31-bb60-a70a0c91cfcb)
Xcode 15.4

**Comment by kried** [comment]
Hi @cufapaez 

> Same here. Only have MapboxMaps - Exact @ 11.5.1 and MapboxDirections - Up To Next Major @ 2.14.0.

The error on your screenshot is completely different. It says about "multiple targets named `MapboxDirections`. You need to remove dependency on MapboxDirections v2.14.0 from [mapbox-directions-swift](https://github.com/mapbox/mapbox-directions-swift). The MapboxNavigation v3.2.0 already contains the `MapboxDirections` [package inside](https://github.com/mapbox/mapbox-navigation-ios/blob/157e08c0d21efcbdedb1220956b65a557bb0e86f/Package.swift#L54). 
<img width="949" alt="Screenshot 2024-07-18 at 10 24 33" src="https://github.com/user-attachments/assets/839aa2ce-bc33-4c46-8d82-cddd0a059e55">

Please follow [our installation guide](https://docs.mapbox.com/ios/navigation/guides/get-started/install/#part-2-add-the-dependency) to specify dependencies.

**Comment by kried** [comment]
Hi @nnhubbard 

Please try to install the latest v3.2.0 after you cleaned the SPM cache.
Make sure [you configure](https://docs.mapbox.com/ios/navigation/guides/get-started/install/#step-3-configure-your-secret-token) `.netrc` token.

Your problem seems to be similar to mapbox/mapbox-maps-ios#2206 or mapbox/mapbox-maps-ios#2156
This comment should be helpful https://github.com/mapbox/mapbox-maps-ios/issues/2156#issuecomment-2036414347.

**Comment by nnhubbard** [comment]
> Hi @nnhubbard
> 
> Please try to install the latest v3.2.0 after you cleaned the SPM cache. Make sure [you configure](https://docs.mapbox.com/ios/navigation/guides/get-started/install/#step-3-configure-your-secret-token) `.netrc` token.
> 
> Your problem seems to be similar to [mapbox/mapbox-maps-ios#2206](https://github.com/mapbox/mapbox-maps-ios/issues/2206) or [mapbox/mapbox-maps-ios#2156](https://github.com/mapbox/mapbox-maps-ios/issues/2156) This comment should be helpful [mapbox/mapbox-maps-ios#2156 (comment)](https://github.com/mapbox/mapbox-maps-ios/issues/2156#issuecomment-2036414347).

That worked. Thank you!
