### ISSUE TITLE
[Bug]: Turn right guidance icon error

### ISSUE THREAD

**Issue by santoso8118** [mapbox/mapbox-navigation-ios#4697]
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

User is in navigation and should be at location 1.3408074438903008, 103.97175462635322

![navigation](https://github.com/user-attachments/assets/d40abd71-2160-4854-b20a-c29b8a87447e)
![googlemaps_streetview](https://github.com/user-attachments/assets/9662791b-75e0-457f-8c66-05a85b5fd08d)

### Expected behavior

1> The straight road arrows should light up instead of the turn arrows
2> The right turn arrows are should be pointing to left and should not light up

### Actual behavior

1> The straight road arrows are grey out
2> The turn arrows light up and pointing to the right

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by santoso8118** [comment]
We got another issue when user in navigation the directions arrow not lit up
Please see attached photo below to see. Both 2 arrows turn left in the red rectangle should be light up.

![lane-arrow-error](https://github.com/user-attachments/assets/a8472e33-4317-4e51-9fa2-8f769e65ee6e)
![image-20240731-001156](https://github.com/user-attachments/assets/f0e70f91-3288-4016-86d8-3a2a947ba5ff)

This is very serious issue to our app its showing dangerous instructions to user while driving.
Please help to fix the issue.

Looking forward to Mapbox team's feedback on this.

**Comment by kried** [comment]
Hi @santoso8118

Thank you for the report.

Could you please try to retest the navigation in described locations, possibly with v2.18.x?
<img src="https://github.com/user-attachments/assets/181c636b-3146-461a-8fa0-1020c6c997f7" width="350" /><img src="https://github.com/user-attachments/assets/efca04f1-1d50-41e5-bfaf-69fd2240f2fa" width="350" />

I will check the lane guidance for the second location, where only the one lane is highlighted

**Comment by santoso8118** [comment]
Hi @kried 
Thank you for your feedbacks.
I will retest the navigation with mapbox sdk 2.18.x

**Comment by kried** [comment]
> I will check the lane guidance for the second location, where only the one lane is highlighted
The data issue was fixed.
