### ISSUE TITLE
[Bug]: Missing XCFrameworks in v3.2.0 

### ISSUE THREAD

**Issue by emilianoalvarez91** [mapbox/mapbox-navigation-ios#4703]
### Mapbox Navigation SDK version

v3.2.0

### Steps to reproduce

Fetch the mapbox-navigation-ios package pointing to version 3.2.0.

From version 3.1.1 the navigation SDK could be added as xcframeworks, however since 3.2.0 MapboxNavigationCore and MapboxNavigationUIKit and their dependencies are not exposed as binaries.

My Project uses frameworks for modularization and if I add mapbox-navigation-ios as a swift package inside my framework and then add it to my app target the app fails to compile due to duplicated symbols. Therefore, I would require the dependencies as xcframeworks to manually add them.

### Expected behavior

All artificts should be retrieved:
_MapboxNavigationUXPrivate.xcframework;
MapboxCoreMaps.xcframework;
MapboxDirections.xcframework;
MapboxMaps.xcframework;
MapboxNavigationCore.xcframework;
MapboxNavigationUIKit.xcframework;
Turf.xcframework;
MapboxNavigationNative.xcframework;
MapboxCommon.xcframework.

### Actual behavior

Only these are retrieved as XCFrameworks:
MapboxCoreMaps.xcframework;
MapboxNavigationNative.xcframework;
MapboxCommon.xcframework.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @emilianoalvarez91 

Thank you for the report.

The Nav SDK iOS is intended to be distributed as open source. We intentionally switched to the source code distribution for the Swift SDKs, as we did for the v2 SDK.

You can create local frameworks for the distributed libraries using the standard `xcodebuild -create-xcframework` command or by using some third party tools, like [Scipio](https://github.com/giginet/Scipio).

**Comment by emilianoalvarez91** [comment]
Hi @kried, have you tried building the XCFrameworks on 3.2.0?

When using Scipio I'm getting the following error:
![Screenshot 2024-08-02 at 01 09 23](https://github.com/user-attachments/assets/0fa18a5f-a3b2-4621-8bd7-151ec8dabbb1)

Which is exactly the same issue that I get when I'm trying to embed the framework when using SMP

![image](https://github.com/user-attachments/assets/92ea10a7-e54b-434e-94e8-085bcbc20dd6)
![image](https://github.com/user-attachments/assets/dabab647-310e-4796-a2c9-415fc4ca0503)
![image](https://github.com/user-attachments/assets/9dcf70b9-b3c0-4ef1-b77d-ece98048600c)
![image](https://github.com/user-attachments/assets/54a0345b-7b7a-47ee-9713-98e0a9eaba75)

**Comment by fbeccaceci** [comment]
> Hi @kried, have you tried building the XCFrameworks on 3.2.0?
> 
> When using Scipio I'm getting the following error: ![Screenshot 2024-08-02 at 01 09 23](https://private-user-images.githubusercontent.com/17701694/354411809-0fa18a5f-a3b2-4621-8bd7-151ec8dabbb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTAzNjksIm5iZiI6MTcyMzM5MDA2OSwicGF0aCI6Ii8xNzcwMTY5NC8zNTQ0MTE4MDktMGZhMThhNWYtYTNiMi00NjIxLThiZDctMTUxZWM4ZGFiYmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YWUzYjc4Y2NiNmE4NThiMDg1ODI5OTQ5OWM4YjczMDAyNzJlOGNhNDhjNjhiOTk4MmY5NDU1NzIyOThkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXAcwV1vs0GFFwagE7KJ8ksRTKmbzK5J0-Mbj2yPdRk)
> 
> Which is exactly the same issue that I get when I'm trying to embed the framework when using SMP
> 
> ![image](https://private-user-images.githubusercontent.com/17701694/354412437-92ea10a7-e54b-434e-94e8-085bcbc20dd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTAzNjksIm5iZiI6MTcyMzM5MDA2OSwicGF0aCI6Ii8xNzcwMTY5NC8zNTQ0MTI0MzctOTJlYTEwYTctZTU0Yi00MzRlLTk0ZTgtMDg1YmNiYzIwZGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNmY1ZDNkN2U2NWQ4ZTgyYmQyODdmODUzYTY5OGExYmYxZTAxMDczMTM2M2NhMDUzYzI2MWFiZTZkY2QzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.alYh48dbFkrm8O0NpsfiEWGgR_CvIXOtT8f3nqaRrlw) ![image](https://private-user-images.githubusercontent.com/17701694/354412461-dabab647-310e-4796-a2c9-415fc4ca0503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTAzNjksIm5iZiI6MTcyMzM5MDA2OSwicGF0aCI6Ii8xNzcwMTY5NC8zNTQ0MTI0NjEtZGFiYWI2NDctMzEwZS00Nzk2LWEyYzktNDE1ZmM0Y2EwNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMDBkMWI3NGZkZDBkMmIyOGM4MDM3MjIyMzdkMzA5YTA1OWEyMDY4MDg2Yjg0MTMxYWM3NjhiZWRkZjEyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iZEbza1NOLEJqbmOMGuArk4EMzpOsEdVHBFmJcmAL5E) ![image](https://private-user-images.githubusercontent.com/17701694/354412485-9dcf70b9-b3c0-4ef1-b77d-ece98048600c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTAzNjksIm5iZiI6MTcyMzM5MDA2OSwicGF0aCI6Ii8xNzcwMTY5NC8zNTQ0MTI0ODUtOWRjZjcwYjktYjNjMC00ZWYxLWI3N2QtZWNlOTgwNDg2MDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Y2IwMWZmM2JlZjQxYzNmZTMzZTgxOGQ3MTAxODJmMWI3ZmE3MWYzNjQwMmY1MGM0NWRjOWE2NTg4N2NlZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QTVXFPoUYxyeLIqy6TTvXr7w7A8spekglrsMptLrvRM) ![image](https://private-user-images.githubusercontent.com/17701694/354412578-54a0345b-7b7a-47ee-9713-98e0a9eaba75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTAzNjksIm5iZiI6MTcyMzM5MDA2OSwicGF0aCI6Ii8xNzcwMTY5NC8zNTQ0MTI1NzgtNTRhMDM0NWItN2I3YS00N2VlLTk3MTMtOThlMGE5ZWFiYTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NDI2YjVhYWZlODg3ZTFjM2EzNDY0OTBkZTI5YTU5MWFkYWFmMWIxYWVmYTFhNzZlNmM2NWI2MGQ0YTNkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uzISEyVw5o30IzCNyTpQ7mW088zIO-g7aEPv8e8e5M)

I'm having the same problem, did you find a solution?

**Comment by emilianoalvarez91** [comment]
Not yet, I'm still waiting for a solution on this

**Comment by emilianoalvarez91** [comment]
Hi, @kried @chizhavko @volkdmitri the new framework distribution is not allowing to upgrade to the newest framework. I've tried the solution proposed by @kried but that's not working as there is something wrong in how MapboxNavigationCore is created.

Not being able to migrate to v3.2.0 is a serious issue as v3.1.1 doesn't allow you to use dynamic access tokens and forcing the only option to expose the access token in the info.plist.

I'm trying to upgrade since July 1st and still I'm unable to do so. What are the options to migrate to the newest versions of the framework?

**Comment by kried** [comment]
Hi @emilianoalvarez91 

The Nav SDK iOS is distributed as source code, in both v3 and v2. It is the designated way for our library to distribute the release. We will support a second option to distribute the release as a framework, but at the moment I cannot guarantee the timeline.

-----

As a temporary workaround, you can build local xcframework. Please note that in this case, you need to provide all dependencies as frameworks.

You can test the flow in a branch [kried/framework-build.](https://github.com/mapbox/mapbox-navigation-ios/tree/kried/framework-build) Execute `sh scripts/build_frameworks.sh` in the root directory and open the `Examples/Examples.xcodeproj` project.

----

>  I've tried the solution proposed by @kried but that's not working as there is something wrong in how MapboxNavigationCore is created.

On the screenshot, it is visible that the dependency `MapboxNavigationNative` was not added. You need to add all the compiled frameworks to the project to resolve `missing symbol` errors.

1. You can update `Package.swift`: remove test targets and specify explicitly dependency on `MapboxNavigationNative` binary target. I attached the example Package.swift for v3.3.0. 
[Package.swift.zip](https://github.com/user-attachments/files/16665137/Package.swift.zip)

2. build the frameworks with [Scipio](https://github.com/giginet/Scipio/releases/tag/0.21.0) by executing the following lines in the mapbox-navigation-ios directory:
```
if [ ! -d "scipts/Scipio" ]; then
    git clone https://github.com/giginet/Scipio.git scipts/Scipio
fi
cd scipts/Scipio
git checkout "0.21.0"
swift build -c release

swift run -c release scipio create ../.. -f \
    --platforms iOS  \
    --only-use-versions-from-resolved-file \
    --enable-library-evolution \
    --support-simulators \
    --embed-debug-symbols \
    --verbose
```
3. Update Framework Search Path in Xcode project to contain the build results from `$PROJECT_DIR/../XCFrameworks`
4. Embed the xcframeworks into the project. Please note that you need to embed all of the frameworks on the screenshots and not add the dependencies through SPM.
<img width="815" alt="Screenshot 2024-08-19 at 22 18 12" src="https://github.com/user-attachments/assets/18b96990-6db1-40c7-8475-d2621c997ae6">

**Comment by emilianoalvarez91** [comment]
@kried thank you very much for the thorough response, I will check this tomorrow.

**Comment by fbeccaceci** [comment]
> Hi @emilianoalvarez91
> 
> The Nav SDK iOS is distributed as source code, in both v3 and v2. It is the designated way for our library to distribute the release. We will support a second option to distribute the release as a framework, but at the moment I cannot guarantee the timeline.
> 
> As a temporary workaround, you can build local xcframework. Please note that in this case, you need to provide all dependencies as frameworks.
> 
> You can test the flow in a branch [kried/framework-build.](https://github.com/mapbox/mapbox-navigation-ios/tree/kried/framework-build) Execute `sh scripts/build_frameworks.sh` in the root directory and open the `Examples/Examples.xcodeproj` project.
> 
> > I've tried the solution proposed by @kried but that's not working as there is something wrong in how MapboxNavigationCore is created.
> 
> On the screenshot, it is visible that the dependency `MapboxNavigationNative` was not added. You need to add all the compiled frameworks to the project to resolve `missing symbol` errors.
> 
> 1. You can update `Package.swift`: remove test targets and specify explicitly dependency on `MapboxNavigationNative` binary target. I attached the example Package.swift for v3.3.0.
>    [Package.swift.zip](https://github.com/user-attachments/files/16665137/Package.swift.zip)
> 2. build the frameworks with [Scipio](https://github.com/giginet/Scipio/releases/tag/0.21.0) by executing the following lines in the mapbox-navigation-ios directory:
> 
> ```
> if [ ! -d "scipts/Scipio" ]; then
>     git clone https://github.com/giginet/Scipio.git scipts/Scipio
> fi
> cd scipts/Scipio
> git checkout "0.21.0"
> swift build -c release
> 
> swift run -c release scipio create ../.. -f \
>     --platforms iOS  \
>     --only-use-versions-from-resolved-file \
>     --enable-library-evolution \
>     --support-simulators \
>     --embed-debug-symbols \
>     --verbose
> ```
> 
> 3. Update Framework Search Path in Xcode project to contain the build results from `$PROJECT_DIR/../XCFrameworks`
> 4. Embed the xcframeworks into the project. Please note that you need to embed all of the frameworks on the screenshots and not add the dependencies through SPM.
> 
> <img alt="Screenshot 2024-08-19 at 22 18 12" width="815" src="https://private-user-images.githubusercontent.com/3630656/359233655-18b96990-6db1-40c7-8475-d2621c997ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzY4MTcsIm5iZiI6MTcyNDEzNjUxNywicGF0aCI6Ii8zNjMwNjU2LzM1OTIzMzY1NS0xOGI5Njk5MC02ZGIxLTQwYzctODQ3NS1kMjYyMWM5OTdhZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDY0ODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZiNGYxODc2YjZmYWMwNmI0ODhmYzE4ZWVhMjEzNGIzNzMzYjM0OWJjZmY3MzA3NDc3MjhhOTVhNzFmZDk5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.um02Hpc_dXaNCVMgixzvEuRcHkv1tDyCGEaBTyw0Fu4">

Thanks @kried now i can build the frameworks correctly and they works included as you show, anyway i'm trying to include them as vedored_frameworks in a pod but i get some errors with duplicated declarations
<img width="603" alt="Screenshot 2024-08-20 alle 10 01 28" src="https://github.com/user-attachments/assets/3bde6e01-7fd7-462d-b376-bbf1d0f76fa8">

**Comment by kried** [comment]
> Thanks @kried now i can build the frameworks correctly and they works included as you show, anyway i'm trying to include them as vedored_frameworks in a pod but i get some errors with duplicated declarations

@fbeccaceci  The problem is that if you add `MapboxNavigation` as frameworks, you should also use all its dependencies as frameworks. So you cannot use the public open source release of `MapboxMaps`, because it leads to the symbols duplications for the Maps SDK and its dependencies, like `MapboxCommon`.

On your screenshots, it looks like there are duplicate symbols for `MapboxCommon`. Please ensure that you don't use dependencies on the pods`MapboxMaps` in your podspec, but explicitly add them as frameworks.

**Comment by fbeccaceci** [comment]
This is my podspec
```ruby
Pod::Spec.new do |s|
  s.name           = 'ExpoMapboxNavigation'
  s.version        = '1.0.0'
  s.summary        = 'A sample project summary'
  s.description    = 'A sample project description'
  s.author         = ''
  s.homepage       = 'https://docs.expo.dev/modules/'
  s.platforms      = { :ios => '15.0', :tvos => '15.0' }
  s.source         = { git: '' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'
  s.dependency 'SnapKit', '~> 5.7.0'

  s.vendored_frameworks = [
    "Frameworks/_MapboxNavigationHelpers.xcframework",
    "Frameworks/MapboxCommon.xcframework",
    "Frameworks/MapboxCoreMaps.xcframework",
    "Frameworks/MapboxDirections.xcframework",
    "Frameworks/MapboxMaps.xcframework",
    "Frameworks/MapboxNavigationCore.xcframework",
    "Frameworks/MapboxNavigationNative.xcframework",
    "Frameworks/MapboxNavigationUIKit.xcframework",
    "Frameworks/Turf.xcframework"
  ]

  # Swift/Objective-C compatibility
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'SWIFT_COMPILATION_MODE' => 'wholemodule'
  }

  s.source_files = "**/*.{h,m,mm,swift,hpp,cpp}"
end
```

I fixed the last 2 errors ("No such module 'MapboxMaps'") fixing a typo on the podspec but the redefinition errors remained, i don't have any dependency on any mapbox library in the pospec and i added all the frameworks

**Comment by fbeccaceci** [comment]
@kried I actually managed to fix the errors adding
```
s.exclude_files = "Frameworks/*.xcframework/**/*.h"
```
to the podspec

Now i got a question, can the frameworks be compiled as static frameworks? Cause i tried with scipio and the compile but then at runtime i get this exception
<img width="1012" alt="Screenshot 2024-08-20 alle 10 41 16" src="https://github.com/user-attachments/assets/af54a81c-866c-4771-acf1-7ddba309b3f4">

**Comment by fbeccaceci** [comment]
I got it working using use_frameworks! :linkage => :static don't really know why, i'm not that an expert about ios frameworks stuff

**Comment by emilianoalvarez91** [comment]
@kried I checked your branch and it works, also I could check the dynamic access token and that works too, thank you very much with the help here.

Can this solution be integrated into future versions of Package.swift? I don't mind generating the xcframeworks, but I prefer not to modify the original file. Otherwise, it would be difficult to track the URL for downloading MapboxNavigationNative.xcframework.zip or other framework dependencies.
