### ISSUE TITLE
[Bug]: Incorrect road which should be one way in Openstreetmap but it seems mapbox route still not updated

### ISSUE THREAD

**Issue by santoso8118** [mapbox/mapbox-navigation-ios#4712]
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

1. User origin location at : 1.2916178, 103.8491238
2. Search for a location name "Capitol Theatre" (1.2934845, 103.8513529)
3. Mapbox returns incorrect route that go through "Coleman lane". That is 1 way lane
4. We can check the location at that lane from google maps at: [25 Hill St - Google Maps](https://www.google.com/maps/@1.2937093,103.8502358,3a,15.1y,127.82h,87.25t/data=!3m10!1e1!3m8!1sUISNr01v-SOyaWOuDd5OSQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DUISNr01v-SOyaWOuDd5OSQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D94.6886%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192!9m2!1b1!2i48?coh=205409&entry=ttu)
Please see the capture image below to see the 1 way lane that we marked as red X icon in the image:

![Incorrect Route](https://github.com/user-attachments/assets/2ea8f45b-c868-4b4b-b997-abed122850d1)

### Expected behavior

Mapbox should update map data and suggest correct route for user.
The route should not go through "Coleman lane" its a 1 way lane

### Actual behavior

Mapbox give incorrect route to navigate user go through 1 way lane. This is dangerous for user to driving to a 1 way road

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @santoso8118 

Now the returned route looks like on this screenshot:
<img src="https://github.com/user-attachments/assets/d3b240b8-509b-4205-8bca-7a0553c7eb50" width="300" />
