### ISSUE TITLE
[Bug]: MapboxNavigationProvider automatically prompt user for foreground location permission

### ISSUE THREAD

**Issue by fbeccaceci** [mapbox/mapbox-navigation-ios#4714]
### Mapbox Navigation SDK version

3.3.0

### Steps to reproduce

Just instantiate an instance of MapboxNavigationProvider

```swift
let navigationProvider = MapboxNavigationProvider(coreConfig: .init(
    locationSource: .simulation(initialLocation: nil)
))
```

### Expected behavior

Nothing happen and i can manage myself the location permission.

### Actual behavior

The app shows the popup to grant foreground location permission.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by fbeccaceci** [comment]
This is a problem because i show a navigationMapView to the user in the first screen of the app, initialized like this 
```swift
let mapboxNavigation = navigationProvider.mapboxNavigation

self.navigationMapView = .init(
      location: mapboxNavigation.navigation().locationMatching.map(\.location).eraseToAnyPublisher(),
      routeProgress: mapboxNavigation.navigation().routeProgress.map(\.?.routeProgress).eraseToAnyPublisher(),
      heading: navigationProvider.navigation().heading,
      predictiveCacheManager: navigationProvider.predictiveCacheManager
    )
```

to show the user a map, without any navigation behavior. Then if the user grants location permission i can show theire location on the map and do some navigation, but right now as the app loads the user is directly asked to grant the permission and i cannot manage it myself

**Comment by JanTG1** [comment]
@fbeccaceci I have no Idea and haven't tried anything similar, but as a Mapbox User myself, I would guess it is due to the navigationProvider's Location handling, which needs permissions to work. You might want to build your own placeholder location provider instead of the one from your navigationProvider to avoid that.

**Comment by kried** [comment]
Hi @fbeccaceci 

As mentioned above, you can implement a custom location client that does not request location permission and pass it to  `MapboxNavigationProvider`
```swift
MapboxNavigationProvider(
            coreConfig: .init(
                locationSource: .custom(customLocationClient)
            )
        )
```
You can copy the  default SDK [LocationClient initialization](https://github.com/mapbox/mapbox-navigation-ios/blob/20f3c3c8ef9e0f5f63abaf064268a3c14fd81216/Sources/MapboxNavigationCore/Navigator/LocationClient/LocationClient.swift#L33) and remove `manager.requestWhenInUseAuthorization()` call.
Then it will be the responsibility of your app to request the required location permission at a suitable moment.

---

The other possible scenario is to custom initialize the `NavigationMapView` instance. You can create it even without `MapboxNavigationProvider` instance. You can pass empty publisher implementations and recreate `NavigationMapView` instance later once the location permission is requested:
```swift
let emptyLocationPublisher: AnyPublisher<CLLocation, Never> = Empty().eraseToAnyPublisher()
let emptyRouteProgress: AnyPublisher<RouteProgress?, Never> = Empty().eraseToAnyPublisher()
navigationMapView = .init(location: emptyLocationPublisher, routeProgress: emptyRouteProgress)
```
