### ISSUE TITLE
[Bug]: Xcode 16 - App Store Connect - validation warnings

### ISSUE THREAD

**Issue by denhams** [mapbox/mapbox-navigation-ios#4721]
### Mapbox Navigation SDK version

3.3.1.

### Steps to reproduce

In Xcode 16:

Select 'Archive' from the 'Product' menu.
When complete, select 'Validate App'

### Expected behavior

There are no validations warnings or errors.

### Actual behavior

The following warnings are reported:

Upload Symbols Failed
The archive did not include a dSYM for the MapboxCommon.framework with the UUIDs [6E909B97-8FE9-3577-AD0B-0BC34ECA5A3B]. Ensure that the archive's dSYM folder includes a DWARF file for MapboxCommon.framework with the expected UUIDs.

Upload Symbols Failed
The archive did not include a dSYM for the MapboxCoreMaps.framework with the UUIDs [E15C452C-5E22-3640-8107-EE5BDB04F372]. Ensure that the archive's dSYM folder includes a DWARF file for MapboxCoreMaps.framework with the expected UUIDs.

Upload Symbols Failed
The archive did not include a dSYM for the MapboxNavigationNative.framework with the UUIDs [C27E1C05-9177-32DE-9034-C9A7111551F4]. Ensure that the archive's dSYM folder includes a DWARF file for MapboxNavigationNative.framework with the expected UUIDs.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @denhams 

Thank you for the report. 
It was an intentional decision not to include dSYM for binary libraries. We are aware of the issue and this warning is an expected behavior.

Please see [the following response](https://developer.apple.com/forums/thread/761589?page=2) from the Apple on developer forum:
> This is a new warning in Xcode 16 where if you're missing a dSYM, Xcode lets you know in case you aren't expecting that — this is to reduce scenarios where you won't are able to fully symbolicating frames coming from your app's code in crash reports. In some cases, you may not have a dSYM, such as a closed source library from a vendor, and in those cases, the warning is safe to discard.
...
> I also did some tests with some libraries popular among the iOS community that are dynamically linked and closed source (with no dSYM provided), and in those circumstances, I did receive the warning, but that warning is expected in that situation.
