### ISSUE TITLE
Example-Swift app crashes when running in iPad Pro simulator when tapping Start Navigation button

### ISSUE THREAD

**Issue by troyibm** [mapbox/mapbox-navigation-ios#473]
I get this error when I run Example-Swift in Xcode 8.3.2 on the iPad Pro (9.7 inch) simulator in landscape mode.

`
Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7f926fa4fef0>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
`

**Comment by troyibm** [comment]
worked around this by changing `.actionSheet` to `.alert` in line https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/ViewController.swift#L90

**Comment by egmixer** [comment]
Thanks for sharing your solution

**Comment by valterh4ck3r** [comment]
Thank you so much @troyibm , you saved me :)

**Comment by SamAlmo** [comment]
You are amazing. Thanks for saving my time
