### ISSUE TITLE
Cocoapods and objective-c can't build project

### ISSUE THREAD

**Issue by populius** [mapbox/mapbox-navigation-ios#478]
xcode 8.3.2, cocoapods-1.2.1

![2017-08-11 15 49 31](https://user-images.githubusercontent.com/2752484/29206722-6021988a-7ead-11e7-86a5-183701b58984.png)

**Comment by frederoni** [comment]
This is because of a breaking change in [Pulley](https://github.com/52inc/Pulley) that mapbox-navigation-ios uses.

A workaround in the meantime would be to lock down Pulley to a specific version.
Add this to your Podfile
```ruby
pod 'Pulley', '1.4'
```
