### ISSUE TITLE
Ignoring return value of function declared with 'warn_unused_result' attribute

### ISSUE THREAD

**Issue by populius** [mapbox/mapbox-navigation-ios#479]
Objective-c code generate this warning

![2017-08-11 16 02 13](https://user-images.githubusercontent.com/2752484/29206989-8f90b8c0-7eae-11e7-9e5f-4d83db1780d6.png)

**Comment by frederoni** [comment]
Closing but feel free to open this issue in [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift)

You can avoid this by assigning the return value to a `NSURLSessionDataTask`:
```objc
NSURLSessionDataTask *task = [MBDirections …
```
or
```objc
(void)[MBDirections …
```
