### ISSUE TITLE
Smarter lane view

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#493]
We have a [long, convoluted and confusing series of if statements](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/LaneArrowView.swift) for figuring out the optimal lane configuration. It works ~80% of the time, but the remaining 20%, it fails miserably. 

![image](https://user-images.githubusercontent.com/1058624/29294316-a32eb074-8103-11e7-9108-8a7a4fe4cea0.png)

Let's find a more programmatic approach for displaying a lane than what we have now.

/cc @frederoni

**Comment by frederoni** [comment]
This is being implemented as part of https://github.com/mapbox/mapbox-navigation-ios/pull/490

**Comment by ericrwolfe** [comment]
Closed with #490.
