### ISSUE TITLE
Documentation: controller.route = route

### ISSUE THREAD

**Issue by Ahmeddben** [mapbox/mapbox-navigation-ios#495]
Hi there,

following this https://www.mapbox.com/mapbox-navigation-ios/navigation/0.6.0/storyboards.html trying to add Turn by turn navigation to my app. 

However:

                controller.route = route
                controller.directions = directions

keeps giving me an issue: 
Use of unresolved identifier "route"
Use of unresolved identifier "directions"

Pretty new to this so any help would be much appreciated!
Thanks

**Comment by bsudekum** [comment]
hey @Ahmeddben,

You shouldn't have to set these properties when showing the navigation UI. Check out how we're presenting the [view in the example app](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/ViewController.swift#L144-L154).

We're grabbing the route from here: https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/ViewController.swift#L114-L140

**Comment by Ahmeddben** [comment]
Hi @bsudekum,

Thank you for you reply! Do you guys have a detailed tutorial on how to set up turn by turn? I have looked at some tutorials on How to get started with Mapbox on the website but I am not able to find guides on Directions. 

Thanks!

**Comment by bsudekum** [comment]
@Ahmeddben I'm going through and updating the documentation now in this pr https://github.com/mapbox/mapbox-navigation-ios/pull/499. Until this is merged and put on mapbox.com, you can view the new guide here: https://github.com/mapbox/mapbox-navigation-ios/blob/1ddacc9a015af1acc84b7467b043c0caa546cf9a/docs/guides/getting-started.md

**Comment by Ahmeddben** [comment]
@bsudekum  Thanks, I followed all steps but get this: 
<img width="550" alt="screen shot 2017-08-16 at 12 21 13 am" src="https://user-images.githubusercontent.com/16583146/29347236-2fa487a2-8219-11e7-94da-d58ec0690786.png">


and also the app would crash once run
"terminating with uncaught exception of type NSException"

Im on Xcode8.3.1

Thanks!
