### ISSUE TITLE
can't reach mauverType, maneuverDirection not visible from Objective-C

### ISSUE THREAD

**Issue by greenzeal** [mapbox/mapbox-navigation-ios#496]
Dear friends,

Using your maps and want to reach mauverType, maneuverDirection properties of the MBRouteStep but can't from Objective C classes. Just not showing. The only is maneuverLocation is available. Please can you suggest the best way to solve this problem?

Thanks!

**Comment by 1ec5** [comment]
This issue is tracked in mapbox/MapboxDirections.swift#117. The fix would be entirely contained within that library; I’ll close this issue so we can keep the discussion in a single issue.
