### ISSUE TITLE
Puck jumps regression

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#500]
![](https://user-images.githubusercontent.com/1058624/29341221-cfbf5fec-81d7-11e7-9773-caade3d2bfaf.gif)

After bisecting it looks like something happened in https://github.com/mapbox/mapbox-navigation-ios/pull/490

Hunches: 

* Causes redraws everywhere https://github.com/mapbox/mapbox-navigation-ios/pull/490/files#diff-1d723166dc245772dbb9ba0077c94e6cR26
* that's all I got

/cc @frederoni

**Comment by frederoni** [comment]
Also bisected to the same commit.
However, `setNeedsDisplay()` is very efficient and isolated. It only marks the receiver once upon a style change but doesn't redraw until the next draw call. This is an issue with the map view and the Nav SDK's subviews not being in sync so we get an incorrect contentInset or other camera related options. Forcing a [`layoutIfNeeded`](https://github.com/mapbox/mapbox-navigation-ios/pull/503) before updating camera and userTrackingMode fixes that.
