### ISSUE TITLE
Loosen dependency requirements

### ISSUE THREAD

**Issue by aodhol** [mapbox/mapbox-navigation-ios#522]
Could Navigation depend on the latest version of MapBox because I'd like to take advantage of bug fixes / enhancements in 3.6.latest.

Thanks!

**Comment by 1ec5** [comment]
This would’ve been possible without any changes to the navigation SDK, except that we pinned all the navigation SDK’s dependencies to specific versions in #489 for some reason.

**Comment by aodhol** [comment]
@1ec5 Could it be pinned to major and minor versions allowing for patch version changes only?

**Comment by 1ec5** [comment]
@aodhol, yes, that’s what we should do. The fact that we aren’t currently specifying the dependency that way is a regression.

**Comment by 1ec5** [comment]
For future reference, CocoaPods [recommends](https://guides.cocoapods.org/syntax/podspec.html#dependency) that libraries declare dependencies using the tadpole operator. (I don’t see a reason why Carthage would differ on this point.)
