### ISSUE TITLE
Subclass RouteOptions instead of extending it

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#528]
It isn’t necessarily clear to a developer that the various `RouteOptions(forNavigationWith…)` methods are preferred over the standard initializers provided by MapboxDirections.swift. This library should provide NavigationOptions as a subclass of RouteOptions. It would then be possible to override all the standard initializers, including `init(coder:)`, and NavigationViewController’s initializer could enforce the use of NavigationOptions over RouteOptions, if desired.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/497#discussion_r134693672
/cc @mapbox/navigation-ios @ericdeveloper

**Comment by ericrwolfe** [comment]
Closed with https://github.com/mapbox/mapbox-navigation-ios/pull/531.
