### ISSUE TITLE
Warning - Instance method 'navigationMapView(_:imageFor:)' nearly matches optional requirement 'navigationMapView(_:shapeFor:)' of protocol 'NavigationMapViewDelegate'

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#533]
I think this occurred after waypoints merged. 

![image](https://user-images.githubusercontent.com/1058624/29685892-c1f1ec72-88cb-11e7-990e-0a1bbb3c35c0.png)

/cc @frederoni @1ec5

**Comment by 1ec5** [comment]
Yes, this is fallout from #270.
