### ISSUE TITLE
Build fails with Carthage

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-navigation-ios#537]
Using Carthage 0.24.0
Command line : 
carthage update --platform ios
output:
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Fetching mapbox-navigation-ios
*** Fetching MapboxDirections.swift
*** Fetching Polyline
*** Fetching aws-sdk-ios
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
*** Fetching Pulley
Failed to check out repository into /Users/mappy/Library/Caches/org.carthage.CarthageKit/dependencies/aws-sdk-ios: No object named "83c722a3e2aa9251d3d9f8e7b04339d5e6c83eab" exists (Error Domain=CarthageKit.CarthageError Code=22 "(null)")

Using mapbox navigation 0.6.1

**Comment by RomainQuidet** [comment]
Same env, using mapbox navigation 0.5 works.

**Comment by 1ec5** [comment]
Huh, frederoni/aws-sdk-ios@83c722a3e2aa9251d3d9f8e7b04339d5e6c83eab exists; not sure why Carthage fails to pick it up.

/cc @frederoni

**Comment by 1ec5** [comment]
Does your application also depend on the AWS SDK for its own purposes? This library depends on a fork of the AWS SDK, so there could be a conflict unless you depend on the same fork.

**Comment by RomainQuidet** [comment]
Hi,
No my test app only uses the navigation core. Carthage does not offer anyway to use only the core, so I import all the lib as in your readme.

Romain

**Comment by Svantulden** [comment]
I'm having the same issue when including release 0.6.1 and running `carthage update --platform ios`. The only way I got the project to build (as a quick workaround), was by running the `master` branch in my carthage file and modifying my local repo to change the frederoni fork to the official AWS repo (`github "aws/aws-sdk-ios" == 2.5.10`). This of course then loads all the AWS SDK's, which is unwanted.

**Comment by Jauzee** [comment]
Try to run `carthage update` without specifying a platform.

**Comment by bsudekum** [comment]
We just released v0.7.0 which should solve this polly issue.

**Comment by RomainQuidet** [comment]
I will test it ! Thanks.
