### ISSUE TITLE
Enable night mode while in tunnels

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#559]
We should be able to tell if a driver's in a tunnel and automatically enable dark mode. 

However, this isn't something that's currently supported by the Directions API 

cc @bsudekum @miccolis @v8c3

**Comment by daniel-j-h** [comment]
Upstream ticket for tunnels and other notifications:

https://github.com/Project-OSRM/osrm-backend/issues/3028

I can remember talking to @1ec5 about tunnels when we added the classes way property and there was an argument against tunnels but I can't remember - @1ec5 could you chime in here?

**Comment by 1ec5** [comment]
In this case, I don’t think we need an additional notification from OSRM. We already query the map vector tiles on each location update to get the current road’s name. #297 (which was closed but could easily be resurrected) refactors that code to give us rich information about the current road, including whether it’s in a tunnel or on a bridge.

**Comment by 1ec5** [comment]
> However, this isn't something that's currently supported by the Directions API

Project-OSRM/osrm-backend#4816 added a `tunnel` class. Once mapbox/MapboxDirections.swift#237 lands, we can switch to night mode as soon as the user crosses an intersection with the tunnel class and switch back to day mode as soon as they cross an intersection without the tunnel class.

**Comment by bsudekum** [comment]
This shipped in https://github.com/mapbox/mapbox-navigation-ios/pull/1127
