### ISSUE TITLE
Lane icons need to handle more lane configurations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#576]
[`LaneArrowView.draw(_:)`](https://github.com/mapbox/mapbox-navigation-ios/blob/622d092808b660085cf149411de7886dfd810b01/MapboxNavigation/LaneArrowView.swift#L34) omits some common lane indication scenarios, which means we probably give misleading information in those cases:

* [x] Three indications on a single lane — There are hundreds of ways in OpenStreetMap that contain `left;through;right` in the [`turn:lanes`](http://taginfo.openstreetmap.org/keys/turn%3Alanes#values) tag, which maps to a `LaneIndication` of `[.left, .straight, .right]` in MapboxDirections.swift ([example](https://www.openstreetmap.org/way/394222593)). There are also `reverse;left;through` lanes in some places.
* [x] U-turn lanes — There are hundreds of ways that contain `reverse;left`, which maps to `[.uTurn, .left]`. For any step that requires a U-turn, this becomes relevant for situations like `reverse;left|left`, when a lane that allows U-turns and left turns is next to a lane that allows only left turns – the driver needs to get into the leftmost lane, not the two left lanes.
* [x] Left-right turn lanes — There are thousands of ways that contain `left;right`, which maps to `[.left, .right]` ([example](http://www.openstreetmap.org/way/517630993); open iD to see the pavement marking). This is especially common at a T-intersection or where a road becomes a one-way road.

![](http://image.shutterstock.com/display_pic_with_logo/5056/5056,1200279692,3/stock-photo-left-amp-u-turn-lanes-sign-8523307.jpg)
[![](https://64979b2f6b027cae8e62-f7cc18cbdbb0c5f64a3d357c0f170d67.ssl.cf2.rackcdn.com/0650AE54-A632-4C0E-8E2C-A263804440B1-lg.jpg)](https://www.tapconet.com/store/product-detail/vkbb/r61-26-ca-triple-lane-control-left-and-right-turn-symbol-sign?c=Bmab&sku=311110)

The U.S. signs above are based on the following standard:

http://mutcd.fhwa.dot.gov/SHSe/Regulatory.pdf#page=29
http://mutcd.fhwa.dot.gov/SHSe/Regulatory.pdf#page=62

Commons has plenty of SVGs of U.S. and European lane control signs that we can repurpose for this UI:

https://commons.wikimedia.org/wiki/Category:Lane_turning_road_signs
https://commons.wikimedia.org/wiki/Category:Mandatory_direction_road_signs
https://commons.wikimedia.org/wiki/Category:R3-6_-_Optional_Movement_Lane_Control
https://commons.wikimedia.org/wiki/Category:R3-18_-_No_Left_or_U_turn

/cc @bsudekum @mayagao @frederoni @daniel-j-h @danesfeder @ericrwolfe

**Comment by 1ec5** [comment]
@bhousel made a bunch of scalable vector turn lane icons that closely match the style we’re using: openstreetmap/lane-icons#1.

**Comment by bhousel** [comment]
> @bhousel made a bunch of scalable vector turn lane icons that closely match the style we’re using: openstreetmap/lane-icons#1.

Disclaimer:  I haven't actually made them yet :)   I do have an illustrator file sitting somewhere.  Ballpark estimate, what kind of resolution would you show them at?  We realized that we'd need to design very different icons for tiny and large sizes (arrowheads are complicated).

**Comment by 1ec5** [comment]
30 points × 30 points:

https://github.com/mapbox/mapbox-navigation-ios/blob/e942a425208feda1ad2a15ee0c6ad27552440b34/MapboxNavigation/LanesView.swift#L32

Note that we designed the lane arrow icons in PaintCode and exported them as Swift code (on iOS; Java code on Android). PaintCode can import SVG, but mainly I mentioned openstreetmap/lane-icons#1 to provide a sense of the combinations that are required.

**Comment by 1ec5** [comment]
Tracking the actual artwork in mapbox/navigation-ui-resources#8.

**Comment by 1ec5** [comment]
Still blocked upstream.

**Comment by 1ec5** [comment]
No longer blocked as of mapbox/navigation-ui-resources#21.

**Comment by 1ec5** [comment]
#2801 tracks selecting the turn lane icon with less guessing; that change would have a much greater impact if we can support the common configurations listed in https://github.com/mapbox/mapbox-navigation-ios/issues/576#issue-254680486. mapbox/navigation-ui-resources#21 adds these and several somewhat less common configurations. In order to support any of the new assets, a new StyleKit will need to be exported from PaintCode and the calls to it in LaneView will need to be updated.

**Comment by 1ec5** [comment]
Fixed in #2882 on the release-v2.0 branch for v2.0.0.
