### ISSUE TITLE
Adjust day/night timing to match typical headlight usage

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#581]
Civil sunrise + sunset might still be too late to enable dark mode.

The typical regulations are for headlights to be in use from 30 minutes after sunset until 30 minutes before sunrise: https://www.yourmechanic.com/article/headlight-use-laws-for-all-50-states

Even just 10-15 min before sunrise / after sunset feels right for night mode.

cc @bsudekum

**Comment by bsudekum** [comment]
[Solar gives us the option for:](https://github.com/ceeK/Solar#types-of-sunrise-and-sunset) 

* Official (~0°)
* Civil (6° below horizon)
* Nautical (12° below horizon)
* Astromonical (18° below horizon)

Want to try moving to `official`?

**Comment by ericrwolfe** [comment]
Let's go with `official`.

Driving back on a highway this weekend around sunset, most drivers had their headlights on by sunset because trees/clouds blocked the sun. Google Maps switched to night mode right at sunset.

**Comment by bsudekum** [comment]
done in https://github.com/mapbox/mapbox-navigation-ios/pull/584
