### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value in RouteMapViewController.swift

### ISSUE THREAD

**Issue by TCOA** [mapbox/mapbox-navigation-ios#582]
just loaded 0.7.0 and upon running, I get the 'nil' error on this line....
`if notification.userInfo![RouteControllerDidFindFasterRouteKey] as! Bool {`

wrapping in a "!= nil" bypasses the error...

` if notification.userInfo![RouteControllerDidFindFasterRouteKey] != nil {`

though the route is not tracking the Simulator route (not sure if that is related, though still testing...)

**Comment by bsudekum** [comment]
I've actually seen this a few times. It looks like we're sending a reroute somewhere without all the proper user info keys. @TCOA are there specific situations you see this error?

**Comment by TCOA** [comment]
I'm currently presenting the map viewController after receiving a push notification.  Further testing (after I removed the wrap) shows it doesn't crash every time (right now I am also running the example test on the same phone on a long simulation drive, so the phone is pretty busy...).

I'm hoping to find a way to 'add on' the bits to the map instead of presenting a new controller (what I'm doing now is showing the map at first, then after 'conditions' [and a push notification], jump into the turn-by-turn.   Once I figure out how to add/remove just those pieces {and I think the new Custom example will get me there}, I think that will be a much better way)
