### ISSUE TITLE
Option to use metric or customary units

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#589]
`DistanceFormatter` currently switches between metric and customary units based on the locale (specifically the region):

https://github.com/mapbox/mapbox-navigation-ios/blob/e48d724b7e22522bbffc2a90e9435e4d0e31e6ad/MapboxCoreNavigation/DistanceFormatter.swift#L31-L37

But turn-by-turn applications often offer a user setting to switch between metric and customary units, regardless of the locale. We should expose a top-level option that affects the measurement system used by any `DistanceFormatter` instance associated with a NavigationViewController instance.

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/242#issuecomment-327619678
/cc @frederoni @troyibm

**Comment by 1ec5** [comment]
The “In {distance}” parts of spoken instructions now come from the server, and the units are determined by the `RouteOptions.distanceMeasurementSystem` property, which defaults to the current locale’s measurement system. To ensure consistency between spoken instructions and the the UI, we should expose `distanceMeasurementSystem` on NavigationViewController and automatically set `RouteOptions.distanceMeasurementSystem` and set all the DistanceFormatter instances’ measurement systems accordingly.

/cc @ericrwolfe @bsudekum

**Comment by bsudekum** [comment]
Can't you override this on `NavigationRouteOptions`?

**Comment by 1ec5** [comment]
Yes, but what about the mileage in the bottom bar and elsewhere? Essentially, this ticket consists of automatically adapting the DistanceFormatter instances to use whatever measurement system NavigationRouteOptions uses.
