### ISSUE TITLE
Flash while rerouting

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#592]
The UI does a quick flash while rerouting, we should fix this.

/cc @frederoni

**Comment by bsudekum** [comment]
![old](https://user-images.githubusercontent.com/1058624/30176589-01576d50-93d1-11e7-853e-c822e30f94ed.gif)

**Comment by frederoni** [comment]
@bsudekum is this on iOS 10 or 11?

**Comment by bsudekum** [comment]
iOS 10, iPhone 6 & 7.
