### ISSUE TITLE
How to apply custom map style?

### ISSUE THREAD

**Issue by davidseek** [mapbox/mapbox-navigation-ios#597]
Trying it exactly the way the documentation suggests don't seem to work for me.

```

class CustomStyle: DayStyle {
    
    
    required init() {
        super.init()
        mapStyleURL = URL(string: "mapbox://styles/mapbox/light-v9")!
        styleType = .dayStyle
    }
    
    override func apply() {
        super.apply()
        ManeuverView.appearance().backgroundColor = Colors.white
        RouteTableViewHeaderView.appearance().backgroundColor = Colors.white
    }
    
    
}

```

The values of `ManeuverView.appearance().backgroundColor` and `RouteTableViewHeaderView.appearance().backgroundColor` can be changed the way I want. But the mapStyleURL has no effect at all.

How do I properly change the mapStyleURL? Help is very appreciated.

**Comment by davidseek** [comment]
According to pod update I'm using `Using MapboxNavigation (0.7.0)`

**Comment by davidseek** [comment]
Maybe related: https://github.com/mapbox/mapbox-navigation-ios/issues/596 ?

**Comment by frederoni** [comment]
> Maybe related: #596 ?

Yes, unfortunately, updating the map view’s styleURL using a `Style` is not working in 0.7.0.
Please try the latest from master or wait for the next release.

**Comment by davidseek** [comment]
Thank you for letting me know. I'll just wait for the next release then.
