### ISSUE TITLE
RouteController: add possibility for rerouting travel less than 50 meters away

### ISSUE THREAD

**Issue by hervouinc** [mapbox/mapbox-navigation-ios#598]
RouteController's delegate "shouldReroute" can't be called by traveling less than 50 meters away from the current step. 

This distance is defined by the Constant ```RouteControllerMaximumDistanceBeforeRecalculating ``` which is used in ```userIsOnRoute``` method.

Reroutes can be "filtered" using ```shouldRerouteFrom```:
```swift
guard userIsOnRoute(location) || !(delegate?.routeController?(self, shouldRerouteFrom: location) ?? true) else {
    reroute(from: location)
    return
}
```
But it can't be less than 50 meters anyway.

It would be great to have the possibility to set the ```RouteControllerMaximumDistanceBeforeRecalculating``` parameter from outside the SDK.

**Comment by bsudekum** [comment]
@hervouinc you can set `RouteControllerMaximumDistanceBeforeRecalculating ` after presenting, (building on the example app code):

```swift
func startBasicNavigation() {
    guard let route = currentRoute else { return }
    
    exampleMode = .default
    
    let navigationViewController = NavigationViewController(for: route, locationManager: locationManager())
    navigationViewController.showsReportFeedback = true
    navigationViewController.navigationDelegate = self
    navigationViewController.automaticallyAdjustsStyleForTimeOfDay = true
    
    present(navigationViewController, animated: true, completion: nil)
    
    RouteControllerMaximumDistanceBeforeRecalculating = 5
}
```

**Comment by hervouinc** [comment]
@bsudekum right, I didn't realise it was a ```var```.
I close that one !
