### ISSUE TITLE
Cannot build Example Swift project

### ISSUE THREAD

**Issue by kthotav** [mapbox/mapbox-navigation-ios#601]
Hi im not able to build the example project. Please help. I tried changing the team to my personal team and it would not work. thanks in advance! 
![screen shot 2017-09-11 at 11 51 01 am](https://user-images.githubusercontent.com/13564400/30291366-8510d9f6-96e7-11e7-958e-3f54c3143146.png)

**Comment by frederoni** [comment]
I assume you have two teams. Try the one that doesn't say "Personal Team"
Also, would you mind adding a screenshot of the Signing section of the Example-Swift target?

**Comment by Jauzee** [comment]
@kthotav try to change signing settings for tests & framework targets too.

**Comment by kthotav** [comment]
@Jauzee thanks I got it to build after changing the signing settings for all the targets
