### ISSUE TITLE
Confusion about yards vs feet

### ISSUE THREAD

**Issue by jeeftor** [mapbox/mapbox-navigation-ios#606]
I'm a little confused on how to use the distance formatters correctly.  I've tried to implement my own Navigation controller using this repo.

I've defined formatters as such:

```swift
fileprivate let voiceInstructionFormatter = SpokenInstructionFormatter()
fileprivate let textInstructionFormatter = VisualInstructionFormatter()
fileprivate let textDistanceFormatter = DistanceFormatter(approximate: true)
fileprivate let voiceDistanceFormatter = SpokenDistanceFormatter(approximate: true)
```

and set them up this way:

```swift
textDistanceFormatter.numberFormatter.maximumFractionDigits = 0
textDistanceFormatter.numberFormatter.locale = Locale(identifier: "en-US")
voiceDistanceFormatter.numberFormatter.locale = Locale(identifier: "en-US")        
```

My voice formatter is giving me things in `feet` while the text one is giving me `yards`.  Am i missing a setting somewhere?

**Comment by frederoni** [comment]
My assumption is that you're using one of NSLengthFormatter’s methods and therefore bypassing the overriding of yards.

```swift
DistanceFormatter.string(from:) <- should work
DistanceFormatter.string(fromValue:unit:) <- won't work
DistanceFormatter.string(fromMeters:) <- won't work
```

Can you verify if that's the case?

**Comment by jeeftor** [comment]
THANKS YOU!

**Comment by jeeftor** [comment]
I was using `fromMeters:` All is good in the world again!!!
