### ISSUE TITLE
Xcode 9 and Swift 4 plan

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#608]
What kind of schedule are we looking at here? Should we keep a swift 3/xcode 8 branch laying around for people to use if they're app is behind? When do we want swift 4 in master?

/cc @1ec5 @frederoni @ericrwolfe

**Comment by 1ec5** [comment]
Xcode 9 supports Swift 3, so there’s no rush to adopt Swift 4. We should make sure the library compiles as Swift 3 via CocoaPods, though.

> When do we want swift 4 in master?

When there’s a good concrete reason to use Swift 4 for a new feature, we can guard it behind `#if swift(4)`, or we can upgrade the library to Swift 4 but leave in `#if swift(3)` fallbacks as necessary.

**Comment by 1ec5** [comment]
Polyline just upgraded to Swift 4 in v4.2.0. [Via Carthage](https://github.com/mapbox/MapboxDirections.swift/blob/master/Cartfile), MapboxDirections.swift depends on `~> 4.1.1` of that library, which means it won’t pull in v4.2.0, but [via CocoaPods](https://github.com/mapbox/MapboxDirections.swift/blob/b0099c081cac78aa57945e3b9fc3e7daa4316921/MapboxDirections.swift.podspec#L47), it depends on `~> 4.1`, which will pull in v4.2.0. It should be possible for a Swift 3 library to depend on a Swift 4 library in Xcode 9, but I’m not sure whether MapboxDirections.swift remains compatible with Xcode 8.3 or how much that matters at this point.

**Comment by bsudekum** [comment]
We're on swift 4.
