### ISSUE TITLE
Improve iphone x layout

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#611]
![image](https://user-images.githubusercontent.com/1058624/30398412-1b9b0970-9885-11e7-8b47-30e97de09dbc.png)

1. resume button is not flush with bottom bar
1. bottom bar is too tight on new home button
1. padding should be increased around edges

/cc @frederoni

**Comment by bsudekum** [comment]
@frederoni have a sec this week to take a look at this?

**Comment by frederoni** [comment]
All minor tweaks like this is currently blocked by #745

**Comment by bsudekum** [comment]
Optimized for the x in v0.10.0.
