### ISSUE TITLE
Possibility to adjust the width of polyline

### ISSUE THREAD

**Issue by KevinBerglund-Hitta** [mapbox/mapbox-navigation-ios#627]
Any possibility to be able to adjust the width of the polyline before starting the navigation.

![screen shot 2017-09-19 at 15 57 32](https://user-images.githubusercontent.com/25028125/30596046-4d390824-9d53-11e7-8eb9-bcff1d2d5ada.png)

**Comment by frederoni** [comment]
Yes, you can implement:`NavigationViewControllerDelegate.navigationMapView(_:routeStyleLayerWithIdentifier:source:)` and use [Runtime Styling](https://www.mapbox.com/ios-sdk/api/3.6.3/runtime-styling.html) to modify most of its attributes. 

If you leave the delegate method unimplemented, we style the route line with something along these lines:
```swift
func navigationMapView(_ mapView: NavigationMapView, routeStyleLayerWithIdentifier identifier: String, source: MGLSource) -> MGLStyleLayer? {
        if identifier == "routeLayer" {
            
            let routeLineWidthAtZoomLevels: [Int: MGLStyleValue<NSNumber>] = [
                10: MGLStyleValue(rawValue: 8),
                13: MGLStyleValue(rawValue: 9),
                16: MGLStyleValue(rawValue: 12),
                19: MGLStyleValue(rawValue: 24),
                22: MGLStyleValue(rawValue: 30)
            ]
            
            let line = MGLLineStyleLayer(identifier: identifier, source: source)
            line.lineWidth = MGLStyleValue(interpolationMode: .exponential,
                                           cameraStops: routeLineWidthAtZoomLevels,
                                           options: [.defaultValue : MGLConstantStyleValue<NSNumber>(rawValue: 1.5)])
            
            line.lineColor = MGLStyleValue(interpolationMode: .categorical, sourceStops: [
                "unknown": MGLStyleValue(rawValue: mapView.trafficUnknownColor),
                "low": MGLStyleValue(rawValue: mapView.trafficLowColor),
                "moderate": MGLStyleValue(rawValue: mapView.trafficModerateColor),
                "heavy": MGLStyleValue(rawValue: mapView.trafficHeavyColor),
                "severe": MGLStyleValue(rawValue: mapView.trafficSevereColor)
                ], attributeName: "congestion", options: [.defaultValue: MGLStyleValue(rawValue: mapView.trafficUnknownColor)])
            
            line.lineOpacity = MGLStyleValue(interpolationMode: .categorical, sourceStops: [
                true: MGLStyleValue(rawValue: 1),
                false: MGLStyleValue(rawValue: 0)
                ], attributeName: "isCurrentLeg", options: nil)
            
            line.lineJoin = MGLStyleValue(rawValue: NSValue(mglLineJoin: .round))
            
            return line
        }
        
        return nil
    }
```

_this example has been adapted to work for the view controller that presents `NavigationViewController`_

**Comment by KevinBerglund-Hitta** [comment]
This works fine when I start the navigation, but what should I send to the function before I start the navigation?

**Comment by frederoni** [comment]
Not sure I'm following. Do you want to adjust the route line on the in navigation screen or on a screen that's being used before presenting the `NavigationViewController`? If it's another screen, is the map view of kind `MGLMapView` or `NavigationMapView`?

If you use a `NavigationMapView`, calling `showRoute(_:)` will construct sources and layers using runtime styling and let you style the route line conveniently via the delegate method.

If it's a regular `MGLMapView`, you'd have to use runtime styling "from scratch" and construct your sources and layers.

**Comment by KevinBerglund-Hitta** [comment]
We're using the NavigationMapView in the background and before starting the NavigationViewController is has a preview of the route Mapbox has calculated and we want to adjust the thickness of the polyline drawn on the NavigationMapView.

**Comment by frederoni** [comment]
Ok, then it should call the `navigationMapView(_:routeStyleLayerWithIdentifier:source:)` and let you adjust the route line using that delegate method. Make sure the `navigationMapDelegate` is set and that you implement the correct delegate method.

If there's a timing issue or the method not getting triggered, could you provide a small snippet of your implementation?

**Comment by KevinBerglund-Hitta** [comment]
`
let navigationViewController = NavigationViewController(for: route, locationManager: self.locationManager())
navigationViewController.showsReportFeedback = false
navigationViewController.navigationDelegate = self
present(navigationViewController, animated: true, completion: nil)
`
is contained in a function which is called when clicking a start button otherwise we havn't called for the NavigationViewController in Mapbox Navigation SDK

**Comment by frederoni** [comment]
`NavigationViewController` is irrelevant if this is regarding an arbitrary preview screen that's only making use of `NavigationMapView`.

A bare minimum of a `PreviewViewController` could look something like this:
```swift
class PreviewViewController: UIViewController, NavigationMapViewDelegate {
    @IBOutlet weak var mapView: NavigationMapView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mapView.navigationMapDelegate = self
    }

    // Calculate a route and call `mapView.showRoute(_:)`

    func navigationMapView(_ mapView: NavigationMapView, routeStyleLayerWithIdentifier identifier: String, source: MGLSource) -> MGLStyleLayer? {
        /// return a custom styled version of the various style layers
    }
}
```

**Comment by frederoni** [comment]
@KevinBerglund-Hitta did you get this issue sorted out?

**Comment by KevinBerglund-Hitta** [comment]
@frederoni, yes, thank you for your help :)
