### ISSUE TITLE
Issue after installing using CocoaPods

### ISSUE THREAD

**Issue by jojonarte** [mapbox/mapbox-navigation-ios#636]
Xcode Version: 8.2
Podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapBoxOfflineSpike' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapBoxOfflineSpike
#    pod 'Mapbox-iOS-SDK', '~> 3.6'
#    pod 'MapboxDirections.swift', '~> 0.10'
    pod 'MapboxNavigation', '~> 0.8.0'
end

```

![issue](https://user-images.githubusercontent.com/11880365/30650951-dae9db0e-9e56-11e7-92aa-b79c10714013.png)

**Comment by frederoni** [comment]
Thank you for your report.
Can you try a more recent version of Xcode? Preferably 8.3.3 or 9.

**Comment by jojonarte** [comment]
@frederoni I actually couldn't right now, I have not updated my mac to Sierra and can't as I don't have enough space also. I hope I could though.

**Comment by sriteja25** [comment]
Tried it on Xcode. 9 (Final public release) and still having some issues integrating the project using Cocoapods.

**Comment by bsudekum** [comment]
@sriteja25 are you having the same issue or a different error?

**Comment by sriteja25** [comment]
<img width="1019" alt="screen shot 2017-09-28 at 1 03 45 am" src="https://user-images.githubusercontent.com/12974407/30933709-f7083d7a-a3e8-11e7-8ec7-3c5e30a91af6.png">

**Comment by 1ec5** [comment]
@sriteja25, that looks like a distinct problem. Can you open a separate issue for that? Thanks!
