### ISSUE TITLE
Incorrect arrow exit indicator on roundabout

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#638]
On the current 0.80.0 SDK, the navigation displays an incorrect roundabout exit arrow indicator.

![img_0012](https://user-images.githubusercontent.com/4553825/30693757-483bdc32-9ed1-11e7-889d-862a87c9acaf.PNG)

The roundabout in question is:
https://www.hitta.se/kartan!~59.21583,17.63506,16z/tr!i=6Kbb9lGk/geocode!l=59.21595:17.63450

**Comment by frederoni** [comment]
Fixed in #640

**Comment by Sealos** [comment]
Thank you!
