### ISSUE TITLE
Modularize UI components

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#645]
Let's make it so developers can mix and match different pieces of the UI as needed. Developers should be able to provide their own view and add a top bar or a bottom bar as needed.

/cc @frederoni @1ec5 @ericrwolfe

**Comment by ericrwolfe** [comment]
Components of the top and bottom bar that might be useful to modularize. Some of these are basically there while some will require more of a lift: 
- [ ] turn arrow view
- [ ] lane guidance view
- [ ] colorized time remaining label
- [ ] banner label that supports inline shields
- [ ] shield view

Most other cases around top/bottom banners can be made up with basic labels that update in response to a progressDidChange notification.

**Comment by 1ec5** [comment]
Are we talking about making these views settable as properties on NavigationViewController (so you can swap in a custom view), or being able to use each of the views above as standalone views (so you could use the banner with, say, a MapKit MKMapView)?

**Comment by ericrwolfe** [comment]
> being able to use each of the views above as standalone views

👆
