### ISSUE TITLE
How to present a NavigationViewController from a container View?

### ISSUE THREAD

**Issue by sriteja25** [mapbox/mapbox-navigation-ios#664]
I have a container View where the upper half shows some details and th lower half shows the navigation to a particular place.

A is my View Controller with a container View , Now i have B View Controller which occupies bottom Half of the A View Controller. I have another View Controller C which is being presented from B, but instead of occupying the bottom half , it occupies entire screen. How can i fix it so that whatever happens after interaction fro View Controller B it stays in the bottom half of the screen ?

In the bottom half the view controller first takes in a few values and them presents a view 

![img_7889](https://user-images.githubusercontent.com/12974407/30949334-5fe3458e-a433-11e7-8c5e-49ba8f3f627a.PNG)

Now when i present a new View Controller it occupies entire screen

![img_7890](https://user-images.githubusercontent.com/12974407/30949340-681dad20-a433-11e7-95c1-fcf484a41ca5.PNG)

I want the turn by turn Navigations aka NavigationViewController to be displayed from the container view, can i achieve this ?

**Comment by frederoni** [comment]
You can wrap View Controller B in a UINavigationController (with a hidden navigation bar) so that it has its own navigation stack.

**Comment by sriteja25** [comment]
Thanks a lot works perfectly. :)
