### ISSUE TITLE
setting delegate on NavigationMapView crashes app running in Xcode 9

### ISSUE THREAD

**Issue by troyibm** [mapbox/mapbox-navigation-ios#666]
I was using mapbox-navigation-ios version 0.6.0 before upgrading to 0.8.1 and building with Xcode9 (figured I would need the latest and greatest to get everything building with Xcode 9).  My app immediately crashed on `mapView.delegate = self`.  I was doing this call in viewDidLoad before, but thought I better move it to viewDidAppear but that didn't solve the problem.

Still investigating.  Not sure where the problem is as the project compiles.

**Comment by troyibm** [comment]
eeek.. I entered issue # 666.  😨

**Comment by bsudekum** [comment]
@troyibm could you distill this error down to a few lines of code and share it with us?

**Comment by troyibm** [comment]
@bsudekum that will be tough to do.  I'm on the mapbox slack.  I'm wondering if a /hero screen share will suffice.  I'm actually having a tough time getting anything to work with Xcode 9, device at iOS 11.0.1, with latest mapbox-navigation-ios, mapbox-ios-sdk, and MapboxDirections.swift.  Currently trying different combinations to see where the problem is.  Do you guys know if latest on all those libraries on iOS 11.0.1 with navigation simulation works fine?

**Comment by troyibm** [comment]
One thing I notice is that MapboxDirections.swift/Cartfile.resolved has mapbox-ios-sdk at 3.5.4.  That's odd to me if my Cartfile.resolved is using a later version like 3.6.4.

**Comment by troyibm** [comment]
After looking at the Cartfile in mapbox-navigation-ios I saw that it includes MapboxDirections and Mapbox-iOS-SDK and thought this problem might be caused by the fact that I would specify versions of mapbox-navigation-ios, MapboxDirections.swift and Mapbox-iOS-SDK in my Cartfile.  But even after just having mapbox-navigation-ios in my Cartfile (using 0.8.2), I still get a crash as soon as I set mapView.delegate (mapView is `@IBOutlet weak var mapView: NavigationMapView!`).

**Comment by frederoni** [comment]
The `RouteMapViewController` must be the receiver of`NavigationMapView`’s delegate (`MGLMapViewDelegate`). However, some of the methods are delegated through the `RouteMapViewController` to the `NavigationViewController` for customizability and exposed as `NavigationViewControllerDelegate.navigationMapView(_:viewFor:)`, `NavigationViewControllerDelegate.navigationMapView(_:imageFor:)`. Let us know if there are any other `MGLMapViewDelegate` methods that we should expose.

<details>
<code>

```swift
class MyViewController: UIViewController, NavigationViewControllerDelegate {
    
    func navigationMapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        // Return a custom view for annotation
    }
    
    func navigationMapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
        // Return a custom image for annotation
    }
    
    func startNavigation() {
        let controller = NavigationViewController(for: route)
        controller.navigationDelegate = self
        present(controller, animated: true, completion: nil)
    }
}
```

</code>
<details>

**Comment by troyibm** [comment]
Okay, this is likely narrowing down to the problem.  I'm assigning the delegate of `NavigationMapView` to allow the map to be interacted with during navigation.  I do not have a  `RouteMapViewController` extension defined.  I do define the `MGLMapViewDelgate` and `NavigationViewControllerDelegate` extension.

Here's the code I have for the NVDC:
```swift
extension MapboxViewController: NavigationViewControllerDelegate {
    func navigationViewController(_ navigationViewController: NavigationViewController, didArriveAt destination: MGLAnnotation) {
        navigationViewController.dismiss(animated: true, completion: nil)
        startingPoint = (destination as? MGLPointAnnotation)!
        mapView.removeRoute()
        mapView.removeAnnotations(mapView.annotations!)
        mapView.addAnnotation(startingPoint)
    }
}
```
I do see a warning in Xcode on the function above saying `Instance method 'navigationViewController(_:didArriveAt:)' nearly matches optional requirement 'navigationViewController(_:didArriveAt:)' of protocol 'NavigationViewControllerDelegate'` maybe this is the problem.


Here's the code for how I'm detecting that the user is manipulating the map and not the programmatic tracking of the "current location annotation " that is changing the map:

```swift
// MARK: MGLMapViewDelegate
extension MapboxViewController: MGLMapViewDelegate {
    
    private func mapViewRegionDidChangeFromUserInteraction() -> Bool {
        //  Look through gesture recognizers to determine whether this region change is from user interaction
        if let gestureRecognizers = self.mapView.gestureRecognizers {
            for recognizer in gestureRecognizers {
                if recognizer.numberOfTouches != 3 {
                    if( recognizer.state == UIGestureRecognizerState.began || recognizer.state == UIGestureRecognizerState.ended ) {
                        return true
                    }
                }
            }
        }
        return false
    }
    
    func mapView(_ mapView: MGLMapView, regionWillChangeAnimated animated: Bool) {
        if mapViewRegionDidChangeFromUserInteraction() {
            self.stopTracking()
        }
    }
    
    func mapView(_ mapView: MGLMapView, regionDidChangeAnimated animated: Bool) {
        if mapViewRegionDidChangeFromUserInteraction() {
            self.stopTracking()
        }
    }
}
```

**Comment by frederoni** [comment]
The `RouteMapViewController` is embedded at the top part of `NavigationViewController` so 
 you do make use of it under the hood. Unfortunately, with the current implementation, you can't/shouldn't set the `mapView`’s `delegate` property because the `RouteMapViewController` must be the receiver of those delegate methods.

If you need to use:
```swift
mapView(_:regionWillChangeAnimated:)
mapView(_:regionDidChangeAnimated:)
```

it must be done through delegating the corresponding `MGLMapViewDelegate` methods through the `NavigationMapView`→`RouteMapViewController`→`NavigationViewController` and then expose it publicly in `NavigationViewControllerDelegate`. See #498

**Comment by troyibm** [comment]
After looking at #498 and trying to understand what you are telling me @frederoni I think I'd have to change Mapbox code in order to be able to provide overrides for `regionWillChangeAnimated` and `regionDidChangeAnimated`.  The way the Mapbox code is now, there is no `NavigationViewControllerDelegate` functions to override.  

Note, setting the mapView's delegate in 0.6.0 didn't cause a crash.  (I realize that was a long time ago and things change, so it is just an fyi).

Are you suggesting that I fork this code and make the changes similar to what is in #498 if I need to override the MGLMapViewDelegate functions?

I guess I could do that, but surely don't want to.  😄 
Could I transition this github issue to be a request to add this ability to Mapbox??

**Comment by frederoni** [comment]
> Could I transition this github issue to be a request to add this ability to Mapbox??

👍 

Closing in favor of #685
