### ISSUE TITLE
Crash after reroute

### ISSUE THREAD

**Issue by AFcgi** [mapbox/mapbox-navigation-ios#676]
I have a crash during rerouting and their UI update. The update of the tableView isn't correct. At beginning I have 11 maneuver, after reroute it's 9 by 5 deletes and 5 inserts. It crashes because it lacks 2 rows. But this 2 maneuver I have already completed before reroute the navigation.

**Comment by frederoni** [comment]
Is this during automatic rerouting or do you set the `NavigationViewController`’s `route` manually?

**Comment by AFcgi** [comment]
@frederoni I set the `NavigationViewController`’s `route` manually.

**Comment by frederoni** [comment]
Fixed in #677

**Comment by AFcgi** [comment]
The fix solve the issue.
