### ISSUE TITLE
Can't find or build MapboxDirections.framework - Xcode 9 - Swift 4 - Carthage 0.25.0

### ISSUE THREAD

**Issue by addzo** [mapbox/mapbox-navigation-ios#680]
Hello.
I'm running Xcode 9 (GM), Swift 4, and Carthage 0.25.0.
I followed the directions on https://github.com/mapbox/mapbox-navigation-ios and it does not find the framework or build the framework.

I tried building all the projects and searched for the .framework on disk and it does not exist. 
<img width="262" alt="screen shot 2017-10-02 at 4 18 22 pm" src="https://user-images.githubusercontent.com/168576/31102337-de1a13a2-a78e-11e7-8b9b-ebc2693b32d3.png">

Does that framework get pulled from Carthage?
Does it get built in the project?

Thanks

**Comment by frederoni** [comment]
> Does that framework get pulled from Carthage?

Yes
> Does it get built in the project?

No

What did Carthage output after running `carthage bootstrap --platform ios`?

**Comment by addzo** [comment]
Ah.  Well that is interesting:

$ carthage bootstrap --platform ios
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Checking out Solar at "5ce2ca7baaa82b1abb0467642ae237faf674b645"
*** Checking out SDWebImage at "4.1.0"
*** Checking out ios-snapshot-test-case at "2.1.4"
*** Checking out Polyline at "v4.1.1"
*** Checking out osrm-text-instructions.swift at "v0.3.5"
*** Checking out MapboxDirections.swift at "v0.10.6"
*** Checking out mapbox-telemetry-ios at "v0.2.11"
*** Checking out Pulley at "1.4"
*** Checking out aws-sdk-ios at "2.6.0"
*** xcodebuild output can be found in /var/folders/6h/gjnb3qpj4zs9h1jtzf73b6640000gn/T/carthage-xcodebuild.3slBUw.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/brep/Sandbox/mapbox/mapbox-navigation-ios/Carthage/Checkouts/aws-sdk-ios/AWSiOSSDKv2.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by frederoni** [comment]
Please verify your Command Line Tools under Xcode→Preferences→Locations.
Should look something like this:
<img src="https://user-images.githubusercontent.com/764476/31103264-48db81d4-a7d6-11e7-96a0-d98019359f36.png" width=400>

**Comment by addzo** [comment]
OK.  That did the trick.  Didn't even think of that.
Thank you for that.
