### ISSUE TITLE
Confusing/Incorrect behaviour when giving directions with small distances

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#681]
v0.8.0

When using the default UI, it wrongly suggests turns in zero meters when they are in 10-15 meters away. This can cause confusion when driving within the city.

My suggestion would be to not round the distance if whole current instruction distance it's less than 25 meters, and round every 5-10 meters.

This direction is actually 11 meters, but it's displayed as 0 meters
![image](https://user-images.githubusercontent.com/4553825/31124917-be257e16-a846-11e7-8035-63952f1578e1.png)

Same turn on a different UI:
![image](https://user-images.githubusercontent.com/4553825/31125018-220beb40-a847-11e7-83b0-f407f88f693b.png)

**Comment by frederoni** [comment]
Thanks for the report. 5 meters make sense for distances shorter than 25 meters.

Fixed in #682
