### ISSUE TITLE
Control simulated speed

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#694]
Right now using real world values, it's a little too slow. Can we have a multiplier? Maybe keyboard shortcuts for toggling the speed too?

/cc @frederoni

**Comment by TCOA** [comment]
It would be GREAT to speed this up - testing multi-features from various points (routeAlerts that I have built in) gets really  S L O W  when I have to do a 2-3 mile test.

If we had a way to give a speed for a given segment, it would really help (I could go 'slow' at first, until the first triggers are working well, then speed those up while keeping the next development segment in the 'slow' mode - then keep that rolling through until all the steps were 'fast')

This would save me several hours a week just on waiting time!
