### ISSUE TITLE
fatal error: Array index is out of range

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#695]
using 0.8.2
![snip20171009_14](https://user-images.githubusercontent.com/10751092/31359407-7cc28b58-ad0f-11e7-9a85-a14e9f168fac.png)
![snip20171009_15](https://user-images.githubusercontent.com/10751092/31359406-7cc203c2-ad0f-11e7-9432-3ca387921cd3.png)
![snip20171009_16](https://user-images.githubusercontent.com/10751092/31359408-7cc325c2-ad0f-11e7-8f00-a81231650787.png)

**Comment by zijiazhai** [comment]
![snip20171012_19](https://user-images.githubusercontent.com/10751092/31524189-a5d91780-af7d-11e7-83ad-88132b28f76e.png)
![snip20171012_20](https://user-images.githubusercontent.com/10751092/31524190-a78cbd5c-af7d-11e7-949c-4f56489c39a0.png)
In my situation, sometimes it still crash after I updated to 0.8.3.
it will not crash after a did this:  
replace
let coordsForLeg = coordinates[previousLegCongestionIndex..<previousLegCongestionIndex + legCongestion.count]  
to 
let coordsForLeg = coordinates[previousLegCongestionIndex..<previousLegCongestionIndex + legCongestion.count + 1]
but I want to know, does it have any other Bad influences to my code after I removed + 1.
@bsudekum

**Comment by bsudekum** [comment]
@zijiazhai unfortunately this fix did not make it into 0.8.3. It will be included in the next release.
