### ISSUE TITLE
Always consider a maneuver as complete if distanceRemaining = 0

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#698]
There are cases, particularly with roundabouts in Europe and tight sequences of turns, where the geometry of a maneuver might not match the actual path a car takes. 

For example, in the following case, the in-bearing and out-bearing of the `enter roundabout` maneuver would be `0` and `90` respectively, but the location bearings would never exceed 15-20° if the driver "cut" the corners.

<img src="https://user-images.githubusercontent.com/664805/31362560-fdbb7fbe-ad0d-11e7-9f92-0925f684694a.png" width="150">

The turn would never be considered complete, and the snapped location would get stuck before jumping ahead to the next maneuver just before rerouting.

cc @bsudekum @cammace

**Comment by ericrwolfe** [comment]
Here's an example with a few roundabouts as well as a bonus super long tunnel: https://gist.github.com/ericrwolfe/b9c4665e7b1ef24d1520ab2147f96347

![image](https://user-images.githubusercontent.com/664805/31363787-aa143344-ad15-11e7-899f-d0712fb286db.png)

**Comment by bsudekum** [comment]
I think doing this sparingly for particular cases makes sense. However, doing this in all cases/maneuver types seems like a regression.

**Comment by ericrwolfe** [comment]
@bsudekum to your point, doing this for a traditional 90° right or left turn would cause the completion announcement to happen early. 

How do we do this without hard coding maneuver types?
