### ISSUE TITLE
 implement marker info click action

### ISSUE THREAD

**Issue by ItsMeMIHIR** [mapbox/mapbox-navigation-ios#700]
please tell me how to implement marker info click listener in Swift.
Actually i  want data clicked marker

**Comment by JThramer** [comment]
Hello @ItsMeMIHIR, It sounds like you're looking for a method that is called when an annotation is selected. Have a look at [-mapView:didSelectAnnotation:](https://www.mapbox.com/ios-sdk/api/3.6.4/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didSelectAnnotation:) and [-mapView:didSelectAnnotationView:](https://www.mapbox.com/ios-sdk/api/3.6.4/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didSelectAnnotationView:) in `MGLMapViewDelegate`.

In your delegate method, you can then test for the type of your `MGLAnnotation` or `MGLAnnotationView`.

Does this help?

**Comment by bsudekum** [comment]
Going to close this out. @ItsMeMIHIR, if you have more questions regarding the iOS SDK, please contact support@mapbox.com.
