### ISSUE TITLE
UI Componentization

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#701]
# Abstract
In Developer-focused SDK's, it's often desirable to offer UI components in a piecemeal fashion, rather then an all-or-nothing approach. The idea behind this is that it may be desirable for a consumer to add/extend a "Maneuver Symbol View", or just the "Maneuver Carousel", instead of being forced to make the choice of either using the stock UI, or rolling their own. We should consider this in our SDK.

# Techical Considerations:
It may be desirable to embed a UI framework within the navigation framework, as this offers us a couple of advantages.
1. This helps out with IBDesignable/IBInspectable by directing the agent to build only the UI framework, not the whole navigation framework. This saves on compile time.
2. By offering UI components as a framework, you can package any resources (images, etc) along with the framework, allowing for a lighter-weight import.

CC @bsudekum @1ec5 @frederoni @ericrwolfe

**Comment by JThramer** [comment]
Also notifying @willwhite because oops.

**Comment by JThramer** [comment]
Mothballed for now to focus on feedback work, Current work in 861ba71

**Comment by 1ec5** [comment]
Looks like we’re tracking the same work in #645.

**Comment by JThramer** [comment]
Closing as duplicate.
