### ISSUE TITLE
Deal with GPS noise

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#71]
https://github.com/mapbox/MapboxNavigation.swift/pull/57 is a good first step but we need to think more about cleaning out bad GPS noise. Not only should we be snapping locations harder, bearings should be snapped if they are within x degrees of the expected heading.

/cc @frederoni @1ec5

**Comment by 1ec5** [comment]
If you have access to the location manager, you can configure the [`headingFilter`](https://developer.apple.com/reference/corelocation/cllocationmanager/1620550-headingfilter).

**Comment by 1ec5** [comment]
Do you have known instances of the heading being incorrect? Note that there’s a difference between heading and course:

* Heading comes from the magnetometer. It can be filtered per https://github.com/mapbox/MapboxNavigation.swift/issues/71#issuecomment-285827366. We likely don’t have any problems with heading noise.
* Course comes from GPS readings. Noise could be a problem with course.

**Comment by 1ec5** [comment]
Closing in favor of #381, which I think gets to the heart of the issue.
