### ISSUE TITLE
v0.9.0 or v1.0.0 release?

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#711]
We have a few large and/or breaking changes coming down the line between [custom course tracking](https://github.com/mapbox/mapbox-navigation-ios/pull/402) and [voice instructions from the server](https://github.com/mapbox/mapbox-navigation-ios/pull/614). How do we want to go about the next release? People who rely solely on MapboxCoreNavigation or `AlertLevel`s at all will require a solid refactor.

/cc @frederoni @1ec5 @JThramer @ericrwolfe @Sealos

**Comment by ericrwolfe** [comment]
My vote is for 1.0 with server-side voice instructions.

**Comment by 1ec5** [comment]
My vote is for v0.9.0. Being pre-1.0 gives us more flexibility to make breaking changes in the next few releases. There’s no expectation that we preserve backwards compatibility between v0.8.x and v0.9.0.

**Comment by Sealos** [comment]
I would go for a 0.9 release, which would imply possible breaking changes. However, I would appreciate it if we had a crash fix release with on the v0.8.x

**Comment by bsudekum** [comment]
@Sealos I think that's reasonable. I can look into putting out a release including https://github.com/mapbox/mapbox-navigation-ios/commit/41860934843653fd6f7402219e6bb179482f71bd today.

**Comment by 1ec5** [comment]
We’re going with v0.9.0 per #723.
