### ISSUE TITLE
Add voice instruction location and text to map in debug mode

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#715]

**Comment by roxic8** [comment]
Point origin = originPosition;
        Point destination = destinationPosition;

        // Pass in your Amazon Polly pool id for speech synthesis using Amazon Polly
        // Set to null to use the default Android speech synthesizer
        String awsPoolId = null;

        boolean simulateRoute = true;

        NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(origin)
                .destination(destination)
                .awsPoolId(awsPoolId)
                .shouldSimulateRoute(simulateRoute)
                .build();

        // Call this method with Context from within an Activity
        NavigationLauncher.startNavigation(MainActivity.this, options);
