### ISSUE TITLE
Value of type 'MGLMapView' has no member 'locationManager'

### ISSUE THREAD

**Issue by johnwallco** [mapbox/mapbox-navigation-ios#721]
I'm building custom navigation using MapboxCoreNavigation. It's based on the example project.

The line below works in the example project, but it's throwing an error in my project:

`mapView.locationManager(routeController.locationManager, didUpdateLocations: [location])`

The error is:

`Value of type 'MGLMapView' has no member 'locationManager'`

My pod dependencies are Mapbox iOS SDK version 3.6.4, MapboxCoreNavigation version 0.7.0 and MapboxDirections version 0.11.2.

**Comment by frederoni** [comment]
The fact the `MGLMapView` conforms to `CLLocationManagerDelegate` is not exposed publicly. To overcome that in our custom example, we use a category on MGLMapView located here:
https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/MGLMapView+CustomAdditions.h
https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/MGLMapView+CustomAdditions.m

**Comment by johnwallco** [comment]
Thanks, @frederoni.
