### ISSUE TITLE
landscape mode

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#726]
0.8.3  iphone SE
![img_0033](https://user-images.githubusercontent.com/10751092/31688988-a77589f0-b353-11e7-828c-1e9764595566.PNG)
Hope to see more improvement in the future

**Comment by zijiazhai** [comment]
![snip20171017_4](https://user-images.githubusercontent.com/10751092/31689443-0bbb6b2c-b355-11e7-8df3-29af3ec68d3c.png)
![snip20171017_5](https://user-images.githubusercontent.com/10751092/31689453-11948f92-b355-11e7-8b6c-c489ef25fdaf.png)

**Comment by bsudekum** [comment]
Landscape has been improved in v0.11.0-rc1.

**Comment by 1ec5** [comment]
Tracking further improvements in #1139.
