### ISSUE TITLE
Initialising the NavigationViewController with custom style source crashes the application

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#735]
Hello, I'm trying to programmatically initialize the NavigationViewController without having the MGLMapboxAccessToken in the application plist. 

Once the NavigationViewController is presented with the custom style:
![img_0007](https://user-images.githubusercontent.com/4553825/31774225-7379be80-b4e5-11e7-9e61-62891686d2b3.PNG)

The application promptly crashes with:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: You must provide a Mapbox API access token for Mapbox tile sources
```

We're setting the styleURL in 2 places:

```swift
let directionsService = Directions(accessToken: <Key>)

let syles = [DefaultStyle()]
let navigationViewController = NavigationViewController(for: route, directions: directionsService, styles: styles, locationManager: self.locationManager())
navigationViewController.mapView?.styleURL = <CustomStyleURL>
```

And creating a custom DayStyle

```swift
class DefaultStyle: DayStyle {
    required init() {
        super.init()
        mapStyleURL = <CustomStyleURL>
   }
}
```

The same does not occur with the MGLMapView. Any help would be greatly appreciated.

**Comment by bsudekum** [comment]
> Hello, I'm trying to programmatically initialize the NavigationViewController without having the MGLMapboxAccessToken in the application plist.

@Sealos can you say more about why you're doing this?

**Comment by Sealos** [comment]
Our application doesn't use Mapbox styles, and everywhere else we set the style URL to our custom one. We do however use the Mapbox Directions service.

This changes the statistics on the Mapbox token usage. For example, we're getting a lot monthly active users than the amount of users that use directions requests. This is not consistent with our usage of the Mapbox service since we only use it for the directions, which is giving us an inconsistent balance of active users that only use the direct service.

**Comment by frederoni** [comment]
Can you include the stack trace you get when this crash occurs?

**Comment by Sealos** [comment]
I'm not getting any stack trace out of this. I'll try to upload a sample project tomorrow.

**Comment by 1ec5** [comment]
> Our application doesn't use Mapbox styles

Does your custom style use Mapbox-hosted sources such as the Mapbox Streets source, by any chance? Use of these sources also requires an access token.

**Comment by 1ec5** [comment]
Apparently even if the custom style avoids using Mapbox-hosted sources, the navigation SDK forces it to anyways in order to power the current road name label:

https://github.com/mapbox/mapbox-navigation-ios/blob/685e9fc2ced15cfa21190610d1ecfc00248c4edb/MapboxNavigation/RouteMapViewController.swift#L673-L678

Instead of too-helpfully adding this source to the style, RouteMapViewController should ask its delegate for a source identifier and source layer identifier that would provide the data needed for this feature. In the meantime, we should remove this special case. Originally we put it in with the reasoning that a satellite-only style could still benefit from a current road name label, but that’s quite an edge case and not worth this bug.

/cc @bsudekum

**Comment by 1ec5** [comment]
I guess we could also just conditionalize the code above on whether `MGLAccountManager.accessToken` is `nil`.

**Comment by 1ec5** [comment]
> I guess we could also just conditionalize the code above on whether `MGLAccountManager.accessToken` is `nil`.

#1183 hides the current road name label and avoids force-adding the Mapbox Streets source to the style if no access token is provided. After this fix, the only reason you’d run into this crash would be if your style somehow makes use of a Mapbox-hosted vector or raster tile source.

**Comment by Sealos** [comment]
Thanks!, I'll try this out.

**Comment by 1ec5** [comment]
#1183 fixes the issue that affects anyone using a custom, non–Mapbox Streets–based style. If you continue to encounter this particular crash, please ensure that your style isn’t making use of any Mapbox-hosted tile sources. Please reopen this issue if this particular crash (with the same error message) appears and your style doesn’t refer to any Mapbox-hosted tile sources. Thanks!
