### ISSUE TITLE
Portuguese [BR] localization

### ISSUE THREAD

**Issue by gloffreda** [mapbox/mapbox-navigation-ios#737]
Hi there
What is the plan to localize into pt-BR ?
I'm working on Transifex to help and just finished OSRM translation.
I really need to implement it before launching and If I can do more to speed it up I will be glad to help.

**Comment by frederoni** [comment]
This is being added as part of https://github.com/mapbox/mapbox-navigation-ios/pull/744

**Comment by 1ec5** [comment]
#744 landed.

**Comment by 1ec5** [comment]
> I'm working on Transifex to help and just finished OSRM translation.

Project-OSRM/osrm-text-instructions#189 pulls the instruction translations into OSRM Text Instructions.
