### ISSUE TITLE
Voice instructions not working on real device

### ISSUE THREAD

**Issue by johnwallco** [mapbox/mapbox-navigation-ios#742]
Voice instructions work on an emulator, but not on a real device.

I've tried doing `speechSynth.speak()` on the main thread, but that didn't make a difference.

I'm sorry this is so vague, but is there any reason why spoken instructions would work on an emulator, but not on a real device?

**Comment by frederoni** [comment]
Can you give some more details? What version of the Navigation SDK are you on? What language is set in your iOS settings? Background, foreground or both? Do you use MapboxCoreNavigation or MapboxNavigation?

**Comment by johnwallco** [comment]
Sure, @frederoni. 

I'm using MapboxCoreNavigation v0.8.3 and Mapbox iOS SDK v3.6. I'm not using MapboxNavigation.

English (U.S.) is my iOS language. 

It's not working in either background or foreground.

**Comment by johnwallco** [comment]
It helps to not have the phone on silent. I'm dumb.
