### ISSUE TITLE
Traffic in Brazil

### ISSUE THREAD

**Issue by gloffreda** [mapbox/mapbox-navigation-ios#748]
Hi there

I've noticed that traffic feature outside US has none or very poor quality. Which I guess is due to lack of users.
To workaround it and still having the others very good stuffs of Mapbox, is there a way to load traffic from other source ? For example, Google API ?
Thanks

**Comment by 1ec5** [comment]
Hi @gloffreda, which country is this, and can you give specific examples of poor traffic data? Traffic data is outside the scope of this repository, but we can pass along your feedback to the traffic team.

> is there a way to load traffic from other source ? For example, Google API ?

This probably isn’t possible for technical reasons or due to Google’s terms of service.

**Comment by gloffreda** [comment]
Hi @1ec5 
This is for Brazil, and by my tests it isn't taken any traffic information when I center the map on São Paulo for example. I'm sure there is a lot of traffic and looking on Waze or Google Maps traffic is there.

**Comment by 1ec5** [comment]
According to [this documentation](https://www.mapbox.com/api-documentation/pages/traffic-countries.html), we don’t currently support traffic in Brazil. Please keep an eye on that page to find out when we enable traffic there.
