### ISSUE TITLE
Make distance more prominent in turn banner

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#75]
#56 stuffed the distance under the maneuver icon and gave the road name top billing in the turn banner, like Google Maps and unlike Apple Maps. This is a usability regression: a driver glances periodically at their phone primarily to gauge the ever-changing distance. It’s less urgent to inform the driver that the upcoming road still has the same name as it did a moment ago. After all, if you know _what_ maneuver to perform (based on the icon) and _when_ to perform it (based on the distance), the road name becomes inessential, mostly there for reassurance.

We should reconsider the layout of the turn banner. The distance should be a the heading (larger, bolder) and the road name should be a subheading (smaller, fainter). By setting the road name in a somewhat smaller font, we’d also have more room for longer street names without resorting to autoshrinking. We’d also be able to enlarge the maneuver icon.

As an additional optimization, we could shrink the distance and enlarge the road name as the user approaches the junction. At that point (and no sooner), the distance becomes unimportant and it often becomes more important to distinguish between multiple streets meeting at the junction.

/cc @katmeng @bsudekum @frederoni @cammace

**Comment by 1ec5** [comment]
As discussed in #74, the proposed layout would offer us a good solution for the case where the upcoming road has no name or destination: there is always a distance, so we’ll always display the same information in the same places where available, without shuffling things around.

**Comment by frederoni** [comment]
This happened in #217 and other PRs.
