### ISSUE TITLE
assertion failed:

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#752]
hi guys, I am using 0.8.3.
every time, I navigate to Little Rock, AR from chicago, the app got crash.
assertion failed: Invalid data: file /Users/cai_ios_dev_1/Desktop/cognitiveai_carloudy /Pods/MapboxDirections.swift/MapboxDirections/MBDirections.swift, line 205

**Comment by bsudekum** [comment]
This implies your response from the directions api is malformed: https://github.com/mapbox/MapboxDirections.swift/blob/master/MapboxDirections/MBDirections.swift#L205

@zijiazhai can you say a little more about your setup? Are you using `NavigationRouteOptions()` to make your request?

**Comment by zijiazhai** [comment]
![snip20171024_1](https://user-images.githubusercontent.com/10751092/31960196-98d172f6-b8bc-11e7-80f7-395bef377f0b.png)

**Comment by zijiazhai** [comment]
now it works again, I did not change any code.
