### ISSUE TITLE
Catalan road abbreviations are miscapitalized

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#763]
The Catalan localization’s [abbreviations file](https://github.com/mapbox/mapbox-navigation-ios/blob/d9d7d6e9a2f2f6e6ddb4ab776801ff6d10a45197/MapboxNavigation/Resources/ca.lproj/Abbreviations.csv.plist) capitalizes the first letter of each spelled-out word, which prevents `String.abbreviated(by:)` from finding the abbreviation:

https://github.com/mapbox/mapbox-navigation-ios/blob/bf1c7aa5d17efbc06a3055d6deeff27d28376baf/MapboxNavigation/Abbreviations.swift#L23

[One of the Lithuanian abbreviations](https://github.com/mapbox/mapbox-navigation-ios/blob/808760840aa511866535ee72b61c240c85ade1d6/MapboxNavigation/Resources/lt.lproj/Abbreviations.plist#L7) faces the same problem.

/cc @frederoni

**Comment by 1ec5** [comment]
The left side of each line is expected to be lowercased; the right side is expected to begin with a capital letter.

**Comment by 1ec5** [comment]
I’ve corrected the Catalan and Lithianian localizations to use the correct case.

**Comment by frederoni** [comment]
Fixed  in #765
