### ISSUE TITLE
IB Designables Failed to render and update auto layout status for MapViewController

### ISSUE THREAD

**Issue by DigitalLeaves** [mapbox/mapbox-navigation-ios#764]
As issue https://github.com/mapbox/mapbox-navigation-ios/issues/210 seems to still be happening, I would like to open a new ticket so this can be addressed. It's a real nuisance. 

Basically, setting a UIView on a IB's storyboard as a MGLMapView ruins the autolayout and rendering features of IB. A rendering error appears and from that moment, changes in view hierarchy, layout or properties from the views are not updated or refreshed in IB anymore. That certainly prevents you from building any UI including a MapBox view.

There's a temporary patch that involves removing the MGLMapView class definition from the view in storyboard. As soon as you do that, the rendering error is gone and views start refreshing again. You can then do your views/layout/properties changes and then set the view as a MGLMapView again. However, this is certainly a PITA, and not a long-term solution.

Hope you guys can please address this. Best regards.

**Comment by Jackhammer42** [comment]
I am seeing this issue too, since i updated to xcode 9.

**Comment by frederoni** [comment]
This issue seems to be ticketed in the correct repo already https://github.com/mapbox/mapbox-gl-native/issues/10072
Does the workaround proposed in https://github.com/mapbox/mapbox-gl-native/issues/10072#issuecomment-332288922 prevent the IB agent from crashing?

**Comment by Jackhammer42** [comment]
Yes, subclassing `MGLMapView` seems to work. But i had to kill all "Interface Builder Cocoa Touch Tool" processes and restart xcode to make the error go away. Thanks!

**Comment by friedbunny** [comment]
Thanks for the reports — let’s track this upstream in https://github.com/mapbox/mapbox-gl-native/issues/10072.
