### ISSUE TITLE
SecondaryText is clipped early

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#796]
On an iPhone SE:

![image](https://user-images.githubusercontent.com/1058624/32420008-11cf29ac-c239-11e7-8872-3b8a676b1040.png)

**Comment by frederoni** [comment]
I can't seem to reproduce this.
<img src="https://user-images.githubusercontent.com/764476/32435845-7aa7a0d6-c2e2-11e7-9aa0-1df3db0ca9c3.png" width=200><img src="https://user-images.githubusercontent.com/764476/32435848-7c62e2fa-c2e2-11e7-88e6-f97b51ad2473.png" width=200><img src="https://user-images.githubusercontent.com/764476/32435862-86c2d8ea-c2e2-11e7-8c87-2b6f534efa0b.png" width=200>

Are you on latest master? Do you have the exact route?

**Comment by frederoni** [comment]
Scratch that 👆, I was able to reproduce. Fixed in #797
