### ISSUE TITLE
Show highway direction next to highway shield

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#803]
If a direction is available on the ref/destination ref, e.g. "I 80 East", then only replace the ref code portion with the inline shield and leave the direction in tact.

![image](https://user-images.githubusercontent.com/664805/32466051-a10f4ce8-c313-11e7-922e-643ae2b378de.png)

cc @frederoni

**Comment by 1ec5** [comment]
If it wouldn’t complicate the code too much, it would be a good idea to also preserve “route banner” text, so “<img src="https://upload.wikimedia.org/wikipedia/commons/5/58/US_50.svg" height="20" alt="US 50"> Business West” for `US 50 Business West`. (I think the route banner currently prevents the SDK from displaying any shield.)

**Comment by frederoni** [comment]
The direction part of this ticket has been implemented as part of #785
