### ISSUE TITLE
Route preview view controller

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#808]
This library should vend a view controller that displays a preview of a route (and potentially any alternative routes). There would be controls for beginning the route (pushing NavigationViewController onto the stack), as well as an option to view a static list of steps along the route.

RoutePreviewViewController would serve as an additional, optional entry point to the existing NavigationViewController. The user normally expects to be able to see the route visualized or summarized somehow before committing to it by beginning turn-by-turn navigation. In a navigation-focused application, the main view controller may already contain a NavigationMapView that can display the route, so it RoutePreviewViewController may not be strictly necessary. However, in a non-navigation-focused application, such a UI may not already be present, so RoutePreviewViewController will make it easier for developers to complete that part of the user experience.

/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
I think this is a huge rabbit hole and time sink that really doesn't help developers all that much in the end. There are a few basic functions a developer needs here:

* show the route
  * congestion, alterates, etc
* Fit to bounds
* Preview steps

Soon, we have all these pieces exposed (missing: https://github.com/mapbox/mapbox-navigation-ios/pull/785). Looking at google and apple, we'd need to expose all sorts of elements to do this right. This would mean a search view to edit the start location:

<img src="https://user-images.githubusercontent.com/1058624/32554849-260c11a0-c469-11e7-8c90-bebefe94036d.png" width="30%" />

<img src="https://user-images.githubusercontent.com/1058624/32554879-390c5044-c469-11e7-829e-66dc59292f6e.png" width="30%" />

In my opinion we should make the example app implement this in a concise manner and keep focused on more core features.

**Comment by 1ec5** [comment]
> However, in a non-navigation-focused application, such a UI may not already be present, so RoutePreviewViewController will make it easier for developers to complete that part of the user experience.

I guess I was envisioning something like a store locator application, where it would be unnecessary to provide a search/waypoint interface, but a drop-in interface for a route confirmation screen would still be convenient. I suppose we could reimplement that view controller as part of [the store locator kit](https://github.com/mapbox/store-locator-ios/), though.

**Comment by 1ec5** [comment]
> I think this is a huge rabbit hole and time sink that really doesn't help developers all that much in the end.

It’s important to recognize that the preview view controller would be an optional entry point. A developer who needs a more custom confirmation screen or no confirmation screen at all can still build their own UI and push NavigationViewController onto the stack directly.

Moreover, even if the developer needs a custom confirmation screen, they can still embed RoutePreviewViewController in their own view controller via a container view.

As I see it, we’ve already headed down this rabbit hole by trying to cram view controller functionality into NavigationMapView. Implementing RoutePreviewViewController will allow us to dig ourselves out of the hole.

**Comment by 1ec5** [comment]
Vending a preview view controller would also make it possible for us to track whether the selected route is a primary or alternative route. Currently, all the SDK tracks is the original request and the selected route, but not that route’s position within the response.

**Comment by 1ec5** [comment]
A prerequisite for this feature would be the ability to inject a NavigationMapView into a NavigationViewController. That would be desirable even on its own as a way to guarantee a seamless transition between an application-defined preview map view controller and NavigationViewController.

/cc @mapbox/straightaway-ios-team

**Comment by 1ec5** [comment]
> A prerequisite for this feature would be the ability to inject a NavigationMapView into a NavigationViewController. That would be desirable even on its own as a way to guarantee a seamless transition between an application-defined preview map view controller and NavigationViewController.

#3165

**Comment by 1ec5** [comment]
#3186 has landed, making it possible for the application to implement a route preview view controller, then hand off its map view to NavigationViewController when starting a trip. The route preview view controller would ideally accept the map view back when ending the trip.
