### ISSUE TITLE
Rename navigationMapView(_:didTap:)

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#809]
`NavigationMapViewDelegate.navigationMapView(_:didTap:)` is too tightly coupled to a specific gesture (a tap). In the future, it may be possible to select a route with some other gesture as well. For consistency with MGLMapViewDelegate methods, let’s rename it to `navigationMapView(_:didSelect:)` in Swift (`-navigationMapView:didSelectRoute:)` in Objective-C).

For completeness, we could also pair the method with a `navigationMapView(_:didDeselect:)` method that gets called right before `navigationMapView(_:didSelect:)`.

/cc @bsudekum

**Comment by JThramer** [comment]
Willfix as part of #806, as I'm going to be working in this area anyway, adding relevant delegate methods for waypoint removal.

**Comment by JThramer** [comment]
Implemented in #806.
