### ISSUE TITLE
Continuous update of route on NavigationMapView

### ISSUE THREAD

**Issue by apascual** [mapbox/mapbox-navigation-ios#810]
Hi, I'd like to know what is the correct way of updating the route in a custom `NavigationMapView` without `NavigationViewController`.

Our project is similar to what is described on the iOS documentation (https://www.mapbox.com/help/ios-navigation-sdk/), we have some kind of preview of the route and the user can go into navigation mode (or not).

![screen shot 2017-11-08 at 09 37 32](https://user-images.githubusercontent.com/3491658/32539282-312d7808-c469-11e7-86a8-cbb8a1ba19b5.png)

The thing is that **now I am requesting new directions and updating the route every time that there is a new location event**, and I have the feeling that this is not the proper way of doing it.

What is the appropriate way? Only update the route if the location changes significatively? Or maybe only after certain time span? Or a combination of both? Thanks.

**Comment by bsudekum** [comment]
Hi @apascual,

You can set [`checkForFasterRouteInBackground`](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L125) to true to do this for you. To keep battery life up and costs down, we only do the check for a faster route every 2 minutes and only if the route is longer than 600 seconds. If the new route is significantly faster, we update the route (> 10% faster). 

Updating the ETA in the background is something that is on our roadmap but not yet implemented.

**Comment by frederoni** [comment]
Is the intention to remove the part of the route line that is behind you? If that's the case, you can use [Turf-swift](https://github.com/mapbox/turf-swift) -> https://github.com/mapbox/turf-swift/blob/master/Turf/Turf.swift#L178 to slice the polyline from your current location to the end of the route.

**Comment by apascual** [comment]
@frederoni Thank you, I think that is going to be useful.

What about rerouting? I think there must be a way of getting all the `RouteController` functionality to be applied to a custom `NavigationMapView`.

**Comment by frederoni** [comment]
The `RouteController` will handle reroute for you. You just have to listen for a `RouteControllerDidReroute` notification _or_ implement `RouteControllerDelegate.routeController(_:didRerouteAlong:)` delegate method and redraw your route accordingly.

**Comment by apascual** [comment]
@frederoni Thank you, I tried your approach.

Please have a look to these videos:

- This one uses a `RouteController` and updates the route displayed every time `RouteControllerDelegate.routeController(_:didRerouteAlong:)` is called. https://streamable.com/37en9

- And on this one I get location updates directly on my own controller and re-create/re-display the route every time. https://streamable.com/buzzg

Obviously the second one looks much better, specially when the user is still "on the route". Any chance on getting this level of route-updates with the current `RouteController` (maybe the correct wording here would be path-updates)?

If not, maybe it won't be such a bad idea to have something like a `NavigationRouteController`extending the current `RouteController` and providing more accurate updates on what should be displayed on the map according to the user's location.

**Comment by frederoni** [comment]
> Any chance on getting this level of route-updates with the current RouteController?

Yes, you need to snap your location updates to the closest point on the line and then slice the `[CLLocationCoordinate2D]` that is being drawn as the route line. The location updates are too inaccurate to follow a line without snapping and `NavigationMapView/MGLMapView` doesn't snap by default. In your case, you're using the default user puck from `MGLMapView` which doesn't expose a way to modify the locations but can workaround that by adding a category on `MGLMapView` similar to https://github.com/mapbox/mapbox-navigation-ios/blob/master/Examples/Swift/MGLMapView+CustomAdditions.h

**Comment by apascual** [comment]
@frederoni Thanks, I'd really like to see that slicing integrated into `NavigationMapView/MGLMapView`.

What about the ETA and current distance to destination? Is there a way of getting them updated while the user moves or will only get updated after a re-routing?

**Comment by Jackyaung** [comment]
@frederoni Hi do you have example of how to do that? I am new to Mapbox, right now I am stuck the step to remove the line behind you. For example, if you walked to the place that the red arrow pointing to, I want to remove the line in the circle. 

![image](https://user-images.githubusercontent.com/16591529/114558409-f07b2200-9c6a-11eb-85cc-2d36360b1342.png)
