### ISSUE TITLE
Stick to chosen alternative route after rerouting

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#818]
Upon rerouting, RouteController should choose the route (possibly an alternative route) that’s most similar to the route the user began with.

Let’s say the user is going from San José, California, to Houston, Texas. The Directions API comes up with two routes, one using I-40 and the other using I-10. The user selects I-10 and starts the route. Before leaving San José, they take a small detour to fill up the tank. That’s enough to trigger a reroute, and RouteController dutifully reselects the default, fastest route, discarding any alternative routes that may’ve been requested:

https://github.com/mapbox/mapbox-navigation-ios/blob/64abd85990b62db04cdb2e240d7eab1fb50efba4/MapboxCoreNavigation/RouteController.swift#L720-L722

In Bakersfield, the navigation SDK ends up telling the user to turn onto I-40, despite the user’s original selection.

To determine route similarity, we could compare all the coordinates and sort by the number of shared coordinates. However, that brute-force approach would perform very poorly for longer routes, especially given that multiple rerouting attempts can occur in rapid succession. Instead, we can use the route legs’ descriptions (summaries) as proxies for similarity. Each description names the two most prominent roads along the route leg:

* If two routes between the same waypoints largely travel over the same roads, then it doesn’t really matter which route we choose automatically.
* If the routes travel over different roads, then we can sort the routes by the [Damerau–Levenshtein edit distance](https://github.com/modocache/MDCDamerauLevenshtein/) from the initial route leg description to the new route leg descriptions.

Note that multifaceted routing – shortest route versus fastest versus cheapest – is out of scope for this issue. This issue is only concerned with correctly persisting the user’s selection across rerouting attempts.

/cc @mapbox/navigation-ios

**Comment by hervouinc** [comment]
Up !

**Comment by hervouinc** [comment]
Hi @1ec5, could you please set the milestone for this issue ?
