### ISSUE TITLE
Add custom button to NavigationController

### ISSUE THREAD

**Issue by Ahmeddben** [mapbox/mapbox-navigation-ios#827]
Hi guys,

Need some help here. 

I have been following the tutorial found here: https://www.mapbox.com/help/ios-navigation-sdk/#add-minimal-navigation. I had on my Mapview few buttons that I would like to keep while the person is driving and getting navigation instructions. How can I add the buttons already on my MapView controller to the navigation controller?

Thanks!

**Comment by frederoni** [comment]
We currently don't expose a convenient way to add custom controls on top of the NavigationViewController. However, you can always reach into `NavigationViewController.view` or the `mapView` to add your own controls.

Tracking this feature here #830
