### ISSUE TITLE
Expand Style documentation with links + examples

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#832]
Right now, our documentation for [`Style`](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.9.0/Classes/Style.html) is brief. Ideally, the styling section of our documentation should contain or link out to everything a developer needs to custom style navigation for their app.

We should:
- [ ] Link out to the example project that [shows how to use custom styling](https://github.com/mapbox/mapbox-navigation-ios/blob/03bcff8991c75beda87afb6c7b640d44fb97c842/Examples/Swift/ViewController.swift#L274-L292).
- [ ] Link out to the documentation on [how to set custom start/end markers](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.9.0/Protocols/NavigationViewControllerDelegate.html#/s:FP16MapboxNavigation32NavigationViewControllerDelegate17navigationMapViewFTCSo10MGLMapView7viewForPSo13MGLAnnotation__GSqCSo17MGLAnnotationView_).

h/t to @ericdeveloper for the feedback.

cc @frederoni @bsudekum @JThramer

**Comment by bsudekum** [comment]
We should really just redo the readme, it's old.

/cc @colleenmcginnis

**Comment by ericrwolfe** [comment]
> We should really just redo the readme, it's old.

@bsudekum to be clear, this was referring to the Jazzy documentation hosted on Mapbox.com
