### ISSUE TITLE
Cannot create a custom subclass with Objective-C

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-navigation-ios#837]
I'm currently receiving the following error when attempting to create a custom subclass of one of the built-in style classes in Objective-C. The issue does not occur when creating a custom subclass of the same object in Swift:

Steps to reproduce:
1) Create a new `ViewController.m` file and import the Mapbox Navigation SDK for iOS.
2) Attempt to create a custom subclass, in this case of the `DayStyle` object.:
3) Observe error: `Cannot subclass a class that was declared with the 'objc_subclassing_restricted' attribute`.

![screenshot 2017-11-10 14 26 10](https://user-images.githubusercontent.com/10850812/32674929-1f3a3ecc-c623-11e7-9d2e-f4d724fa0d16.png)

cc @frederoni @bsudekum

**Comment by captainbarbosa** [comment]
It appears that [subclassing Swift classes in Objective-C is not possible](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/Migration.html) ☹️

**Comment by bsudekum** [comment]
Should we solve this though?
