### ISSUE TITLE
Add delegate method for overriding a voice announcement

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#846]
something like `voiceController.shouldSpeak(_ instruction:step:)`. If the developer returns a String, this string is said instead of the instruction for a step. We'll need to give the developer a `RouteStep` and also the `spokenVoiceIndex` here to allow them to figure out if they want to override this instruction.

/cc @ericrwolfe @ericdeveloper @1ec5

**Comment by 1ec5** [comment]
> We'll need to give the developer a `RouteStep` and also the `spokenVoiceIndex` here to allow them to figure out if they want to override this instruction.

Would passing in the current RouteProgress suffice?

**Comment by bsudekum** [comment]
Oh yep

**Comment by TCOA** [comment]
Could you please expand on this (is it available now? How to access?)

I really like the multiple waypoints (just what I need), though the spoken "You have arrived at your first destination" doesn't really work for us (prefer the standard "You have arrived at your destination" for our situation - the user knows they will continue after selecting the info in the Waypoint controller...)

If we can say what we want here, that would be really great!  (Of course, it will take a rework of all the software, but it should be more common to the release version so future mods should be simpler and worth the upfront effort to do it now)

**Comment by bsudekum** [comment]
@TCOA this is not available yet.
