### ISSUE TITLE
Navigation Arabic Support

### ISSUE THREAD

**Issue by engaliaaS** [mapbox/mapbox-navigation-ios#849]
Hello,
will you support Arabic localization in the navigation SDK?

**Comment by 1ec5** [comment]
Hi @engaliaaS, if you’re proficient in Arabic, please consider contributing to our open source translation efforts:

* [Mapbox Navigation SDK for iOS](https://www.transifex.com/mapbox/mapbox-navigation-ios/) includes user interface messages for various controls, such as the bottom bar and feedback screen, as well as the example applications.
* [OSRM Text Instructions](https://www.transifex.com/project-osrm/osrm-text-instructions/) powers written instructions in the Directions API and spoken instructions in the navigation SDK.
* [Mapbox GL Native](https://www.transifex.com/mapbox/mapbox-gl-native/) includes our iOS map SDK, specifically the interface messages for formatting distances or opting out of telemetry.

We’ll accept pull requests for the Arabic localizations of these projects once they near completion. Thank you for your interest in the navigation SDK.
