### ISSUE TITLE
Selecting routes without Tolls

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#855]
Hi,
I need a feature in this SDK like to select or get only that Routes which is not followed by Tolls/highway/ferry etc. possible terms.

**Comment by bsudekum** [comment]
This will be available once https://github.com/mapbox/MapboxDirections.swift/pull/180 is merged.

**Comment by ashishke2m** [comment]
How much time will it take approx?

**Comment by TCOA** [comment]
(related) Any way to get the amount (even estimated) of tolls for the route?  

Right now, we are making the assumption the per-mile cost we put in will cover them, but certainly it would be great to somehow be able to pull:

1) the fact that there is a toll road along the route and 

2) cost prior to starting the ride (so the decision could be made to select the non-toll route)

**Comment by ashishke2m** [comment]
Hi,
I need a feature in this SDK like to select or get only that Routes which **is or is not** followed by Tolls/highway/ferry etc. possible terms. 
I want a custom property to set it as we have for alternate possible routes.

**Comment by bsudekum** [comment]
This is now available in master and will be published in the next release. On your `NavigationRouteOptions` object you can set `options.roadClassesToAvoid = .toll` (or `.motorway` or `.ferry`).
