### ISSUE TITLE
Incorrect then banner

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#862]
![simulator screen shot - iphone 8 - 2017-11-16 at 17 38 17](https://user-images.githubusercontent.com/1058624/32925143-3b6b6f5e-caf5-11e7-842f-b62ffc6f89d4.png)

Does it seem a little early to be telling the user about this next step? I'm still on the ramp and have not yet entered 280.

/cc @frederoni @ericrwolfe

**Comment by 1ec5** [comment]
For what it’s worth, the southbound CA 85 ramp begins very soon after the on-ramp from De Anza Boulevard merges into I-280. A then instruction isn’t totally unreasonable, but it’s a borderline case I think.
