### ISSUE TITLE
NSMicrophoneUsageDescription

### ISSUE THREAD

**Issue by diegogarciar** [mapbox/mapbox-navigation-ios#866]
I Submitted my app to the App Store and received the following binary error.

This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

I checked my whole project and the only framework that requests user's microphone is this one. Maybe you should add a warning in the documentation that NSMicrophoneUsageDescription is needed in the info.plist.

**Comment by bsudekum** [comment]
Hey @diegogarciar,

We allow the mic to function to allow users to long press while giving feedback on their navigation experience. This way, they can give a little bit more information about the issue they are seeing. 

However, this option is by default [off](https://github.com/mapbox/mapbox-navigation-ios/blob/5eca88a1af26ec2dc09120d43e3d512374f8103d/MapboxNavigation/RouteMapViewController.swift#L84). I will look into whether just having the code path in the library requires developers to provide a `NSMicrophoneUsageDescription`.
