### ISSUE TITLE
To Get continuous Location Updates when user is actually traveling with Turn By Turn Navigation

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#867]
Is there any way to to Get  a **continuous Location Updates** when user is actually traveling with Turn By Turn Navigation using `NavigationMapviewController`

**Comment by frederoni** [comment]
The `RouteController` will post a notification each time the progress changes due to a location update, which means you can register an observer and grab the location from the notification’s userInfo.

```swift
NotificationCenter.default.addObserver(self, selector: #selector(progressDidChange(_:)), name: RouteControllerProgressDidChange, object: routeController)

func progressDidChange(_ notification: Notification) {
    let location = notification.userInfo![RouteControllerProgressDidChangeNotificationLocationKey] as! CLLocation
}
```

**Comment by ashishke2m** [comment]
Oh Ok, Great!!
As I also need a MapView Of current navigation controller, is that possible?

**Comment by frederoni** [comment]
Glad it helped. Yes, there's a `mapView` property on the `NavigationViewController`.

**Comment by ashishke2m** [comment]
Yes I got it!**Done**!!
