### ISSUE TITLE
How to use StepTableView for custom UI in App

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#868]
Hi, I want to implement step table view with a different design .is it possible?

**Comment by frederoni** [comment]
You can use UIAppearance to style the step table but we currently don't provide a way use your own custom cells or table view controller. What exactly do you want to change? Here's a snippet of how to style the various components in the step table view:

```swift
DistanceLabel.appearance(whenContainedInInstancesOf: [StepInstructionsView.self]).unitTextColor = .gray
DistanceLabel.appearance(whenContainedInInstancesOf: [StepInstructionsView.self]).valueTextColor = .darkGray
ManeuverView.appearance(whenContainedInInstancesOf: [StepInstructionsView.self]).secondaryColor = .darkGray
PrimaryLabel.appearance(whenContainedInInstancesOf: [StepInstructionsView.self]).normalTextColor = .darkGray
SecondaryLabel.appearance(whenContainedInInstancesOf: [StepInstructionsView.self]).normalTextColor = .gray
StepInstructionsView.appearance().backgroundColor = .clear
StepsBackgroundView.appearance().backgroundColor = .white
StepTableViewCell.appearance().backgroundColor = .white
```

**Comment by ashishke2m** [comment]
I want to make my own step view controller outside of the Turn by Turn Navigation view.
U can consider it in Preview screen of Route, I want to put a button and on Click of it Display Steps for the whole Route with Waypoints.

**Comment by frederoni** [comment]
Oh, ok. Not currently, but it should just be a matter of changing the access level on the `StepsViewController` to allow subclassing. Opened a PR in #869, when that lands, you can subclass StepsViewController and provide your own UITableViewDelegate and UITableViewDataSource.

**Comment by ashishke2m** [comment]
It is good to hear from you that it is already in process.But as I need it to add to my current Build so You have any other way to a use it ? as we used it before from Old SDK.

**Comment by frederoni** [comment]
You can pin the dependency on https://github.com/mapbox/mapbox-navigation-ios/commit/499a5ec4aa2a2c30f650151a8221fb213c8a4a62 or wait for the next release.
