### ISSUE TITLE
CocoaPods preflight tests fail for third-party PRs

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#87]
The CocoaPods preflight test on Bitrise is failing for PRs contributed from third-party developers on their own forks of the repository.

#54 added a CocoaPods step to the Bitrise workflow that tests whether the library can be installed via CocoaPods without errors. This step replaces [`BRANCH_NAME` placeholders](https://github.com/mapbox/MapboxNavigation.swift/blob/c1371f0d434a4a8272800c6ec1b1a42aa8296b5f/MapboxNavigationTests/CocoaPodsTest/PodInstall/Podfile#L7-L8) with the PR’s branch name but leaves the Git address in place, even if the branch lives on a fork.

You can see an example of this failure in #86.

/cc @frederoni @bsudekum

**Comment by frederoni** [comment]
Updated the workflow on Bitrise in order to support forks.

**Comment by frederoni** [comment]
Reopening because the git URL of the fork is still incorrect.

**Comment by LuAndreCast** [comment]
anyone know the correct URL?

**Comment by bsudekum** [comment]
We're no longer using branches.

**Comment by 1ec5** [comment]
This issue is still relevant. Any third-party contributor to this repository will run into the CocoaPods failure on CI, and they won’t be able to see why because Bitrise logs are hidden.

**Comment by bsudekum** [comment]
This has been fixed.

**Comment by 1ec5** [comment]
Specifically, this issue was fixed in #1115, as demonstrated by #1118.
