### ISSUE TITLE
Issues With Turf library

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#871]
I am always facing an issue with Turf when I am trying to Run an app on the device and then next try it in simulator or vice-versa. I am getting Below error

```
**dyld: Library not loaded: @rpath/Turf.framework/Turf
  Referenced from: /Users/sys/Library/Developer/CoreSimulator/Devices/ADD85805-B100-4EE6-B671-5CE4DE4634FC/data/Containers/Bundle/Application/EEC8FB3A-BD59-4395-8429-894E6625FDBD/XYZ.app/XYZ

  Reason: no suitable image found.  Did find:
	/Users/sys/Library/Developer/CoreSimulator/Devices/ADD85805-B100-4EE6-B671-5CE4DE4634FC/data/Containers/Bundle/Application/EEC8FB3A-BD59-4395-8429-894E6625FDBD/XYZ.app/Frameworks/Turf.framework/Turf: required code signature missing for '/Users/sys/Library/Developer/CoreSimulator/Devices/ADD85805-B100-4EE6-B671-5CE4DE4634FC/data/Containers/Bundle/Application/EEC8FB3A-BD59-4395-8429-894E6625FDBD/XYZ.app/Frameworks/Turf.framework/Turf'**
```

**Comment by frederoni** [comment]
Would it be correct to assume that you're using Carthage?
If so, please make sure you followed these steps  https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

The build phase must copy all underlying dependencies:
 
![screenshot 2017-11-21 10 04 21](https://user-images.githubusercontent.com/764476/33063674-6d1eb478-cea3-11e7-8acb-df5f5ed99d50.png)

**Comment by ashishke2m** [comment]
Hi, I am Using a CocoaPods Directly as You can see below lines:
  ```
**pod 'Mapbox-iOS-SDK', '~> 3.6'
  pod 'MapboxNavigation', '~> 0.10'
  pod 'MapboxGeocoder.swift', '~> 0.6**
```'

**Comment by frederoni** [comment]
Do you have `use_frameworks!` specified at the top of your Podfile? What version of Xcode are you using?

**Comment by ashishke2m** [comment]
![screen shot 2017-11-21 at 3 24 13 pm](https://user-images.githubusercontent.com/16642068/33065887-d0182ef2-cecf-11e7-9e4c-e9681a2eccaf.png)
I am Using Xcode 9.1 with swift 3.X

**Comment by frederoni** [comment]
It shouldn't try to codesign Turf. Do you get same error if you `pod install` or `pod update` again?
What if you try `pod deintegrate` then install again?

Also noticed that your target in the Podfile says `XYZ` but the error specifies a different target. I presume xyz is a placeholder?

**Comment by ashishke2m** [comment]
Yes XYZ is a placeholder. and error came when I updated a Pod file from version 6 to 8 of MapBoxNavigation.

**Comment by ashishke2m** [comment]
Ok I am trying pod deintegrate then install again.and let you know will find any issues.

**Comment by frederoni** [comment]
@ashishke2m any updates here?

**Comment by ashishke2m** [comment]
Hi,
I am still getting same error.

**Comment by michealbeatty** [comment]
I'm seeing this issue as well using CocoaPods. I don't know if cleaning the project helps or not because when I do I get an error message "No such module 'MapboxDirections'" and the build fails.

**Comment by ashishke2m** [comment]
Hi,
I solved this issues on temporary basis Using clean project and removed derived data.
But for a permanent solution, I updated all my provisioning profile and WWDC Developer Certificate in my keychain.
