### ISSUE TITLE
Navigation DidArrive At WayPooint/Destination not called

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#877]
Hi,
I am facing issues with `navigation view controller:didArriveAtWaypoint`, this method was called when the user arrives at any waypoint or destination as in the previous SDK but in currently released v0.10.1. this method is not called when user arrived at any waypoint or destination.I already assigned a delegate to `Navigationmapviewcontroller` .the name was NavigationDelegate in the previous Version.
This is the major issues which I found please let me know some updates on it ASAP.

**Comment by frederoni** [comment]
`navigationDelegate` was renamed to just `delegate`. Try setting the `delegate` and see if it works.

**Comment by ashishke2m** [comment]
I already renamed it to `delegate`.but it is not working as I just updated SDK with pre-released version v0.11.0-rc.1.But still, it is not calling a method for `navigationviewcontroller:didArriveAtWaypoint`.You can see my code SS.
![screen shot 2017-11-23 at 6 46 51 pm](https://user-images.githubusercontent.com/16642068/33174576-a32d95de-d07e-11e7-8d11-50616e5b3a97.png)

**Comment by ashishke2m** [comment]
I guess it is never satisfying below lines of code as i debug.
```
if routeProgress.currentLegProgress.userHasArrivedAtWaypoint {
            delegate?.navigationViewController?(self, didArriveAt: routeProgress.currentLegProgress.leg.destination)
        }
```
That is the reason is never called as i Tested other methods of deleagte that is **Cancel** and **DidReroute** it is working fine only **didArriveit is not working.**

Please Check it once and update it ASAP because it is important for SDK Users.

**Comment by ashishke2m** [comment]
We are eagerly waiting for your reply.

**Comment by TCOA** [comment]
although things have changed a lot (which does make updating the app a mess...), this hopefully will get you going......

    let center = NotificationCenter.default
    center.addObserver(forName: NSNotification.Name(rawValue: "RouteControllerProgressDidChange"), object: nil, queue: nil) {
                notification in
            let routeProgress = notification.userInfo![RouteControllerProgressDidChangeNotificationProgressKey] as! RouteProgress
            print("userHasArrivedAtWaypoint is ", routeProgress.currentLegProgress.userHasArrivedAtWaypoint)
     }

userHasArrivedAtWaypoint is triggering when the SPOKEN route of "You have arrived" is sent (though, sadly for the user that is driving, that seems to be sent several seconds before actually arriving, however, it is the point I need for notifying the other party of the arrival....)

(found this in NavigationViewController.swift under func didPassInstructionPoint(notification: NSNotification))

We used to have (not long ago....) a great system of "alertUserLevel" in routeProgress.currentLegProgress where we could get alerts on all the activities

                 0 = none
                 1 = depart
                 2 = after a maneuver
                 3 = 70 seconds out
                 4 = 15 seconds out
                 5 = arrive
                 
Not sure why that went away, but after building a lot of my code around it (and now having to change it all.....) - only having the spoken 'arrived' seriously changes the feature set.........  (other things like moving the buttons from the left to the right didn't help either..... - oh, well - that is what we have to live with when others develop the SDK! :)

**Comment by ashishke2m** [comment]
Hi,
I tried but this is not working.
```
let center = NotificationCenter.default
center.addObserver(forName: NSNotification.Name(rawValue: "RouteControllerProgressDidChange"), object: nil, queue: nil) {
            notification in
        let routeProgress = notification.userInfo![RouteControllerProgressDidChangeNotificationProgressKey] as! RouteProgress
        print("userHasArrivedAtWaypoint is ", routeProgress.currentLegProgress.userHasArrivedAtWaypoint)
 }
```
What i can do for this now its stuck my app progress.we want to purchase this sdk but first we want it in stable version which is not still exists.how we can go ahead.this is too bad to here like this SDK degrading its performance.

**Comment by frederoni** [comment]
@ashishke2m do you have more information about the route? How do you request the route? Is it automobile, cycling or walking?

Both the delegate and the notification approach seems to be working just fine in the example app:
```
userHasArrivedAtWaypoint is  false
didArriveAt: Junipero Serra Freeway
userHasArrivedAtWaypoint is  true
```

Would you mind sharing the relevant part of your code, including the `NavigationViewControllerDelegate.navigationViewController(_:didArriveAt:)` method?

**Comment by TCOA** [comment]
@frederoni, would you mind sharing the times you see on the 'didArriveAt'?

I'm getting (using simulated navigation) a spoken message of 'You have arrived at your destination' WAY ahead (34 SECONDS!) of actual arrival.....

Here's the data from the change-over of userHasArrivedAtWaypoint from 'false' to 'true' - as well as the actual arrival....
(using routeProgress = notification.userInfo![RouteControllerProgressDidChangeNotificationProgressKey] as! RouteProgress)

Last 'false' report
> 2017-11-25 08:47:01.751120-0500 ++++++++++ start ++++++++++++++
routeProgress.currentLegProgress.userHasArrivedAtWaypoint is  false
routeProgress.currentLegProgress.leg.distance is  915.1
routeProgress.currentLegProgress.leg.expectedTravelTime is  130.3
routeProgress.currentLegProgress.currentStepProgress.durationRemaining is  0.431063062536455
routeProgress.currentLegProgress.durationRemaining is  34.8310630625365
routeProgress.currentLegProgress.stepAfter(routeProgress.currentLegProgress.currentStep)! is  Turn right to stay on West 97th Place South
routeProgress.durationRemaining is  34.8310630625365
routeProgress.distanceRemaining is  118.135892375645
2017-11-25 08:47:01.751616-0500  ++++++++++ end ++++++++++++++

Turns to TRUE - though distanceRemaining and durationRemaining both clearly show NOT arrived!
> 2017-11-25 08:47:02.756083-0500  ++++++++++ start ++++++++++++++
routeProgress.currentLegProgress.userHasArrivedAtWaypoint is  true
routeProgress.currentLegProgress.leg.distance is  915.1
routeProgress.currentLegProgress.leg.expectedTravelTime is  130.3
routeProgress.currentLegProgress.currentStepProgress.durationRemaining is  34.4420247389889
routeProgress.currentLegProgress.durationRemaining is  34.4420247389889
routeProgress.currentLegProgress.stepAfter(routeProgress.currentLegProgress.currentStep)! is  You have arrived at your destination, on the right
routeProgress.durationRemaining is  34.4420247389889
routeProgress.distanceRemaining is  115.641100504454
2017-11-25 08:47:02.756689-0500  ++++++++++ end ++++++++++++++

The ride continues until the destination is actually reached...... - as predicted, 34 seconds LATER than the spoken instruction of 'Arrived'
> 2017-11-25 08:47:36.599214-0500  ++++++++++ start ++++++++++++++
routeProgress.currentLegProgress.userHasArrivedAtWaypoint is  true
routeProgress.currentLegProgress.leg.distance is  915.1
routeProgress.currentLegProgress.leg.expectedTravelTime is  130.3
routeProgress.currentLegProgress.currentStepProgress.durationRemaining is  0.0
routeProgress.currentLegProgress.durationRemaining is  0.0
routeProgress.currentLegProgress.stepAfter(routeProgress.currentLegProgress.currentStep)! is  You have arrived at your destination, on the right
routeProgress.durationRemaining is  0.0
routeProgress.distanceRemaining is  0.0
2017-11-25 08:47:36.599701-0500  ++++++++++ end ++++++++++++++

**Comment by ashishke2m** [comment]
Hi,
let me try for another location navigation simulation as I am using right now is not turning false to true.but let me try for another location simulation if it is or not.

**Comment by bsudekum** [comment]
Hi @ashishke2m, I'm going to look into this more today.

> Not sure why that went away, but after building a lot of my code around it (and now having to change it all.....) - only having the spoken 'arrived' seriously changes the feature set......... (other things like moving the buttons from the left to the right didn't help either..... - oh, well - that is what we have to live with when others develop the SDK! :)

@TCOA Just wanted to touch on this comment to give you some answers about the move. I understand your frustration with the large API change. We made the change because we are no longer creating spoken instructions and visual instructions on the client. This allows us to iterate faster and fix visual/spoken issues on the server instead of putting out a new release of navigation to fix a bug. This was a huge change to the library and I don't foresee any PRs coming down the line that will be this big of a shift. A roadmap for developers I think would be helpful so they can time their refactors a bit better. Here is rough list of things coming down the line:

* Swift 4 required in >= v0.11.0
* Using Visual instructions from the server https://github.com/mapbox/mapbox-navigation-ios/pull/767 (although a large fundamental change, the impact on the developer should be very low)

That's about it for now. I'll get started on a roadmap to make sure developers are kept in the loop on the direction of the library and any large changes coming down the line. Thanks for your flexibility and keeping up with our changes!

**Comment by bsudekum** [comment]
@ashishke2m FWIW, in the example app, I am getting the delegate method to fire:

![gif3](https://user-images.githubusercontent.com/1058624/33285379-f90ca4a0-d366-11e7-9465-68ab5f440f78.gif)

We're showing the confirmation modal when the arrival delegate is called. 

However, I will say that the arrival zone is relatively tight. This could be the underlying problem.

**Comment by TCOA** [comment]
@bsudekum,

Thanks for the response.  I would have liked to know more about the roadmap (certainly a pun in there somewhere!) although, in my case, it would not have changed things too much as I still am working out the final touches to get the app out - though having all the changes from the alert levels (that I had asked you guys about some time ago and implemented things around...) was extra work that I would rather have avoided (I wound up just tracking the route and putting them in myself, so not a massive thing, just that I liked the alert levels! :)

On the firing of "arrived", I think it is the route I have for my test - it has a corner just before the arrival and that is where "arrived" triggers (I can send the start/dest lat/lng privately if you need, though as it is a real person's house that I'm testing, I would rather not make it public...)

A quick question - from the new demo you are showing, it looks like this is a waypoint and now it says "arrived at destination"???  (before it was something like "arrived at the first destination" or something not useful for me....)  Does this mean that now we can use waypoint routes and the spoken (and visual) reaction will be as if it were two (or more) separate routes???  (that is one of my biggest problems - the waypoint method was 'ugly' before and I couldn't use it, so I'm trying to make multiple routes and clear the viewcontroller and speech... - I have the view and route working, but the spoken instructions are not clearing......)  If the new software makes waypoint routes act like singles, that would certainly be the right way for me to go!  (so, please say that's how it works! :)

**Comment by ashishke2m** [comment]
hi @bsudekum 

Thanks for your response but in some case, it is working fine for arrival but sometimes it is not why i don't know.
Maybe issues are because of sometimes I am not able to see "Blue Path Line" on map.this is the too worse issue.if we are using this SDK for Turn by Turn Navigation then it is not useful if it will not show a path on the map.
Can you please elaborate more on this issue?

**Comment by TCOA** [comment]
@ashishke2m 
I think the 'sometimes' arrival is because at those times you don't get the voice command - and it is a known issue that https://github.com/mapbox/mapbox-navigation-ios/pull/883 addresses.

I'm approaching it this way (and hopefully new upcoming changes won't affect it! :)

 
    let routeProgress = notification.userInfo![RouteControllerProgressDidChangeNotificationProgressKey] as! RouteProgress

                /*
                 0 = none
                 1 = depart
                 2 = after a maneuver
                 3 = 70 seconds out
                 4 = 15 seconds out
                 5 = arrive
                 */
                routeAlertLevel = 1
                if routeProgress.durationRemaining <= 70 {
                    routeAlertLevel = 3
                }
                if routeProgress.durationRemaining <= 15 {
                    routeAlertLevel = 4
                }
                if routeProgress.durationRemaining <= 5 {
                    routeAlertLevel = 5
                }
                if oldRouteAlertLevel != routeAlertLevel {
                switch routeAlertLevel {
                case 0:
                    print("route level 0 - do nothing")
                    break
                case 1:
                    print("route level 1 - departed")
                    break
                case 2:
                    print("route level 2 - finished a maneuver")
                    break
                case 3:
                    print("route level 3 - should be 70 seconds out")
                    break
                case 4:
                        print("route level 4 - should be 15 seconds out")
                    break
                case 5:
                    // ARRIVED
                    print("should have arrived at destination")
                    break
                default:
                    print("route level not found - hit DEFAULT")
                }

This way, I KNOW when my triggers are - and they come every time because they are monitoring the distance out from the destination. (NOTE: I made 'arrival' 5 seconds out so I can trigger another message - of course the 'real' arrival would be at 0 seconds, though we estimate times when the destination is not exactly where the vehicle can stop.  We figure 5 seconds 'close' is worthy for our needs.  Also, I did not put triggers for each 'alert' case {yet...} as some of them have no current interest for me.)

I don't know anything about 'not able to see "Blue Path Line" on map', but I hope the above code (or the referenced fix from mapbox, which I think is likely similar) helps you on the trigger issue.

**Comment by bsudekum** [comment]
> I think the 'sometimes' arrival is because at those times you don't get the voice command - and it is a known issue that #883 addresses.

Precisely. Now we're not waiting on announcement to trigger when the user arrives at a waypoint; it can happen independently as of #833.
