### ISSUE TITLE
Do not want Feedback and Sound Button On MapView in NavigationMapViewController

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-navigation-ios#878]

**Comment by frederoni** [comment]
`NavigationViewController.showsReportFeedback` lets you toggle the visibility of the feedback button, but the mute button is not exposed in the same way.

A convoluted workaround to hide the mute button in the meantime could look like:
```swift
let stackViews = navigationViewController.childViewControllers.first?.view.subviews.filter { $0 is UIStackView } as? [UIStackView]
let muteButton = stackViews?.last?.arrangedSubviews[1] as? Button
muteButton?.isHidden = true
```

**Comment by bsudekum** [comment]
@ashishke2m can you talk more about your use case here? Shouldn't users be allowed to enable/disable audio instructions on their own?

**Comment by ashishke2m** [comment]
Hi,
I just tried above code it is working like now I am not getting audio on/off button but I am getting "`Report FeedBack`" button when user doing `didRerouting` it is coming like animated button after "**Reroute loader**" went.

**Comment by Ankitkasia** [comment]
This work for me:
Pod -> MapBoxNavigation -> NavigationViewController.swift -> @objc public var showsReportFeedback: Bool = true {}
Just change true into false
