### ISSUE TITLE
Map doesn't follow user's movement

### ISSUE THREAD

**Issue by Ahmeddben** [mapbox/mapbox-navigation-ios#889]
I used mapView.userTrackingMode = .follow While it centers the map on user location when the map load or when a location button is pressed if the user moves the map doesn't move along with the user. How can I fix that?

Thanks

**Comment by frederoni** [comment]
Are you using the drop-in UI (`NavigationViewController`) or building your custom navigation with an `MGLMapView` or `NavigationMapView`? The NavigationMapView implements its own course tracking but doesn't expose everything publicly. For example the `NavigationMapView.tracksUserCourse` is an internal variable used by the `RouteMapViewController` to enable and disable course tracking.

**Comment by Ahmeddben** [comment]
I am not implementing any Navigation yet, I just want user to be able to follow where they are while moving and for that I want the map to move with the user so that users don't have to track their position by moving the map by hand

**Comment by frederoni** [comment]
Ok. You can either disable panning on the map view or conform to some of `MGLMapViewDelegate` methods. For example: `MGLMapViewDelegate.mapView(_:,regionDidChangeAnimated:)` is triggered when you pan the map. This could show a recenter button that sets `userTrackingMode` back to `.follow`.
