### ISSUE TITLE
Can't compile Example code - error: Missing Mapbox access token

### ISSUE THREAD

**Issue by TCOA** [mapbox/mapbox-navigation-ios#892]
Why does this have to be such a struggle???

1) followed instructions from https://github.com/mapbox/mapbox-navigation-ios#running-the-example-project
in building, had the same issue as #601 (changed to my personal team - obvious enough...)

However, after putting in my Token in Info.plist, I still get this error.....

> error: Missing Mapbox access token
error: Get an access token from <https://www.mapbox.com/studio/account/tokens/>, then create a new file at /Users/myuser/.mapbox that contains the access token. 

when I try to do that, this stupid Mac tells me "You can't use a name that begins with a dot ".", because these names are reserved for the system.  Please choose another name."

What now???

**Comment by frederoni** [comment]
We implemented an unversioned access token in #817 for security reasons.
There's most likely a setting in Finder that you need to enable to add files that begins with a dot.
However, using a terminal, you can just: `echo "YOUR_ACCESS_TOKEN" > ~/.mapbox`

We should clarify in the readme that this is the preferred way and perhaps also add support for the old way using the Info.plist.

**Comment by TCOA** [comment]
thanks @frederoni  - that worked to compile (sorry, I'm not a fan of Apple - - - actually, since they dropped support for the ][e/gs line - which was my first computer.... I've been forced to use this Mac, but, very sadly, it really isn't very intuitive, even after all these years....)

but, I get no map (just a dot on the screen - top and bottom seem ok). 
![screen shot 2017-11-28 at 8 15 31 am](https://user-images.githubusercontent.com/20958703/33321632-59634784-d414-11e7-8c37-5b7d8f71213c.png)

I can move the dot around, just no location stuff - even though I gave it permission for location and notifications

**Comment by TCOA** [comment]
retried the token (seems the last part didn't copy from the site the first time) - now I get the map and can finally start - again......

**Comment by TCOA** [comment]
trying pod install (again, after following the instructions........

> [!] Unable to satisfy the following requirements:

- `MapboxCoreNavigation (= 0.11.0-rc.1)` required by `MapboxNavigation (0.11.0-rc.1)`

None of your spec sources contain a spec satisfying the dependency: `MapboxCoreNavigation (= 0.11.0-rc.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Could you, please, provide instructions that work?  Even being around this 'a lot' in the last year, I'm by no means 'comfortable' with doing all these installs and upgrades.  And, instead of it being a somewhat pleasant experience (as best as doing upgrades/installs can be..), it is a struggle every time I mess with this SDK.........  

Sure would be great if the instructions were clear, complete (in a step-by-step fashion for those of us that don't live in SDKs...) - and worked.....

**Comment by TCOA** [comment]
trying 

    pod `MapboxCoreNavigation (= 0.11.0-rc.1)`

or even (guessing.... to make it more like others that work....)

     pod 'MapboxCoreNavigation', '~> 0.11.0-rc.1'

I get

> sh: -c: line 0: syntax error near unexpected token `='
sh: -c: line 0: `MapboxCoreNavigation (= 0.11.0-rc.1)'
Analyzing dependencies
Pre-downloading: `MapboxNavigation` from `https://github.com/mapbox/mapbox-navigation-ios.git`, tag `v0.11.0-rc.1`
[!] Unable to find a specification for ``

Trying

     pod 'MapboxCoreNavigation (= 0.11.0-rc.1)'

gives

    [!] Unable to find a specification for `MapboxCoreNavigation (= 0.11.0-rc.1)`

**Comment by frederoni** [comment]
> pod 'MapboxCoreNavigation', '~> 0.11.0-rc.1'

AFAIK, the tadpole operator only works for actual releases, this is a release candidate.

0.11.0-rc.1 was never published to the CocoaPods public repository so you'd have to specify the full git url including the tag:
```ruby
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v0.11.0-rc.1'
```

or just:
```ruby
pod 'MapboxCoreNavigation'
```

to get the latest. Also note that update/install doesn't necessarily sync with the public repo. To make sure you'll get the latest and greatest, run `pod repo update` before updating.

**Comment by TCOA** [comment]
@frederoni - thanks!  That at least got the pod errors gone (though now crashing at 
`mapView.navigationMapDelegate = self`
with 

> Thread 1: EXC_BAD_ACCESS (code=2, address=0x1b4028ec8)

..... using the example code in my new build (I'll hopefully figure that - and other issues out soon - I'm supposed to be delivering this app by the 1st......)

Anyway, that info about where to find MapboxCoreNavigation certainly would be a great thing to add to the installation instructions..... https://github.com/mapbox/mapbox-navigation-ios#installation - I tried probably 20 combinations of everything I could think of, but didn't think the CoreNavigation would be in the same place......

(BTW, just using pod 'MapboxCoreNavigation' by itself doesn't work (it was one of the things I tried...) - a different error message comes up that I don't have a need to go look at now....)

I'm just trying to get a 'latest "supported" version' so I can start the rebuild on my app - sure wish there was a 'stable release' version somewhere so I wouldn't have to constantly rework things, but I am looking forward to fewer major changes in the foreseeable future.

At least, now, I can start - again......

**Comment by 1ec5** [comment]
> when I try to do that, this stupid Mac tells me "You can't use a name that begins with a dot ".", because these names are reserved for the system. Please choose another name."

> We should clarify in the readme that this is the preferred way and perhaps also add support for the old way using the Info.plist.

In #902, I made the error a warning, for those who are comfortable putting their access token directly in the Info.plist, and provided for “mapbox” as an alternative to “.mapbox”.
