### ISSUE TITLE
distanceLabel is Invisible in iphoneX

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#898]
Hi, guys 
I am using 0.10, distanceLabel is Invisible in iphoneX.
![img_0023](https://user-images.githubusercontent.com/10751092/33343877-815aad30-d44c-11e7-8e7d-e44cbeb20eee.PNG)

after I updated to 0.10.1, a few errors came out. using swift 3.2

![snip20171128_2](https://user-images.githubusercontent.com/10751092/33343995-fcd91cd0-d44c-11e7-936e-3fb86b1ebfb7.png)

**Comment by frederoni** [comment]
Thanks for reaching out.

I'm unable to reproduce the issue:
<img src="https://user-images.githubusercontent.com/764476/33376750-32790afe-d50f-11e7-990f-3ba0660ab7f7.png" width=200>

However, it looks like you're using a combination of language and region we haven't tested.
Is that simplified Chinese with US regional settings?

MapboxNavigation and MapboxCoreNavigation must be built with Swift 4 as of 0.10.1 but your application target can be using Swift 3.2. Are you integrating the framework using CocoaPods or Carthage? CocoaPods is still ironing out some issues related to multiple Swift versions but it seems to be working in the latest beta.

**Comment by zijiazhai** [comment]
Thank you for your help! 
Yes, that is simplified Chinese with US regional setting.
