### ISSUE TITLE
Conversion problem in OSRMTextInstructions when building

### ISSUE THREAD

**Issue by jojonarte** [mapbox/mapbox-navigation-ios#903]
![screen shot 2017-11-30 at 12 00 59 pm](https://user-images.githubusercontent.com/11880365/33412429-3353902c-d5c6-11e7-8162-7208209fc786.png)

**Comment by bsudekum** [comment]
This library now requires swift 4. It looks like from your screenshot that you are running Swift 3. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jojonarte** [comment]
It's 3.2. I was using the suggested v0.10.1 which is what's in the Readme file that says it is the last supported version for Swift 3.2.

**Comment by bsudekum** [comment]
Ah interesting. Can you check out your Podfile.lock and see what version of OSRMTextInstructions was installed?

**Comment by jojonarte** [comment]
The OSRMTextInstructions installed was version (0.6.0)

**Comment by sbatururimi** [comment]
@bsudekum We are facing the same problem. Any update on this?

**Comment by 1ec5** [comment]
#925 removes the dependency on OSRM Text Instructions. (Nowadays, localized guidance instructions are included in the Directions API response.) The build problems should go away with the next release of the navigation SDK. In the meantime, you can point your Podfile to the master branch.
