### ISSUE TITLE
How to change regionType of PollyVoiceController at (Or after) initialisation?

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#913]
Hello!, I've been trying to implement the PollyVoiceController using a different region than .USEast1 (Which is default)

I've attempted to override the default service configuration of AWS but to no avail. The only thing that works is initializing the AWSService before the VoiceController. Otherwise, setting the regionType does nothing.

This is the only way that I've found it to work, but seems a bit hacky.
```swift
let credentialProvider = AWSCognitoCredentialsProvider(regionType: .EUWest1, identityPoolId: amazonPollyPoolId)
let configuration = AWSServiceConfiguration(region: .EUWest1, credentialsProvider: credentialProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration

let pollyVoiceController = PollyVoiceController(identityPoolId: amazonPollyPoolId)
pollyVoiceController.regionType = .EUWest1
pollyVoiceController.voiceControllerDelegate = self
```

I submitted #914 which fixes the issue. Another way would be for the variable to be static, or initializing PollyVoiceController with a AWS configuration

Thanks!

**Comment by bsudekum** [comment]
Totally reasonable request @Sealos, will PR now.
