### ISSUE TITLE
End Of Route Label Geocoding issues

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#921]
@1ec5 has reported that the destination name label on the EORVC is misbehaving. He saw that the label would always either show OSRM names or coordinate pairs. This suggests a problem with the `CLGeocoder` implementation.

The expected order of precedence is: 
`Manually Set Name` ➡️ `OSRM Name` ➡️ `CLGeocoder Name` ➡️ `"You Have Arrived"`

To Do: 
- [x] Investigate `CLGeocoder` failure
- [x] Change coordinate Pair to "You Have Arrived" and hide static label in this case

/cc @bsudekum @frederoni @ericrwolfe

**Comment by ericrwolfe** [comment]
@JThramer Let's remove the fallback to the coordinate pair, and instead just show "You have arrived" in larger text instead of showing the smaller label.

**Comment by bsudekum** [comment]
This is dependent on https://github.com/mapbox/MapboxDirections.swift/pull/222.

**Comment by 1ec5** [comment]
Fixed in #922.
