### ISSUE TITLE
Avoid embedding dependencies in framework targets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#927]
MapboxNavigation.framework embeds all its dependencies, so an application target’s build phase only needs to directly embed MapboxNavigation.framework and MapboxCoreNavigation.framework, but nothing else. (If MapboxNavigation.framework were to additionally embed MapboxCoreNavigation.framework, then the application target would only need to embed MapboxNavigation.framework alone.)

While this approach simplifies setup, it runs counter to the best practice of [linking frameworks together at the application target level](https://developer.apple.com/library/content/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-PROJ_CONFIG-APPS_WITH_DEPENDENCIES_BETWEEN_FRAMEWORKS). For example, if the application also depends on the map SDK, then things get a bit awkward because a developer would expect to have to embed Mapbox.framework directly, which would lead to two copies of Mapbox.framework in the resulting application bundle. The iTunes Store rejects application submissions with duplicate frameworks.

As far as I can tell, the Swift and Objective-C example applications should embed all the dependencies directly, leaving MapboxNavigation.framework and MapboxCoreNavigation.framework to link their respective dependencies but not embed them.

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/804#issuecomment-350819048
/cc @frederoni @bsudekum @LuAndreCast

**Comment by 1ec5** [comment]
Do we need to make a similar change to MapboxDirections.swift, which pulls in Polyline?

**Comment by frederoni** [comment]
MapboxDirections.swift doesn't embed Polyline in its own framework.
