### ISSUE TITLE
Separate example applications from this repository

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#932]
We should create a new set of mini example applications that live in a separate repository. Each application would be a separate target in the same Xcode project that shows off a single way of integrating the SDK: one for very basic integration, another that allows the user to specify multiple waypoints, and another that sports a custom turn-by-turn navigation UI. Maybe a watchOS application that depends on Core Navigation too (#305).

The existing example applications, particularly the Swift one, have grown into a menagerie of options and UI elements. While they’re perfectly appropriate as a way to exercise all the functionality in this SDK during development, they aren’t focused enough to introduce developers to the SDK, to show them how they would realistically get started with the SDK. For one thing, as the SDK’s public API remains in flux, it’s too easy for a developer to base their work on master, only to realize they should be using a more stable release with a different feature set or APIs.

Meanwhile, this repository would retain its Swift and Objective-C applications to serve as testbeds – to avoid breaking key features and obscure options alike as we develop features, and to ensure adequate Objective-C bridging. So I don’t expect that we’d often need to set up mapbox-navigation-ios-examples with local podspec paths to develop the SDK.

## Separate targets or view controllers?

As an alternative to many mini application targets, if we’re sure each example would only need a single view controller, then each of the Swift example view controllers could live in the same target. A table view controller would select among them at runtime.

Think of a monolithic application as the navigation SDK’s answer to [ios-sdk-examples](https://github.com/mapbox/ios-sdk-examples/). In fact, it could even live in that repository, off in its own folder. This approach would be much more difficult to build off of than separate applications. On the bright side, a script could transclude the contents of each Swift or Objective-C file into Markdown files to be packaged up as [jazzy guides](https://www.mapbox.com/mapbox-navigation-ios/navigation/0.11.0/Guides.html) and eventually live on a dedicated example site like [the map SDK’s](https://www.mapbox.com/ios-sdk/examples/).

/ref https://github.com/mapbox/mapbox-navigation-ios/pull/804#issuecomment-342675785
/cc @mapbox/navigation-ios @captainbarbosa @friedbunny

**Comment by bsudekum** [comment]
We now have https://github.com/mapbox/navigation-ios-examples, can we close this out?

**Comment by 1ec5** [comment]
Yep, that’s exactly what this issue called for. #1113 deemphasized the Swift and Objective-C test applications in this repository in favor of those examples. The last step would be to move the steps to run those applications from [the readme](https://github.com/mapbox/mapbox-navigation-ios/blob/b381563387262b408dfe1939883c813bd616654b/README.md#examples) to the contributing guide.
