### ISSUE TITLE
Spoken instructions should automatically match the route response’s locale

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#933]
PollyVoiceController and RouteVoiceController both use `Locale.preferredLocalLanguageCountryCode` to choose the speech synthesis voice. This is usually correct, but if the developer has customized the route response’s locale by setting `RouteOptions.locale`, then instructions written in one language could potentially be read aloud in a different language, probably to humorous effect. Instead, the voice controllers should get their locales from `RouteOptions.locale`, which will help to ensure a matching language.

https://github.com/mapbox/mapbox-navigation-ios/blob/49d8d3e9014bd97fb6fadee7703cfae888d003a3/MapboxNavigation/RouteVoiceController.swift#L230
https://github.com/mapbox/mapbox-navigation-ios/blob/49d8d3e9014bd97fb6fadee7703cfae888d003a3/MapboxNavigation/PollyVoiceController.swift#L92

/cc @bsudekum @ericrwolfe

**Comment by 1ec5** [comment]
#617 is replacing PollyVoiceController with MapboxVoiceController, which will correctly match the route response’s locale.

**Comment by bsudekum** [comment]
@1ec5 is it worth fixing this while we work on https://github.com/mapbox/mapbox-navigation-ios/pull/617?

**Comment by bsudekum** [comment]
Done in https://github.com/mapbox/mapbox-navigation-ios/pull/617/commits/1a161fd5a59d0b9cbd9c3c5423da27eee832dcd1

**Comment by bsudekum** [comment]
This is was added in https://github.com/mapbox/mapbox-navigation-ios/pull/617
