### ISSUE TITLE
NavigationMapViewDelegate is undocumented

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#934]
`NavigationMapViewDelegate` is completely undocumented, so it doesn’t show up in the jazzy docset.

/cc @bsudekum @captainbarbosa

**Comment by 1ec5** [comment]
For some reason we’ve been documenting some of these methods in the Swift example project instead of the SDK:

https://github.com/mapbox/mapbox-navigation-ios/blob/0eb0f675f5b763e61c5fe276d3b35c41635ccc07/Examples/Swift/ViewController.swift#L355-L358

Now that we’ve got a separate project for navigation SDK examples, we shouldn’t expect a developer to ever see the Swift example application’s source code, let alone find comments such as this one.

/cc @JThramer

**Comment by frederoni** [comment]
Fixed in #1024
