### ISSUE TITLE
Can't find how o set the unitType in my Navigation

### ISSUE THREAD

**Issue by Halpph** [mapbox/mapbox-navigation-ios#946]
Before last commitments i used
 `NavigationViewOptions options = NavigationViewOptions.builder()
                .origin(getOrigin())
                .destination(getDestination())
                .awsPoolId(null)
                //.unitType(NavigationUnitType.TYPE_METRIC)
                .shouldSimulateRoute(false)
                .build();`
but now the `//.unitType(NavigationUnitType.TYPE_METRIC)` is not present in the Class.
How can i set the unit Type in metrical instead of Imperial?

**Comment by JThramer** [comment]
Hi @Halpph,

It looks like you may of posted your question in this repository by mistake. From a quick look at your code, you are probably looking for https://github.com/mapbox/mapbox-navigation-android.

Please let us know if this is not the case.

**Comment by Halpph** [comment]
Yes, sorry man :(

**Comment by JThramer** [comment]
No problem at all 😁
