### ISSUE TITLE
There isn't Instruction view insteand of Navigation view

### ISSUE THREAD

**Issue by MadBurea** [mapbox/mapbox-navigation-ios#955]
Hi  there,

I am Presenting navigation view like this

```
 MBNavigationViewController *cont = [[MBNavigationViewController alloc]initWithRoute:route directions:[MBDirections sharedDirections] style:nil locationManager:mbLocationManager];
[self presentViewController:cont animated:YES completion:nil]; 
```

Now This works well as it present Navigation Controller with moving Turn by turn instructions.

I want only instruction view that is on the top of navigation view what should i do to accomplish that.

is this functionality is there in iOS as i can see this in android.

**Comment by frederoni** [comment]
> is this functionality is there in iOS as i can see this in android.

Yes, you can mix and match various components.
The two components you refer to is `MBNavigationMapView` and `MBInstructionsBannerView`.
Please feel free to use them however you want in your custom view.
