### ISSUE TITLE
MBRouteStep - Missing swift Properties

### ISSUE THREAD

**Issue by Ovianet** [mapbox/mapbox-navigation-ios#961]
Hi !

I've got an issue with using the MBRouteStep class (RouteStep in Swift).

In the documentation and in the swift example, it's shown that it's possible to access to the following properties : 

- maneuverType
- maneuverDirection

But when i try to access it from Objective-C, this properties are not available.

I'm using the latest version of each frameworks and here are my includes : 

`@import MapboxCoreNavigation;`
`@import MapboxDirections;`
`@import MapboxNavigation;`
`@import Mapbox;`

Thanks in advance for your help.

**Comment by 1ec5** [comment]
Tracking this issue upstream in mapbox/MapboxDirections.swift#117.

/cc @frederoni

**Comment by frederoni** [comment]
Fixed in https://github.com/mapbox/MapboxDirections.swift/pull/227
