### ISSUE TITLE
Progress bar never reaches the end

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#97]

**Comment by frederoni** [comment]
The progress bar will reach the end when we get a progress update and `routeProgress.fractionTraveled` returns 1.0. However, I guess it's very unlikely that we end up exactly on the destination. What is the logic for firing the "You've reached your destination" notification? We should probably override the progress and set it to 1.0 if the maneuver type is `.arrive` and the user is within ~20 meters?
