### ISSUE TITLE
Can we remove our dependency on SDWebImage?

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#978]
We do not really use it for that much other than fetching, unpacking and caching image data. Is this something we can do on our own and remove the need for this dependency?

/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
Per conversation, SDWebImage does cache downloaded images on disk. If we used a simple NSCache, we'd only be storing images in memory and thus we'd have to make a few more network requests.

**Comment by 1ec5** [comment]
If the size of SDWebImage becomes a problem and we continue to use only a small slice of its functionality, it may be possible to replace it with a smaller library.

**Comment by bsudekum** [comment]
Keeping for now.
