### ISSUE TITLE
How to reroute in mapbox navigation swift?

### ISSUE THREAD

**Issue by AndreiOpanasenko** [mapbox/mapbox-navigation-ios#980]
Hello, 

I am working with mapbox navigation.

mapbox navigation function is great.

But, I have some issues now.

It is how to reroute map navigation.

I am working with multi waypoints(5 coordinates)

I can't get routes from 5 waypoints.

So I were going to implement rerouting function.

But it don't works now.

Would you please let me know the solution?

Best regards

Andrei

**Comment by frederoni** [comment]
Thank you for the report.

The `NavigationViewController` will ask its delegate before rerouting.
You could return false there and use your own rerouting-mechanism.

```swift
func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {
    // Gather remaining waypoints
    // Request route from current location (using remaining waypoints)
    // Call `navigationViewController.route = fetchedRoute`
    return false
}
```

After a second thought, this library already takes waypoints into account when rerouting.
![reroute](https://user-images.githubusercontent.com/764476/34673039-2f61759a-f481-11e7-88cd-48b14d8abf48.gif)

What exactly happens in your case when the reroute occurs? Does all or a few waypoints disappear? No reroute at all?

 /cc @bsudekum

**Comment by AndreiOpanasenko** [comment]
Hello, frederoni 

Thanks,

My problem is to get routes for multi waypoints in map navigation.

But, I can't get routes.

SDK said that maximum waypoints number is 3.

But my waypoints number is 6

So I were going to use rerouting in map navigation.

Sorry, I can't this method is true or not.

I am sorry, I would like you to show some code for rerouting.

Best regards

Andrei

**Comment by AndreiOpanasenko** [comment]
I get some codes from googling.

var navigation: RouteController!
navigation.routeProgress = RouteProgress(route: newRoute)

I have to use this code when fetched reroute event.

Where can i implement above codes?

**Comment by AndreiOpanasenko** [comment]
Do you have sample project for rerouting in mapbox navigation?

I would be thankful if you can show sample project to me.

Best regards

Andrei

**Comment by frederoni** [comment]
You're correct that the `driving-traffic` profile currently [supports 3 waypoints](https://www.mapbox.com/api-documentation/#directions). Please consider using a different profile or [contact our support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you.

**Comment by AndreiOpanasenko** [comment]
Hello, Fredrik

I am not receiving navigation view controller delegate method(....
didArrive At waypoint()).

Do you have any solution?

Best regards

Andrei

**Comment by PreetOceans** [comment]
Hello,
I am facing the same issue ..
I am not receiving navigation view controller delegate method

I did this steps
1.  MBNavigationViewControllerDelegate
2. MBNavigationViewController *controller = [[MBNavigationViewController alloc] initWithRoute:_route styles:nil navigationService:mbservice voiceController:nil];
    controller.delegate = self;

3. implements this method
- (BOOL)navigationViewController:(MBNavigationViewController *)navigationViewController shouldRerouteFromLocation:(CLLocation *)location
{
    return NO;
}

but this method is not call.

Plz give me reply as soon as possible.
