### ISSUE TITLE
Handling multiple annotations selected

### ISSUE THREAD

**Issue by Niduank** [mapbox/mapbox-navigation-ios#983]
Hi,

I added polyline with MGLPolylineFeature as annotation (to customize polyline color).
Then I added a MGLPointAnnotation to add a marker.

This marker is over the polyline previously added.
When I select the MGLPointAnnotation, MGLNavigationMapView handle annotationSelected only for the polyline not for the marker.
I displayed [mapView selectedAnnotations] which only contains instance of MGLPolylineFeature.

How can I handle click on MGLPointAnnotation when this one is over another annotation ?

Thanks

**Comment by bsudekum** [comment]
It should be able to handle overlapping elements. Can you make sure you are setting `mapView.delegate = self`?

**Comment by Niduank** [comment]
Sure I am !

`func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation)` is called when I select annotation.

But when a MGLPointAnnotation is on top of MGLPolylineFeature and I select this MGLPointAnnotation, callback of mapview is called with MGLPolylineFeature in argument.

**Comment by ohelli** [comment]
I have the same issue: The callback via
`func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation)` also only selects the poly line, even thought there is another annotation directly at that touch point. In addition, the poly line is selected very inexactly, meaning even if the touch is next to the line up to 40 - 50 pixels.

**Comment by JPSiller** [comment]
Same issue here. Is there a way to disable user interaction with certain types of annotations or add a z-index to make sure the point annotation is selected instead of the polyline?
