### ISSUE TITLE
Expose currentLegAttribute

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#987]
https://github.com/mapbox/mapbox-navigation-ios/blob/06d5bc708e4079df25187eb56e43b7954222352a/MapboxNavigation/NavigationMapView.swift#L62

It's difficult to style non-active legs without knowing this string. Ref implementation: 
https://github.com/mapbox/mapbox-navigation-ios/blob/06d5bc708e4079df25187eb56e43b7954222352a/MapboxNavigation/NavigationMapView.swift#L931-L934

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Can NavigationMapView expose a more targeted way of styling legs based on whether they’re active?
