### ISSUE TITLE
Is it possible to navigate for large vehicle on mapbox swift?

### ISSUE THREAD

**Issue by AndreiOpanasenko** [mapbox/mapbox-navigation-ios#997]
Hello, Mapbox team!

I am working with mapbox navigation on my project.
it works well now.

But, I have very important problem.
Because it is large vehicle.
So the routes that supported on navigation map view is not the route correctly.

Is it possible mapbox navigation for large vehicle on swift?

Best regards

Andrei

**Comment by bsudekum** [comment]
Hi @AndreiOpanasenko,

Currently, the [Mapbox Directions API only supports](https://www.mapbox.com/api-documentation/#directions) the following 4 routing types:

* `mapbox/driving-traffic` for automotive routing. This profile factors in current and historic traffic conditions to avoid slowdowns. Traffic is available in these supported geographies
* `mapbox/driving` for automotive routing. This profile shows the fastest routes by preferring high-speed roads, like highways.
* `mapbox/walking` for pedestrian and hiking routing. This profile shows the shortest path by using sidewalks and trails.
* `mapbox/cycling` for bicycle routing. This profile shows routes that are short and safer for cyclists by avoiding highways and preferring streets with bike lanes.

Other routing profiles are on our roadmap, but we have no ETA as to when these (if ever) will land.

**Comment by AndreiOpanasenko** [comment]
Hello, Bobby

I see

Thanks for your helping!

Best regards

Andrei

**Comment by AndreiOpanasenko** [comment]
I am sorry, May i ask one question?

I am using mapbox rerouting function.

when user get every waypoint, I have to calculate new route for rerouting.

But, unfortunately, navigation controller delegate method(....didarriveAt
waypoint: Waypoint) don't be called now.

I think that I am missing some rules on mapbox navigation for rerouting.

Would you please let me know any solution?

Best regards

Andrei

On Wed, Jan 10, 2018 at 10:40 PM, Андрей Опанасенко <opanasenkoupw@gmail.com
