### ISSUE TITLE
Editing of mapbox navigation buttons 

### ISSUE THREAD

**Issue by eyosgithub** [mapbox/mapbox-navigation-ios#998]
is there any way the buttons on the navigation system for Mapbox can be readjusted or disabled?

![img_5726](https://user-images.githubusercontent.com/24883928/34801168-2fd177e0-f635-11e7-9683-9126718169fb.JPG)

**Comment by frederoni** [comment]
We will make these components public in an upcoming release. In the meantime, you can use this workaround:

```swift
let stackViews = navigationViewController.childViewControllers.first?.view.subviews.filter { $0 is UIStackView } as? [UIStackView]
let muteButton = stackViews?.last?.arrangedSubviews[1] as? Button
muteButton?.isHidden = true
```

**Comment by eyosgithub** [comment]
This was very helpful
