### ISSUE TITLE
Unable to build project when working with Objective-C

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-navigation-ios#999]
**Xcode version:** 9.2 beta (9C34b), 9.2 (9C40b)
**Navigation SDK version:** 0.12.1
**CocoaPods version:** 1.3.1

Creating a new project that includes MapboxNavigation as the only dependency results in the following errors:

![screenshot 2018-01-10 13 49 52](https://user-images.githubusercontent.com/10850812/34789664-2b0f6f50-f60d-11e7-9dfd-78c424a2981a.png)

<details>
<summary>ViewController.m</summary>

```objc
#import "ViewController.h"
@import Mapbox;
@import MapboxCoreNavigation;
@import MapboxNavigation;
@import MapboxDirections;

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


@end
```
</details>

<details>
<summary>Podfile.lock</summary>

```
PODS:
  - AWSCore (2.6.10)
  - AWSPolly (2.6.10):
    - AWSCore (= 2.6.10)
  - Mapbox-iOS-SDK (3.7.2)
  - MapboxCoreNavigation (0.12.1):
    - MapboxDirections.swift (~> 0.15)
    - MapboxMobileEvents (~> 0.2)
    - Turf (~> 0.0.4)
  - MapboxDirections.swift (0.15.1):
    - Polyline (~> 4.2)
  - MapboxMobileEvents (0.2.10)
  - MapboxNavigation (0.12.1):
    - AWSPolly (~> 2.6)
    - Mapbox-iOS-SDK (~> 3.6)
    - MapboxCoreNavigation (= 0.12.1)
    - SDWebImage (~> 4.1)
    - Solar (~> 2.1)
    - Turf (~> 0.0.4)
  - Polyline (4.2.0)
  - SDWebImage (4.2.3):
    - SDWebImage/Core (= 4.2.3)
  - SDWebImage/Core (4.2.3)
  - Solar (2.1.0)
  - Turf (0.0.4)

DEPENDENCIES:
  - MapboxNavigation (~> 0.12)

SPEC CHECKSUMS:
  AWSCore: 5bb072a6b5b185f43ddbd239d6554d2f8a285ad2
  AWSPolly: 2e06b395db6176f6edc8ce6cd3379c46c1bccb44
  Mapbox-iOS-SDK: d882f53debc26649b728755df5b7a160d9086367
  MapboxCoreNavigation: d35ac3c11d9d3ea852823822752922ea34d82104
  MapboxDirections.swift: 2ed0a698a7721b5373362b74579c7194cda12528
  MapboxMobileEvents: 9e48b59d0eed04508595dcb04a77b7632e1c3054
  MapboxNavigation: a3307bbd66fcbe6c5ef50f2a6419c6d2f4d2de07
  Polyline: 3d69f75bb136357e27291d439d0436c6ebda57a4
  SDWebImage: 791bb72962b3492327ddcac4b1880bd1b5458431
  Solar: 2dc6e7cc39186cb0c8228fa08df76fb50c7d8f24
  Turf: 6c169618fa671e3f8a7b764b5b3332053ad6110e

PODFILE CHECKSUM: b9e3c0186cda397757f48de9db7c0363d4b26569

COCOAPODS: 1.3.1
```
</details>

**Comment by 1ec5** [comment]
Are you using the new build system?

**Comment by dredful** [comment]
We are seieing these same issues. 

Here are the Mapbox pod versions installed:

Installing Mapbox-iOS-SDK (3.7.3)
Installing MapboxCoreNavigation (0.12.1)
Installing MapboxDirections.swift (0.15.1)
Installing MapboxGeocoder.swift (0.7.0)
Installing MapboxMobileEvents (0.2.10)
Installing MapboxNavigation (0.12.1)

The MapboxNavigation Objective C app won’t build either.

**Comment by frederoni** [comment]
This should be fixed in CocoaPods 1.4 which is currently in rc.

In the meantime, you can set the Swift version manually:
<img width="654" alt="screenshot 2018-01-15 14 33 01" src="https://user-images.githubusercontent.com/764476/34944907-a896761a-fa01-11e7-9f0f-b9c79691533c.png">
_this will get overridden when you run `pod install/update`_

a more persistent way would be to put this at the bottom of your Podfile:
```ruby
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
end
```

**Comment by bsudekum** [comment]
Cool, perhaps we should update the readme with this requirement.

**Comment by captainbarbosa** [comment]
I can confirm updating to the `1.4.0.rc.1` version of CocoaPods and defining the `SWIFT_VERSION` in the `Pods` build settings as @frederoni described worked successfully 👍

**Comment by bsudekum** [comment]
@dredful can you upgrading your version of cocoapods to `1.4.0.rc.1`?

**Comment by dredful** [comment]
@bsudekum, updating the SWIFT version to 4.0 on all the Mapbox PODS in our project appeared to solve our issue. I will look into updating to the `1.4.0.rc.1` version of CocoaPods.

Thanks!
